### ISSUE TITLE
fmpeg build failed with mysofa

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#1007]
[logs.zip](https://0x0.st/sRO6.zip)

**Comment by schmidthubert** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/commit/b3d57e536015298dad59445d1d0ef241beb44b96
https://github.com/jb-alvarado/media-autobuild_suite/blob/master/doc/forcing-recompilations.md#libraries-not-using-pkg-config

**Comment by Selur** [comment]
that helped
Thanks!

**Comment by Selur** [comment]
libmysofa not found, see: [logs.zip](https://0x0.st/iZBJ.zip) 
deleting the libmysofa.a files and the ffmpeg-git folder did not help either.

**Comment by 1480c1** [comment]
Your mysofa build contains Code coverage stuff, don't know what's introducing it, will check soon

**Comment by 1480c1** [comment]
I'm able to reproduce now

**Comment by 1480c1** [comment]
Latest mysofa commit set code coverage as default, try rebuild

**Comment by Selur** [comment]
Works fine now, thanks!
