### ISSUE TITLE
x64 build failure: perl.exe: entry point clearenv could not be located msys-perl5_28.dll

### ISSUE THREAD

**Issue by rustyx** [m-ab-s/media-autobuild_suite#1130]
Just tried to build x64 static ffmpeg, unsuccessfully.

During installing MSYS there were a few "unknown trust" issues like this:

```
error: abrepo: key "EFD16019AE4FF531" is unknown
:: Import PGP key 4096R/CB391133DF0BD5BC6AA32CFFEFD16019AE4FF531, "Ricardo Constantino <wiiaboo@gmail.com>", created: 2015-11-05? [Y/n]
error: abrepo: signature from "Ricardo Constantino <wiiaboo@gmail.com>" is unknown trust
error: failed to update abrepo (invalid or corrupted database (PGP signature))
```

The build subsequently failed on **freetype2**:

```
./autogen.sh 
./autogen.sh: line 55: test: 1: unary operator expected
./autogen.sh: line 59: test: 1: unary operator expected
./autogen.sh: line 67: test: 10: unary operator expected
./autogen.sh: line 71: test: 10: unary operator expected
generating `configure.ac'
running `aclocal -I . --force'
error while running `aclocal -I . --force'
```

Full build log: https://0x0.st/zH9Q.zip

After some digging I saw that Perl doesn't work:

**perl.exe - Entry Point Not Found
The procedure entry point clearenv could not be located in the dynamic link library msys-perl5_28.dll**

However, **reinstalling the key and perl didn't help**:

```
$ pacman-key --lsign AE4FF531
  -> Locally signing key AE4FF531...
==> Updating trust database...
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   5  signed:   3  trust: 1-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
$ pacman -S --force perl git gawk
warning: perl-5.28.1-2 is up to date -- reinstalling
warning: git-2.21.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (3) gawk-4.2.1-2  git-2.21.0-1  perl-5.28.1-2

Total Download Size:    1.03 MiB
Total Installed Size:  85.53 MiB
Net Upgrade Size:       0.13 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 gawk-4.2.1-2-x86_64                           1050.3 KiB   369K/s 00:03 [#######################################] 100%
(3/3) checking keys in keyring                                           [#######################################] 100%
(3/3) checking package integrity                                         [#######################################] 100%
(3/3) loading package files                                              [#######################################] 100%
(3/3) checking for file conflicts                                        [#######################################] 100%
(3/3) checking available disk space                                      [#######################################] 100%
:: Processing package changes...
(1/3) reinstalling perl                                                  [#######################################] 100%
(2/3) reinstalling git                                                   [#######################################] 100%
(3/3) upgrading gawk                                                     [#######################################] 100%
$ perl --version
$
```
Same issue:
**perl.exe - Entry Point Not Found
The procedure entry point clearenv could not be located in the dynamic link library msys-perl5_28.dll**

What am I missing? How to resolve this?

**Comment by wiiaboo** [comment]
Seems like a broken perl. Try uninstalling it `pacman -Rd perl` and then installing it again `pacman -S perl`. If it still doesn't work, maybe try asking in https://github.com/msys2/MSYS2-packages/issues.
It's working fine on my side.

**Comment by rustyx** [comment]
Reinstalling perl (and even the entire thing) didn't help. What helped was installing MSYS2 separately and copying over **msys-2.0.dll**.
But first I had to kill two instances of **gpg-agent.exe**, which were holding it open (maybe that was the reason it didn't update in the first place).
The PGP key setup can definitely be improved. Maybe add a retry for key retrieval?
And is the agent needed? If not, maybe it should be disabled (put `no-use-agent` in `gpg.conf`).

**Comment by 1480c1** [comment]
It would be nice to add a retry for key, however problem comes when pool.sks-keyservers.com is the problem and when it should stop trying. I've had multiple instances where the mirror link doesn't work but the mirrors themselves work.

The gpg-agent probably can probably be disabled since from my use, I only know of signing that uses the gpg-agent agent. Although I think pacman-key might use it, may need more testing.
Try disabling gpg agent and running pacman -Syyu to see if it will update without gpg-agent (after making sure there isn't any running)

**Comment by wiiaboo** [comment]
https://github.com/msys2/MSYS2-packages/issues/1611
