### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by Schokn-Itrch** [m-ab-s/media-autobuild_suite#1201]
log - https://0x0.st/zTvR.zip

**Comment by 1480c1** [comment]
Possibly related: https://github.com/jb-alvarado/media-autobuild_suite/issues/1101

**Comment by Schokn-Itrch** [comment]
No. I have 8.1x64.

**Comment by 1480c1** [comment]
No, I mean i686(32 bit) rust compilation. Rust seems to have some problems on 32-bit(?)
