### ISSUE TITLE
Does ffmpeg ever appear to freeze?

### ISSUE THREAD

**Issue by GyanD** [m-ab-s/media-autobuild_suite#1259]
Edit: See new post. This is due to winpthreads, not curses library.
----
For the past 3 weeks or so, ffmpeg appears to get stuck once every few runs.
This happens when ffmpeg is run inside Cmder or mintty, but it hasn't happened when run directly in cmd.  This is on Windows 7 SP1.

AFAICT, ffmpeg appears to be waiting for keyboard input. but doesn't receive any keypresses. The main transcode loop is still running and one can still exit with three Ctrl+C presses.

This is not directly related to the suite as it happens with ffmpeg compiled standalone in a separate MSYS2 installation. It has not happened with Zeranoe builds.

I believe the change may be related to the replacement of the curses lib in MSYS2 from ncurses to pdcurses at around the same time. See details at https://github.com/msys2/MINGW-packages/issues/5437#issuecomment-503131637

Has anyone else experienced this?

**Comment by wiiaboo** [comment]
Have you tried running with `winpty ffmpeg`?

**Comment by moisesmcardona** [comment]
I've seen this behavior but only when my CPU is at 100% utilization. Not using any of the tools you mentioned, but rather using ffmpeg in my own software GUIs which simply launch it as a standard process with arguments.

**Comment by Norwelian** [comment]
> I've seen this behavior but only when my CPU is at 100% utilization. Not using any of the tools you mentioned, but rather using ffmpeg in my own software GUIs which simply launch it as a standard process with arguments.

Exactly this happens to me at times.

**Comment by GyanD** [comment]
After running a series of tests, the issue only occurs with multi-threaded video decoding on Windows 7. Switching to single-threaded avoids it (almost) completely. 

This is due to the (lib)winpthreads library, which was upgraded on May 17th to 7.0.0.5447.a2d94c81

After downgrading to mingw-w64-x86_64-winpthreads-git-7.0.0.5325.11a5459d-1, the issue disappears.

You can use a command of this form to test it on your machine:

`for /L %c in (1,1,200) do echo Run %c >> freeze.log & .\ffmpeg.exe -threads:v 0 -i some1080pfile.mp4  -an -t 2 -f null - >> freeze.log 2>&1`

ffmpeg will get stuck faster when decoding a higher resolution file - codec doesn't matter.

**Comment by wiiaboo** [comment]
I think it should've been fixed with 9.2 as shinchiro and others have started to use it.
