### ISSUE TITLE
Request: [angle] git update takes too many time.

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#1345]
The Github mirror: https://github.com/google/angle.git

Will takes a few mins to update the source.

But switch to the origin source: https://chromium.googlesource.com/angle/angle

Will be much faster.

Seems GitHub is not fast to update over 1000 branches project yet.

**Comment by 1480c1** [comment]
Could you give some numbers? It is a personal preference on mine to try to not rely on so many sites off of GitHub and others, but if there is a good gain to be had, sure.

You could open a PR with the changes and reasoning instead of opening a request issue and take the time learning with the git workflow or how to edit files in GitHub web

**Comment by fuchanghao** [comment]
> 
> 
> Could you give some numbers? It is a personal preference on mine to try to not rely on so many sites off of GitHub and others, but if there is a good gain to be had, sure.
> 
> You could open a PR with the changes and reasoning instead of opening a request issue and take the time learning with the git workflow or how to edit files in GitHub web

For me,  It has over 20% chance stop at "Running git update for angle" with zero traffic in "git-remote-https.exe".

The last run of the build. you can see the git update of angle takes over 8mins. And others are using GitHub too but not have that problem.


> [313m05:33:59(B[m   Running svn update for mplayer...
> [313m05:34:06(B[m [1mmplayer svn (B[m ...................................... [[32mUp-to-date(B[m]
> [313m05:34:15(B[m   Running git update for angle...
> [313m05:42:28(B[m [1mangle git (B[m ........................................ [[32mUp-to-date(B[m]
> [313m05:42:28(B[m [1m├(B[m [32mCompiling mpv with Vapoursynth R47(B[m(B[m
> [313m05:42:28(B[m [1m├(B[m [311mmpv will need vapoursynth.dll and vsscript.dll to use vapoursynth filter!(B[m(B[m
> [313m05:42:28(B[m   Running git update for mujs...
> [313m05:42:32(B[m [1mmujs git (B[m ......................................... [[32mUp-to-date(B[m]
> [313m05:42:33(B[m   Running git update for vulkan-loader...
> [313m05:42:36(B[m [1mvulkan-loader git (B[m ................................ [[32mUp-to-date(B[m]

**Comment by 1480c1** [comment]
``` bash
source /build/media-suite_helper.sh

time do_vcs https://github.com/google/angle.git angle-github
...
real    0m44.089s
user    0m12.337s
sys     0m13.566s
```

``` bash
time do_vcs https://chromium.googlesource.com/angle/angle angle-google
...
real    0m34.467s
user    0m14.244s
sys     0m14.144s
```

Can you try running these commands and print the times?

**Comment by 1480c1** [comment]
I want to make sure it isn't just my side speed difference
