### ISSUE TITLE
mpv on screen display isn't working

### ISSUE THREAD

**Issue by tcmbackwards** [m-ab-s/media-autobuild_suite#1347]
The on screen display function of mpv depends on Lua < 5.3, and it hasn't been working with luajit. As far as I can tell it hasn't been working since April or so, maybe related to this commit:

https://github.com/msys2/MINGW-packages/commit/81c02d0b8bdbc69c939f6cca8e08032eda003f3a

**Comment by wiiaboo** [comment]
It's working fine for me, I would've noticed. It's a mpv issue, probably.

**Comment by p-roesink** [comment]
My on screen display also hasn't been working for quite some time.

**Comment by wiiaboo** [comment]
OK. What do you want me to do about it? Complain to mpv, it's working fine for me.

**Comment by p-roesink** [comment]
My on screen display issue seems to be limited to builds created with this project. At first, I thought the fault was my own computer. But browsing around the internet today brought me to this brand new issue report.

Seeing as I was not the only one with this particular issue (and that this project still mainly compiles other programs), I wanted to be helpful and give a "I also have problem" kind of feedback.

My apologies if this kind of feedback only seems like a complaint.

**Comment by wiiaboo** [comment]
OK, now that's a lot more interesting to know. I'll try to investigate this
week. Like I said, I also use my own builds, and did notice that
--no-config had broken OSC, but I assumed others' builds were also broken.

**Comment by tcmbackwards** [comment]
I tried some custom builds linked from the mpv site and they're all working.

**Comment by wiiaboo** [comment]
I don't know why shinchiro's isn't broken, too many different variables, but there's an [issue open about it](https://github.com/mpv-player/mpv/issues/6775) and already a [fix incoming](https://github.com/mpv-player/mpv/pull/6878). Meanwhile, just use `--gpu-api=opengl` or `--gpu-api=vulkan`.
