### ISSUE TITLE
mingw32 libopenh264.dll is shared link in ffmpeg.exe, ffplay.exe

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1349]
mingw32 libopenh264.dll is shared link in ffmpeg.exe, ffplay.exe

**Comment by 1480c1** [comment]
As far as I know, https://github.com/m-ab-s/media-autobuild_suite/pull/1308

**Comment by 1480c1** [comment]
#688
#690
#699
#709
