### ISSUE TITLE
mplayer  undefined reference to `ff_vp9_qsv_decoder'

### ISSUE THREAD

**Issue by kuh3h3** [m-ab-s/media-autobuild_suite#1357]
10:25:51 ┌ mplayer svn  .............................. [Recently updated]
10:25:51 ├ Running distclean...
10:27:58 ├ Running configure...
10:38:08 ├ Running install...

Likely error:
AR      libavutil/libavutil.a
make[1]: Leaving directory '/build/mplayer-svn/ffmpeg'
gcc -o mencoder.exe mencoder.o parser-mecmd.o xvid_vbr.o libmpcodecs/ae.o libmpcodecs/ae_pcm.o libmpcodecs/ve.o libmpcodecs/ve_raw.o libmpdemux/muxer.o libmpdemux/muxer_avi.o libmpdemux/muxer_mpeg.o libmpdemux/muxer_rawaudio.o libmpdemux/muxer_rawvideo.o libmpcodecs/ae_faac.o libmpcodecs/ae_lavc.o libmpcodecs/ve_lavc.o libmpdemux/muxer_lavf.o libmpcodecs/ve_nuv.o libmpcodecs/native/rtjpegn.o libmpcodecs/ae_lame.o libmpcodecs/ae_twolame.o libmpcodecs/ve_x264.o libmpcodecs/ve_xvid4.o asxparser.o bstr.o codec-cfg.o cpudetect.o edl.o fmt-conversion.o m_config.o m_option.o m_struct.o mp_msg.o mp_strings.o mpcommon.o parser-cfg.o path.o playtree.o playtreeparser.o subopt-helper.o libaf/af.o libaf/af_center.o libaf/af_channels.o libaf/af_comp.o libaf/af_delay.o libaf/af_dummy.o libaf/af_equalizer.o libaf/af_extrastereo.o libaf/af_format.o libaf/af_gate.o libaf/af_hrtf.o libaf/af_karaoke.o libaf/af_pan.o libaf/af_resample.o libaf/af_scaletempo.o libaf/af_sinesuppress.o libaf/af_stats.o libaf/af_sub.o libaf/af_surround.o libaf/af_sweep.o libaf/af_tools.o libaf/af_volnorm.o libaf/af_volume.o libaf/filter.o libaf/format.o libaf/reorder_ch.o libaf/window.o libmpcodecs/ad.o libmpcodecs/ad_alaw.o libmpcodecs/ad_dvdpcm.o libmpcodecs/ad_hwac3.o libmpcodecs/ad_hwmpa.o libmpcodecs/ad_pcm.o libmpcodecs/dec_audio.o libmpcodecs/dec_teletext.o libmpcodecs/dec_video.o libmpcodecs/img_format.o libmpcodecs/mp_image.o libmpcodecs/pullup.o libmpcodecs/vd.o libmpcodecs/vd_hmblck.o libmpcodecs/vd_lzo.o libmpcodecs/vd_mpegpes.o libmpcodecs/vd_mtga.o libmpcodecs/vd_null.o libmpcodecs/vd_raw.o libmpcodecs/vd_sgi.o libmpcodecs/vd_black.o libmpcodecs/vf.o libmpcodecs/vf_1bpp.o libmpcodecs/vf_2xsai.o libmpcodecs/vf_blackframe.o libmpcodecs/vf_boxblur.o libmpcodecs/vf_crop.o libmpcodecs/vf_cropdetect.o libmpcodecs/vf_decimate.o libmpcodecs/vf_delogo.o libmpcodecs/vf_denoise3d.o libmpcodecs/vf_detc.o libmpcodecs/vf_dint.o libmpcodecs/vf_divtc.o libmpcodecs/vf_down3dright.o libmpcodecs/vf_dsize.o libmpcodecs/vf_dvbscale.o libmpcodecs/vf_eq.o libmpcodecs/vf_eq2.o libmpcodecs/vf_expand.o libmpcodecs/vf_field.o libmpcodecs/vf_fil.o libmpcodecs/vf_filmdint.o libmpcodecs/vf_fixpts.o libmpcodecs/vf_flip.o libmpcodecs/vf_format.o libmpcodecs/vf_framestep.o libmpcodecs/vf_gradfun.o libmpcodecs/vf_halfpack.o libmpcodecs/vf_harddup.o libmpcodecs/vf_hqdn3d.o libmpcodecs/vf_hue.o libmpcodecs/vf_il.o libmpcodecs/vf_ilpack.o libmpcodecs/vf_ivtc.o libmpcodecs/vf_kerndeint.o libmpcodecs/vf_mirror.o libmpcodecs/vf_noformat.o libmpcodecs/vf_noise.o libmpcodecs/vf_ow.o libmpcodecs/vf_palette.o libmpcodecs/vf_perspective.o libmpcodecs/vf_phase.o libmpcodecs/vf_pp7.o libmpcodecs/vf_pullup.o libmpcodecs/vf_rectangle.o libmpcodecs/vf_remove_logo.o libmpcodecs/vf_rgbtest.o libmpcodecs/vf_rotate.o libmpcodecs/vf_sab.o libmpcodecs/vf_scale.o libmpcodecs/vf_smartblur.o libmpcodecs/vf_softpulldown.o libmpcodecs/vf_stereo3d.o libmpcodecs/vf_softskip.o libmpcodecs/vf_swapuv.o libmpcodecs/vf_telecine.o libmpcodecs/vf_test.o libmpcodecs/vf_tfields.o libmpcodecs/vf_tile.o libmpcodecs/vf_tinterlace.o libmpcodecs/vf_unsharp.o libmpcodecs/vf_vo.o libmpcodecs/vf_yadif.o libmpcodecs/vf_yuvcsp.o libmpcodecs/vf_yvu9.o libmpdemux/aac_hdr.o libmpdemux/asfheader.o libmpdemux/aviheader.o libmpdemux/aviprint.o libmpdemux/demuxer.o libmpdemux/demux_aac.o libmpdemux/demux_asf.o libmpdemux/demux_audio.o libmpdemux/demux_avi.o libmpdemux/demux_demuxers.o libmpdemux/demux_film.o libmpdemux/demux_fli.o libmpdemux/demux_lmlm4.o libmpdemux/demux_mf.o libmpdemux/demux_mkv.o libmpdemux/demux_mov.o libmpdemux/demux_mpg.o libmpdemux/demux_nsv.o libmpdemux/demux_pva.o libmpdemux/demux_rawaudio.o libmpdemux/demux_rawvideo.o libmpdemux/demux_realaud.o libmpdemux/demux_real.o libmpdemux/demux_roq.o libmpdemux/demux_smjpeg.o libmpdemux/demux_ts.o libmpdemux/demux_ty.o libmpdemux/demux_ty_osd.o libmpdemux/demux_viv.o libmpdemux/demux_vqf.o libmpdemux/demux_y4m.o libmpdemux/ebml.o libmpdemux/extension.o libmpdemux/mf.o libmpdemux/mp3_hdr.o libmpdemux/mp_taglists.o libmpdemux/mpeg_hdr.o libmpdemux/mpeg_packetizer.o libmpdemux/parse_es.o libmpdemux/parse_mp4.o libmpdemux/video.o libmpdemux/yuv4mpeg.o libmpdemux/yuv4mpeg_ratio.o osdep/getch2-win.o osdep/timer-win2.o stream/open.o stream/stream.o stream/stream_bd.o stream/stream_cue.o stream/stream_file.o stream/stream_mf.o stream/stream_null.o stream/url.o sub/eosd.o sub/find_sub.o sub/osd.o sub/spudec.o sub/sub.o sub/sub_cc.o sub/subreader.o sub/vobsub.o sub/font_load.o stream/stream_cdda.o stream/cdinfo.o stream/stream_dvdnav.o stream/stream_dvd.o stream/stream_dvd_common.o libvo/aclib.o av_helpers.o av_opts.o libaf/af_lavcac3enc.o libaf/af_lavcresample.o libmpcodecs/ad_ffmpeg.o libmpcodecs/ad_spdif.o libmpcodecs/vd_ffmpeg.o libmpcodecs/vf_geq.o libmpcodecs/vf_lavc.o libmpcodecs/vf_lavcdeint.o libmpcodecs/vf_screenshot.o libmpdemux/demux_lavf.o stream/stream_ffmpeg.o sub/av_sub.o libmpcodecs/vf_fspp.o libmpcodecs/vf_qp.o libmpcodecs/vf_spp.o libmpcodecs/vf_uspp.o sub/font_load_ft.o stream/stream_ftp.o libmpcodecs/vd_ijpg.o libmpcodecs/vf_ass.o sub/ass_mp.o sub/subassconvert.o libass/ass.o libass/ass_bitmap.o libass/ass_cache.o libass/ass_drawing.o libass/ass_font.o libass/ass_fontconfig.o libass/ass_library.o libass/ass_parse.o libass/ass_render.o libass/ass_render_api.o libass/ass_shaper.o libass/ass_strtod.o libass/ass_utils.o stream/stream_bluray.o libaf/af_bs2b.o libmpcodecs/ad_libmad.o libmpcodecs/vd_theora.o stream/stream_rtsp.o stream/freesdp/common.o stream/freesdp/errorlist.o stream/freesdp/parser.o stream/librtsp/rtsp.o stream/librtsp/rtsp_rtp.o stream/librtsp/rtsp_session.o stream/stream_netstream.o stream/asf_mmst_streaming.o stream/asf_streaming.o stream/cookies.o stream/http.o stream/network.o stream/pnm.o stream/rtp.o stream/udp.o stream/tcp.o stream/stream_rtp.o stream/stream_udp.o stream/realrtsp/asmrp.o stream/realrtsp/real.o stream/realrtsp/rmff.o stream/realrtsp/sdpplin.o stream/realrtsp/xbuffer.o libmpcodecs/vd_mpng.o libmpcodecs/vf_pp.o osdep/priority.o libmpcodecs/ad_realaud.o libmpcodecs/vd_realvid.o libmpcodecs/ad_speex.o stream/cache2.o stream/frequencies.o stream/stream_tv.o stream/tv.o stream/tvi_dummy.o stream/tvi_dshow.o loader/dshow/guids.o loader/dshow/mediatype.o libmpcodecs/ad_libvorbis.o libmpdemux/demux_ogg.o libmpcodecs/vd_xanim.o libmpcodecs/vd_xvid4.o osdep/glob-win.o osdep/setenv.o osdep/strsep.o ffmpeg/libpostproc/libpostproc.a ffmpeg/libavfilter/libavfilter.a ffmpeg/libavformat/libavformat.a ffmpeg/libavcodec/libavcodec.a ffmpeg/libswscale/libswscale.a ffmpeg/libswresample/libswresample.a ffmpeg/libavutil/libavutil.a -static -Wl,--version-script,binary.ver -Wl,--nxcompat -Wl,--no-seh -Wl,--dynamicbase -Wl,--allow-multiple-definition -pipe -static-libgcc -static-libstdc++ -lws2_32 -liconv -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -LC:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/lib -lgnutls -lws2_32 -lgmp -latomic -lcrypt32 -lhogweed -lgmp -lnettle -ltasn1 -lpng -lz -ljpeg -lbluray -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -ldvdread -ldl -lpsapi -lcdio_cdda -lcdio -lcdio_paranoia  -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -LC:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/lib -lfreetype -lz -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -LC:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/lib -lfontconfig -lintl -liconv -lexpat -lfreetype -lz -lfribidi -lz -lbz2 -llzo2 -lmad -lvorbisenc -lvorbis -logg -lspeex -ltheoradec -logg -lilbc -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -lopus -lm -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -lbs2b -lm -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -LC:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/lib -lrtmp -lz -lgmp -lws2_32 -lwinmm -lgdi32 -lgnutls -lws2_32 -lgmp -latomic -lcrypt32 -ltasn1 -lhogweed -lgmp -lnettle -lopencore-amrnb -lopencore-amrwb -lxvidcore -lvpx -lole32 -luuid  -ldl  -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -ldvdnav -ldvdread -ldl -lpsapi -lm -lwinmm -llzma -liconv -lws2_32 -lpthread -lwinpthread -lpng -lwinmm -ltwolame -lfaac -lx264  -lmp3lame
C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ffmpeg/libavcodec/allcodecs.o:allcodecs.c:(.rdata+0xda8): undefined reference to `ff_vp9_qsv_decoder'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:746: mencoder.exe] Error 1
gcc -o mencoder.exe mencoder.o parser-mecmd.o xvid_vbr.o libmpcodecs/ae.o libmpcodecs/ae_pcm.o libmpcodecs/ve.o libmpcodecs/ve_raw.o libmpdemux/muxer.o libmpdemux/muxer_avi.o libmpdemux/muxer_mpeg.o libmpdemux/muxer_rawaudio.o libmpdemux/muxer_rawvideo.o libmpcodecs/ae_faac.o libmpcodecs/ae_lavc.o libmpcodecs/ve_lavc.o libmpdemux/muxer_lavf.o libmpcodecs/ve_nuv.o libmpcodecs/native/rtjpegn.o libmpcodecs/ae_lame.o libmpcodecs/ae_twolame.o libmpcodecs/ve_x264.o libmpcodecs/ve_xvid4.o asxparser.o bstr.o codec-cfg.o cpudetect.o edl.o fmt-conversion.o m_config.o m_option.o m_struct.o mp_msg.o mp_strings.o mpcommon.o parser-cfg.o path.o playtree.o playtreeparser.o subopt-helper.o libaf/af.o libaf/af_center.o libaf/af_channels.o libaf/af_comp.o libaf/af_delay.o libaf/af_dummy.o libaf/af_equalizer.o libaf/af_extrastereo.o libaf/af_format.o libaf/af_gate.o libaf/af_hrtf.o libaf/af_karaoke.o libaf/af_pan.o libaf/af_resample.o libaf/af_scaletempo.o libaf/af_sinesuppress.o libaf/af_stats.o libaf/af_sub.o libaf/af_surround.o libaf/af_sweep.o libaf/af_tools.o libaf/af_volnorm.o libaf/af_volume.o libaf/filter.o libaf/format.o libaf/reorder_ch.o libaf/window.o libmpcodecs/ad.o libmpcodecs/ad_alaw.o libmpcodecs/ad_dvdpcm.o libmpcodecs/ad_hwac3.o libmpcodecs/ad_hwmpa.o libmpcodecs/ad_pcm.o libmpcodecs/dec_audio.o libmpcodecs/dec_teletext.o libmpcodecs/dec_video.o libmpcodecs/img_format.o libmpcodecs/mp_image.o libmpcodecs/pullup.o libmpcodecs/vd.o libmpcodecs/vd_hmblck.o libmpcodecs/vd_lzo.o libmpcodecs/vd_mpegpes.o libmpcodecs/vd_mtga.o libmpcodecs/vd_null.o libmpcodecs/vd_raw.o libmpcodecs/vd_sgi.o libmpcodecs/vd_black.o libmpcodecs/vf.o libmpcodecs/vf_1bpp.o libmpcodecs/vf_2xsai.o libmpcodecs/vf_blackframe.o libmpcodecs/vf_boxblur.o libmpcodecs/vf_crop.o libmpcodecs/vf_cropdetect.o libmpcodecs/vf_decimate.o libmpcodecs/vf_delogo.o libmpcodecs/vf_denoise3d.o libmpcodecs/vf_detc.o libmpcodecs/vf_dint.o libmpcodecs/vf_divtc.o libmpcodecs/vf_down3dright.o libmpcodecs/vf_dsize.o libmpcodecs/vf_dvbscale.o libmpcodecs/vf_eq.o libmpcodecs/vf_eq2.o libmpcodecs/vf_expand.o libmpcodecs/vf_field.o libmpcodecs/vf_fil.o libmpcodecs/vf_filmdint.o libmpcodecs/vf_fixpts.o libmpcodecs/vf_flip.o libmpcodecs/vf_format.o libmpcodecs/vf_framestep.o libmpcodecs/vf_gradfun.o libmpcodecs/vf_halfpack.o libmpcodecs/vf_harddup.o libmpcodecs/vf_hqdn3d.o libmpcodecs/vf_hue.o libmpcodecs/vf_il.o libmpcodecs/vf_ilpack.o libmpcodecs/vf_ivtc.o libmpcodecs/vf_kerndeint.o libmpcodecs/vf_mirror.o libmpcodecs/vf_noformat.o libmpcodecs/vf_noise.o libmpcodecs/vf_ow.o libmpcodecs/vf_palette.o libmpcodecs/vf_perspective.o libmpcodecs/vf_phase.o libmpcodecs/vf_pp7.o libmpcodecs/vf_pullup.o libmpcodecs/vf_rectangle.o libmpcodecs/vf_remove_logo.o libmpcodecs/vf_rgbtest.o libmpcodecs/vf_rotate.o libmpcodecs/vf_sab.o libmpcodecs/vf_scale.o libmpcodecs/vf_smartblur.o libmpcodecs/vf_softpulldown.o libmpcodecs/vf_stereo3d.o libmpcodecs/vf_softskip.o libmpcodecs/vf_swapuv.o libmpcodecs/vf_telecine.o libmpcodecs/vf_test.o libmpcodecs/vf_tfields.o libmpcodecs/vf_tile.o libmpcodecs/vf_tinterlace.o libmpcodecs/vf_unsharp.o libmpcodecs/vf_vo.o libmpcodecs/vf_yadif.o libmpcodecs/vf_yuvcsp.o libmpcodecs/vf_yvu9.o libmpdemux/aac_hdr.o libmpdemux/asfheader.o libmpdemux/aviheader.o libmpdemux/aviprint.o libmpdemux/demuxer.o libmpdemux/demux_aac.o libmpdemux/demux_asf.o libmpdemux/demux_audio.o libmpdemux/demux_avi.o libmpdemux/demux_demuxers.o libmpdemux/demux_film.o libmpdemux/demux_fli.o libmpdemux/demux_lmlm4.o libmpdemux/demux_mf.o libmpdemux/demux_mkv.o libmpdemux/demux_mov.o libmpdemux/demux_mpg.o libmpdemux/demux_nsv.o libmpdemux/demux_pva.o libmpdemux/demux_rawaudio.o libmpdemux/demux_rawvideo.o libmpdemux/demux_realaud.o libmpdemux/demux_real.o libmpdemux/demux_roq.o libmpdemux/demux_smjpeg.o libmpdemux/demux_ts.o libmpdemux/demux_ty.o libmpdemux/demux_ty_osd.o libmpdemux/demux_viv.o libmpdemux/demux_vqf.o libmpdemux/demux_y4m.o libmpdemux/ebml.o libmpdemux/extension.o libmpdemux/mf.o libmpdemux/mp3_hdr.o libmpdemux/mp_taglists.o libmpdemux/mpeg_hdr.o libmpdemux/mpeg_packetizer.o libmpdemux/parse_es.o libmpdemux/parse_mp4.o libmpdemux/video.o libmpdemux/yuv4mpeg.o libmpdemux/yuv4mpeg_ratio.o osdep/getch2-win.o osdep/timer-win2.o stream/open.o stream/stream.o stream/stream_bd.o stream/stream_cue.o stream/stream_file.o stream/stream_mf.o stream/stream_null.o stream/url.o sub/eosd.o sub/find_sub.o sub/osd.o sub/spudec.o sub/sub.o sub/sub_cc.o sub/subreader.o sub/vobsub.o sub/font_load.o stream/stream_cdda.o stream/cdinfo.o stream/stream_dvdnav.o stream/stream_dvd.o stream/stream_dvd_common.o libvo/aclib.o av_helpers.o av_opts.o libaf/af_lavcac3enc.o libaf/af_lavcresample.o libmpcodecs/ad_ffmpeg.o libmpcodecs/ad_spdif.o libmpcodecs/vd_ffmpeg.o libmpcodecs/vf_geq.o libmpcodecs/vf_lavc.o libmpcodecs/vf_lavcdeint.o libmpcodecs/vf_screenshot.o libmpdemux/demux_lavf.o stream/stream_ffmpeg.o sub/av_sub.o libmpcodecs/vf_fspp.o libmpcodecs/vf_qp.o libmpcodecs/vf_spp.o libmpcodecs/vf_uspp.o sub/font_load_ft.o stream/stream_ftp.o libmpcodecs/vd_ijpg.o libmpcodecs/vf_ass.o sub/ass_mp.o sub/subassconvert.o libass/ass.o libass/ass_bitmap.o libass/ass_cache.o libass/ass_drawing.o libass/ass_font.o libass/ass_fontconfig.o libass/ass_library.o libass/ass_parse.o libass/ass_render.o libass/ass_render_api.o libass/ass_shaper.o libass/ass_strtod.o libass/ass_utils.o stream/stream_bluray.o libaf/af_bs2b.o libmpcodecs/ad_libmad.o libmpcodecs/vd_theora.o stream/stream_rtsp.o stream/freesdp/common.o stream/freesdp/errorlist.o stream/freesdp/parser.o stream/librtsp/rtsp.o stream/librtsp/rtsp_rtp.o stream/librtsp/rtsp_session.o stream/stream_netstream.o stream/asf_mmst_streaming.o stream/asf_streaming.o stream/cookies.o stream/http.o stream/network.o stream/pnm.o stream/rtp.o stream/udp.o stream/tcp.o stream/stream_rtp.o stream/stream_udp.o stream/realrtsp/asmrp.o stream/realrtsp/real.o stream/realrtsp/rmff.o stream/realrtsp/sdpplin.o stream/realrtsp/xbuffer.o libmpcodecs/vd_mpng.o libmpcodecs/vf_pp.o osdep/priority.o libmpcodecs/ad_realaud.o libmpcodecs/vd_realvid.o libmpcodecs/ad_speex.o stream/cache2.o stream/frequencies.o stream/stream_tv.o stream/tv.o stream/tvi_dummy.o stream/tvi_dshow.o loader/dshow/guids.o loader/dshow/mediatype.o libmpcodecs/ad_libvorbis.o libmpdemux/demux_ogg.o libmpcodecs/vd_xanim.o libmpcodecs/vd_xvid4.o osdep/glob-win.o osdep/setenv.o osdep/strsep.o ffmpeg/libpostproc/libpostproc.a ffmpeg/libavfilter/libavfilter.a ffmpeg/libavformat/libavformat.a ffmpeg/libavcodec/libavcodec.a ffmpeg/libswscale/libswscale.a ffmpeg/libswresample/libswresample.a ffmpeg/libavutil/libavutil.a -static -Wl,--version-script,binary.ver -Wl,--nxcompat -Wl,--no-seh -Wl,--dynamicbase -Wl,--allow-multiple-definition -pipe -static-libgcc -static-libstdc++ -lws2_32 -liconv -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -LC:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/lib -lgnutls -lws2_32 -lgmp -latomic -lcrypt32 -lhogweed -lgmp -lnettle -ltasn1 -lpng -lz -ljpeg -lbluray -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -ldvdread -ldl -lpsapi -lcdio_cdda -lcdio -lcdio_paranoia  -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -LC:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/lib -lfreetype -lz -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -LC:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/lib -lfontconfig -lintl -liconv -lexpat -lfreetype -lz -lfribidi -lz -lbz2 -llzo2 -lmad -lvorbisenc -lvorbis -logg -lspeex -ltheoradec -logg -lilbc -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -lopus -lm -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -lbs2b -lm -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -LC:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/lib -lrtmp -lz -lgmp -lws2_32 -lwinmm -lgdi32 -lgnutls -lws2_32 -lgmp -latomic -lcrypt32 -ltasn1 -lhogweed -lgmp -lnettle -lopencore-amrnb -lopencore-amrwb -lxvidcore -lvpx -lole32 -luuid  -ldl  -LC:/Users/kuh3h/Downloads/media-autobuild_suite/local64/lib -ldvdnav -ldvdread -ldl -lpsapi -lm -lwinmm -llzma -liconv -lws2_32 -lpthread -lwinpthread -lpng -lwinmm -ltwolame -lfaac -lx264  -lmp3lame
C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ffmpeg/libavcodec/allcodecs.o:allcodecs.c:(.rdata+0xda8): undefined reference to `ff_vp9_qsv_decoder'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:746: mencoder.exe] Error 1
install failed. Check C:/Users/kuh3h/Downloads/media-autobuild_suite/build/mplayer-svn/ab-suite.install.log
This isn't required for anything so we can move on.
11:12:06 ├ /local64/bin-video/mplayer.exe  ........ [Not found]
11:12:06 └ mplayer-svn  ........................................ [Failed]

Try deleting '/build/mplayer-svn' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

**Comment by wiiaboo** [comment]
Mplayer is not supported, complain to upstream.

**Comment by LigH-de** [comment]
Reported to [mplayerhq tracker, ticket 2362](https://trac.mplayerhq.hu/ticket/2362).

**Comment by LigH-de** [comment]
Fixed by r38151.
