### ISSUE TITLE
mingw32 libmusicbrainz build ok, mingw64 build error

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1359]
libmusicbrainz mingw64 use libproxy library, mingw32 not use.

**Comment by dbyoung720** [comment]
advice: 
Open source code changes from time to time, 
if the compilation fails, the old library is used. 
Compiled successfully and replaced with a new library.

**Comment by wiiaboo** [comment]
What do you mean by "old library"? The previous installation is purged before compiling because it'll usually break compilation.

**Comment by dbyoung720** [comment]
Source code changes from time to time, 
and there is no guarantee that every library will compile successfully.

**Comment by wiiaboo** [comment]
Yes? And what?
If you want guarantees pick a version and never update it ever.

**Comment by wiiaboo** [comment]
Or just use pre-compiled binaries from the internet. If you want your packages to stay stable, this is the wrong place to ask for them.
