### ISSUE TITLE
rav1e build error

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1360]
┌ rav1e git  ......................................... [Recently updated]
├ Running submodule...
├ Running update...
├ Running build...
Likely error:
    |
241 |     PixelType::U16 => match AVG_HBD_FNS[cpu.as_index()] {
    |                             ^^^^^^^^^^^ not found in this scope

error: aborting due to 6 previous errors

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `rav1e`.

To learn more, run the command again with --verbose.
build failed. Check D:/media-ab_suite/build/rav1e-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zWYO.zip
Copy and paste [logs.zip](https://0x0.st/zWYO.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
Complain to upstream.

**Comment by moisesmcardona** [comment]
rav1e actually built fine a few minutes ago on my machine.

**Comment by Barough** [comment]
Been away for a few days. Just tested and it works again.
