### ISSUE TITLE
[mingw64] [libmysofa] build fails

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#1371]
error log:https://0x0.st/z4mD.zip

> 10:07:13 ┌ libmysofa git  ............................... [Updates found]
> 10:07:13 ├ Running cmake...
> 10:07:19 ├ Running build...
> 10:07:20 ├ Running install...
> Likely error:
> CMake Error at cmake_install.cmake:36 (file):
>   file INSTALL cannot read symlink
>   "C:/media-autobuild_suite/build/libmysofa-git/share/default.sofa" to
>   duplicate at
>   "C:/media-autobuild_suite/local64/share/libmysofa/default.sofa".
> 
> 
> FAILED: CMakeFiles/install.util
> cmd.exe /C "cd /D C:\media-autobuild_suite\build\libmysofa-git\build-64bit && C:\media-autobuild_suite\msys64\mingw64\bin\cmake.exe -P cmake_install.cmake"
> ninja: build stopped: subcommand failed.
> install failed. Check C:/media-autobuild_suite/build/libmysofa-git/build-64bit/ab-suite.install.log
> This is required for other packages, so this script will exit.
>

**Comment by moisesmcardona** [comment]
I could not reproduce this issue. It built fine.

**Comment by fuchanghao** [comment]
> 
> 
> I could not reproduce this issue. It built fine. Make sure you're using the latest suite code.

it works now with the new libmysofa git.
