### ISSUE TITLE
rav1e build issue with AVX2 processors; temp fix included

### ISSUE THREAD

**Issue by ImportTaste** [m-ab-s/media-autobuild_suite#1376]
There is currently an issue with building rav1e, it is an upstream issue and isn't due to media-autobuild_suite: https://github.com/xiph/rav1e/issues/1618 A fix is currently pending: https://github.com/xiph/rav1e/pull/1621

But you can apply a temporary fix in the meantime (credit goes to @wiiaboo both for the framework and commands). Open mintty and enter the following commands:
```
source /build/media-suite_helper.sh
create_extra_skeleton rav1e
sed -i '/_pre_rust/a rust_extras+=(--no-default-features --features=binaries)' /build/rav1e_extra.sh
```
When the pending fix linked above is merged, delete `media-autobuild_suite\build\rav1e_extra.sh`

**Comment by ImportTaste** [comment]
Probably fixed upstream now.

**Comment by moisesmcardona** [comment]
Not yet until https://github.com/xiph/rav1e/pull/1624 is merged.

**Comment by moisesmcardona** [comment]
The fix is merged and rav1e is working once again.
