### ISSUE TITLE
Question: enable NDI with FFmpeg 4.1.4 and the suite

### ISSUE THREAD

**Issue by BlackScreen** [m-ab-s/media-autobuild_suite#1377]
I am trying to build a NDI enabled FFmpeg version, that is newer than the one that NDI provided in their SDK (which led to the removal of NDI support, if I understood the discussions correctly).
I found out that the support was removed in 4.2 and onwards in FFmpeg. But the latest 4.1 version - 4.1.4 should work.
So, I tried editing the suite files.

I found the commits, that removed NDI support in the suite:
https://github.com/m-ab-s/media-autobuild_suite/commit/75dfb80d5f1e1a7cffad8f11388da195902e75b5
https://github.com/m-ab-s/media-autobuild_suite/commit/bc0b0704ba989c42374fdc4726c90160632d1c24

So, I re-added the parts that were removed.
And I edited the git-link for FFmpeg in the compile script (line 1783 at the moment) to https://git.ffmpeg.org/ffmpeg.git#tag=n4.1.4.
I also had to disable the new libraries, that were added in 4.2... At the moment this is cuda-llvm & libdav1d.

The suite went through fine. And I got a newer FFmpeg version with NDI support.

I now asked myself if there is a better solution than to re-add all of the code after updating the suite everytime. I see that you will not support my custom additions, I am fine with that. I have this build in an extra folder - separtely to the normal, uncustomised builds.
But, there is probably a better solution - maybe automated - for this? Thanks for your help! :)

**Comment by wiiaboo** [comment]
> I now asked myself if there is a better solution than to re-add all of the code after updating the suite everytime. I see that you will not support my custom additions, I am fine with that. I have this build in an extra folder - separtely to the normal, uncustomised builds.
> But, there is probably a better solution - maybe automated - for this? Thanks for your help! :)

Ideally, you'd have your own custom script that retrieves 4.1.x dependencies, whatever they are, and builds your own FFmpeg as well. That way you still keep up-to-date official suite files and you still have your own FFmpeg build. Just duplicate compile.sh, remove whatever you don't need, add what you need and change FFmpeg to be clamped to `branch=release/4.1`.

No further support is going to be added to this workflow as it would be a monumental pain in the ass to keep track of all dependencies that work in a specific version with their own clamps.

**Comment by NullVSNone** [comment]
Sorry to bring up an old issue, but trying to build FFmpeg with NDI as well.

This story is the only reference of someone getting it working, so I was wondering if @BlackScreen or someone can be of help? I tried grabbing ddf92aeb0f71cf3299e803a1ea8fd2716a0b0061 (commit before removing NDI) and replacing all instances of `https://git.ffmpeg.org/ffmpeg.git` with `https://git.ffmpeg.org/ffmpeg.git#tag=n4.1.4`.

Trying to run it I get, with no log file:

```
first update
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
critical updates
-------------------------------------------------------------------------------
warning: bash-4.4.023-2 is up to date -- skipping
warning: pacman-5.2.1-12 is up to date -- skipping
warning: msys2-runtime-3.1.5-3 is up to date -- skipping
 there is nothing to do
-------------------------------------------------------------------------------
second update
-------------------------------------------------------------------------------
FINDSTR: Cannot open C:\mabs\msys64\home\atlas\.minttyrc
-------------------------------------------------------------------------------
install msys2 base system
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
install 64 bit compiler
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

MinGW64 GCC compiler isn't installed; maybe the download didn't work
Do you want to try it again?

-------------------------------------------------------------------------------
try again [y/n]:
```

Any suggested outline otherwise?

**Comment by wiiaboo** [comment]
Yes, do not use old suite commits.
Instead use the suite as is and add what is missing to build ndi and clamp ffmpeg to whatever version you want, like OP did.

**Comment by NullVSNone** [comment]
Tried that, and had to disable a number of libraries.
Ending with [logs.zip](https://0x0.st/iy91.zip)

```
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --cc=ccache gcc --cxx=ccache g++ --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-chromaprint --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libsvthevc --enable-libsvtav1 --enable-libkvazaar --enable-libmodplug --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libvmaf --enable-libcodec2 --enable-libsrt --enable-ladspa --enable-opencl --enable-opengl --enable-libopenh264 --enable-mbedtls --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --extra-version=gc2d000ec27+257
ERROR: fribidi not found using pkg-config
```
It sounded as though BlackScreen got it working just from removing the libraries, so could something else have changed?
