### ISSUE TITLE
Request: proceed after ffmbc build fail

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#1382]
Since nothing else depends on ffmbc it would be nice if the script would not stop in case building it fails. (can't build 32&64 bit in one go over night since the build gets stuck at ffmbc)

**Comment by Helenerineium** [comment]
You can try patch this line to `[[ $_notrequired ]] || do_prompt`
https://github.com/m-ab-s/media-autobuild_suite/blob/a9274d5a0f77f85307359ee5dfde189b244bfb0d/build/media-suite_helper.sh#L559

**Comment by wiiaboo** [comment]
Implemented/Fixed in https://github.com/m-ab-s/media-autobuild_suite/commit/9b427634a2f44c0df17c4c77f237d79699628ea4
