### ISSUE TITLE
Request: Github Actions

### ISSUE THREAD

**Issue by 1480c1** [m-ab-s/media-autobuild_suite#1388]
@jb-alvarado, can you sign up the m-ab-s organization for github actions? https://github.com/features/actions

It might be possible to run the suite using actions as a check since their max time is 6 hours

**Comment by 1480c1** [comment]
Example: https://github.com/1480c1/media-autobuild_suite/runs/225537173

**Comment by jb-alvarado** [comment]
I think it should work now.

**Comment by 1480c1** [comment]
Thank you

**Comment by softworkz** [comment]
@1480c1  - What was the outcome of the attempts to build with GH actions? I wonder whether you got anywhere because I can't find anything newer (and the older link above is dead).

**Comment by 1480c1** [comment]
I gave up on it as, although I got it to work a few times, usually the build failed due to exceeding time limits. Plus, I don't have an idle windows machine I could hook up to GHA and the ones provided by github are unfortunately too slow to get a build done in time.

it may be possible if somehow the script was either shortened, or split up so it could spawn jobs for individual packages or something, but that may be hard.

**Comment by softworkz** [comment]
> I gave up on it as, although I got it to work a few times, usually the build failed due to exceeding time limits. Plus, I don't have an idle windows machine I could hook up to GHA and the ones provided by github are unfortunately too slow to get a build done in time.

I had suspected something like that. I'm about to try setting this up for building on Azure DevOps and was looking for some experience in that area. I know Devops quite well - essentially it's almost the same like GH actions but the time limit is in fact a problem. Right now it's 60min iirc.

> it may be possible if somehow the script was either shortened, or split up so it could spawn jobs for individual packages or something, but that may be hard.

I thought about splitting the libraries compilation from the ffmpeg/mpv compilation and cache the former, but even on my  local system it's still compiling libraries after almost an hour (building mabs from scratch incl. msys2 installation). And that's just 64bit, the same needs to happen for 32bit as well.

Yea, this is difficult to modularize - at least not without significant work - and maintenance on top....

**Comment by softworkz** [comment]
> I gave up on it as, although I got it to work a few times, usually the build failed due to exceeding time limits. Plus, I don't have an idle windows machine I could hook up to GHA and the ones provided by github are unfortunately too slow to get a build done in time.
> 
> it may be possible if somehow the script was either shortened, or split up so it could spawn jobs for individual packages or something, but that may be hard.

I got this working on Azure DevOps using a rolling cache and some ugly manual kill mechanism that hits after 45min (because the results are cached only when there wasn't any error output). Finally it worked ok, but there was always some uncertainty about whether the killing might possibly leave some state behind which causes subsequent build failures, and so we went with a commercial option.

Yet, the important news is this: you can get build jobs with 6h time limit on devops as an open source project, so in case you would still be interested in having automated builds, then that's probably the best option available.

Best,  
sw
