### ISSUE TITLE
mpv: '--disable-vapoursynth-lazy' suddenly unsupported

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1390]
I asked via IRC whether it can be safely omitted or should be replaced by another option; JEEB replied: "yea, wm4's branch just went in one big whoosh so if something broke for you it's checking time."

```CFLAGS: -mthreads -mtune=generic -O2 -pipe 
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local32/lib -L/mingw32/lib
/usr/bin/python waf configure --prefix=/local32 --bindir=/local32/bin-video --disable-vapoursynth-lazy --disable-debug-build --lua=luajit --enable-static-build

...

waf: error: no such option: --disable-vapoursynth-lazy
```

**Comment by LigH-de** [comment]
Tested removing this option from media-suite_compile.sh line 2145; configuring and building completed.

**Comment by 1480c1** [comment]
@Helenerineium, can you please check to make sure

**Comment by pat357** [comment]
Yes, it's sure.
See https://github.com/mpv-player/mpv/commit/fb8d240c4d045ca254aa6693c48aecc75954cba0

**Comment by 1480c1** [comment]
Removed, please test to make sure

**Comment by pat357** [comment]
MPV configure / build / install are all fine now.
