### ISSUE TITLE
Fail running git update for vvc

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1392]
16:39:58   Running git update for vvc...
16:40:02 ┌ vvc git  ..................................... [Updates found]
16:40:03 ├ Running uninstall...
16:40:09 ├ Running cmake...
16:40:20 ├ Running build...
Likely error (tail of the failed operation logfile):
      |               ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
cc1plus.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.
build failed. Check C:/mingw/build/vvc-git/build-64bit/ab-suite.build.log
This isn't required for anything so we can move on.
16:40:51 ├ Running install...
Likely error (tail of the failed operation logfile):
      |               ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
../source/Lib/CommonLib/Slice.cpp:2015:23: error: 'int __builtin_memcmp_eq(const void*, const void*, long long unsigned int)' reading 256 bytes from a region of size 64 [-Werror=stringop-overflow=]
cc1plus.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.
install failed. Check C:/mingw/build/vvc-git/build-64bit/ab-suite.install.log
[ab-suite.install.log](https://github.com/m-ab-s/media-autobuild_suite/files/3638507/ab-suite.install.log)

**Comment by 1480c1** [comment]
Already reported upstream: https://jvet.hhi.fraunhofer.de/trac/vvc/ticket/538 (thanks @LigH-de)
Related Merge Request: https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM/merge_requests/962

**Comment by LigH-de** [comment]
Waiting for [Fraunhofer VVC ticket 538](https://jvet.hhi.fraunhofer.de/trac/vvc/ticket/538) to be closed when a patch is merged.

**Comment by 1480c1** [comment]
If https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM/merge_requests/974 can be confirmed to be a fix, we can temporarily apply that as a fix

**Comment by 1480c1** [comment]
The fix got merged

**Comment by 1480c1** [comment]
@ycwan, @LigH-de, can you guys please confirm vvc is fine now? Builds on my end fine

**Comment by LigH-de** [comment]
Yes, compiling vvc passed.
