### ISSUE TITLE
Error running git update for vulkan-loader

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1393]
17:05:59   Running git update for vulkan-loader
[CMakeOutput.log](https://github.com/m-ab-s/media-autobuild_suite/files/3638539/CMakeOutput.log)
[ab-suite.cmake.log](https://github.com/m-ab-s/media-autobuild_suite/files/3638541/ab-suite.cmake.log)

...
17:06:03 ┌ vulkan-loader git  ........................... [Updates found]
17:06:04 ├ Running uninstall...
0001-fix-cross-compiling.patch
        Patch could not be applied with `patch`. Continuing without patching.
17:06:05 ├ Running dependencies...
17:06:16 ├ Installing Vulkan-Headers...
17:06:16 ├ Running uninstall...
17:06:16 ├ Running cmake...
17:06:17 ├ Running build...
17:06:17 ├ Running install...
17:06:20 ├ Building Vulkan-Loader...
17:06:21 ├ Running cmake...
Likely error (tail of the failed operation logfile):
CMake Error at C:/mingw/msys64/mingw64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find WDK (missing: WDK_VERSION_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/mingw/msys64/mingw64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindWDK.cmake:73 (find_package_handle_standard_args)
  CMakeLists.txt:122 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/mingw/build/vulkan-loader-git/build-64bit/CMakeFiles/CMakeOutput.log".
cmake failed. Check C:/mingw/build/vulkan-loader-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
17:06:29   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zt2Q.zip
Copy and paste [logs.zip](https://0x0.st/zt2Q.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by 1480c1** [comment]
Please try deleting vulkan-loader-git and rerunning

**Comment by wiiaboo** [comment]
Patch needs rebase. PR made upstream. Wait for https://github.com/DeadSix27/python_cross_compile_script/pull/92
