### ISSUE TITLE
Request: Make a VC version

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1396]
This is for great projects.

Can you make a VC version, so that these intermediate LIB files can also be used by other projects, it will be more beautiful.

Can the Tesseract library be added to ffmpeg compilation

**Comment by 1480c1** [comment]
What do you mean by VC version (What does it stand for? Visual C++?)

**Comment by 1480c1** [comment]
> Can the Tesseract library be added to ffmpeg compilation

I can try

**Comment by 1480c1** [comment]
> > Can the Tesseract library be added to ffmpeg compilation
> 
> I can try

libtesseract is already in the list of things compiled for ffmpeg. Either do a ffmpeg full build or add `--enable-libtesseract` to your ffmpeg_options.txt

**Comment by dbyoung720** [comment]
YES, libtesseract is have.

**Comment by dbyoung720** [comment]
YES Visual C++ projects
thank a lot

**Comment by 1480c1** [comment]
I could try, but what for?

link for my own future reference: https://wiki.videolan.org/GenerateLibFromDll

**Comment by dbyoung720** [comment]
many static libraries generated during MAS compilation can also be used by other VC projects.
For example, in OPENCV, when compiling extended libraries
Thank you for your reply.

**Comment by 1480c1** [comment]
Yea, I only found that out.

Have you tried some of the shared libraries?

**Comment by dbyoung720** [comment]
I use other language, so I hope to integrate it into a DLL in VC.

**Comment by wiiaboo** [comment]
This is an often requested "feature" but I don't really care for it. Most of the libs compiled are not made to work with VC's crippled C compiler (blame Microsoft for not being fully C89/C99 compliant or something).
