### ISSUE TITLE
failed sccache build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1399]
┌ sccache git  ........................................ [Recently updated]
├ Running rust.update...
├ Running rust.build...
Likely error (tail of the failed operation logfile):
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
error: failed to run `rustc` to learn about target-specific information

Caused by:
  could not execute process `sccache rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (never executed)

Caused by:
  Det går inte att hitta filen. (os error 2)
rust.build failed. Check D:/media-ab_suite/build/sccache-git/ab-suite.rust.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ztt8.zip
Copy and paste [logs.zip](https://0x0.st/ztt8.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
Can you try to apply
``` patch
diff --git a/build/media-suite_compile.sh b/build/media-suite_compile.sh
index b3e065a..d8a70e9 100644
--- a/build/media-suite_compile.sh
+++ b/build/media-suite_compile.sh
@@ -173,8 +173,8 @@ if [[ $ripgrep = y || $rav1e = y || $dssim = y ]]; then
 
     _check=(bin/sccache.exe)
     if do_vcs "https://github.com/mozilla/sccache.git"; then
-        do_uninstall "${_check[@]}"
         do_rust
+        sccache --stop-server || false
         do_install "target/$CARCH-pc-windows-gnu/release/sccache.exe" bin/
         do_checkIfExist
         export RUSTC_WRAPPER=sccache
diff --git a/build/media-suite_helper.sh b/build/media-suite_helper.sh
index 5410f72..2b8c154 100644
--- a/build/media-suite_helper.sh
+++ b/build/media-suite_helper.sh
@@ -1273,7 +1273,7 @@ do_mesoninstall() {
 
 do_rust() {
     log "rust.update" "$RUSTUP_HOME/bin/cargo.exe" update
-    command -v sccache > /dev/null 2>&1 && export RUSTC_WRAPPER=sccache
+    { command -v sccache > /dev/null 2>&1 && export RUSTC_WRAPPER=sccache; } || unset RUSTC_WRAPPER
     # use this array to pass additional parameters to cargo
     local rust_extras=()
     extra_script pre rust
```

and rerun?

**Comment by Barough** [comment]
And how do i apply that?

**Comment by 1480c1** [comment]
Save the thing from `diff --git` to `extra_script pre rust` into a file ( temp.diff) and in the mabs folder, run `git apply temp.diff`

**Comment by Barough** [comment]
Getting this when i run the command

$ git apply temp.diff
error: corrupt patch at line 27

**Comment by 1480c1** [comment]
Did you clone from mabs directly?

If so, do 
``` bash
git fetch origin pull/1402/head
git checkout FETCH_HEAD
```
and retry

**Comment by Barough** [comment]
I saved the diff file in the root of my mabs folder and ran the git apply temp.diff in the minty window

**Comment by Barough** [comment]
After running those command so do i still get the same error message

**Comment by 1480c1** [comment]
Okay, will look into why more

**Comment by pat357** [comment]
If you can't apply the patch, make sure the .diff file has line endings are Unix like : **\n** and not Windows like **\n\r**.
If it still doesn't work, you can easily do the changes manually : it's just deleting the line with the minus sign in front and adding the one with the plus sign in front.
Sccache.exe was build successful for me with the patch applied.

**Comment by Barough** [comment]
Took a little while longer to get back ;)

Everything works fine now. The issue is gone.

**Comment by Barough** [comment]
I just noticed this when updating the suite
"fatal: HEAD does not point to a branch"

I guess that it could be related to the commands i ran. Is there a way to fix that?

**Comment by 1480c1** [comment]
Do 
``` bash
git fetch --all 
git reset --hard HEAD
```

**Comment by Barough** [comment]
Thnx :)

**Comment by Barough** [comment]
Still the same thing. Maybe i'll just start over with a fresh mabs setup.
