### ISSUE TITLE
svt-hevc

### ISSUE THREAD

**Issue by laurfb** [m-ab-s/media-autobuild_suite#1400]
Hi.
svt-hevc binary is build even svt option is disabled in media-autobuild_suite.ini ("svthevc=2") and libs svt is added to ffmpeg binary even is marked as disabled in ffmpeg_options.txt (#--enable-libsvthevc).

regards,
laur

**Comment by wiiaboo** [comment]
`#` does not disable anything. It ignores that line. If you have enable-libsvthevc somewhere else or are using a ffmpegChoice >= 2 svthevc is still enabled.
