### ISSUE TITLE
Request: avoid rustc popping up an own window

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1403]
Since you are trying to use sscache for rust builds, an independent console window for rustc occasionally pops up for a very brief time. This is a bit annoying if you want to run the suite in the background while working on other tasks. Also I am not sure if that might be a sign that something failed. Hard for me to track the exact call that causes this popup, but it seems to be rather a cmd or separate window, not mintty.

**Comment by wiiaboo** [comment]
Yeah, I've also wanted to fix mintty doing that eventually, but I don't know if there's an option to start in the background.

**Comment by LigH-de** [comment]
CMD can run a CLI application in a minimized separate window on purpose, using `start /min` ... but that seems to me like walking around another corner.

**Comment by wiiaboo** [comment]
Mintty is not a CLI application.

**Comment by 1480c1** [comment]
I do know that sccache as a `--start-server` option, maybe that's what you are looking for?

**Comment by 1480c1** [comment]
@LigH-de can you test if the pr with stop the multiple cmd windows popping up?

**Comment by LigH-de** [comment]
It does not. I deleted the contents of lib and bin-* in local* before rebuilding. Already building ripgrep let two cmd windows pop up, I noticed one called rustc.

**Comment by 1480c1** [comment]
Hmm

**Comment by LigH-de** [comment]
Additional issue with manually starting the sccache server: When the script gets interrupted, the server persists, and there is an error message when running it again that every socket should be used only once.

**Comment by 1480c1** [comment]
hmm again, I need to research more on sccache's side

**Comment by 1480c1** [comment]
https://github.com/mozilla/sccache/issues/514
