### ISSUE TITLE
cyanrip build failed error cannot find -lnppig

### ISSUE THREAD

**Issue by kuh3h3** [m-ab-s/media-autobuild_suite#1408]
16:20:55   Running git clone for cyanrip...
16:20:58 ┌ cyanrip git  .............................. [Recently updated]
16:20:59 ffmpeg git  ....................................... [Up-to-date]
16:21:00 ├ Running meson...
16:21:08 ├ Running build...
Likely error (tail of the failed operation logfile):
ninja: build stopped: subcommand failed.
[1/1] Linking target src/cyanrip.exe.
FAILED: src/cyanrip.exe
gcc.bat @src/cyanrip.exe.rsp
C:/Users/reandro/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lnppig
C:/Users/reandro/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lnppicc
C:/Users/reandro/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lnppc
C:/Users/reandro/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lnppidei
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/Users/reandro/Downloads/media-autobuild_suite/build/cyanrip-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
16:21:10   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zvmL.zip
Copy and paste [logs.zip](https://0x0.st/zvmL.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by 1480c1** [comment]
Okay, so it wasn't just me

**Comment by LigH-de** [comment]
I have a different issue building for Win32: Dozens of
```
E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: E:/MABS/local32/lib/libavfilter.a(asrc_sinc.o):asrc_sinc.c:(.text+0xad6): undefined reference to ...
```
Is it related or another separate bug? I'm about to report that to the cyanrip project, unless you tell me to wait.

**Comment by 1480c1** [comment]
That seems like a separate bug, but possibly more related towards the suite since it's trying to pick up your separate ffmpeg installation instead of the one just for cyanrip

**Comment by LigH-de** [comment]
Then I'll open a new issue for this part.

**Comment by ycwan** [comment]
Is this the same bug as #1408

[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/3664506/ab-suite.build.log)

22:53:54   Running git update for cyanrip...
22:53:57 ┌ cyanrip git  ................................. [Updates found]
22:53:59 ┌ ffmpeg git  ............................... [Recently updated]
22:53:59 ├ Running uninstall...
22:54:00 ├ Running configure...
22:57:56 ├ Running install...
22:59:07 ├ Running meson...
22:59:09 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_superequalizer.o):af_superequalizer.c:(.text.unlikely+0x88): undefined reference to `av_rdft_init'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_superequalizer.o):af_superequalizer.c:(.text.unlikely+0x52): undefined reference to `av_rdft_end'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text+0x9c): undefined reference to `av_rdft_calc'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text+0xf0): undefined reference to `av_rdft_calc'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text+0x40ed): undefined reference to `av_rdft_init'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text+0x43c9): undefined reference to `av_rdft_init'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text.unlikely+0x47): undefined reference to `av_rdft_end'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text.unlikely+0x66): undefined reference to `av_rdft_end'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/mingw/build/cyanrip-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
22:59:19   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zvBB.zip
Copy and paste [logs.zip](https://0x0.st/zvBB.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by LigH-de** [comment]
No, it's #1409

**Comment by wiiaboo** [comment]
This is due to the recent [requirement of the hdcd filter](https://github.com/cyanreg/cyanrip/commit/4602932514ddf7c266e5855601183cc1a8e96833#diff-9fbb37ad64805c2da3889d419806cd51).

**Comment by ycwan** [comment]
After media-autobuild_suite update (a672809 cyanffmpeg: add hdcd filter), I run it again and still the same problem

[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/3664926/ab-suite.build.log)
 
08:26:29   Running git update for cyanrip...
08:26:31 ┌ cyanrip git  .............................. [Recently updated]
08:26:41 ┌ ffmpeg git  ............................... [Recently updated]
08:26:41 ├ Running uninstall...
08:26:42 ├ Running configure...
08:31:17 ├ Running install...
08:33:01 ├ Running meson...
08:33:10 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_superequalizer.o):af_superequalizer.c:(.text.unlikely+0x88): undefined reference to `av_rdft_init'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_superequalizer.o):af_superequalizer.c:(.text.unlikely+0x52): undefined reference to `av_rdft_end'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text+0x9c): undefined reference to `av_rdft_calc'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text+0xf0): undefined reference to `av_rdft_calc'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text+0x40ed): undefined reference to `av_rdft_init'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text+0x43c9): undefined reference to `av_rdft_init'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text.unlikely+0x47): undefined reference to `av_rdft_end'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/libavfilter.a(af_surround.o):af_surround.c:(.text.unlikely+0x66): undefined reference to `av_rdft_end'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/mingw/build/cyanrip-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
08:33:20   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zv1c.zip
Copy and paste [logs.zip](https://0x0.st/zv1c.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment]
There were more updates after it.
