### ISSUE TITLE
Rebuilding ffmpeg completely: ffnvcodec may need another check

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1410]
When I purge the local*/bin-* and local*/lib directories to enforce rebuilding of all components, it usually happens that the configure step of ffmpeg stops because it can't find the ffnvcodec installed (when I use an ffmpeg configuration which includes it). I have to remove the build/ffnvcodec-git directory to enforce its additional rebuild. So I guess an additional check for the existence of the installed library, when ffmpeg is configured to use it, may be useful.

**Comment by wiiaboo** [comment]
Well, it should check for ffnvcodec.pc, but maybe it doesn't fail the check if it can't find it.

**Comment by wiiaboo** [comment]
No, just checked. If you delete ffnvcodec.pc it recompiles it.

**Comment by wiiaboo** [comment]
If you only delete the libraries inside /local*/lib, then you're not deleting anything that ffnvcodec needs, since there's no libs it installs, just pkgconfig and headers.

**Comment by wiiaboo** [comment]
Are you absolutely sure that it's always the ffnvcodec check that fails?

**Comment by LigH-de** [comment]
Tested it again (after disabling libtesseract while it fails).

- Configure MABS to build ffmpeg as non-free edition with custom full module selection via text file (including cuda and ffnvcodec).
- Have ffmpeg compiled once, so ffnvcodec was also built and installed once.
- Purge local*/lib/ and local*/bin-*/ to enforce rebuilding of everything; now the file local*/lib/pkconfig/ffnvcodec.pc does not exist, neither the library files.
- Run MABS again.
- The configure step of ffmpeg fails: `ERROR: cuda requested, but not all dependencies are satisfied: ffnvcodec`
- Remove build/ffnvcodec-git to enforce rebuilding and reinstallation.
- Run MABS again.
- Now the file local*/lib/pkconfig/ffnvcodec.pc and the library files do exist again after ffnvcodec was compiled and installed.
- The configure step of ffmpeg passes now, and ffmpeg gets built including ffnvcodec.

I do see a few libraries being (re-) installed before running the ffmpeg part. I guess libffnvcodec might get added to this list (when enabled)?

```
Installing gsm... done
Installing snappy... done
Installing libssh... done
Installing libtheora... done
Installing libcdio-paranoia... done
Installing libcaca... done
Installing libmodplug... done
Installing openjpeg2... done
Installing openh264... done
Installing chromaprint... done
Installing zeromq... done
Installing libxml2... done
Installing ladspa-sdk... done
```

----

> BTW: I had to restart this attempt several times because some resident Tortoise... "Explorer Extensions" kept blocking directories. Not your problem ... just mentioning that "something in Windows" is likely to interfere with the jobs in MSYS2, which are unable to know these reasons and e.g. wait for locked files/directories to be released, and instead throw errors. Sad but usual for me. Might be useful to keep that in mind as a quite probable source of issues.

**Comment by pat357** [comment]
I had a similar problem a couple of months ago.
I changed the line
```
_check=(ffnvcodec/nvEncodeAPI.h)
```
by
```
_check=(ffnvcodec/nvEncodeAPI.h ffnvcodec.pc)
```
This seemed to solve my problem, as I never had it again.
