### ISSUE TITLE
vorbis-tools make failed

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1425]
make[3]: Entering directory '/build/vorbis-tools-git/build-32bit/oggenc'
  CCLD     oggenc.exe
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x2a2): undefined reference to `_imp__FLAC__stream_decoder_process_single'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x3b0): undefined reference to `_imp__FLAC__stream_decoder_get_state'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x3e7): undefined reference to `_imp__FLAC__metadata_object_clone'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x513): undefined reference to `_imp__FLAC__stream_decoder_new'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x526): undefined reference to `_imp__FLAC__stream_decoder_set_md5_checking'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x536): undefined reference to `_imp__FLAC__stream_decoder_set_metadata_respond'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x5b1): undefined reference to `_imp__FLAC__stream_decoder_init_ogg_stream'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x5bc): undefined reference to `_imp__FLAC__stream_decoder_process_until_end_of_metadata'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x5c7): undefined reference to `_imp__FLAC__stream_decoder_process_single'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x692): undefined reference to `_imp__FLAC__stream_decoder_init_stream'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x6f9): undefined reference to `_imp__FLAC__stream_decoder_finish'
../i686-w64-mingw32/bin/ld.exe: flac.o:flac.c:(.text+0x704): undefined reference to `_imp__FLAC__stream_decoder_delete'
collect2.exe: error: ld returned 1 exit status
make[3]: *** [Makefile:540: oggenc.exe] Error 1
make[3]: Leaving directory '/build/vorbis-tools-git/build-32bit/oggenc'
make[2]: *** [Makefile:598: all-recursive] Error 1
make[2]: Leaving directory '/build/vorbis-tools-git/build-32bit/oggenc'
make[1]: *** [Makefile:497: all-recursive] Error 1
make[1]: Leaving directory '/build/vorbis-tools-git/build-32bit'
make: *** [Makefile:427: all] Error 2

**Comment by BlackScreen** [comment]
I had almost the same error today with opus-tools. Maybe the same solution?
I have no output of the console - writing from my mobile phone. Sorry.

**Comment by dbyoung720** [comment]
Updated, the problem remains

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/issues/1426
