### ISSUE TITLE
The source directory "I:/media-autobuild_suite/build/sndfile-git" does not appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#1432]
building snd for lame failed and after the deletion of the sndfile-git folder and restarting the script I got:
 [logs.zip](https://0x0.st/zxB2.zip)

**Comment by 1480c1** [comment]
Try completely deleting sndfile-git and rerunning, it seems that maybe git didn't run, but I can't tell since your git clone log file hasn't been updated

**Comment by Selur** [comment]
deleting the sndfile-git folder is what I did, I deleted the folder again and this time it worked. No clue what is different then before. Really strange.
