### ISSUE TITLE
error with ffms2 patch

### ISSUE THREAD

**Issue by Patman86** [m-ab-s/media-autobuild_suite#1442]
Hi,

today i got these error:

`0001-ffmsindex-fix-linking-issues.patch
	Patch could not be applied with `git am`. Continuing without patching.`

This results in a compile error.

Here is the Log:
[Log.zip](https://0x0.st/z3mU.zip)

**Comment by wiiaboo** [comment]
@1480c1 you changed it to the old URL but forgot to rebase it, I think.

**Comment by 1480c1** [comment]
Did I? Let me check

**Comment by 1480c1** [comment]
Wait, it seems I copied the wrong link
