### ISSUE TITLE
do_patch error of some patches

### ISSUE THREAD

**Issue by Patman86** [m-ab-s/media-autobuild_suite#1446]
Hi

i got these errors:

> 19:32:52 ┌ ffmpeg git  .................................. [Files missing]
> 19:32:52 ├ Changing options to comply to nonfree...
> 19:32:53 Installing clang... done
> vapoursynth_alt.patch
>         Patch could not be applied with `git am`. Continuing without patching.
> zLsN.txt
>         Patch could not be applied with `git am`. Continuing without patching.
> openal-pkgconfig.patch
>         Patch could not be applied with `patch`. Continuing without patching.
> 19:32:57 ├ Compiling static FFmpeg...

Wrong URL's?

**Comment by 1480c1** [comment]
The patches seem to exist and the links doesn't seem to be dead, maybe something is conflicting with an earlier patch, but I can't tell much without knowing what patches your build applied

**Comment by Patman86** [comment]
Here is my modified media-suite_compile.sh in ZIP. I've changed python to 3.7.5, vapoursynth to R48-RC3 and added the patch from [here](https://github.com/m-ab-s/media-autobuild_suite/issues/1441) for svt-av1.

[media-suite_compile.zip](https://github.com/m-ab-s/media-autobuild_suite/files/3757576/media-suite_compile.zip)

**Comment by wiiaboo** [comment]
I didn't look at your modifications, but do try to keep all patches using 'am'. And even if you do, there's no guarantee that a patch won't trample on another one, so you have to take that into account.

**Comment by Patman86** [comment]
I've delete all stuff and started rebuilding, including my changes. Now everything is fine.
