### ISSUE TITLE
[mingw32] libwebp fails to build with undef to __memcpy_chk

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1450]
Running git clone for libwebp...
┌ libwebp git  ........................................ [Recently updated]
├ Running autoreconf...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0xc53): undefined reference to `__memcpy_chk'
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0xc72): undefined reference to `__memcpy_chk'
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0xcf0): undefined reference to `__memcpy_chk'
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0xd0b): undefined reference to `__memcpy_chk'
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0x146a): undefined reference to `__memcpy_chk'
D:/media-ab_suite/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-ab_suite/build/libwebp-git/build-32bit/src/.libs/libwebp.a(libwebpdspdecode_sse2_la-upsampling_sse2.o):upsampling_sse2.c:(.text+0x1493): more undefined references to `__memcpy_chk' follow
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:441: webp_quality.exe] Error 1
make[1]: Leaving directory '/build/libwebp-git/build-32bit/extras'
make: *** [Makefile:420: all-recursive] Error 1
make failed. Check D:/media-ab_suite/build/libwebp-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/z3Rv.zip
Copy and paste [logs.zip](https://0x0.st/z3Rv.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
Related to stack fortifying and etc

**Comment by 1480c1** [comment]
I don't think this still applies anymore
