### ISSUE TITLE
Error running git update for SVT-AV1

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1451]
``` bash
02:14:28   Running git update for SVT-AV1...
02:14:32 ├ Found SVT-AV1_extra.sh. Sourcing script...
02:14:32 ┌ SVT-AV1 git  ................................. [Updates found]
02:14:33 ├ Running pre cmake from SVT-AV1_extra.sh...
Likely error (tail of the failed operation logfile):
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
_pre_cmake
717.patch
        Patch could not be applied with `patch`. Continuing without patching.
pre_cmake failed. Check C:/mingw/build/SVT-AV1-git/ab-suite.pre_cmake.log
This is required for other packages, so this script will exit.
02:14:36   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/z3FF.zip
Copy and paste [logs.zip](https://0x0.st/z3FF.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/z3FF.zip)
[ab-suite.pre_cmake.log](https://github.com/m-ab-s/media-autobuild_suite/files/3773259/ab-suite.pre_cmake.log)

**Comment by 1480c1** [comment]
Update, removed it since upstream merged

**Comment by ycwan** [comment]
Updated MABS and deleted SVT-AV1.git and rerun MABS but the error persists.  Please advise

03:50:44   Running git clone for SVT-AV1...
03:51:09 ├ Found SVT-AV1_extra.sh. Sourcing script...
03:51:09 ┌ SVT-AV1 git  .............................. [Recently updated]
03:51:10 ├ Running pre cmake from SVT-AV1_extra.sh...
Likely error (tail of the failed operation logfile):
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
_pre_cmake
717.patch
        Patch could not be applied with `patch`. Continuing without patching.
pre_cmake failed. Check C:/mingw/build/SVT-AV1-git/ab-suite.pre_cmake.log
This is required for other packages, so this script will exit.
03:51:14   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/z3Cx.zip
Copy and paste [logs.zip](https://0x0.st/z3Cx.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/z3Cx.zip)
[ab-suite.pre_cmake.log](https://github.com/m-ab-s/media-autobuild_suite/files/3773606/ab-suite.pre_cmake.log)

**Comment by 1480c1** [comment]
Remove SVT-AV1_extra.sh
