### ISSUE TITLE
Fails to build fontconfig-git

### ISSUE THREAD

**Issue by LeeThompson** [m-ab-s/media-autobuild_suite#1460]
OS: Windows 10 (1903) (x64)

Script fails on fontconfig-git

```
make[3]: Entering directory '/build/fontconfig-git/build-64bit/src'
lib -name:libfontconfig-1.dll -def:fontconfig.def -out:fontconfig.lib
make[3]: lib: Command not found
make[3]: *** [Makefile:986: fontconfig.lib] Error 127
```

The Msys environment doesn't appear to include a lib.
I tried using Microsoft's lib but that fails due to an invalid option.

[logs.zip](https://0x0.st/zg_U.zip)

**Comment by LeeThompson** [comment]
Tried using Microsoft's (visual studio 2017) lib.exe and it gets slightly farther, but this time there's an error with MSys64's linker.

```
lib -name:libfontconfig-1.dll -def:fontconfig.def -out:fontconfig.lib
LINK: unknown option -- n
Try 'LINK --help' for more information.
make[3]: *** [Makefile:986: fontconfig.lib] Error 1
```
`lib.exe: 14.15.26732.1 (x64)`
`link.exe' April 25 2019 3:36:02am (no version information) in msys64/usr/bin.`

[logs.zip](https://0x0.st/zgLz.zip)

**Comment by 1480c1** [comment]
Don't use msvc's executables for msys2 and mingw-w64 purposes.

It's like trying to combine rice cookers and ovens to make bread. You can do it, but just don't.

**Comment by 1480c1** [comment]
Right now running to see if I can reproduce on my machine

**Comment by LeeThompson** [comment]
I figured, I took the lib.exe back out.

**Comment by 1480c1** [comment]
Can't reproduce on mine, Same os ver and building 64-bit

**Comment by LeeThompson** [comment]
So you have a lib.exe somewhere?    Did you try testing this on a clean machine/VM?   (Maybe it's finding lib.exe with your build tools.)

**Comment by LeeThompson** [comment]
Just re-ran this again on a clean install:

```
Likely error (tail of the failed operation logfile):
make[3]: Entering directory '/build/fontconfig-git/build-32bit/src'
lib -name:libfontconfig-1.dll -def:fontconfig.def -out:fontconfig.lib
make[3]: lib: Command not found
make[3]: *** [Makefile:986: fontconfig.lib] Error 127
make[3]: Leaving directory '/build/fontconfig-git/build-32bit/src'
make[2]: *** [Makefile:541: all] Error 2
make[2]: Leaving directory '/build/fontconfig-git/build-32bit/src'
make[1]: *** [Makefile:599: all-recursive] Error 1
make[1]: Leaving directory '/build/fontconfig-git/build-32bit'
make: *** [Makefile:483: all] Error 2
make failed. Check D:/Build/FFMPEG/build/fontconfig-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
14:54:46   Creating diagnostics file...
```

[logs.zip](https://0x0.st/zgL2.zip)

**Comment by 1480c1** [comment]
For me, it's not even trying to call `lib` or `lib.exe`

Try deleting your msys2 folder, I have a feeling that something is wrong with your initialization as it's thinking you are running this for msvc building or something.

**Comment by LeeThompson** [comment]
I deleted the whole thing (all of it) and re-extracted this release and re-ran the master batch file and (ultimately) got the same error.  [logs.zip](https://0x0.st/zgL2.zip)

**Comment by 1480c1** [comment]
Okay, I will try to look into why fontconfig might detect your build as msvc later

**Comment by LeeThompson** [comment]
Been kinda digging through some of fontconfig logs myself and it seems to want to make a DLL even though all my choices are for a static ffmpeg exe.

(from .\build\fontconfig-git\build-64bit\config.log)

`$ ../configure --prefix=/local64 --disable-shared --enable-static --bindir=/local64/bin-global --disable-docs --enable-iconv --with-libiconv-prefix=/mingw64 --with-libiconv-lib=/mingw64/lib --with-libiconv-includes=/mingw64/include LDFLAGS=-pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib --enable-libxml2`

... but at some point it seems to decide to make DLLs.

**Comment by LeeThompson** [comment]
Just finished running on a different Windows 10 machine (also 1903) and got the same error:  [logs.zip](https://0x0.st/zgLl.zip) 

I'm going to try this on my gaming box which doesn't have a MS Visual Studio present.

**Comment by LeeThompson** [comment]
I may have found it, will update as tests continue.

**Comment by LeeThompson** [comment]
If ab-suite.configure.log has this line: `checking for lib.exe... yes` it appears to cause the issue,

I had an old lib.exe in my Tools folder (common tools) which replicates to each of my Windows machines (virtual and not, except for test environments).    When I removed _that_, the ab-suite configure of fontconfig changed to `checking for lib.exe... no` and it was able to proceed.

Oddly, although lib.exe was in my path, when the make actually runs, it can't find it (presumably because the bash shell isn't inheriting the Windows path).

If whatever generates ab-suite.configure.log isn't part of your script, what you might want to do is initially check for lib.exe in the Windows environment path and warn if it finds it. 

(There also appears to be the possibility of an override in fontconfig-git/configure at line 15405.)

**Comment by 1480c1** [comment]
For fontconfig, the thing that generates `ab-suite.configure.log` is fontconfig's configure file.

So maybe we do need to do harder path sanitation, but problem is, I don't know all of the names of the executables that the configure files would look for, and to compile that list, it would require me to go through all of the project that are built, and look through their scripts.

One possible thing to do is to ask/submit a patch to fontconfig to prevent looking for `lib.exe` when building for mingw-w64 targets (That should be autodetected by config.guess).

I can try to see if I can make a patch in my free time, but it may be better to submit an issue upstream (https://gitlab.freedesktop.org/fontconfig/fontconfig). However, knowing your situation, they may not care about it until necessary as your situation is a bit unique (A shared folder with an executable whose name was listed for search) or may delay finding a way to fix it since it doesn't actually block msys2/mingw-w64 building.

**Comment by LeeThompson** [comment]
I would say if this hasn't affected anyone else that it's probably not worth the effort.

Having said that it would probably be worthwhile in the troubleshooting section maybe just note something like "If you're getting failures due to 'lib: command not found" that there is probably a lib.exe somewhere in your path and needs to be renamed/removed/moved for the compile to succeed."  

Since that seems to be enough for fontconfig to insist on building a DLL even if everything else is saying not to.  

The issue seems to be in fontconfig's 'configure' script (although the line with 'ac_cv_prog_ms_librarian="$ms_librarian" # Let the user override the test.' might be a way around it too but I'm not sure what `${ac_cv_prog_ms_librarian+:}` does since I'm not that knowledgeable on bash scripts.)      I'll probably report it to fontconfig once I set up an account (the login via GitLab and GitHub each went to a 404 for me),

```
if test "$os_win32" = "yes"; then
  # Extract the first word of "lib.exe", so it can be a program name with args.
set dummy lib.exe; ac_word=$2
{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
$as_echo_n "checking for $ac_word... " >&6; }
if ${ac_cv_prog_ms_librarian+:} false; then :
  $as_echo_n "(cached) " >&6
else
  if test -n "$ms_librarian"; then
  ac_cv_prog_ms_librarian="$ms_librarian" # Let the user override the test.
else
as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
for as_dir in $PATH
do
  IFS=$as_save_IFS
  test -z "$as_dir" && as_dir=.
    for ac_exec_ext in '' $ac_executable_extensions; do
  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
    ac_cv_prog_ms_librarian="yes"
    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
    break 2
  fi
done
  done
IFS=$as_save_IFS

  test -z "$ac_cv_prog_ms_librarian" && ac_cv_prog_ms_librarian="no"
fi
fi
ms_librarian=$ac_cv_prog_ms_librarian
if test -n "$ms_librarian"; then
  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ms_librarian" >&5
$as_echo "$ms_librarian" >&6; }
else
  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
$as_echo "no" >&6; }
fi


fi
 if test x$ms_librarian = xyes; then
  MS_LIB_AVAILABLE_TRUE=
  MS_LIB_AVAILABLE_FALSE='#'
else
  MS_LIB_AVAILABLE_TRUE='#'
  MS_LIB_AVAILABLE_FALSE=
fi
```

**Comment by wiiaboo** [comment]
I'd say having lib.exe in PATH is broken environment. Add a big warning to
the .bat in case lib.exe is found that you shouldn't run the suite with the
MSVC CMD shortcuts or after importing the MSVC environment. A lot of
configures/cmake would be broken because they'll prefer MSVC to GCC in
Windows.

**Comment by LeeThompson** [comment]
I tested the updated batch file on my old environment (I copied lib.exe back to my Tools folder) and it caught it so I think that's probably good enough.   (The only improvement I could think of would be to list out where it's located but if someone has cl.exe or lib.exe they can probably figure that out.)

**Comment by 1480c1** [comment]
Make sure to comment in the associated pr if it's related to that

`cl.exe` should be fine as we are telling the scripts we want to use gcc and g++ as the compiler manually through exporting the CC and CXX variables. They should only care about it if they explicitly require `cl.exe` for a msvc only file or something
