### ISSUE TITLE
Undefined reference related to _FORTIFY_SOURCE

### ISSUE THREAD

**Issue by ghost** [m-ab-s/media-autobuild_suite#1464]
Here I provide some workaround to errors caused by `_FORTIFY_SOURCE > 0` 
(undefined reference to `*_chk` functions)

1. Unlike glibc, mingw-w64 does not provide fortified functions at all. 
**So fortification requires `-lssp` (or `-fstack-protector` which adds `-lssp` implicitly) to work.**
2. modify system header (`msys64/mingw64/x86_64-w64-mingw32/include/_mingw_mac.h` for 64bit) 
Change `#    define __MINGW_FORTIFY_LEVEL 2` and `#    define __MINGW_FORTIFY_LEVEL 1` to 
`#    define __MINGW_FORTIFY_LEVEL 0` so that fortified functions will not be used even if `_FORTIFY_SOURCE > 0` is set. (You need to do it again if mingw-w64-headers-git is updated.)

So here is the question: Since modifying system headers / source code is unlikely to be accepted,
do we want to turn on `-fstack-protector(-strong)` by default?
Or only add it to repos that need it?

**Comment by 1480c1** [comment]
I personally would prefer to have `-fstack-protector(-strong)` on by default from a programmer's side even with any performance penalty it will bring, however, that's on the condition that all of the projects build and run properly.

**Comment by wiiaboo** [comment]
Why was this only broken recently? What changed in MingW?

**Comment by 1480c1** [comment]
https://github.com/msys2/MINGW-packages/issues/5803
https://sourceforge.net/p/mingw-w64/mailman/message/36764708/

mingw-w64's stack fortifications stuff sucked since it relied on `*_chk` functions provided in another library, `libssp`, and didn't provide any itself. mingw-w64's crt used to be build with `_FORTIFY_SOURCE`  set, but since it would require a separate lib to actually compile, there was a circular dependency. Msys2 removed `_FORTIFY_SOURCE` as much as possible, but upstream packages still add it manually.

To use those functions, we would either add `-lssp` or `-fstack-protector-strong` which would in turn implicitly add `-lssp`.

**Comment by slyfox1186** [comment]
For anyone who is having trouble finding the files  mentioned above they are located in these files. After making the changes MAB does build successfully.

```
C:\Media-Autobuild_Suite\build\libidn2-2.2.0\build-64bit\config.h:583:            || (defined _FORTIFY_SOURCE && 0 < _FORTIFY_SOURCE \
C:\MAB\build\libidn2-2.2.0\config.h.in:582:            || (defined _FORTIFY_SOURCE && 0 < _FORTIFY_SOURCE \
C:\MAB\build\libidn2-2.2.0\m4\extern-inline.m4:61:            || (defined _FORTIFY_SOURCE && 0 < _FORTIFY_SOURCE \
C:\MAB\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\9.2.0\include\ssp\ssp.h:38:#if _FORTIFY_SOURCE > 0 && __OPTIMIZE__ > 0 \
C:\MAB\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\9.2.0\include\ssp\ssp.h:42:# if _FORTIFY_SOURCE == 0
C:\MAB\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\9.2.0\include\ssp\ssp.h:44:# elif _FORTIFY_SOURCE > 0
C:\MAB\msys64\mingw64\share\aclocal\extern-inline.m4:49:            || (defined _FORTIFY_SOURCE && 0 < _FORTIFY_SOURCE \
C:\MAB\msys64\mingw64\x86_64-w64-mingw32\include\_mingw_mac.h:304:#if _FORTIFY_SOURCE > 0 && __OPTIMIZE__ > 0 && __MINGW_GNUC_PREREQ(4, 1)
C:\MAB\msys64\mingw64\x86_64-w64-mingw32\include\_mingw_mac.h:305:#  if _FORTIFY_SOURCE >0
C:\MAB\msys64\usr\include\ruby-2.6.0\x86_64-msys\rb_mjit_min_header-2.6.5.h:2:#define _FORTIFY_SOURCE 0
C:\MAB\msys64\usr\share\aclocal\extern-inline.m4:49:            || (defined _FORTIFY_SOURCE && 0 < _FORTIFY_SOURCE \
```

**Comment by wiiaboo** [comment]
We don't use ruby anywhere.
And that's a lot of files to maintain a custom hack on. I'd prefer just
hard depending on libssp.

**Comment by 1480c1** [comment]
I think this isn't an issue anymore, but if it is, we can always reopen this and the pr
