### ISSUE TITLE
tesseract build error

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1467]
┌ tesseract git  ...................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libtesseract.a(libtesseract_api_la-baseapi.o):baseapi.cpp:(.text+0x6f3a): undefined reference to `_imp__curl_easy_init'
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libtesseract.a(libtesseract_api_la-baseapi.o):baseapi.cpp:(.text+0x6f58): undefined reference to `_imp__curl_easy_setopt'
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libtesseract.a(libtesseract_api_la-baseapi.o):baseapi.cpp:(.text+0x6fab): undefined reference to `_imp__curl_easy_perform'
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libtesseract.a(libtesseract_api_la-baseapi.o):baseapi.cpp:(.text+0x6fbc): undefined reference to `_imp__curl_easy_cleanup'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:600: tesseract.exe] Error 1
make[2]: Leaving directory '/build/tesseract-git/build-32bit/src/api'
make[1]: *** [Makefile:538: all-recursive] Error 1
make[1]: Leaving directory '/build/tesseract-git/build-32bit'
make: *** [Makefile:424: all] Error 2
make failed. Check D:/mabs/build/tesseract-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zEiJ.zip
Copy and paste [logs.zip](https://0x0.st/zEiJ.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
Again with impl stuff and curl

Note for later: tesseract trying to use shared curl lib

**Comment by ispysoftware** [comment]
same issue - clean build

**Comment by wiiaboo** [comment]
https://github.com/m-ab-s/media-autobuild_suite/issues/1413
