### ISSUE TITLE
Unexpected dependencies with ffmpegSHARED

### ISSUE THREAD

**Issue by ImportTaste** [m-ab-s/media-autobuild_suite#1472]
In the past, I really only needed what was included in the ffmpegSHARED folder to be able to launch ffmpeg, however there are new dependencies that seem to be solely situated in `msys64\mingw64\bin`.

The DLLs are `libcrypto-1_1-x64.dll`, `libgcc_s_seh-1.dll`, `libssh.dll`, `libwinpthread-1.dll`, & `zlib1.dll`.

I'm not sure if perhaps msys64\mingw64\bin used to be in my PATH and that's the only reason it worked (though I'm pretty sure I never did they myself so it would have to have been something the suite did at some point) or there's been some sort of change somewhere that isn't packing them into the executable when it's made.

**Comment by wiiaboo** [comment]
postproc is part of ffmpeg. The others should be a dependency, unless
hide_shared_libs is broken.

**Comment by wiiaboo** [comment]
Shouldn't be a dependency*

**Comment by wiiaboo** [comment]
postproc-55.dll, swresample-3.dll, swscale-5.dll are all ffmpeg libs, so obviously they are expected shared libs.
If you didn't want shared dependencies, why are you building shared FFmpeg?

**Comment by ImportTaste** [comment]
I keep successfully compiled binaries and dependencies outside of my media-autobuild_suite folder, and I'm confused as to why the shared binaries now require they be in the same folder as these dlls or for them to be in my PATH.

I ended up just launching ffmpeg.exe over and over and fishing out the DLLs it asked for out of `media-autobuild_suite\msys64\mingw64\bin` until the errors stopped.

I've compiled the shared version of FFmpeg many times, and this has never happened before. All they required was the av* and sw* DLLs that were contained in the same folder, as well as CUDA DLLs available through my PATH variable. I think something must have changed.

**Comment by ImportTaste** [comment]
I just realized I made a mistake in my initial report; `swresample-3.dll`, `swscale-5.dll`, and `postproc-55.dll` should not have been listed.

**Comment by wiiaboo** [comment]
And I can't reproduce the issue either. I don't have all of those dlls with ffmpegB2=4.

**Comment by wiiaboo** [comment]
Do `ldd ffmpeg.exe` and you can see what you depend on. Or ProcessMonitor (?).

**Comment by wiiaboo** [comment]
Or https://github.com/lucasg/Dependencies/releases or `dumpbin /dependents <exe>` if you have MSVS installed and open the dev tools.

**Comment by ImportTaste** [comment]
Will this work?
```
>for /f "tokens=1" %G in ('ldd ffmpeg.exe') do @echo|set /p="%G "
ntdll.dll KERNEL32.DLL KERNELBASE.dll msvcrt.dll SHELL32.dll ucrtbase.dll cfgmgr32.dll shcore.dll RPCRT4.dll combase.dll bcryptPrimitives.dll windows.storage.dll msvcp_win.dll sechost.dll advapi32.dll profapi.dll powrprof.dll UMPDC.dll shlwapi.dll GDI32.dll win32u.dll gdi32full.dll USER32.dll kernel.appcore.dll cryptsp.dll avdevice-58.dll IMM32.dll avfilter-7.dll avformat-58.dll ole32.dll bcrypt.dll avcodec-58.dll CRYPT32.dll WLDAP32.dll avutil-56.dll OLEAUT32.dll MSASN1.dll WS2_32.dll postproc-55.dll SETUPAPI.dll swresample-3.dll swscale-5.dll IPHLPAPI.DLL WINMM.dll OPENGL32.dll libssh.dll VERSION.dll AVICAP32.dll nppicc64_100.dll WINMMBASE.dll nppidei64_100.dll GLU32.dll nppig64_100.dll libwinpthread-1.dll libgcc_s_seh-1.dll zlib1.dll MSVFW32.dll libcrypto-1_1-x64.dll CRYPTBASE.DLL COMCTL32.dll dxcore.dll nppc64_100.dll
```

**Comment by wiiaboo** [comment]
Work for what?
Most of those dlls come with the system, you're not supposed to distribute them.

**Comment by ImportTaste** [comment]
Oh, I assumed you wanted to see the list of dependencies.

**Comment by wiiaboo** [comment]
The npp*.dll ones are definitely not redistributable, they're part of Nvidia Cuda SDK.

**Comment by ImportTaste** [comment]
I don't redistribute my compilations of FFmpeg, they're for personal use.

**Comment by wiiaboo** [comment]
I don't, I know for sure that you shouldn't be depending on libcrypto as I'm also building with openssl and my ffmpeg doesn't depend on it. Probably consequence of shared-only libssh, which I've already forcefully disabled.

**Comment by ImportTaste** [comment]
I'm noticing that my static compilation of ffmpeg has the same 5 DLL files listed, but they're built into the binary.

They must have been built into the shared binaries in the past, but no longer.

**Comment by ImportTaste** [comment]
Just noticed your new commit, I will recompile and see what happens.

**Comment by wiiaboo** [comment]
![](https://i.fsbn.eu/3tcN.webp)

Only difference between static and shared FFmpeg should be that shared ffmpeg.exe additionally depends on each ffmpeg lib.

**Comment by wiiaboo** [comment]
> They must have been built into the shared binaries in the past, but no longer.

No, they absolutely weren't. That's the only fucking difference on building shared FFmpeg, like I've said 3 times already.

**Comment by ImportTaste** [comment]
Wow.

**Comment by wiiaboo** [comment]
Sorry for the swearing, I get particularly annoyed when I have to repeat myself.

**Comment by ImportTaste** [comment]
I get that it's supposed to work that way, I never doubted you on that. My assumption was that something strange happened.

My mistake was I was thinking in terms of the DLLs having always been dependencies instead of the DLLs not previous being dependencies. On busy evenings, I'm admittedly prone to getting carried away on a particular train of thought.

You are correct of course. I found an old copy of my ffmpeg-shared binaries and verified it. Sorry for the misunderstanding.

**Comment by GyanD** [comment]
I do a static build and I get libssh.dll missing. Never had that before. Resolved by adding msys64/mingw64/bin to the path. What's changed?

**Comment by wiiaboo** [comment]
Look for libssh on commits and issues. Mingw libssh is now shared-only, so it's been disabled. If you need it, complain to mingw-packages, as I don't really want to add libssh to the suite.
