### ISSUE TITLE
Reactivate --enable-librav1e for ffmpeg

### ISSUE THREAD

**Issue by easyfab** [m-ab-s/media-autobuild_suite#1474]
Librav1e is now in master. 
https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=d8bf24459b694338de4ceb2a2e6d4d2949d6658d

Could --enable-librav1e for ffmpeg be reactivate ?

**Comment by 1480c1** [comment]
Possible, but would take some time unless @wiiaboo is already working on it.

**Comment by wiiaboo** [comment]
There's already code to handle that, I think? I just temporarily disabled it because the patch was stale.

**Comment by ImportTaste** [comment]
librav1e seems to work for compiling shared FFmpeg but not for compiling static FFmpeg.

**Comment by 1480c1** [comment]
```
        # librav1e
        if enabled librav1e; then
            do_removeOption FFMPEG_OPTS_SHARED "--enable-librav1e"
        fi
```
It shouldn't be there for shared ffmpeg

**Comment by ImportTaste** [comment]
Oh, that explains it.
