### ISSUE TITLE
Error running git update for vulkan-loader

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1482]
``` bash
21:46:13   Running git update for vulkan-loader...
21:46:20 ┌ vulkan-loader git  ........................... [Updates found]
21:46:20 ├ Running uninstall...
0001-fix-cross-compiling.patch
        Patch could not be applied with `git am`. Continuing without patching.
21:46:21 ├ Running dependencies...
21:46:44 ├ Installing Vulkan-Headers...
21:46:44 ├ Running uninstall...
21:46:44 ├ Running cmake...
21:46:44 ├ Running build...
21:46:44 ├ Running install...
21:46:46 ├ Building Vulkan-Loader...
21:46:47 ├ Running cmake...
21:46:51 ├ Running build...
Likely error (tail of the failed operation logfile):
../loader/vk_loader_platform.h:373:13: warning: 'loader_platform_thread_init_cond' defined but not used [-Wunused-function]
  373 | static void loader_platform_thread_init_cond(loader_platform_thread_cond *pCond) { InitializeConditionVariable(pCond); }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:364:34: warning: 'loader_platform_get_thread_id' defined but not used [-Wunused-function]
  364 | static loader_platform_thread_id loader_platform_get_thread_id() { return GetCurrentThreadId(); }
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:288:14: warning: 'loader_platform_basename' defined but not used [-Wunused-function]
  288 | static char *loader_platform_basename(char *pathname) {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check C:/mingw/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
21:46:58   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zIs9.zip
Copy and paste [logs.zip](https://0x0.st/zIs9.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
```

[logs.zip](https://0x0.st/zIs9.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/3881523/ab-suite.build.log)

**Comment by 1480c1** [comment]
```
[3/17] Building C object loader/CMakeFiles/loader-norm.dir/loader.c.obj
FAILED: loader/CMakeFiles/loader-norm.dir/loader.c.obj 
C:\mingw\local64\bin\gcc.bat -DAPI_NAME=\"Vulkan\" -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -I../loader -I../loader/generated -Iloader -IC:/mingw/local64/include -mthreads -mtune=generic -O2 -pipe -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wno-stringop-truncation -Wno-stringop-overflow -Wimplicit-fallthrough=0 -D_CRT_SECURE_NO_WARNINGS -O3 -DNDEBUG -MD -MT loader/CMakeFiles/loader-norm.dir/loader.c.obj -MF loader\CMakeFiles\loader-norm.dir\loader.c.obj.d -o loader/CMakeFiles/loader-norm.dir/loader.c.obj   -c ../loader/loader.c
../loader/loader.c: In function 'loaderGetDeviceRegistryFiles':
../loader/loader.c:678:25: error: 'CM_GETIDLIST_FILTER_CLASS' undeclared (first use in this function); did you mean 'CM_GETIDLIST_FILTER_BITS'?
  678 |     const ULONG flags = CM_GETIDLIST_FILTER_CLASS | CM_GETIDLIST_FILTER_PRESENT;
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                         CM_GETIDLIST_FILTER_BITS
../loader/loader.c:678:25: note: each undeclared identifier is reported only once for each function it appears in
../loader/loader.c:678:53: error: 'CM_GETIDLIST_FILTER_PRESENT' undeclared (first use in this function); did you mean 'CM_GETIDLIST_FILTER_SERVICE'?
  678 |     const ULONG flags = CM_GETIDLIST_FILTER_CLASS | CM_GETIDLIST_FILTER_PRESENT;
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                     CM_GETIDLIST_FILTER_SERVICE
```

https://github.com/Warblefly/MultimediaTools-mingw-w64/blob/76a9eef9157a456a4d0bb32e3b5014da44387277/001-build-fix.patch#L63-74

Those two do not exist in mingw-w64, perhaps it's failing because
```
21:46:20 ├ Running uninstall...
0001-fix-cross-compiling.patch
        Patch could not be applied with `git am`. Continuing without patching.
```

**Comment by myfreeer** [comment]
Upstream has broken the patch. Check https://github.com/KhronosGroup/Vulkan-Loader/pull/260.

**Comment by wiiaboo** [comment]
shinchiro has uploaded a rebased patch.

**Comment by ycwan** [comment]
Run MABS about an hour ago and hit the same error as below

14:05:30   Running git update for vulkan-loader...
14:05:33 ┌ vulkan-loader git  ........................ [Recently updated]
14:05:34 ├ Running uninstall...
0001-fix-cross-compiling.patch
        Patch could not be applied with `git am`. Continuing without patching.
14:05:37 ├ Running dependencies...
14:05:51 ├ Installing Vulkan-Headers...
14:05:51 ├ Running uninstall...
14:05:52 ├ Running cmake...
14:05:53 ├ Running build...
14:05:53 ├ Running install...
14:05:57 ├ Building Vulkan-Loader...
14:05:57 ├ Running cmake...
14:06:08 ├ Running build...
Likely error (tail of the failed operation logfile):
../loader/vk_loader_platform.h:373:13: warning: 'loader_platform_thread_init_cond' defined but not used [-Wunused-function]
  373 | static void loader_platform_thread_init_cond(loader_platform_thread_cond *pCond) { InitializeConditionVariable(pCond); }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:364:34: warning: 'loader_platform_get_thread_id' defined but not used [-Wunused-function]
  364 | static loader_platform_thread_id loader_platform_get_thread_id() { return GetCurrentThreadId(); }
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:288:14: warning: 'loader_platform_basename' defined but not used [-Wunused-function]
  288 | static char *loader_platform_basename(char *pathname) {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check C:/mingw/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
14:06:13   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zITm.zip
Copy and paste [logs.zip](https://0x0.st/zITm.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/3883282/ab-suite.build.log)
