### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by daalmogo** [m-ab-s/media-autobuild_suite#1495]
https://0x0.st/zl20.zip

**Comment by 1480c1** [comment]
delete ccache-git in the build folder and rerun

**Comment by daalmogo** [comment]
> 
> 
> delete ccache-git in the build folder and rerun

https://0x0.st/zlLi.zip

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/issues/1413
