### ISSUE TITLE
[mingw64] [Tesseract] Tesseract compilation fails with undef to __imp_curl_version

### ISSUE THREAD

**Issue by psisis** [m-ab-s/media-autobuild_suite#1497]
I'm trying to build tesseract via the media-autobuild_suite but I get a compilation error and it fails. I'm not too experienced with making, so even though I will try looking for an error, I might have troubles recognizing it.

I posted my make log https://pastebin.com/pnjhbM02

It ends with the error: undefined reference to `__imp_curl_version'

Is there any way to disable teserract, or 'libtesseract' as it says in ffmpeg_options.txt? Running the bat file only tries to re-compile. and media-autobuild_suite.ini has no option for tesseract I can see so it might be dependable?

https://0x0.st/zl3r.zip <- uploaded log files

I'm indebted to any assistance. I've been trying too much to build ffmpeg with Cuda sdk enabled. In mingw, ffmpeg complained about not creating an executable with C, and I read around that link.exe or cl.exe has something to do with it? Anyway, without media autobuild, I've never come this far.

I did install VS locator, and just to be safe, I also added the custom_profile in local64/etc

**Comment by 1480c1** [comment]
> it ends with the error: undefined reference to `__imp_curl_version'

look at https://github.com/m-ab-s/media-autobuild_suite/issues/1413 for tesseract+curl and ffmpeg issues

Have you tried updating the suite? One of the latest commit deals with tesseract and libcurl

>Is there any way to disable teserract, or 'libtesseract' as it says in ffmpeg_options.txt? Running the bat file only tries to re-compile. and media-autobuild_suite.ini has no option for tesseract I can see so it might be dependable?

Inside `ffmpeg_options.txt`, either remove the line that says `--enable-libtesseract` or prefix it with a `#` to `#--enable-libtesseract` comment it out

> I also added the custom_profile in local64/etc

This part is necessary to do, you only need to do it if you want to set custom variables etc
