### ISSUE TITLE
[FFmpeg+CUDA] CUDA_PATH env variable not found

### ISSUE THREAD

**Issue by psisis** [m-ab-s/media-autobuild_suite#1499]
I'm trying to build ffmpeg with cuda codecs enabled. I get this error when compiling ffmpeg.

`CUDA_PATH environment variable not set or directory does not exist.` Very unfortunate. I have those variables set in my Windows ENV, I thought maybe msys needs them too. But I opened mntty and did echo $PATH and $CUDA_PATH and everything looks right, CUDA PATH gives me `C:/PROGRA~1/NVIDIA~2/CUDA/10.2`  which looked weird at first, but I suppose is a legitimate way to write directories (with spaces) in Win.

I also added the paths in custom_profile. But it seems this did nothing to affect build process. 

I also opened ffmpeg-git/configure to see if there is any option for CUDA_PATH but I couldn't find any.

BTW, where is ffmpeg.exe supposed to go when the compilation is finished and successful? I did a search for ffmpeg.exe but it's in a weird location so maybe it isn't the one I compiled?

**Comment by 1480c1** [comment]
When you double click the `mintty` in the repo folder, and type
```bash
[[ -z $CUDA_PATH || ! -d $CUDA_PATH ]]; echo $?
cygpath -m "$CUDA_PATH"
```
what does it give you?

**Comment by 1480c1** [comment]
After successfully compiling, you should find `ffmpeg.exe` under `local64/bin-video` or `local32/bin-video`

**Comment by 1480c1** [comment]
> I also added the paths in custom_profile. But it seems this did nothing to affect build process.

Also, https://github.com/m-ab-s/media-autobuild_suite/blob/d0254119d7dfafc2b67a3c7fc1a5cdd6962aa605/README.md#you-do-not-need-to-do-the-following-if-you-installed-the-sdk-with-the-default-locations-etc

**Comment by psisis** [comment]
Hmm, maybe I'm just stupid. I found /local64/bin-video/ffmpeg.exe and tried various stuff. At first glance it looks like cuda was enabled properly. I have codecs such as hevc_cuvid h264_cuvid and nvenc 

I even tried hevc_cuda --> hevc_nvenc (for what it's worth) and it's coding properly!

-hwaccel cuvid didn't work though, but maybe because I have to manually set software filters?

Anyway, thanks for this piece of software! It's invaluable on Windows. Now I have to learn how to use ffmpeg..

P.S The first command returned 0 for me, not a 1, second command repeated the `C:\Progra~1\Nvidia~1\..` path. Maybe the package has a small bug somewhere, reporting a false negative during make?

**Comment by 1480c1** [comment]
Maybe you should check your environment variables since for me, `echo $CUDA_PATH` produces the whole `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0`

**Comment by psisis** [comment]
Well, that's the thing. My System variables are set up correct. `CUDA_PATH` points to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2`

```
echo %CUDA_PATH%
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
```

I also have a `CUDA_PATH_V10_2` entry pointing to same location

Don't know if the different version is at play, but I suppose it shouldn't cause issues

That directory is also both in User and System PATH

**Comment by psisis** [comment]
If it helps. The way the error came was during compilation of ffmpeg-git. Compile.log says

```
Running git update for ffmpeg...
[1m┌ ffmpeg git (B[m ......................................... [[311mRecently updated(B[m]
[1m├(B[m Until SVT-AV1 issues a fix, libsvtav1 must be disabled while libsvthevc is enabled....
[1m├(B[m Changing options to comply to nonfree...
[311mCUDA_PATH environment variable not set or directory does not exist.(B[m
patch unexpectedly ends in middle of line
[1m├(B[m Compiling [1mstatic(B[m FFmpeg... 
```
Right after saying Cuda path not found, it says **patch unexpectedly ends in middle of line**

Maybe it is a problem for the folks at ffmpeg-git Idk.
