### ISSUE TITLE
logs and logs.zip missing

### ISSUE THREAD

**Issue by flip111** [m-ab-s/media-autobuild_suite#1507]
I tried to do a build, see belowed for the attached files which options i choose

[terminal.txt](https://github.com/m-ab-s/media-autobuild_suite/files/3992665/terminal.txt)

An additional msys widow popped up which was closed when i came back to the computer. I can not find any logfiles or logs.zip. A lot of things have been build though ..

**Comment by 1480c1** [comment]
If the build was successful, the suite doesn't generate a logs.zip (rather, it deletes it). If you want to see if it was successful, look for a file called `last_successful_run` or look through CHANGELOG.txt

https://github.com/m-ab-s/media-autobuild_suite/blob/de8b66ddafcf44e0d1ea25e07f52a66e2be747a0/build/media-suite_helper.sh#L1875-L1876

**Comment by flip111** [comment]
Do you accept a PR where i put that information into the readme?

**Comment by 1480c1** [comment]
Sure, it would be good to clarify these things so that there isn't much confusion in the future

**Comment by flip111** [comment]
on my system the contents of `CHANGELOG.txt` are

```

Build start: 2019-12-22 01:28:46 +0100

```
