### ISSUE TITLE
[Msys2] [bug] python3-docutils should change to python-docutils

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#1511]
Now the package name is "mingw64/mingw-w64-x86_64-python-docutils 0.15.2-1" and "mingw32/mingw-w64-i686-python-docutils 0.15.2-1"

But the script still check "python3-docutils" and said not found.

**Comment by LigH-de** [comment]
That doesn't fix anything for me. Here is the loop for every run of the suite now:

```
-------------------------------------------------------------------------------
You have more packages than needed!
Do you want to remove them?
-------------------------------------------------------------------------------

Remove:
mingw-w64-i686-python-docutils
mingw-w64-x86_64-python-docutils
remove packs [y/n]? y

...

-------------------------------------------------------------------------------
You're missing some packages!
Do you want to install them?
-------------------------------------------------------------------------------

Install:
mingw-w64-i686-python3-docutils
mingw-w64-x86_64-python3-docutils
install packs [y/n]? y
Löse Abhängigkeiten auf...

Pakete (2) mingw-w64-i686-python-docutils-0.15.2-1  mingw-w64-x86_64-python-docutils-0.15.2-1
```

[update.log](https://github.com/m-ab-s/media-autobuild_suite/files/4015011/update.log) (partially in German but you will see what happens)

**Comment by 1480c1** [comment]
Try rerunning with latest commit and then after it finishes, try again

or just run mintty and
```bash
source /build/media-suite_helper.sh
do_pacman_remove python3-docutils
```

**Comment by LigH-de** [comment]
The current script behaves just like before:

- suggest to remove python-docutils
- remove python-docutils
- pretend to install python**3**-docutils
- install python-docutils instead
- unable to set installation reason for python**3**-docutils because it's not installed

[update.log](https://github.com/m-ab-s/media-autobuild_suite/files/4017868/update.log)

**Comment by 1480c1** [comment]
Try again with new commit

**Comment by LigH-de** [comment]
Passed now. :+1:
