### ISSUE TITLE
CantPackException: superfluous data between sections   mingw64 

### ISSUE THREAD

**Issue by xiedeacc** [m-ab-s/media-autobuild_suite#1518]
upx: D:/code/media-autobuild_suite/local64/bin-video/ffplay.exe: CantPackException: superfluous data between sections (try --force)

does this matter?

**Comment by 1480c1** [comment]
At what point did this message appear? During compilation with the suite or at runtime?

**Comment by 1480c1** [comment]
@xiedeacc, ping?

**Comment by xiedeacc** [comment]
compilation

**Comment by 1480c1** [comment]
Although I can reproduce, I don't think it's necessarily an issue

**Comment by Boscop** [comment]
@xiedeacc I get the same error with ffprobe.exe (but not with ffmpeg.exe). Did you confirm that with --force, the exe still works correctly afterwards? :)

**Comment by wiiaboo** [comment]
I remember ffplay having some issues with upx; don't use upx, basically.

**Comment by gonzalezvaguiner** [comment]
had to use --force on ffmpeg, but not on ffplay
they both worked and cut size on more than half
