### ISSUE TITLE
Compilation fails when trying to clone opus git.

### ISSUE THREAD

**Issue by dystopia2017** [m-ab-s/media-autobuild_suite#1523]
logs.zip https://0x0.st/z5Cr.zip 

https://i.imgur.com/Pz6okiL.png
The opus git is up, but it fails at this stage and exits.

**Comment by 1480c1** [comment]
`git: command not found`

Try deleting msys64 and rerunning

**Comment by dystopia2017** [comment]
logs.zip https://0x0.st/zRzG.zip

Hi, thanks for the reply. I deleted msys64 and reran it. It fails again with a similar error 
https://i.imgur.com/LALtZgT.png

Is there somthing else I can try?

**Comment by 1480c1** [comment]
can toy instead take a screenshot of the suite root folder and the insides of the build folder?

**Comment by dystopia2017** [comment]
sure.
https://i.imgur.com/Gvx6P4x.png

**Comment by 1480c1** [comment]
Can you open up `mintty` and type
```bash
source /build/media-suite_helper.sh
set -x
do_vcs "https://gitlab.gnome.org/GNOME/libxml2.git"
```
and show me the output?

**Comment by dystopia2017** [comment]
https://i.imgur.com/LVl9qGv.png

**Comment by 1480c1** [comment]
how about running
```bash
ping gitlab.gnome.org
ping gitlab.com
```
from inside `mintty`?

**Comment by dystopia2017** [comment]
https://i.imgur.com/vfLZBDV.png
ping seems to work fine

**Comment by 1480c1** [comment]
Then how about
```bash
git clone "https://gitlab.gnome.org/GNOME/libxml2.git"
```
?

**Comment by dystopia2017** [comment]
That returns
"bash: git: command not found"
https://i.imgur.com/Q16YSul.png

**Comment by 1480c1** [comment]
try
```bash
pacman -S git
```
and rerun the suite

**Comment by dystopia2017** [comment]
https://i.imgur.com/7adneEO.png
This seems to be the issue, loads of errors when installing git
it seems the path doesn't exist?

**Comment by 1480c1** [comment]
Does `P:\` have enough space?

**Comment by dystopia2017** [comment]
Yeah it has close to 1tb free and im using admin account, there is nothing stopping me making directories there.

**Comment by 1480c1** [comment]
I'm not sure what could be the problem since I can't reproduce the problem on my machines.

Could you try
```bash
/usr/bin/git --version
echo "$PATH"
```

**Comment by dystopia2017** [comment]
https://i.imgur.com/e4HSo6D.png
Thanks for trying to help, I am unsure why it's failing with git also. I am going to try set up a virtual machine later and see if I have any luck there

**Comment by wiiaboo** [comment]
Is P:\ formatted in NTFS and not a network drive?

**Comment by dystopia2017** [comment]
> 
> 
> Is P:\ formatted in NTFS and not a network drive?

It is an exFAT drive and is not a network drive

**Comment by wiiaboo** [comment]
Then you haven't read the README where it explicitely says an NTFS drive is required.

**Comment by dystopia2017** [comment]
> 
> 
> Then you haven't read the README where it explicitely says an NTFS drive is required.

Yes it is working correctly from an NTFS formatted drive, sorry for raising the issue. And thanks for the autobuild script set.
