### ISSUE TITLE
[Msys2] The update check get sth wrong for me.

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#1528]
Even though there's a git update of the project but the update check still says up-to-date.

For example, I found that the aom project said up to date yesterday, And I found it's not the latesat commit.

https://aomedia.googlesource.com/aom/

I tried to delete the git folder and let m-ab-s rebuild it.

But the same problem happened now.

> 
> [313m04:05:05(B[m   Running git update for aom...
> [313m04:05:11(B[m [1maom git (B[m .......................................... [[32mUp-to-date(B[m]

my local aom commit is a0b3d1a.

https://aomedia.googlesource.com/aom/+/a0b3d1a7ec9b73985e9ad184ba55d318e20e47ff

but the newset the commit I found (in origin master) is 0d89a63.

https://aomedia.googlesource.com/aom/+/0d89a630fbb8cf8f478dec509093a516e78e7e27

It's strange which I done the git update fine but the commit of the ab-suite branch don't change.

PS: x265 hg / mplayer svn works fine.

**Comment by 1480c1** [comment]
I will check it out in the morning, right now I have power outage on my dev machine
