### ISSUE TITLE
HTTP error 404: openal-pkgconfig.patch lost on gist

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1531]
`Error 404 while downloading https://gist.githubusercontent.com/Helenerineium/406d836f81f99a0656bdaf885265ca2e/raw/openal-pkgconfig.patch`

Did user Helenerineium disappear or get renamed?

**Comment by 1480c1** [comment]
Perhaps he did, I no longer see his name under the contributor tab

**Comment by 1480c1** [comment]
Uploaded a local copy I had for now, if we have problems with it, I might just remove openal depending on how hard it is to figure out.
