### ISSUE TITLE
Building FFMPEG with pthreads yields incorrect CBR UDP TS output.   

### ISSUE THREAD

**Issue by Svyatk0** [m-ab-s/media-autobuild_suite#1532]
This is a rather odd behaviour but i will try to explain. 
Basically i am building static ffmpeg with 2 additional options: --disable-w32threads and --enable-pthreads (likely not needed). Reason i need pthreads is the CBR TS output with the use of  additional parameters (bitrate, burst_bits, etc.), basically same as ticket #888

The build succeeds without any problems, but i have noticed that when i use those additional parameters, my TS output comes out "broken" e.g. 
Encoding and muxing a TS @ 2.5Mbps or any other bitrate, always results in output stream @ ~ 1.5Mbps, even though ffmpeg is showing that its streaming at specified bitrate: 
`frame=   88 fps= 17 q=20.0 size=    1978kB time=00:00:04.92 bitrate=3291.4kbits/s speed=0.976x`

see side-by-side screenshot : https://1drv.ms/u/s!Ar_ePfSDBV8xgaPlegjHb_xZpvkezAE?e=X1aWn7

The same ffmpeg command used without pthreads, streams at correct bitrate (but without CBR ofcourse)

Reason i am raising it here and not in FFMPEG forum is to ask whether fallback and support to pthreads actually works when building with this suite. I have not found traces of pthreads-w32 along with pthread.h and libpthreadGC2.a so was wondering what pthreads are used when disabling -w32threads.

**Comment by 1480c1** [comment]
I'm not sure if it works properly, you would probably need to look through each of the packages you have enabled to see if any of them are forcing w32threads on both through the suite and through ffmpeg's configure script

**Comment by wiiaboo** [comment]
There shouldn't be any lib "forcing" w32threads. There might some that require pthreads, like decklink, libzvbi, vmaf. If you don't have any of those enabled, w32threads will be used by default, but if you explicitely enable pthreads or any of the above libs, the suite will not prevent pthreads from being used and will explicitely disable w32threads.

There's a patch about UDP up for review on their mailing list.

Either way, it would be a FFmpeg issue. The suite/msys2 uses winpthreads, which includes:
```
find /mingw64/{x86_64-w64-mingw32/,}lib -name '*pthread*'
/mingw64/x86_64-w64-mingw32/lib/libpthread.a
/mingw64/x86_64-w64-mingw32/lib/libwinpthread.a
```
and the suite would need to compile GCC to use something else.
