### ISSUE TITLE
Probably unrelated. FLTMGR_FILE_SYSTEM BSOD's

### ISSUE THREAD

**Issue by moisespr123** [m-ab-s/media-autobuild_suite#1539]
This is probably unrelated, but it seems that a component in the suite doesn't like Windows 10 running on an AMD Ryzen 9 3950X CPU. 

I tried changing the core numbers, but it doesn't matter, as at some random point, I'll get the FLTMGR_FILE_SYSTEM BSOD. It usually happens when it is building something.

As a workaround, I'm building the suite on another PC.

These BSODs have been happening for some time in my system, and it only happens when running the suite. I don't experience BSODs otherwise. Tried cloning the repo to a different drive with no success.

**Comment by moisespr123** [comment]
The below crashes all happened when running the suite at different times.

![image](https://user-images.githubusercontent.com/16326634/73022576-dbad3700-3df7-11ea-8b2f-358e9ffa6daa.png)

**Comment by moisespr123** [comment]
After cleaning the msys64 and local64 folders, It seems the BSOD happens when building fdk-aac.

It's either the FLTMGR_FILE_SYSTEM or a PAGE_FAULT_IN_NONPAGED_AREA.

**Comment by wiiaboo** [comment]
Not the right place for this type of issue.
