### ISSUE TITLE
Autobuild failed. configure failed. 

### ISSUE THREAD

**Issue by gaamaaresosa** [m-ab-s/media-autobuild_suite#1543]
Windows 10 64bit
Path: C:\ffmpegbuild
Version: 27 JAN 2020

Build fails even after trying many times.
Below is the error:

23:32:26
        Starting 32bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
23:32:33
        Starting 32bit compilation of global tools
23:32:33   Running git update for jo...
23:32:35 ┌ jo git  ................................... [Recently updated]
23:32:35 ├ Running autoreconf...
23:32:48 ├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
../configure --prefix=/local32 --disable-shared --enable-static --bindir=/local32/bin-global
configure: WARNING: unrecognized options: --disable-shared, --enable-static
configure: loading site script /mingw32/etc/config.site
checking for gcc... ccache gcc
checking whether the C compiler works... no
configure: error: in `/build/jo-git/build-32bit':
configure: error: C compiler cannot create executables
See `config.log' for more details
configure failed. Check C:/ffmpegbuild/build/jo-git/build-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
23:32:52   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/irhm.zip
Copy and paste [logs.zip](https://0x0.st/irhm.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
[ab-suite.configure.log](https://github.com/m-ab-s/media-autobuild_suite/files/4118608/ab-suite.configure.log)
[config.log](https://github.com/m-ab-s/media-autobuild_suite/files/4118609/config.log)

**Comment by 1480c1** [comment]
Could you see if https://github.com/1480c1/media-autobuild_suite/tree/ccache works?

(https://github.com/1480c1/media-autobuild_suite/commit/bef084cffdf28ad71daf84b7d686a170d5269a09)

**Comment by gaamaaresosa** [comment]
Thanks for your swift reply.

    REMOVED: echo.export CC="ccache gcc"
    REMOVED: echo.export CXX="ccache g++"
    ADDED: echo.export CC="${LOCALDESTDIR}/bin/gcc.bat"
    ADDED:  echo.export CXX="${LOCALDESTDIR}/bin/g++.bat"

Same error:
![error](https://user-images.githubusercontent.com/21296884/73202670-88254b00-4161-11ea-8698-abaef7ccad36.png)

Why configure: WARNING: unrecognized options: --disable-shared, --enable-static >

gaamaa

**Comment by 1480c1** [comment]
can you open `C:\ffmpegbuild\mintty` and type
```bash
source /build/media-suite_helper.sh
source /local32/etc/profile2.local
do_vcs "https://github.com/jpmens/jo.git"
do_autoreconf
do_separate_confmakeinstall global
```

and print out the output here?

**Comment by gaamaaresosa** [comment]
gaamaa@BRAYSUNG /trunk
$ source /build/media-suite_helper.sh
gaamaa@BRAYSUNG /trunk
$ source /local32/etc/profile2.local
gaamaa@BRAYSUNG /trunk
$ do_vcs "https://github.com/jpmens/jo.git"
+ case ${2:-$(vcs_get_current_type)} in
++ vcs_get_current_type
+++ get_first_subdir -f
+++ local subdir=jo-git fullpath=false OPTION OPTIND
+++ getopts :f OPTION
+++ case "$OPTION" in
+++ fullpath=true
+++ getopts :f OPTION
+++ shift 1
+++ [[ jo-git != \/\b\u\i\l\d\/\j\o\-\g\i\t ]]
+++ true
+++ printf %s /build/
+++ echo jo-git
++ cd /build/jo-git
++ for file in .*
++ case $file in
++ false
++ for file in .*
++ case $file in
++ false
++ for file in .*
++ case $file in
++ git rev-parse --is-inside-work-tree
++ echo git
++ return 0
+ git config remote.origin.url
+ git remote set-url origin https://github.com/jpmens/jo.git
+ git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
+ git checkout --no-track -fB ab-suite
Reset branch 'ab-suite'
++ vcs_get_latest_tag origin/HEAD git
++ case ${2:-$(vcs_get_current_type)}/${1:-unknown} in
++ false
++ echo origin/HEAD
+ git reset --hard origin/HEAD
HEAD is now at aa2579d Merge pull request #107 from Roguelazer/issue-105
┌ jo git  ............................................. [Recently updated]
gaamaa@BRAYSUNG /build/jo-git
$ do_autoreconf
Running autoreconf in jo-git
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
gaamaa@BRAYSUNG /build/jo-git
$ do_separate_confmakeinstall global
Running configure in jo-git
configure: WARNING: unrecognized options: --disable-shared, --enable-static
configure: loading site script /mingw32/etc/config.site
checking for gcc... /local32/bin/gcc.bat
checking whether the C compiler works... no
configure: error: in `/build/jo-git/build-32bit':
configure: error: C compiler cannot create executables
See `config.log' for more details
Running make in jo-git
make: *** No targets specified and no makefile found.  Stop.
make: *** No targets specified and no makefile found.  Stop.
Running install in jo-git
make: *** No rule to make target 'install'.  Stop.
make: *** No rule to make target 'install'.  Stop.
gaamaa@BRAYSUNG /build/jo-git
$

**Comment by gaamaaresosa** [comment]
Remaining last reply:

Running configure in jo-git
configure: WARNING: unrecognized options: --disable-shared, --enable-static
configure: loading site script /mingw32/etc/config.site
checking for gcc... /local32/bin/gcc.bat
checking whether the C compiler works... no
configure: error: in `/build/jo-git/build-32bit':
configure: error: C compiler cannot create executables
See `config.log' for more details
Running make in jo-git
make: *** No targets specified and no makefile found.  Stop.
make: *** No targets specified and no makefile found.  Stop.
Running install in jo-git
make: *** No rule to make target 'install'.  Stop.
make: *** No rule to make target 'install'.  Stop.
gaamaa@BRAYSUNG /build/jo-git

**Comment by 1480c1** [comment]
can you zip up `build/jo-git` or run `zip_logs` from that folder and send `build/logs.zip`?

**Comment by gaamaaresosa** [comment]
[jo-git.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4118783/jo-git.zip)
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4118787/logs.zip)

**Comment by 1480c1** [comment]
I will try to figure out more, but in the meanwhile, can you try disabling building jo?

Change `jo=1` to `jo=2` in `media-autobuild_suite.ini` in build folder

**Comment by gaamaaresosa** [comment]
Can I resume 2 changes done in the bat file ?
Or same will do ?

**Comment by 1480c1** [comment]
You can revert the changes in the bat file since I don't think that's the issue

**Comment by gaamaaresosa** [comment]
This is with new 2 lines added today in bat file :
Seems same error:

00:38:08
        Starting 32bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
00:38:14
        Starting 32bit compilation of global tools
00:38:15   Running git clone for jq...
00:38:21 ┌ jq git  ................................... [Recently updated]
00:38:22 ├ Installing oniguruma... done
00:38:24 ├ Running autoreconf...
00:38:58 ├ Running configure...
Likely error (tail of the failed operation logfile):
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... /local32/bin/gcc.bat
checking whether the C compiler works... no
configure: error: in `/build/jq-git/build-32bit':
configure: error: C compiler cannot create executables
See `config.log' for more details
configure failed. Check C:/ffmpegbuild/build/jq-git/build-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
00:39:04   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/irhI.zip
Copy and paste [logs.zip](https://0x0.st/irhI.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by 1480c1** [comment]
hmm, seem's there's some other issue. Could you try deleting msys64 folder and rerunning?

**Comment by gaamaaresosa** [comment]
Same error with original bat file used.

**Comment by gaamaaresosa** [comment]
>Could you try deleting msys64 folder and rerunning?
I will

**Comment by gaamaaresosa** [comment]
May be latest Windows 10 ?
Version 1909 (25)
We face some security issues on our software development with this new OS

**Comment by gaamaaresosa** [comment]
Reinstalling...
- Downloading and unpacking msys2 basic system

-------------------------------------------------------------------------------

7-Zip (a) 18.06 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2018-12-30


Extracting archive:
--
Path =
Type = tar
Code Page = UTF-8

Everything is Ok

Folders: 695
Files: 13835
Size:       238561203
Compressed: 7440384

**Comment by gaamaaresosa** [comment]
No luck...
Same error:

00:55:19
        Starting 32bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
00:55:25
        Starting 32bit compilation of global tools
00:55:26   Running git update for jq...
00:55:28 ┌ jq git  ................................... [Recently updated]
00:55:29 ├ Installing oniguruma... done
00:55:32 ├ Running autoreconf...
rm: cannot remove 'build-32bit': Device or resource busy
00:56:04 ├ Running configure...
Likely error (tail of the failed operation logfile):
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... ccache gcc
checking whether the C compiler works... no
configure: error: in `/build/jq-git/build-32bit':
configure: error: C compiler cannot create executables
See `config.log' for more details
configure failed. Check C:/ffmpegbuild/build/jq-git/build-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
00:56:10   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/irhC.zip
Copy and paste [logs.zip](https://0x0.st/irhC.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by gaamaaresosa** [comment]
Usually we need ffmpeg libraries for build ffmpeg.exe
Are you downloading via script ?
Where do you place it and which path ?
I see no such files on my folder.
If I need to edit some ffmpeg.c file code, can I do that before build ?
I do that in rdp/ffmpeg-windows-build-helpers

**Comment by 1480c1** [comment]
My path is usually
```bash
git clone https://github.com/m-ab-s/media-autobuild_suite.git
cd media-autobuild_suite
./media-autobuild_suite.bat
```
inside my D:\ drive. I am on 1909 too

For needing to apply edits to ffmpeg.c, you should look into the [custom patches](https://github.com/m-ab-s/media-autobuild_suite#custom-patches) section

**Comment by gaamaaresosa** [comment]
I am not familiar with github path.
Could you please test in simple local harddisk path ?
D:\AnyName\media-autobuild_suite.bat

**Comment by 1480c1** [comment]
It just downloads the suite into the `media-autobuild_suite` folder and results in `D:\media-autobuild_suite\media-autobuild_suite.bat`

**Comment by gaamaaresosa** [comment]
Great !
So you could fix it ...

**Comment by 1480c1** [comment]
Maybe, depends on if I can actually figure out what's the problem, because it seems that everything works fine, except when running a configure script

**Comment by 1480c1** [comment]
Actually, can you show me the output of local32/bin/gcc.bat?

**Comment by gaamaaresosa** [comment]
I hope you scanned each line on my config.log

configure:2608: error: in `/build/jo-git/build-32bit':
configure:2610: error: C compiler cannot create executables
See `config.log' for more details

**Comment by 1480c1** [comment]
Yes, I saw that. I'm trying to figure out why gcc.bat is not working for you

**Comment by gaamaaresosa** [comment]
You wrote: Actually, can you show me the output of local32/bin/gcc.bat?

This time I tried at P:\ drive, because some time Windows protects C:\ drive more.

@echo off >nul 2>&1
rem() { "$@"; }
rem test -f nul && rm nul
rem /mingw32/bin/ccache --help > /dev/null 2>&1 && /mingw32/bin/ccache /mingw32/bin/gcc "$@" || /mingw32/bin/gcc "$@"
rem exit $?
P:/ffmpegbuild/msys64/mingw32/bin/ccache.exe P:/ffmpegbuild/msys64/mingw32/bin/gcc.exe %*

**Comment by 1480c1** [comment]
Okay, after moving it, what is the result?

**Comment by gaamaaresosa** [comment]
This time I opted only 32bit binary to keep the case simple.
Still same error...
You don't get any error there ?

**Comment by 1480c1** [comment]
Nope, have not been able to reproduce on two separate machines

**Comment by gaamaaresosa** [comment]
Oh!
Should I try on other system here with same Windows 10 64bit ?

**Comment by 1480c1** [comment]
That would be good to see

**Comment by gaamaaresosa** [comment]
I am booting...

**Comment by gaamaaresosa** [comment]
I can give you Teamviewer if you come on private mail

**Comment by 1480c1** [comment]
I probably won't need it unless the second machine also is failing, but if it does fail, you can email me at "ccom @ randomderp.com" (remove space)

**Comment by gaamaaresosa** [comment]
Ok in 10 mins I will update you...

**Comment by gaamaaresosa** [comment]
processing started...

**Comment by gaamaaresosa** [comment]
If all is going fine, please help me to add Newtek NDI option also.
--enable-libndi_newtek --enable-nonfree

**Comment by gaamaaresosa** [comment]
Super !
Same error on the other system too

**Comment by gaamaaresosa** [comment]
I will mail you the teamviewer ID in 5 mins

**Comment by 1480c1** [comment]
> Super !
> Same error on the other system too

Is a fresh copy from the internet?



> If all is going fine, please help me to add Newtek NDI option also.
> --enable-libndi_newtek --enable-nonfree

https://github.com/m-ab-s/media-autobuild_suite/commit/75dfb80d5f1e1a7cffad8f11388da195902e75b5
newtek was removed from both the suite and ffmpeg

**Comment by gaamaaresosa** [comment]
TV id sent

**Comment by 1480c1** [comment]
@gaamaaresosa are you able to compile properly?

**Comment by gaamaaresosa** [comment]
Hi thanks for your concern.
I couldn't succeed, so I left it.

**Comment by 1480c1** [comment]
I see, my consolences

**Comment by gaamaaresosa** [comment]
No problem, I will give a try later again.

**Comment by 1480c1** [comment]
I will close since I don't think there's anything the suite can do to fix this if you want to reopen, you can write that here again
