### ISSUE TITLE
What version of ffmpeg?

### ISSUE THREAD

**Issue by alex-devPY** [m-ab-s/media-autobuild_suite#1544]
hello!

What version of ffmpeg used to compile?
Can I compile using local ffmpeg repo?

tnx.

**Comment by 1480c1** [comment]
master branch is compiled by default, to choose something else, you need to use [ffmpeg_extra.sh](https://github.com/m-ab-s/media-autobuild_suite#custom-patches), but that would make it unsupported by the suite
