### ISSUE TITLE
After ffmpeg is built, what next ? (not your bug)

### ISSUE THREAD

**Issue by mrfrieza** [m-ab-s/media-autobuild_suite#1546]
Hello,

(Sorry) Once the build has been compiled, and I've got the local64 folder containing the bin, bin-audio, bin-video... folders, what should I do with that ? 

I usually use Zeranoe's which only contains a "bin" folder, and I just had to rename the whole thing ffmpeg and add "C:/ffmpeg/bin" into the environment variables and it worked.

Here, I get a local64 folder with multiple bin-xxx folders.. 

I've tried to rename local64 into ffmpeg, add it to C:/ and add the environment variable C:/ffmpeg/bin-video (as this is where the ffmpeg.exe is) but when I try to run a command with libsvt_av1, it says it's unrecognized .. ?

Very sorry to ask this of you, I'm a total rookie in this... 

Thank you !

**Comment by gapbl4** [comment]
If you chose "Mimic Zeranoe", then it doesn't include libsvt_av1.

**Comment by 1480c1** [comment]
The bin-*** folders are where the programs are installed to based on their main usage, to use them, you can either call them directly `C:\suite\local64\bin-video\ffmpeg.exe -i ...` or add them to the environment variable PATH, I recommend you to search how to do it yourself.

So, what you did was correct, however, it does not seem like your ffmpeg contained libsvt_av1

**Comment by mrfrieza** [comment]
So basically I thought that compiling FFmpeg would add libsvt_av1 to FFmpeg and call SvtAv1Enc from FFmpeg without having to pipe or anything.. 

I guess I was wrong, it compiles FFmpeg separately from the "other" tools (.exe files) that are with it.

I managed to make SvtAv1Enc.exe work though so I guess that's a start ^^

Thanks for the replies ! ;)

**Comment by gapbl4** [comment]
If you chose Yes when asked for custom options, then you need to check the ffmpeg_options.txt file.
—libsvtav1 is commented out with # in that file by default, that’s why you might not have it in you ffmpeg.exe.
Or you could choose to build all and skip the options file, and have 100MiB+ ffmpeg.exe file.
