### ISSUE TITLE
x265 will migrate to Git

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1548]
Until June 2020, bitbucket will remove Mercurial support.

The new Git repo URL will be: https://bitbucket.org/multicoreware/x265_git/

**Comment by 1480c1** [comment]
Holy heck that url looks ugly

**Comment by LigH-de** [comment]
Temporary issue ... or untested patch?

```
  Running git clone for x265_git...
x265_git git seems to be down
```

**Comment by 1480c1** [comment]
Seems to work for me, perhaps you had some intermittent internet issues?

**Comment by wiiaboo** [comment]
https://bitbucket.status.atlassian.com/incidents/7y89r0ynqyg9

**Comment by LigH-de** [comment]
Again? ... From [ab-suite.git.clone.log](https://github.com/m-ab-s/media-autobuild_suite/files/4165010/ab-suite.git.clone.log):

```
+ git clone https://bitbucket.org/multicoreware/x265_git.git x265_git-git
Cloning into 'x265_git-git'...
error: RPC failed; curl 56 OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)
```

Tried it 3 times. Data is being retrieved, several subdirectories below .git, I believe objects/pack/ is being downloaded while the transmission is interrupted.

Shall I "Report an issue" to Atlassian/Bitbucket?

**Comment by wiiaboo** [comment]
If other repositories are working fine for you, yeah, it's a bitbucket issue.

**Comment by LigH-de** [comment]
I wonder if this might be an MSYS2 specific case. Here from an interactive console:

```
$ git clone https://bitbucket.org/multicoreware/x265_git.git x265_git-git
Cloning into 'x265_git-git'...
remote: Counting objects: 88154, done.
remote: Compressing objects: 100% (88115/88115), done.
remote: Total 88154 (delta 2853), reused 85263 (delta 0)
error: RPC failed; curl 56 OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)
Receiving objects: 100% (88154/88154), 277.47 MiB | 1.58 MiB/s, done.
Resolving deltas: 100% (2853/2853), done.
```

Apparently the transfer was complete. Yet it is handled like an error.

**Comment by LigH-de** [comment]
I have no clue, because it happens to nobody else; and suddenly (after cloning x264 and adjacent ffmpeg/ffms2/lsmash), it doesn't happen for x265 anymore. So I give up and hope it be gone.
