### ISSUE TITLE
Error when downloading openh264 dll

### ISSUE THREAD

**Issue by jdlyga** [m-ab-s/media-autobuild_suite#1550]
When building openh264, the link to download the dll fails:

![image](https://user-images.githubusercontent.com/4921961/73761426-d7104900-473c-11ea-9ab1-febc80f67d7a.png)

Looks like an issue with openh264's site, or the file was moved.  Happened multiple times today.  As an alternative, we can use the link to openh264's github release: 

https://github.com/cisco/openh264/releases/download/v2.0.0/openh264-2.0.0-win64.dll.bz2

``` bash
10:36:53 ┌ srt git  ..................................... [Updates found]
10:36:58 ├ Running cmake...
10:37:31 ├ Running build...
10:38:30 ├ Running install...
10:38:31 ├ Stripping...
10:38:31 └ srt-git  ........................................... [Updated]
10:41:06 └ libopenh264.dll.bz2  ................................ [Failed]
Error 000 while downloading http://ciscobinary.openh264.org/openh264-2.0.0-win64.dll.bz2
<Ctrl+c> to cancel build or <Enter> to continue
if you're sure nothing depends on it.
10:54:19 ├ Installing ladspa-sdk... done
10:54:57   Running git update for ffmpeg...
```

**Comment by 1480c1** [comment]
Although I'm able to download the dll.bz2 using the direct link, It doesn't seem that openh264.org is valid(?) anymore

**Comment by berbunda** [comment]
I am from Russia and i get error 403 due try to downloading http://ciscobinary.openh264.org/openh264-2.0.0-win64.dll.bz2
I used proxifier to proxify connect to openh264.org via my vps in Finland. And succesfully download and pass this step
