### ISSUE TITLE
Rust Installation failed due to curl: (60) SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by mmshasan** [m-ab-s/media-autobuild_suite#1553]
I've build FFMPEG successfully twice but this time I failed. I think including one or more packages causing this issue. In my previous build **Rust** never showed up or didn't interrupt. I am pretty sure something wrong in my end. I am not an expert which why came here to resolve this issue.

Would appreciate if you guys can help... Thanks in advance.

``` bash
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
./rustup.sh -v -y --no-modify-path --default-host=x86_64-pc-windows-gnu --default-toolchain=stable
info: downloading installer
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe /c/Users/Public/Documents/Wondershare/CreatorTemp/tmp.N8B1p9AxqP/rustup-init.exe
```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4193187/logs.zip)

![rust](https://user-images.githubusercontent.com/6724259/74350663-3aa31200-4de0-11ea-88a6-d23a4bc85881.jpg)

**Comment by 1480c1** [comment]
Are you building this on a work computer or something behind a corporate firewall or on a machine managed by an IT department? Can you try to go to <https://static.rust-lang.org> and see if you can access it properly without any errors?

**Comment by mmshasan** [comment]
Thanks for your prompt response. I am building it on my personal laptop. I have excluded https://static.rust-lang.org/ from Kaspersky Firewall and Voila ...... It' working now. Thanks a lot.

![rust_done](https://user-images.githubusercontent.com/6724259/74359360-56f97b80-4ded-11ea-8ddb-5be86f21b032.jpg)
