### ISSUE TITLE
Interactively building x265: make gets verbose

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1559]
The suite installs an MSYS2/MinGW environment. Sometimes I use an interactive mintty shell to build x265 with an own set of semi-automated shell scripts. I was used to reading **cmake** progress messages during this building sequence.

Quite recently I noticed that the console output now also includes verbose messages produced by **make**. Is there any tweak in the suite which may have caused this? Or is the current version of make suddenly so verbose by default?

![make_vs_cmake](https://user-images.githubusercontent.com/5917225/74947610-66835080-53fb-11ea-88d3-ce47ef69e158.png)

**Comment by 1480c1** [comment]
Nothing in the suite should apply `V=1` or verbose to make, rather your log does seems like it's actually verbose (make wise, since that would also print the gcc commands too)

**Comment by LigH-de** [comment]
My build scripts call `make ${MAKEFLAGS}` but I checked `export` and there is no such variable present. Can you imagine any other places to check?

**Comment by 1480c1** [comment]
try running make directly in maybe a cmd prompt or something other than mintty

**Comment by LigH-de** [comment]
Cound not find a reason yet, but will add the parameter `make --no-print-directory` to my scripts as a workaround.
