### ISSUE TITLE
Viewing DVD Video File Information with FFMPEG, missing subtitle stream information.

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1560]
Viewing DVD Video File Information with FFMPEG:
ffprobe vts_01_2.vob
[mpeg2video @ 02cd0480] Invalid frame dimensions 0x0.
    Last message repeated 11 times
Input #0, mpeg, from 'vts_01_2.vob':
  Duration: 00:25:49.83, start: 1683.401567, bitrate: 5542 kb/s
    Stream #0:0[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, top first), 720x480 [SAR 8:9 DAR 4:3], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 448 kb/s
    Stream #0:2[0x81]: Audio: ac3, 48000 Hz, stereo, fltp, 448 kb/s
    Stream #0:3[0x1bf]: Data: dvd_nav_packet
Unsupported codec with id 100357 for input stream 3

The 3 subtitle streams are missing. I wonder if there are any missing libraries that are not compiled in?

**Comment by wiiaboo** [comment]
This is not the ffmpeg-user mailing list.

And likely not missing libraries.
