### ISSUE TITLE
Request: can use Emscripten compile FFMPEG for Javascript?

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1561]
can use Emscripten compile FFMPEG for Javascript?

**Comment by 1480c1** [comment]
https://github.com/Kagami/ffmpeg.js/
https://itnext.io/build-ffmpeg-webassembly-version-ffmpeg-js-part-1-preparation-ed12bf4c8fac

Please google it first before asking here, anything outside of the way the suite compiles is out of scope
