### ISSUE TITLE
Bug/enhancement  in  Media-suite_compile.sh

### ISSUE THREAD

**Issue by pat357** [m-ab-s/media-autobuild_suite#1564]
I should use a PR for this, but PR's never worked out as intended for me !

**1. For egl-angle in MPV:**
```bash
    do_pacman_remove angleproject-git
    _check=(EGL/egl.h)
    if mpv_enabled egl-angle && do_vcs "https://chromium.googlesource.com/angle/angle"; then
    { code }
    elif ! mpv_disabled egl-angle; then
        mpv_disable egl-angle
    fi
```
This will allow you to compile MPV with angle, but only when the headers were updated.
If the headers were not updated, egl-angle will always be disabled by the elif.

It's easy to overcome with an extra if/then:
```bash
    do_pacman_remove angleproject-git
    _check=(EGL/egl.h)
    if mpv_enabled egl-angle; then 
          if do_vcs "https://chromium.googlesource.com/angle/angle"; then
           { code }
          fi
    elif ! mpv_disabled egl-angle; then
        mpv_disable egl-angle
    fi
```

**2. Line 2293 (cyanrip.exe)**
```bash
if flavor=cyan do_vcs "https://git.ffmpeg.org/ffmpeg.git"; then
```
I can't wrap my head around this code....
Is it like
```bash
if [[ $flavor=cyan ]] &&  do_vcs "https://git.ffmpeg.org/ffmpeg.git"; then
or
if [[ $flavor=$cyan ]] &&  do_vcs "https://git.ffmpeg.org/ffmpeg.git"; then
or just
if [[ flavor=cyan ]]  &&  do_vcs "https://git.ffmpeg.org/ffmpeg.git"; then
```
Note that neither flavor/cyan are somewhere written to (or even exist at all).
Does this make the code included between this **if/fi** dead code ??

**3. Builing MPV.exe/com** (line 2137)
This is more an enhancement :
```bash
    _check=(bin-video/mpv.{exe,com})
+    mpv_enabled libmpv-shared && _check+=(bin-video/mpv-1.dll)
    _deps=(lib{ass,avcodec,vapoursynth,shaderc_combined,spirv-cross}.a "$MINGW_PREFIX"/lib/libuchardet.a)
    if do_vcs "https://github.com/mpv-player/mpv.git"; then
        hide_conflicting_libs
        create_ab_pkgconfig
```
By adding the line, the **mpv-1.dll** is checked upon if --enable-libmpv-shared is in MPV_OPTIONS.TXT and will also be stripped properly at the end.
Now I have to strip it manually.

**4. Media-suite_helper.sh**
This is a more a question:
Is there a difference between the way to define a function in the following 2 examples ?
Are these identical ?
I see mostly the first is used but recently the second appeared in the helper function.
```bash
function1() {
    codeblock
}

and

function2() (
    codeblock
)

**Comment by 1480c1** [comment]
> I should use a PR for this, but PR's never worked out as intended for me !

Is there something specifically that is blocking you?

> 
> **1. For egl-angle in MPV:**
> 
> ```shell
>     do_pacman_remove angleproject-git
>     _check=(EGL/egl.h)
>     if mpv_enabled egl-angle && do_vcs "https://chromium.googlesource.com/angle/angle"; then
>     { code }
>     elif ! mpv_disabled egl-angle; then
>         mpv_disable egl-angle
>     fi
> ```
> 
> This will allow you to compile MPV with angle, but only when the headers were updated.
> If the headers were not updated, egl-angle will always be disabled by the elif.
> 
> It's easy to overcome with an extra if/then:
> 
> ```shell
>     do_pacman_remove angleproject-git
>     _check=(EGL/egl.h)
>     if mpv_enabled egl-angle; then 
>           if do_vcs "https://chromium.googlesource.com/angle/angle"; then
>            { code }
>           fi
>     elif ! mpv_disabled egl-angle; then
>         mpv_disable egl-angle
>     fi
> ```

The first example makes since, the second, not so much


> **2. Line 2293 (cyanrip.exe)**
> 
> ```shell
> if flavor=cyan do_vcs "https://git.ffmpeg.org/ffmpeg.git"; then
> ```
> 
> I can't wrap my head around this code....
> Is it like
> 
> ```shell
> if [[ $flavor=cyan ]] &&  do_vcs "https://git.ffmpeg.org/ffmpeg.git"; then
> or
> if [[ $flavor=$cyan ]] &&  do_vcs "https://git.ffmpeg.org/ffmpeg.git"; then
> or just
> if [[ flavor=cyan ]]  &&  do_vcs "https://git.ffmpeg.org/ffmpeg.git"; then
> ```
> 
> Note that neither flavor/cyan are somewhere written to (or even exist at all).
> Does this make the code included between this **if/fi** dead code ??

The line `flavor=cyan do_vcs "https://git.ffmpeg.org/ffmpeg.git"` passes the variable `flavor` with a value of `cyan` to `do_vcs`, so it's for when `${flavor}` is being used
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02
case 7
 
> **3. Builing MPV.exe/com** (line 2137)
> This is more an enhancement :
> 
> ```shell
>     _check=(bin-video/mpv.{exe,com})
> +    mpv_enabled libmpv-shared && _check+=(bin-video/mpv-1.dll)
>     _deps=(lib{ass,avcodec,vapoursynth,shaderc_combined,spirv-cross}.a "$MINGW_PREFIX"/lib/libuchardet.a)
>     if do_vcs "https://github.com/mpv-player/mpv.git"; then
>         hide_conflicting_libs
>         create_ab_pkgconfig
> ```
> 
> By adding the line, the **mpv-1.dll** is checked upon if --enable-libmpv-shared is in MPV_OPTIONS.TXT and will also be stripped properly at the end.
> Now I have to strip it manually.

Sure, is `--enable-libmpv-shared` a valid option in mpv? (I haven't checked so Idk)

> **4. Media-suite_helper.sh**
> This is a more a question:
> Is there a difference between the way to define a function in the following 2 examples ?
> Are these identical ?
> I see mostly the first is used but recently the second appeared in the helper function.
> 
> ```shell
> function1() {
>     codeblock
> }
> 
> and
> 
> function2() (
>     codeblock
> )
> ```

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_04
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_05

the `( )` starts a subshell and `{ }` is just a regular command list, the benefit of a subshell is to be able to change variables and other stuff without it affecting the global or exported variables (example would be needing to cd into a folder, but not wanting to affect the calling location or needing to set CFLAGS without affecting other program's CFLAGS)

**Comment by wiiaboo** [comment]
> 1. For egl-angle in MPV:

018b5ad 



> **3. Builing MPV.exe/com** (line 2137)

320184e
