### ISSUE TITLE
Request: Vulkan filter

### ISSUE THREAD

**Issue by nico-lab** [m-ab-s/media-autobuild_suite#1565]
I want ffmpeg to include Vulkan, which is already available in mpv, and libglslang to be able to use the Vulkan filter.

Manually start msys64\mingw64.exe
https://gist.github.com/nico-lab/27192535b78a9c0bf70d29c5536c1943

add build\ffmpeg_options.txt

```
--enable-vulkan
--enable-libglslang
```

Then Run  media-autobuild_suite.bat to enable Vulkan filter.

**Comment by 1480c1** [comment]
You can always try to open a pull request

**Comment by catcafeplus** [comment]
Hi, I had forked the suite and added / removed some features for my personal preference. (including libglslang and vulkan for ffmpeg)

Anyone is welcomed to create PR with my changes back to this repository, but I will not do it myself considering that many of the changes are just of personal preference and I am a bit lazy.

**Comment by nico-lab** [comment]
@1480c1
I cant do PR because I don't have the skills to write shell script.

@catcafeplus
Thank you, I'll try it.

**Comment by wiiaboo** [comment]
@catcafeplus too lazy to even click Fork instead of pushing your own fresh repo with the whole history completely gone?

**Comment by 1480c1** [comment]
I think the reason why he didn't fork it because the diff is over 9370 line long at the current master and his commit and he stripped out a lot of the code andfiles, including the license header from the bat file and included some other patches etc.

**Comment by 1480c1** [comment]
I don't think we can use his repository at all since I can't tell what he changed to add the vulkan-filter

**Comment by wiiaboo** [comment]
Yeah, I don't really feel like wasting any time on this either.
