### ISSUE TITLE
libmusicbrainz-git - Build Failure - CMAKE Error

### ISSUE THREAD

**Issue by slyfox1186** [m-ab-s/media-autobuild_suite#1566]
This has happened for 2-3 days every time I try update the suite.
https://0x0.st/icLs.zip

Can anyone tell me `what I can change` in the build-config file to NOT build this package?
For the time being I can do without this package but can't ID the correct line to edit to stop the build.

**Comment by 1480c1** [comment]
delete libxml2-git in the build folder and retry or disable cyanrip in the media-autobuild_suite.ini by changing `cyanrip2=1` to `cyanrip2=2`
