### ISSUE TITLE
jq git update failes

### ISSUE THREAD

**Issue by j-mas** [m-ab-s/media-autobuild_suite#1567]
I got the following fault and the suite stopps!

 jq git  ................................................ [Updates found]
├ Running autoreconf...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
  CC       src/parser.lo
  CCLD     libjq.la
  CCLD     jq.exe
  GEN      jq.1
cp: cannot stat 'jq.1.prebuilt': No such file or directory
make[2]: *** [Makefile:1914: jq.1] Error 1
make[2]: Leaving directory '/build/jq-git/build-64bit'
make[1]: *** [Makefile:1170: all-recursive] Error 1
make[1]: Leaving directory '/build/jq-git/build-64bit'
make: *** [Makefile:801: all] Error 2
make failed. Check N:/media-autobuild_suite-master/build/jq-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
Creating diagnostics file...

**Comment by 1480c1** [comment]
jq's latest commit broke

**Comment by 1480c1** [comment]
Fixed in https://github.com/stedolan/jq/commit/ccc79e592cfe1172db5f2def5a24c2f7cfd418bf
