### ISSUE TITLE
update, compile, curl Likely error

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1569]
Likely error (tail of the failed operation logfile):
E:\Source\ffmpeg\MAS\msys64\mingw32\bin\ld: ../lib/.libs/libcurl.a(libcurl_la-psl.o):psl.c:(.text+0x9b): undefined reference to `_imp__psl_latest'
E:\Source\ffmpeg\MAS\msys64\mingw32\bin\ld: ../lib/.libs/libcurl.a(libcurl_la-psl.o):psl.c:(.text+0xd3): undefined reference to `_imp__psl_free'
E:\Source\ffmpeg\MAS\msys64\mingw32\bin\ld: ../lib/.libs/libcurl.a(libcurl_la-psl.o):psl.c:(.text+0x100): undefined reference to `_imp__psl_builtin'
E:\Source\ffmpeg\MAS\msys64\mingw32\bin\ld: ../lib/.libs/libcurl.a(libcurl_la-cookie.o):cookie.c:(.text+0x12b4): undefined reference to `_imp__psl_is_cookie_domain_acceptable'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:931: curl.exe] Error 1
make[2]: Leaving directory '/build/curl-git/build-32bit/src'
make[1]: *** [Makefile:1998: all-recursive] Error 1
make[1]: Leaving directory '/build/curl-git/build-32bit/src'
make: *** [Makefile:948: all-recursive] Error 1

**Comment by 1480c1** [comment]
Please attach a zip of the logs, else we won't try to fix this issue
```bash
[[ -f "$LOCALBUILDDIR/no_logs" ||  $logging = n ]] &&
    do_simple_print -p "${orange}Warning: We will not accept any issues lacking any form of logs or logs.zip!${reset}"
```

**Comment by 1480c1** [comment]
It's hard to debug anything without any logs

**Comment by dbyoung720** [comment]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4285624/logs.zip)
upload log file

**Comment by 1480c1** [comment]
Try again
