### ISSUE TITLE
[mingw64] [libass] libass build error with clang enabled

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1571]
Likely error (tail of the failed operation logfile):
make[1]: Entering directory '/build/libass-git/build-64bit'
Making all in libass
make[2]: Entering directory '/build/libass-git/build-64bit/libass'
  NASM     x86/rasterizer.lo
mv: cannot stat 'rasterizer.o': No such file or directory
make[2]: *** [Makefile:856: x86/rasterizer.lo] Error 1
make[2]: Leaving directory '/build/libass-git/build-64bit/libass'
make[1]: *** [Makefile:476: all-recursive] Error 1
make[1]: Leaving directory '/build/libass-git/build-64bit'
make: *** [Makefile:385: all] Error 2
make failed.

There are no errors with the gcc compiler.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4286826/logs.zip)

**Comment by 1480c1** [comment]
Fixed in 5e722e8

**Comment by 1480c1** [comment]
Reopening since I needed to revert the commit since it somehow breaks ffmpeg for me on two different machines

**Comment by 1480c1** [comment]
Has this been fixed?

**Comment by kliffgomel** [comment]
I already had no compilation errors.
