### ISSUE TITLE
qtbase: unable to install qmake.exe

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1572]
I guess you may just point to a wrong directory: `build/qtbase-git/qmake/qmake.exe` does not exist, but `build/qtbase-git/bin/qmake.exe` does. – Or should it have been built newly in there? At least I don't see any error messages besides the one complaining that it cannot be copied.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4287754/logs.zip)

**Comment by 1480c1** [comment]
Try again

**Comment by LigH-de** [comment]
Passed with separate make.
