### ISSUE TITLE
opusfile-git compile error

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1573]
``` bash
opusfile-git compile error
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4289815/logs.zip)

```

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)

**Comment by dbyoung720** [comment]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4289817/logs.zip)

**Comment by 1480c1** [comment]
Seems to be cause by opusfile using `-std=c89` and clang not supporting inline like inline in c89 mode

**Comment by dbyoung720** [comment]
can not select clang compile, use default gcc (cc=2), compile ok

**Comment by 1480c1** [comment]
Not solved, will reopen

**Comment by LigH-de** [comment]
Possibly related? Compiling with GCC:

```
┌ opusfile git  .......................................... [Updates found]
0002-configure-Only-add-std-c89-if-not-mingw-because-of-c.patch
        Patch could not be applied with `git am`. Continuing without patching.
```

Doesn't hurt, just cosmetical ... or fixed upstream?

**Comment by 1480c1** [comment]
Updated the patch since it needed a 3-way merge
