### ISSUE TITLE
error: failed retrieving file 'mingw32.db! 

### ISSUE THREAD

**Issue by j-mas** [m-ab-s/media-autobuild_suite#1575]
What is the fault? What can I do?

-------------------------------------------------------------------------------

:: Synchronizing package databases...
error: failed retrieving file 'mingw32.db' from repo.msys2.org : Connection timed out after 10009 milliseconds
error: failed retrieving file 'mingw32.db' from sourceforge.net : Operation timed out after 10012 milliseconds with 0 out of 0 bytes received
 mingw32 is up to date
error: failed retrieving file 'mingw64.db' from repo.msys2.org : Connection timed out after 10006 milliseconds
 mingw64 is up to date
error: failed retrieving file 'msys.db' from repo.msys2.org : Connection timed out after 10005 milliseconds
 msys is up to date

-------------------------------------------------------------------------------
Checking pacman packages...
-------------------------------------------------------------------------------

:: Synchronizing package databases...
error: failed retrieving file 'mingw32.db' from repo.msys2.org : Connection timed out after 10013 milliseconds
 mingw32 is up to date
error: failed retrieving file 'mingw64.db' from repo.msys2.org : Connection timed out after 10001 milliseconds
 mingw64 is up to date
error: failed retrieving file 'msys.db' from repo.msys2.org : Connection timed out after 10003 milliseconds
 msys is up to date

**Comment by 1480c1** [comment]
Nothing, repo.msys2.org is having some issues

**Comment by 1480c1** [comment]
From https://gitter.im/msys2/msys2

> Алексей @Alexpux 07:58
something not work on server
so it take time while i fix it

**Comment by b9AcE** [comment]
FYI, repo.msys2.org is back up now and AFAIK should remain so at least for the immediate future or longer.
