### ISSUE TITLE
libdvdread: VLC+MPV build failed, strerror_r

### ISSUE THREAD

**Issue by j-mas** [m-ab-s/media-autobuild_suite#1576]
00:27:40 ┌ vlc git  ..................................... [Updates found]
00:27:40 ├ Running uninstall...
00:27:44 ├ Running autoreconf...
00:29:17 ├ Running configure...
00:37:54 ├ Running install...
Likely error (tail of the failed operation logfile):
collect2.exe: error: ld returned 1 exit status
make[4]: *** [Makefile:16226: libdvdnav_plugin.la] Error 1
make[4]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[3]: *** [Makefile:31837: install-recursive] Error 1
make[3]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[2]: *** [Makefile:32268: install] Error 2
make[2]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[1]: *** [Makefile:1573: install-recursive] Error 1
make[1]: Leaving directory '/build/vlc-git/build-64bit'
make: *** [Makefile:2042: install] Error 2
install failed. Check C:/media-autobuild_suite-master/build/vlc-git/build-64bit/ab-suite.install.log
This is required for other packages, so this script will exit.
00:40:47   Creating diagnostics file...

**Comment by LigH-de** [comment]
libdvdnav just had another update, will report if I passed...

**Comment by LigH-de** [comment]
trac.videolan.org "has issues" [sic, in IRC]: Can't log in, can't reset password. Hard to discuss VLC issues now... trying more via IRC, but may not easily find competent developers there.

**Comment by LigH-de** [comment]
Possible reason reported in **build/dvdread-git/build-32bit/ab-suite.make.log**

```
../src/dvd_input.c: In function 'file_open':
../src/dvd_input.c:203:8: warning: implicit declaration of function 'strerror_r'; did you mean 'strerror_s'? [-Wimplicit-function-declaration]
```

**Comment by 1480c1** [comment]
I think it was located in libcompat or something

**Comment by 1480c1** [comment]
https://sourceforge.net/p/mingw-w64/bugs/513/

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/issues/1574#issue-575857304

**Comment by LigH-de** [comment]
The libdvdread issue got closed with [added checks](https://code.videolan.org/videolan/libdvdread/-/merge_requests/12), please try again.

**Comment by 1480c1** [comment]
@j-mas, ping? If you don't respond within a day or two, I will close since I don't have this problem anymore
