### ISSUE TITLE
libtiff - tiffgt.c: undefined reference to _imp____glut... functions

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1577]
```
[93/129] Linking C executable tools\tiffgt.exe
FAILED: tools/tiffgt.exe 
cmd.exe /C "cd . && E:\MABS\msys64\mingw32\bin\ccache.exe  gcc -mthreads -mtune=generic -O2 -pipe -Wall -Winline -W -Wformat-security -Wpointer-arith -Wdisabled-optimization -Wno-unknown-pragmas -Wdeclaration-after-statement -fstrict-aliasing -O3 -DNDEBUG  -pipe -static-libgcc -static-libstdc++ tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj  -o tools\tiffgt.exe -Wl,--major-image-version,0,--minor-image-version,0  libtiff/libtiff.a  port/libport.a  -Wl,-Bstatic  -lglut  -Wl,-Bdynamic  -lopengl32  -lglu32  -Wl,-Bstatic  -lz  -ljpeg  -llzma  -lzstd  -Wl,-Bdynamic  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj:tiffgt.c:(.text.startup+0x28b): undefined reference to `_imp____glutInitWithExit@12'
E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld.exe: tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj:tiffgt.c:(.text.startup+0x567): undefined reference to `_imp____glutCreateWindowWithExit@8'
```

Reported to [libtiff issues](https://gitlab.com/libtiff/libtiff/-/issues/180)

Happened after a recent merge, so possibly caused by an upstream change.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4297777/logs.zip)

**Comment by 1480c1** [comment]
I'm tempted to create a personal patch for their cmakelists to add an option like ENABLE_TOOLS to be able to disable the tools folder since we don't really need them.

**Comment by dbyoung720** [comment]
delete or rename the include / gl directory,
Make libtiff not find glut, libtiff will disable glut and compile ok

**Comment by LigH-de** [comment]
Might be related:
```
$ pacman -Qs opengl
local/mingw-w64-i686-freeglut 3.2.1-1
    Freeglut allows the user to create and manage windows containing OpenGL contexts (mingw32-w64)
local/mingw-w64-i686-libepoxy 1.5.4-1
    A library for handling OpenGL function pointer management for you (mingw-w64)
local/mingw-w64-x86_64-freeglut 3.2.1-1
    Freeglut allows the user to create and manage windows containing OpenGL contexts (mingw32-w64)
local/mingw-w64-x86_64-libepoxy 1.5.4-1
    A library for handling OpenGL function pointer management for you (mingw-w64)
```
@bobfriesenhahn recommends investigating the configure script logic to the libtiff developers.

**Comment by 1480c1** [comment]
Right now working on building freeglut in suite to satisfy glut dependencies since findglut.cmake doesn't have any way to pick up the weirdly named libfreeglut_static.a since nothing references it at all

**Comment by LigH-de** [comment]
On the other side (upstream at gitlab), GLUT dependency of libtiff shall become optional, provided the configure scripts can be brought to a current state.

**Comment by bobfriesenhahn** [comment]
On Mon, 9 Mar 2020, LigH-de wrote:

> On the other side (upstream at gitlab), GLUT dependency of libtiff shall become optional, provided the configure scripts can be brought to a current state.

This is something I intend to take care of.

Bob
-- 
Bob Friesenhahn
bfriesen@simple.dallas.tx.us, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by 1480c1** [comment]
> On Mon, 9 Mar 2020, LigH-de wrote: On the other side (upstream at gitlab), GLUT dependency of libtiff shall become optional, provided the configure scripts can be brought to a current state.
> This is something I intend to take care of. Bob -- Bob Friesenhahn bfriesen@simple.dallas.tx.us, http://www.simplesystems.org/users/bfriesen/ GraphicsMagick Maintainer, http://www.GraphicsMagick.org/ Public Key, http://www.simplesystems.org/users/bfriesen/public-key.txt

Thank you, although one thing to note is that we are using cmake instead of autotools right now

**Comment by bobfriesenhahn** [comment]
On Mon, 9 Mar 2020, Christopher Degawa wrote:

>> On Mon, 9 Mar 2020, LigH-de wrote: On the other side (upstream at gitlab), GLUT dependency of libtiff shall become optional, provided the configure scripts can be brought to a current state.
>> This is something I intend to take care of. Bob -- Bob Friesenhahn bfriesen@simple.dallas.tx.us, http://www.simplesystems.org/users/bfriesen/ GraphicsMagick Maintainer, http://www.GraphicsMagick.org/ Public Key, http://www.simplesystems.org/users/bfriesen/public-key.txt
>
> Thank you, although one thing to note is that we are using cmake instead of autotools right now

I have little knowledge of cmake but I can take care of the 
Autotools-based build so it is at least possible to disable use of 
OpenGL/GLUT.

CMake and Autoconf operate in profoundly diffent ways in that CMake 
appears to test header files but Autoconf compiles and links test 
programs.  This means that CMake is more optimistic than Autoconf is 
since it is non-validating.

Bob
-- 
Bob Friesenhahn
bfriesen@simple.dallas.tx.us, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by 1480c1** [comment]
I currently have a suite side fix for libtiff using the cmake that I can push today, but if you do have a fix for autotools, I can test it out too later
