### ISSUE TITLE
VLC error

### ISSUE THREAD

**Issue by j-mas** [m-ab-s/media-autobuild_suite#1583]
I got this error by building VLC today. I have two PC´s. One PC shows me the following error. The other produced a green screen and an restart of the PC.

10:22:40 ┌ vlc git  ..................................... [Updates found]
10:22:40 ├ Running uninstall...
10:22:42 ├ Running autoreconf...
10:23:54 ├ Running configure...
10:30:15 ├ Running install...
Likely error (tail of the failed operation logfile):
      |                  ^~~~~~~~~~~~~~~~~~
make[4]: *** [Makefile:27524: misc/medialibrary/libmedialibrary_plugin_la-medialib.lo] Error 1
make[4]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[3]: *** [Makefile:31837: install-recursive] Error 1
make[3]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[2]: *** [Makefile:32268: install] Error 2
make[2]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[1]: *** [Makefile:1573: install-recursive] Error 1
make[1]: Leaving directory '/build/vlc-git/build-64bit'
make: *** [Makefile:2042: install] Error 2
install failed. Check C:/media-autobuild_suite-master/build/vlc-git/build-64bit/ab-suite.install.log
This is required for other packages, so this script will exit.
10:43:00   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iAlQ.zip

**Comment by LigH-de** [comment]
I will try to discover where to report; IRC channel tells me it's in the medialib subproject, VLC may need to use a compatible revision, not always HEAD.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4343473/logs.zip)

**Comment by LigH-de** [comment]
Issue may be fixed. I'm getting a different error now, but that's from the linker, so compiling should have been successful before.

```
undefined reference to `qt_static_plugin_QtQuickControls2Plugin()'
undefined reference to `qt_static_plugin_QtQuickTemplates2Plugin()'
```

^ this deserves another issue.

@j-mas - please check build\vlc-git\build-##bit\ab-suite.install.log because the relevant error does not appear in the tail in the whole suite's compile log.

**Comment by j-mas** [comment]
@LigH-de 

No, I still have the same mistake. With running install it takes 20 min. 
Then comes the known error message or the green crash screen.

15:25:15 ┌ vlc git  .................................. [Recently updated]
15:25:17 ├ Running autoreconf...
15:26:38 ├ Running configure...
15:33:14 ├ Running install...
Likely error (tail of the failed operation logfile):
      |                  ^~~~~~~~~~~~~~~~~~
make[4]: *** [Makefile:27557: misc/medialibrary/libmedialibrary_plugin_la-medialib.lo] Error 1
make[4]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[3]: *** [Makefile:31870: install-recursive] Error 1
make[3]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[2]: *** [Makefile:32301: install] Error 2
make[2]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[1]: *** [Makefile:1573: install-recursive] Error 1
make[1]: Leaving directory '/build/vlc-git/build-64bit'
make: *** [Makefile:2042: install] Error 2
install failed.

I attached the ab-suite.install.log:

[ab-suite.install.log](https://github.com/m-ab-s/media-autobuild_suite/files/4355179/ab-suite.install.log)

Thank you for your help! 

Best regards
j-mas

**Comment by LigH-de** [comment]
So I wonder if I got different results because I removed both build/vlc-git and build/medialibrary-git to force a complete clone and rebuild of both... My suite is in the middle of rebuilding a lot more, including Qt, since MSYS2 just updated to GCC 9.3.0 - will take a while to verify.

**Comment by j-mas** [comment]
@LigH-de 
Ok. Ich werde auch mal versuchen welche Ergebnisse ich erziele, wenn ich die build/vlc-git and build/medialibrary-git ebenfalls mal komplett entferne! Ich werde dann berichten
Danke
@ LigH-de
OK. I will also try what results I get if I completely remove the build/vlc-git and build/medialibrary-git! I will report then
Thank you

**Comment by j-mas** [comment]
@LigH-de 
that doesn´t help. Same result as before!

**Comment by LigH-de** [comment]
So I wonder if I got different results because I removed both build/vlc-git and build/medialibrary-git to force a complete clone and rebuild of both... My suite is in the middle of rebuilding a lot more, including Qt, since MSYS2 just updated to GCC 9.3.0 - will take a while to verify.

**Comment by LigH-de** [comment]
Does building VLC respect all the **contrib/src**/_subprojects_/**rules.mak** files?

**Comment by LigH-de** [comment]
Again, I get medialibrary compiled (or does it only believe so?), but instead, there are the undefined references to QtQuick.

@1480c1 - is this worth a separate issue or shall I add logs here?

**Comment by 1480c1** [comment]
> Does building VLC respect all the **contrib/src**/_subprojects_/**rules.mak** files?

Of course not, we don't touch those at all and those are written on an assumption of running then from Ubuntu or some other Linux distro

**Comment by 1480c1** [comment]
> Again, I get medialibrary compiled (or does it only believe so?), but instead, there are the undefined references to QtQuick.
> 
> @1480c1 - is this worth a separate issue or shall I add logs here?

I think that can be added to one of the other VLC at issue from dbyoung

**Comment by robUx4** [comment]
> > Does building VLC respect all the **contrib/src**/_subprojects_/**rules.mak** files?
> 
> Of course not, we don't touch those at all and those are written on an assumption of running then from Ubuntu or some other Linux distro

No they are not. There's even some Mingw/msys detection in there. Anything that can build VLC can also build contribs (not all of them depending on the platform)

**Comment by 1480c1** [comment]
> > > Does building VLC respect all the **contrib/src**/_subprojects_/**rules.mak** files?
> > 
> > 
> > Of course not, we don't touch those at all and those are written on an assumption of running then from Ubuntu or some other Linux distro
> 
> No they are not. There's even some Mingw/msys detection in there. Anything that can build VLC can also build contribs (not all of them depending on the platform)

Of course, some of it is generic enough and I was able to compile some of them, however, some of it was not generic enough and one of the makefile had some wine files in some folder under /usr set as a requirement last time I tried using the contribs folder. Of course, it could have changed since that was tested around February

**Comment by 1480c1** [comment]
Also, recommendation, please rename https://wiki.videolan.org/Win32CompileMSYS/ to https://wiki.videolan.org/Win32CompileMSYS2/ since MSYS and MSYS2 are different projects

**Comment by j-mas** [comment]
14:31:18 ┌ vlc git  ..................................... [Updates found]
14:31:19 ├ Running uninstall...
vlc-mabs.patch
        Patch could not be applied with `git am`. Continuing without patching.
14:31:21 ├ Running autoreconf...
14:32:51 ├ Running configure...
14:41:45 ├ Running install...
Likely error (tail of the failed operation logfile):
      |                  ^~~~~~~~~~~~~~~~~~
make[4]: *** [Makefile:27815: misc/medialibrary/libmedialibrary_plugin_la-medialib.lo] Error 1
make[4]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[3]: *** [Makefile:32128: install-recursive] Error 1
make[3]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[2]: *** [Makefile:32566: install] Error 2
make[2]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[1]: *** [Makefile:1575: install-recursive] Error 1
make[1]: Leaving directory '/build/vlc-git/build-64bit'
make: *** [Makefile:2044: install] Error 2
install failed.

**Comment by j-mas** [comment]
Has the VLC project been stopped?

**Comment by moisespr123** [comment]
> Has the VLC project been stopped?

I checked their nightly builds and there haven't been any new releases. My guess is that there are compilation issues since we also have them here.

Their latest nightly for v4.0.0 was on April 3rd.

**Comment by j-mas** [comment]
That can be! But I haven't been able to compile a single VLC build with media autobuild_suite yet.

**Comment by moisespr123** [comment]
I seem to be making progress, except that now I'm stuck at this error:

```
In file included from H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/x86_64-w64-mingw32/bits/c++allocator.h:33,
                 from H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/bits/allocator.h:46,
                 from H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/memory:63,
                 from ../../modules/misc/medialibrary/fs/fs.h:24,
                 from ../../modules/misc/medialibrary/fs/fs.cpp:25:
H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/ext/new_allocator.h: In instantiation of 'void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = vlc::medialibrary::SDDevice; _Args = {char*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Tp = vlc::medialibrary::SDDevice]':
H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/bits/alloc_traits.h:482:2:   required from 'static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = vlc::medialibrary::SDDevice; _Args = {char*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Tp = vlc::medialibrary::SDDevice; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<vlc::medialibrary::SDDevice>]'
H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/bits/shared_ptr_base.h:548:39:   required from 'std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {char*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Tp = vlc::medialibrary::SDDevice; _Alloc = std::allocator<vlc::medialibrary::SDDevice>; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]'
H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/bits/shared_ptr_base.h:679:16:   required from 'std::__shared_count<_Lp>::__shared_count(_Tp*&, std::_Sp_alloc_shared_tag<_Alloc>, _Args&& ...) [with _Tp = vlc::medialibrary::SDDevice; _Alloc = std::allocator<vlc::medialibrary::SDDevice>; _Args = {char*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]'
H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/bits/shared_ptr_base.h:1344:71:   required from 'std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<vlc::medialibrary::SDDevice>; _Args = {char*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Tp = vlc::medialibrary::SDDevice; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]'
H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/bits/shared_ptr.h:359:59:   required from 'std::shared_ptr<_Tp>::shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<vlc::medialibrary::SDDevice>; _Args = {char*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; _Tp = vlc::medialibrary::SDDevice]'
H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/bits/shared_ptr.h:701:14:   required from 'std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = vlc::medialibrary::SDDevice; _Alloc = std::allocator<vlc::medialibrary::SDDevice>; _Args = {char*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]'
H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/bits/shared_ptr.h:717:39:   required from 'std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = vlc::medialibrary::SDDevice; _Args = {char*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]'
../../modules/misc/medialibrary/fs/fs.cpp:226:61:   required from here
H:/repos/media-autobuild_suite/msys64/mingw64/include/c++/9.3.0/ext/new_allocator.h:145:20: error: invalid new-expression of abstract class type 'vlc::medialibrary::SDDevice'
  145 |  noexcept(noexcept(::new((void *)__p)
      |                    ^~~~~~~~~~~~~~~~~~
  146 |        _Up(std::forward<_Args>(__args)...)))
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../modules/misc/medialibrary/fs/fs.cpp:32:
../../modules/misc/medialibrary/fs/device.h:32:7: note:   because the following virtual functions are pure within 'vlc::medialibrary::SDDevice':
   32 | class SDDevice : public IDevice
      |       ^~~~~~~~
In file included from ../../modules/misc/medialibrary/fs/fs.cpp:30:
H:/repos/media-autobuild_suite/local64/include/medialibrary/filesystem/IDevice.h:45:32: note: 	'virtual const string& medialibrary::fs::IDevice::scheme() const'
   45 |     virtual const std::string& scheme() const = 0;
      |                                ^~~~~~
H:/repos/media-autobuild_suite/local64/include/medialibrary/filesystem/IDevice.h:48:18: note: 	'virtual bool medialibrary::fs::IDevice::isNetwork() const'
   48 |     virtual bool isNetwork() const = 0;
      |                  ^~~~~~~~~
```

@1480c1, any thoughts?

I have the following gists:

* https://gist.github.com/moisespr123/2369978dc603ed1e67bdf7aba7304416
* https://gist.github.com/moisespr123/70e16f70f5d016c3d0f0dacbf97526f0

They get applied, but gives me the above issue. Seems to be something on gcc?

**Comment by 1480c1** [comment]
I'm not entirely sure, but I'll look into it once I have some time

**Comment by moisespr123** [comment]
I think it has to do with the changes in medialibrary. I'm still working on it. There were some new additions that needed new virtual methods.

**Comment by moisespr123** [comment]
Can someone test PR #1629 ? I managed to compile it on my end.

**Comment by j-mas** [comment]
@moisespr123 
If I knew how to apply the patch, I would love to do it!
