### ISSUE TITLE
Repo rav1e fails on "linking with `gcc` failed"  "ld: cannot find -lntdll"

### ISSUE THREAD

**Issue by pat357** [m-ab-s/media-autobuild_suite#1585]
Building C lib fails on linking with gcc : "ld: cannot find -lntdll"

full logs at https://0x0.st/ia4V.zip

**Comment by buhlaze** [comment]
yep... it failed for me too. Any help would be useful.

**Comment by wiiaboo** [comment]
Please don't paste the whole log, it's just a pain in the ass to see the issue. That's what the .zip is for.

**Comment by 1480c1** [comment]
So annoyingly, ntdll is a system lib that gcc picks up when running `gcc -lntdll` but ld doesn't

**Comment by wiiaboo** [comment]
Maybe workaround it by creating an import lib?

**Comment by wiiaboo** [comment]
But weird, I do have it in `/trunk/msys64/mingw64/x86_64-w64-mingw32/lib/libntdll.a`.
