### ISSUE TITLE
[mingw64] [rav1e]  cargo-c v0.6.2 fails to install during the installing process for rav1e

### ISSUE THREAD

**Issue by jaytrinitron** [m-ab-s/media-autobuild_suite#1587]
Just tested the latest build (Latest commit [126429b](https://github.com/m-ab-s/media-autobuild_suite/commit/126429bf84c0c16973bdac08bce28030330b9ef1)), still get the error that cargo-c v0.6.2 fails to install during the installing process for rav1e. I don't think the error is the missing dll like it was before though, for what that's worth. Thanks and let me know if you need anything else from me. 
``` bash
Likely error (tail of the failed operation logfile):


error: aborting due to previous error

error: failed to compile `cargo-c v0.6.2`, intermediate artifacts can be found at `C:\media-autobuild_suite-master\msys64\tmp\cargo-installYQykFK`

Caused by:
  could not compile `cargo-c`.

To learn more, run the command again with --verbose.
install-cargo-c failed. Check C:/media-autobuild_suite-master/build/rav1e-git/ab-suite.install-cargo-c.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iaGv.zip
Copy and paste [logs.zip](https://0x0.st/iaGv.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```
[logs.zip](https://0x0.st/iaGv.zip)

**Comment by 1480c1** [comment]
Note:
```none
C:\media-autobuild_suite-master\msys64\tmp\cargo-installYQykFK\x86_64-pc-windows-gnu\release\deps\libcurl_sys-2630bdf46b3b3bf8.rlib(url.o):url.c:(.text$Curl_init_userdefined+0xb): undefined reference to `__imp___acrt_iob_func'
...
 C:\media-autobuild_suite-master\msys64\tmp\cargo-installYQykFK\x86_64-pc-windows-gnu\release\deps\liblibssh2_sys-02c87dd187dfed87.rlib(session.o):session.c:(.text$_libssh2_wait_socket+0xe8): undefined reference to `__imp__difftime64'
```

**Comment by dumdrak** [comment]
forcing version 0.5.3 of cargo-c seems to make the cargo install successful

 diff media-suite_compile.orig.sh media-suite_compile.sh
1066c1066
<         log "install-cargo-c" "$RUSTUP_HOME/bin/cargo.exe" install cargo-c \
---
>         log "install-cargo-c" "$RUSTUP_HOME/bin/cargo.exe" install cargo-c --vers 0.5.3 \

**Comment by wiiaboo** [comment]
Well, that's a valid workaround, if the newer versions aren't strictly required.

**Comment by Selur** [comment]
deleted `media-autobuild_suite\msys64\opt\cargo`
changed to `log "install-cargo-c" "$RUSTUP_HOME/bin/cargo.exe" install cargo-c --vers 0.5.3`
rav1e build still fails for me:
```
16:36:38 ┌ rav1e git  ................................ [Recently updated]
16:36:38 ├ Running submodule...
16:36:39 ├ Running rust.update...
16:36:45 ├ Running rust.build...
16:39:45 ├ Running install-cargo-c...
16:41:36 ├ Running install-rav1e-c...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
/opt/cargo/bin/cargo.exe cinstall --release --prefix /build/rav1e-git/install-32bit --jobs 16
error: could not execute process `I:/media-autobuild_suite/msys64/opt/cargo\bin\cargo-cinstall.exe cinstall --release --prefix 'I:/media-autobuild_suite/build/rav1e-git/install-32bit' --jobs 16` (never executed)

Caused by:
  Der angeforderte Vorgang erfordert erhöhte Rechte. (os error 740)
install-rav1e-c failed. Check I:/media-autobuild_suite/build/rav1e-git/ab-suite.install-rav1e-c.log
This is required for other packages, so this script will exit.
```
[logs.zip](https://0x0.st/iBRi.zip)

**Comment by buhlaze** [comment]
where do i put this  log "install-cargo-c" "$RUSTUP_HOME/bin/cargo.exe" install cargo-c --vers 0.5.3 \ command

**Comment by Selur** [comment]
in media-autobuild_suite\build\media-suite_compile.sh line 1066

**Comment by raza-gh** [comment]
adding " --vers 0.5.3" in line 1066 of media-suite_compile.sh worked for me to solve this bug. I did not test rav1e.exe or rav1e encoding with ffmpeg.exe though.

**Comment by wiiaboo** [comment]
@1480c1 can you test this? ^
I won't have a Windows machine available for some weeks.

**Comment by 1480c1** [comment]
Sure

**Comment by 1480c1** [comment]
rust compiled successfully, waiting for ffmpeg to test librav1e

**Comment by 1480c1** [comment]
Seems to work, will merge the fix
