### ISSUE TITLE
Xvid v1.3.7

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1589]
Just found out that Xvid 1.3.7 was released at the end of last year and mingw-w64-xvidcore packages is available but the suite doesn't update and compile it.
https://packages.msys2.org/search?t=binpkg&q=xvid

Can maybe someone share some light into this and find out why the suite don't update and compile the new version?

[EDIT]
Remember now that something needed to be updated in the suite the for the previous xvid version, ie. 1.3.5, so i guess it's the same thing this time.

**Comment by Barough** [comment]
Nah, v1.3.7 was released quick to fix something in v1.3.6

**Comment by 1480c1** [comment]
I mean I don't think we kept up with xvid updating since we never looked at it in a while

**Comment by 1480c1** [comment]
Note for self: It seems there's a svn server https://labs.xvid.com/source/

**Comment by Barough** [comment]
Ok

Hope to see a little update in the suite then. ;)

**Comment by wiiaboo** [comment]
By how fast (read: slow) development seems to be moving, I don't think xvid
warrants a move to svn.

**Comment by 1480c1** [comment]
Yeah, I mainly made that note so I could look at the code without needing to download the zip/tarballs when I want to search for something

**Comment by LigH-de** [comment]
Proposed patch 27b7cddaa47463d0043eb8c6d995362955ac57c5 - increased version number and updated hash; not sure if that is sufficient or if deleting xvid_encraw.exe and xvidcore.tar.gz have to enforce it.
