### ISSUE TITLE
Request: [Vapoursynth] Vapoursynth already update to r49

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#1590]
https://github.com/vapoursynth/vapoursynth/releases

And the Vapoursynth r49 requires python 3.8 instead of python 3.7.

**Comment by pat357** [comment]
Vapoursynth r49 is still a release candidate, not a full oficial release.

**Comment by pat357** [comment]
Now R49 is officially released !
Needs python v3.8.x , v3.7.x will not work.

**Comment by Patman86** [comment]
Request can be closed.
