### ISSUE TITLE
libmusicbrainz: missing includes, make rule syntax error?

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1594]
ab-suite.install.log
```
make[2]: *** No rule to make target 'src/*.inc', needed by 'src/mb5_c.cc'.  Stop.
```
Surprisingly, `src/` contains the created binaries, not includes. Possibly a syntax mistake that shifts the meaning of parameters, maybe one of the parameters is empty or contains an unescaped/unquoted space?

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4409295/logs.zip)

**Comment by Data55** [comment]
Got the same issue today with a fresh install.

[logs.zip](https://0x0.st/iMfJ.zip)

**Comment by LigH-de** [comment]
The URL points to a fork created by @wiiaboo - so I hope he will maintain it.

**Comment by Patman86** [comment]
I think the issue is [here](https://github.com/wiiaboo/libmusicbrainz/blob/2fb51bd5aee5036730990970b04ad5db9110407f/src/CMakeLists.txt#L33)

**Comment by wiiaboo** [comment]
Yeah, I merged some changes from upstream, so they're not completely dead.

**Comment by 1480c1** [comment]
I'm asssuming this is done
