### ISSUE TITLE
 git reset --hard origin/HEAD fatal

### ISSUE THREAD

**Issue by unmanei** [m-ab-s/media-autobuild_suite#1596]
I  run "media-autobuild_suite.bat"  ,  has a error, see a log :  

------------------------------------------

fatal: ambiguous argument 'origin/HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
git.reset failed. Check M:/name/media-autobuild/build/libxml2-git/ab-suite.git.reset.log
This is required for other packages, so this script will exit.
10:13:53   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iMGZ.zip
Copy and paste [logs.zip](https://0x0.st/iMGZ.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by 1480c1** [comment]
Try deleting `M:/name/media-autobuild/build/libxml2-git` and reruning

**Comment by unmanei** [comment]
Thanks，Probably, my network speed is not stable, now the file is incomplete。

**Comment by 1480c1** [comment]
> now the file is incomplete。

what?

**Comment by unmanei** [comment]
Sorry, the old file is not complete, now the problem has been solved。

**Comment by 1480c1** [comment]
I see
