### ISSUE TITLE
[mingw32|mingw64] [repo] Shader git

### ISSUE THREAD

**Issue by Hallkel** [m-ab-s/media-autobuild_suite#1598]
Likely error (tail of the failed operation logfile):
../third_party/glslang/glslang/MachineIndependent/localintermediate.h:230:62: error: extra ';' after in-class function d  230 |     TMap<TString, int>& operator[](int i) { return maps[i]; };
      |                                                              ^
      |                                                              -
../third_party/glslang/glslang/MachineIndependent/localintermediate.h:231:74: error: extra ';' after in-class function definition [-Werror=extra-semi]
  231 |     const TMap<TString, int>& operator[](int i) const { return maps[i]; };
      |                                                                          ^
      |                                                                          -
cc1plus.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.

https://0x0.st/iurR.zip

**Comment by 1480c1** [comment]
Please consider looking at other issue reports and try to follow what they do. This literally is not very helpful.
