### ISSUE TITLE
kvazaar hanging after a fresh installation...

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#1601]
16:47:49   Running git update for kvazaar...
16:47:50 ┌ kvazaar git  .............................. [Recently updated]
16:47:50 ├ Running autogen...
16:48:14 ├ Running configure...
16:48:51 ├ Running make...
Likely error (tail of the failed operation logfile):
Making all in src
make[2]: Entering directory '/build/kvazaar-git/build-32bit/src'
  GEN      kvazaar.exe
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.3.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazar.a(libavx2_la-picture-avx2.o):picture-avx2.c:(.text+0x8af): undefined reference to `_mm_cvtsi128_si64'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:1004: kvazaar.exe] Error 1
make[2]: Leaving directory '/build/kvazaar-git/build-32bit/src'
make[1]: *** [Makefile:524: all-recursive] Error 1
make[1]: Leaving directory '/build/kvazaar-git/build-32bit'
make: *** [Makefile:394: all] Error 2
make failed. Check F:/m-a-s/build/kvazaar-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
16:49:12   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iuSq.zip
Copy and paste [logs.zip](https://0x0.st/iuSq.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4431727/logs.zip)

**Comment by 1480c1** [comment]
Report this [upstream](https://github.com/ultravideo/kvazaar/issues) and see if they care about 32-bit.

This is caused by certain simds being missing on 32-bit

**Comment by ASopH** [comment]
They work on this issue: https://github.com/ultravideo/kvazaar/issues/260

**Comment by ASopH** [comment]
Seem to run now..
