### ISSUE TITLE
Error during compiling ffms for x264

### ISSUE THREAD

**Issue by Patman86** [m-ab-s/media-autobuild_suite#1602]
Hi,

An error occurred while compiling ffms2 for x264. [Here](https://0x0.st/iu15.zip) is the log. I think it's a bug in ffmpeg and not in m-ab-s.

**Comment by Patman86** [comment]
I've tested compiling x264 including lsmash and ffms without using m-ab-s and I got an error during preparing ffms libs. All libs from ffmpeg are missing but the libs are in the pkgconfig folder. That really seems to be a problem by ffmpeg.

**Comment by 1480c1** [comment]
I'm able to reproduce but am not able to put time into looking into fixing just yet

**Comment by Patman86** [comment]
Problem is gone. I just tested it again today and it all works.
