### ISSUE TITLE
[mingw64] [ffmpeg] don't have avisynth+ include/libs

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#1603]
error log:https://0x0.st/iufr.zip

>  [313m02:30:32(B[m [1mâ”Œ ffmpeg git (B[m .................................. [[311mUpdates found(B[m]
> [313m02:30:32(B[m [1mâ”œ(B[m Until SVT-AV1 issues a fix, libaom & libopencore-amrwb must be disabled while libsvtav1 is enabled....
> [313m02:30:32(B[m [1mâ”œ(B[m Changing options to comply to nonfree...
> patch unexpectedly ends in middle of line
> [313m02:30:46(B[m [1mâ”œ(B[m Compiling [1mshared(B[m FFmpeg...
> [313m02:30:48(B[m [1mâ”œ(B[m Running uninstall...
> [313m02:30:53(B[m [1mâ”œ(B[m Running configure...
> Likely error (tail of the failed operation logfile):
> CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
> LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
> ../configure --prefix=/local64 --disable-static --enable-shared --pkg-config-flags=--static --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --disable-debug --enable-ffnvcodec --enable-nvdec --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-chromaprint --enable-cuda-llvm --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-libopenh264 --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-opencl --enable-opengl --enable-libvmaf --enable-libcodec2 --enable-libsrt --enable-ladspa --enable-vapoursynth --enable-libsvthevc --enable-libsvtav1 --enable-openssl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --prefix=/local64/bin-video/ffmpegSHARED
> ERROR: avisynth/avisynth_c.h not found
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem.
> [31mconfigure failed. Check C:/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.configure.log(B[m
> [31mThis is required for other packages, so this script will exit.(B[m
> [313m02:33:13(B[m   Creating diagnostics file...
> 
> [32mAll relevant logs have been anonymously uploaded to https://0x0.st/iufr.zip
> [32mCopy and paste [31m[logs.zip](https://0x0.st/iufr.zip)[32m in the GitHub issue.(B[m
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
> Try running the build again at a later time.

FFmpeg now use avisynth+ instead of AvxSynth.

https://github.com/FFmpeg/FFmpeg/commit/6d8cddd1c67758636843f6a08295b3896c2e9ef8

avisynth+ git: https://github.com/AviSynth/AviSynthPlus

**Comment by wiiaboo** [comment]
Didn't notice @qyot27 removed the compat libs too.

**Comment by wiiaboo** [comment]
Seems simple enough: https://github.com/shinchiro/mpv-winbuild-cmake/commit/054f7527906944451018110887e1968dbfbebf55
