### ISSUE TITLE
[mingw32|mingw64] [repo] Cargo failed to compile

### ISSUE THREAD

**Issue by axel578** [m-ab-s/media-autobuild_suite#1605]
I encountered this error during build time ( I didn't use unrecommanded libs that you clearly stated during the installation process ) :
failed to compile `cargo-c v0.6.2`, intermediate artifacts can be found at `C:\media-autobuild_suite-master\msys64\tmp\cargo-installvmrZuG

I tried on different machines while still having this error, I do know that this type of issues are the ones you hate the most but I tested nearly everything to avoid this error.

**Comment by 1480c1** [comment]
Get the latest suite, we are not using v0.6.2 anymore, it's pinned to 0.5.1 or something
