### ISSUE TITLE
Request: OpenSource CineForm encoder cfenc

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1609]
[VideoHelp forum](https://forum.videohelp.com/threads/396588-cfenc-command-line-Cineform-encoder)
[doom9 forum](https://forum.doom9.org/showthread.php?p=1906671) — HolyWu was able to compile a Windows binary, will try to invite him here.

**Comment by LigH-de** [comment]
An integration into ffmpeg [may not happen](https://forum.videohelp.com/threads/396588-cfenc-command-line-Cineform-encoder#post2578692) because the algorithm relies too much on x86 architecture/instructions. So it will stay a separate encoder.

**Comment by 1480c1** [comment]
So I guess this is stalled on cineform-sdk

**Comment by 1480c1** [comment]
Seems that they only produce two executables with both of them not being installed
```none
TestCFHD.exe
WaveletDemo.exe
```

**Comment by 1480c1** [comment]
Seems I can't build cfenc because I need FFmpeg, and that's blocked by some others atm

**Comment by 1480c1** [comment]
http://ffmpeg.org/pipermail/ffmpeg-devel/2020-July/267060.html

seems it might be related?

**Comment by LigH-de** [comment]
It hsa been made available in ffmpeg.
