### ISSUE TITLE
Meson / GCC error 

### ISSUE THREAD

**Issue by easyfab** [m-ab-s/media-autobuild_suite#1610]
Hi, 

I have error with meson, It try to find files in D: instead of C:  (D:/msys64/mingw64/x86_64-w64-mingw32/lib/x86_64-w64-mingw32/9.3.0) ? Why ? I must have some corrupt config files. I try to reinstall msys2/mingw but same error. Can someone help me ?

Error log example :

CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -march=native -O3 -pipe
CXXFLAGS: -mthreads -march=native -O3 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
meson .. --default-library=static --buildtype=release --prefix=/local64 --backend=ninja --bindir=bin-video
Traceback (most recent call last):
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 131, in run
    return options.run_func(options)
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/msetup.py", line 215, in _generate
    intr.backend.generate()
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/backend/ninjabackend.py", line 322, in generate
    self.generate_target(t)
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/backend/ninjabackend.py", line 642, in generate_target
    elem = self.generate_link(target, outname, obj_list, linker, pch_objects, stdlib_args=stdlib_args)
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/backend/ninjabackend.py", line 2566, in generate_link
    dep_targets.extend(self.guess_external_link_dependencies(linker, target, commands, internal))
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/backend/ninjabackend.py", line 2449, in guess_external_link_dependencies
    search_dirs = tuple(search_dirs) + tuple(linker.get_library_dirs(self.environment))
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/compilers/mixins/clike.py", line 145, in get_library_dirs
    dirs = self.get_compiler_dirs(env, 'libraries')
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/compilers/mixins/gnu.py", line 275, in get_compiler_dirs
    return self._split_fetch_real_dirs(line.split('=', 1)[1])
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/site-packages/mesonbuild/compilers/mixins/gnu.py", line 257, in _split_fetch_real_dirs
    if pobj.exists():
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/pathlib.py", line 1385, in exists
    self.stat()
  File "C:/media-autobuild_suite/msys64/mingw64/lib/python3.8/pathlib.py", line 1191, in stat
    return self._accessor.stat(self)
OSError: [WinError 1005] Le volume ne contient pas de système de fichiers connu. Vérifiez si tous les pilotes de système

de fichiers nécessaires sont chargés et si le volume n’est pas endommagé: **'D:/msys64/mingw64/x86_64-w64-mingw32/lib/x86_64-w64-mingw32/9.3.0'**
The Meson build system
Version: 0.54.0
Source dir: C:/media-autobuild_suite/build/vmaf-git/libvmaf
Build dir: C:/media-autobuild_suite/build/vmaf-git/libvmaf/build-64bit
Build type: native build
Using 'PKG_CONFIG_PATH' from environment with value: 'C:\\media-autobuild_suite\\local64\\lib\\pkgconfig;C:\\media-autobuild_suite\\msys64\\mingw64\\lib\\pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: 'C:\\media-autobuild_suite\\local64\\lib\\pkgconfig;C:\\media-autobuild_suite\\msys64\\mingw64\\lib\\pkgconfig'
Project name: libvmaf
Project version: 1.3.16
Using 'CC' from environment with value: 'gcc.bat'
Using 'CFLAGS' from environment with value: '-mthreads -march=native -O3 -pipe'
Using 'LDFLAGS' from environment with value: '-pipe -static-libgcc -static-libstdc++'
Using 'CPPFLAGS' from environment with value: '-D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1'
Using 'CXX' from environment with value: 'g++.bat'
Using 'CXXFLAGS' from environment with value: '-mthreads -march=native -O3 -pipe'
Using 'LDFLAGS' from environment with value: '-pipe -static-libgcc -static-libstdc++'
Using 'CPPFLAGS' from environment with value: '-D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1'
Using 'CC' from environment with value: 'gcc.bat'
Using 'CFLAGS' from environment with value: '-mthreads -march=native -O3 -pipe'
Using 'LDFLAGS' from environment with value: '-pipe -static-libgcc -static-libstdc++'
Using 'CPPFLAGS' from environment with value: '-D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1'
C compiler for the host machine: gcc.bat (gcc 9.3.0 "gcc.exe (Rev1, Built by MSYS2 project) 9.3.0")
C linker for the host machine: gcc.bat ld.bfd 2.34
Using 'CXX' from environment with value: 'g++.bat'
Using 'CXXFLAGS' from environment with value: '-mthreads -march=native -O3 -pipe'
Using 'LDFLAGS' from environment with value: '-pipe -static-libgcc -static-libstdc++'
Using 'CPPFLAGS' from environment with value: '-D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1'
C++ compiler for the host machine: g++.bat (gcc 9.3.0 "g++.exe (Rev1, Built by MSYS2 project) 9.3.0")
C++ linker for the host machine: g++.bat ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Check usable header "stdatomic.h" : YES 
Run-time dependency threads found: YES
Library m found: YES
Configuring version.h using configuration
Program doxygen found: YES (C:\media-autobuild_suite\msys64\usr\bin/doxygen.EXE)
Configuring Doxyfile using configuration
Build targets in project: 23

Found ninja.EXE-1.10.0 at C:\media-autobuild_suite\msys64\mingw64\bin/ninja.EXE

**Comment by easyfab** [comment]
Not sure it's meson, I revert GCC to :

http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-9.2.0-2-any.pkg.tar.xz
 http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libs-9.2.0-2-any.pkg.tar.xz

And it's ok

**Comment by easyfab** [comment]
With 9.3 :

 gcc -print-search-dirs
install: C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/
programs: =C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/x86_64-w64-mingw32/9.3.0/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/
libraries: =C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/;C:/media-autobuild_suite/local64/lib/x86_64-w64-mingw32/9.3.0/;C:/media-autobuild_suite/local64/lib/../lib/;C:/media-autobuild_suite/msys64/mingw64/lib/x86_64-w64-mingw32/9.3.0/;C:/media-autobuild_suite/msys64/mingw64/lib/../lib/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/lib/x86_64-w64-mingw32/9.3.0/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/lib/../lib/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../x86_64-w64-mingw32/9.3.0/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../lib/;**D:/msys64/mingw64/x86_64-w64-mingw32/lib/x86_64-w64-mingw32/9.3.0/;D:/msys64/mingw64/x86_64-w64-mingw32/lib/../lib/**;C:/media-autobuild_suite/local64/lib/;C:/media-autobuild_suite/msys64/mingw64/lib/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/lib/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../;**D:/msys64/mingw64/x86_64-w64-mingw32/lib/**

with 9.2 : 

gcc -print-search-dirs
install: C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/
programs: =C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/x86_64-w64-mingw32/9.2.0/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/
libraries: =C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/;C:/media-autobuild_suite/local64/lib/x86_64-w64-mingw32/9.2.0/;C:/media-autobuild_suite/local64/lib/../lib/;C:/media-autobuild_suite/msys64/mingw64/lib/x86_64-w64-mingw32/9.2.0/;C:/media-autobuild_suite/msys64/mingw64/lib/../lib/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/lib/x86_64-w64-mingw32/9.2.0/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/lib/../lib/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../x86_64-w64-mingw32/9.2.0/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../lib/;C:/building/msys64/mingw64/x86_64-w64-mingw32/lib/x86_64-w64-mingw32/9.2.0/;C:/building/msys64/mingw64/x86_64-w64-mingw32/lib/../lib/;C:/media-autobuild_suite/local64/lib/;C:/media-autobuild_suite/msys64/mingw64/lib/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/lib/;C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../;**C:/building/msys64/mingw64/x86_64-w64-mingw32/lib/**

**Comment by 1480c1** [comment]
That's an upstream msys2 issue

**Comment by 1480c1** [comment]
@easyfab anything changed? I want to close this issue because it isn't something that the suite can control since those paths are there because of when the packages are generated, and so nothing the suite can do

**Comment by easyfab** [comment]
No change for me with latest GCC 9.3, but we can close the issue as GCC 9.2 revert seems work fine and is simple to apply.
