### ISSUE TITLE
Vulkan hangs on suits run 

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#1611]
I have relaunched the suite. All settings are the default settings. The suite still hangs at the same spot. I need help to solve this problem.

10:05:49 ┌ vulkan-loader git  ........................ [Recently updated]
10:05:49 ├ Running uninstall...
vulkan-0001-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
10:05:50 ├ Running dependencies...
10:05:55 ├ Installing Vulkan-Headers...
10:05:55 ├ Running uninstall...
10:05:55 ├ Running cmake...
10:05:55 ├ Running build...
10:05:55 ├ Running install...
10:05:56 ├ Building Vulkan-Loader...
10:05:56 ├ Running cmake...
10:05:58 ├ Running build...
Likely error (tail of the failed operation logfile):
ninja: build stopped: subcommand failed.
[1/6] Building RC object loader/CMakeFiles/vulkan.dir/loader.rc.obj
FAILED: loader/CMakeFiles/vulkan.dir/loader.rc.obj
F:\m-a-s\msys64\mingw32\bin\windres.exe -O coff -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -Dvulkan_EXPORTS -IF:/m-a-s/build/vulkan-loader-git/loader -IF:/m-a-s/build/vulkan-loader-git/loader/generated -IF:/m-a-s/build/vulkan-loader-git/build-32bit/loader -IF:/m-a-s/local32/include  F:/m-a-s/build/vulkan-loader-git/loader/loader.rc loader/CMakeFiles/vulkan.dir/loader.rc.obj
F:/m-a-s/build/vulkan-loader-git/loader/loader.rc:46:10: fatal error: winres.h: No such file or directory
   46 | #include "winres.h"
      |          ^~~~~~~~~~
compilation terminated.
F:\m-a-s\msys64\mingw32\bin\windres.exe: preprocessing failed.
ninja: build stopped: subcommand failed.
build failed. Check F:/m-a-s/build/vulkan-loader-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
10:05:59   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iSuL.zip
Copy and paste [logs.zip](https://0x0.st/iSuL.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4454882/logs.zip)

**Comment by j-mas** [comment]
Same Problem here!

**Comment by 1480c1** [comment]
```none
vulkan-0001-cross-compile-static-linking-hacks.patch
Patch could not be applied with git am. Continuing without patching.
```
I'm assuming it's because the patch failed to apply, thus we are not using the right headers

**Comment by ASopH** [comment]
A miracle :-) It works now...
