### ISSUE TITLE
[|mingw64] [ffmpeg] ERROR: cuda_llvm requested but not found

### ISSUE THREAD

**Issue by moisespr123** [m-ab-s/media-autobuild_suite#1613]
Started getting this error when I ran the suite yesterday when ffmpeg is running configure: 

`ERROR: cuda_llvm requested but not found`

[logs.zip](https://0x0.st/iSVC.zip)

**Comment by Patman86** [comment]
I can confirm that I have this error too.

**Comment by pat357** [comment]
From your ffmpeg config.log:
```bash
check_nvcc cuda_llvm
test_nvcc
BEGIN /tmp/ffconf.pIAyPVGU/test.cu
    1	extern "C" {
    2	    __global__ void hello(unsigned char *data) {}
    3	}
END /tmp/ffconf.pIAyPVGU/test.cu
clang --cuda-gpu-arch=sm_30 -O2 -m64 -S -nocudalib -nocudainc --cuda-device-only -include src/compat/cuda/cuda_runtime.h -o H:/repos/media-autobuild_suite/msys64/tmp/ffconf.pIAyPVGU/test.o H:/repos/media-autobuild_suite/msys64/tmp/ffconf.pIAyPVGU/test.cu
H:/repos/media-autobuild_suite/msys64/mingw64/bin/clang.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory 
```
Could be that your Clang installation is missing something or got messed up, but since there are at least 2 people having this issue, it's unlikely.

What is very strange is that it let pass the above error and then finally fails on testing if your compiler supports the **-Wmaybe-uninitialized**  flag.......

I'd certainly report it as ffmpeg issue on the bug tracker.

**Comment by moisespr123** [comment]
I have Clang. Tried to run it and it returns this:

![image](https://user-images.githubusercontent.com/16326634/79018404-c071de00-7b41-11ea-9972-82d3d8738c00.png)

**Comment by moisespr123** [comment]
Ran the suite again and turns out there were some new updates including one for Clang:

![image](https://user-images.githubusercontent.com/16326634/79018833-cae0a780-7b42-11ea-9149-540d4afa23a7.png)

Maybe this fixes the issues.

**Comment by moisespr123** [comment]
Closing since the new updates fixed this issue.
