### ISSUE TITLE
[mingw64] 

### ISSUE THREAD

**Issue by netleader** [m-ab-s/media-autobuild_suite#1615]
**MinGW64 GCC compiler isn't installed; maybe the download didn't work
Do you want to try it again?**

I tried it 50 times always the same…

**Comment by 1480c1** [comment]
Check what is outputted beforehand. This issue report is lacking any kind of information and is useless.

**Comment by netleader** [comment]
Everything else above this message succeeded.

**Comment by 1480c1** [comment]
It still doesn't change that this issue report is lacking anything useful. Can you check if you can delete the msys2 folder and rerun the script

**Comment by netleader** [comment]
<img width="707" alt="Screenshot 2020-04-14 at 19 06 48" src="https://user-images.githubusercontent.com/3867846/79253251-2aacba80-7e83-11ea-9d25-d4f85af17bd7.png">

**Comment by netleader** [comment]
Looks like I got it working, the  main problem was that i executed the batch file within powershell.

**Comment by 1480c1** [comment]
I see, I usually run the suite through pwsh with noMintty enabled. I don't know why it would not work for you

**Comment by moisespr123** [comment]
@netleader I could not replicate this issue within powershell. Did you ran something specific?

**Comment by 1480c1** [comment]
Assuming closed either way
