### ISSUE TITLE
libtiff / Clang

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1621]
┌ libtiff git  ........................................... [Updates found]
├ Running uninstall...
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
D:\mabs\msys64\mingw32\bin\ld: tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj:tiffgt.c:(.text+0x555): undefined reference to `glutSpecialFunc'
D:\mabs\msys64\mingw32\bin\ld: tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj:tiffgt.c:(.text+0x55d): undefined reference to `glutMainLoop'
D:\mabs\msys64\mingw32\bin\ld: tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj:tiffgt.c:(.text+0x86b): undefined reference to `__glutCreateWindowWithExit'
D:\mabs\msys64\mingw32\bin\ld: tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj:tiffgt.c:(.text+0x992): undefined reference to `glutSetWindowTitle'
D:\mabs\msys64\mingw32\bin\ld: tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj:tiffgt.c:(.text+0xa5c): undefined reference to `glutPostRedisplay'
D:\mabs\msys64\mingw32\bin\ld: tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj:tiffgt.c:(.text+0xac2): undefined reference to `glutPostRedisplay'
D:\mabs\msys64\mingw32\bin\ld: tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj:tiffgt.c:(.text+0xbf6): undefined reference to `glutReshapeWindow'
D:\mabs\msys64\mingw32\bin\ld: tools/CMakeFiles/tiffgt.dir/tiffgt.c.obj:tiffgt.c:(.text+0xbff): undefined reference to `glutPostRedisplay'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
build failed. Check D:/mabs/build/libtiff-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iQYm.zip
Copy and paste [logs.zip](https://0x0.st/iQYm.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by kliffgomel** [comment]
I have successfully build libtiff v4.1.0 with clang.

**Comment by dbyoung720** [comment]
Create a libtiff.patch file locally and "set(HAVE_OPENGL FALSE)" in CMakeLists.txt
dopatch "xxx/libtiff.patch" (modify media-suite_compile.sh)
compile ok

[libtiff.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4816427/libtiff.zip)

**Comment by 1480c1** [comment]
@Barough, can you run `nm /local64/lib/libglut.a | sort -u | grep glutGet` in mintty and paste the output here?

**Comment by Barough** [comment]
Totally forgot about this issue. It's been resolved since a 'while'.

But here is the output for that command

$ nm /local64/lib/libglut.a | sort -u | grep glutGet
                 U glutGet
                 U glutGetColor
                 U glutGetMenu
                 U glutGetMenuData
                 U glutGetModeValues
                 U glutGetModifiers
                 U glutGetProcAddress
                 U glutGetWindow
                 U glutGetWindowData
0000000000000000 r .rdata$.refptr.glutGet
0000000000000000 r .rdata$.refptr.glutGetColor
0000000000000000 r .rdata$.refptr.glutGetMenu
0000000000000000 r .rdata$.refptr.glutGetMenuData
0000000000000000 r .rdata$.refptr.glutGetModeValues
0000000000000000 r .rdata$.refptr.glutGetModifiers
0000000000000000 r .rdata$.refptr.glutGetWindow
0000000000000000 r .rdata$.refptr.glutGetWindowData
0000000000000000 R .refptr.glutGet
0000000000000000 R .refptr.glutGetColor
0000000000000000 R .refptr.glutGetMenu
0000000000000000 R .refptr.glutGetMenuData
0000000000000000 R .refptr.glutGetModeValues
0000000000000000 R .refptr.glutGetModifiers
0000000000000000 R .refptr.glutGetWindow
0000000000000000 R .refptr.glutGetWindowData
0000000000000000 T glutGetProcAddress
0000000000000170 T glutGet
0000000000000310 T glutGetColor
00000000000004a0 T glutGetWindow
0000000000000630 T glutGetModifiers
0000000000000700 T glutGetModeValues
0000000000000ca0 T glutGetWindowData
00000000000011c0 T glutGetMenu
00000000000018e0 T glutGetMenuData

**Comment by 1480c1** [comment]
Oh, I see
