### ISSUE TITLE
[mingw64] [libpsl] [clang] libpsl build error with clang enabled

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1622]
11:42:07 ┌ libpsl-0.21.0  .................................. [Downloaded]
11:42:08 ├ Running extract...
11:42:14 ├ Running configure...
11:46:49 ├ Running make...
Likely error (tail of the failed operation logfile):
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: psl.o:psl.c:(.text+0x976): undefined reference to `__imp_psl_is_cookie_domain_acceptable'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: psl.o:psl.c:(.text+0x99b): undefined reference to `__imp_psl_is_public_suffix'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: psl.o:psl.c:(.text+0xa3a): undefined reference to `__imp_psl_check_version_number'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: psl.o:psl.c:(.text+0xa56): undefined reference to `__imp_psl_get_version'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:478: psl.exe] Error 1
make[2]: Leaving directory '/build/libpsl-0.21.0/build-64bit/tools'
make[1]: *** [Makefile:536: all-recursive] Error 1
make[1]: Leaving directory '/build/libpsl-0.21.0/build-64bit'
make: *** [Makefile:445: all] Error 2
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4503146/logs.zip)

**Comment by megapro17** [comment]
Openal also fails with clang

**Comment by 1480c1** [comment]
> Openal also fails with clang

Then make a separate issue

**Comment by megapro17** [comment]
> > Openal also fails with clang
> 
> Then make a separate issue

There are so many problems with clang, I doubt that anyone cares

**Comment by kliffgomel** [comment]
The library is compiled with the latest clang toolchain.
