### ISSUE TITLE
Clang enabled, but ffmpeg still says that it built with gcc

### ISSUE THREAD

**Issue by megapro17** [m-ab-s/media-autobuild_suite#1623]
```
ffmpeg version N-97440-ge0b1ca5669 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.0 (Rev2, Built by MSYS2 project)
```
`CC=1` in ini file present

I even deleted /msys32, /msys64, /local32 and /local64 folders to ensure all libs are rebuilt

**Comment by 1480c1** [comment]
That's because ffmpeg doesn't respect the CC and CXX variable. I think it's dumb, but they only accept `--cc=` and `--cxx=` options for compilers

**Comment by megapro17** [comment]
It is needed to edit media-suite_compile.sh script? I can't find exact place where ffmpeg is compiled

**Comment by 1480c1** [comment]
Try again, ffmpeg options are a bit convoluted

**Comment by megapro17** [comment]
Why this not working right away? It is clearly an issue. Why you closed it?

**Comment by 1480c1** [comment]
I added a commit to fix the issue. Look at the linked commit https://github.com/m-ab-s/media-autobuild_suite/commit/07960ab8b12bf346d74c940feff0f13b32779b9a

**Comment by megapro17** [comment]
🤦‍♂️

**Comment by megapro17** [comment]
It still says gcc...
```
ffmpeg version N-97449-g7197076eec Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.0 (Rev2, Built by MSYS2 project)
```

**Comment by 1480c1** [comment]
Try again, added a new commit

**Comment by megapro17** [comment]
Awesome
```
ffmpeg version N-97451-g6a071e001f Copyright (c) 2000-2020 the FFmpeg developers
  built with clang version 10.0.0 (https://github.com/msys2/MINGW-packages.git 3f880aaba91a3d9cdfb222dc270274731a2119a9)  configuration:  --disable-static --enable-shared --cc='ccache clang' --cxx='ccache clang++' --disable-autodetect
```
