### ISSUE TITLE
Request: Move Chromaprint From Full Build to Other Tools

### ISSUE THREAD

**Issue by gammaray10k** [m-ab-s/media-autobuild_suite#1625]
Hello: thank you for your hard work and creating this script. I wanted to know if you can move Chromaprint from the Full Build to the Other Tools option. I run the Zeranoe emulation variation of the script build but I would also like to have the Chromaprint codec without having to run script for a full build. At least make it an option to build it with their desired build options. Thank you .

**Comment by 1480c1** [comment]
Use 1 for ffmpeg option and comment out the ones you don't want

**Comment by 1480c1** [comment]
If not, give an actual justification for moving chromaprint to a different category. It probably won't be in the zeranoe emulation since that's supposed to include what zeranoe has,

**Comment by gammaray10k** [comment]
It’s not in the Zeranoe emulation, and that’s why I was asking for it to be moved; Justification: to have Zeranoe+Chromaprint+the other optionals. I guess I’ll try commenting out the ones I don’t want like you said. Thank you for responding so quickly.

**Comment by 1480c1** [comment]
Assuming closed
