### ISSUE TITLE
[Question] SoX Dependencies

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1627]
Hi

Trying to find out what external dependencies SoX have. I have looked but nothing have come up. Can any1 help?

**Comment by wiiaboo** [comment]
https://github.com/m-ab-s/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L854-L880

**Comment by Barough** [comment]
Thnx a lot :)

**Comment by wiiaboo** [comment]
The only mandatory dependency is libsndfile. The others depend if you have them enabled in ffmpeg_options.txt.
