### ISSUE TITLE
Vorbis-tools

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1628]
Just checked these
https://github.com/xiph/vorbis/commits/master
https://github.com/xiph/vorbis-tools/commits/master

and both have updates from this year, but the suite don't make any new compiles. Why doesn't it do that?

**Comment by wiiaboo** [comment]
We don't compile libvorbis. And vorbis-tools is only updated if oggenc is deleted. We should remove the `! files_exist "${_check[@]}"` part.

**Comment by Barough** [comment]
That would be great if this could be fixed so that it compiles when updates is available.
