### ISSUE TITLE
exhale x86 EXE in 'local64/bin-audio folder'

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1634]
Just noticed after running the suite to checkout the exhale encoder that the 32-bit encoder is in the 'local64/bin-audio folder' also. I've deleted the exhale-git folder and re-run the suite just to be sure but it was the same thing on the second run. Any1 else noticed this?

**Comment by moisespr123** [comment]
Can you try with the latest commit? The build command was changed.

**Comment by Barough** [comment]
Started doing that 5 minutes ago. I'll get back 2 ya when the suite have done it's session. ;)

**Comment by Barough** [comment]
That solved it. Thnx a lot. :)
