### ISSUE TITLE
neon-0.30.2.tar.gz does not exist any more

### ISSUE THREAD

**Issue by pkcv** [m-ab-s/media-autobuild_suite#1636]
We have newer version, hence following URL to download does not work anymore resulting in build failure.

https://fossies.org/linux/www/neon-0.30.2.tar.gz

New Version:  neon-0.31.1.tar.gz

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4586323/logs.zip)

**Comment by moisespr123** [comment]
Compiling to make sure the new release doesn't break anything.

**Comment by moisespr123** [comment]
Unfortunately, `libmusicbrainz` fails to compile with the 0.31.1 version:

![image](https://user-images.githubusercontent.com/16326634/81174599-1df62080-8f70-11ea-81f9-24a4639de707.png)

[logs.zip](https://0x0.st/i2G5.zip)

**Comment by moisespr123** [comment]
Switching to git works but fails on install:

![image](https://user-images.githubusercontent.com/16326634/81178436-2fdac200-8f76-11ea-89d1-41038e3318c7.png)

[logs.zip](https://0x0.st/i2Dc.zip)

**Comment by 1480c1** [comment]
https://fossies.org/linux/www/neon-0.31.1.tar.gz seems to exist

**Comment by moisespr123** [comment]
> https://fossies.org/linux/www/neon-0.31.1.tar.gz seems to exist

It exists and compiles, but libmusicbrainz fails to compile because some nonnulls were added to the neon code on that version.

**Comment by 1480c1** [comment]
We can either use 0.30.2 from https://github.com/notroj/neon/releases or try upgrading to 0.31.1 and try to fix the issues

**Comment by moisespr123** [comment]
> We can either use 0.30.2 from https://github.com/notroj/neon/releases or try upgrading to 0.31.1 and try to fix the issues

The 0.30.2 from the Git repository fails with this. Already tested...

> Switching to git works but fails on install:
> 
> ![image](https://user-images.githubusercontent.com/16326634/81178436-2fdac200-8f76-11ea-89d1-41038e3318c7.png)
> 
> [logs.zip](https://0x0.st/i2Dc.zip)

Also it needs to do autogen.

**Comment by 1480c1** [comment]
Did you use the release zip?

**Comment by moisespr123** [comment]
> Did you use the release zip?

The .tar.gz from the release page.

**Comment by 1480c1** [comment]
I found out what broke 0.30.2 doc stuff

**Comment by moisespr123** [comment]
We could use that if it works, and if we decide to use master, we'll need to remove the ` ne_attribute((nonnull));` lines on `src/ne_request.h`. That should make libmusicbrainz compile.
