### ISSUE TITLE
Request: consider merits of migrating to microsoft's open source Vcpkg on github ?

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#1638]
Microsoft has a new initiative on github called Vcpkg.  
https://github.com/microsoft/vcpkg  
Apparently it can already build various forms of ffmpeg for win10 with specific dependencies.
It seems to be under very active development and is able to build a range of open source tools.   
> we now support 1322 libraries in the main vcpkg library catalog   

Perhaps used in conjunction with a free microsoft "Windows 10 development environment" VM with visual studio and win10 sdk etc pre-installed, the Vcpkg tool for parameterising builds seems as if it may be handy in the long run.   
vm: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/  

Do you have any thoughts on perhaps moving to the Vcpkg tool/environment and supporting build parameters in that way ?

**Comment by 1480c1** [comment]
Not really interested, too complex for our use case. It would be more suitable if you personally installed it or if a developer used it in their own project

**Comment by 1480c1** [comment]
Plus idk about their mingw-w64 support

**Comment by wiiaboo** [comment]
I see this as absolutely useless for our usecase and huge amount of work for absolutely no gain for us, unless I'm seriously misinterpreting what's being requested here.

**Comment by 1480c1** [comment]
Based on limited searching, they only support msvc on windows platform and trying to set it up as Linux auto-redirects to the windows setup in a msys2 environment

**Comment by hydra3333** [comment]
good oh.

**Comment by hydra3333** [comment]
OK, it seems I am better off using a free microsoft "Windows 10 development environment" VM with visual studio and win10 sdk etc pre-installed,   
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/    
and running mabs in that.

... given I don't want to install much stuff (or any, in fact :) on my pc
