### ISSUE TITLE
[Feature-Request] Adding RIST

### ISSUE THREAD

**Issue by laurfb** [m-ab-s/media-autobuild_suite#1639]
Hi.
Dare with a sugestion: do you think the RIST (https://code.videolan.org/rist/librist) protocol could be added to the media_autobuilt-suite?
Besides SRT, RIST is a promising protocol for reliable live video transmission over Internet with low latency and high quality.
An open alternative to proprietary protocols like Zixi, VideoFlow etc.
regards,
Laur

**Comment by wiiaboo** [comment]
Is it supported by anything? Who would it be used by?

**Comment by moisespr123** [comment]
Seems this utils project makes use of it:

https://code.videolan.org/rist/rist-utils

But there's no ffmpeg support for this library.

**Comment by 1480c1** [comment]
Not sure what's the benefit of adding those two at it's current state

**Comment by DWAMTV** [comment]
Yeah that'd be great. RIST is an alternative to SRT and it's been implemented in VLC and Gstreamer and is already supported by professional platforms like Elemental and Zixi.

**Comment by 1480c1** [comment]
https://code.videolan.org/videolan/vlc/-/blob/master/NEWS#L61 I see it was indeed added to vlc

**Comment by 1480c1** [comment]
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210119120140.10504-1-onemda@gmail.com/

**Comment by laurfb** [comment]
Hi. Finally RIST protocol was added to ffmpeg via librist (https://code.videolan.org/rist/librist).
regards,
laur
