### ISSUE TITLE
"MinGW64 GCC compiler isn't installed" on initial run

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#1641]
Hello. An initial MABS install in a win10 x64 VM yielded "MinGW64 GCC compiler isn't installed".
Process: 
- started the VM and logged in as an admin user
- checked and saw VS2019 is pre-installed
- downloaded and installed the CUDA toolkit
- downloaded and installed python 3.8.2
- downloaded and unzipped the .zip
- double clicked on media-autobuild_suite.bat
- saw the error message.

Given the mingw64.log error message "/usr/bin/bash: /build/mingw.sh: No such file or directory" I'm not sure where to next. Advice welcomed.

Logs attached
[secondUpdate.log](https://github.com/m-ab-s/media-autobuild_suite/files/4597128/secondUpdate.log)
[firstrun.log](https://github.com/m-ab-s/media-autobuild_suite/files/4597129/firstrun.log)
[firstUpdate.log](https://github.com/m-ab-s/media-autobuild_suite/files/4597130/firstUpdate.log)
[mingw64.log](https://github.com/m-ab-s/media-autobuild_suite/files/4597131/mingw64.log)
[pacman.log](https://github.com/m-ab-s/media-autobuild_suite/files/4597132/pacman.log)

**Comment by 1480c1** [comment]
Try setting NoMintty=1 in media-autobuild_suite

**Comment by hydra3333** [comment]
OK, will give that a try.
PS mingw.sh was empty.

**Comment by hydra3333** [comment]
Yes, it's going now.  Thank you.

**Comment by hydra3333** [comment]
Before I close this issue, I just noticed the error message `The system cannot find the path specified.`   
Is that normal ?   

```
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
-------------------------------------------------------------------------------
Updates finished.
-------------------------------------------------------------------------------
The system cannot find the path specified.
22:57:36 Warning: We will not accept any issues lacking any form of logs or logs.zip!
22:57:36
        Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
22:57:38
        Starting 64bit compilation of global tools
```

**Comment by 1480c1** [comment]
Very possibly, depends on the command that cause the message, it could be a find command that looks for a non existent file, that we create if the prior command failed or something

**Comment by hydra3333** [comment]
OK, I'll see how it goes. Ta.
