### ISSUE TITLE
ninja: error: FindFirstFileExA

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1644]
┌ libtiff git  ........................................ [Recently updated]
├ Running cmake...
├ Running build...
├ Running install...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe -DFREEGLUT_STATIC
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
ninja -j1 install
ninja: error: FindFirstFileExA(d/:/mabs/msys64/mingw32/i686-w64-mingw32/include): Felaktig syntax f▒r filnamn, katalognamn eller volymetikett.

ninja: error: FindFirstFileExA(d/:/mabs/msys64/mingw32/i686-w64-mingw32/include): Felaktig syntax f▒r filnamn, katalognamn eller volymetikett.

install failed. Check D:/mabs/build/libtiff-git/build-32bit/ab-suite.install.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/i_O_.zip
Copy and paste [logs.zip](https://0x0.st/i_O_.zip) in the GitHub issue.

**Comment by j-mas** [comment]
Here the same problem

**Comment by 1480c1** [comment]
Happens with fribidi

**Comment by 1480c1** [comment]
https://github.com/msys2/MINGW-packages/issues/6469

**Comment by ImportTaste** [comment]
There does seem to be [a patch](https://raw.githubusercontent.com/msys2/MINGW-packages/99e20fec2c976bc99e504509964e9066a0bbc06e/mingw-w64-ninja/gcc10-depfile-escape-fix-1774.patch) available, but as far as I can tell, since media-autobuild_suite doesn't build mingw-w64-ninja, we'll have to wait for it or a similar fix to be merged.

**Comment by KobusPost** [comment]
Also getting this error, not just for fribidi, but multiple packages. Everytime the path has the same error. 

Tried replacing the ninja executable with an older version, but that didn't work for me. As I'm more a web (C#) guy and have absolutely no knowledge of mingw, I didn't bother trying more things. 

However they just released a workaround: #9b7f67c5f620d1ba7ce951cfee3ce2328fb751f6 
Started the suite, which downloaded some new packages and now Fribidi does compile.

**Comment by 1480c1** [comment]
issue started from gcc 10, not ninja

**Comment by Barough** [comment]
Some GCC10.x updates was pushed and compiling works for me again

**Comment by 1480c1** [comment]
Assuming closed

**Comment by brechtsanders** [comment]
I have the same issue on Windows/MSYS2 since GCC 10 (MinGW-w64 version from http://winlibs.com) building a number of packages (e.g. GTK3).
This was the release version of GCC 10.1.0.
@Barough which GCC10.x version fixed it for you?
