### ISSUE TITLE
mingw64 SVT-AV1 build error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1647]
[95m11:46:58(B[m   Running git clone for SVT-AV1...
[95m11:48:30(B[m [1m┌ SVT-AV1 git (B[m .............................. [[93mRecently updated(B[m]
[95m11:48:32(B[m [1m├(B[m Running cmake...
[95m11:49:39(B[m [1m├(B[m Running build...
Likely error (tail of the failed operation logfile):
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(common_dsp_rtcd.c.obj):common_dsp_rtcd.c:(.bss+0xa80): multiple definition of `eb_aom_highbd_h_predictor_16x16'; ../Bin/Release/libSvtAv1Enc.a(aom_dsp_rtcd.c.obj):aom_dsp_rtcd.c:(.bss+0x1258): first defined here

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(common_dsp_rtcd.c.obj):common_dsp_rtcd.c:(.bss+0xa78): multiple definition of `eb_aom_highbd_h_predictor_16x32'; ../Bin/Release/libSvtAv1Enc.a(aom_dsp_rtcd.c.obj):aom_dsp_rtcd.c:(.bss+0x1250): first defined here

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(common_dsp_rtcd.c.obj):common_dsp_rtcd.c:(.bss+0x8): multiple definition of `eb_log2f'; ../Bin/Release/libSvtAv1Enc.a(aom_dsp_rtcd.c.obj):aom_dsp_rtcd.c:(.bss+0x7e0): first defined here

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(common_dsp_rtcd.c.obj):common_dsp_rtcd.c:(.bss+0x0): multiple definition of `eb_memcpy'; ../Bin/Release/libSvtAv1Enc.a(aom_dsp_rtcd.c.obj):aom_dsp_rtcd.c:(.bss+0x7d8): first defined here

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(common_dsp_rtcd.c.obj):common_dsp_rtcd.c:(.bss+0xa8): multiple definition of `eb_cdef_filter_block_8x8_16'; ../Bin/Release/libSvtAv1Enc.a(aom_dsp_rtcd.c.obj):aom_dsp_rtcd.c:(.bss+0x880): first defined here

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(common_dsp_rtcd.c.obj):common_dsp_rtcd.c:(.bss+0xe30): multiple definition of `sum_residual8bit'; ../Bin/Release/libSvtAv1Enc.a(aom_dsp_rtcd.c.obj):aom_dsp_rtcd.c:(.bss+0x1608): first defined here

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(common_dsp_rtcd.c.obj):common_dsp_rtcd.c:(.bss+0xe38): multiple definition of `compute8x8_satd_u8'; ../Bin/Release/libSvtAv1Enc.a(aom_dsp_rtcd.c.obj):aom_dsp_rtcd.c:(.bss+0x1610): first defined here

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbFullLoop.c.obj):EbFullLoop.c:(.data+0x140): multiple definition of `allowed_tx_set_a'; ../Bin/Release/libSvtAv1Enc.a(EbProductCodingLoop.c.obj):EbProductCodingLoop.c:(.bss+0x0): first defined here

collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

[31mbuild failed. Check D:/ffmpeg-autobuild/build/SVT-AV1-git/build-64bit/ab-suite.build.log(B[m
[31mThis is required for other packages, so this script will exit.(B[m
[95m11:50:36(B[m   Creating diagnostics file...

[32mAll relevant logs have been anonymously uploaded to https://0x0.st/i_k0.zip
[32mCopy and paste [31m[logs.zip](https://0x0.st/i_k0.zip)[32m in the GitHub issue.(B[m
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
[H[2J[3J
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4615318/logs.zip)

**Comment by moisespr123** [comment]
There's a merge request for it.

**Comment by 1480c1** [comment]
Related PR: https://github.com/OpenVisualCloud/SVT-AV1/pull/1295

**Comment by 1480c1** [comment]
upstream fixed
