### ISSUE TITLE
medialibrary git make failed

### ISSUE THREAD

**Issue by j-mas** [m-ab-s/media-autobuild_suite#1649]
14:59:05   Running git update for medialibrary...
14:59:06 ┌ medialibrary git  ......................... [Recently updated]
14:59:06 ├ Running autoreconf...
14:59:32 ├ Running configure...
 ├ Running make...
Likely error (tail of the failed operation logfile):
      |                                                      |
      |                                                      const string {aka const std::__cxx11::basic_string<char>}
In file included from ../src/filesystem/common/CommonDeviceLister.h:25,
                 from ../src/filesystem/common/CommonDeviceLister.cpp:27:
../include/medialibrary/IDeviceLister.h:48:54: note:   initializing argument 1 of 'virtual void medialibrary::IDeviceListerCb::onDeviceMounted(const int&, const int&, bool)'
   48 |     virtual void onDeviceMounted( const std::string& uuid,
      |                                   ~~~~~~~~~~~~~~~~~~~^~~~
make[1]: *** [Makefile:2201: src/filesystem/common/libmedialibrary_la-CommonDeviceLister.lo] Error 1
make[1]: Leaving directory '/build/medialibrary-git/build-64bit'
make: *** [Makefile:1174: all] Error 2
make failed.

**Comment by 1480c1** [comment]
we need the log.

**Comment by j-mas** [comment]
Here comes the log
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/4624137/ab-suite.make.log)

**Comment by 1480c1** [comment]
```c++
In file included from ../src/filesystem/common/CommonDeviceLister.h:25,
                 from ../src/filesystem/common/CommonDeviceLister.cpp:27:
../include/medialibrary/IDeviceLister.h:48:46: error: 'string' in namespace 'std' does not name a type
   48 |     virtual void onDeviceMounted( const std::string& uuid,
      |                                              ^~~~~~
../include/medialibrary/IDeviceLister.h:27:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
   26 | #include <vector>
  +++ |+#include <string>
   27 | 
```
This is the error that is missing when you don't include the log files. There should have been a message right after the part that you copied that has the message mentioning uploading the log.zip or copying the link into the github issue. Why is it that you are not putting it there in the first place?

**Comment by 1480c1** [comment]
https://code.videolan.org/videolan/medialibrary/-/merge_requests/300

**Comment by j-mas** [comment]
OK. Thanks for the answer. I am only a user and not a programmer. Unfortunately I have no idea what is important to you and what is not. Unfortunately my English is not that good either, just my school English.
But since I use the program every day, it is important for me to report the errors that occur and to ask for help. I will endeavor to post all information and logs that are necessary in the future.

**Comment by 1480c1** [comment]
> OK. Thanks for the answer. I am only a user and not a programmer. Unfortunately I have no idea what is important to you and what is not. Unfortunately my English is not that good either, just my school English.

You should consider that the logs are very important to tell the context of the issue
https://github.com/m-ab-s/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L82

> But since I use the program every day, it is important for me to report the errors that occur and to ask for help. I will endeavor to post all information and logs that are necessary in the future.

Thank you

**Comment by 1480c1** [comment]
Merge request got merged so assuming this is closed
