### ISSUE TITLE
[mingw64] [flite-git] flite tries to build 32-bit version when m-ab-s is configured to only build 64-bit

### ISSUE THREAD

**Issue by ImportTaste** [m-ab-s/media-autobuild_suite#1652]
I did try to delete the flite-git directory already and it didn't make a difference. During the build procedure, once it gets to the make step, it tries to call mingw32 to build the i386 binary. Because my m-ab-s only has the 64-bit tools, this causes it to fail.

**Comment by 1480c1** [comment]
Seems it might be best to report upstream

**Comment by 1480c1** [comment]
Seems to be because of https://github.com/festvox/flite/blob/96c9df6a4c4e64e9e1b7ca040eddb619a386663b/configure#L4084

**Comment by 1480c1** [comment]
Can you try again? I added a patch from the owner of the original fork we used

**Comment by ImportTaste** [comment]
Heh, I was trying to write out an issue as requested but you're five steps ahead of me it seems. I'll try it out.

**Comment by ImportTaste** [comment]
It worked, thanks.
