### ISSUE TITLE
make[1]: *** [Makefile:98: ../bin/flite.exe] Error 1

### ISSUE THREAD

**Issue by Ky-Myrra** [m-ab-s/media-autobuild_suite#1653]
Likely error (tail of the failed operation logfile):
gcc -mthreads -mtune=generic -O2 -pipe -Wall -DCST_NO_SOCKETS -DUNDER_WINDOWS -DWIN32    -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1  -I../include  -c -o flite_lang_list.o flite_lang_list.c
../tools/make_voice_list cmu_us_kal cmu_time_awb cmu_us_kal16 cmu_us_awb cmu_us_rms cmu_us_slt
rm -f flite_voice_list.o
make flite_voice_list.o
gcc -mthreads -mtune=generic -O2 -pipe -Wall -DCST_NO_SOCKETS -DUNDER_WINDOWS -DWIN32    -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1  -I../include  -c -o flite_voice_list.o flite_voice_list.c
gcc -mthreads -mtune=generic -O2 -pipe -Wall -DCST_NO_SOCKETS -DUNDER_WINDOWS -DWIN32    -o ../bin/flite.exe flite_main.o flite_voice_list.o flite_lang_list.o -L../build/x86_64-mingw32/lib -lflite_cmu_us_kal -lflite_cmu_time_awb -lflite_cmu_us_kal16 -lflite_cmu_us_awb -lflite_cmu_us_rms -lflite_cmu_us_slt -lflite_usenglish -lflite_cmu_indic_lang -lflite_cmu_grapheme_lang -lflite_cmulex -lflite_cmu_indic_lex -lflite_cmu_grapheme_lex -lflite -pipe -static-libgcc -static-libstdc++ -lm -lwinmm
D:/Software/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../build/x86_64-mingw32/lib/libflite_cmu_indic_lex.a(cmu_indic_lex.o):cmu_indic_lex.c:(.rdata+0x1380): multiple definition of `cst_rx_not_indic'; ../build/x86_64-mingw32/lib/libflite_cmu_indic_lang.a(cmu_indic_lang.o):cmu_indic_lang.c:(.rdata+0x178): first defined here
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:98: ../bin/flite.exe] Error 1
make: *** [config/common_make_rules:133: build/x86_64-mingw32/obj//.make_build_dirs] Error 2
make failed. Check D:/Software/media-autobuild_suite-master/build/flite-git/ab-suite.make.log
This is required for other packages, so this script will exit.
01:55:47   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iLpc.zip
Copy and paste [logs.zip](https://0x0.st/iLpc.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by LigH-de** [comment]
The title should contain the project name "flite".

I see there was a patch f86cded109c7e9144712020b7165f7f2549fc67e just 3h ago, did you update the suite before compiling?

**Comment by 1480c1** [comment]
The other patch should have specifically addressed this

**Comment by Ky-Myrra** [comment]
> 
> 
> The title should contain the project name "flite".
> 
> I see there was a patch [f86cded](https://github.com/m-ab-s/media-autobuild_suite/commit/f86cded109c7e9144712020b7165f7f2549fc67e) just 3h ago, did you update the suite before compiling?

I'm new to GitHub, so still trying to figure out how to do things.  I edited the tittle, so hopefully it now reflects the error correctly.

I'm not sure how to "update the suite" before compiling, so I just run media-autobuild_suite.bat again several minutes ago, and still receive the same error as before:

11:54:14 ┌ flite git  ................................ [Recently updated]
11:54:15 ├ Running clean...
11:54:24 ├ Running configure...
11:54:50 ├ Running make...
Likely error (tail of the failed operation logfile):
gcc -mthreads -mtune=generic -O2 -pipe -Wall -DCST_NO_SOCKETS -DUNDER_WINDOWS -DWIN32    -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1  -I../include  -c -o flite_lang_list.o flite_lang_list.c
../tools/make_voice_list cmu_us_kal cmu_time_awb cmu_us_kal16 cmu_us_awb cmu_us_rms cmu_us_slt
rm -f flite_voice_list.o
make flite_voice_list.o
gcc -mthreads -mtune=generic -O2 -pipe -Wall -DCST_NO_SOCKETS -DUNDER_WINDOWS -DWIN32    -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1  -I../include  -c -o flite_voice_list.o flite_voice_list.c
gcc -mthreads -mtune=generic -O2 -pipe -Wall -DCST_NO_SOCKETS -DUNDER_WINDOWS -DWIN32    -o ../bin/flite.exe flite_main.o flite_voice_list.o flite_lang_list.o -L../build/x86_64-mingw32/lib -lflite_cmu_us_kal -lflite_cmu_time_awb -lflite_cmu_us_kal16 -lflite_cmu_us_awb -lflite_cmu_us_rms -lflite_cmu_us_slt -lflite_usenglish -lflite_cmu_indic_lang -lflite_cmu_grapheme_lang -lflite_cmulex -lflite_cmu_indic_lex -lflite_cmu_grapheme_lex -lflite -pipe -static-libgcc -static-libstdc++ -lm -lwinmm
D:/Software/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../build/x86_64-mingw32/lib/libflite_cmu_indic_lex.a(cmu_indic_lex.o):cmu_indic_lex.c:(.rdata+0x1380): multiple definition of `cst_rx_not_indic'; ../build/x86_64-mingw32/lib/libflite_cmu_indic_lang.a(cmu_indic_lang.o):cmu_indic_lang.c:(.rdata+0x178): first defined here
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:98: ../bin/flite.exe] Error 1
make: *** [config/common_make_rules:133: build/x86_64-mingw32/obj//.make_build_dirs] Error 2
make failed. Check D:/Software/media-autobuild_suite-master/build/flite-git/ab-suite.make.log
This is required for other packages, so this script will exit.
11:55:44   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iLyD.zip
Copy and paste [logs.zip](https://0x0.st/iLyD.zip) in the GitHub issue.



> 
> 
> The other patch should have specifically addressed this

I'm not sure what "other patch" you were referring to.

Thanks for the replies!

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/f86cded109c7e9144712020b7165f7f2549fc67e#diff-a986c8b0e0f8c10580f72215d3e05a74R906

**Comment by LigH-de** [comment]
> I'm not sure how to "update the suite" before compiling, ...

The trivial way would be to download the [ZIP archive](https://github.com/m-ab-s/media-autobuild_suite/archive/master.zip) and unpack it again over your existing installation, right before running it another time. This suite is updated quite frequently.

**Comment by Ky-Myrra** [comment]
> 
> 
> [f86cded#diff-a986c8b0e0f8c10580f72215d3e05a74R906](https://github.com/m-ab-s/media-autobuild_suite/commit/f86cded109c7e9144712020b7165f7f2549fc67e#diff-a986c8b0e0f8c10580f72215d3e05a74R906)

I downloaded the updated media-suite_compile.sh file via the raw option to override the existing file and was able to run the batch file successfully.


> 
> 
> > I'm not sure how to "update the suite" before compiling, ...
> 
> The trivial way would be to download the [ZIP archive](https://github.com/m-ab-s/media-autobuild_suite/archive/master.zip) and unpack it again over your existing installation, right before running it another time. This suite is updated quite frequently.

I'll be sure to do this when running into errors or rebuilding.

Thanks for your time and assistance!
