### ISSUE TITLE
64 bit, Error running build when updating vulkan-loader git – "ninja: build stopped: subcommand failed"

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1657]
``` bash
05:26:03 ┌ vulkan-loader git  ........................... [Updates found]
05:26:03 ├ Running uninstall...
vulkan-0001-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
05:26:04 ├ Running dependencies...
05:26:17 ├ Installing Vulkan-Headers...
05:26:17 ├ Running uninstall...
05:26:17 ├ Running cmake...
05:26:19 ├ Running build...
05:26:19 ├ Running install...
05:26:20 ├ Building Vulkan-Loader...
05:26:20 ├ Running cmake...
05:26:25 ├ Running build...
Likely error (tail of the failed operation logfile):
../loader/vk_loader_platform.h:349:13: warning: 'loader_platform_thread_cond_wait' defined but not used [-Wunused-function]
  349 | static void loader_platform_thread_cond_wait(loader_platform_thread_cond *pCond, loader_platform_thread_mutex *pMutex) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:348:13: warning: 'loader_platform_thread_init_cond' defined but not used [-Wunused-function]
  348 | static void loader_platform_thread_init_cond(loader_platform_thread_cond *pCond) { InitializeConditionVariable(pCond); }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:339:34: warning: 'loader_platform_get_thread_id' defined but not used [-Wunused-function]
  339 | static loader_platform_thread_id loader_platform_get_thread_id() { return GetCurrentThreadId(); }
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW64/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
05:26:28   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iLvp.zip
Copy and paste [logs.zip](https://0x0.st/iLvp.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

[logs.zip](https://0x0.st/iLvp.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/4637775/ab-suite.build.log)

**Comment by pat357** [comment]
Could this be the cause of the error ?
from the log:
```
vulkan-0001-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.

**Comment by arnabanimesh** [comment]
I am also facing the same issue: [logs.zip](https://0x0.st/ipUd.zip)

**Comment by 1480c1** [comment]
Can you guys try deleting the `build/vulkan-loader-git` folder and rerunning? I am able to apply the patch just fine on my machine

**Comment by VulkanAuto** [comment]
> 
> 
> Can you guys try deleting the `build/vulkan-loader-git` folder and rerunning? I am able to apply the patch just fine on my machine

I am trying this and will update on the result . ty

**Comment by VulkanAuto** [comment]
@1480c1 Hello, I deleted the folder and ran the script again.  It gave me the same error and the script closed. I checked the folder and it downloaded the folder again. Let me know if you want me to try some different changes. Also there is the "CUDA PATH environment variable not set or directory does not exist" I am not sure if it is causing the error. I have attached the log file. 

```20:21:14 ┌ ffmpeg git  ............................. [Newer dependencies]
20:21:14 ├ Until SVT-AV1 issues a fix, libaom & libopencore-amrwb must be disabled while libsvtav1 is enabled....
20:21:14 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
20:21:20 ├ Compiling static FFmpeg...
20:21:21 ├ Running uninstall...
20:21:22 ├ Running configure...
20:24:02 ├ Running make...
20:28:18 ├ Running install...
20:28:24 ├ Stripping...
20:28:24 └ ffmpeg-git  ........................................ [Updated]
20:28:25   Running svn update for mplayer...
20:28:27 mplayer svn  ...................................... [Up-to-date]
20:28:32 ├ Compiling mpv with Vapoursynth R49
20:28:32 ├ mpv will need vapoursynth.dll and vsscript.dll to use vapoursynth filter!
20:28:32   Running git update for mujs...
20:28:33 mujs git  ......................................... [Up-to-date]
20:28:34   Running git clone for vulkan-loader...
20:28:42 ┌ vulkan-loader git  ........................ [Recently updated]
20:28:42 ├ Running uninstall...
vulkan-0001-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
20:28:43 ├ Running dependencies...
20:28:47 ├ Installing Vulkan-Headers...
20:28:47 ├ Running uninstall...
20:28:47 ├ Running cmake...
20:28:47 ├ Running build...
20:28:47 ├ Running install...
20:28:49 ├ Building Vulkan-Loader...
20:28:49 ├ Running cmake...
20:28:51 ├ Running build...
Likely error (tail of the failed operation logfile):
../loader/vk_loader_platform.h:378:13: warning: 'loader_platform_thread_cond_wait' defined but not used [-Wunused-function]
  378 | static void loader_platform_thread_cond_wait(loader_platform_thread_cond *pCond, loader_platform_thread_mutex *pMutex) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:377:13: warning: 'loader_platform_thread_init_cond' defined but not used [-Wunused-function]
  377 | static void loader_platform_thread_init_cond(loader_platform_thread_cond *pCond) { InitializeConditionVariable(pCond); }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:368:34: warning: 'loader_platform_get_thread_id' defined but not used [-Wunused-function]
  368 | static loader_platform_thread_id loader_platform_get_thread_id() { return GetCurrentThreadId(); }
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check D:/build/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
20:28:54   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ipds.zip
Copy and paste [logs.zip](https://0x0.st/ipds.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[LOG](https://0x0.st/ipds.zip)

**Comment by ycwan** [comment]
@1480c1  Deleted build/vulkan-loader-git folder & rerun MAB the same error as below:

20:55:35   Running git clone for vulkan-loader...
20:56:06 ┌ vulkan-loader git  ........................ [Recently updated]
20:56:06 ├ Running uninstall...
vulkan-0001-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
20:56:07 ├ Running dependencies...
20:56:20 ├ Installing Vulkan-Headers...
20:56:20 ├ Running uninstall...
20:56:20 ├ Running cmake...
20:56:20 ├ Running build...
20:56:20 ├ Running install...
20:56:22 ├ Building Vulkan-Loader...
20:56:22 ├ Running cmake...
20:56:26 ├ Running build...
Likely error (tail of the failed operation logfile):
../loader/vk_loader_platform.h:378:13: warning: 'loader_platform_thread_cond_wait' defined but not used [-Wunused-function]
  378 | static void loader_platform_thread_cond_wait(loader_platform_thread_cond *pCond, loader_platform_thread_mutex *pMutex) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:377:13: warning: 'loader_platform_thread_init_cond' defined but not used [-Wunused-function]
  377 | static void loader_platform_thread_init_cond(loader_platform_thread_cond *pCond) { InitializeConditionVariable(pCond); }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:368:34: warning: 'loader_platform_get_thread_id' defined but not used [-Wunused-function]
  368 | static loader_platform_thread_id loader_platform_get_thread_id() { return GetCurrentThreadId(); }
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW64/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
20:56:29   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ipR3.zip
Copy and paste [logs.zip](https://0x0.st/ipR3.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/ipR3.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/4688911/ab-suite.build.log)

**Comment by arnabanimesh** [comment]
I disabled building ```mpv```. Now it is working fine.

**Comment by VulkanAuto** [comment]
> 
> 
> I disabled building `mpv`. Now it is working fine.

How do I disable it?

**Comment by 1480c1** [comment]
Modify build/media-autobuild_suite.ini and change mpv=1 to mpv=2

**Comment by VulkanAuto** [comment]
@1480c1 

Update: I disabled mpv and it did not give me the error. However, I did receive another error from "vlc-corrected-patch"; it says "Patch could not be applied with 'git am' continuing without patching. I am not sure if it is the same issue as Vulkan related to 'git am'. I can disable it as well to try to fix the issue?

```
15:11:28 ┌ vlc git  .................................. [Recently updated]
vlc-corrected-patch
        Patch could not be applied with `git am`. Continuing without patching.
medialib-patch
        Patch could not be applied with `patch`. Continuing without patching.
15:11:30 ├ Running autoreconf...
15:12:34 ├ Running configure...
15:17:23 ├ Running install...
Likely error (tail of the failed operation logfile):
collect2.exe: error: ld returned 1 exit status
make[4]: *** [Makefile:17148: liblibass_plugin.la] Error 1
make[4]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[3]: *** [Makefile:32352: install-recursive] Error 1
make[3]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[2]: *** [Makefile:32790: install] Error 2
make[2]: Leaving directory '/build/vlc-git/build-64bit/modules'
make[1]: *** [Makefile:1575: install-recursive] Error 1
make[1]: Leaving directory '/build/vlc-git/build-64bit'
make: *** [Makefile:2044: install] Error 2
install failed. Check D:/build/build/vlc-git/build-64bit/ab-suite.install.log
This is required for other packages, so this script will exit.
15:24:59   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ifsZ.zip
Copy and paste [logs.zip](https://0x0.st/ifsZ.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

[logs.zip](https://0x0.st/ifsZ.zip)

**Comment by 1480c1** [comment]
you could try to disable vlc or ping @moisespr123 since he was the one who rebased them

**Comment by moisespr123** [comment]
I'll take a look and see what changed.

**Comment by VulkanAuto** [comment]
I changed vlc =1 to vlc =2. I started the program again and will post any updates. Thank you @moisespr123

**Comment by VulkanAuto** [comment]
@1480c1  I disabled VLC and compilation finished successfully.  Thank you for the help.

**Comment by 1480c1** [comment]
nope, not for that one, it's a licensing issue

**Comment by 1480c1** [comment]
I would recommend disabling libopenh264 for ffmpeg if you don't need it

**Comment by 1480c1** [comment]
for those still waiting on this, try recompiling, I changed do_patch to accept slightly off patches that require a 3-way merge

**Comment by VulkanAuto** [comment]
@1480c1 I disabled libopenh264 and recompiled and everything works great. I really appreciate your help. Thank you. :)

**Comment by arnabanimesh** [comment]
> @1480c1 I disabled libopenh264 and recompiled and everything works great. I really appreciate your help. Thank you. :)

I just copied ```libopenh264.dll``` in ```system32``` folder (any folder defined in ```path``` will do).

Also, how did you disable libopenh264?

**Comment by wiiaboo** [comment]
> Also, how did you disable libopenh264?

Use `ffmpegChoice=1` in the .ini and comment/remove the line with `--enable-libopenh264`.

(Please do not copy random dlls to your system32 directory. That's a horrible security practice.)

**Comment by VulkanAuto** [comment]
@arnabanimesh In the folder /build/ there is a file called "ffmpeg_options.txt" open it. At the bottom of the text file I changed "--enable-libopenh264" to "--disable-libopenh264" and than ran the script again to compile and now it works the way I want it to. Hope it helps.
