### ISSUE TITLE
Enabled libfdk_aac not built into final FFmpeg result

### ISSUE THREAD

**Issue by gammaray10k** [m-ab-s/media-autobuild_suite#1658]
Hello. Thank you for the script. I have observed an issue in the last few versions of your script; with libfdk_aac enabled in the script, along with non-free, libfdk_aac gets downloaded by the script and compiled, but it is not compiled into the ffmpeg result. The flag, "--enable-libfdk_aac" is not turned on and the encoder is missing from the ffmpeg result.
[ffmpeg_version.txt](https://github.com/m-ab-s/media-autobuild_suite/files/4639485/ffmpeg_version.txt)
[compile.log](https://github.com/m-ab-s/media-autobuild_suite/files/4639491/compile.log)
[last_successful_run.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4639492/last_successful_run.zip)

**Comment by 1480c1** [comment]
either upload your media-autobuild_suite.ini and ffmpeg_options.txt files or open mintty and run

```bash
source /build/media-suite_helper.sh
zip_logs
``` and upload the logs.zip in the build folder

**Comment by gammaray10k** [comment]
As you requested:

[media-autobuild_suite.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4639508/media-autobuild_suite.zip)
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4639513/logs.zip)

**Comment by 1480c1** [comment]
`ffmpegChoice=3` in media-autobuild_suite.ini will not cause libfdk_aac to be compiled **with** FFmpeg since Zeranoe does not include libfdk_aac inside his builds. You either need to use 1 and modify your ffmpeg_options.txt to have the `--enable-libfdk_aac` option enabled or use 4 to compile essentially everything the suite offers for ffmpeg.

**Comment by gammaray10k** [comment]
Ok, will do. I will test now and and check the results.
