### ISSUE TITLE
Error building ffmpeg

### ISSUE THREAD

**Issue by foroughmajidi** [m-ab-s/media-autobuild_suite#1659]
[logs.zip](https://0x0.st/iLnu.zip)

![Capture4](https://user-images.githubusercontent.com/51900859/82136487-d8650d80-9823-11ea-9b71-16deb8f08da6.PNG)

Could I get these dlls  libavacodec.dll, libavdevice.dll, libavfilter.dll,... by  adding --enable-shared in ffmpeg_options.txt after building?

**Comment by 1480c1** [comment]
Delete the `build/openmpt-git` folder and rerun

You can get your dlls by choosing shared at the initial starting page or changing ffmpegB2 in the `build/media-autobuild_suite.ini` file to 3

**Comment by foroughmajidi** [comment]
thanks

**Comment by foroughmajidi** [comment]
Can I use ffmpeg dll's and lib's within a visual studio project?

**Comment by 1480c1** [comment]
https://sourceforge.net/p/mingw-w64/mailman/message/32027366/

The short answer seems to be maybe with no guarantees either way
