### ISSUE TITLE
vvc is not built

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1661]
Despite `vvc=1` in **media-autobuild_suite.ini**, the **compile.log** does not mention building vvc, and the vvc-git subdirectory is untouched; last modification times are Nov 6, 2019, in my case. Commit 1cfbaf008b34edcc914661a181e6e4bc03feb837 of Nov. 11 restricts building to `64bits` ... maybe this keyword comparison is wrong (e.g. might be singular `64bit` instead)?

Probably. There is a similar restriction for vapoursynth and python, comparing to `64bit`

**Comment by wiiaboo** [comment]
Yeah, it's singular 64bit.

**Comment by LigH-de** [comment]
Requesting pull #1662 for patch 0232830287ddfaeb3d29b59fe8c25f96ba204f72
