### ISSUE TITLE
mingw64 vvc: stringop-overflow in UnitTools.cpp

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1663]
```
[3/151] Building CXX object source/Lib/CommonLib/CMakeFiles/CommonLib.dir/UnitTools.cpp.o
FAILED: source/Lib/CommonLib/CMakeFiles/CommonLib.dir/UnitTools.cpp.o 
E:\MABS\msys64\mingw64\bin\ccache.exe  g++  -DENABLE_SPLIT_PARALLELISM=0 -I../source/Lib/CommonLib/. -I../source/Lib/CommonLib/.. -I../source/Lib/CommonLib/./x86 -I../source/Lib/CommonLib/../libmd5 -mthreads -mtune=generic -O2 -pipe -fopenmp -O3 -DNDEBUG   -Wall -fdiagnostics-show-option -Werror -Wno-sign-compare -Wno-class-memaccess -msse4.1 -mthreads -std=gnu++11 -MD -MT source/Lib/CommonLib/CMakeFiles/CommonLib.dir/UnitTools.cpp.o -MF source\Lib\CommonLib\CMakeFiles\CommonLib.dir\UnitTools.cpp.o.d -o source/Lib/CommonLib/CMakeFiles/CommonLib.dir/UnitTools.cpp.o -c ../source/Lib/CommonLib/UnitTools.cpp
../source/Lib/CommonLib/UnitTools.cpp: In function 'void PU::getInterMergeCandidates(const PredictionUnit&, MergeCtx&, int, const int&)':
../source/Lib/CommonLib/UnitTools.cpp:1261:50: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
 1261 |     mrgCtx.interDirNeighbours [uiArrayAddr     ] = 1;
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
In file included from ../source/Lib/CommonLib/UnitTools.h:43,
                 from ../source/Lib/CommonLib/UnitTools.cpp:38:
../source/Lib/CommonLib/ContextModelling.h:451:17: note: at offset 6 to object 'MergeCtx::interDirNeighbours' with size 6 declared here
  451 |   unsigned char interDirNeighbours[ MRG_MAX_NUM_CANDS      ];
      |                 ^~~~~~~~~~~~~~~~~~
../source/Lib/CommonLib/UnitTools.cpp:1262:50: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
 1262 |     mrgCtx.BcwIdx             [uiArrayAddr     ] = BCW_DEFAULT;
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from ../source/Lib/CommonLib/UnitTools.h:43,
                 from ../source/Lib/CommonLib/UnitTools.cpp:38:
../source/Lib/CommonLib/ContextModelling.h:450:17: note: at offset 6 to object 'MergeCtx::BcwIdx' with size 6 declared here
  450 |   uint8_t       BcwIdx            [ MRG_MAX_NUM_CANDS      ];
      |                 ^~~~~~
../source/Lib/CommonLib/UnitTools.cpp:1268:58: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
 1268 |       mrgCtx.interDirNeighbours [ uiArrayAddr          ] = 3;
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
In file included from ../source/Lib/CommonLib/UnitTools.h:43,
                 from ../source/Lib/CommonLib/UnitTools.cpp:38:
../source/Lib/CommonLib/ContextModelling.h:451:17: note: at offset 6 to object 'MergeCtx::interDirNeighbours' with size 6 declared here
  451 |   unsigned char interDirNeighbours[ MRG_MAX_NUM_CANDS      ];
      |                 ^~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

You seem to use your own fork of the VVC repo, so I am not sure where to report this issue upstream: jvet.hhi.fraunhofer.de/trac/vvc or vcgit.hhi.fraunhofer.de/ksuehring/VVCSoftware_VTM are two possible trackers I know about ...

[ab-suite.install.log](https://github.com/m-ab-s/media-autobuild_suite/files/4649454/ab-suite.install.log)

**Comment by 1480c1** [comment]
You should probably report to Fraunhofer since the fork we use is just an automatic updating repo that we use so that we are using as many github/gitlab based repos to lighten the overall load on the main servers, particularly with ones that are self-hosted by some companies.

**Comment by LigH-de** [comment]
Reported to [VVC trac ticket 1072](https://jvet.hhi.fraunhofer.de/trac/vvc/ticket/1072)

**Comment by LigH-de** [comment]
Still no response from the JVET team after 2 weeks ... I tried to bump.

**Comment by LigH-de** [comment]
[JVET will not](https://jvet.hhi.fraunhofer.de/trac/vvc/ticket/1072#comment:2)
> spend time for installing an unsupported compiler on an unsupported platform to re-produce the problem.
because
> The software compiles fine under a wide range of supported compilers.

**Comment by moisespr123** [comment]
From the last comment, apparently passing `-Wno-stringop-overflow` should resolve this.

**Comment by LigH-de** [comment]
A patch was linked.

A few more comments follow up, may be worth reading too.

**Comment by Jamaika1** [comment]
I shouldn't care about vvc problems because I'm not a creator and they don't pay me for advice. In addition I can't manually add my patches to git vvc because you don't want without CLA.
Apart from this fact, it is a problem of combining uint32 or unsigned to int.  Apparently, there is no problem with this in Visual Studio.
Change uint32 or unsigned to int:
https://github.com/Jamaika1/libbpg_jvetvvc

**Comment by ValZapod** [comment]
> We know, we know: Ignoring a warning is so ... unprofessional ... or isn't it?

No, it is not. They already turned off some warnings. It is nothing supernatural. Also it is new from GCC 10.
