### ISSUE TITLE
FFmpeg failed to compile

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1667]
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
D:/media-autobuild_suite-ffmpeg/local32/include/avisynth/avisynth_c.h:1325: note: macro "AVSC_LOAD_FUNC" defined here
 1325 | #define AVSC_LOAD_FUNC(name) {\
      |
D:/media-autobuild_suite-ffmpeg/local32/include/avisynth/avisynth_c.h:1453:37: error: macro "AVSC_LOAD_FUNC" passed 2 arguments, but takes just 1
 1453 |   AVSC_LOAD_FUNC(avs_is_y, avs_is_y8);
      |                                     ^
D:/media-autobuild_suite-ffmpeg/local32/include/avisynth/avisynth_c.h:1325: note: macro "AVSC_LOAD_FUNC" defined here
 1325 | #define AVSC_LOAD_FUNC(name) {\
      |
make: *** [/build/ffmpeg-git/ffbuild/common.mak:59: libavformat/avisynth.o] Error 1
make failed. Check D:/media-autobuild_suite-ffmpeg/build/ffmpeg-git/build-static-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/i93i.zip
Copy and paste [logs.zip](https://0x0.st/i93i.zip) in the GitHub issue.

**Comment by Patman86** [comment]
Same with 64bit. Maybe new AviSynthPlus version?

**Comment by kliffgomel** [comment]
same on 64bit
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4661751/logs.zip)

**Comment by martininguyen** [comment]
I'm also having troubling compiling
[i90z.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4664362/i90z.zip)

**Comment by 1480c1** [comment]
https://github.com/AviSynth/AviSynthPlus/commit/d4983ce5526684e68df85f9124843de5a72381cd

try again

**Comment by gammaray10k** [comment]
I know I'm not the original poster, but whatever you did worked for me, compiling completed without an issue. - Win10 x64, shared and static builds.

**Comment by 1480c1** [comment]
I didn't do anything, they fixed it 8 hours ago in the commit I linked
