### ISSUE TITLE
vapoursynth r50 with python 3.8.3

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#1670]
I've tested with change the "media-suite_compile.sh" it works fine.

Any plan to update the libs version?

**Comment by 1480c1** [comment]
Idk, we usually don't have automatic notification for updates etc and i only really notice any new updates when i am looking through all of the packages so no real plans other than "once i get to it".

We do encourage you to try to submit a pull request with the update changes once you do notice them, that way it's not limited to whenever a contributor's time allows for it
