### ISSUE TITLE
Some failure? - ab-suite.make.log

### ISSUE THREAD

**Issue by lincalinca** [m-ab-s/media-autobuild_suite#1671]
https://0x0.st/ip2G.zip

 Check C:/StreamApps/media-autobuild_suite-master/build/libpsl-0.21.0/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.

**Comment by 1480c1** [comment]
Rebuild with latest suite

**Comment by lincalinca** [comment]
Thanks. Running it again now.
