### ISSUE TITLE
Request: local patch failures should display the filename of the failed patch

### ISSUE THREAD

**Issue by ImportTaste** [m-ab-s/media-autobuild_suite#1674]
One of the svt patches is failing to apply, but it's not indicating which one. I see in the helper file that there's text which will indicate which patch failed to apply for patches downloaded through curl, but not for local patches.

**Comment by 1480c1** [comment]
```bash
    if [[ -f $patchName ]]; then
        if $am; then
            git apply --check --ignore-space-change --ignore-whitespace "$patchName" > /dev/null 2>&1 &&
                git am -q --ignore-whitespace --no-gpg-sign "$patchName" > /dev/null 2>&1 &&
                return 0
            git am -q --abort > /dev/null 2>&1
        else
            patch --dry-run $binarypatch -s -N -p"$strip" -i "$patchName" > /dev/null 2>&1 &&
                patch $binarypatch -s -N -p"$strip" -i "$patchName" &&
                return 0
        fi
        printf '%b\n' "${orange}${patchName}${reset}" \
            '\tPatch could not be applied with `'"$($am && echo "git am" || echo "patch")"'`. Continuing without patching.'
    else
        printf '%b\n' "${orange}${patchName}${reset}" \
            '\tPatch not found anywhere. Continuing without patching.'
    fi
    return 1
```

as far as I can tell, it should always print out a patchName if it failed.

When you say svt patch and local patch, did you download one of the patches and tried applying that one?

**Comment by ImportTaste** [comment]
No, I'm talking about when it stores a patch inside of the ffmpeg-git directory and then tries to apply it. It did not print which patch failed.

**Comment by 1480c1** [comment]
Do you know what message it prints out?

**Comment by ImportTaste** [comment]
"patch unexpectedly ends in middle of line"

**Comment by 1480c1** [comment]
That is technically not an error, but a warning

https://unix.stackexchange.com/questions/1395/what-does-patch-unexpectedly-ends-in-middle-of-line-mean

One "fix" is to regenerate the patches, which I can try to do

**Comment by ImportTaste** [comment]
If a patch unexpectedly ends, I would think for that to mean it failed to apply somehow, which seems odd for a warning.

**Comment by 1480c1** [comment]
It's more like the file might be lacking a Newline or two at the end

**Comment by ImportTaste** [comment]
Oh, I see. So it's successfully applying but it's just slightly formatted the wrong way?

**Comment by 1480c1** [comment]
Yeah, essentially

**Comment by ImportTaste** [comment]
My mistake then, sorry about that.

**Comment by 1480c1** [comment]
It's fine, I probably should go ahead and try to regenerate the patches since that message has honestly been a bit annoying
