### ISSUE TITLE
[mingw64] [ffmpeg] [clang] unexpected libbrotlidec.dll runtime dependency

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1676]
I successfully compiled ffmpeg using clang (ffmpeg limited configuration)
But in the compiled file ffmpeg.exe there is a dll dependency on the libbrotlidec.dll library. The ffmpeg executable cannot be started.

**Comment by kliffgomel** [comment]
[build.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4682929/build.zip)

**Comment by 1480c1** [comment]
Can you try enabling curl in the media-autobuild_suite.ini and reruning?

**Comment by kliffgomel** [comment]
Enabling curl in the script configuration solves the problem with the brotli library in the ffmpeg executable. But I note that when gcc is used, there is no such direct dependency in the configuration. The curl compilation required the compilation of another dependency, libpsl, which I had previously failed to compile using clang. But now, for the first time, I have had everything compiled without errors using clang, let in a limited configuration.
