### ISSUE TITLE
Request: Compile luajit and add shinchiro's patch to support utf-8 filenames

### ISSUE THREAD

**Issue by wiiaboo** [m-ab-s/media-autobuild_suite#1678]
See https://github.com/shinchiro/mpv-winbuild-cmake/commits/master/packages/luajit.cmake since shinchiro/mpv-winbuild-cmake@e5818ef61c5ed4ee734bbb6fa88e59e4ccf4f8d1 and https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/luajit-0001-add-win32-utf-8-filesystem-functions.patch for the patch.

**Comment by 1480c1** [comment]
Should I install this to bin-global, or just bin?

**Comment by wiiaboo** [comment]
The luajit executable? bin-global, like it was before we started using the mingw one.

**Comment by wiiaboo** [comment]
See/partially revert https://github.com/m-ab-s/media-autobuild_suite/commit/356762a1c8623269bbd4059cff55b49f49f4d2f5

**Comment by 1480c1** [comment]
Should I include the checks for `standalone`? I think some programs might need the `luajit` executable (I'm not sure about it, will need to recheck)

**Comment by wiiaboo** [comment]
Sure. luajit is moderately useful to test mpv scripts too.

**Comment by wiiaboo** [comment]
You can probably always compile it disregarding $standalone. luajit.exe is negligibly small.
