### ISSUE TITLE
libplacebo: No module named 'mako'

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1679]
```
[10/42] Generating vulkan boilerplate with a custom command
FAILED: src/utils_gen.c 
"E:/MABS/msys64/mingw32/bin/python3.EXE" "../src/vulkan/utils_gen.py" "/usr/share/vulkan/registry/vk.xml" "src/utils_gen.c"
Traceback (most recent call last):
  File "../src/vulkan/utils_gen.py", line 19, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
```

Looks like it might be just a typo (make or makro instead)...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4694624/logs.zip)

[videolan/libplacebo issue 93](https://code.videolan.org/videolan/libplacebo/-/issues/93)

**Comment by LigH-de** [comment]
According to the [dependencies list](https://code.videolan.org/videolan/libplacebo#dependencies), `python3-mako` is now required.

**Comment by pat357** [comment]
Which python3-make is required ?
The one from MingW or the msys2 one ?

$ pacman -Ss python3-mako
mingw32/mingw-w64-i686-python-mako 1.1.2-1
    A super-fast templating language that borrows the best ideas from the existing templating languages (mingw-w64)
mingw64/mingw-w64-x86_64-python-mako 1.1.2-1
    A super-fast templating language that borrows the best ideas from the existing templating languages (mingw-w64)
msys/python-mako 1.1.2-2
    A super-fast templating language that borrows the best ideas from the existing templating languages

**Comment by ycwan** [comment]
I have just run MAB and was so happy the vulkan-loader got successfully updated, but unfortunately ran into the same problem reported in this issue report next

20:08:18   Running git update for libplacebo...
20:08:23 ┌ libplacebo git  .............................. [Updates found]
20:08:23 ├ Running uninstall...
20:08:23 ├ Running meson...
20:08:27 ├ Running build...
Likely error (tail of the failed operation logfile):
[17/37] Compiling C object src/25a6634@@placebo@sta/vulkan_gpu.c.obj
ninja: build stopped: subcommand failed.
[1/21] Generating vulkan boilerplate with a custom command
FAILED: src/utils_gen.c
"C:/MinGW64/msys64/mingw64/bin/python3.EXE" "../src/vulkan/utils_gen.py" "/usr/share/vulkan/registry/vk.xml" "src/utils_gen.c"
Traceback (most recent call last):
  File "../src/vulkan/utils_gen.py", line 19, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW64/build/libplacebo-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
20:08:31   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ifH5.zip
Copy and paste [logs.zip](https://0x0.st/ifH5.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/ifH5.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/4695484/ab-suite.build.log)

**Comment by LigH-de** [comment]
We were already told the reason by the developers of libplacebo: Now it needs one more package (`python3-mako`) to be installed.

**Comment by LigH-de** [comment]
Pretty confusing for me to know here whether to include the `3` or not...

**Comment by 1480c1** [comment]
For msys2's pacman packages, they are trying to remove as much of the python2 packages as possible https://packages.msys2.org/python2

**Comment by pat357** [comment]
> Pretty confusing for me to know here whether to include the `3` or not...

There apparently is no package with the 3 included, there is just **python-mako** ....
Convince yourself by searching through the packages :
```
$ pacman -Ss python3-mako
mingw32/mingw-w64-i686-python-mako 1.1.2-1
    A super-fast templating language that borrows the best ideas from the existing templating languages (mingw-w64)
mingw64/mingw-w64-x86_64-python-mako 1.1.2-1
    A super-fast templating language that borrows the best ideas from the existing templating languages (mingw-w64)
msys/python-mako 1.1.2-2
    A super-fast templating language that borrows the best ideas from the existing templating languages
```
BTW, does it work for you after installing this extra package  ?
For me it still errors out like:
```
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
ninja -j10 
[1/37] Compiling C object subprojects/bstr/0ab0a38@@bstr@sta/siphash.c.obj
[2/37] Compiling C object subprojects/xtalloc/f0d261a@@xtalloc@sta/xtalloc.c.obj
[3/37] Generating vulkan boilerplate with a custom command
FAILED: src/utils_gen.c 
"H:/Mingw647/msys64/mingw32/bin/python3.EXE" "../src/vulkan/utils_gen.py" "/usr/share/vulkan/registry/vk.xml" "src/utils_gen.c"
Traceback (most recent call last):
  File "../src/vulkan/utils_gen.py", line 94, in <module>
    registry = ET.parse(xmlfile)
  File "H:/Mingw647/msys64/mingw32/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "H:/Mingw647/msys64/mingw32/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/vulkan/registry/vk.xml'

**Comment by 1480c1** [comment]
pull latest changes, it was changed https://github.com/m-ab-s/media-autobuild_suite/issues/1680

**Comment by LigH-de** [comment]
I am sorry to keep asking here; I tried in IRC but nobody knew...

When I tested a solution, I tried to let the suite install `python3-mako` so it keeps recommnding to install `mingw-w64-i686-python3-mako` and `mingw-w64-x86_64-python3-mako` at every run but can't find them. How do I make pacman forget about them?

**Comment by wiiaboo** [comment]
do_pacman_uninstall python3-mako, or just remove the line directly for
/msys64/etc/somethingpkg

**Comment by LigH-de** [comment]
`pac-mingw-extra.pk` - thank you.
