### ISSUE TITLE
No "ffmpeg_options.txt" file in build folder

### ISSUE THREAD

**Issue by arnabanimesh** [m-ab-s/media-autobuild_suite#1681]
```ffmpeg_options.txt``` is not being created while building. It is resulting in an inability to modify compile options for FFmpeg.

Please find the logs attached herewith: [logs.zip](https://0x0.st/ipUd.zip)

**Comment by wiiaboo** [comment]
You're using `ffmpegChoice=4` in your .ini. That file is only created and used if it's `ffmpegChoice=1`.
