### ISSUE TITLE
[Question] FFmpeg & exhale

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1688]
Got the question from a m8 if it's possible to add exhale into FFmpeg and i don't know so i thought i would ask here. Is it possible to add exhale into FFmpeg and if so, how?

**Comment by 1480c1** [comment]
Not yet, exhale doesn't have an ffmpeg patch and it's not been upstreamed afaik

**Comment by 1480c1** [comment]
https://trac.ffmpeg.org/ticket/8411

**Comment by Barough** [comment]
Thnx for the info/reply

**Comment by 1480c1** [comment]
https://gitlab.com/ecodis/exhale/-/issues/7

opened an issue with exhale, although I do doubt there's any plans to do so consider it doesn't have a "proper" c-api for FFmpeg to use
