### ISSUE TITLE
[mingw32|mingw64] unable to download MinGW

### ISSUE THREAD

**Issue by Henrik3901** [m-ab-s/media-autobuild_suite#1689]
Hi,
I have an issue with MinGW. Installed from Scratch on an new installed Windows 1909 64 bit (also tested on two other Windows PCs. Tried both MinGW32 and 64 but it allways failed at the beginning with:
``` bash
-------------------------------------------------------------------------------
install 64 bit compiler
-------------------------------------------------------------------------------
xargs: pacboy: No such file or directory
xargs: pacboy: No such file or directory
-------------------------------------------------------------------------------

MinGW64 GCC compiler isn't installed; maybe the download didn't work
Do you want to try it again?

-------------------------------------------------------------------------------
try again [y/n]:
```
Pressing y and enter: nothing happens, n it closes. 
I can reach all MinGW Servers.
Any Ideas, whats wrong?

Thanks
Henrik

[mingw64.log](https://github.com/m-ab-s/media-autobuild_suite/files/4707610/mingw64.log)
[pacman.log](https://github.com/m-ab-s/media-autobuild_suite/files/4707611/pacman.log)
[secondUpdate.log](https://github.com/m-ab-s/media-autobuild_suite/files/4707612/secondUpdate.log)
[firstrun.log](https://github.com/m-ab-s/media-autobuild_suite/files/4707613/firstrun.log)
[firstUpdate.log](https://github.com/m-ab-s/media-autobuild_suite/files/4707614/firstUpdate.log)

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4707616/logs.zip)

**Comment by Henrik3901** [comment]
Thanks!!!

**Comment by 1480c1** [comment]
you too
