### ISSUE TITLE
libfdk_aac not implemented

### ISSUE THREAD

**Issue by MediaxSF6** [m-ab-s/media-autobuild_suite#1690]
[libfdk_aac.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4708568/libfdk_aac.zip)
the compiling with included fdk_aac did run with out error message but the libfdk_aac seems not to be present...

**Comment by 1480c1** [comment]
check to make sure if you have either selected all libs for FFmpeg, `--enable-libfdk_aac` in ffmpeg_options with nonfree selected

https://github.com/m-ab-s/media-autobuild_suite/issues/1658#issuecomment-629729754

**Comment by 1480c1** [comment]
`ffmpegChoice=2` in media-autobuild_suite.ini needs to either be 1 or 4 since choosing any in the middle will not offer fdk_aac since it's not provided by zeranoe nor is worth putting in light build since FFmpeg has their own aac encoder
