### ISSUE TITLE
--enable-nonfree

### ISSUE THREAD

**Issue by MediaxSF6** [m-ab-s/media-autobuild_suite#1691]
why doe he tell me that:
"libfdk_aac is incompatible with the gpl and --enable-nonfree is not specified." 
while it is and gpl is commented out...?

https://0x0.st/iOr6.zip

**Comment by 1480c1** [comment]
Did you select nonfree in the beginning questions?

**Comment by MediaxSF6** [comment]
yes

**Comment by MediaxSF6** [comment]
thats why I was yesterday irritated, because I expected whe I chose "nonfree" the "--enable" command will be automatically included; the same for the libfdk_aac...

**Comment by 1480c1** [comment]
How about trying to not have an explicit `--enable-nonfree` in ffmpeg_options.txt?

**Comment by 1480c1** [comment]
@wiiaboo do you think another option to ffmpegchoice called `Zeranoe plus fdk-aac` would be good? since there seems to be a lot of people who want fdk-aac, but don't understand that the zeranoe emulating one would not have it by default

**Comment by MediaxSF6** [comment]
> 
> 
> How about trying to not have an explicit `--enable-nonfree` in ffmpeg_options.txt?

same outcome...
![aac](https://user-images.githubusercontent.com/66224578/83437437-0fe8d200-a440-11ea-8636-2e34b9b8132e.jpg)

**Comment by wiiaboo** [comment]
> @wiiaboo do you think another option to ffmpegchoice called `Zeranoe plus fdk-aac` would be good? since there seems to be a lot of people who want fdk-aac, but don't understand that the zeranoe emulating one would not have it by default

Well, if fdk-aac is added to the zeranoe-emulating option, it stops being a zeranoe-emulating option, so I disagree with it, no matter how many people think they expect fdk-aac to be there. Zeranoe won't include it as it would make his GPL builds unredistributable, and people would still bitch about fdk-aac not being included if they don't choose nonfree license.

I'd say it's enough to fix whatever issue is going on here.

**Comment by wiiaboo** [comment]
@MediaxSF6 use `--enable-libfdk-aac` instead.

**Comment by wiiaboo** [comment]
On the other hand, openssl is already part of the zeranoe-emulating options, so it could be argued that fdk-aac could also be there.

**Comment by 1480c1** [comment]
> > @wiiaboo do you think another option to ffmpegchoice called `Zeranoe plus fdk-aac` would be good? since there seems to be a lot of people who want fdk-aac, but don't understand that the zeranoe emulating one would not have it by default
> 
> Well, if fdk-aac is added to the zeranoe-emulating option, it stops being a zeranoe-emulating option, so I disagree with it, no matter how many people think they expect fdk-aac to be there. Zeranoe won't include it as it would make his GPL builds unredistributable, and people would still bitch about fdk-aac not being included if they don't choose nonfree license.
> 
> I'd say it's enough to fix whatever issue is going on here.

I meant as in a option 5 which would be the zeranoe emulating libs, plus libfdk_aac, not appending libfdk_aac to the current zeranoe emulating option

**Comment by wiiaboo** [comment]
> @MediaxSF6 use `--enable-libfdk-aac` instead.

FFmpeg takes your `--enable-libfdk_aac` fine, but our code doesn't, and so it removes `--enable-nonfree` (as it sees you're not using any nonfree lib, so it tries to make your build redistributable if possible).

**Comment by wiiaboo** [comment]
Changing `license2` to `license3` requiring everyone to update their .ini options just to add an option with just fdk-aac extra? Seems like it'd be simpler to just add it to zeranoe's options.

**Comment by MediaxSF6** [comment]
> 
> 
> > @MediaxSF6 use `--enable-libfdk-aac` instead.
> 
> FFmpeg takes your `--enable-libfdk_aac` fine, but our code doesn't, and so it removes `--enable-nonfree` ...

...so, in other words: it is a typo... don't know why the error-message is not "unknown codeck, please check..."

**Comment by wiiaboo** [comment]
It's a typo that FFmpeg happens to accept, but not m-ab-s.
