### ISSUE TITLE
Build issue w/ svt-vp9

### ISSUE THREAD

**Issue by bentotom** [m-ab-s/media-autobuild_suite#1694]
Running into an issue while compiling ffmpeg + SVTVP9 with autobuild suite. 64bit

using latest SVTVP9 git from earlier today.
and master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch

log
```
E:/media-autobuild_suite-master/build/ffmpeg-git/libavcodec/libsvt_vp9.c: In function 'config_enc_params':
E:/media-autobuild_suite-master/build/ffmpeg-git/libavcodec/libsvt_vp9.c:191:10: error: 'EbSvtVp9EncConfiguration' has no member named 'intra_refresh_type'
  191 |     param->intra_refresh_type       =
      |          ^~
make: *** [/build/ffmpeg-git/ffbuild/common.mak:59: libavcodec/libsvt_vp9.o] Error 1
```

https://github.com/OpenVisualCloud/SVT-VP9/issues/113#issue-629393067

**Comment by bentotom** [comment]
#https://github.com/OpenVisualCloud/SVT-VP9/issues/113#issue-629393067

**Comment by 1480c1** [comment]
Just making sure, you are compiling using default suite with nothing changed?

**Comment by bentotom** [comment]
What do you mean by nothing changed?
The only patch I have applied is the vp9 patch. Everything else is vanilla. 

Build compiled correctly on Full.
Build failed with Full = SVT-VP9.
Build compiled correctly with a few packages disabled.
Build compiled correctly with a few packages disabled + VP9.

**Comment by 1480c1** [comment]
I mean, by using `--enable-libsvt_vp9`, the suite will pull in the appropriate patch, you should not be doing any manual patching at all.

**Comment by bentotom** [comment]
The included patch was throwing errors, I reconfigured the URI to point to "master-0001-..."
Same errors.

**Comment by 1480c1** [comment]
Are you sure it's actually throwing errors? What kind of errors?

**Comment by bentotom** [comment]
same error listed above when i reverted everything back to the original package.
No _extra.sh, patching with original media-suite_compile.sh link

**Comment by bentotom** [comment]
@1480c1 
What does the 'am' option at the end of the do_patch command do?
I think the issue was the URI for the patch being outdated. However, updating the URI returns
` Patch could not be applied with `patch``

**Comment by 1480c1** [comment]
I see what the problem is now

**Comment by bentotom** [comment]
Patch files were updated
https://github.com/OpenVisualCloud/SVT-VP9/issues/113#issuecomment-637914601

Thanks again
