### ISSUE TITLE
32bit ffmpeg configure fail: libgme not found

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#1698]
08:09:53 ├ Compiling FFmpeg with Vapoursynth R50
08:09:53 ├ FFmpeg will need vapoursynth.dll and vsscript.dll to run using vapoursynth demuxers!
08:09:53   Running git clone for ffmpeg...
08:11:07 ┌ ffmpeg git  ............................... [Recently updated]
08:11:07 ├ Changing options to comply to gplv3...
08:11:10 ├ Compiling static FFmpeg...
08:11:11 ├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local32/lib -L/mingw32/lib
../configure --prefix=/local32 --bindir=/local32/bin-video --pkg-config-flags=--static --cc=ccache gcc --cxx=ccache g++ --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libaom --enable-libopenmpt --enable-version3 --enable-chromaprint --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-libsrt --enable-ladspa --enable-librav1e --enable-vapoursynth --enable-liblensfun --enable-opencl --enable-opengl --enable-libopenh264 --enable-mbedtls --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --extra-version=g7f817853cd+2
ERROR: libgme not found

If you think configure made a mistake, make sure you are using the latest

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4734283/logs.zip)

**Comment by 1480c1** [comment]
Try updating suite

**Comment by ASopH** [comment]
Hi, suite ist up to date... starting update every time before I start the suite...
I've tried deleting ffmpeg-folder - not working.

**Comment by 1480c1** [comment]
Try deleting local32/lib/libgme.a

**Comment by ASopH** [comment]
seems working now!
thanks :-)
