### ISSUE TITLE
[mingw64] [cargo-c] build error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1702]
[95m10:11:13(B[m   Running git update for aom...
[95m10:11:17(B[m [1maom git (B[m .......................................... [[32mUp-to-date(B[m]
[95m10:11:18(B[m   Running git clone for cargo-c...
[95m10:11:23(B[m [1m┌ cargo-c git (B[m .............................. [[93mRecently updated(B[m]
[95m10:11:23(B[m [1m├(B[m Running ssh2-clone...
[95m10:11:41(B[m [1m├(B[m Running rust.update...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
/opt/cargo/bin/cargo.exe update
/build/media-suite_helper.sh: line 1441: /opt/cargo/bin/cargo.exe: No such file or directory
[31mrust.update failed. Check D
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4744723/logs.zip)
:/ffmpeg-autobuild/build/cargo-c-git/ab-suite.rust.update.log(B[m
[31mThis is required for other packages, so this script will exit.(B[m

**Comment by kliffgomel** [comment]
And anyway, why do we need cargo-c if rav1e (librav1e) is disabled?

**Comment by wiiaboo** [comment]
Missing a `&&` on L1054.

**Comment by wiiaboo** [comment]
Regression from 72ab9f3859f9bcc314784d871765a34576c05f4e
