### ISSUE TITLE
[mingw64] [mpv] Uninstalling python3-docutils... failed

### ISSUE THREAD

**Issue by ImportTaste** [m-ab-s/media-autobuild_suite#1704]
It's probably nothing, but this error came up today, and it seems... out of place? I'm not sure why it would even be trying to do this.
```
┌ mpv git  ..................................... [Updates found]
├ Running bootstrap...
├ Running uninstall...
├ Uninstalling python3-docutils... failed
```

**Comment by 1480c1** [comment]
the main reason was before python3-docutils was replaced with python-docutils, but pacman didn't properly recognize the changeover and would error out during an update or something, I think it's safe to remove it now
