### ISSUE TITLE
Luajit : patch could not be applied ....

### ISSUE THREAD

**Issue by pat357** [m-ab-s/media-autobuild_suite#1709]
Since a recent update on the luajit repo, the patches are reported as:
 "_Patch could not be applied with `git am`. Continuing without patching."_

Everything builds ok, so I have no logs.zip.
Are the patches no longer required or do they need a rebase ?

``` bash
 Running git update for luajit...
 ┌ luajit git  ...................................................... [Files missing]
 ├ Running uninstall...
 ├ Running clean...
luajit-0001-add-win32-utf-8-filesystem-functions.patch
	Patch could not be applied with `git am`. Continuing without patching.
0001-win32-UTF-8-Remove-va-arg-and-.-and-unused-functions.patch
	Patch could not be applied with `git am`. Continuing without patching.
 ├ Running make...
 ├ Running install...
 ├ Stripping...
 └ luajit-git  ............................................................ [Updated]

**Comment by 1480c1** [comment]
Seems that shinchiro rebased on LuaJIT's master branch, which is considerably behind their v2.1 branch, I will have to regenerate the patches it seems
