### ISSUE TITLE
exhale error

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1710]
This started to happen after the latest exhale commit to the suite. No logs

  Running git clone for exhale...
┌ exhale git  ......................................... [Recently updated]
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/1] Linking CXX executable src\app\exhale.exe
FAILED: src/app/exhale.exe
cmd.exe /C "cd . && D:\mabs\msys64\mingw32\bin\ccache.exe  g++ -Wall -Wshadow -mthreads -mtune=generic -O2 -pipe -Wuninitialized -O3 -DNDEBUG  -pipe -static-libgcc -static-libstdc++ src/app/CMakeFiles/exhaleApp.dir/loudnessEstim.cpp.o src/app/CMakeFiles/exhaleApp.dir/basicMP4Writer.cpp.o src/app/CMakeFiles/exhaleApp.dir/exhaleApp.cpp.o src/app/CMakeFiles/exhaleApp.dir/exhaleApp.rc.obj src/app/CMakeFiles/exhaleApp.dir/basicWavReader.cpp.o src/app/CMakeFiles/exhaleApp.dir/exhaleAppPch.cpp.o  -o src\app\exhale.exe -Wl,--major-image-version,0,--minor-image-version,0  src/lib/libexhale.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o): in function `main':
D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check D:/mabs/build/exhale-git/build-32bit/ab-suite.build.log
This isn't required for anything so we can move on.
├ Running install...
Likely error (tail of the failed operation logfile):
D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/2] Linking CXX executable src\app\exhale.exe
FAILED: src/app/exhale.exe
cmd.exe /C "cd . && D:\mabs\msys64\mingw32\bin\ccache.exe  g++ -Wall -Wshadow -mthreads -mtune=generic -O2 -pipe -Wuninitialized -O3 -DNDEBUG  -pipe -static-libgcc -static-libstdc++ src/app/CMakeFiles/exhaleApp.dir/loudnessEstim.cpp.o src/app/CMakeFiles/exhaleApp.dir/basicMP4Writer.cpp.o src/app/CMakeFiles/exhaleApp.dir/exhaleApp.cpp.o src/app/CMakeFiles/exhaleApp.dir/exhaleApp.rc.obj src/app/CMakeFiles/exhaleApp.dir/basicWavReader.cpp.o src/app/CMakeFiles/exhaleApp.dir/exhaleAppPch.cpp.o  -o src\app\exhale.exe -Wl,--major-image-version,0,--minor-image-version,0  src/lib/libexhale.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o): in function `main':
D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
install failed. Check D:/mabs/build/exhale-git/build-32bit/ab-suite.install.log
This isn't required for anything so we can move on.
├ /local32/bin-audio/exhale.exe  ............................. [Not found]
└ exhale-git  ................................................... [Failed]

**Comment by moisespr123** [comment]
Check if your `bin-audio` folder has `exhale.exe`. I ran into this yesterday and made a patch to let the suite continue because of this issue. It actually compiled for me.

**Comment by Barough** [comment]
No 'exhale.exe' available in my bin-audio folder

**Comment by Barough** [comment]
Issue fixed upstream.
