### ISSUE TITLE
Request: ffmpeg-gl-transition

### ISSUE THREAD

**Issue by vuknikolic** [m-ab-s/media-autobuild_suite#1711]
Hi,
it look like nice feature. it will be nice to have it.
https://github.com/transitive-bullshit/ffmpeg-gl-transition

regards

**Comment by wiiaboo** [comment]
Yes. Include it in your custom build if you want.
But not the suite. That's opening a can of worms for every slowflake to add their special plugin.
Have them submit it to ffmpeg-devel if they want.
