### ISSUE TITLE
Openal : Patch could not be applied with `patch`.....

### ISSUE THREAD

**Issue by pat357** [m-ab-s/media-autobuild_suite#1712]
Due updates to CMakelist.txt, it seems the patches from MingW need to be rebased.
The building doesn't fail,  but the created & installed lib is called **libOpenAL32.a** instead of just **libopenal.a**.

``` bash
17:51:43 ┌ openal-soft git  ................................................. [Updates found]
17:51:43 ├ Running uninstall...
0003-openal-not-32.mingw.patch
        Patch could not be applied with `patch`. Continuing without patching.
0004-disable-OSS-windows.patch
        Patch could not be applied with `patch`. Continuing without patching.
17:51:46 ├ Running cmake...
17:51:58 ├ Running build...
17:52:07 ├ Running install...
17:52:08 ├ /local32/lib/libopenal.a  ............................................ [Not found]
17:52:08 └ openal-soft-git  ........................................................ [Failed]
```

**Comment by pat357** [comment]
I've created a new patch that should replace the 3 patches for Openal.
Just remove the .txt extension, so the resulting file is named **patch_openal.diff**.

Patching can be done as follows:
```
patch -N -p1 -i patch_openal.diff
```

[patch_openal.diff.txt](https://github.com/m-ab-s/media-autobuild_suite/files/4777022/patch_openal.diff.txt)

**Comment by LigH-de** [comment]
Patch may be obsolete now. Built without applying.
