### ISSUE TITLE
[mingw64] [gpac] [clang] Build error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1713]
Likely error (tail of the failed operation logfile):
D:/ffmpeg-autobuild-clang/build/gpac-git/src/utils/os_net.c:956:9: error: use of undeclared identifier 'EPROTOTYPE'
                        case EPROTOTYPE:
                             ^
D:/ffmpeg-autobuild-clang/build/gpac-git/src/utils/os_net.c:959:9: error: use of undeclared identifier 'ENOBUFS'
                        case ENOBUFS:
                             ^
3 errors generated.
make[1]: *** [../config.mak:144: utils/os_net.o] Error 1
make[1]: Leaving directory '/build/gpac-git/build-64bit/src'
make: *** [Makefile:13: all] Error 2
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4784611/logs.zip)

**Comment by 1480c1** [comment]
@kliffgomel can you try using for gpac
```bash
do_patch "https://github.com/m-ab-s/media-autobuild_suite/issues/1713.patch" am
```

**Comment by kliffgomel** [comment]
> ```shell
> "https://github.com/m-ab-s/media-autobuild_suite/issues/1713.patch"
> ```

Error 406 while downloading https://github.com/m-ab-s/media-autobuild_suite/issues/1713.patch
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4944740/logs.zip)
[gpac_extra.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4944741/gpac_extra.zip)

**Comment by 1480c1** [comment]
oops, wrong link
```bash
do_patch "https://github.com/gpac/gpac/pull/1545.patch" am
```

**Comment by kliffgomel** [comment]
This patch works!

**Comment by 1480c1** [comment]
Nice, I will make sure if it works with gcc with no errors and add it to the suite
