### ISSUE TITLE
[mingw64] libidn2 2.3.0 build error

### ISSUE THREAD

**Issue by thefastman** [m-ab-s/media-autobuild_suite#1714]
17:05:14 libidn2 2.3.0  ................................. [Not installed]
17:05:14 ├ libidn2-2.3.0  ............................. [File up-to-date]
17:05:15 ├ Running extract...
17:05:25 ├ Running configure...
17:07:52 ├ Running make...
Likely error (tail of the failed operation logfile):
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make[2]: *** [Makefile:969: ../../src/Makefile.in] Error 63
make[2]: Leaving directory '/build/libidn2-2.3.0/build-64bit/src'
make[1]: *** [Makefile:1099: all-recursive] Error 1
make[1]: Leaving directory '/build/libidn2-2.3.0/build-64bit'
make: *** [Makefile:1008: all] Error 2
make failed. Check E:/media-autobuild_suite/build/libidn2-2.3.0/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
17:08:23   Creating diagnostics file...

[logs.zip](https://0x0.st/iWVy.zip)

**Comment by aduzsardi** [comment]
Just ran into the same issue , you can either patch the build scripts or the archive of the libraries.
I chose to patch the archive of **libidn2** and **libpsl**

Open the mintty terminal from `..\media-autobuild_suite-master`
Navigate to build directory , download the source code archives, patch their configure.ac , repack them and change the sha256sum in `build/media-suite_compile.sh` of these packages

```shell
Administrator@WIN-EQJIF7C1VOK /trunk
$ cd build/
$ rm -rf libidn2-2.3.0.tar.gz libidn2-2.3.0
$ rm -rf libpsl-0.21.0.tar.gz libpsl-0.21.0
$ wget https://ftp.gnu.org/gnu/libidn/libidn2-2.3.0.tar.gz
$ wget https://github.com/rockdaboot/libpsl/releases/download/libpsl-0.21.0/libpsl-0.21.0.tar.gz
$ tar xvf libidn2-2.3.0.tar.gz
$ tar xvf libpsl-0.21.0.tar.gz
$ rm libidn2-2.3.0.tar.gz libpsl-0.21.0.tar.gz
```
Run these commands in both unarchived folders **libidn2-2.3.0** , **libpsl-0.21.0**
_Not sure if all these are needed, but it fixed it for me, taken from:  https://stackoverflow.com/a/48574758/12437643_

```shell
# Fix AM_INIT_AUTOMAKE
sed -e 's/^AM_INIT_AUTOMAKE.*/AM_INIT_AUTOMAKE/g' configure.ac > configure.ac.fixed
mv configure.ac.fixed configure.ac
# Remove useless directive
sed -e '/AM_SILENT_RULES/d' configure.ac > configure.ac.fixed
mv configure.ac.fixed configure.ac
# Get rid of all docs Makefiles
sed -e '/^  doc\//d' configure.ac > configure.ac.fixed
mv configure.ac.fixed configure.ac
```

Repackage them

```shell
$ tar cvzf libidn2-2.3.0.tar.gz libidn2-2.3.0
$ tar cvzf libpsl-0.21.0.tar.gz libpsl-0.21.0
```
Generate sha256sum for the archives
```shell
$ sha256sum libidn2-2.3.0.tar.gz libpsl-0.21.0.tar.gz
```

Edit `build/media-suite_compile.sh` , look for where the packages are downloaded/compiled and replace the checksum with the ones generated above

Run the batch script (media-autobuild_suite.bat) again

**Comment by 1480c1** [comment]
It doesn't seem like I can reproduce this

**Comment by megapro17** [comment]
> It doesn't seem like I can reproduce this

delete build/libidn2-2.3.0 folder first

**Comment by 1480c1** [comment]
> > It doesn't seem like I can reproduce this
> 
> delete build/libidn2-2.3.0 folder first

that's what I did.

**Comment by thaischumi** [comment]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4807569/logs.zip)

same here

**Comment by aduzsardi** [comment]
if i run configure && make outside of the media-autobuild , for example from the mintty shell , i don't have any issues and the autotools (autoconf,automake) are not triggered

is it possible that some file timestamps are messed up in media-autobuild environment which forces the autoconf/automake to run ?

**Comment by megapro17** [comment]
libpsl also affected
