### ISSUE TITLE
GPAC/MP4Box build error

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1716]
┌ gpac git  ........................................... [Recently updated]
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
   52 | typedef int ssize_t;
      |             ^~~~~~~
D:/mabs/build/gpac-git/src/quickjs/quickjs.c: In function 'js_random_init':
D:/mabs/build/gpac-git/src/quickjs/quickjs.c:40431:5: warning: implicit declaration of function 'gettimeofday'; did you mean 'mingw_gettimeofday'? [-Wimplicit-function-declaration]
40431 |     gettimeofday(&tv, NULL);
      |     ^~~~~~~~~~~~
      |     mingw_gettimeofday
make[1]: *** [../config.mak:143: quickjs/quickjs.o] Error 1
make[1]: Leaving directory '/build/gpac-git/build-32bit/src'
make: *** [Makefile:13: all] Error 2
make failed. Check D:/mabs/build/gpac-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iWW-.zip

**Comment by 1480c1** [comment]
Seems that this might be because of upstream unnecessarily typedefing `ssize_t`

```c
#if defined(_WIN32)
#define __exception /* */
typedef int64_t ssize_t;
#else
#define __exception __attribute__((warn_unused_result))
#endif

```

**Comment by aureliendavid** [comment]
upstream should be fixed now, thanks

**Comment by Barough** [comment]
Fixed. Thnx

**Comment by wiiaboo** [comment]
@aureliendavid might be an old MinGW in ubuntu 18.04.

**Comment by 1480c1** [comment]
> mbas

just realized, lol
