### ISSUE TITLE
vmaf-git won't build

### ISSUE THREAD

**Issue by haquacoustic** [m-ab-s/media-autobuild_suite#1722]
[logs.zip](https://0x0.st/i4Wi.zip)

**Comment by 1480c1** [comment]
https://github.com/Netflix/vmaf/pull/592#issuecomment-647349610

**Comment by 1480c1** [comment]
https://github.com/Netflix/vmaf/commit/4f5ee7815b34c78d2ece9b71583ba6e81e8932ef

**Comment by ImportTaste** [comment]
I like how they knew about the problem and merged it anyway.

**Comment by ImportTaste** [comment]
Fixed upstream.
