### ISSUE TITLE
msys64\home\%USERNAME%\.gnupg\ : path not found

### ISSUE THREAD

**Issue by martin54** [m-ab-s/media-autobuild_suite#1723]
[Line 1645 (see below) from media-autobuild_suite.bat](https://github.com/m-ab-s/media-autobuild_suite/blob/5453ca8358c0bcc717f63b60f5bb8a641a6f2254/media-autobuild_suite.bat#L1645) is causing an MSDOS error "path not found", each time when I execute media-autobuild_suite.bat:

```
E:\mingw\> media-autobuild_suite.bat
-------------------------------------------------------------------------------
update autobuild suite
-------------------------------------------------------------------------------
Error: Path not found!
```
Caused by:

`findstr hkps://keys.openpgp.org "%instdir%\msys64\home\%USERNAME%\.gnupg\gpg.conf" >nul 2>&1 || echo keyserver hkps://keys.openpgp.org >> "%instdir%\msys64\home\%USERNAME%\.gnupg\gpg.conf"
`

Reason is the part `echo ... >> "%instdir%\msys64\home\%USERNAME%\.gnupg\gpg.conf"`, as there is no folder `.gnupg`:
```
>dir "E:\mingw\msys64\home\user1\"
24.02.2020  14:57             5.828 .bashrc
24.06.2020  17:55                24 .bash_history
24.02.2020  14:57                21 .bash_logout
24.02.2020  14:57             1.256 .bash_profile
13.06.2020  00:00    <DIR>          .ccache
12.06.2020  23:47               161 .gitconfig
12.06.2020  23:47               297 .hgrc
24.02.2020  14:57             3.273 .inputrc
12.06.2020  23:47                81 .minttyrc
24.02.2020  14:57             1.575 .profile
```
Couldn't find any code, which should create that missing directory.
Except from that error message, I didn't saw negative side effects caused by the missing `gpg.conf`.
After manually creating .gnupg, the error message disappeared.

**Comment by 1480c1** [comment]
Ah, never realized that might be causing those messages.

**Comment by martin54** [comment]
PS: The error message is translated. The direct translation is "`The system cannot find the specified path.`"

**Comment by 1480c1** [comment]
added a mkdir in the latest commit, can you test after removing the .gnupg folder?

**Comment by 1480c1** [comment]
Nice, thanks for the report
