### ISSUE TITLE
Misc suite update error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1726]
Updating msys2 system and installed packages...
-------------------------------------------------------------------------------
error: no targets specified (use -h for help)
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing pacman (5.2.1-12) breaks dependency 'pacman-contrib' required by base
-------------------------------------------------------------------------------
Updates finished.

[update.log](https://github.com/m-ab-s/media-autobuild_suite/files/4849975/update.log)

**Comment by 1480c1** [comment]
as far as I remember, easiest way to solve this was to remove msys2 and rerun,

an alternative might be to remove `base` from `msyspackages` in the bat file, run mintty and run `pacman -R base` and try again
