### ISSUE TITLE
[mingw64] [libplacebo] implicit declaration of function of ffs

### ISSUE THREAD

**Issue by Asphxiated** [m-ab-s/media-autobuild_suite#1728]
I have tried many different compilation options and I don't even have 'libplacebo' enabled for mpv or FFmpeg (I assume this is only for mpv as FFmpeg does build. I also just had libplacebo-git compile on my laptop about 4 days ago without issue but there seems to be some update because if I copy over the build directory from the computer where it did compile it still failed on my desktop because it replaces the 'old source' with 'updated one' that fails. It is an older AMD FX-8350 based machine but I have compiled all of these packages myself on Gentoo Linux many times on this machine so it has to either be the updated git repo breaking this or there could be an issue with Windows 10 on my machine but everything else seems to compile just fine (besides libsrt which I know its not a bug in this suite but an upstream issue so I am kind of leaning that way here. )

If you have any ideas that could help beyond waiting for libplacebo to get updated again please let me know. No matter what options I choose I always get libplacebo installed even though its always #'d out in the mpv_options.txt so I don't get why the suite is installing it.

``` ┌ libplacebo git  ..................................... [Recently updated]
├ Installing python-mako... done
├ Running meson...
├ Running build...
Likely error (tail of the failed operation logfile):
../src/vulkan/malloc.c: In function 'vk_malloc_import':
../src/vulkan/malloc.c:760:26: error: implicit declaration of function 'ffs' [-Werror=implicit-function-declaration]
  760 |     int first_mem_type = ffs(reqs.memoryTypeBits);
      |                          ^~~
../src/vulkan/malloc.c:818:9: error: implicit declaration of function 'close'; did you mean 'fclose'? [-Werror=implicit-function-declaration]
  818 |         close(fdinfo.fd);
      |         ^~~~~
      |         fclose
cc1.exe: some warnings being treated as errors
ninja: build stopped: subcommand failed.
build failed. Check C:/mabs/media-autobuild_suite-master/build/libplacebo-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iJDb.zip
Copy and paste [logs.zip](https://0x0.st/iJDb.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

[logs.zip](https://0x0.st/iJDb.zip)

**Comment by 1480c1** [comment]
For disabling libplacebo
```bash
! mpv_disabled libplacebo
```
you have to have explicitly disable libplacebo, not an enable.

for the actual issue itself, it seems that the idefs got moved around in the source file and @haasn forgot to move the conditional of Unix around the ffs function https://github.com/haasn/libplacebo/commit/1d0f4380ef3bf6a48a7f0fc2964534e7b9b104ec#diff-e15a1c4498d0bf72cdbb82822c9f2ab6L644

for a fix, it might be as easy as adding
```diff
diff --git a/src/vulkan/malloc.c b/src/vulkan/malloc.c
index bfb5ce2..a2c007c 100644
--- a/src/vulkan/malloc.c
+++ b/src/vulkan/malloc.c
@@ -773,7 +773,11 @@ bool vk_malloc_import(struct vk_malloc *ma, VkMemoryRequirements reqs,
 
     // We pick the first compatible memory type because we have no other basis
     // for choosing if there is more than one available.
+#ifdef VK_HAVE_UNIX
     int first_mem_type = ffs(reqs.memoryTypeBits);
+#else
+    int first_mem_type = 0;
+#endif
     if (!first_mem_type) {
         PL_ERR(vk, "No compatible memory types offered for imported memory");
         return false;
```
but, since I don't actually know/understand the code, I wouldn't change it or patch it rn.

**Comment by Asphxiated** [comment]
thanks, I got it to build by explicitly disabling Vulkan and libplacebo in MPV, Vulkan still compiles into FFMpeg just fine at the moment. Just wanted to let you know it worked so if you need this right now just disable Vulkan and libplacebo for full FFMpeg and MPV compilation in auto-build suite.

**Comment by 1480c1** [comment]
Seems he already fixed it.

**Comment by Asphxiated** [comment]
odd, I can try to rebuild fresh to see if it works now but I had just tried about an hour before my last post and still got the same issue with vulkan/libplacebo enabled for the auto-build

**Comment by 1480c1** [comment]
well, if it's still broken it would be best to report it so we know if the fix does not actually fix it.

**Comment by Asphxiated** [comment]
Well, I want to make sure that it was grabbing the new commit, I didn't remove the previous libplacebo source package so I am not sure. I will definitely run it again in a few hours after this encode finishes. Now that I know I can definitely get it running on this computer I can be more confident about playing with the options and how the auto-build suite works. I have only cross-compiled stuff a few times before (I know this isn't really a cross-compile but its the best relationship I can think of) so I wasn't exactly sure how to control the auto-build options. Thanks for the quick reply.
