### ISSUE TITLE
[mingw64] [faac] /local64/bin-audio/faac.exe not found

### ISSUE THREAD

**Issue by dsent** [m-ab-s/media-autobuild_suite#1736]
``` bash
  Running git update for faac...
┌ faac git  ........................................... [Recently updated]
├ Running uninstall...
├ Running bootstrap...
├ Running configure...
├ Running make...
├ Running install...
├ /local64/bin-audio/faac.exe  ............................... [Not found]
└ faac-git  ..................................................... [Failed]

Try deleting '/build/faac-git' and start the script again.
If you are sure there are no dependencies, <Enter> to continue building.
Close this window if you wish to stop building.
```

Searching for faac reveals it's getting installed into `/msys64/mingw64/bin/faac.exe`, but not into `/local64/bin-audio/faac.exe`

[logs.zip](https://0x0.st/iyOr.zip)

**Comment by 1480c1** [comment]
wrong log

**Comment by dsent** [comment]
I just hit Enter after this and continued installation; should I close the window and collect logs manually somehow at the point of seeing this?

**Comment by 1480c1** [comment]
Try looking for log files under build/faac-git

**Comment by 1480c1** [comment]
Including ones under the build-*bits folder under faac-git

**Comment by dsent** [comment]
[faac-git.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4880027/faac-git.zip)

**Comment by dsent** [comment]
Sorry for not copying the directory structure, is this okay?

**Comment by 1480c1** [comment]
fine enough with me.

can you make sure your suite is updated? I believe this was fixed a bit ago

**Comment by dsent** [comment]
I installed and first ran it yesterday.

**Comment by dsent** [comment]
Should I run update_suite.sh?

**Comment by 1480c1** [comment]
can you try looking for a file called `update_suite.sh` and drag and drop it onto the mintty shortcut?

**Comment by dsent** [comment]
The result is (up to date):
![image](https://user-images.githubusercontent.com/8774536/86615903-c733b400-bfbd-11ea-8226-d3945be038d5.png)

**Comment by dsent** [comment]
Should I now try to repeat the build process?

**Comment by 1480c1** [comment]
Yeah

**Comment by dsent** [comment]
Ok, will do a little bit later and post faac logs.

**Comment by dsent** [comment]
No error after updating the suite. Not sure why this was the case (as I downloaded the suite yesterday), but now it works. Sorry for the false alarm.
