### ISSUE TITLE
Request: Implement Compilation of the VTM VCC En-/Decoder

### ISSUE THREAD

**Issue by Felixkruemel** [m-ab-s/media-autobuild_suite#1739]
As the VCC / H266 Standard is now completed, I would be happy if the autobuild suite could also automatically build the reference decoder and encoder for it.

Here's a Gitlab link to it:
https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM
And the description:
https://jvet.hhi.fraunhofer.de/

And it would be nice if MPV could be compiled with it, but I don't think that's possible (yet).

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L1774
