### ISSUE TITLE
Compiling error with dssim

### ISSUE THREAD

**Issue by Patman86** [m-ab-s/media-autobuild_suite#1743]
Hi,

An error occurs during compilation, see linked file:

[https://0x0.st/itsz.zip](https://0x0.st/itsz.zip)

**Comment by 1480c1** [comment]
Possible issue with https://github.com/kornelski/dssim/commit/1870591d07366934485ba57490f398e50e450472, but I was able to successfully compile with https://github.com/kornelski/dssim/commit/389e1051c20144c1645785b3c00efb9794d6e546 with both gcc and clang just now

**Comment by LigH-de** [comment]
Same here. I'll quote the errors here so their text can be found when searching:

```
   Compiling dssim v2.11.0 (E:\MABS\build\dssim-git)
warning: use of deprecated item 'imgref::Img::buf': Don't access struct fields directly. Use buf(), buf_mut() or into_buf()
   --> src\blur.rs:131:20
    |
131 |         let src = &src.buf[..];
    |                    ^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'imgref::Img::buf': Don't access struct fields directly. Use buf(), buf_mut() or into_buf()
   --> src\blur.rs:132:24
    |
132 |         let dst = &mut dst.buf[..];
    |                        ^^^^^^^

warning: use of deprecated item 'imgref::Img::buf': Don't access struct fields directly. Use buf(), buf_mut() or into_buf()
   --> src\blur.rs:158:37
    |
158 |             do_blur(srcdst.new_buf(&srcdst.buf[..]), tmp_dst);
    |                                     ^^^^^^^^^^

warning: variable does not need to be mutable
   --> src\blur.rs:143:17
    |
143 |             let mut dstrow = &mut dst[y*dst_stride..y*dst_stride+width];
    |                 ----^^^^^^
    |                 |
    |                 help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: 4 warnings emitted

error[E0277]: `?` couldn't convert the error to `lodepng::ffi::Error`
  --> src/main.rs:46:59
   |
46 |     let img = load_image::load_image(path.as_ref(), false)?;
   |                                                           ^ the trait `std::convert::From<lodepng::error::Error>` is not implemented for `lodepng::ffi::Error`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following implementations were found:
             <lodepng::ffi::Error as std::convert::From<std::io::Error>>
   = note: required by `std::convert::From::from`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `dssim`.

To learn more, run the command again with --verbose.
```

**Comment by Patman86** [comment]
I tested the compilation directly from the dssim folder and received an error message when compiling "mozjpeg-sys". Maybe that's the reason ...

**Comment by 1480c1** [comment]
With clang or gcc?

**Comment by Patman86** [comment]
With gcc 9.3.1 and gcc 10.1.0, i opened a ticket at dssim

**Comment by 1480c1** [comment]
@Patman86 can you reconfirm you still have errors when compiling mozjpeg-sys? I am not able to reproduce your error for mozjpeg-sys at least.

For the other one I can, and I will open an issue about it.

**Comment by LigH-de** [comment]
No obvious relation to mozjpeg-sys for me. The error at the question mark persists.

**Comment by Patman86** [comment]
I tested the compilation directly from the dssim folder again with gcc and procedure returns 3 error messages:

```
- error: linking with `gcc` failed: exit code: 1
- error: aborting due to previous error
- error: could not compile mozjpeg-sys
```
I think the linking error is the main reason.

**Comment by 1480c1** [comment]
@LigH-de it seems he solved the issue for the question mark part https://github.com/kornelski/dssim/issues/73

@Patman86 maybe we might need to do something similar to what we did with rav1e with
```bash
        old_cpath=$CPATH
        old_libpath=$LIBRARY_PATH
        CPATH=$(cygpath -m "$LOCALDESTDIR/include" "$MINGW_PREFIX/include" "$MINGW_PREFIX/$MINGW_CHOST/include" | tr '\n' ' ')
        LIBRARY_PATH=$(cygpath -m "$LOCALDESTDIR/lib" "$MINGW_PREFIX/lib" "$MINGW_PREFIX/$MINGW_CHOST/lib" | tr '\n' ' ')
        export CPATH LIBRARY_PATH
...
```
to make it use the libs from msys2's mingw-w64 instead of trying to use their own packaged one.

**Comment by Patman86** [comment]
Let's give it a try...

**Comment by Asphxiated** [comment]
I am still having the same issue, I was attempting to recompile to confirm that libplacebo could be compiled on my system but I get the same issue with dssim, can it be compiled without dssim? FFmpeg that is? Here are my logs [logs.zip](https://0x0.st/ivAs.zip)

**Comment by Asphxiated** [comment]
Thought it might be because I didn't sync the new updates to the script but still get the ssim problem. Logs =  [logs.zip](https://0x0.st/ivAf.zip) am skipping and seeing if FFmpeg will compile without dssim, I assume it will but many encoders may not have the ssim functions?

**Comment by 1480c1** [comment]
seems to be a new issue on dssim's side

**Comment by 1480c1** [comment]
you need to disable dssim inside the ini file

**Comment by Asphxiated** [comment]
> you need to disable dssim inside the ini file

Yeah I got that but I am just wondering what functions of FFmpeg/x264/x265 will be impacted without dssim inclusion.

**Comment by 1480c1** [comment]
none, dssim is only compiled for the dssim.exe as of right now
```bash
do_install "target/$CARCH-pc-windows-gnu/release/dssim.exe" bin-global/
```

**Comment by Asphxiated** [comment]
oh ok, good to know, I wasn't sure if you chose to not compile the individual binaries as to whether their libraries would be available to other programs or not but I am also guessing that FFmpeg does not rely on dssim for its SSIM measurements. This is just an assumption but a project as big as FFmpeg would likely have their own in the source tarball.

**Comment by 1480c1** [comment]
@Patman86 any updates? if you don't know how to do the changes, I can try providing a patch

**Comment by Patman86** [comment]
@1480c1 i updated m-ab-s and only changed the following line
[media-suite_compile.sh#L213](https://github.com/m-ab-s/media-autobuild_suite/blob/6600388568a6a84ecc7111d96d331eaa01c6e672/build/media-suite_compile.sh#L213)
`CFLAGS+=" -fno-PIC" do_rust`

to

`CFLAGS+=" -fno-PIC"`
`do_rust`

I think the update fixed the problem. Thank for your efforts!
