### ISSUE TITLE
AOM Compiling error

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1744]
┌ aom git  ............................................ [Recently updated]
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/bin/ld.exe: libaom.a(encoder.c.o):encoder.c:(.text+0x8a6c): undefined reference to `av1_select_sb_size'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/20] Updating version info if necessary.
[2/20] Linking CXX executable lightfield_bitstream_parsing.exe
FAILED: lightfield_bitstream_parsing.exe
cmd.exe /C "cd . && D:\mabs\msys64\mingw32\bin\ccache.exe  g++ -mthreads -mtune=generic -O2 -pipe -O3 -DNDEBUG -D_WIN32_WINNT=0x0601 -std=c++11 -Wall -Wdisabled-optimization -Wextra -Wfloat-conversion -Wimplicit-function-declaration -Wlogical-op -Wpointer-arith -Wsign-compare -Wtype-limits -Wuninitialized -Wunused -Wvla -Wstack-usage=240000 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -pipe -static-libgcc -static-libstdc++ CMakeFiles/aom_common_app_util.dir/common/args.c.o CMakeFiles/aom_common_app_util.dir/common/av1_config.c.o CMakeFiles/aom_common_app_util.dir/common/md5_utils.c.o CMakeFiles/aom_common_app_util.dir/common/tools_common.c.o CMakeFiles/aom_common_app_util.dir/common/rawenc.c.o CMakeFiles/aom_common_app_util.dir/common/y4menc.c.o CMakeFiles/aom_encoder_app_util.dir/common/ivfenc.c.o CMakeFiles/aom_encoder_app_util.dir/common/video_writer.c.o CMakeFiles/aom_encoder_app_util.dir/common/warnings.c.o CMakeFiles/aom_encoder_app_util.dir/common/y4minput.c.o CMakeFiles/aom_encoder_app_util.dir/examples/encoder_util.c.o CMakeFiles/aom_encoder_app_util.dir/common/webmenc.cc.o CMakeFiles/aom_decoder_app_util.dir/common/ivfdec.c.o CMakeFiles/aom_decoder_app_util.dir/common/obudec.c.o CMakeFiles/aom_decoder_app_util.dir/common/video_reader.c.o CMakeFiles/aom_decoder_app_util.dir/common/webmdec.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/cpu_id.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/planar_functions.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/row_any.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/row_common.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/row_gcc.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/row_mips.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/row_neon.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/row_neon64.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/row_win.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/scale.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/scale_any.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/scale_common.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/scale_gcc.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/scale_mips.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/scale_neon.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/scale_neon64.cc.o CMakeFiles/yuv.dir/third_party/libyuv/source/scale_win.cc.o CMakeFiles/webm.dir/third_party/libwebm/common/hdr_util.cc.o CMakeFiles/webm.dir/third_party/libwebm/mkvmuxer/mkvmuxer.cc.o CMakeFiles/webm.dir/third_party/libwebm/mkvmuxer/mkvmuxerutil.cc.o CMakeFiles/webm.dir/third_party/libwebm/mkvmuxer/mkvwriter.cc.o CMakeFiles/webm.dir/third_party/libwebm/mkvparser/mkvparser.cc.o CMakeFiles/webm.dir/third_party/libwebm/mkvparser/mkvreader.cc.o CMakeFiles/lightfield_bitstream_parsing.dir/examples/lightfield_bitstream_parsing.c.o  -o lightfield_bitstream_parsing.exe -Wl,--major-image-version,0,--minor-image-version,0  libaom.a  -lm  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/bin/ld.exe: libaom.a(encoder.c.o):encoder.c:(.text+0x8a6c): undefined reference to `av1_select_sb_size'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check D:/mabs/build/aom-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/itsg.zip
Copy and paste [logs.zip](https://0x0.st/itsg.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
https://bugs.chromium.org/p/aomedia/issues/detail?id=2750

**Comment by Barough** [comment]
Okey. Just a matter of waiting for them to fix it upstream then.

**Comment by 1480c1** [comment]
Fixed upstream, comment if it's still broken
