### ISSUE TITLE
(cosmetics) Batch ANSI colors unreliable

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1746]
When I install MABS from scratch, the color in the batch console window changes back from your custom "black on grey" to the default "grey on black" during the configuration. In my last run, it happened while selecting the ffmpeg license, the second step.

Some time later, while installing the MSYS2 base package, the background returns to grey, but the text still is grey-on-black and overwrites the grey background again.

Furthermore, the font gets reset to a basic bitmap font. The suite seems to dislike my default customization using Consolas 16. Which TrueType fonts are acceptable?

**Comment by 1480c1** [comment]
are you using noMintty?

**Comment by LigH-de** [comment]
No - mintty is used for the *.sh scripts, but not for the starting *.bat which runs in cmd.

**Comment by 1480c1** [comment]
noMintty (the variable set by the option asking `Are you running this script through ssh or similar?`) is used to determine if any bash commands should be run through mintty instead of directly through bash. The main reason why I ask is that I have experienced the colors "resetting" to back background with default white foreground with noMintty set to `y` during the first time setup and during compilation etc

**Comment by LigH-de** [comment]
No, I am sure I have it on 2 in all my installations. And this color change is an older issue, reporting it rather late...

**Comment by 1480c1** [comment]
Hmm, interesting, I'm not sure what would cause that.

Could you try removing the `@echo off` line from the top of the bat file and try to see at what command does it run when the color starts to change?

**Comment by LigH-de** [comment]
I guess it happened due to fixing the font. Closing until I find any other reason I can reproduce...

**Comment by LigH-de** [comment]
I dot another case today, and I believe it is directly related to the selected font and window dimensions, so it **won't fix** ...

When the output reaches the bottom of the screen, the background gets reset to black in my case on one PC, but not with slightly different options on another.

![MABS_cfg1](https://user-images.githubusercontent.com/5917225/87756149-a6aef980-c808-11ea-9c0f-2c7d9728aa45.png)
![MABS_cfg2](https://user-images.githubusercontent.com/5917225/87756162-ad3d7100-c808-11ea-89a6-d6e9d90c86d1.png)

When I comment out the `@ech off` in the beginning, there is so much output that the location in question is long gone before requesting the first input:

![MABS_echo](https://user-images.githubusercontent.com/5917225/87756232-d0682080-c808-11ea-99d3-ff69463cc07d.png)

I will keep this one closed and ignore it, as I see it only in this specific console setup.
