### ISSUE TITLE
[mingw32|mingw64] [repo] mpv git

### ISSUE THREAD

**Issue by masterkivat** [m-ab-s/media-autobuild_suite#1749]
06:05:37 ┌ mpv git  ..................................... [Updates found]
06:05:37 ├ Running bootstrap...
06:05:38 ├ Running configure...
06:05:51 ├ Running build...
Likely error (tail of the failed operation logfile):
S:/media-autobuild_suite-master/local64/lib\libass.a(ass_shaper.o):ass_shaper.c:(.text+0x19fb): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_fribidi_join_arabic'
S:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: S:/media-autobuild_suite-master/local64/lib\libass.a(ass_shaper.o):ass_shaper.c:(.text+0x1a19): undefined reference to `__imp_fribidi_shape'
S:/media-autobuild_suite-master/local64/lib\libass.a(ass_shaper.o):ass_shaper.c:(.text+0x1a19): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_fribidi_shape'
S:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: S:/media-autobuild_suite-master/local64/lib\libass.a(ass_shaper.o):ass_shaper.c:(.text+0x1d22): undefined reference to `__imp_fribidi_reorder_line'
S:/media-autobuild_suite-master/local64/lib\libass.a(ass_shaper.o):ass_shaper.c:(.text+0x1d22): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_fribidi_reorder_line'
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)

[iteE.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4906528/iteE.zip)

**Comment by 1480c1** [comment]
can you try deleting `build/libass-git` and `build/fribidi-git` and rerun?

**Comment by masterkivat** [comment]
I think I got the same error...

20:24:05 ┌ mpv git  ..................................... [Updates found]
20:24:05 ├ Running bootstrap...
20:24:07 ├ Running configure...
20:24:18 ├ Running build...
Likely error (tail of the failed operation logfile):
S:/media-autobuild_suite-master/local64/lib\libass.a(ass_shaper.o):ass_shaper.c:(.text+0x19fb): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_fribidi_join_arabic'
S:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: S:/media-autobuild_suite-master/local64/lib\libass.a(ass_shaper.o):ass_shaper.c:(.text+0x1a19): undefined reference to `__imp_fribidi_shape'
S:/media-autobuild_suite-master/local64/lib\libass.a(ass_shaper.o):ass_shaper.c:(.text+0x1a19): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_fribidi_shape'
S:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: S:/media-autobuild_suite-master/local64/lib\libass.a(ass_shaper.o):ass_shaper.c:(.text+0x1d22): undefined reference to `__imp_fribidi_reorder_line'
S:/media-autobuild_suite-master/local64/lib\libass.a(ass_shaper.o):ass_shaper.c:(.text+0x1d22): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_fribidi_reorder_line'
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)


[itW9.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4907756/itW9.zip)

**Comment by 1480c1** [comment]
Can you make sure to pull the latest suite and rerun after deleting the same folders?

line 278 of media-suite_compile.sh should not have `tag=LATEST` in it https://github.com/m-ab-s/media-autobuild_suite/commit/819e75ce4254a6841b33f70f1473826d6f8c5984

**Comment by masterkivat** [comment]
I think by doing that the error disappeared, wow...
Thanks for that :)
