### ISSUE TITLE
Request: [x264 custom patches]

### ISSUE THREAD

**Issue by masterkivat** [m-ab-s/media-autobuild_suite#1750]
Hi.
I'm wondering if it's possible to build x264 on MABS with custom patches like the following ones:
- [fadecomp.diff](https://github.com/DJATOM/x264-aMod-patches/blob/master/09-fadecomp.diff) (fade compensate, isolated)
- [x264_YMod.patch](https://github.com/bubonic/x264_YMod_ffmpeg4.patch/blob/5a2b49cfa4def3d071bc794fec93bd42378020af/x264_YMod.patch) (fade compensate + film grain optimization, merged)
I don't have enough "knowledge"/skill to make custom builds myself but as a encoder it would be interesting having both _fade-compensate_ and _film grain optimization_ patches available as optional.
Thanks in advance 👍

**Comment by 1480c1** [comment]
for the x264 patch (fadecom), you might want to suggest to the original author to use git format-patch and try to upstream it to x264 if it's worth it https://code.videolan.org/videolan/x264/ plus, at least getting it reviewed would be good.

for the ffmpeg's libx264.c patch (x264_YMod), that one might have a harder time since I know trying to submit a patch to the FFmpeg mailing list is probably not the easiest thing in the world to do, not the hardest way to submit a patch, but definitely not easy.
either way, you might want to suggest them to try to upstream their patches or at least have them reviewed so they don't have any unwanted bugs.

for using those patches inside mabs, you would want to look at the custom patches section https://github.com/m-ab-s/media-autobuild_suite#custom-patches
 
an example would be inside `build/x264_extra.sh
```bash
#!/bin/bash

_pre_configure(){
    do_patch "https://raw.githubusercontent.com/DJATOM/x264-aMod-patches/master/09-fadecomp.diff"
}
```
and inside `build/ffmpeg_extra.sh`
```bash
#!/bin/bash
_pre_configure(){
    do_patch "https://raw.githubusercontent.com/bubonic/x264_YMod_ffmpeg4.patch/master/x264_YMod.patch"
}

**Comment by wiiaboo** [comment]
The fadecomp one at least is a decades old patch. If it hasn't been
upstreamed so far, it won't ever be. Especially considering how dead x264
dev is.

I'd say use the custom patches existing functionality and maintain it at
your own risk.

**Comment by masterkivat** [comment]
Well... I tried...
1) x264_extra.sh

00:26:17   Running git clone for x264...
00:26:24 ├ Found x264_extra.sh. Sourcing script...
00:26:24 ┌ x264 git  ................................. [Recently updated]
00:26:27   Running git update for ffmpeg...
00:26:29 ffmpeg git  ....................................... [Up-to-date]
00:26:29 ├ Running uninstall...
00:26:30 ├ Running configure...
00:27:27 ├ Running install...
00:28:35   Running git update for ffms2...
00:28:36 ┌ ffms2 git  ................................... [Updates found]
00:28:36 ├ Running autoreconf...
00:28:58 ├ Running configure...
00:29:16 ├ Running make...
00:29:21 ├ Running install...
00:29:22 ├ Stripping...
00:29:22 └ ffms2-git  ......................................... [Updated]
00:29:23   Running git update for liblsmash...
00:29:24 ┌ liblsmash git  ............................... [Files missing]
00:29:24 ├ Running configure...
00:29:26 ├ Running make...
00:29:30 └ liblsmash-git  ..................................... [Updated]
00:29:30 ├ Running uninstall...
00:29:30 ├ Found x264_extra.sh. Sourcing script...
00:29:30 ├ Running pre configure from x264_extra.sh...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
_pre_configure
09-fadecomp.diff
        Patch could not be applied with `patch`. Continuing without patching.
pre_configure failed. Check S:/media-autobuild_suite-master/build/x264-git/ab-suite.pre_configure.log
This is required for other packages, so this script will exit.

[ivm_.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4929152/ivm_.zip)

2) ffmpeg_extra.sh

00:49:11   Running git clone for x264...
00:49:20 ┌ x264 git  ................................. [Recently updated]
00:49:20   Running git clone for ffmpeg...
00:50:17 ├ Found ffmpeg_extra.sh. Sourcing script...
00:50:17 ┌ ffmpeg git  ............................... [Recently updated]
00:50:17 ├ Running uninstall...
00:50:17 ├ Running pre configure from ffmpeg_extra.sh...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/mingw32/lib
_pre_configure
x264_YMod.patch
        Patch could not be applied with `patch`. Continuing without patching.
pre_configure failed. Check S:/media-autobuild_suite-master/build/ffmpeg-git/ab-suite.pre_configure.log
This is required for other packages, so this script will exit.

[ivmw.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4929197/ivmw.zip)

Guess I'll have to learn myself how to compile it with custom patches because like I said, I don't have "knowledge"/skills for this xD

**Comment by 1480c1** [comment]
seems that those two patches no longer work.

**Comment by 1480c1** [comment]
can't help you any further with that, you will need to contact the original author to see if he can redo it, or try redoing it yourself.

**Comment by masterkivat** [comment]
> 
> 
> can't help you any further with that, you will need to contact the original author to see if he can redo it, or try redoing it yourself.

I'll see what I can do to make it myself but don't worry, thanks for the help anyways :)
Apparently this [jpsdr](https://github.com/jpsdr/x264) guy creates his own x264 build with both patches but he seems too busy these days to update his own build, that's why I think that it would be interesting have only both patches as optional on MABS, there's not too many custom patches around for x264 but both _fade-compensate_ and _film grain optimization_. 
If you wanna close this topic I don't mind. Again, thanks for the support and keep up the good work on MABS, it's a wonderful tool for people like me that doesn't have much "knowledge"/experience building tools 👍
