### ISSUE TITLE
pacman : updating packages is extremely SLOOOW ! 

### ISSUE THREAD

**Issue by pat357** [m-ab-s/media-autobuild_suite#1751]
Updating the packages (using pacman) goes extremely slow !
I'm talking about download speed of < 50 KiB .... and the update takes **3-4 hours** if there are some big files to download.

There seem to be mirrors available in **/etc/pacman.d/mirrorlist.mingw64** for the 64 bit packages and there are mirrors for MINGW32 and MSYS packages too.
My question is how do you select a different mirror instead of the default **http://repo.msys2.org** ?
Is it possible to configure the system in such way that it uses a different/faster mirror ?

**Comment by 1480c1** [comment]
I think you can try moving around the mirrors in the mirrorlist to see if you get any speedups

**Comment by LigH-de** [comment]
Mirrors are tried in the listed order. I reordered them once when msys2.org was unavailable; futureware.at was suggested to be usually fast and up to date.

**Comment by pat357** [comment]
Thanks both of you for this info. I really appreciate this.
Do you know if the order change has to be done before the suite starts downloading or can it be done "on the fly" (=while downloading) ?
How can I safely abort/stop a slow download session  ?

**Comment by 1480c1** [comment]
I'm not aware if pacman can do any changes for repositories "on the fly", so it will need to be done before

although I'm not sure if it's really safe, I usually just sigint it and control c

**Comment by pat357** [comment]
Just some very positive feedback:  putting "**futureware.at**" at the top in all 3 files bumped my download speed to 10MiB/s !
The 500 MB from the 1000 MB I had left to download after letting it downloading for a whole night from the official repo, was done in minutes !
There were 2 files that gave a 404 error (file not available),  but these were downloaded from the next mirror in the list I guess.
(The reason for this big download was mostly due the update from clang - LLVM (32+64bit).  )

Thanks again to both of you !

**Comment by pat357** [comment]
Just some very positive feedback:  putting "futureware.at" at the top in all 3 files bumped my download speed to 10MiB/s !
The 500 MB from the 1000 MB I had left to download after letting it downloading for a whole night from the official repo, was done in minutes !
There were 2 files that gave a 404 error (file not available),  but these were downloaded from the next mirror in the list I guess.
(The reason for this big download was mostly due the update from clang - LLVM (32+64bit).  )

Thanks again to both of you !
