### ISSUE TITLE
[mingw64] [repo] Failure to compile cargo-c, seems to be a problem with configure as it fails so early

### ISSUE THREAD

**Issue by Asphxiated** [m-ab-s/media-autobuild_suite#1752]
Started to completely rebuild all packages and first found a problem with dssim that has already been reported, so I skipped dssim and was getting pretty far until I get the issue with cargo-c. I will attempt to find out if something is pulling this in or if it is a general dependency. If I can disable it I will and go from there but there is something up with cargo-c now too...

```         Starting 64bit compilation of video tools
librtmp git  ............................................. [Already built]
vpx git  ................................................. [Already built]
vmaf git  ................................................ [Already built]
aom git  ................................................. [Already built]
dav1d git  ............................................... [Already built]
  Running git update for cargo-c...
┌ cargo-c git  ........................................ [Recently updated]
├ Running uninstall.cargo-c...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
cargo uninstall -q cargo-c
error: package ID specification `cargo-c` matched no packages
uninstall.cargo-c failed. Check C:/mabs/build/cargo-c-git/ab-suite.uninstall.cargo-c.log
This is required for other packages, so this script will exit.

```

[logs.zip](https://0x0.st/ivmV.zip)

**Comment by Asphxiated** [comment]
or rather it seems like it is trying to uninstall cargo-c even though this is a complete rebuild where it was never build before. I don't know why. Here is the logs =  [logs.zip](https://0x0.st/ivmY.zip)

**Comment by Asphxiated** [comment]
why closed?

**Comment by 1480c1** [comment]
pull new changes. it shows it was closed due to a commit

**Comment by Asphxiated** [comment]
oh i see you just updated the script

**Comment by Asphxiated** [comment]
did not fix the issue for me at least logs =  [logs.zip](https://0x0.st/ivml.zip)

same bash output as before

**Comment by 1480c1** [comment]
```bash
_check=(/opt/cargo/bin/cargo-c{build,api}.exe)
if enabled librav1e &&
    do_vcs "https://github.com/lu-zero/cargo-c.git"; then
    # Delete any old cargo-cbuilds
    log uninstall.cargo-c cargo uninstall -q cargo-c
    do_rustinstall
    do_checkIfExist
fi
```
does not seem like you have updated the scripts

**Comment by Asphxiated** [comment]
nevermind, made a mistake in what file I pulled, don't have this set up to just do a git pull sorry, my bad
