### ISSUE TITLE
Big unified solution

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1756]
All module patch place source code patch directory.
Create zmas.cmd file:
[zmas.txt](https://github.com/m-ab-s/media-autobuild_suite/files/4935793/zmas.txt)

download, change ext name .cmd.
Double-click zmas.cmd to start compilation

![无标题](https://user-images.githubusercontent.com/11304997/87749806-403bd280-c82c-11ea-8ff2-7a501be4b2c6.png)

**Comment by dbyoung720** [comment]
Every time you recompile, an error will occur.
Delete the wrong module and compile again to succeed.

Hope this question can be corrected.

**Comment by 1480c1** [comment]
I'm not sure I understand if there is any question here, nor what exactly is being discussed

**Comment by dbyoung720** [comment]
For example, compiling qtquickcontrols2-git will fail,

Delete the source code, compile again, and you will succeed.
