### ISSUE TITLE
build stopped every time at fribidi git 

### ISSUE THREAD

**Issue by j-mas** [m-ab-s/media-autobuild_suite#1759]
23:05:33 ┌ fribidi git  .............................. [Recently updated]
23:05:34 ├ Running meson...
23:05:36 ├ Running build...
Likely error (tail of the failed operation logfile):
gcc.exe: fatal error: no input files
compilation terminated.
ninja: build stopped: subcommand failed.
[1/58] Compiling C object gen.tab/1a55e88@@gen-unicode-version@exe/gen-unicode-version.c.obj
FAILED: gen.tab/1a55e88@@gen-unicode-version@exe/gen-unicode-version.c.obj
gcc.bat @gen.tab/1a55e88@@gen-unicode-version@exe/gen-unicode-version.c.obj.rsp
gcc.exe: error: gen.tab/1a55e88@@gen-unicode-version@exe/gen-unicode-version.c.obj.rsp: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
ninja: build stopped: subcommand failed.
build failed. Check C:/media-autobuild_suite-master/build/fribidi-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
23:05:37   Creating diagnostics file...
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/4944691/ab-suite.build.log)
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4944692/logs.zip)

**Comment by 1480c1** [comment]
can you try deleting `build/fribidi-git`?

**Comment by j-mas** [comment]
I've already tried this at least 10 times, also on different PCs. No success. I also tried to disable libfribidi in ffmpeg-options. Didn't help.

**Comment by LigH-de** [comment]
Similar issue here, but for me it stops during the meson sanity checks already.

I'll attach a log zip with manually added files, because build/fribidi-git/build-##bit contains files in **meson-logs** and **meson-private** which may be interesting, but the suite does not yet include these subdirectories in the log archive:

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4948387/logs.zip)

**meson-logs/meson-log.txt**
```
...
Sanity testing C compiler: gcc.bat
Is cross compiler: False.
Sanity check compiler command line: gcc.bat E:/MABS/build/fribidi-git/build-32bit/meson-private/sanitycheckc.c -o E:/MABS/build/fribidi-git/build-32bit/meson-private/sanitycheckc.exe -mthreads -mtune=generic -O2 -pipe -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1 -pipe -static-libgcc -static-libstdc++
Sanity check compile stdout:

-----
Sanity check compile stderr:
E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot open output file E:/MABS/build/fribidi-git/build-32bit/meson-private/sanitycheckc.exe: Permission denied
collect2.exe: error: ld returned 1 exit status

-----

../meson.build:1:0: ERROR: Compiler gcc.bat can not compile programs.
```

**meson-private/sanitycheckc.c**
```
int main(void) { int class=0; return class; }
```

A really simple program. But I suspect the Windows host to have locked a file in the compilation workflow just a little too long so it can't be accessed by a process in an MSYS shell.

In my case, I have ccache active, so "the compiler" is gcc.**bat**; I have such issues irregularly and for a long time already, but usually starting the suite right again solves it. For me it is a "once in a while, but over and over again" issue. But not like regularly 10 times in a row.

This one appears to be persistent now. Will check on a different PC soon...

**Comment by LigH-de** [comment]
By the way, there is a recent update of the "filesystem" package...

**Comment by 1480c1** [comment]
for the `filesystem` package, that's a new installed by default package

**Comment by LigH-de** [comment]
Another PC, and it passed...

**Comment by j-mas** [comment]
I run it at three different PC's. I have the problem at all three of them!

**Comment by kliffgomel** [comment]
I noticed a strange feature when compiling this library lately - when starting the build of the project, fribidi started updating every time, even if I start rebuilding after 20 minutes. The compilation of fribidi with me goes without errors, and the logs you submitted are really very strange. Three different computers and the same error everywhere? I constantly compile the entire project on two different computers and I never noticed such errors.
I have only one doubt - do you have antivirus installed on all your computers?

**Comment by LigH-de** [comment]
A residental antivirus may not even be the only possible reason. It could as well be any Explorer extension scanning new files for e.g. embedded content to be displayed as icon. But yes, an antivirus monitor would be the most probable reason for a temporarily locked file.

**Comment by j-mas** [comment]
Only Windows 10 defender. My last attempt 1 hour ago on a laptop with windows 10 vers. 2004 worked. So my computer at work and my main PC at home have the problem. At home I have an Intel Core i9 7940x with Windows 10 Preview build 20170.1000.
Perhaps it is a problem with the preview build. I don´t know.

**Comment by kliffgomel** [comment]
Try to completely disable windows defender, this is the most likely cause of your problems.

**Comment by kliffgomel** [comment]
And yet, very strange behavior when compiling fribidi - every time you build a project - "Updates found." I think there's a problem.

**Comment by kliffgomel** [comment]
> 
> 
> And yet, very strange behavior when compiling fribidi - every time you build a project - "Updates found." I think there's a problem.

but latest commit 15 day ago...

**Comment by 1480c1** [comment]
try merging https://github.com/m-ab-s/media-autobuild_suite/pull/1758 into your local clone

**Comment by kliffgomel** [comment]
I'm not clear on how to do this? My local copy is in sync with master

**Comment by 1480c1** [comment]
if you did a normal git clone with mabs set as origin, you can do something like
```bash
git fetch origin pull/1758/head
git checkout FETCH_HEAD
```

**Comment by kliffgomel** [comment]
At first glance, this branch does not have the problems I noted, except for the vorbis-tools library, which is still rebuilt every time the project starts.

**Comment by LigH-de** [comment]
I reported my last cases to https://github.com/mesonbuild/meson/issues/7486 - but I doubt this one will be resolved quickly... at least I believe they are not the same case as those of j-mas :confused:

**Comment by j-mas** [comment]
I think it is a specific problem with my computer. 
It works fine on my laptop again. 
I copied the result and transferred it to my desktop PC. 
When I ran it on my PC, the problem came back immediately. 
Perhaps it is also the preview build of Windows 10. 
But since it works again on my laptop and the problem does not seem to be a general one, I will close this issue. 
Thank you for your help!
