### ISSUE TITLE
[mingw32|mingw64] [gpac]

### ISSUE THREAD

**Issue by masterkivat** [m-ab-s/media-autobuild_suite#1762]
07:24:53   Running git update for gpac...
07:24:54 ┌ gpac git  .................................... [Updates found]
07:24:54 ├ Running uninstall...
07:24:54 ├ Running configure...
07:25:03 ├ Running make...
Likely error (tail of the failed operation logfile):
make[2]: Entering directory '/build/gpac-git/build-32bit/applications/gpac'
make[2]: Leaving directory '/build/gpac-git/build-32bit/applications/gpac'
make[2]: Entering directory '/build/gpac-git/build-32bit/applications/mp4box'
S:/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(constants.o):constants.c:(.data+0x0): multiple definition of `itunes_tags'; main.o:main.c:(.bss+0x138): first defined here
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:68: MP4Box.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/build-32bit/applications/mp4box'
make[1]: *** [Makefile:41: apps] Error 2
make[1]: Leaving directory '/build/gpac-git/build-32bit/applications'
make: *** [Makefile:14: all] Error 2

[ivRh.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4947231/ivRh.zip)

**Comment by kenichi512** [comment]
The same thing happened to me today, until yesterday everything was fine.

**Comment by 1480c1** [comment]
https://github.com/gpac/gpac/commit/20e9b1de6934161ce4ada9ec69832dc75a3b9550

will need a patch
