### ISSUE TITLE
64 bit, Error after jq git  .......... [Up-to-date] –git.reset failed

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1766]
``` bash
20:24:04 Warning: We will not accept any issues lacking any form of logs or logs.zip!
20:24:04
        Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
20:24:11
        Starting 64bit compilation of global tools
20:24:11 ├ Running rustup_update...
20:24:12 ├ Running set_default_toolchain...
20:24:16   Running git update for ripgrep...
20:24:19 ripgrep git  ...................................... [Up-to-date]
20:24:21   Running git update for jo...
20:24:22 jo git  ........................................... [Up-to-date]
20:24:26   Running git update for jq...
20:24:28 jq git  ........................................... [Up-to-date]
Likely error (tail of the failed operation logfile):
++ vcs_get_latest_tag origin/HEAD git
++ case ${2:-$(vcs_get_current_type)}/${1:-unknown} in
++ false
++ echo origin/HEAD
+ git reset --hard origin/HEAD
warning: ignoring dangling symref refs/remotes/origin/HEAD
warning: ignoring dangling symref refs/remotes/origin/HEAD
fatal: ambiguous argument 'origin/HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
git.reset failed. Check C:/MinGW64/build/dssim-git/ab-suite.git.reset.log
This is required for other packages, so this script will exit.
20:24:30   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iwXy.zip
Copy and paste [logs.zip](https://0x0.st/iwXy.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

[logs.zip](https://0x0.st/iwXy.zip)
[ab-suite.git.reset.log](https://github.com/m-ab-s/media-autobuild_suite/files/4953478/ab-suite.git.reset.log)

**Comment by 1480c1** [comment]
Can you try this branch? https://github.com/m-ab-s/media-autobuild_suite/pull/1758

**Comment by 1480c1** [comment]
and also delete build/dssim-git

**Comment by 1480c1** [comment]
@ycwan any update?

**Comment by ycwan** [comment]
@1480c1  Updated MABS & deleted build/dssim-git.  Now MABS is running & has successfully continue after jq git  ........ [Up-to-date] as shown in screenshot below.  Thanks.  Hope it will complete compilation of all tools without error

        Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
00:14:17
        Starting 64bit compilation of global tools
00:14:17 ├ Running rustup_update...
00:14:17 ├ Running set_default_toolchain...
00:14:20   Running git update for ripgrep...
00:14:21 ripgrep git  ...................................... [Up-to-date]
00:14:23   Running git update for jo...
00:14:23 jo git  ........................................... [Up-to-date]
00:14:25   Running git update for jq...
00:14:26 jq git  ........................................... [Up-to-date]
00:14:26   Running git clone for dssim...
00:14:32 ┌ dssim git  ................................ [Recently updated]
00:14:33 ├ Running rust.update...
00:14:51 ├ Running rust.build...
00:16:10 ├ Stripping...
00:16:10 └ dssim-git  ......................................... [Updated]
00:16:14   Running git update for libxml2...
00:16:23 ┌ libxml2 git  ................................. [Updates found]
00:16:24 ├ Running uninstall...
00:16:25 ├ Running autogen...
00:16:59 ├ Running configure...
00:18:19 ├ Running make...
00:18:51 ├ Running install...
00:18:58 ├ Stripping...
00:18:58 └ libxml2-git  ....................................... [Updated]

**Comment by 1480c1** [comment]
Okay, thanks
