### ISSUE TITLE
LuaJIT : Patch could not be applied with `....

### ISSUE THREAD

**Issue by pat357** [m-ab-s/media-autobuild_suite#1771]
``` bash
22:36:54 ┌ luajit git  ............................... [Recently updated]
22:36:56 Running clean in luajit-git
make -C src clean
make[1]: Entering directory '/build/luajit-git/src'
rm -f luajit.exe libluajit.a lua51.dll host/minilua.exe host/buildvm.exe lj_vm.S lj_bcdef.h lj_ffdef.h lj_libdef.h lj_recdef.h lj_folddef.h host/buildvm_arch.h jit/vmdef.lua *.o host/*.o *.obj *.lib *.exp *.dll *.exe *.manifest *.pdb *.ilk
make[1]: Leaving directory '/build/luajit-git/src'
0001-Add-win32-UTF-8-filesystem-functions.patch
        Patch could not be applied with `git am`. Continuing without patching.
002-fix-pkg-config-file.patch
        Patch could not be applied with `patch`. Continuing without patching.
22:36:59 Running make in luajit-git
Building LuaJIT 2.1.0-beta3
make -C src amalg
make[1]: Entering directory '/build/luajit-git/src'

```

**Comment by 1480c1** [comment]
could you potentially make sure you have the latest suite and also upload the media-suite_compile.sh? I was able to apply the patches cleanly both on Linux and windows

**Comment by pat357** [comment]
Strange ....
Because of an issue I have with the suite producing corrupted MPV for 32bit (64 bit is fine), I started all over again with building the suite yesterday.
I checked out MABS and started the .bat and let everything download, recompile everything.
Than I got this message -> LuaJIT : Patch could not be applied with `...
After comparing the media-suite_compile.sh from download today with my updated version shows files are identical.

Since the was no commit for LuaJIT between yesterday and today, I confident that I have the latest media-suite_compile.sh.
I'll try to run it again and report back.

BTW  : if you compile the 32bit version of MPV, does it also silently crash after double clicking on MPV.EXE ??

**Comment by 1480c1** [comment]
yeah, trying to run the 32-bit mpv doesn't seem to work, nothing in the console either

**Comment by pat357** [comment]
I must be something specific to our way to build mpv, because the builds from shinchiro are OK.
Problem started between 2/6/2020 and 5/6/2020. 
My compile from 2/6/2020 and earlier work, but all later compiles have a corrupted MPV.
I compiled the debug version and loaded MPV in GDB : crash in kernelbase.dll IIRC.
```
$ gdb -w -args mpv.exe 1.mp4
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
This GDB was configured as "i686-w64-mingw32".
Reading symbols from mpv.exe...
Reading symbols from H:\Mingw645\local32\bin-video\mpv.exe.debug...
(gdb) run
Starting program: H:\Mingw645\local32\bin-video\mpv.exe 1.mp4
[New Thread 9560.0x248c]
[New Thread 9560.0x2488]
[New Thread 9560.0x2484]
[New Thread 9560.0x2578]
[New Thread 9560.0x2574]
[New Thread 9560.0x2500]
[New Thread 9560.0x24fc]
gdb: unknown target exception 0xc00001a5 at 0x22a6650

Thread 5 received signal ?, Unknown signal.
[Switching to Thread 9560.0x2578]
0x76bd4402 in RaiseException () from C:\WINDOWS\System32\KernelBase.dll
(gdb)
```
I suspect the problem comes from shader-c (combined shaders), because if you run mpv with --logfile=log.txt , the last line is
initialising shaders-c .
It seems it fails to init the shader-c lib.
Would mpv uberhaupt run without the shader-c lib ? How  to disable these in the mpv.conf ?

**Comment by pat357** [comment]
Problem with patch seems to be solved.
It was my mistake.
