### ISSUE TITLE
aom failed to build

### ISSUE THREAD

**Issue by j-mas** [m-ab-s/media-autobuild_suite#1773]
16:22:45 ┌ aom git  .................................. [Recently updated]
16:22:46 ├ Running cmake...
Likely error (tail of the failed operation logfile):

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)

-- Configuring incomplete, errors occurred!
See also "C:/media-autobuild_suite-master/build/aom-git/build-64bit/CMakeFiles/CMakeOutput.log".
See also "C:/media-autobuild_suite-master/build/aom-git/build-64bit/CMakeFiles/CMakeError.log".
cmake failed. Check C:/media-autobuild_suite-master/build/aom-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
16:22:48   Creating diagnostics file...

[ab-suite.cmake.log](https://github.com/m-ab-s/media-autobuild_suite/files/4988950/ab-suite.cmake.log)
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4989004/logs.zip)

**Comment by 1480c1** [comment]
try rerunning the suite, it seems like a temporary issue due to cmake

**Comment by j-mas** [comment]
In the meantime, I have completely rebuilt Windows 10. After that, the suite worked perfectly. Now that I have reinstalled all programs, the previous problem arises. At first the suite at aom git broke with the error message I posted (at cmake) and now, after there is an update from fribidi git, the suite breaks at fribidi git again. Are there any programs known to cause a problem with the suite? The Defender cannot be, it worked after reinstalling Windows 10. Could Python 3.8 (32-bit) prevent compiling?

**Comment by 1480c1** [comment]
Not entirely sure what could cause it, since the most likely problem would be a antivirus deleting the compiled file before gcc can link it, but you said it seems it worked before. I do not think any other package could cause this issue.

**Comment by 1480c1** [comment]
@j-mas can you try adding the suite folder to the windows defender exclusion and rerun and see if that produces an error?

**Comment by j-mas** [comment]
I will try it in the evening after work! Thank you!

**Comment by j-mas** [comment]
I give up. It's probably because of the computer, for whatever reason. Defender exclusion also did nothing. I still have my laptop. There the suite is running perfectly!
