### ISSUE TITLE
Request: VapourSynth R51 was released

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1775]
You may want to update dependencies.

**Comment by LigH-de** [comment]
Serious issues have been discovered in R51. R52-RC1 was urgently recommended, a final release R52 announced *soon™*.

**Comment by LigH-de** [comment]
[R52](https://github.com/vapoursynth/vapoursynth/releases/tag/R52) is available, identical to R52-RC1.

**Comment by LigH-de** [comment]
[R53](https://github.com/vapoursynth/vapoursynth/releases/tag/R53) got released.

**Comment by 1480c1** [comment]
updated to 3.8.9 and 53

**Comment by LigH-de** [comment]
[R54](https://github.com/vapoursynth/vapoursynth/releases/tag/R54) got released. Uses [a newer MSVC](https://forum.doom9.org/showthread.php?p=1948168#post1948168).
