### ISSUE TITLE
libkvazaar and kvazaar produce no output

### ISSUE THREAD

**Issue by acfrock** [m-ab-s/media-autobuild_suite#1777]
Neither the libkvazaar encoder in ffmpeg or the kvazaar.exe executable produce output. 

My commands are as follows:
`.\ffmpeg.exe -v verbose -i "E:\Video\The Wind Rises\The Wind Rises.mkv" -c:v libkvazaar -kvazaar-params preset=medium,qp=18 -c:a copy "E:\MKV\Transcoded\The Wind Rises_kvazaar.mkv"`
and
`.\kvazaar.exe -i "E:\Video\The Wind Rises\The Wind Rises.yuv" --input-res 1920x1080 --preset medium --qp 18 -o "E:\MKV\Transcoded\The Wind Rises_kvazaar.hevc"`

The second command produces correct output with the official build of kvazaar [link](https://github.com/ultravideo/kvazaar/releases/tag/v2.0.0), but only acknowledges the parameters with the m-ab-a build:

`Using preset medium: --rd=0 --pu-depth-intra=1-4 --pu-depth-inter=0-3 --me=hexbs --gop=16 --ref=4 --bipred=1 --deblock=0:0 --signhide=0 --subme=4 --sao=full --rdoq=1 --rdoq-skip=0 --transform-skip=0 --mv-rdo=0 --full-intra-search=0 --smp=0 --amp=0 --cu-split-termination=zero --me-early-termination=on --intra-rdo-et=0 --early-skip=1 --fast-residual-cost=0 --max-merge=5
Compiled: INTEL, flags: MMX SSE SSE2 SSSE3 SSE41 SSE42
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(11) avx2(55) sse2(2) sse41(4)
In use: avx(1) avx2(55)
--owf=auto value set to 3.
--threads=auto value set to 24.
Input: E:\Video\The Wind Rises\The Wind Rises.yuv, output: E:\MKV\Transcoded\The Wind Rises_kvazaar.hevc
  Video size: 1920x1080 (input=1920x1080)`

**Comment by 1480c1** [comment]
When you mean "output", are you talking about the mkv and hevc file or output to terminal?

**Comment by acfrock** [comment]
Yes, thank you. As I included at the end there, it's outputting an acknowledgement of the preset to the terminal, but it writes an empty mkv or hevc file. (as both standalone exe and lib in ffmpeg)

**Comment by 1480c1** [comment]
Okay, thanks for the info, wasn't sure if you were saying ffmpeg and kvazaar.exe outputted nothing in terms of file and terminal and saying an official release was, or if you were saying the terminal output from the kvazaar.exe built was correct as compared to an official release, but does not output to a file correctly.

I will need to look into the issue since I have not used kvazaar recently.

**Comment by 1480c1** [comment]
You might want to report this to upstream, since trying to run
```bash
gdb --args ffmpeg.exe -v verbose -i '.\Falling In Reverse - ''Popular Monster''-jakpo7tj7Qw.mp4' -c:v libkvazaar -q 18 -an temp.hevc
```

results in 
```none
Output #0, hevc, to 'temp.hevc':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6av01mp41
    encoder         : Lavf58.50.100
    Stream #0:0(und): Video: hevc (libkvazaar), 1 reference frame, yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 24 fps, 24 tbn, 24 tbc (default)
    Metadata:
      creation_time   : 2019-11-30T03:07:01.000000Z
      handler_name    : ISO Media file produced by Google Inc.
      encoder         : Lavc58.100.100 libkvazaar

Thread 37 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 5220.0x568]
0x00007ff7725f4386 in ?? ()
````

I will try recompiling kvazaar without strip and with debug to try to see what's causing it, but it's not ffmpeg since running the debug ffmpeg still produces `??`

**Comment by 1480c1** [comment]
```c
Starting program: D:\media-autobuild_suite\local64\bin-video\kvazaar.exe -i .\temp.yuv --input-res 1920x1080 --preset medium --qp 18 -o .\temp.hevc
[New Thread 18996.0x5b60]
Using preset medium: --rd=0 --pu-depth-intra=1-4 --pu-depth-inter=0-3 --me=hexbs --gop=16 --ref=4 --bipred=1 --deblock=0:0 --signhide=0 --subme=4 --sao=full --rdoq=1 --rdoq-skip=0 --transform-skip=0 --mv-rdo=0 --full-intra-search=0 --smp=0 --amp=0 --cu-split-termination=zero --me-early-termination=on --intra-rdo-et=0 --early-skip=1 --fast-residual-cost=0 --max-merge=5
Compiled: INTEL, flags: MMX SSE SSE2 SSSE3 SSE41 SSE42
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(11) avx2(55) sse2(2) sse41(4)
In use: avx(1) avx2(55)
--owf=auto value set to 2.
--threads=auto value set to 12.
[New Thread 18996.0x2b4]
[New Thread 18996.0x5198]
[New Thread 18996.0x4e08]
[New Thread 18996.0x2d60]
[New Thread 18996.0x4048]
[New Thread 18996.0x3e04]
[New Thread 18996.0x5aec]
[New Thread 18996.0x4df8]
[New Thread 18996.0x41b8]
[New Thread 18996.0x5b2c]
[New Thread 18996.0x3d88]
[New Thread 18996.0x2c94]
Input: .\temp.yuv, output: .\temp.hevc
  Video size: 1920x1080 (input=1920x1080)
[New Thread 18996.0x5830]

Thread 3 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 18996.0x2b4]
0x000000000042eb96 in matrix_dct_4x4_avx2 ()
(gdb)
```

**Comment by pat357** [comment]
This is in fact an old bug. The with GCC compiled .exe is broken for a while already.
What I did is using the **clang/clang++** compiler instead of gcc : the produced .exe is running just fine.

**Comment by 1480c1** [comment]
hmm, do you think it might be a good idea to report it somewhere and make a warning then?

**Comment by pat357** [comment]
Report where ?
I  suppose the kvazaar guys already know that there are problems when compiling with GCC.
In the file "readme.md" they advise you to use clang instead of gcc

_### Autotools on MinGW
It is recommended to use Clang instead of GCC in MinGW environments. GCC also works, but AVX2 optimizations will be disabled because of a known GCC issue from 2012, so performance will suffer badly. Instead of `./configure`, run

    CC=clang ./configure
to build Kvazaar using Clang._

**Comment by 1480c1** [comment]
It could be reported to gcc (although i assume they might already know iirc there was some kind of issued filed before) but the fact that avx2 doesn't actually get disabled with mingw-w64 gcc can be reported to kvazaar so they can manually disable it during configure time or make sure it doesn't get compiled until it's known to be fixed or something

**Comment by pat357** [comment]
For the suite, I think the best option is to use the **clang**-compiler instead of **gcc.**
Even if the kvazaar guys would add a detection to disable AVX2, you would still end up with a "half broken" encoder that would be very slow and not be very useful because of the serious performance penalty due to the missing AVX2 optimizations.

**Comment by 1480c1** [comment]
@wiiaboo do you have any opinion on forcing kvazaar to compile with clang instead of gcc?

**Comment by wiiaboo** [comment]
I've never used it, nor know if anyone actually uses it, so seems fine by me.

**Comment by 1480c1** [comment]
@pat357 are you sure kvazaar compiles fine with clang? I keep on getting errors such as 
```bash
/bin/sh ../libtool --mode=compile --tag=CC yasm -I../../src/extras -DARCH_X86_64=1 -m amd64 -fwin64 -DHAVE_ALIGNED_STACK=1 ../../src/strategies/x86_asm/picture-x86-asm-sad.asm -o strategies/x86_asm/picture-x86-asm-sad.lo -prefer-non-pic 1>/dev/null
mv: cannot stat 'picture-x86-asm-sad.o': No such file or directory
```

with using find

```bash
find . -name "*picture-x86-asm-sad*"
./src/picture-x86-asm-sad.obj
```


which feels like https://github.com/m-ab-s/media-autobuild_suite/issues/1571

I'm wondering if autotools or libtool isn't detecting the proper object format or something

**Comment by pat357** [comment]
It did last time it was updated and I did run the suite.....
I will try it again soon and report back.

**Comment by pat357** [comment]
I just reran the suite and compiled kvazaar.exe again using CC=clang.bat.
I included some log files from kvazaar configure/make. If you would like to see other files as well, just ask and I will provide them.
[kvazaar_log.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5086148/kvazaar_log.zip)
[kvazaar_encoding_ok.txt](https://github.com/m-ab-s/media-autobuild_suite/files/5086150/kvazaar_encoding_ok.txt)

My yet to clean up code in media-suite_build.sh

``` bash
check=(libkvazaar.{,l}a kvazaar.pc kvazaar.h)
    [[ $standalone = y ]] && _check+=(bin-video/kvazaar.exe)
if [[ $bits == 32bit ]]; then
    do_removeOption "--enable-libkvazaar"
    unset _check _deps
elif { [[ $other265 = y ]] || { [[ $ffmpeg != no ]] && enabled libkvazaar; }; } &&
    do_vcs "https://github.com/ultravideo/kvazaar.git"; then
    do_uninstall kvazaar_version.h "${_check[@]}"
    CC_ORG="$CC"
    CXX_ORG="$CXX"
    CC="clang.bat"
    CXX="clang++.bat"
    CFLAGS_ORG="$CFLAGS"
    unset CFLAGS CXXFLAGS
    CFLAGS=" -march=native -mavx -mavx2 -O3 -pipe" ## -mavx512f -mavx512cd -mavx512dq -mavx512bw -mavx512vl
    CXXFLAGS="$CFLAGS"
    export CFLAGS CXXFLAGS CC CXX
    do_autogen
    [[ $standalone = y || $other265 = y ]] ||
        sed -i "s|bin_PROGRAMS = .*||" src/Makefile.in
    CC='clang.bat' CXX='clang++.bat' \
    do_separate_conf video --prefix="$LOCALDESTDIR"
    do_make
    make install PREFIX="$LOCALDESTDIR" BINDIR="$LOCALDESTDIR/bin-video"
    CC="$CC_ORG"
    CXX="$CXX_ORG"
    CFLAGS="$CFLAGS_ORG"
    CXXFLAGS="$CFLAGS_ORG"
    export CFLAGS CXXFLAGS CC CXX
    unset CC_ORG CXX_ORG CFLAGS_ORG _notrequired
    do_checkIfExist
fi

**Comment by 1480c1** [comment]
hmm, interesting, I guess I will try making the necessary changes on a local branch and run it through the suite instead of manually running them

**Comment by 1480c1** [comment]
seems it doesn't work for me
```none
Likely error (tail of the failed operation logfile):
  CCLD     libsse2.la
  CC       strategies/sse41/libsse41_la-picture-sse41.lo
  CCLD     libsse41.la
  YASM     strategies/x86_asm/picture-x86-asm-sad.lo
mv: cannot stat 'picture-x86-asm-sad.o': No such file or directory
make[2]: *** [Makefile:2051: strategies/x86_asm/picture-x86-asm-sad.lo] Error 1
make[2]: Leaving directory '/build/kvazaar-git/build-64bit/src'
make[1]: *** [Makefile:524: all-recursive] Error 1
make[1]: Leaving directory '/build/kvazaar-git/build-64bit'
make: *** [Makefile:394: all] Error 2
```

I wonder what's different

**Comment by 1480c1** [comment]
> If you want I'll upload my full kvazaar-build64 directory to some place, just let me know if you would like to look at any file I have.

Could you try that? I think it would be helpful to see the output of your configuration step and also the generated libtool to see how it compares to the one generated locally

**Comment by pat357** [comment]
Here you go:
[kvazaar-build-64bit.7z.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5118977/kvazaar-build-64bit.7z.zip)

**Comment by 1480c1** [comment]
thanks, I'll look into it in my free time

**Comment by 1480c1** [comment]
Actually, I'll try seeing if adding `-fno-asynchronous-unwind-tables` to the CFLAGS fixes the issue

**Comment by 1480c1** [comment]
seems it works

**Comment by 1480c1** [comment]
@acfrock and @pat357 can you guy check if changing line 1116 in media-suite_compile.sh to
```bash
    CFLAGS+=" -fno-asynchronous-unwind-tables" do_separate_confmakeinstall video
```

and see if that will fix it for gcc and also won't break compilation for clang?

**Comment by 1480c1** [comment]
Well, after testing with both clang and gcc, the encoding is running with avx2 and not crashing

**Comment by 1480c1** [comment]
Well, after finding out that kvazaar disables avx2 in some way in the configure file, added an extra patch, current work is in https://github.com/1480c1/media-autobuild_suite/tree/kva, it has some other fixes for clang related stuff like vidstab

**Comment by 1480c1** [comment]
after testing and seeing that avx2 doesn't seem to crash with gcc as well, going to push
