### ISSUE TITLE
Script fails because harfbuzz is no longer using autogen

### ISSUE THREAD

**Issue by brianjjones** [m-ab-s/media-autobuild_suite#1780]
harfbuzz just updated their codebase to use meson / ninja instead of autogen. And because of this the script fails because ./autogen.sh no longer exists. See this PR for info.

https://github.com/harfbuzz/harfbuzz/commit/01ac32aab2109681abc58bb2f96a4ef4a7f0c6df

**Comment by wiiaboo** [comment]
Did you update the suite since https://github.com/m-ab-s/media-autobuild_suite/commit/77f2836f62ea5b28f1d687a526843af2e1ebbdaf?

**Comment by 1480c1** [comment]
I'm assuming closed since this should have been fixed in that commit, if you still have an issue, you can comment or reopen
