### ISSUE TITLE
openal-soft: 0001-CMake-Fix-issues-for-mingw-w64.patch (again) not applied in mingw64 branch

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1784]
```
┌ openal-soft git  .................................... [Recently updated]
├ Running uninstall...
0001-CMake-Fix-issues-for-mingw-w64.patch
	Patch could not be applied with `patch`. Continuing without patching.
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ openal-soft-git  ............................................. [Updated]
```

In my last mistaken pull request, @1480c1 mentioned to have rebased this patch. So I wonder if the sources changed again, or the rebased patch was not uploaded to the same place, or a dual build for mingw32 and mingw64 might try to apply it twice?

In addition, I miss a compile.log stripped off ANSI color sequences when the suite finished successfully. I know one is generated when it fails. At least I found a Windows CLI filter (ansifilter by André Simon).

[compile_stripped.log](https://github.com/m-ab-s/media-autobuild_suite/files/5063511/compile_stripped.log)

**Comment by 1480c1** [comment]
Can you retry on the latest suite? I changed it to use git am with the three-way option, so it might be a bit more resilient

**Comment by LigH-de** [comment]
Ran it 2 times in a row; works reliably for me now.
