### ISSUE TITLE
[mingw64] [ffmpeg] Can't build ffmpeg with CUDA toolkit 11.0.3

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#1785]
Windows Server 2019
Visual Studio 16.7.0 enterprise
CUDA Toolkit 11.0.3

My "CUDA_PATH" variable  is "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0"

> 09:07:18 ┌ ffmpeg git  .................................. [Updates found]
> 09:07:22 ├ Changing options to comply to nonfree...
> FFmpeg and related apps will depend on CUDA SDK to run!
> 09:07:24 ├ Spaces detected in the short path returned by your system!
> 09:07:24 ├ Path returned by windows: C:/PROGRA~1/NVIDIA GPU Computing Toolkit/CUDA/v11.0
> 09:07:24 ├ This will break FFmpeg compilation, so aborting early!
> This is required for other packages, so this script will exit.
> 09:07:24   Creating diagnostics file in ffmpeg-git

Full error log:  https://0x0.st/iYqW.zip

**Comment by 1480c1** [comment]
Please reinstall cuda to a shorter path or a path without spaces since it seems there's no shortpath generated for that path, so compiling will fail

https://github.com/m-ab-s/media-autobuild_suite/issues/1778

https://github.com/m-ab-s/media-autobuild_suite#you-do-not-need-to-do-the-following-if-you-installed-the-sdk-with-the-default-locations-etc-and-you-have-83-short-paths-enabled-or-if-you-installed-to-a-directory-without-any-spaces

**Comment by 1480c1** [comment]
btw @fuchanghao and @miguelapg, can you guys run `fsutil 8dot3name query` inside cmd.exe or powershell and tell me what is says, and also what windows version you guys have? I'm wondering if MS did something to disable generating new shortpaths on newer windows 10 builds or something or if it's only related to cuda 11 not asking for short paths

**Comment by miguelapg** [comment]
I think you should add a more clear message in the shell above-mentioned, something for example like (feel free to change it)...
```
09:07:18 ┌ ffmpeg git .................................. [Updates found]
09:07:22 ├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK to run!
09:07:24 ├ Spaces detected in the CUDA path! Please, install CUDA SDK in a path without spaces.
09:07:24 ├ Path returned by windows: C:/PROGRA~1/NVIDIA GPU Computing Toolkit/CUDA/v11.0
09:07:24 ├ This will break FFmpeg compilation, so aborting early!
This is required for other packages, so this script will exit.
09:07:24 Creating diagnostics file in ffmpeg-git
```
I think that people are asking because they don't understand well what is happening.

```
fsutil 8dot3name query
Registry status is: 1 (disable 8dot3 naming on all volumes).
```

**Comment by 1480c1** [comment]
Would it be possible to ask you to submit a PR with the wording changes? It might be better overall if someone who is on the side of needing to change their cuda install can give make sure the message is transmitted in a way that they will easily understand. If not I will try see if I can word the message a bit more clearer.

**Comment by miguelapg** [comment]
I don't catch you. What do you mean when you mention PR?

As you can see I just replaced ...
```
Spaces detected in the short path returned by your system!
```
... by
```
Spaces detected in the CUDA path! Please install CUDA SDK in a path without spaces.`
```
And it's just an example. Feel free to add any other clarification.

**Comment by 1480c1** [comment]
A PR on github means a pull request, aka a way to request a maintainer to review and potentially add your changes, but it is no longer needed, I added your change in https://github.com/m-ab-s/media-autobuild_suite/commit/580e11d372562f17762c02435c7b3020298ad65d


https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by miguelapg** [comment]
OK, I understand. Thanks, Christopher

**Comment by 1480c1** [comment]
You're welcome, going to close this issue since this is not necessarily something we can solve suite side

**Comment by ImportTaste** [comment]
> You're welcome, going to close this issue since this is not necessarily something we can solve suite side

Why rely on cygpath to do the job when it can be done natively in the batch file?

```batch
if defined CUDA_PATH for %%G in ("%CUDA_PATH%") do set "fixed_CUDA_PATH=%%~sG"
```

**Comment by 1480c1** [comment]
It's mainly because what cygpath does in the case of when a short path is requested is directly ask window's API, and in this case, since the window's API returns a path with spaces, I do not think a bat file will give any better results

@fuchanghao and @miguelapg, could you guys try putting
```batch
if defined CUDA_PATH for %%G in ("%CUDA_PATH%") do set "fixed_CUDA_PATH=%%~sG"
echo %fixed_CUDA_PATH%
pause
```
into a file called bat.bat and double click it and print out what it shows?

**Comment by ImportTaste** [comment]
Alternatively you could just put this into the command prompt:
```batch
if defined CUDA_PATH for %G in ("%CUDA_PATH%") do @echo %~sG
```

I'm assuming it's a WS2019 compatibility issue since `cygpath -sm "$CUDA_PATH'` converts into a short path just fine for me on Windows 10.

**Comment by 1480c1** [comment]
It prints out fine for me with short paths without spaces as well, but I currently still have an old 10.3 cuda sdk, currently upgrading it so I can try to see if there's something different with 11

**Comment by 1480c1** [comment]
as a reference, `fsutil 8dot3name query` prints 2 for me

**Comment by 1480c1** [comment]
seems it's fine for me
```bash
$ cygpath -sm "$CUDA_PATH"
C:/PROGRA~1/NVIDIA~2/CUDA/v11.0
```

but probably because it's set to `The registry state is: 2 (Per volume setting - the default).`

**Comment by miguelapg** [comment]
```
C:\media_2>if defined CUDA_PATH for %G in ("C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0") do set "fixed_CUDA_PATH=%~sG"

C:\media_2>set "fixed_CUDA_PATH=C:\PROGRA~1\NVIDIA GPU Computing Toolkit\CUDA\v11.0"

C:\media_2>echo C:\PROGRA~1\NVIDIA GPU Computing Toolkit\CUDA\v11.0
C:\PROGRA~1\NVIDIA GPU Computing Toolkit\CUDA\v11.0

C:\media_2>pause

$ cygpath -sm "$CUDA_PATH"
C:/PROGRA~1/NVIDIA GPU Computing Toolkit/CUDA/v11.0
```

By the way, I have installed Visual Studio 2019 Community Editioon

**Comment by ImportTaste** [comment]
Try this
```batch
@cd /d "C:\Program Files"
@fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~1 || fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~2
@pause
```

Might have to be ran as administrator

**Comment by miguelapg** [comment]
> Try this
> 
> ```batchfile
> @echo off
> cd /d "C:\Program Files"
> fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~1 || fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~2
> if defined CUDA_PATH for %%G in ("%CUDA_PATH%") do echo %%~sG
> pause
> ```
> 
> Might have to be ran as administrator

I created a bat.bat inserting the code you mentioned and running that bat as administrator and I received this message ...

Spanish: Error:  No se puede crear un archivo que ya existe.
English Error:  It cannot be created a file which is already existing

**Comment by ImportTaste** [comment]
> > Try this
> > ```batchfile
> > @echo off
> > cd /d "C:\Program Files"
> > fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~1 || fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~2
> > if defined CUDA_PATH for %%G in ("%CUDA_PATH%") do echo %%~sG
> > pause
> > ```
> > 
> > 
> > Might have to be ran as administrator
> 
> I created a bat.bat inserting the code you mentioned and running that bat as administrator and I received this message ...
> 
> Spanish: Error: No se puede crear un archivo que ya existe.
> English Error: It cannot be created a file which is already existing

```batch
@echo off
cd /d "C:\Program Files"
fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~1 || fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~2 || fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~3
if defined CUDA_PATH for %%G in ("%CUDA_PATH%") do echo %%~sG
pause
```

**Comment by miguelapg** [comment]
Yes it worked!!!

$ cygpath -sm "$CUDA_PATH"
C:/PROGRA~1/NVIDIA~3/CUDA/v11.0

**Comment by 1480c1** [comment]
Oh, nice, maybe that can be added to the readme instead of immediately asking for the user to reinstall.


I do wonder what was taking up the other shortnames

**Comment by miguelapg** [comment]
> Oh, nice, maybe that can be added to the readme instead of immediately asking for the user to reinstall.
> 
> I do wonder what was taking up the other shortnames

Yes, it seems a strange thing why NVIDIA~2 didn't work.

**Comment by 1480c1** [comment]
Did you have an older cuda sdk installed before?

I wonder if maybe the newer installers didn't remove the old short paths during cleanup?

**Comment by miguelapg** [comment]
> Did you have an older cuda sdk installed before?
> 
> I wonder if maybe the newer installers didn't remove the old short paths during cleanup?

Yes I had CUDA v11.2

**Comment by 1480c1** [comment]
So currently I am thinking of making some changes that will print out

```bash
├ Spaces detected in the CUDA path!
├ Path returned by windows: C:/PROGRA~1/NVIDIA~2/CUDA/v11.0
├ A script was created at D:/media-autobuild_suite/build/cuda.bat
├ Please run that script as an administrator and rerun the suite
├ This will break FFmpeg compilation, so aborting early!
```
![image](https://user-images.githubusercontent.com/8345542/90213715-18ed0c80-ddbc-11ea-8cbe-7426fd38553a.png)
minus the part that the path shown here doesn't actually have spaces.

and inside `D:/media-autobuild_suite/build/cuda.bat`

```batch
@echo off
cd /d "C:\PROGRA~1"
fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~1 || fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~2 || fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~3 || fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~4 || echo Failed to set a shortname for your CUDA_PATH
```

generated using
```bash
               {
                    cat << EOF
@echo off
cd /d "$(dirname "$(dirname "$(dirname "$(cygpath -sw "$CUDA_PATH")")")")"
EOF
                    # Generate up to 4 shortnames
                    for _n in 1 2 3 4; do
                        printf 'fsutil file setshortname "NVIDIA GPU Computing Toolkit" NVIDIA~%d || ' "$_n"
                    done
                    echo 'echo Failed to set a shortname for your CUDA_PATH'
                } > "$LOCALBUILDDIR/cuda.bat"
```

@miguelapg @fuchanghao @ImportTaste does the message make enough sense? Do you guys think there is anything else I should add or remove?

**Comment by ImportTaste** [comment]
Looks good. Here's something you can toss in.
```batch
fltmc >NUL 2>&1 || echo Elevation required, right click the script and click 'Run as administrator'. & echo/ & pause & exit /b 1
```

**Comment by 1480c1** [comment]
I'm assuming that goes right after `@echo off` to trigger an elevation required message?

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/5648822710adb5a7343876fbd641345b89b66b5e

**Comment by miguelapg** [comment]
Wow. This is incredible. What smart solutions you get!

Thanks!!
