### ISSUE TITLE
Problems installing rustup

### ISSUE THREAD

**Issue by miguelapg** [m-ab-s/media-autobuild_suite#1786]
There is a problem when installing rustup once MSYS2 is installed and the suite starts to configure things. This is preventing that suite continues its installation rightly.

It's solved adding -k at curl calls inside the script downloaded from https://sh.rustup.rs so basically we are allowing curl to connect to sites without checking the SSL certificate.

I mean at these lines inside the downloaded /build/rustinstall/rustup.sh
``` bash
        if [ -n "$_ciphersuites" ]; then
            curl --proto '=https' --tlsv1.2 --ciphers "$_ciphersuites" --silent --show-error --fail --location "$1" --output "$2"
        else
            echo "Warning: Not enforcing strong cipher suites for TLS, this is potentially less secure"
            if ! check_help_for "$3" curl --proto --tlsv1.2; then
                echo "Warning: Not enforcing TLS v1.2, this is potentially less secure"
                curl --silent --show-error --fail --location "$1" --output "$2"
            else
                curl --proto '=https' --tlsv1.2 --silent --show-error --fail --location "$1" --output "$2"
            fi
        fi
```
But this file is out of the hands of the suite as is owned by Rustup.rs

On the other hand, in the website https://rustup.rs/ there is a recommendation as follow ...
_________________________
If you're a Windows Subsystem for Linux user run the following in your terminal, then follow the onscreen instructions to install Rust.

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
_________________________

The call at the suite is different, namely is ...

curl "https://sh.rustup.rs" -sSo rustup.sh

I don't know if using the command for curl recommended by rustup the issue is solved.

The issue at the suite installation is as follow ...
``` bash
Starting 64bit compilation of global tools
04:32:50 ├ Running download_rustup...
04:32:51 ├ Running install_rust...
Likely error (tail of the failed operation logfile):
LDFLAGS: -pipe -static-libgcc -static-libstdc++
./rustup.sh -v -y --no-modify-path --default-host=x86_64-pc-windows-gnu --default-toolchain=stable
info: downloading installer
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe /tmp/tmp.TUdHQDPSFi/rustup-init.exe x86_64-pc-windows-gnu
```

Logs here ... https://0x0.st/iYu6.zip

**Comment by miguelapg** [comment]
The problem continues and unfortunately, the problem is at the script /build/rustinstall/rustup.sh downloaded from https://sh.rustup.rs

Seems the only solution is to contact those people.
```
Starting 64bit compilation of global tools
├ Running download_rustup...
├ Running install_rust...
Likely error (tail of the failed operation logfile):
LDFLAGS: -pipe -static-libgcc -static-libstdc++
./rustup.sh -v -y --no-modify-path --default-host=x86_64-pc-windows-gnu --default-toolchain=stable
info: downloading installer
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe /tmp/tmp.4E9gV7Rinc/rustup-init.exe x86_64-pc-windows-gnu
install_rust failed. Check C:/media_2/build/rustinstall/ab-suite.install_rust.log
This is required for other packages, so this script will exit.
```
Logs here https://0x0.st/iYSm.zip

**Comment by 1480c1** [comment]
indeed, this seems to come from inside rustup.sh

**Comment by miguelapg** [comment]
Yes, indeed.

I just can fix it from my end manually adding -k to the curl calls in rustup.sh and comment the line ...
```
# log download_rustup curl --proto '=https' --tlsv1.2 "https://sh.rustup.rs" -sSo rustup.sh
```
to avoid getting again a fresh copy of rustup.sh with the same bug

This problem is preventing installing your suite at all

**Comment by 1480c1** [comment]
Could you perhaps file an issue on rustup's side here https://github.com/rust-lang/rustup as well? Perhaps they might know something more about a self-signed cert in their cert chain

**Comment by 1480c1** [comment]
I am currently running a fresh clone before going to sleep, so I will see if it failed in the morning.

**Comment by miguelapg** [comment]
> Could you perhaps file an issue on rustup's side here https://github.com/rust-lang/rustup as well? Perhaps they might know something more about a self-signed cert in their cert chain

Yes, I can of course, but I am not sure I am so skilled to explain the issue to them rightly.

I could explain to them that their curl calls are having problems with their self-signed certificates and in order to run their script I have to add -k to skip the security checking at their curl calls

**Comment by miguelapg** [comment]
> I am currently running a fresh clone before going to sleep, so I will see if it failed in the morning.

Perfect. I am sure you will see it as I did it some minutes ago and I saw it

**Comment by 1480c1** [comment]
That's probably good enough if not, you can tag me by saying
```
/cc @1480c1 
```
and I can try to see if I can respond to their questions if there's any

**Comment by miguelapg** [comment]
> That's probably good enough, if not, you can tag me an issue by saying
> 
> ```
> /cc @1480c1 
> ```
> 
> and I can try to see if I can respond to their questions if there's any

Seems that everything is at their end, but I take note about the tagging

**Comment by miguelapg** [comment]
By the way, if once rustup.sh is downloaded you can manipulate that file and to add -k like the following ...
```
        if [ -n "$_ciphersuites" ]; then
            curl -k --proto '=https' --tlsv1.2 --ciphers "$_ciphersuites" --silent --show-error --fail --location "$1" --output "$2"
        else
            echo "Warning: Not enforcing strong cipher suites for TLS, this is potentially less secure"
            if ! check_help_for "$3" curl --proto --tlsv1.2; then
                echo "Warning: Not enforcing TLS v1.2, this is potentially less secure"
                curl -k --silent --show-error --fail --location "$1" --output "$2"
            else
                curl -k --proto '=https' --tlsv1.2 --silent --show-error --fail --location "$1" --output "$2"
            fi
        fi
```
You can fix the issue, at least temporarily, until they do something

**Comment by 1480c1** [comment]
```none
23:45:01
        Starting 64bit compilation of global tools
23:45:01 ├ Running download_rustup...
23:45:02 ├ Running install_rust...
23:45:53 ├ Stripping...
23:45:54 └ rustinstall  ....................................... [Updated]
23:45:54 ├ Running rustup_update...
23:45:54 ├ Running set_default_toolchain...
23:45:54   Running git clone for libxml2...
```
I didn't get any issues, could you perhaps try on another computer or inside a VM? I'm wondering if something went wrong with your certificate installation

**Comment by miguelapg** [comment]
Ohhh

OK, I am going to try the suite in a virtual machine with windows.

**Comment by miguelapg** [comment]
I didn't need to install the suite in a Virtual Machine with Windows.

The problem was my Kaspersky Total Security 2020 suite.

It was blocking the connection to those servers.

Seems it considered the connection to "https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe" insecure.

I deactivated the Kaspersky protection just for the rustup part and the installation didn't stop and it downloaded "rustup-init.exe" well.

Feel free to think if you find it helpful, so you could add some warning about this in your readme file or not.

**Comment by 1480c1** [comment]
Interesting, I knew about antivirus stuff like windows defender slowing down compilation by a lot (because it's constantly scanning the output of the compilation steps), but I didn't really think about if it was blocking connections to the sources. I guess that will be something to keep in mind in the future.

**Comment by miguelapg** [comment]
> Interesting, I knew about antivirus stuff like windows defender slowing down compilation by a lot (because it's constantly scanning the output of the compilation steps), but I didn't really think about if it was blocking connections to the sources. I guess that will be something to keep in mind in the future.

Kaspersky is also slowing down all the installation process and compilations because it all time scanning everything. Probably all antivirus are doing the same.
