### ISSUE TITLE
[mingw64] [ffmpeg] libsvt patch not applied

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1787]
0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
	Patch could not be applied with `git am`. Continuing without patching.

ffmpeg build succeeds.

[compile.log](https://github.com/m-ab-s/media-autobuild_suite/files/5078452/compile.log)

**Comment by 1480c1** [comment]
linking https://github.com/OpenVisualCloud/SVT-HEVC/pull/572
