### ISSUE TITLE
mingw32 rav1e: installation - file path contains shell syntax elements, wrong escaping?

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1797]
```
┌ rav1e git  ............................................. [Updates found]
├ Running uninstall...
├ Running rust.update...
├ Running rust.build...
├ Running install-rav1e-c...
install: cannot stat 'install-32bit/lib/librav1e.a'$'\n''install-32bit/MABS/local32/lib/librav1e.a': No such file or directory
install: cannot stat 'install-32bit/lib/pkgconfig/rav1e.pc'$'\n''install-32bit/MABS/local32/lib/pkgconfig/rav1e.pc': No such file or directory
install: cannot stat 'install-32bit/include/rav1e'$'\n''install-32bit/MABS/local32/include/rav1e/*.h': No such file or directory
├ /local32/lib/librav1e.a  ................................... [Not found]
└ rav1e-git  .................................................... [Failed]
```

**Comment by LigH-de** [comment]
*According to the recommendation of the suite, I tried to remove **build/rav1e-git** ...*

:flushed: 

*It consumed 35 GB in 81k files. Why?!*

**Comment by wiiaboo** [comment]
Lots of dependencies, I assume.

**Comment by LigH-de** [comment]
After the overhaul and possibly another update in the meantime, the installation was now successful.

**Comment by megapro17** [comment]
> 35 gb

~~Because rust is crap?~~

**Comment by wiiaboo** [comment]
@1480c1 looking at those stat there does seem to be a typo somewhere.

**Comment by moisespr123** [comment]
Deleting the folder and running the suite again fixed it for me too.

**Comment by 1480c1** [comment]
I think that's because i switched to using destdir so the pkgconfig etc is correct, so since the old folder isn't cleaned, we get multiple files

**Comment by 1480c1** [comment]
Oh, you're talking about the file size, that one not sure yet, It's 1.87 GB for me locally, but that's 64-bit only, and after the suite has run

**Comment by wiiaboo** [comment]
I mean this part:

> install: cannot stat 'install-32bit/lib/librav1e.a'$'\n''install-32bit/MABS/local32/lib/librav1e.a': No such file or directory
> install: cannot stat 'install-32bit/lib/pkgconfig/rav1e.pc'$'\n''install-32bit/MABS/local32/lib/pkgconfig/rav1e.pc': No such file or directory
> install: cannot stat 'install-32bit/include/rav1e'$'\n''install-32bit/MABS/local32/include/rav1e/*.h': No such file or directory

**Comment by 1480c1** [comment]
Yeah, that's because of the really simple
```bash
        do_install "$(find "install-$bits/" -name "librav1e.a")" lib/
        do_install "$(find "install-$bits/" -name "rav1e.pc")" lib/pkgconfig/
        do_install "$(find "install-$bits/" -name "rav1e")"/*.h include/rav1e/
```
which finds both the old and the new ones since I changed it to use
```bash
        log "install-rav1e-c" "$RUSTUP_HOME/bin/cargo.exe" capi install \
            --release --jobs "$cpuCount" --prefix="$LOCALDESTDIR" \
            --destdir="$PWD/install-$bits"
```
instead

**Comment by 1480c1** [comment]
Going to close since the issue seems to be "fixed", although it could possibly be remedied if we add `vcs_clean` to `do_vcs` to clean up old build stuff
