### ISSUE TITLE
[mingw64] [ffmpeg] ERROR: openal not found

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#1798]
Commit: https://github.com/m-ab-s/media-autobuild_suite/commit/5f074e91cc431b92bd5b344ac76aa55617e4d6c7

Full error log: https://0x0.st/igUX.zip

Is that openal means openal-soft or not?

> 11:05:04 ┌ ffmpeg git  .................................. [Updates found]
> 11:05:07 ├ Changing options to comply to nonfree...
> FFmpeg and related apps will depend on CUDA SDK to run!
> 11:05:19 ├ Compiling shared FFmpeg...
> 11:05:21 ├ Running uninstall...
> 11:05:24 ├ Running configure...
> Likely error (tail of the failed operation logfile):
> CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
> LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
> ../configure --prefix=/local64 --disable-static --enable-shared --pkg-config-flags=--static --cc=ccache gcc --cxx=ccache g++ --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libsvthevc --enable-libsvtav1 --enable-libsvtvp9 --enable-libkvazaar --enable-libmodplug --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-vapoursynth --enable-libglslang --enable-vulkan --enable-opencl --enable-opengl --enable-libnpp --enable-libopenh264 --enable-openssl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-IC:/PROGRA~1/NVIDIA/CUDA/v11.0/include --extra-ldflags=-LC:/PROGRA~1/NVIDIA/CUDA/v11.0/lib/x64 --prefix=/local64/bin-video/ffmpegSHARED
> ERROR: openal not found
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem.
> configure failed. Check C:/Softwares/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.configure.log
> This is required for other packages, so this script will exit.
> 11:17:14   Creating diagnostics file...
>

**Comment by 1480c1** [comment]
Ah.
