### ISSUE TITLE
Discussion: Use individual PKGBUILD file instead of shell scripts

### ISSUE THREAD

**Issue by Biswa96** [m-ab-s/media-autobuild_suite#1804]
As this repository uses MSYS2/MinGW toolchain, is it possible to add individual PKGBUILD file instead of a gigantic shell scripts to build the programs? It will be easy to manage, review, edit, build and everything.

**Comment by 1480c1** [comment]
I am currently testing out something like using PKGBUILDS in https://github.com/m-ab-s/vlc-autobuild_suite in my free time, but I do realize a few issues, with one being if we are compiling a commonly used package, it's possible it might break compilation in general by breaking gcc or cmake etc.


Although I sort of do want to try to use PKGBUILDS instead, I think it might be hard to do at least immediately

**Comment by wiiaboo** [comment]
I'd thought of this some years ago, but figured it was too painful for little gain.

**Comment by Biswa96** [comment]
> I do realize it has a few issues

Ready to listen those 😊

**Comment by 1480c1** [comment]
@Biswa96 do you happen to know a way to make makepkg not modify the pkgver and rel automatically for -git packages?

**Comment by Biswa96** [comment]
Though I have not tried it. How about not adding pkgver function? But changing pkgver is good practice for VCS packages (e.g. git, svn, hg etc.) Also the pkgver could be make as the timestamp of last commit + shallow clone.

**Comment by 1480c1** [comment]
Hmm, I mainly had a pkgver function because it was mentioned in arch's wiki and also in the -git packages in MINGW-packages, but I guess maybe it might be better to do it a different way

**Comment by wiiaboo** [comment]
This is pointless, IMO. If you want something like Arch's AUR, just use it.
We're not going to port everything to PKGBUILD files just for users that want to "makepkg" things magically.
What, will we need to reinvent AUR helpers too?

The only benefit in switching to makepkg would be to create a repository of built binaries where users would just download updated binaries when they want, and for that, why not just use MSYS2/MINGW/Chocolatey?

**Comment by Biswa96** [comment]
OK. Understood. Thanks for the discussion.
