### ISSUE TITLE
Request: Provide pdb files when building and/or provide debug builds for ffmpeg?

### ISSUE THREAD

**Issue by sdcb** [m-ab-s/media-autobuild_suite#1805]
I think debug build and pdb is pretty useful especially when debugging some code.

I did see there is some ffmpeg pdb in `AMF-git` folder, so I guess it's possible, (but the version is low `4.1.3`)
`C:\_\3rd\ffmpeg-build\build\AMF-git\Thirdparty\ffmpeg\ffmpeg-4.1.3\x64\release\bin\avformat-58.pdb`

**Comment by 1480c1** [comment]
Since we don't use msvc, we can't produce pdb, you could instead use gdb with the ffmpeg_g binary for some basic debugging

**Comment by 1480c1** [comment]
We could try adding a debug build option by adding `-g` to the cflags, but i have never tested it

**Comment by 1480c1** [comment]
Marking this specific issue as closed since we can't provide pdbs, but you can use gdb or lldb to do debugging

**Comment by 1480c1** [comment]
This might be of interest to you, but I do not have experience using it at all https://github.com/rainers/cv2pdb

**Comment by sdcb** [comment]
Thanks, I'm investigating the vcpkg.
