### ISSUE TITLE
[mingw64] [ffmpeg] Latest decklink changes broke building

### ISSUE THREAD

**Issue by BlackScreen** [m-ab-s/media-autobuild_suite#1808]
The latest decklink changes in FFmpeg in the last 24 hours seem to have broken the building of FFmpeg...

```
10:56:19   Running git update for ffmpeg...
10:56:21 ┌ ffmpeg git  .................................. [Updates found]
10:56:21 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
10:56:28 ├ Compiling static FFmpeg...
10:56:29 ├ Running uninstall...
10:56:30 ├ Running configure...
11:02:29 ├ Running make...
Likely error (tail of the failed operation logfile):
      |                     ^~~~~~~~~~~~~~~~~~~~
C:/Development/MABS_All/build/ffmpeg-git/libavdevice/decklink_dec.cpp: In member function 'virtual ULONG decklink_input_callback::Release()':
C:/Development/MABS_All/build/ffmpeg-git/libavdevice/decklink_dec.cpp:734:9: warning: deleting object of polymorphic class type 'decklink_input_callback' which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
  734 |         delete this;
      |         ^~~~~~~~~~~
C:/Development/MABS_All/build/ffmpeg-git/libavdevice/decklink_dec.cpp: In function 'int ff_decklink_read_header(AVFormatContext*)':
C:/Development/MABS_All/build/ffmpeg-git/libavdevice/decklink_dec.cpp:1235:28: error: 'bmdFormatUnspecified' was not declared in this scope
 1235 |     if (ctx->raw_format == bmdFormatUnspecified)
      |                            ^~~~~~~~~~~~~~~~~~~~
make: *** [/build/ffmpeg-git/ffbuild/common.mak:70: libavdevice/decklink_dec.o] Error 1
make failed. Check C:/Development/MABS_All/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
11:02:53   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iI2m.zip
Copy and paste [logs.zip](https://0x0.st/iI2m.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

**Comment by GyanD** [comment]
Will be reviewed on the ffmpeg devel mailing list.

**Comment by wiiaboo** [comment]
Can you check with 11.6 which I've just updated?

**Comment by hamwong** [comment]
HI, I try encode again and I got difference error this time,

`07:59:13(B   Running git update for ffmpeg...
07:59:17(B ┌ ffmpeg git (B .................................. [Updates found(B]
07:59:17(B ├(B Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK to run!(B
07:59:32(B ├(B Compiling static(B FFmpeg...
07:59:36(B ├(B Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --cc=ccache clang --cxx=ccache clang++ --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libsvthevc --enable-libsvtvp9 --enable-libkvazaar --enable-libmodplug --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-libglslang --enable-vulkan --enable-opencl --enable-opengl --enable-libnpp --enable-libopenh264 --enable-openssl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-IC:/PROGRA~1/NVIDIA~2/CUDA/v11.0/include --extra-ldflags=-LC:/PROGRA~1/NVIDIA~2/CUDA/v11.0/lib/x64 --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-IC:/media-autobuild_suite-master/local64/include/AL --extra-version=g05c8d0bce6+3
ERROR: tesseract not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check C:/media-autobuild_suite-master/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log(B
This is required for other packages, so this script will exit.(B
08:06:36(B   Creating diagnostics file...
`

**Comment by hamwong** [comment]
I have success build after set #--enable-libtesseract in ffmpeg_options.txt

**Comment by GyanD** [comment]
The issue for this suite is moot but the fix will be applied likely today.

**Comment by BlackScreen** [comment]
> Can you check with 11.6 which I've just updated?
I ran the suite again just now, and it is working again. Thanks!
