### ISSUE TITLE
libavif error while buidling.

### ISSUE THREAD

**Issue by Steph55** [m-ab-s/media-autobuild_suite#1812]
I was building 64-bit version. Here is the log:

[logs.zip](https://0x0.st/iIko.zip)

Thank you for your help!

**Comment by Steph55** [comment]
PS: The error message was that it failed to find JPEG (missing JPEG_LIBRARY JPEG_INCLUDE_DIR)

**Comment by 1480c1** [comment]
Could you try again after pulling the latest suite?
