### ISSUE TITLE
make 32-bit ffmpeg failed: undefined reference to `ff_parse_a53_cc'

### ISSUE THREAD

**Issue by Rollinnn** [m-ab-s/media-autobuild_suite#1814]
Starting 32bit compilation of video tools(B(B
  Running git update for ffmpeg...
┌ ffmpeg git (B ......................................... [Recently updated(B]
├(B Changing options to comply to lgpl...
├(B Compiling shared(B FFmpeg...
├(B Running configure...
├(B Running make...
Likely error (tail of the failed operation logfile):
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/ffbuild/library.mak:103: libavcodec/avcodec-58.dll] Error 1
EXTERN_PREFIX="_" AR="ar" NM="nm -g" /build/ffmpeg-git/compat/windows/makedef libavcodec/libavcodec.ver libavcodec/8svx.o libavcodec/aac_ac3_parser.o libavcodec/aac_adtstoasc_bsf.o libavcodec/aac_parser.o libavcodec/aacdec.o libavcodec/aacdec_fixed.o libavcodec/aacps_fixed.o libavcodec/aacps_float.o libavcodec/aacpsdsp_fixed.o libavcodec/aacpsdsp_float.o libavcodec/aacsbr.o libavcodec/aacsbr_fixed.o libavcodec/aactab.o libavcodec/ac3.o libavcodec/ac3_parser.o libavcodec/ac3dec_data.o libavcodec/ac3dec_fixed.o libavcodec/ac3dec_float.o libavcodec/ac3dsp.o libavcodec/ac3tab.o libavcodec/acelp_filters.o libavcodec/acelp_pitch_delay.o libavcodec/acelp_vectors.o libavcodec/adpcm.o libavcodec/adpcm_data.o libavcodec/adpcmenc.o libavcodec/adts_header.o libavcodec/adts_parser.o libavcodec/adx.o libavcodec/adx_parser.o libavcodec/adxdec.o libavcodec/alac.o libavcodec/alac_data.o libavcodec/alacdsp.o libavcodec/allcodecs.o libavcodec/alsdec.o libavcodec/amrnbdec.o libavcodec/amrwbdec.o libavcodec/apedec.o libavcodec/aptx.o libavcodec/aptxdec.o libavcodec/atrac.o libavcodec/atrac1.o libavcodec/atrac3.o libavcodec/atrac3plus.o libavcodec/atrac3plusdec.o libavcodec/atrac3plusdsp.o libavcodec/atrac9dec.o libavcodec/audio_frame_queue.o libavcodec/audiodsp.o libavcodec/av1_frame_merge_bsf.o libavcodec/av1_frame_split_bsf.o libavcodec/av1_metadata_bsf.o libavcodec/av1_parse.o libavcodec/av1_parser.o libavcodec/av1dec.o libavcodec/avdct.o libavcodec/avfft.o libavcodec/avpacket.o libavcodec/avpicture.o libavcodec/avs2_parser.o libavcodec/bgmc.o libavcodec/binkaudio.o libavcodec/bitstream.o libavcodec/bitstream_filter.o libavcodec/bitstream_filters.o libavcodec/blockdsp.o libavcodec/bmp_parser.o libavcodec/bmvaudio.o libavcodec/bsf.o libavcodec/bswapdsp.o libavcodec/cavs_parser.o libavcodec/cbrt_data.o libavcodec/cbrt_data_fixed.o libavcodec/cbs.o libavcodec/cbs_av1.o libavcodec/cbs_h2645.o libavcodec/cbs_mpeg2.o libavcodec/cbs_vp9.o libavcodec/celp_filters.o libavcodec/celp_math.o libavcodec/cfhddata.o libavcodec/cfhdenc.o libavcodec/chomp_bsf.o libavcodec/cngdec.o libavcodec/codec2utils.o libavcodec/codec_desc.o libavcodec/cook.o libavcodec/cook_parser.o libavcodec/d3d11va.o libavcodec/dca.o libavcodec/dca_core.o libavcodec/dca_core_bsf.o libavcodec/dca_exss.o libavcodec/dca_lbr.o libavcodec/dca_parser.o libavcodec/dca_xll.o libavcodec/dcadata.o libavcodec/dcadct.o libavcodec/dcadec.o libavcodec/dcadsp.o libavcodec/dcahuff.o libavcodec/dct.o libavcodec/dct32_fixed.o libavcodec/dct32_float.o libavcodec/decode.o libavcodec/dirac.o libavcodec/dirac_parser.o libavcodec/dnxhd_parser.o libavcodec/dnxhddata.o libavcodec/dolby_e.o libavcodec/dpcm.o libavcodec/dpx_parser.o libavcodec/dsd.o libavcodec/dsddec.o libavcodec/dsicinaudio.o libavcodec/dss_sp.o libavcodec/dstdec.o libavcodec/dump_extradata_bsf.o libavcodec/dv_profile.o libavcodec/dvaudio_parser.o libavcodec/dvaudiodec.o libavcodec/dvbsub_parser.o libavcodec/dvd_nav_parser.o libavcodec/dvdsub_parser.o libavcodec/eac3_core_bsf.o libavcodec/eac3_data.o libavcodec/encode.o libavcodec/error_resilience.o libavcodec/evrcdec.o libavcodec/exif.o libavcodec/extract_extradata_bsf.o libavcodec/faandct.o libavcodec/faanidct.o libavcodec/fastaudio.o libavcodec/fdctdsp.o libavcodec/fft_fixed.o libavcodec/fft_fixed_32.o libavcodec/fft_float.o libavcodec/fft_init_table.o libavcodec/ffwavesynth.o libavcodec/filter_units_bsf.o libavcodec/fits.o libavcodec/flac.o libavcodec/flac_parser.o libavcodec/flacdata.o libavcodec/flacdec.o libavcodec/flacdsp.o libavcodec/fmtconvert.o libavcodec/frame_thread_encoder.o libavcodec/g722.o libavcodec/g722dec.o libavcodec/g722dsp.o libavcodec/g723_1.o libavcodec/g723_1_parser.o libavcodec/g723_1dec.o libavcodec/g726.o libavcodec/g729_parser.o libavcodec/g729dec.o libavcodec/g729postfilter.o libavcodec/gif_parser.o libavcodec/golomb.o libavcodec/gsm_parser.o libavcodec/gsmdec.o libavcodec/gsmdec_data.o libavcodec/h261_parser.o libavcodec/h263.o libavcodec/h263_parser.o libavcodec/h263data.o libavcodec/h263dec.o libavcodec/h263dsp.o libavcodec/h2645_parse.o libavcodec/h264_levels.o libavcodec/h264_metadata_bsf.o libavcodec/h264_mp4toannexb_bsf.o libavcodec/h264_parse.o libavcodec/h264_parser.o libavcodec/h264_ps.o libavcodec/h264_redundant_pps_bsf.o libavcodec/h264_sei.o libavcodec/h264chroma.o libavcodec/h264data.o libavcodec/h264dsp.o libavcodec/h264idct.o libavcodec/h265_metadata_bsf.o libavcodec/h265_profile_level.o libavcodec/hap.o libavcodec/hapqa_extract_bsf.o libavcodec/hcadec.o libavcodec/hcom.o libavcodec/hevc_data.o libavcodec/hevc_mp4toannexb_bsf.o libavcodec/hevc_parse.o libavcodec/hevc_parser.o libavcodec/hevc_ps.o libavcodec/hevc_sei.o libavcodec/hpeldsp.o libavcodec/idctdsp.o libavcodec/ilbcdec.o libavcodec/imc.o libavcodec/imgconvert.o libavcodec/imx_dump_header_bsf.o libavcodec/interplayacm.o libavcodec/ituh263dec.o libavcodec/jfdctfst.o libavcodec/jfdctint.o libavcodec/jni.o libavcodec/jpeg2000_parser.o libavcodec/jpegtables.o libavcodec/jrevdct.o libavcodec/kbdwin.o libavcodec/latm_parser.o libavcodec/log2_tab.o libavcodec/lossless_audiodsp.o libavcodec/lsp.o libavcodec/mace.o libavcodec/mathtables.o libavcodec/mdct15.o libavcodec/mdct_fixed.o libavcodec/mdct_fixed_32.o libavcodec/mdct_float.o libavcodec/me_cmp.o libavcodec/mediacodec.o libavcodec/metasound.o libavcodec/metasound_data.o libavcodec/mjpeg2jpeg_bsf.o libavcodec/mjpeg_parser.o libavcodec/mjpega_dump_header_bsf.o libavcodec/mjpegenc_huffman.o libavcodec/mlp.o libavcodec/mlp_parse.o libavcodec/mlp_parser.o libavcodec/mlpdec.o libavcodec/mlpdsp.o libavcodec/mlz.o libavcodec/mobiclip.o libavcodec/movsub_bsf.o libavcodec/mp3_header_decompress_bsf.o libavcodec/mpc.o libavcodec/mpc7.o libavcodec/mpc8.o libavcodec/mpeg12.o libavcodec/mpeg12data.o libavcodec/mpeg12framerate.o libavcodec/mpeg2_metadata_bsf.o libavcodec/mpeg4_unpack_bframes_bsf.o libavcodec/mpeg4audio.o libavcodec/mpeg4video.o libavcodec/mpeg4video_parser.o libavcodec/mpeg4videodec.o libavcodec/mpeg_er.o libavcodec/mpegaudio.o libavcodec/mpegaudio_parser.o libavcodec/mpegaudiodata.o libavcodec/mpegaudiodec_fixed.o libavcodec/mpegaudiodec_float.o libavcodec/mpegaudiodecheader.o libavcodec/mpegaudiodsp.o libavcodec/mpegaudiodsp_data.o libavcodec/mpegaudiodsp_fixed.o libavcodec/mpegaudiodsp_float.o libavcodec/mpegpicture.o libavcodec/mpegutils.o libavcodec/mpegvideo.o libavcodec/mpegvideo_motion.o libavcodec/mpegvideo_parser.o libavcodec/mpegvideodata.o libavcodec/mpegvideodsp.o libavcodec/msgsmdec.o libavcodec/nellymoser.o libavcodec/nellymoserdec.o libavcodec/noise_bsf.o libavcodec/null_bsf.o libavcodec/on2avc.o libavcodec/on2avcdata.o libavcodec/options.o libavcodec/opus.o libavcodec/opus_celt.o libavcodec/opus_metadata_bsf.o libavcodec/opus_parser.o libavcodec/opus_pvq.o libavcodec/opus_rc.o libavcodec/opus_silk.o libavcodec/opusdec.o libavcodec/opusdsp.o libavcodec/opustab.o libavcodec/pafaudio.o libavcodec/parser.o libavcodec/parsers.o libavcodec/pcm-bluray.o libavcodec/pcm-dvd.o libavcodec/pcm.o libavcodec/pcm_rechunk_bsf.o libavcodec/photocd.o libavcodec/pixblockdsp.o libavcodec/png_parser.o libavcodec/pnm.o libavcodec/pnm_parser.o libavcodec/profiles.o libavcodec/prores_metadata_bsf.o libavcodec/pthread.o libavcodec/pthread_frame.o libavcodec/pthread_slice.o libavcodec/qcelpdec.o libavcodec/qdm2.o libavcodec/qdmc.o libavcodec/qpeldsp.o libavcodec/qsv_api.o libavcodec/ra144.o libavcodec/ra144dec.o libavcodec/ra288.o libavcodec/ralf.o libavcodec/rangecoder.o libavcodec/raw.o libavcodec/rdft.o libavcodec/remove_extradata_bsf.o libavcodec/reverse.o libavcodec/rl.o libavcodec/rpzaenc.o libavcodec/rv34_parser.o libavcodec/s302m.o libavcodec/sbc.o libavcodec/sbc_parser.o libavcodec/sbcdec.o libavcodec/sbcdec_data.o libavcodec/sbrdsp.o libavcodec/sbrdsp_fixed.o libavcodec/shorten.o libavcodec/simple_idct.o libavcodec/sinewin.o libavcodec/sinewin_fixed.o libavcodec/sipr.o libavcodec/sipr16k.o libavcodec/sipr_parser.o libavcodec/siren.o libavcodec/smacker.o libavcodec/sonic.o libavcodec/startcode.o libavcodec/synth_filter.o libavcodec/tak.o libavcodec/tak_parser.o libavcodec/takdec.o libavcodec/takdsp.o libavcodec/tiff_common.o libavcodec/trace_headers_bsf.o libavcodec/truehd_core_bsf.o libavcodec/truespeech.o libavcodec/tta.o libavcodec/ttadata.o libavcodec/ttadsp.o libavcodec/twinvq.o libavcodec/twinvqdec.o libavcodec/utils.o libavcodec/vc1.o libavcodec/vc1_parser.o libavcodec/vc1data.o libavcodec/vc1dsp.o libavcodec/videodsp.o libavcodec/vima.o libavcodec/vmdaudio.o libavcodec/vorbis.o libavcodec/vorbis_data.o libavcodec/vorbis_parser.o libavcodec/vorbisdec.o libavcodec/vorbisdsp.o libavcodec/vp3_parser.o libavcodec/vp8_parser.o libavcodec/vp9_metadata_bsf.o libavcodec/vp9_parser.o libavcodec/vp9_raw_reorder_bsf.o libavcodec/vp9_superframe_bsf.o libavcodec/vp9_superframe_split_bsf.o libavcodec/wavpack.o libavcodec/webp_parser.o libavcodec/wma.o libavcodec/wma_common.o libavcodec/wma_freqs.o libavcodec/wmadec.o libavcodec/wmalosslessdec.o libavcodec/wmaprodec.o libavcodec/wmavoice.o libavcodec/wmv2data.o libavcodec/ws-snd1.o libavcodec/x86/aacpsdsp.o libavcodec/x86/aacpsdsp_init.o libavcodec/x86/ac3dsp.o libavcodec/x86/ac3dsp_downmix.o libavcodec/x86/ac3dsp_init.o libavcodec/x86/alacdsp.o libavcodec/x86/alacdsp_init.o libavcodec/x86/audiodsp.o libavcodec/x86/audiodsp_init.o libavcodec/x86/blockdsp.o libavcodec/x86/blockdsp_init.o libavcodec/x86/bswapdsp.o libavcodec/x86/bswapdsp_init.o libavcodec/x86/constants.o libavcodec/x86/dcadsp.o libavcodec/x86/dcadsp_init.o libavcodec/x86/dct32.o libavcodec/x86/dct_init.o libavcodec/x86/fdct.o libavcodec/x86/fdctdsp_init.o libavcodec/x86/fft.o libavcodec/x86/fft_init.o libavcodec/x86/flacdsp.o libavcodec/x86/flacdsp_init.o libavcodec/x86/fmtconvert.o libavcodec/x86/fmtconvert_init.o libavcodec/x86/fpel.o libavcodec/x86/g722dsp.o libavcodec/x86/g722dsp_init.o libavcodec/x86/h263_loopfilter.o libavcodec/x86/h263dsp_init.o libavcodec/x86/h264_chromamc.o libavcodec/x86/h264_chromamc_10bit.o libavcodec/x86/h264_deblock.o libavcodec/x86/h264_deblock_10bit.o libavcodec/x86/h264_idct.o libavcodec/x86/h264_idct_10bit.o libavcodec/x86/h264_weight.o libavcodec/x86/h264_weight_10bit.o libavcodec/x86/h264chroma_init.o libavcodec/x86/h264dsp_init.o libavcodec/x86/hpeldsp.o libavcodec/x86/hpeldsp_init.o libavcodec/x86/idctdsp.o libavcodec/x86/idctdsp_init.o libavcodec/x86/imdct36.o libavcodec/x86/lossless_audiodsp.o libavcodec/x86/lossless_audiodsp_init.o libavcodec/x86/mdct15.o libavcodec/x86/mdct15_init.o libavcodec/x86/me_cmp.o libavcodec/x86/me_cmp_init.o libavcodec/x86/mlpdsp.o libavcodec/x86/mlpdsp_init.o libavcodec/x86/mpegaudiodsp.o libavcodec/x86/mpegvideo.o libavcodec/x86/mpegvideodsp.o libavcodec/x86/opusdsp.o libavcodec/x86/opusdsp_init.o libavcodec/x86/pixblockdsp.o libavcodec/x86/pixblockdsp_init.o libavcodec/x86/qpel.o libavcodec/x86/qpeldsp.o libavcodec/x86/qpeldsp_init.o libavcodec/x86/sbrdsp.o libavcodec/x86/sbrdsp_init.o libavcodec/x86/simple_idct.o libavcodec/x86/simple_idct10.o libavcodec/x86/synth_filter.o libavcodec/x86/synth_filter_init.o libavcodec/x86/takdsp.o libavcodec/x86/takdsp_init.o libavcodec/x86/ttadsp.o libavcodec/x86/ttadsp_init.o libavcodec/x86/vc1dsp_init.o libavcodec/x86/vc1dsp_loopfilter.o libavcodec/x86/vc1dsp_mc.o libavcodec/x86/vc1dsp_mmx.o libavcodec/x86/videodsp.o libavcodec/x86/videodsp_init.o libavcodec/x86/vorbisdsp.o libavcodec/x86/vorbisdsp_init.o libavcodec/xiph.o libavcodec/xma_parser.o > libavcodec/avcodec-58.def
LD	libavcodec/avcodec-58.dll
C:/1/1/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: libavcodec/h264_sei.o: in function `decode_registered_user_data_closed_caption':
C:/1/1/build/ffmpeg-git/libavcodec/h264_sei.c:180: undefined reference to `ff_parse_a53_cc'
C:/1/1/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: libavcodec/hevc_sei.o: in function `decode_registered_user_data_closed_caption':
C:/1/1/build/ffmpeg-git/libavcodec/hevc_sei.c:173: undefined reference to `ff_parse_a53_cc'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/ffbuild/library.mak:103: libavcodec/avcodec-58.dll] Error 1
make failed. Check C:/1/1/build/ffmpeg-git/build-shared-32bit/ab-suite.make.log(B
This is required for other packages, so this script will exit.(B

**Comment by 1480c1** [comment]
We need the whole log, else this is considered invalid

**Comment by Rollinnn** [comment]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5248332/logs.zip)

**Comment by 1480c1** [comment]
why did you disable so many decoders?

**Comment by Rollinnn** [comment]
I'm trying to create ultra light build for audio decoding only. There was no problems with it ~2-3 months ago.

**Comment by Rollinnn** [comment]
Can this somehow be connected with this patch - http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=1ab3ae6fd5b1866aa42cfc0c5d79700adb7281d8 ?

**Comment by 1480c1** [comment]
you probably might want to add
```none
--disable-parser=h264_parser
--disable-parser=hevc_parser
```
to your ffmpeg_options.txt

as an after I wrote this part, yes

**Comment by 1480c1** [comment]
you might want to instead go backwards and do disable everything and only enable the stuff you need, if you know what you need at least

**Comment by 1480c1** [comment]
Like getting the output of `--list-demuxers` etc and then choosing the stuff you need

**Comment by Rollinnn** [comment]
Disabling parsers didn't help. I'll try to disable everything.

**Comment by wiiaboo** [comment]
Either way this will be likely a ffmpeg-reproducible issue, so they'll want to know about uncaught dependencies.
But do start with --disable-everything and then enabling what you need.

**Comment by 1480c1** [comment]
http://ffmpeg.org/pipermail/ffmpeg-devel/2020-September/270088.html maybe related
