### ISSUE TITLE
mv: cannot stat '': No such file or directory

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1816]
Hi

Got this now after i updated the suite to the latest version

        Starting 32bit compilation of audio tools
mv: cannot stat '': No such file or directory
mv: cannot stat '': No such file or directory
mv: cannot stat '': No such file or directory
mv: cannot stat '': No such file or directory
mv: cannot stat '': No such file or directory
mv: cannot stat '': No such file or directory

**Comment by 1480c1** [comment]
repull https://github.com/m-ab-s/media-autobuild_suite/commit/7b221dcfea1cb35d1ffe3567fea196dac09b063d

**Comment by Barough** [comment]
That fixed it. :)
