### ISSUE TITLE
[QUESTION] rav1e & SVT-AV1 compiles without me selected the suite to do that.

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1817]
Hi

I have a fresh 'setup' of the suite and for some wierd reason so does it compile rav1e & SVT-AV1. I haven't set the suite to compile those two. This suite setup is NOT set to compile ffmpeg.

**Comment by 1480c1** [comment]
For svt-av1, the only checks are
```bash
{ [[ $svtav1 = y ]] || enabled libsvtav1; }
```
for rav1e, it's
```bash
{ [[ $rav1e = y ]] || [[ $libavif = y ]] || enabled librav1e; }
```
You might want to check your ffmpeg_options.txt and see if making is empty will make it not compile those two, and also check if you have libavif enabled as well

**Comment by Barough** [comment]
I dont have a ffmpeg_options.txt file and libavif is not enabled

**Comment by 1480c1** [comment]
What did you select for `Choose ffmpeg and mpv optional libraries?`?

**Comment by Barough** [comment]
[compiler list] 
arch=1
license2=1
standalone=1
vpx2=2
aom=2
rav1e=2
dav1d=2
libavif=2
x2643=1
x2652=1
other265=2
svthevc=2
xvc=2
vvc=2
svtav1=2
svtvp9=2
flac=1
fdkaac=1
faac=2
exhale=1
mediainfo=2
soxB=1
ffmpegB2=2
ffmpegUpdate=1
ffmpegChoice=3
mp4box=1
rtmpdump=2
mplayer2=2
mpv=2
vlc=2
bmx=2
curl=2
ffmbc=2
cyanrip2=2
redshift=2
ripgrep=2
jq=2
jo=2
dssim=2
avs2=2
CC=2
cores=4
deleteSource=1
strip=1
pack=2
logging=1
updateSuite=1
timeStamp=2
ccache=1
noMintty=2

**Comment by 1480c1** [comment]
ffmpegChoice=3 implies zeranoe, which implies `librav1e` and `libsvta1`

**Comment by 1480c1** [comment]
You probably should choose 2 instead or just 1 and delete all of the enables

**Comment by Barough** [comment]
I removed the 'media-autobuild_suite.ini' file and started over. Now everything works fine.
Thnx for the help/input. :)
