### ISSUE TITLE
Where or how to use MSYS2

### ISSUE THREAD

**Issue by cristofayre** [m-ab-s/media-autobuild_suite#1821]
I am a newbie to to this 'compiling' game, and know nothing of how to use GIT and all its files.

I ran the installer, got all the way through to the compile section ... and then it failed asking me to manually install MSYS2, and place into media-app folder. So I downloaded it, placed it in folder ... and Powershell crashes at the REM "download and install basic msys2 system" (line 1395)

I have placed it in the "media-autobuild-suite-master" folder, updated the files with 'pacman -Syu' and 'pacman -Su' ... and batch file won't budge past the REM

I installed in in "C" drive, updated files ... and batch file won't budge past REM, (stalling Powershell each time)

Should the files be in a MSYS2 folder, or files within there place where the batch file is? I tried it in the build folder. Nothing!

m-a-s/
..
.
m-a-s.bat
msys2/

At present, I have ffmpeg / ffprobe / ffplay as 64mb exe in a folder that can be moved to other locations. I, HOPING  to create a similar exe, but without the 'bloat' (one ffmpeg - audio extraction only - file seen recently was 346kb) All I require is MP4 / Ogg video and the ssa and srt subtitling filters

**Comment by 1480c1** [comment]
![image](https://user-images.githubusercontent.com/8345542/94579088-0d578700-023e-11eb-8c1c-3b5f421cfb83.png)
your `media-autobuild-suite-master` folder should contain a build folder, msys64 (the extracted msys2) folder, and the media-autobuild_suite.bat file, those are the only ones that are necessary to the suite

**Comment by 1480c1** [comment]
btw, does your powershell not work?

**Comment by 1480c1** [comment]
I'm going to assume it's fixed bc it's been over a week with no response
