### ISSUE TITLE
Decklink functions in FFmpeg not working anymore

### ISSUE THREAD

**Issue by BlackScreen** [m-ab-s/media-autobuild_suite#1824]
Hey guys,

I just found out, that my most recent builds (from today) do not work with basic decklink functions in FFmpeg.
Sadly I do not keep all of my builds, but I have one from September 8th - there the functions are working.

Output of **"ffmpeg -hide_banner -sources decklink"** with a decklink in my computer and the latest build:

```
Auto-detected sources for decklink:
```

It should look like this - from the build from September 8th:

```
Auto-detected sources for decklink:
  73:18622632:00000000 [DeckLink 4K Extreme 12G]
```

When this basic function is not working, none of them are.
Do you have any idea why that could be? Thank you for your help.

**Comment by wiiaboo** [comment]
I updated decklink headers to the latest SDK: https://notabug.org/RiCON/decklink-headers/commits/master

Try clamping it to the commit before (#commit=efb287366b) and forcing recompilation of ffmpeg if it fixes anything.
If not, it might be a FFmpeg issue.

**Comment by BlackScreen** [comment]
Will test this next week, thanks for your fast answer.

**Comment by BlackScreen** [comment]
Replaced the URL in line 1366 of "media-suite_compile.sh" with this "https://gitlab.com/media-autobuild_suite-dependencies/decklink-headers.git#commit=efb287366b^".
I could compile successfully and could also successfully use the decklink functions again.
Will you revert the new commits then or should i clamp to this commit?

**Comment by BlackScreen** [comment]
@wiiaboo Any news on this? Have you had time to look into it?

**Comment by wiiaboo** [comment]
I think I forgot about your last answer. I can revert it, sure, but what happens then? The SDK won't ever be updated again?

**Comment by BlackScreen** [comment]
I have no idea. Could it be a problem that FFmpeg devs have to solve? 🤔

**Comment by wiiaboo** [comment]
Try notifying either whoever has been updating decklink in FFmpeg to see if they have a Windows machine and a Decklink device, if they can reproduce the problem, or maybe also Decklink themselves. MinGW in Windows is probably not really officially supported, but it's always worth a try.

Meanwhile, I can clamp the commit in the suite.

**Comment by BlackScreen** [comment]
Ok. Perfect. Thanks!
I will open an issue with FFmpeg and hope this brings light to this issue.

**Comment by 1480c1** [comment]
Going to mark this as not-our-bug for now, at least if we consider the main issue being latest FFmpeg doesn't work with latest decklink on windows, but won't close until we get confirmation it might work?

**Comment by BlackScreen** [comment]
I opened a ticket at FFmpeg: https://trac.ffmpeg.org/ticket/8923
Meanwhile it would be great to revert the SDK changes, I think.

**Comment by 1480c1** [comment]
Already clamped https://github.com/m-ab-s/media-autobuild_suite/commit/f79c4bca374c567718f9bb6be23402c86512aa0f

**Comment by wiiaboo** [comment]
You'll need to manually delete the decklink headers to force "recompilation".
`do_vcs` still doesn't properly refresh with clamps.

**Comment by BlackScreen** [comment]
Thanks for clamping the headers. Meanwhile let's hope for a solution at FFmpeg. :)

**Comment by BlackScreen** [comment]
Ok, this is embarassing, I had not updated the Decklink drivers to 11.6.
After I did this, it works as expected. So a big sorry from my side. No clamping necessary, just updating the drivers is enough. :/

**Comment by wiiaboo** [comment]
Cool. I'll unclamp then.
