### ISSUE TITLE
libwavpack deleted from FFmpeg configure options

### ISSUE THREAD

**Issue by paulpacifico** [m-ab-s/media-autobuild_suite#1826]
Hello, 
Just to inform that `--enable-libwavpack` is no more used for FFmpeg configuration.

More info here:
https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/45070eec4c089b06947f07e25cdb1bc8b2102553

Paul.

**Comment by wiiaboo** [comment]
https://github.com/m-ab-s/media-autobuild_suite/issues/1825
