### ISSUE TITLE
[mingw32|mingw64] [repo] several errors cannot update, repo.msys2.org times out

### ISSUE THREAD

**Issue by moob158** [m-ab-s/media-autobuild_suite#1827]
[mingw32|mingw64] [repo] several errors

![Capturar](https://user-images.githubusercontent.com/60049180/95025219-0e464980-0680-11eb-9e88-58838311c518.PNG)

![Capturar](https://user-images.githubusercontent.com/60049180/95025290-7dbc3900-0680-11eb-8ba7-b88841132e4c.PNG)

**Comment by 1480c1** [comment]
https://github.com/msys2/MINGW-packages/issues/7084
https://github.com/msys2/MSYS2-packages/issues/2171

**Comment by wiiaboo** [comment]
repo.msys2.org is down, so it's trying the next mirror. Those aren't errors, it's working as it's supposed to.

**Comment by wiiaboo** [comment]
You can temporarily silence the downed mirror by commenting the line with that mirror in the files in /msys64/etc/pacman.d/mirrorlist.*

You can also run this on mintty:
```bash
sed -ir 's;.*repo.msys2.org;#&;g' /etc/pacman.d/mirrorlist.m*
```

**Comment by moob158** [comment]
I'm new at this, I just execute the bat file and follow the instructions.

where can i change the url mirror? is in the bat file?

**Comment by Barough** [comment]
> I'm I'm newbie at this at this, I just execute the bat file and follow the instructions.
> 
> ok I get it. thanks @wiiaboo

https://github.com/m-ab-s/media-autobuild_suite/issues/1751#issuecomment-660157709

**Comment by 1480c1** [comment]
as an aside, I am testing adding
```bash

cat <<'EOF'
-------------------------------------------------------------------------------
Running rankmirrors
"-------------------------------------------------------------------------------"
EOF

for list in mingw{32,64} msys; do
    cp /etc/pacman.d/mirrorlist.$list{,.orig}
    rankmirrors -r $list -v /etc/pacman.d/mirrorlist.$list.orig > /etc/pacman.d/mirrorlist.$list
done
```
to the update script so it will get the best mirror regardless, only issue I think it might have is the sf mirror is known to be very behind since it's already full.
