### ISSUE TITLE
Request: Enable stdin as default input in xvid_encraw

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1829]
The help output of **xvid_encraw** promises that the default input is **stdin** if the `-i` parameter is omitted. But the source is incomplete, it does not work this way when compiled under Windows. Was discussed in the [doom9 forum](https://forum.doom9.org/showthread.php?t=181894) by @Selur – and @Kurtnoise published a patched version.

Here is a diff patch comparing Kurtnoise's source with the official xvid 1.3.7, including the 8192 zones `sed` which was applied in **media-suite_compile.sh** already (and a few spacing cosmetics which happened while editing).

```
Index: xvidcore/examples/xvid_encraw.c
===================================================================
--- xvidcore/examples/xvid_encraw.c	(revision 2196)
+++ xvidcore/examples/xvid_encraw.c	(working copy)
@@ -38,6 +38,16 @@
  *  Use ./xvid_encraw -help for a list of options
  *	
  ************************************************************************/
+#ifdef _WIN32
+/* The following two defines must be located before the inclusion of any system header files. */
+#define WINVER       0x0500
+#define _WIN32_WINNT 0x0500
+#include <windows.h>
+#include <io.h>       /* _setmode() */
+#include <fcntl.h>    /* _O_BINARY */
+#endif
 
 #include <stdio.h>
 #include <stdlib.h>
@@ -124,7 +134,7 @@
  *                     Command line global variables
  ****************************************************************************/
 
-#define MAX_ZONES   64
+#define MAX_ZONES   8192
 #define MAX_ENC_INSTANCES 4
 #define MAX_XDIM 4096
 #define MAX_YDIM 4096
@@ -350,6 +360,7 @@
 	double totalenctime = 0.;
 	float totalPSNR[3] = {0., 0., 0.};
 
+	FILE *in_file = stdin;
 	FILE *statsfile;
 	frame_stats_t framestats[7];
 
@@ -990,8 +1001,14 @@
 	  	  if (get_frame) AVIStreamGetFrameClose(get_frame);
 		  if (avi_in_stream) AVIStreamRelease(avi_in_stream);
 		  AVIFileExit();
-      }
-      else
+		}
+		else if (ARG_INPUTFILE == NULL || strcmp(ARG_INPUTFILE, "stdin") == 0) {
+#ifdef _WIN32
+		  _setmode(_fileno(stdin), _O_BINARY);
+#endif
+		  in_file = stdin;
+		}
+		else
 #endif
 		{
 			FILE *in_file = fopen(ARG_INPUTFILE, "rb");
```

[xvid_encraw.c.mabs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5346538/xvid_encraw.c.mabs.zip)

**Comment by wiiaboo** [comment]
Why isn't this upstreamed? Isn't xvid still barely active?

**Comment by LigH-de** [comment]
I will try to suggest it there too, as time permits. But I am not sure whether I should include the max zones patch as well.

**Comment by wiiaboo** [comment]
Well, if it's the same as FFmpeg, yes, that's how you propose patches in a non-Github/Gitlab environment.

**Comment by LigH-de** [comment]
> Isn't xvid still barely active?

sysKin wonders about that as well... just met him in IRC, by surprise.

**Comment by wiiaboo** [comment]
Isn't `in_file` being declared twice in that patch, too?

```patch
@@ -350,6 +360,7 @@
 	double totalenctime = 0.;
 	float totalPSNR[3] = {0., 0., 0.};
 
+	FILE *in_file = stdin;
 	FILE *statsfile;
 	frame_stats_t framestats[7];
```
Or is this part unrelated?

**Comment by LigH-de** [comment]
I was trying to apply this patch in various variants (substituting the sed with a `do_patch` with and without a trailing `am`), but without success. It just didn't apply. Unfortunately I don't see the reason for the failing.

**Comment by LigH-de** [comment]
OK, I made a patch that applies. Will create a PR.

**Comment by LigH-de** [comment]
Quick test: Does not work when there is no `-i` parameter for **xvid_encraw.exe**, but works with `-i stdin` alternatively.

**Comment by LigH-de** [comment]
OK, got it.

IMHO, the optimal solution would be someone creating a serious encoding application, based on xvid_encraw, in an own repo, to possibly add MKV and MP4 output based on well-tended public libraries. But that's not the topic of this issue anymore. :relieved:

**Comment by wiiaboo** [comment]
> IMHO, the optimal solution would be someone creating a serious encoding application

Great news, it already exists, it's called "ffmpeg" 🎉 
If you want `-xvidopts`, you can just request it and hope someone still cares enough about xvid to add it or figure out how to add it yourself.

Other than this old post in ffmpeg-user, I can't find anyone else mentioning it: https://ffmpeg.org/pipermail/ffmpeg-user/2012-July/007913.html

**Comment by Selur** [comment]
I don't think there will ever be an xvidopts in ffmpeg like in mencoder since ffmpeg already has options for most of XviDs options.
(A few options are missing, which is why I prefer mencoder and xvid_encraw and the hope that someone in the ffmpeg team will react to a feature request for ffmpeg is minimal,...)

**Comment by wiiaboo** [comment]
What options are missing?
Maybe they do exist already but use a different name, or are implemented differently than in mencoder/encraw.

**Comment by Selur** [comment]
Since I usually use mencoder I take the xvidencopts as basis (see: http://www.mplayerhq.hu/DOCS/man/en/mplayer.1.txt)

Here are the thinks that 

1. 
normally  VHQ has option:
```
vhq=<0-4>
The motion search algorithm is based on a search in the usual color domain and tries to find a motion vector that minimizes the difference between the reference frame and the encoded frame. With this setting activated, Xvid will also use the frequency domain (DCT) to search for a motion vector that minimizes not only the spatial difference but also the encoding length of the block. Fastest to slowest: 0 off 1 mode decision (inter/intra MB) (default) 2 limited search 3 medium search 4 wide search
```
in ffmpeg mbd:
```
mbd integer (encoding,video)
    Set macroblock decision algorithm (high quality mode).
    Possible values:
    ‘simple’
        use mbcmp (default) 
    ‘bits’
        use fewest bits 
    ‘rd’
        use best rate distortion 
```
which has three options.

2. 
Xvid allows to set min/max for i/p/b frames  separately ffmpeg only has qmin/qmax.

3.
Xvid has curve_compression_high and curve_compression_low ffmpeg only has 

4.
a few are missing (or I simply don't know what they could match to)
kfthreshold, kfreduction, bf_threshold, packed, frame_drop_ratio, rc_averaging_period, overflow_control_strength, max_overflow_improvement, max_overflow_degradation, bvhq

there might be more, but that are the missing things that jump to mind.

**Comment by wiiaboo** [comment]
> normally VHQ has option:
> 
> ```
> vhq=<0-4>
> The motion search algorithm is based on a search in the usual color domain and tries to find a motion vector that minimizes the difference between the reference frame and the encoded frame. With this setting activated, Xvid will also use the frequency domain (DCT) to search for a motion vector that minimizes not only the spatial difference but also the encoding length of the block. Fastest to slowest: 0 off 1 mode decision (inter/intra MB) (default) 2 limited search 3 medium search 4 wide search
> ```
> 
> in ffmpeg mbd:
> 
> ```
> mbd integer (encoding,video)
>     Set macroblock decision algorithm (high quality mode).
>     Possible values:
>     ‘simple’
>         use mbcmp (default) 
>     ‘bits’
>         use fewest bits 
>     ‘rd’
>         use best rate distortion 
> ```
> 
> which has three options.

encraw's (there's no git mirror for mencoder's code, so i'm not reading that) vhq is a mix of both ffmpeg's mbd and me_method options:
https://github.com/m-ab-s/xvid/blob/master/xvidcore/examples/xvid_encraw.c#L2627-L2656
https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libxvid.c#L406-L439

> Xvid allows to set min/max for i/p/b frames separately ffmpeg only has qmin/qmax.

https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libxvid.c#L610-L615
True, but you can request that. VAAPI has:
i_quant_factor, i_quant_offset, b_quant_factor, b_quant_offset

> 
> Xvid has curve_compression_high and curve_compression_low ffmpeg only has
> 
> 
> a few are missing (or I simply don't know what they could match to)
> kfthreshold, kfreduction, bf_threshold, packed, frame_drop_ratio, rc_averaging_period, overflow_control_strength, max_overflow_improvement, max_overflow_degradation, bvhq
> 
> there might be more, but that are the missing things that jump to mind.

https://github.com/m-ab-s/xvid/blob/master/xvidcore/examples/xvid_encraw.c#L2299-L2325
https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libxvid.c#L515-L546

Can also be requested.

If no one asks, why would anyone know whether it can be added or not?

**Comment by Selur** [comment]
Thanks for the feedback even if it doesn't really help, but to make sure the ffmpeg folks can know that there is a 'problem' I created a ticket in ffmpegs bug tracker (https://trac.ffmpeg.org/ticket/8935#ticket) asking for clarification and addition of missing options. So with a lot of luck I will get some useful feedback there in a timely fashion.

(So using xvid_encraw or sticking with mencoder is probably the only way for the foreseeable future.)
