### ISSUE TITLE
error: could not create link from

### ISSUE THREAD

**Issue by Pheidologeton** [m-ab-s/media-autobuild_suite#1832]
[iGNT.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5360019/iGNT.zip)
![Screenshot_374](https://user-images.githubusercontent.com/61123444/95664517-47cff680-0b51-11eb-81bd-5123d4d5d8a4.png)

**Comment by 1480c1** [comment]
I think this might be because the script detected that you have symlink support, and so `ln -s` is trying to create real symlinks instead of the fake copies that `ln -s` normally does

@wiiaboo are there any benefits to having it do that for now? I'm not too sold on using normal symlinks when a majority of the suite is tested without it since there's no guarantee that the suite will choose one or the other across all machines

**Comment by wiiaboo** [comment]
I'd still personally want symlinks for me/people for who it perfectly works for. It's still a nice space-saver.

**Comment by fpope** [comment]
I'm getting the same error (with slight variations on what it says before it's triggered), [logs are here](https://0x0.st/iG9r.zip).
I'm probably just missing the obvious but don't see anywhere to force the symlink or where `ln -s` is called.
What options do I have for a work around?

**Comment by 1480c1** [comment]
@wiiaboo I will try to move the check from using mklink to running `ls -s` and `test -h`

**Comment by 1480c1** [comment]
@wiiaboo can you try https://github.com/m-ab-s/media-autobuild_suite/commit/d1a3acc and make sure it doesn't break symlink stuff

it doesn't seem to break in non-symlink available compilation

**Comment by 1480c1** [comment]
```bash
ln: failed to create symbolic link 'linkedtestmklink': Operation not permitted
```
seems I forgot to silence a warning

**Comment by 1480c1** [comment]
merged the commit, @Pheidologeton can you retry?

**Comment by wiiaboo** [comment]
> 
> 
> @wiiaboo can you try [d1a3acc](https://github.com/m-ab-s/media-autobuild_suite/commit/d1a3acc) and make sure it doesn't break symlink stuff
> 
> it doesn't seem to break in what I assume is non-symlink available compilation

Yeah, works fine. Didn't know it could be enabled on runtime.

**Comment by Pheidologeton** [comment]
@1480c1 error 
![Screenshot_379](https://user-images.githubusercontent.com/61123444/96164832-7c162f00-0f24-11eb-976b-04228a77ff28.png)
[iGn5.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5386692/iGn5.zip)

**Comment by 1480c1** [comment]
Can you try deleting the `msys64/opt/cargo` folder?

**Comment by fpope** [comment]
No change on my end after updating and deleting msys64/opt/cargo: [iG5C.zip](https://0x0.st/iG5C.zip)
![image](https://user-images.githubusercontent.com/48143655/96176451-3f751400-0ee1-11eb-9485-b96ab7f59137.png)

**Comment by 1480c1** [comment]
It seems based on a casual perusal of rustup's code, that error shows when trying to create a hard link, aka `ln` without an `-s`, but theoretically, that should not be an issue since even without `MSYS` being set, you should be able to create a hard link with `ln`

Question, what format is your `F` drive?

**Comment by Pheidologeton** [comment]
refs, windows server 2019 virtual machine in gentoo linux

**Comment by 1480c1** [comment]
ah, I do not think refs supports links at all, only ntfs does in the windows world

**Comment by 1480c1** [comment]
https://news.ycombinator.com/item?id=3472857 based on a hacker news post with a dead msdn link, it seems they decided to drop hardlinks in refs

**Comment by Pheidologeton** [comment]
I'll try to reformat the volume to ntfs. I will report the result

**Comment by Pheidologeton** [comment]
new error
![Screenshot_380](https://user-images.githubusercontent.com/61123444/96181055-0ddd6680-0f3c-11eb-9cec-265685e15161.png)
[iGRj.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5387561/iGRj.zip)

**Comment by wiiaboo** [comment]
Only NTFS is supported for most MSYS2/MinGW stuff.
This is a known issue. That new error I have no idea, but that still doesn't look like a suite issue.

**Comment by 1480c1** [comment]
new one seems to be a meson+harfbuzz issues, no clue so far

**Comment by fpope** [comment]
Just wanted to confirm, moving from exFAT drive to NTFS resolved this issue for me.
Thank you both for your help!
