### ISSUE TITLE
cmake failed in libmediainfo

### ISSUE THREAD

**Issue by ghost** [m-ab-s/media-autobuild_suite#1836]
The logs are as follows
 [logs.zip](https://0x0.st/iDJ9.zip)

**Comment by chhaugen** [comment]
Got the same error [logs.zip](https://0x0.st/iDge.zip)

**Comment by alatony** [comment]
same thing here.

```
CMake Error at E:/ffmpeg/msys64/mingw32/share/cmake-3.18/Modules/FindPkgConfig.cmake:75 (set):
  Syntax error in cmake code at

    E:/ffmpeg/msys64/mingw32/share/cmake-3.18/Modules/FindPkgConfig.cmake:75

  when parsing string

    E:\ffmpeg\local32\lib\pkgconfig/../../lib

  Invalid escape sequence \f
Call Stack (most recent call first):
  E:/ffmpeg/msys64/mingw32/share/cmake-3.18/Modules/FindPkgConfig.cmake:107 (_pkgconfig_set)
  E:/ffmpeg/msys64/mingw32/share/cmake-3.18/Modules/FindPkgConfig.cmake:833 (_pkgconfig_invoke)
  E:/ffmpeg/msys64/mingw32/share/cmake-3.18/Modules/FindPkgConfig.cmake:571 (pkg_get_variable)
  E:/ffmpeg/msys64/mingw32/share/cmake-3.18/Modules/FindPkgConfig.cmake:738 (_pkg_check_modules_internal)
  E:/ffmpeg/msys64/mingw32/share/cmake-3.18/Modules/FindCURL.cmake:71 (pkg_check_modules)
  CMakeLists.txt:91 (find_package)
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5431344/logs.zip)

```

**Comment by yluvs** [comment]
I also got the same error.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5435956/logs.zip)

**Comment by sops21** [comment]
Same error here:

[logs.zip](https://0x0.st/ikk_.zip)

**Comment by Sunkyue-Kim** [comment]
same for me.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5480350/logs.zip)
compile succeed with removing --enable-libzimg option in ffmpeg_options.txt manually.

**Comment by Ledinax** [comment]
Same error. [logs.zip](https://0x0.st/idxh.zip)

**Comment by DooMMasteR** [comment]
Can confirm...

**Comment by WorfKlingon** [comment]
for me on the last commit in master 8c6ee6719fc60271f251518bf3566e8358571dc0
it's work;

> 12:46:56   Running git clone for libmediainfo...
> 12:47:06 ┌ libmediainfo git  ......................... [Recently updated]
> 12:47:06 ├ Running cmake...
> 12:47:12 ├ Running build...
> 12:48:00 ├ Running install...
> 12:48:00 ├ Stripping...
> 12:48:00 └ libmediainfo-git  .................................. [Updated]
>

**Comment by 1480c1** [comment]
Haven't yet reproduced the issue, so it could have been fixed on CMake's side, closing
