### ISSUE TITLE
a get error in cargo-c git mingw64

### ISSUE THREAD

**Issue by raestrada95** [m-ab-s/media-autobuild_suite#1837]
17:30:40 ┌ cargo-c git  .............................. [Recently updated]
17:30:40 ├ Running rust.update...
17:30:44 ├ Running rust.install...
Likely error (tail of the failed operation logfile):

``` bash
Paste output of the suite here
```

[logs.zip](https://0x0.st/iD5e.zip)

**Comment by 1480c1** [comment]
Try moving the suite outside of your download's folder and move it as close to the root of a drive as possible, like `D:/media-autobuild_suite`, the issue seems to be that rust likes to put full paths to all of its object files on a single ar command line

**Comment by raestrada95** [comment]
> Try moving the suite outside of your download's folder and move it as close to the root of a drive as possible, like `D:/media-autobuild_suite`, the issue seems to be that rust likes to put full paths to all of its object files on a single ar command line

Hi thx that worked, but now I have this problem
 [logs.zip](https://0x0.st/-k.txt)


By chance do you have any ffmpeg with : libsvtvp9 and libsvtav1

these would be very useful:
vpx
libsvthevc
libvpx
libx264
libx265 
nvdec

**Comment by wiiaboo** [comment]
You're in luck, all of those are supported by the suite, so you could also just run it and have your very own ffmpeg with those.
Yes, even including vpx AND libvpx.

**Comment by 1480c1** [comment]
You could try one of the builds listed on http://ffmpeg.org/download.html#build-windows

none of them include libsvthevc although
