### ISSUE TITLE
Issue in the SVT-AV1 compilation

### ISSUE THREAD

**Issue by miguelapg** [m-ab-s/media-autobuild_suite#1838]
Hi all,

SVT-AV1 was named in August 20th, 2020 the current line of researching for developing the AV1 codec standard, so any issue in the compilation for SVT-AV1 is an important subject, obviously.

As you all know, SVT-AV1 is developed by Intel and Netflix.

As I saw that there is an error message in the compilation of SVT-AV1, I thought that it could be interesting to have a look at what is happening, correcting the issue if possible.

┌ SVT-AV1 git  ........................................... [Updates found]
├ Running uninstall...
1501.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ SVT-AV1-git  ................................................. [Updated]

You can read the press release about SVT-AV1 as the new base for AV1 here ...

http://aomedia.org/press%20releases/aomedia-software-implementation-working-group-to-bring-av1-to-more-video-platforms/
__________________________________________

UPDATE:
__________________________________________

The same issue for libavif library ...

┌ libavif git  ........................................... [Updates found]
├ Running uninstall...
0001-CMake-Use-the-import-libraries-and-the-proper-variab.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libavif-git  ................................................. [Updated]

__________________________________________

Best,
Miguel

**Comment by miguelapg** [comment]
Seems you didn't realize there was a second issue report in my post.

Sorry for adding the second one in the same message.

The problem is with libavif now ...

The same issue for libavif library ...

┌ libavif git ........................................... [Updates found]
├ Running uninstall...
0001-CMake-Use-the-import-libraries-and-the-proper-variab.patch
Patch could not be applied with git am. Continuing without patching.
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libavif-git ................................................. [Updated]

Thanks

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/mabs-patches/commit/7988d569b896ccd01fa7d8598e9fe719781d1712 try again
