### ISSUE TITLE
64 bit Error running git clone for vulkan-loader – ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1839]
22:06:40   Running git clone for vulkan-loader...
22:07:56 ┌ vulkan-loader git  ........................ [Recently updated]
22:07:56 ├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
22:07:59 ├ Running dependencies...
22:08:10 ├ Installing Vulkan-Headers...
22:08:11 ├ Running uninstall...
22:08:11 ├ Running cmake...
22:08:11 ├ Running build...
22:08:11 ├ Running install...
22:08:13 ├ Building Vulkan-Loader...
22:08:13 ├ Running cmake...
22:08:24 ├ Running build...
Likely error (tail of the failed operation logfile):
  410 | static void loader_platform_thread_init_cond(loader_platform_thread_cond *pCond) { InitializeConditionVariable(pCond); }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:401:34: warning: 'loader_platform_get_thread_id' defined but not used [-Wunused-function]
  401 | static loader_platform_thread_id loader_platform_get_thread_id() { return GetCurrentThreadId(); }
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[5/6] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -I../loader -I../loader/generated -Iloader  /c /Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj ../loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW64/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
22:08:32   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ik7k.zip
Copy and paste [logs.zip](https://0x0.st/ik7k.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

[logs.zip](https://0x0.st/ik7k.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/5465681/ab-suite.build.log)

**Comment by j-mas** [comment]
Same here!

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/mabs-patches/commit/1d86df97417d6b931258b0d43f028b6d5f44357c try again

**Comment by j-mas** [comment]
Now I get this:

22:59:49 ┌ ffmpeg git  ............................... [Recently updated]
22:59:49 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
22:59:57 ├ Compiling static FFmpeg...
22:59:59 ├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --cc=ccache gcc --cxx=ccache g++ --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libdav1d --enable-libaom --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libsvthevc --enable-libsvtav1 --enable-libsvtvp9 --enable-libkvazaar --enable-libmodplug --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-vapoursynth --enable-liblensfun --enable-libglslang --enable-vulkan --enable-opencl --enable-opengl --enable-openssl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-IC:/m-a-master/local64/include/AL --extra-version=g45e3131c44+5
**ERROR: vulkan >= 1.1.97 not found using pkg-config**

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check C:/m-a-master/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
23:03:23   Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5467864/logs.zip)
[ab-suite.configure.log](https://github.com/m-ab-s/media-autobuild_suite/files/5467874/ab-suite.configure.log)

**Comment by 1480c1** [comment]
try deleting build/vulkan-loader-git and rebuild https://github.com/m-ab-s/mabs-patches/commit/a9a5f1ae14c9fbe5b79646b6a5d347b32765243f

**Comment by j-mas** [comment]
after deleting it and rebuilding I get the following error:

00:10:10 ┌ ffmpeg git  ............................... [Recently updated]
00:10:10 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
00:10:18 ├ Compiling static FFmpeg...
00:10:19 ├ Running configure...
00:14:12 ├ Running make...
Likely error (tail of the failed operation logfile):
make: *** Waiting for unfinished jobs....
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:121: ffprobe_g.exe] Error 1
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:121: ffplay_g.exe] Error 1
LD      ffmpeg_g.exe
C:/m-a-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/m-a-master/local64/lib/libzimg.a(libzimg_internal_la-libm_wrapper.o):libm_wrapper.cpp:(.text$expf[expf]+0x0): multiple definition of `expf'; C:/m-a-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingwex.a(lib64_libmingwex_a-expf.o):C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/math/expf.c:9: first defined here
C:/m-a-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/m-a-master/local64/lib/libzimg.a(libzimg_internal_la-libm_wrapper.o):libm_wrapper.cpp:(.text$powf[powf]+0x0): multiple definition of `powf'; C:/m-a-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingwex.a(lib64_libmingwex_a-powf.o):C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/math/powf.c:8: first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:121: ffmpeg_g.exe] Error 1
make failed. Check C:/m-a-master/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
00:16:35   Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5468088/logs.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/5468093/ab-suite.make.log)

**Comment by 1480c1** [comment]
seems to be separate issues, although there also seems to be an issue with 32-bit openssl, so I will try to look into that as well
