### ISSUE TITLE
vulkan-0001-cross-compile-static-linking-hacks.patch 404 Not Found

### ISSUE THREAD

**Issue by Toys0125** [m-ab-s/media-autobuild_suite#1843]
![image](https://user-images.githubusercontent.com/15334903/98050694-e02b6500-1df7-11eb-9de2-5e5f65cb302b.png)
[logs.zip](https://0x0.st/id43.zip)

**Comment by 1480c1** [comment]
try rerunning the suite

**Comment by Toys0125** [comment]
Still says 404 not found
[logs.zip](https://0x0.st/idx2.zip)

**Comment by Toys0125** [comment]
So found the issue Once i went to the repository for the patches It was spelled `0001-loader...` while in the suite its `vulkan-0001...`

**Comment by Toys0125** [comment]
So running git pull, and rerunning

**Comment by Toys0125** [comment]
after pulling it works now.
