### ISSUE TITLE
[mingw64] [FFmpeg] FFmpeg share build works but static build fails.

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#1846]
Error log:

> [95m13:23:09(B[m [1mâ”Œ ffmpeg git (B[m .................................. [[93mUpdates found(B[m]
> [95m13:23:09(B[m [1mâ”œ(B[m Changing options to comply to nonfree...
> [93mFFmpeg and related apps will depend on CUDA SDK to run!(B[m
> [95m13:23:43(B[m [1mâ”œ(B[m Compiling [1mshared(B[m FFmpeg...
> [95m13:23:44(B[m [1mâ”œ(B[m Running uninstall...
> [95m13:23:47(B[m [1mâ”œ(B[m Running configure...
> [95m13:32:54(B[m [1mâ”œ(B[m Running make...
> [95m13:42:17(B[m [1mâ”œ(B[m Running install...
> [95m13:42:44(B[m [1mâ”œ(B[m Compiling [1mstatic(B[m FFmpeg...
> [95m13:42:47(B[m [1mâ”œ(B[m Running configure...
> [95m13:51:56(B[m [1mâ”œ(B[m Running make...
> Likely error (tail of the failed operation logfile):
> make: *** Waiting for unfinished jobs....
> collect2.exe: error: ld returned 1 exit status
> make: *** [/build/ffmpeg-git/Makefile:121: ffmpeg_g.exe] Error 1
> collect2.exe: error: ld returned 1 exit status
> make: *** [/build/ffmpeg-git/Makefile:121: ffplay_g.exe] Error 1
> LD	ffmpeg_g.exe
> C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/media-autobuild_suite/local64/lib/libzimg.a(libzimg_internal_la-libm_wrapper.o):libm_wrapper.cpp:(.text$expf[expf]+0x0): multiple definition of `expf'; C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingwex.a(lib64_libmingwex_a-expf.o):C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/math/expf.c:9: first defined here
> 
> C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/media-autobuild_suite/local64/lib/libzimg.a(libzimg_internal_la-libm_wrapper.o):libm_wrapper.cpp:(.text$powf[powf]+0x0): multiple definition of `powf'; C:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingwex.a(lib64_libmingwex_a-powf.o):C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/math/powf.c:8: first defined here
> 
> collect2.exe: error: ld returned 1 exit status
> make: *** [/build/ffmpeg-git/Makefile:121: ffmpeg_g.exe] Error 1
> [31mmake failed. Check C:/media-autobuild_suite/build/ffmpeg-git/build-static-64bit/ab-suite.make.log(B[m
> [31mThis is required for other packages, so this script will exit.(B[m
> [95m14:01:27(B[m   Creating diagnostics file...
> 
> [32mAll relevant logs have been anonymously uploaded to https://0x0.st/idkx.zip
> [32mCopy and paste [31m[logs.zip](https://0x0.st/idkx.zip)[32m in the GitHub issue.(B[m
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
> Try running the build again at a later time.
> 

diagnostics file：https://0x0.st/idkx.zip

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/e57877f87abf1a07b79284de257e3cad6bbf7409 try repulling and deleting build/zimg-git

**Comment by fuchanghao** [comment]
> [e57877f](https://github.com/m-ab-s/media-autobuild_suite/commit/e57877f87abf1a07b79284de257e3cad6bbf7409) try repulling and deleting build/zimg-git

Now it fails at vidstab so I can't check the ffmpeg.

full error log:https://0x0.st/in2d.zip


> [95m09:31:47(B[m [1mâ”Œ vidstab git (B[m .............................. [[93mRecently updated(B[m]
> [95m09:31:49(B[m [1mâ”œ(B[m Running cmake...
> [95m09:31:53(B[m [1mâ”œ(B[m Running build...
> Likely error (tail of the failed operation logfile):
> [11/13] Building C object CMakeFiles/vidstab.dir/src/boxblur.c.o
> 
> [12/13] Building C object CMakeFiles/vidstab.dir/src/motiondetect.c.o
> 
> ninja: build stopped: subcommand failed.
> 
> [1/2] Building C object CMakeFiles/vidstab.dir/src/serialize.c.o
> 
> FAILED: CMakeFiles/vidstab.dir/src/serialize.c.o 
> 
> C:\media-autobuild_suite\msys64\mingw64\bin\ccache.exe  gcc -DDISABLE_ORC -DUSE_OMP -DUSE_SSE2  -mthreads -mtune=generic -O2 -pipe -O3 -DNDEBUG   -Wall -Wno-pointer-sign -msse2 -ffast-math -fopenmp -fopenmp -std=gnu99 -MD -MT CMakeFiles/vidstab.dir/src/serialize.c.o -MF CMakeFiles\vidstab.dir\src\serialize.c.o.d -o CMakeFiles/vidstab.dir/src/serialize.c.o -c ../src/serialize.c
> 
> ../src/serialize.c:67:2: error: #error "I don't know what architecture this is!"
>    67 | #error "I don't know what architecture this is!"
>       |  ^~~~~
> ninja: build stopped: subcommand failed.
> 
> [31mbuild failed. Check C:/media-autobuild_suite/build/vidstab-git/build-64bit/ab-suite.build.log(B[m
> [31mThis is required for other packages, so this script will exit.(B[m
> [95m09:31:54(B[m   Creating diagnostics file...
> 
> [32mAll relevant logs have been anonymously uploaded to https://0x0.st/in2d.zip
> [32mCopy and paste [31m[logs.zip](https://0x0.st/in2d.zip)[32m in the GitHub issue.(B[m
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
> Try running the build again at a later time.

**Comment by 1480c1** [comment]
that's https://github.com/m-ab-s/media-autobuild_suite/issues/1847 now

**Comment by georgmartius** [comment]
Does it work with the latest changes in vidstab now?

**Comment by fuchanghao** [comment]
> 
> 
> Does it work with the latest changes in vidstab now?

It works now for me.
