### ISSUE TITLE
No package 'harfbuzz' found [mingw64] Windows 10

### ISSUE THREAD

**Issue by felicemarra** [m-ab-s/media-autobuild_suite#1849]
What can I do? I tried with 2 pc with Windows 10

![image](https://user-images.githubusercontent.com/2297601/99071030-aa357000-25b1-11eb-8925-928490496d73.png)

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5536674/logs.zip)

**Comment by wiiaboo** [comment]
Libass now [hard-depends on harfbuzz](https://github.com/libass/libass/commit/f3e2c97e1818598afb0b1c7010003ffe4823ff21), but you're probably using ffmpeg=sharedlibs and last time I checked harfbuzz doesn't compile cleanly to a shared lib.

Do not use that ffmpeg option.

@1480c1, can you check if shared-only harfbuzz works now?

**Comment by wiiaboo** [comment]
I don't even know if the original requester for this flavor is still using it. Ping, @Kagami.

**Comment by felicemarra** [comment]
Yes I need to compile FFmpeg as shared libs...

**Comment by wiiaboo** [comment]
That's not what I'm asking.

This specific option is to use shared libs for the dependencies of ffmpeg/mpv.

**Comment by wiiaboo** [comment]
You can choose either 3 or 4 to get shared ffmpeg libs:
https://github.com/m-ab-s/media-autobuild_suite/blob/37f1d63b33c0cbb30b4dd46f7bcff79c967a7d49/media-autobuild_suite.bat#L683-L702

**Comment by wiiaboo** [comment]
Option 5 was specifically added for people that distributed ffmpeg along with mpv and wanted to save some disk space with libs used in both. Do not use it, if you don't need it.

**Comment by felicemarra** [comment]
ok! I try! Thank you

**Comment by 1480c1** [comment]
I'll check if the other options work as well after I finish making 32-bit clang and gcc work as well

**Comment by wiiaboo** [comment]
Only tested for 64-bit + gcc, so not sure if it works with those.
