### ISSUE TITLE
visual studio build

### ISSUE THREAD

**Issue by jindal1979** [m-ab-s/media-autobuild_suite#1851]
I have been following the development at media autobuild suite and its really very helpful for Windows developer. 

It would be very helpful if there is option to use visual studio 2019 compiler in addition to gcc and clang.

**Comment by 1480c1** [comment]
visual studio and gcc don't mix, plus we don't interact with msvc other than certain few instances where we have no other option

**Comment by wiiaboo** [comment]
No, just use some other project.
