### ISSUE TITLE
Missing online patches 

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1853]
Another thing i just noticed........

┌ ffmpeg git  ............................................ [Updates found]
├ Changing options to comply to nonfree...
libnpp is only supported in 64-bit.
CUDA_PATH environment variable not set or directory does not exist.
**0001-get_cabac_inline_x86-Don-t-inline-if-32-bit-clang-on.patch**
        File not found online. Using local copy.
**0001-configure-deduplicate-linking-flags.patch**
        File not found online. Using local copy.
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...

**Comment by wiiaboo** [comment]
Yep, they are.
Check your network.
