### ISSUE TITLE
ffmpeg compilation issue

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1854]
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
libnpp is only supported in 64-bit.
CUDA_PATH environment variable not set or directory does not exist.
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
D:/media-autobuild_suite-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(bn-586.o) and D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(chacha-x86.o) and D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(ecp_nistz256-x86.o) and D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(poly1305-x86.o) and D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(sha1-586.o) and D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(sha256-586.o) and D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(sha512-586.o) and D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/media-autobuild_suite-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-gf2m.o) and D:/media-autobuild_suite-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:121: ffmpeg_g.exe] Error 1
make failed. Check D:/media-autobuild_suite-ffmpeg/build/ffmpeg-git/build-static-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/i5Hy.zip

**Comment by 1480c1** [comment]
delete D:/media-autobuild_suite-ffmpeg/local32/lib/libzimg.a and recompile

**Comment by Barough** [comment]
Will give that a try and get back.

**Comment by Barough** [comment]
That solved it. Thnx :)
