### ISSUE TITLE
Request: JPEG-XL Reference Encoder support

### ISSUE THREAD

**Issue by Felixkruemel** [m-ab-s/media-autobuild_suite#1855]
JPEG XL is a new Jpeg encoder which is way more efficient than old ones and sometimes surpasses webp while beeing 100% compatible to the jpeg spec and decoders. They just published their first release.

I really would love to see it included in the autobuild suite!

Here's the source
https://gitlab.com/wg1/jpeg-xl

**Comment by wiiaboo** [comment]
Even WebP only very recently got support on Safari.
What about this is different than JPEG-XR, JPEG-2000, FLIF and other good but failed attempts at getting an image codec to stick?

**Comment by Felixkruemel** [comment]
@wiiaboo 
While AVIF will probably be the smallest picture codec on the web for the near future, JPEG-XL is not actually an extra codec like webp.

It's just jpeg, just with an more efficient encoding. For the consumer or decoder it makes no difference, they don't even know it was encoded with jpeg-xl. It just looks like a normal jpeg image for them.
So in it, it's not an extra codec. Jpeg is by far the most used codec out there so there's no point in thinking that jpeg-xl won't be used, you will just not know it's been used.

WebP has failed as it's not much more efficient than Jpeg.

AVIF on the other hand is more than twice as efficient and already has support on Firefox (there just the latest nightly) and Chromium based Browsers. In my opinion those efficiency is king for e.g. Google or other sites with many images in it, especially if they are mostly accessed over slow mobile networks. But even if they don't want to store 2 pictures (AVIF & jpeg for compatibility) simultaniously jpeg-xl is there to drastically reduce the file size of the normal jpeg encode too.
