### ISSUE TITLE
[mingw64] [harfbuzz] harfbuzz build error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1856]
09:34:03 ┌ harfbuzz git............................. [Recently updated]
09:34:06 ├ Running meson...
09:36:31 ├ Running build...
Likely error
 (tail of the failed operation logfile):
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x385): undefined reference to `inflateReset'

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x3ff): undefined reference to `inflateEnd'

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x5de): undefined reference to `inflateInit2_'

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x747): undefined reference to `inflateEnd'

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x872): undefined reference to `inflateInit2_'

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x886): undefined reference to `inflate'

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x895): undefined reference to `inflateEnd'

D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libfreetype.a(ftgzip.o):ftgzip.c:(.text+0x8ea): undefined reference to `inflateEnd'

collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

build failed.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5544529/logs.zip)

**Comment by wiiaboo** [comment]
Force recompilation of freetype.
