### ISSUE TITLE
Compile only libmp3lame

### ISSUE THREAD

**Issue by kirgizmustafa17** [m-ab-s/media-autobuild_suite#1857]
Hi I just want to compile libmp3lame to encode audio files. Usually webm/m4a to mp3. How can do this?

I tried this but it didn't work.
https://stackoverflow.com/questions/54750953/how-to-compile-ffmpeg-to-get-only-mp3-and-mp4-support

**Comment by wiiaboo** [comment]
Just disable everything that's not ffmpeg in the INI and choose ffmpegChoice=1. In the ffmpeg_options.txt file that's created, remove/comment every option after the built-in ones that's not `--enable-libmp3lame`.
Don't copy/paste crap from old stackoverflow posts.
