### ISSUE TITLE
libplacebo is updated but no dependent project

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1859]
Today I noticed an update for libplacebo. But after that, no other project was rebuilt, as if no project depends on it. Is there a mistake in a dependency chain or build order?

[compile.log](https://github.com/m-ab-s/media-autobuild_suite/files/5546271/compile.log)

**Comment by 1480c1** [comment]
It seems mpv (one of libplacebo's dependents afaik) does not have it listed.

**Comment by LigH-de** [comment]
True. I wonder why my custom option list got most libraries not enabled... must be a remnant of testing different licenses.

**Comment by LigH-de** [comment]
No, wait ... this option is in the block of defaults, so it should not need explicit enabling, except being located there is outdated. :thinking: I need to recreate this list and see what changes.
