### ISSUE TITLE
Xvid: strange bitstream version number 1.4.-127

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1860]
Not sure if a bug at all, and whether it is related to forking the original repo or present in that one already...

```
xvidcore build version: xvid-1.4.0-dev
Bitstream version: 1.4.-127
```

This negative number might be a sign that the correct value could not be retrieved (or was miscalculated because only integer values were expected and the literal `dev` is NaN); or is it intentional to flag a development version?

**Comment by wiiaboo** [comment]
https://github.com/m-ab-s/xvid/blob/master/xvidcore/src/xvid.h#L71

**Comment by wiiaboo** [comment]
See https://github.com/m-ab-s/xvid/blob/4f02ef0c83387cf030b236114c44af10fd9cd661/xvidcore/src/xvid.h#L71

**Comment by wiiaboo** [comment]
Might be because it's from trunk, so not weird at all.

**Comment by wiiaboo** [comment]
Only the release branches have non-negative patch versions.
