### ISSUE TITLE
[QUESTION] exhale

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1866]
What do i need to change in mabs to make it pull/build from the exhale develop branch. Have looked in 'media-suite_compile.sh' but i don't know what to change etc.

**Comment by wiiaboo** [comment]
https://github.com/m-ab-s/media-autobuild_suite/blob/22539e927dd37ff4a78925ef53e0f4adcefb8d8b/build/media-suite_compile.sh#L711

Add `#branch=develop` after the `exhale.git` part.

And maybe nicely ask @1480c1 to add a `_pre_vcs` hook so that you could possibly override this more easily without changing the suite files.

**Comment by Barough** [comment]
@wiiaboo Thanks for the help. I'll add that to the 711 line
do_vcs "https://gitlab.com/ecodis/exhale.git#branch=develop"; then 
Don't know what a _pre_vcs hook is, but i'll ask nicely ;)

@1480c1 Would it be possible for you to add a _pre_vcs hook for exhale so that it's possible to override the the develop pull more easily without changing the suite files?

**Comment by 1480c1** [comment]
@Barough https://github.com/m-ab-s/media-autobuild_suite/commit/2cd97ad23025f5b60750509cd4e70ce8fe283934 can you try `_pre_vcs`?

**Comment by Barough** [comment]
I'll give it a try when i get back home tonight

**Comment by Barough** [comment]
Don't see anything different here or do i need to change something or?

Noticed that the compiled exhale binary is still based on the master branch and not on the develop branch even though i've added the '#branch=develop' to line 711

**Comment by 1480c1** [comment]
just to make sure, what changes did you do in total?

I do know there's the way @wiiaboo mentioned with changing the line from
```diff
- do_vcs "https://gitlab.com/ecodis/exhale.git"; then 
+ do_vcs "https://gitlab.com/ecodis/exhale.git#branch=develop"; then 
```

the new way would be to make a file called `exhale_extra.sh` under the build folder and inside that file, write
```bash
#!/usr/bin/bash

_pre_vcs() {
    ref=develop
}
```

**Comment by Barough** [comment]
I only did what @wiiaboo mentioned, nothing else. But for some reason so doesn't it pull from the develop branch.

Will give you way a try in a few minutes

**Comment by 1480c1** [comment]
sure, I can try, what indicator can I use to tell what branch the program was compiled on? does it show in a `--version` or `--help` output?

**Comment by Barough** [comment]
It doesn't say but the latest stable version is 1.0.8 and in the develop branch so is it 1.1 RC

**Comment by Barough** [comment]
Your way didn't work here either, still v1.0.8 here on my end. This just sucks. :(

**Comment by 1480c1** [comment]
just making sure, did you delete exhale-git folder or delete the binaries before recompiling?

**Comment by Barough** [comment]
Deleted both

**Comment by 1480c1** [comment]
```ps
PS D:\mabs> .\local64\bin-audio\exhale.exe --version

  ---------------------------------------------------------------------
 | exhale - ecodis extended high-efficiency and low-complexity encoder |
 |                                                                     |
 | version 1.1RC (x64, built on Nov 28 2020) - written by C.R.Helmrich |
  ---------------------------------------------------------------------

 Copyright 2018-2020 C.R.Helmrich, project ecodis. See License.htm for details.

 This software is made available under the exhale Copyright License and comes
 with ABSOLUTELY NO WARRANTY. This software may be subject to other third-party
 rights, including patent rights. No such rights are granted under this License.

 Usage: exhale.exe preset [inputWaveFile.wav] outputMP4File.m4a

 where

 preset =  # (0-9)  low-complexity standard compliant xHE-AAC at 16·#+48 kbit/s
             (a-g)  low-complexity compliant xHE-AAC with SBR at 12·#+36 kbit/s

 inputWaveFile.wav  lossless WAVE audio input, read from stdin if not specified

 outputMP4File.m4a  encoded MPEG-4 bit-stream, extension should be .m4a or .mp4


 Notes: The above bit-rates are for stereo and change for mono or multichannel.
        Use filename prefix .\ for the current directory if this executable was
        called with a path (call: D:\mabs\local64\bin-audio\exhale.exe).
```

I got it to work with the 
```diff
- do_vcs "https://gitlab.com/ecodis/exhale.git"; then 
+ do_vcs "https://gitlab.com/ecodis/exhale.git#branch=develop"; then 
```
changes

**Comment by 1480c1** [comment]
if you open mintty and run `git diff` what shows up?

**Comment by Barough** [comment]
NetRanger@DESKTOP-54U99HF /trunk
$ git diff
NetRanger@DESKTOP-54U99HF /trunk
$

**Comment by Barough** [comment]
Beats me whats going on here on my side. This is just getting ridicules imo.

Thinking about making a new MABS 'setup' and start all over.

**Comment by wiiaboo** [comment]
What do you get with calling `cat /build/exhale_extra.sh`?

**Comment by Barough** [comment]
NetRanger@DESKTOP-54U99HF /trunk
$ cat /build/exhale_extra.sh
#!/usr/bin/bash

_pre_vcs() {
    ref=develop

**Comment by 1480c1** [comment]
I can confirm the extra.sh way did not work, I guess I need to figure out what went wrong

**Comment by Barough** [comment]
> I can confirm the extra.sh way did not work, I guess I need to figure out what went wrong

ok

**Comment by 1480c1** [comment]
oh, I think I see why it fail, I'll ping you when I think I have it working

**Comment by wiiaboo** [comment]
Don't you need to `export ref=stuff` for it to affect the parent scope $ref?

**Comment by 1480c1** [comment]
no, since it's using `{}` any non-local variables get "sourced" back into the caller's "local" variables and not in the exported environment

```bash
#!/bin/bash

g++ -x c++ -o aaa - <<'EOF'
#include <cstdio>
#include <cstdlib>
int main() {
    char *aaa = std::getenv("ref");
    if (aaa) std::printf("%s\n", aaa);
}
EOF

echo pre
_pre_vcs() {
    ref=AAAA
}
_pre_vcs
echo $ref
./aaa
echo post
_post_vcs() {
    export ref=AAAA
}
_post_vcs
echo $ref
./aaa
```

resulted in 

```bash
pre
AAAA
post
AAAA
AAAA
```

**Comment by wiiaboo** [comment]
OK, so the issue is just that it's sourcing it in /build, so it doesn't know vcsFolder. Can't you just pass it as param? (do_wget_sf's check_custom_patches probably doesn't work either)

**Comment by 1480c1** [comment]
now that you mention that, I could (and probably should have).

**Comment by 1480c1** [comment]
@Barough I believe the extra.sh should work now as I tested it just now
```ps
PS D:\media-autobuild_suite> .\local64\bin-audio\exhale.exe --version

  ---------------------------------------------------------------------
 | exhale - ecodis extended high-efficiency and low-complexity encoder |
 |                                                                     |
 | version 1.1.0 (x64, built on Nov 28 2020) - written by C.R.Helmrich |
  ---------------------------------------------------------------------
```

**Comment by Barough** [comment]
@1480c1 It's working fine now. Thnx a lot :)
