### ISSUE TITLE
ERROR: libbs2b not found using pkg-config

### ISSUE THREAD

**Issue by WorfKlingon** [m-ab-s/media-autobuild_suite#1869]
I have clone the repository some hours before to rebuild all and ffmpeg don't compile due to libbs2b not found.
Here the generated logs.zip file.
[i7NR.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5616865/i7NR.zip)

**Comment by 1480c1** [comment]
can you try deleting any bs2b folders you find under the build folder and rerunning?

**Comment by WorfKlingon** [comment]
just for information, before do your request i want to check again with last updates. So Ii delete my local repository and do a git clone
my local repository is  now
❯ git show
commit 9fa467f1de395e93c811c740e4ad893f0e34ca61 (HEAD -> master, origin/master, origin/HEAD)

I have the same error. here the zip file
[i7Mv.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5619402/i7Mv.zip)

Now i will do your request

**Comment by 4501771** [comment]
having exactly the same problem, tried above ... always fails with the libbs2b error
any ideas?

**Comment by 1480c1** [comment]
can you find a file called `libbs2b.pc` under the local64/lib/pkgconfig folder?

**Comment by WorfKlingon** [comment]
Here my all files under  local64/lib/pkgconfig folder :
worf_@LAPTOP-5MROA8A5  C:\Dev\media-autobuild_suite\local64\lib\pkgconfig   master ≣                       [20:51]
❯ tree /F
    aom.pc
    codec2.pc
    dav1d.pc
    davs2.pc
    dvdnav.pc
    dvdread.pc
    fdk-aac.pc
    ffnvcodec.pc
    flac++.pc
    flac.pc
    fontconfig.pc
    freetype2.pc
    frei0r.pc
    fribidi.pc
    glut.pc
    gnutls.pc
    gpac.pc
    haisrt.pc
    harfbuzz-subset.pc
    harfbuzz.pc
    kvazaar.pc
    lept.pc
    libaacs.pc
    libass.pc
    libavif.pc
    libbdplus.pc
    libbluray.pc
    libcurl.pc
    libgme.pc
    libidn2.pc
    libilbc.pc
    libmediainfo.pc
    libmfx.pc
    libmysofa.pc
    libopenmpt.pc
    libopusenc.pc
    libpsl.pc
    librtmp.pc
    libtiff-4.pc
    libvmaf.pc
    libwebp.pc
    libwebpdecoder.pc
    libwebpdemux.pc
    libwebpmux.pc
    libxml-2.0.pc
    libzen.pc
    openal.pc
    opus.pc
    opusfile.pc
    opusurl.pc
    rav1e.pc
    rubberband.pc
    sdl2.pc
    shine.pc
    SPIRV-Tools-shared.pc
    SPIRV-Tools.pc
    srt.pc
    SvtAv1Dec.pc
    SvtAv1Enc.pc
    SvtHevcEnc.pc
    SvtVp9Enc.pc
    tesseract.pc
    uavs3d.pc
    vapoursynth-script.pc
    vapoursynth.pc
    vidstab.pc
    vpx.pc
    vulkan.pc
    x264.pc
    x265.pc
    xavs.pc
    xavs2.pc
    xvc.pc
    zimg.pc

**Comment by WorfKlingon** [comment]
> having exactly the same problem, tried above ... always fails with the libbs2b error
> any ideas?

No informations into the automated zip log file?

**Comment by WereCatf** [comment]
I think the issue is related to the fact that, at least for me, MABS complains about missing mingw-w64-x86_64-pkg-config, but then when trying to install it, there's a conflict with mingw-w64-x86_64-pkgconf. Something's wonky with the packaging-stuff and causing breakage.

**Comment by 1480c1** [comment]
I am currently testing the move from pkg-config to pkgconf, but in the case of @WorfKlingon, that is not the issue as his folder does not have the libbs2b.pc file, and thus my only guess is that maybe bs2b did not compile for him.

Due to real-life stuff, I cannot look into this too much today

**Comment by WereCatf** [comment]
@1480c1 There are a bunch of things that aren't compiling, like libzvbi and libvo-amrwbenc as well as libbs2b. Completely fresh copy of this repo, no previous leftovers or anything.

**Comment by WorfKlingon** [comment]
If you want to do some test, i'm available for

**Comment by 1480c1** [comment]
I think I have an idea now, can you try on https://github.com/m-ab-s/media-autobuild_suite/commit/929cdbae6cb3953d4f7475409cd6395e56f96298

**Comment by WereCatf** [comment]
@1480c1 I'm not OP, but for me, yes, that patch seems to have fixed compilation.

**Comment by WorfKlingon** [comment]
I try right now

**Comment by WorfKlingon** [comment]
As always my test was done with a remove  completely local repository and  a full git clone.

With  https://github.com/m-ab-s/media-autobuild_suite/commit/929cdbae6cb3953d4f7475409cd6395e56f96298 revision, II have this error now;

08:21:22   Running git clone for qtdeclarative...
08:21:57 ┌ qtdeclarative git  ........................ [Recently updated]
08:21:59 ├ Running qmake...
08:22:01 ├ Running install...
Likely error (tail of the failed operation logfile):
make[5]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph/d3d12'
make[4]: *** [Makefile:55: release-install] Error 2
make[4]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph/d3d12'
make[3]: *** [Makefile:62: sub-d3d12-install_subtargets] Error 2
make[3]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph'
make[2]: *** [Makefile:88: sub-scenegraph-install_subtargets] Error 2
make[2]: Leaving directory '/build/qtdeclarative-git/src/plugins'
make[1]: *** [Makefile:429: sub-plugins-install_subtargets-ordered] Error 2
make[1]: Leaving directory '/build/qtdeclarative-git/src'
make: *** [Makefile:65: sub-src-install_subtargets] Error 2

here the log file :
[i7fx.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5628756/i7fx.zip)

**Comment by 4501771** [comment]
> I think I have an idea now, can you try on [929cdba](https://github.com/m-ab-s/media-autobuild_suite/commit/929cdbae6cb3953d4f7475409cd6395e56f96298)

worked for me as it seems, at least it finished properly, ffmpeg.exe seems to work, thanks for the quick help

**Comment by 1480c1** [comment]
> As always my test was done with a remove completely local repository and a full git clone.
> 
> With [929cdba](https://github.com/m-ab-s/media-autobuild_suite/commit/929cdbae6cb3953d4f7475409cd6395e56f96298) revision, II have this error now;
> 
> 08:21:22 Running git clone for qtdeclarative...
> 08:21:57 ┌ qtdeclarative git ........................ [Recently updated]
> 08:21:59 ├ Running qmake...
> 08:22:01 ├ Running install...
> Likely error (tail of the failed operation logfile):
> make[5]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph/d3d12'
> make[4]: *** [Makefile:55: release-install] Error 2
> make[4]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph/d3d12'
> make[3]: *** [Makefile:62: sub-d3d12-install_subtargets] Error 2
> make[3]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph'
> make[2]: *** [Makefile:88: sub-scenegraph-install_subtargets] Error 2
> make[2]: Leaving directory '/build/qtdeclarative-git/src/plugins'
> make[1]: *** [Makefile:429: sub-plugins-install_subtargets-ordered] Error 2
> make[1]: Leaving directory '/build/qtdeclarative-git/src'
> make: *** [Makefile:65: sub-src-install_subtargets] Error 2
> install failed. Check C:/Dev/media-autobuild_suite/build/qtdeclarative-git/ab-suite.install.log
> This is required for other packages, so this script will exit.
> 08:27:19 Creating diagnostics file...

this one is related to vlc and I'm currently trying to fix {64,32}-bit{gcc,clang} compilation in another branch

**Comment by WorfKlingon** [comment]
ready to test is needed ;-)

**Comment by 1480c1** [comment]
https://github.com/1480c1/media-autobuild_suite/tree/vcs_clean here's the branch, but do note it will be force-pushed often

**Comment by WorfKlingon** [comment]
I started the run into your branch...

BTW, I have always the same problem when i do a fresh repository clone. 
When i launch the .\media-autobuild_suite.bat, some stuff are doing but something wrong :
_MinGW64 GCC compiler isn't installed; maybe the download didn't work_
_Do you want to try it again?_

I launch again and I have the same error. I can run the bat file indefinilitely, i have the same problem.

To workaroung this, I close the powerShell and rerun the bat. In this case it's work.
It's not due to ypur branch but I have the same issue in the master since a long time.
I had found a workaround, so I'm not blocked but if you can see what happend it will a good thing ;-)
Let to you to add a new issue for that.

See logs:
- Download and install msys2 basic system

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

- unpacking msys2 basic system

-------------------------------------------------------------------------------

7-Zip SFX 19.00 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Extracting archive: C:\Dev\media-autobuild_suite\build\msys2-base.sfx.exe
--
Path = C:\Dev\media-autobuild_suite\build\msys2-base.sfx.exe
Type = 7z

Everything is Ok
-------------------------------------------------------------------------------
- make a first run
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
first update
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
critical updates
-------------------------------------------------------------------------------
warning: bash-4.4.023-2 is up to date -- skipping
warning: pacman-5.2.2-4 is up to date -- skipping
warning: msys2-runtime-3.1.7-4 is up to date -- skipping
 there is nothing to do
-------------------------------------------------------------------------------
second update
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
creating local64-bit install folders
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

- write fstab mount file

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
install msys2 base system
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
install 64 bit compiler
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

MinGW64 GCC compiler isn't installed; maybe the download didn't work
Do you want to try it again?

-------------------------------------------------------------------------------
try again [y/n]: y
worf_@LAPTOP-5MROA8A5  C:\Dev\media-autobuild_suite   pre_vcs ≣ +1 ~0 -0 !                                                                                                          [21:29]
❯ .\media-autobuild_suite.bat
-------------------------------------------------------------------------------
install msys2 base system
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
install 64 bit compiler
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

MinGW64 GCC compiler isn't installed; maybe the download didn't work
Do you want to try it again?

-------------------------------------------------------------------------------
try again [y/n]:

**Comment by 1480c1** [comment]
try the noMintty option mentioned here https://github.com/m-ab-s/media-autobuild_suite/issues/1864

either way, I think this specific issue can be closed

**Comment by WorfKlingon** [comment]
I will try right now

**Comment by WorfKlingon** [comment]
I try the noMintty option with 1 value and i have the same issue...

**Comment by WorfKlingon** [comment]
The noMintty option no change at all the non blocking issue.
But the pre_vcs branch cannot compile the ffmpeg library:

> 00:29:28 ┌ ffmpeg git  ............................... [Recently updated]
> 00:29:28 ├ Changing options to comply to nonfree...
> FFmpeg and related apps will depend on CUDA SDK to run!
> 00:29:33 ├ Compiling shared FFmpeg...
> 00:29:34 ├ Running configure...
> 00:32:05 ├ Running make...
> 00:35:01 ├ Running install...
> 00:35:06 ├ Compiling static FFmpeg...
> 00:35:07 ├ Running configure...
> 00:37:32 ├ Running make...
> Likely error (tail of the failed operation logfile):
> make: *** [/build/ffmpeg-git/Makefile:124: ffprobe_g.exe] Error 1
> make: *** Waiting for unfinished jobs....
> collect2.exe: error: ld returned 1 exit status
> make: *** [/build/ffmpeg-git/Makefile:124: ffplay_g.exe] Error 1
> collect2.exe: error: ld returned 1 exit status
> make: *** [/build/ffmpeg-git/Makefile:124: ffmpeg_g.exe] Error 1
> LD      ffmpeg_g.exe
> C:/Dev/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Dev/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbPictureOperators.c.obj):EbPictureOperators.c:(.text+0x100): multiple definition of `picture_copy'; C:/Dev/media-autobuild_suite/local64/lib/libvmaf.a(feature_picture_copy.c.obj):picture_copy.c:(.text+0x90): first defined here
> collect2.exe: error: ld returned 1 exit status
> make: *** [/build/ffmpeg-git/Makefile:124: ffmpeg_g.exe] Error 1
> make failed. Check C:/Dev/media-autobuild_suite/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
> This is required for other packages, so this script will exit.
> 00:40:19   Creating diagnostics file...
> 
> All relevant logs have been anonymously uploaded to https://0x0.st/i7wb.zip
> Copy and paste [logs.zip](https://0x0.st/i7wb.zip) in the GitHub issue.
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
> Try running the build again at a later time.

Here the logs 
[i7wb.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5632967/i7wb.zip)

**Comment by 1480c1** [comment]
I see that vmaf 2.0.0 might have added some conflicting symbols

**Comment by WorfKlingon** [comment]
Do you want to do some tests?

**Comment by V1ncNet** [comment]
I've tested https://github.com/AOMediaCodec/SVT-AV1/pull/1620/commits/73897345be3000bc9eb9a185f35b22f9e5fbb711. Works on my system now.

As a workaround change L1442 in the `media-suite_compile.sh` script

https://github.com/m-ab-s/media-autobuild_suite/blob/929cdbae6cb3953d4f7475409cd6395e56f96298/build/media-suite_compile.sh#L1442

```diff
-   do_vcs "https://github.com/AOMediaCodec/SVT-AV1.git"; then
+   do_vcs https://github.com/1480c1/SVT-AV1.git#vmaf200 ;then
```

**Comment by 1480c1** [comment]
I personally prefer the route of just adding `do_patch "https://github.com/AOMediaCodec/SVT-AV1/pull/1620.patch" am` instead of changing the repo and branch in case the fork gets outdated

**Comment by WorfKlingon** [comment]
I agréé with patch. Its better for maintenance purposes

**Comment by V1ncNet** [comment]
Oh. Nice to know. I'm new to this repo and haven't read all the functions in the helper scripts. 😅 Great job btw.
