### ISSUE TITLE
Did something change the way mplayer/mencoder are build since 11th of February 2020?

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#1871]
using:
```
mencoder.exe -chapter 1-1 -ovc raw -noskip -vf scale,format=i420 -forcedsubsonly -nosub -nosound -mc 0 -lavdopts threads=8 -really-quiet -of rawvideo -o - -dvd-device "F:\TESTCL~1\discs\DVDs\TestDVD" dvd://1 | x264.exe --preset ultrafast --tff --sar 64:45 --non-deterministic --range tv --colormatrix bt709 --demuxer raw --input-res 720x576 --input-csp i420 --input-range tv --input-depth 8 --fps 25/1 --output-depth 8 --output "E:\Output\mencoder_interlaced_test.264" -
```
(piping raw interlaced to x264)
works fine with the MPlayer&Mencoder builds from https://www.videohelp.com/software/MPlayer, but current MBAS builds produce garbled output.

Testing with a few old MBAS builds I have the last working MBAS mencoder&mplayer builds i got is from the 11th of February 2020.

Since mplayer/mencoder itself haven't changed for ages,
I was wondering has something changed this then regarding the way mencoder/mplayer are build or is this probably due to some change in ffmpeg which broke interlaced raw output in mencoder/mplayer?

I just want to know someone can tell me whether this is an MBAS or an FFmpeg/Mplayer issue. :)

Cu Selur

**Comment by wiiaboo** [comment]
Who knows.
Lots of things changed in all the external libs you might include with it, unless you're just compiling mplayer by itself, in which case, it probably didn't change much, since it's basically dead.

**Comment by Selur** [comment]
I'm aware of the external libs, just wanted to make sure there wasn't any change in the build scripts. :)

**Comment by wiiaboo** [comment]
A lot has changed in the build scripts too, just not with mplayer directly.

**Comment by Selur** [comment]
okay, thanks for the info. :)

**Comment by 1480c1** [comment]
I'm not entirely inclined to try to debug anything related to mplayer/mencoder since I have never used them, but you could try seeing if you can reproduce the same issue with ffmpeg or other underlying tools to try to see if you can limit the potential issue points

**Comment by Selur** [comment]
Problem only happens with mencoder/mplayer and only when piping interlaced content (otherwise I would have stumbled over it earlier). FFmpeg etc. all work fine. -> I'll try building mencoder/mplayer with different dependencies to try whether I can pin down the issue somehow, just wanted to make sure nothing regarding the general building of mencoder/mplayer and it's dependencies changed.

**Comment by 1480c1** [comment]
Only thing I can think of would be splitting out svn's code from do_vcs into it's own static function, but that theoretically should not affect how it's built
