### ISSUE TITLE
64 bit Error running make when updating ffmpeg – [/build/ffmpeg-git/Makefile:124: ffmpeg_g.exe] Error 1

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1873]
21:48:55   Running git update for ffmpeg...
21:49:29 ┌ ffmpeg git  .................................. [Updates found]
21:49:29 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
21:49:34 ├ Compiling static FFmpeg...
21:49:36 ├ Running uninstall...
21:49:36 ├ Running configure...
21:53:14 ├ Running make...
Likely error (tail of the failed operation logfile):
make: *** [/build/ffmpeg-git/Makefile:124: ffmpeg_g.exe] Error 1
make: *** Waiting for unfinished jobs....
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:124: ffprobe_g.exe] Error 1
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:124: ffplay_g.exe] Error 1
LD      ffmpeg_g.exe
C:/MinGW64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW64/local64/lib/libSvtAv1Enc.a(EbPictureOperators.c.obj):EbPictureOperators.c:(.text+0x100): multiple definition of `picture_copy'; C:/MinGW64/local64/lib/libvmaf.a(feature_picture_copy.c.obj):picture_copy.c:(.text+0x90): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:124: ffmpeg_g.exe] Error 1
make failed. Check C:/MinGW64/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
22:00:37   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/i7nU.zip
Copy and paste [logs.zip](https://0x0.st/i7nU.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

[logs.zip](https://0x0.st/i7nU.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/5643220/ab-suite.make.log)

**Comment by 1480c1** [comment]
https://github.com/AOMediaCodec/SVT-AV1/pull/1620

**Comment by ycwan** [comment]
Run MAB and it completed without errors
