### ISSUE TITLE
qtdeclarative install

### ISSUE THREAD

**Issue by WorfKlingon** [m-ab-s/media-autobuild_suite#1874]
I have do a fresh git clone on the master: 8c6ee6719fc60271f251518bf3566e8358571dc0
ffmeg is ok, but qtdeclarative git does not install

> 13:47:49 ┌ qtdeclarative git  ........................ [Recently updated]
> 13:47:49 ├ Running qmake...
> 13:47:51 ├ Running install...
> Likely error (tail of the failed operation logfile):
> make[5]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph/d3d12'
> make[4]: *** [Makefile:55: release-install] Error 2
> make[4]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph/d3d12'
> make[3]: *** [Makefile:62: sub-d3d12-install_subtargets] Error 2
> make[3]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph'
> make[2]: *** [Makefile:88: sub-scenegraph-install_subtargets] Error 2
> make[2]: Leaving directory '/build/qtdeclarative-git/src/plugins'
> make[1]: *** [Makefile:429: sub-plugins-install_subtargets-ordered] Error 2
> make[1]: Leaving directory '/build/qtdeclarative-git/src'
> make: *** [Makefile:65: sub-src-install_subtargets] Error 2
> install failed. Check C:/Dev/media-autobuild_suite/build/qtdeclarative-git/ab-suite.install.log
> This is required for other packages, so this script will exit.
> 13:53:19   Creating diagnostics file...

here the logs:
[ihsY.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5647084/ihsY.zip)

**Comment by wordlesswind** [comment]
This seems to be because `fxc.exe` is in `C:\Program Files (x86)\Windows Kits\10\bin\10.0.<version>.0\x64` now.

So cannot find `fxc.exe` in `C:\Program Files (x86)\Windows Kits\10\bin\x64`.

[logs.zip](https://0x0.st/-BJ6.zip)

**Comment by Biswa96** [comment]
* Option 1. Disable d3d12 plugin in qtdeclarative, which msys2/mingw-packages does.
* Option 2. Create our own fxc binary, can be done with public documented dx APIs but something need to be done for the command line parameter as stated in the above Stackoverflow question.

**Comment by 1480c1** [comment]
I have been working on fixing qt5 and vlc compilation for a while, but to be honest, with all the issues it has for compiling git HEADs etc., I'm thinking of just dropping it all together

**Comment by Biswa96** [comment]
If that plugin improves any VLC experience I can provide the fxc code in msys2/mingw-packages repository but I am not familiar with the qmake .pro file syntaxes.

**Comment by 1480c1** [comment]
I think that qtdeclarative is required for vlc (not an optional build time dep)

**Comment by 1480c1** [comment]
Should be closed in 6a8bd6c27f4b5d07171d4f28cde031f9bb5dea74
