### ISSUE TITLE
Request: new Fraunhofer HHI VVC codec instead of VTM test codec

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1878]
github: [vvenc](https://github.com/fraunhoferhhi/vvenc) + [vvdec](https://github.com/fraunhoferhhi/vvdec)

Jamaika published [patches](https://forum.doom9.org/showthread.php?p=1930419#post1930419) but I am not sure how persistent they will be. Invited him here.

**Comment by 1480c1** [comment]
Duplicate of #1810
