### ISSUE TITLE
Request: [enable libnpp]

### ISSUE THREAD

**Issue by slyfox1186** [m-ab-s/media-autobuild_suite#1880]
I need to run scale_npp command which requires libnpp be enabled when compiling ffmpeg

I see this code in the file media-suite_helper.sh

```
verify_cuda_deps() {
    enabled cuda-sdk && do_removeOption --enable-cuda-sdk && do_addOption --enable-cuda-nvcc
    if enabled_any libnpp cuda-nvcc && [[ $license != "nonfree" ]]; then
        do_removeOption "--enable-(cuda-nvcc|libnpp)"
    fi
    if enabled libnpp && [[ $bits == 32bit ]]; then
        echo -e "${orange}libnpp is only supported in 64-bit.${reset}"
        do_removeOption --enable-libnpp
    fi
    if enabled_any libnpp cuda-nvcc && [[ -z $CUDA_PATH || ! -d $CUDA_PATH ]]; then
        echo -e "${orange}CUDA_PATH environment variable not set or directory does not exist.${reset}"
        do_removeOption "--enable-(cuda-nvcc|libnpp)"
    fi
    if enabled libnpp && [[ ! -f "$CUDA_PATH/lib/x64/nppc.lib" ]]; then
        do_removeOption --enable-libnpp
    fi
    if ! disabled cuda-llvm && do_pacman_install clang; then
        do_removeOption --enable-cuda-nvcc
    else
        do_removeOption --enable-cuda-llvm
        do_addOption --disable-cuda-llvm
    fi
    if enabled cuda-nvcc; then
        if ! get_cl_path; then
            echo -e "${orange}MSVC cl.exe not found in PATH or through vswhere; needed by nvcc.${reset}"
            do_removeOption --enable-cuda-nvcc
        elif enabled cuda-nvcc && ! nvcc.exe --help &> /dev/null &&
            ! "$(cygpath -sm "$CUDA_PATH")/bin/nvcc.exe" --help &> /dev/null; then
            echo -e "${orange}nvcc.exe not found in PATH or installed in CUDA_PATH.${reset}"
            do_removeOption --enable-cuda-nvcc
        fi
    fi
    enabled_any libnpp cuda-nvcc || ! disabled cuda-llvm
```

What do I need to modify to have ffmpeg build with this library enabled?

**Comment by wiiaboo** [comment]
You need to run the instructions like everyone else. That's what they're there for: https://github.com/m-ab-s/media-autobuild_suite#notes-about-cuda-sdk

**Comment by slyfox1186** [comment]
wiiaboo you do great and it much appreciated. I am an amateur coder asking for advice. Don't forget a lot of people aren't as good as you at this and asking a question isn't always a lack of trying on the persons part to figure the situation out.

**Comment by wiiaboo** [comment]
Do you really need scale_npp? Why not scale_cuda?

**Comment by wiiaboo** [comment]
Before you paste [this old stackoverflow answer](https://stackoverflow.com/questions/55687189/how-to-use-gpu-to-accelerate-the-processing-speed-of-ffmpeg-filter/55747785#55747785), do note that scale_cuda and scale_npp are basically feature-equivalent by now (since early November), scale_cuda only missing a way to select a different output format, but there's alternatives.
