### ISSUE TITLE
Is this claim in the suite true and is there a source for it?

### ISSUE THREAD

**Issue by Kaos-Industries** [m-ab-s/media-autobuild_suite#1883]
[Full question here](https://superuser.com/questions/1610747/is-fdk-aac-still-better-than-ffmpegs-native-aac-encoder) if you would prefer to answer there, might also get a broader audience.

I noticed that the suite includes the following:

> Build FDK-AAC library and binary? [AAC-LC/HE/HEv2 codec]
1 = Yes
2 = No

> Note: FFmpeg's aac encoder is no longer experimental and considered equal or
better in quality from 96kbps and above. It still doesn't support AAC-HE/HEv2
so if you need that or want better quality at lower bitrates than 96kbps,
use FDK-AAC.

However, I can find no reference to this in FFmpeg documentation, and the [relevant wiki page](https://trac.ffmpeg.org/wiki/Encode/AAC) itself still claims FDK-AAC is superior. 

Is this claim true, and what was the source for this it?

**Comment by 1480c1** [comment]
original commit https://github.com/m-ab-s/media-autobuild_suite/commit/1b0a01a884e9a1e01c32ca24dda52646973e3703
commit mentioned in the message http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=d9791a8656b5580756d5b7ecc315057e8cd4255e

https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio#AudioencodersFFmpegcanuse

best note I could find related to this is
> NOTE: as of 2017 `libfdk_aac` may not always be better than `aac` for AAC-LC. The built in aac encoder is quite good.

I personally don't know/don't have an opinion

**Comment by Kaos-Industries** [comment]
It seems that the original source for this claim was the FFmpeg documentation, and was removed from `ffmpeg` in May 2020 due to being unsubstantiated. Detailed info can be found [here](https://superuser.com/a/1610768/323079). If it was removed from the documentation, then maybe it would be a good idea to remove the above notice from the suite so as not to spread misconceptions about the superiority of either encoder - at least, until there is a current source for it.

**Comment by wiiaboo** [comment]
> then maybe it would be a good idea to remove the above notice from the suite so as not to spread misconceptions about the superiority of either encoder - at least, until there is a current source for it.

![image](https://c.tsu.re/EI.png)

**Comment by Kaos-Industries** [comment]
Apologies, I missed that, and thanks for the fast work.
