### ISSUE TITLE
Using binaries with Cygwin

### ISSUE THREAD

**Issue by Kaos-Industries** [m-ab-s/media-autobuild_suite#1884]
I'm trying to use the compiled binaries under Cygwin. When I simply copy them over and run them I get the error:

`/usr/local/bin/ffmpeg: line 3: /usr/bin/winpty: No such file or directory`

Deleting the `ffmpeg` wrapper file fixes this and the `ffmpeg` binary then seems to run fine under Cygwin. Can I expect it to work without issue from hereon, or are other things likely to be broken without the MSYS environment?

**Comment by 1480c1** [comment]
the binaries (the .exe, not the wrappers) generally are supposed to work without msys2 specific stuff, aka only windows dlls if any

**Comment by wiiaboo** [comment]
There should be a `winpty` in cygwin as well.
Without it, ffmpeg/mpv's console controls are broken, last time I checked.
If you don't expect to interact with them, just run the .exes directly.
