### ISSUE TITLE
Request: x265 modifications for AviSynth+ or VapourSynth native input

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1887]
[Yuuki-Asuna mod for AviSynth+](https://github.com/msg7086/x265-Yuuki-Asuna/commit/0bbb886cbbcf5264c78c93cb96aab72c6873fe0f)

[DJATOM's aMod for VapourSynth](https://github.com/DJATOM/x265-aMod)

May forking and merging them in MABS own repo be bearable efforts? Provided they are possible in MinGW only.

**Comment by wiiaboo** [comment]
Apply them using [Custom patches](https://github.com/m-ab-s/media-autobuild_suite#custom-patches).

**Comment by LigH-de** [comment]
That may require a bit cooperation, I don't have enough experience to create the required patch files. But I will see if the doom9 members can help creating them... thank you for the advice.
