### ISSUE TITLE
[mingw64] [mediainfo] [clang]

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1888]
```bash
10:37:47 ┌ mediainfo git  ............................ [Recently updated]
10:37:47 ├ Running autogen...
10:38:27 ├ Running configure...
10:39:23 ├ Running install...
Likely error (tail of the failed operation logfile):
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(bidi.o):(.text+0x12c): undefined reference to `uc_bidi_category'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0x51): undefined reference to `uc_combining_class'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0x80): undefined reference to `uc_combining_class'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0xad): undefined reference to `uc_joining_type'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0xe2): undefined reference to `uc_joining_type'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0x178): undefined reference to `uc_script'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0x1dd): undefined reference to `uc_script'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0x32f): undefined reference to `uc_script'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:326: mediainfo.exe] Ошибка 1
```
install failed. Check D:/ffmpeg-autobuild-clang/build/mediainfo-git/Project/GNU/CLI/ab-suite.install.log
[logs.zip](https://0x0.st/iCP1.zip)

**Comment by 1480c1** [comment]
seems I may have found my first pkgconf bug

**Comment by 1480c1** [comment]
https://github.com/MediaArea/MediaInfo/pull/515

**Comment by kliffgomel** [comment]
So there was a fix for this error?
It still doesn't work for me.

Likely error (tail of the failed operation logfile):
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(bidi.o):(.text+0x12c): undefined reference to `uc_bidi_category'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0x51): undefined reference to `uc_combining_class'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0x80): undefined reference to `uc_combining_class'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0xad): undefined reference to `uc_joining_type'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0xe2): undefined reference to `uc_joining_type'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0x178): undefined reference to `uc_script'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0x1dd): undefined reference to `uc_script'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: D:\ffmpeg-autobuild-clang\msys64\mingw64\lib/libidn2.a(context.o):(.text+0x32f): undefined reference to `uc_script'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:326: mediainfo.exe] Error 1

[logs.zip](https://0x0.st/-K6h.zip)
