### ISSUE TITLE
Request: adding support for TwoLAME

### ISSUE THREAD

**Issue by zedd-0** [m-ab-s/media-autobuild_suite#1892]
hello,

is it possible to add the TwoLAME sources to your ab-suite?
i want to build a standalone binary. (twolame.exe)
https://sourceforge.net/projects/twolame/

thanks a lot

**Comment by wiiaboo** [comment]
No point, it hasn't been updated since last year.
```bash
source /build/media-suite_helper.sh
cd /build
do_wget https://github.com/njh/twolame/releases/download/0.4.0/twolame-0.4.0.tar.gz
do_separate_conf && do_make && do_install frontend/twolame.exe bin-audio/
```
