### ISSUE TITLE
vidstab's new file format is broken in Windows

### ISSUE THREAD

**Issue by tcmbackwards** [m-ab-s/media-autobuild_suite#1893]
vid.stab changed to a binary format for the transforms file which has portability problems under mingw. They've had an issue open for a month now but it hasn't been fixed yet.

Rolling back to https://github.com/georgmartius/vid.stab.git#commit=e7715fc fixes it.

**Comment by 1480c1** [comment]
I am assuming you are talking about https://github.com/georgmartius/vid.stab/commit/3c4dba55bb7ae712cbba65685d56d188640db266 ?

**Comment by tcmbackwards** [comment]
Correct. This is the issue: https://github.com/georgmartius/vid.stab/issues/104
You can make the transforms.trf file, but the second pass can't actually use it and they never hooked up the 'fileformat' option to ffmpeg to use the old format.

**Comment by GyanD** [comment]
The issue is that it now uses the binary format by default, instead of the ASCII, which can be a breaking change. And it should have been configurable by an API user. I can modify the ffmpeg wrapper to access and set the serialization mode. But it's best if vidstab adds it to VSMotionDetectConfig, and update LIBVIDSTAB_VERSION.

**Comment by 1480c1** [comment]
@tcmbackwards can you try again? I tried myself and I didn't see any obvious indicator that it failed (other than the fact that my source video didn't really have anything that would probably qualify as extreme motion)

**Comment by tcmbackwards** [comment]
The indicator is in the ffmpeg log. Vidstab has a whole section which lists its parameters. In pass 2, it loads the transforms file, but when it fails to parse it a bunch of "Cannot parse localmotion" errors are thrown.

The problem is still there, this was built just last night. The vid.stab github hasn't been updated since November 10.

`
[Parsed_vidstabtransform_2 @ 0000025cade27100] Video transformation/stabilization settings (pass 2/2):
[Parsed_vidstabtransform_2 @ 0000025cade27100]     input     = transforms.trf
[Parsed_vidstabtransform_2 @ 0000025cade27100]     smoothing = 20
[Parsed_vidstabtransform_2 @ 0000025cade27100]     optalgo   = gauss
[Parsed_vidstabtransform_2 @ 0000025cade27100]     maxshift  = -1
[Parsed_vidstabtransform_2 @ 0000025cade27100]     maxangle  = -1.000000
[Parsed_vidstabtransform_2 @ 0000025cade27100]     crop      = Black
[Parsed_vidstabtransform_2 @ 0000025cade27100]     relative  = True
[Parsed_vidstabtransform_2 @ 0000025cade27100]     invert    = False
[Parsed_vidstabtransform_2 @ 0000025cade27100]     zoom      = -15.000000
[Parsed_vidstabtransform_2 @ 0000025cade27100]     optzoom   = Off (0)
[Parsed_vidstabtransform_2 @ 0000025cade27100]     interpol  = Bi-Cubic (3)
[vid.stab - serialization @ 000000c41f5fe278] Cannot parse localmotion!
    Last message repeated 18 times
    `
