### ISSUE TITLE
[mingw32] lenstool/lensfun patch isn't found

### ISSUE THREAD

**Issue by ghost** [m-ab-s/media-autobuild_suite#1898]
``` bash
        Patch could not be applied with `patch`. Continuing without patching.
23:50:16 └ lenstool.patch  ..................................... [Failed]
Error 404 while downloading https://github.com/Alexpux/MINGW-packages/raw/master/mingw-w64-lensfun/lenstool.patch
<Ctrl+c> to cancel build or <Enter> to continue
```

Looks like the patch file was removed some time ago: https://github.com/msys2/MINGW-packages/commit/859fc718f8985a3d02f0c2e38e08ab8c9358fc77#diff-c1ec2486a142078355cda5010d811d90c59fdb34117bbd4119a56db3854d96dd

I'll upload logs when this current build completes.

**Comment by 1480c1** [comment]
I haven't tested the lensfun option, so I will after I fix a few other issues with the default build

**Comment by 1480c1** [comment]
Fixed the patch
