### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by jvsdr** [m-ab-s/media-autobuild_suite#1901]
![Screenshot_2](https://user-images.githubusercontent.com/10999602/104796443-fb6e0580-5794-11eb-87ba-b21a3fa6dbd3.png)
I think this repo is empty or something not working properly.
https://gitlab.com/m-ab-s/libsoxr

Log file: https://0x0.st/-z75.zip

**Comment by 1480c1** [comment]
Try again, I accidentally messed up updating the settings

**Comment by jvsdr** [comment]
Ty, I hope I've helped :) cheers
