### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by bladem2003** [m-ab-s/media-autobuild_suite#1902]
I get the error below when compiling.

 [logs.zip](https://0x0.st/-iHU.zip)

![media](https://user-images.githubusercontent.com/47271861/104837083-0622ba80-58bb-11eb-99b7-e95d0b7594c1.png)

**Comment by 1480c1** [comment]
Closing in favor of https://github.com/m-ab-s/media-autobuild_suite/issues/1903
