### ISSUE TITLE
FFMPEG not compiling - libavdevice/avdeviceres.o Error 1

### ISSUE THREAD

**Issue by lukasmd1989** [m-ab-s/media-autobuild_suite#1909]
make: *** [/build/ffmpeg-git/ffbuild/common.mak:93: libavdevice/avdeviceres.o] Error 1

`[1m┌ ffmpeg git (B[m ......................................... [[93mRecently updated(B[m]
[1m├(B[m Changing options to comply to nonfree...
[93mFFmpeg and related apps will depend on CUDA SDK to run!(B[m
[1m├(B[m Compiling [1mshared(B[m FFmpeg...
[1m├(B[m Running configure...
[1m├(B[m Running make...
Likely error (tail of the failed operation logfile):
C:\media-autobuild_suite\msys64\mingw64\bin\windres.exe: preprocessing failed.

make: *** [/build/ffmpeg-git/ffbuild/common.mak:93: libavdevice/avdeviceres.o] Error 1
make: *** Waiting for unfinished jobs....
WINDRES	libavdevice/avdeviceres.o
C:/media-autobuild_suite/build/ffmpeg-git/libavdevice/avdeviceres.rc:25:10: fatal error: libavdevice/version.h: No such file or directory
   25 | #include "libavdevice/version.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

C:\media-autobuild_suite\msys64\mingw64\bin\windres.exe: preprocessing failed.

make: *** [/build/ffmpeg-git/ffbuild/common.mak:93: libavdevice/avdeviceres.o] Error 1
[31mmake failed. Check C:/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.make.log(B[m
[31mThis is required for other packages, so this script will exit.(B[m
  Creating diagnostics file...

[32mAll relevant logs have been anonymously uploaded to https://0x0.st/-oQP.zip`

https://0x0.st/-oQP.zip

**Comment by fdsdev** [comment]
Comfirmed, same problem here.

**Comment by gammaray10k** [comment]
Confirmed. Still occurs.

**Comment by 1480c1** [comment]
Still occurs even after you delete build/ffmpeg-git?

**Comment by 1480c1** [comment]
https://github.com/msys2/MINGW-packages/pull/7870

**Comment by gammaray10k** [comment]
Still occurs.  I followed your direction and deleted build/ffmpeg-git. I ran the script. It ran into an issue with libbluray and the librav1e patch. I ran it again, no librav1e or libbluray issue but it errored out at the same place with the original
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5907581/logs.zip)
 error:

┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling shared FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
F:\My_Autobuild\msys64\mingw64\bin\windres.exe: preprocessing failed.
make: *** [/build/ffmpeg-git/ffbuild/common.mak:93: libavdevice/avdeviceres.o] Error 1
make: *** Waiting for unfinished jobs....
WINDRES libavdevice/avdeviceres.o
F:/My_Autobuild/build/ffmpeg-git/libavdevice/avdeviceres.rc:25:10: fatal error: libavdevice/version.h: No such file or directory
   25 | #include "libavdevice/version.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
F:\My_Autobuild\msys64\mingw64\bin\windres.exe: preprocessing failed.
make: *** [/build/ffmpeg-git/ffbuild/common.mak:93: libavdevice/avdeviceres.o] Error 1

**Comment by ahmadrr** [comment]
Same problem, even when manually running configure and make install

**Comment by lazka** [comment]
should be fixed now

**Comment by gammaray10k** [comment]
@lazka @1480c1 I retried it and it works now. It did ask me to install packages that were already previously installed. Once I said yes, everything went through fine. I tried it twice and it works. We need the OP to test it out.

**Comment by rdp** [comment]
Did a particular commit fix this do you know?

**Comment by 1480c1** [comment]
Inside https://github.com/msys2/MINGW-packages/pull/7870 @lazka cherry-picked https://sourceware.org/bugzilla/show_bug.cgi?id=4356 into binutils
