### ISSUE TITLE
Note: Multicoreware asks to refresh x265 clone

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1911]
Aruna Matheswaran apologized:

> We had to recently strip a commit that got pushed into Release_3.5 branch due to some unavoidable reasons. Hence, we request all those who auto-update x265 to refresh your git repos so that we'll be on the same page.

So remove the folder **build/x265_git-git** once before the next build.

**Comment by 1480c1** [comment]
I believe we are fine since we do not use git pull but rather git fetch then git reset and we don't use the Release _3.5 branch

**Comment by wiiaboo** [comment]
> 
> 
> I believe we are fine since we do not use git pull but rather git fetch then git reset and we don't use the Release _3.5 branch

Exactly because of some upstreams (x264, mpv, that I remember) sometimes doing force pushes like this.
