### ISSUE TITLE
[mingw32] [mplayer] configure fails to detect SSSE3 support

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1912]
**config.log**
```
============ Checking for assembler (ccache gcc ) ============
Result is: failed (Upgrade binutils to 2.16.92 or use --disable-ssse3 etc.)
##########################################
```
binutils is at version 2.36.1-1; strange that it wants to use "ccache gcc" as assembler.

If I wanted to inject `--disable-ssse3` into the set of configure parameters, where should that happen?

[ab-suite.configure.log](https://github.com/m-ab-s/media-autobuild_suite/files/5951942/ab-suite.configure.log)

**Comment by 1480c1** [comment]
Can you check `config.log`?

**Comment by LigH-de** [comment]
I posted quite the whole chapter about it, searched elsewhere but did not find any more details or a source file being compiled, only some SSE instructions in the configure script ... can post a whole archive with files tomorrow, it's on another computer.

**Comment by LigH-de** [comment]
Here the saved logs from the Win32 build; the Win64 build passed without errors. I guess the reason may be in the detected CPU family...

[mplayer_w32_logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5956416/mplayer_w32_logs.zip)

**Comment by LigH-de** [comment]
Appears to be fixed.
