### ISSUE TITLE
libidn2 2.3.0 autoreconf failed. 

### ISSUE THREAD

**Issue by chirrilover** [m-ab-s/media-autobuild_suite#1915]
[mingw64]
libidn2 2.3.0  ........................................... [Not installed]
├ libidn2-2.3.0  ....................................... [File up-to-date]
├ Running extract...
├ Running autoreconf...
Likely error (tail of the failed operation logfile):
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: configure.ac: not using Intltool
autoreconf: Can't exec "gtkdocize": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 293.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5977120/logs.zip)

**Comment by quanco** [comment]
I got it solved by installing gtk-doc on mingw64
pacman -S mingw-w64-x86_64-gtk-doc

**Comment by Biswa96** [comment]
> autoreconf: Can't exec "gtkdocize"

Tip:

```
$ pacman -F /mingw64/bin/gtkdocize
mingw64/bin/gtkdocize is owned by mingw64/mingw-w64-x86_64-gtk-doc 1.33.2-1
```

**Comment by chirrilover** [comment]
Wow! quanco and Biswa96. Even before I try it. Thank you, I'm amazed. I suspected the solution was the same but I'm a "./configure-make-make install" kind of guy (or a "yum" guy, come to think of it). 

The tip to find the owner, excellent.

Trying it... 
Installed gtk-docs (mabs asked me if I wanted to uninstall it. I said no).

Well, this solution must work somehow. wiiabooo closed the thread 23 seconds ago...

**Comment by chirrilover** [comment]
This issue, Issue #1915 should not have been closed in this manner

  Running git update for curl...
┌ curl git  ........................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
make[3]: Leaving directory '/build/curl-git/build-64bit/docs/cmdline-opts'
make[2]: Leaving directory '/build/curl-git/build-64bit/docs'
make[2]: Entering directory '/build/curl-git/build-64bit/src'
  CCLD     curl.exe
gcc.exe: error: C:/mabs/msys64/mingw64/lib/libidn2.dll.a: No such file or directory
make[2]: *** [Makefile:997: curl.exe] Error 1
make[2]: Leaving directory '/build/curl-git/build-64bit/src'
make[1]: *** [Makefile:2156: all-recursive] Error 1
make[1]: Leaving directory '/build/curl-git/build-64bit/src'
make: *** [Makefile:1249: all-recursive] Error 1

$ pacman -F libidn2.dll.a
mingw32/mingw-w64-i686-libidn2 2.3.0-1
    mingw32/lib/libidn2.dll.a
mingw64/mingw-w64-x86_64-libidn2 2.3.0-1 [installed]
    mingw64/lib/libidn2.dll.a
msys/libidn2-devel 2.3.0-1 (development)
    usr/lib/libidn2.dll.a


It's evident running 'pacman -S mingw-w64-x86_64-gtk-doc' did not install file libidn2.dll.a in the proper folder.

I hope that deleting build for libidn2 2.3.0-1 and running batch file again will then solve this issue

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5978233/logs.zip)
