### ISSUE TITLE
Re: Issue #1915

### ISSUE THREAD

**Issue by chirrilover** [m-ab-s/media-autobuild_suite#1916]
Issue #1915 should not have been closed in this manner

Running git update for curl...
┌ curl git ........................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
make[3]: Leaving directory '/build/curl-git/build-64bit/docs/cmdline-opts'
make[2]: Leaving directory '/build/curl-git/build-64bit/docs'
make[2]: Entering directory '/build/curl-git/build-64bit/src'
CCLD curl.exe
gcc.exe: error: C:/mabs/msys64/mingw64/lib/libidn2.dll.a: No such file or directory
make[2]: *** [Makefile:997: curl.exe] Error 1
make[2]: Leaving directory '/build/curl-git/build-64bit/src'
make[1]: *** [Makefile:2156: all-recursive] Error 1
make[1]: Leaving directory '/build/curl-git/build-64bit/src'
make: *** [Makefile:1249: all-recursive] Error 1

$ pacman -F libidn2.dll.a
mingw32/mingw-w64-i686-libidn2 2.3.0-1
mingw32/lib/libidn2.dll.a
mingw64/mingw-w64-x86_64-libidn2 2.3.0-1 [installed]
mingw64/lib/libidn2.dll.a
msys/libidn2-devel 2.3.0-1 (development)
usr/lib/libidn2.dll.a

It's evident running 'pacman -S mingw-w64-x86_64-gtk-doc' did not install file libidn2.dll.a in the proper folder.

I hope that deleting build for libidn2 2.3.0-1 and running batch file again will then solve this issue

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5978235/logs.zip)

**Comment by 1480c1** [comment]
A few things, `C:/mabs/msys64/mingw64/lib/libidn2.dll.a` should not be there as we explicitly move `.dll.a` files so gcc cannot find them, `gtk-doc` does not provide `libidn2.dll.a` as you noted

**Comment by wiiaboo** [comment]
Can't reproduce the issue.
Force recompilation of both libidn2 and libpsl with the suite updated to 54cab670 and uninstall that gtk-doc crap that's not needed for anything.

**Comment by wiiaboo** [comment]
And don't open new issues replying to closed issues. Just reopen the old one or ask to reopen.

**Comment by chirrilover** [comment]
@1480c1 Sorry, my mistake, I should have wrote that by installing gtk-doc by executing 'pacman -S mingw-w64-x86_64-gtk-doc' I solved the previous issue regarding the installation of libidn2 2.3.0-1 but that that did not install file libidn2.dll.a in the proper folder.

@wiiaboo Could not force recompilation of libidn2 and libpsl even after suite updated (by dragging update_suite.sh to mintty shortcut. It showed updated to 54cab67). No mention of how to force it in doc/forcing-recompilations.md, for these libraries. Deleting their build folders did not do the trick either. Both showed installed and up-to-date every time I ran the batch file. Uninstalled gtk-doc. Issue stayed as described at the beginning of this thread.

@wiiaboo @1480c1 Since issue was not reproduced on your side, I deleted /msys64 and /local64, not the /build folder, and ran the batch file again.

That did the trick for this issue

**Comment by wiiaboo** [comment]
> Most libs use pkg-config files to check if they exist, so for most libs in this list all you have to do is delete the corresponding <libname>.pc file in /local32/lib/pkgconfig/ or /local64/lib/pkgconfig

libidn2 and libpsl are such cases too.
