### ISSUE TITLE
Request: Add support for building in Blackmagic Decklink support

### ISSUE THREAD

**Issue by kangstarr** [m-ab-s/media-autobuild_suite#1917]
It would be great to add support for building ffmpeg with Blackmagic Decklink support. It would require the end-user to download the [Blackmagic Decklink SDK](https://www.blackmagicdesign.com/developer/product/capture-and-playback) on their own but if the suite would support it maybe it could just ask the end-user to point to the location that they've downloaded and unpacked the Blackmagic Decklink SDK files. This obviously would only be available if non-free licensing were chosen as well.

The purpose of this request is to allow the end-user to use Blackmagic hardware in the professional AV realm where there are needs for certain types of hardware which require SDI input/output for video/audio.

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/blob/54cab67080fccb40589b1ed9a2dd4892ceaa2bc5/build/media-suite_compile.sh#L1391

Seems like we already do

**Comment by kangstarr** [comment]
How does one enable it to include in the build?

**Comment by 1480c1** [comment]
If you use option 1 for the ffmpeg choice, you can add `--enable-decklink` to the ffmpeg_options.txt or you can just choose 4 for full build

**Comment by 1480c1** [comment]
I myself don't have one so once you have it built, I have no idea how to use it

**Comment by kangstarr** [comment]
Thank you for the quick response. I've used it in the past on some linux builds that others have compiled. If I have any issues I'll open a new ticket. Thanks again!
