### ISSUE TITLE
[mingw64] [gpac] [clang] Make error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1918]
Running make...
Likely error (tail of the failed operation logfile):
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xa7cf): undefined reference to `__imp_nghttp2_session_send'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xa7ff): undefined reference to `__imp_nghttp2_strerror'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xa8b0): undefined reference to `__imp_nghttp2_session_want_read'
D:\ffmpeg-autobuild-clang\msys64\mingw64\bin\ld: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xa8c9): undefined reference to `__imp_nghttp2_session_want_read'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:56: gpac.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/build-64bit/applications/gpac'
make[1]: *** [Makefile:41: apps] Error 2
make[1]: Leaving directory '/build/gpac-git/build-64bit/applications'
make: *** [Makefile:14: all] Error 2

[logs.zip](https://0x0.st/-8n2.zip)

**Comment by kliffgomel** [comment]
same for gcc compiler
[logs.zip](https://0x0.st/-8nF.zip)

**Comment by BlackScreen** [comment]
Same problem here:

```
18:12:49   Running git update for gpac...
18:12:52 ┌ gpac git  .................................... [Updates found]
18:12:53 ├ Running configure...
18:13:33 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdfef): undefined reference to `__imp_nghttp2_session_send'
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdff6): undefined reference to `__imp_nghttp2_session_mem_recv'
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe15c): undefined reference to `__imp_nghttp2_strerror'
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe1d1): undefined reference to `__imp_nghttp2_strerror'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:56: gpac.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/build-64bit/applications/gpac'
make[1]: *** [Makefile:41: apps] Error 2
make[1]: Leaving directory '/build/gpac-git/build-64bit/applications'
make: *** [Makefile:14: all] Error 2
make failed. Check C:/Development/MABS_All/build/gpac-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
18:14:34   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-KKY.zip
Copy and paste [logs.zip](https://0x0.st/-KKY.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by Biswa96** [comment]
Make sure `mingw-w64-x86_64-nghttp2` package is installed. Those functions are exported from nghttp2 library. Example:

```sh
$ nm /mingw64/lib/libnghttp2.dll.a | grep -i __imp_nghttp2_strerror
0000000000000000 I __imp_nghttp2_strerror
```

**Comment by Biswa96** [comment]
I am not sure why it needs it but make check if `mingw-w64-x86_64-nghttp2` package is installed. Those functions are exported from nghttp2 library. Example:

```sh
$ nm /mingw64/lib/libnghttp2.dll.a | grep -i __imp_nghttp2_strerror
0000000000000000 I __imp_nghttp2_strerror
```

**Comment by 1480c1** [comment]
Can you try on  https://github.com/m-ab-s/media-autobuild_suite/commit/a4afbe24101ed61b823f443e1f37dd7ed2d5192a?

**Comment by kliffgomel** [comment]
The error still persists.
Likely error (tail of the failed operation logfile):
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdfef): undefined reference to `__imp_nghttp2_session_send'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdff6): undefined reference to `__imp_nghttp2_session_mem_recv'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe15c): undefined reference to `__imp_nghttp2_strerror'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe1d1): undefined reference to `__imp_nghttp2_strerror'
collect2.exe: error: ld returned 1 exit status
[logs.zip](https://0x0.st/-K2V.zip)

**Comment by Patman86** [comment]
Compiling MP4box directly from the source folder (without suite) does not work either.  I think it's either due to gpac or msys / mingw

**Comment by Weezzel** [comment]
Still getting error after code change:

13:44:22 ┌ gpac git  ................................. [Recently updated]
13:44:22 ├ Running configure...
13:44:38 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdfef): undefined reference to `__imp_nghttp2_session_send'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdff6): undefined reference to `__imp_nghttp2_session_mem_recv'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe15c): undefined reference to `__imp_nghttp2_strerror'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe1d1): undefined reference to `__imp_nghttp2_strerror'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:56: gpac.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/build-64bit/applications/gpac'
make[1]: *** [Makefile:41: apps] Error 2
make[1]: Leaving directory '/build/gpac-git/build-64bit/applications'
make: *** [Makefile:14: all] Error 2
make failed. Check C:/MABS/build/gpac-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
13:45:31   Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6055223/logs.zip)

**Comment by 1480c1** [comment]
Try again on https://github.com/m-ab-s/media-autobuild_suite/commit/dae9d3f43ebbfacc1c73c6a787f6cfbdf5a8d0ab

**Comment by Barough** [comment]
qpac/mp4box builds fine here now

**Comment by kliffgomel** [comment]
It works!
