### ISSUE TITLE
[mingw64] [curl] undefined reference to `__imp_gnutls_free' c8f93f1

### ISSUE THREAD

**Issue by chirrilover** [m-ab-s/media-autobuild_suite#1920]
Running git update for curl...
┌ curl git  ........................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
make[2]: Entering directory '/build/curl-git/build-64bit/src'
  CCLD     curl.exe
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib/.libs/libcurl.a(libcurl_la-gtls.o):gtls.c:(.text+0x143a): undefined reference to `__imp_gnutls_free'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib/.libs/libcurl.a(libcurl_la-gtls.o):gtls.c:(.text+0x14a8): undefined reference to `__imp_gnutls_free'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:997: curl.exe] Error 1
make[2]: Leaving directory '/build/curl-git/build-64bit/src'
make[1]: *** [Makefile:2156: all-recursive] Error 1
make[1]: Leaving directory '/build/curl-git/build-64bit/src'
make: *** [Makefile:1249: all-recursive] Error 1
make failed. Check C:/mabs/build/curl-git/build-64bit/ab-suite.make.log

HEAD is now at c8f93f1 mpv: fix bug with libvidstab
Suite up-to-date.
If you had an issue, please report it in GitHub.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6039037/logs.zip)

**Comment by chirrilover** [comment]
Tried after deleting curl-git in folder /build to no avail.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6039242/logs.zip)

**Comment by chirrilover** [comment]
Forced recompilation of gnutls too and deleted build folder for curl. This time process did not create a curl-git 


[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6044679/logs.zip)

**Comment by chirrilover** [comment]
Delete build folder for gnutls and curl. Forced recompilation on both. To no avail....

 Running git clone for curl...
┌ curl git  ........................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
make[2]: Entering directory '/build/curl-git/build-64bit/src'
  CCLD     curl.exe
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib/.libs/libcurl.a(libcurl_la-gtls.o):gtls.c:(.text+0x143a): undefined reference to `__imp_gnutls_free'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib/.libs/libcurl.a(libcurl_la-gtls.o):gtls.c:(.text+0x14a8): undefined reference to `__imp_gnutls_free'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:997: curl.exe] Error 1
make[2]: Leaving directory '/build/curl-git/build-64bit/src'
make[1]: *** [Makefile:2156: all-recursive] Error 1
make[1]: Leaving directory '/build/curl-git/build-64bit/src'
make: *** [Makefile:1252: all-recursive] Error 1

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6045218/logs.zip)

**Comment by chirrilover** [comment]
So is it trying to build curl.exe again even though it's already in /mingw64/bin/? (curl.exe does exist in /mingw64/bin/)

So I did this:

$ pacman -F /mingw64/bin/curl.exe
warning: database file for 'mingw32' does not exist (use '-Fy' to download)
warning: database file for 'mingw64' does not exist (use '-Fy' to download)
warning: database file for 'msys' does not exist (use '-Fy' to download)


$ pacman -Fy /mingw64/bin/curl.exe
:: Synchronizing package databases...
 mingw32                                       4.0 MiB  8.33 MiB/s 00:00 [#######################################] 100%
 mingw32.sig                                 438.0   B  0.00   B/s 00:00 [#######################################] 100%
 mingw64                                       4.1 MiB  8.44 MiB/s 00:00 [#######################################] 100%
 mingw64.sig                                 438.0   B  0.00   B/s 00:00 [#######################################] 100%
 msys                                       1167.0 KiB  6.16 MiB/s 00:00 [#######################################] 100%
 msys.sig                                    438.0   B  0.00   B/s 00:00 [#######################################] 100%
mingw64/bin/curl.exe is owned by mingw64/mingw-w64-x86_64-curl 7.75.0-1

**Why ":: Synchronizing package databases..." said all the time that everything was up-to-date every time I ran the batch file?**

$ pacman -S mingw-w64-x86_64-curl
warning: mingw-w64-x86_64-curl-7.75.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-curl-7.75.0-1

Total Installed Size:  2.84 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                           [#######################################] 100%
(1/1) checking package integrity                                         [#######################################] 100%
(1/1) loading package files                                              [#######################################] 100%
(1/1) checking for file conflicts                                        [#######################################] 100%
(1/1) checking available disk space                                      [#######################################] 100%
warning: could not get file information for mingw64/lib/libcurl.dll.a
:: Processing package changes...
(1/1) reinstalling mingw-w64-x86_64-curl                                 [#######################################] 100%

After doing this I still get:

  Running git update for curl...
┌ curl git  ........................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
make[2]: Entering directory '/build/curl-git/build-64bit/src'
  CCLD     curl.exe
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib/.libs/libcurl.a(libcurl_la-gtls.o):gtls.c:(.text+0x143a): undefined reference to `__imp_gnutls_free'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib/.libs/libcurl.a(libcurl_la-gtls.o):gtls.c:(.text+0x14a8): undefined reference to `__imp_gnutls_free'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:997: curl.exe] Error 1
make[2]: Leaving directory '/build/curl-git/build-64bit/src'
make[1]: *** [Makefile:2156: all-recursive] Error 1
make[1]: Leaving directory '/build/curl-git/build-64bit/src'
make: *** [Makefile:1249: all-recursive] Error 1
make failed. Check C:/mabs/build/curl-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

I only know that I wanted to build curl with a GNUTLS backend, that's all 

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6050229/logs.zip)

**Comment by chirrilover** [comment]
I did not delete anything after the previous comment and then I ran:

$ pacman -S mingw-w64-x86_64-curl
warning: mingw-w64-x86_64-curl-7.75.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-curl-7.75.0-1

Total Installed Size:  2.84 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                           [#######################################] 100%
(1/1) checking package integrity                                         [#######################################] 100%
(1/1) loading package files                                              [#######################################] 100%
(1/1) checking for file conflicts                                        [#######################################] 100%
(1/1) checking available disk space                                      [#######################################] 100%
warning: could not get file information for mingw64/lib/libcurl.dll.a
:: Processing package changes...
(1/1) reinstalling mingw-w64-x86_64-curl                                 [#######################################] 100%

Same issue as above though. Running git update for curl... failed in the same way as described above.

So I tried using pacman to remove curl but then I had to remove cmake (cmake being dependent on curl). I removed both through pacman:

**$ pacman -R mingw-w64-x86_64-cmake**
checking dependencies...

Packages (1) mingw-w64-x86_64-cmake-3.19.3-2

Total Removed Size:  62.58 MiB

:: Do you want to remove these packages? [Y/n] Y
:: Processing package changes...
(1/1) removing mingw-w64-x86_64-cmake                                    [#######################################] 100%

**$ pacman -R mingw-w64-x86_64-curl**
checking dependencies...

Packages (1) mingw-w64-x86_64-curl-7.75.0-1

Total Removed Size:  2.84 MiB

:: Do you want to remove these packages? [Y/n] Y
:: Processing package changes...
(1/1) removing mingw-w64-x86_64-curl                                     [#######################################] 100%


Then I ran the batch file again (always after doing a mintty ./update_suite.sh) and I noticed that when installing cmake the system made the same warning as above about **libcurl.dll.a** 

So I deleted this file from mingw64/lib/libcurl.dll.a and ran the batch file again (also, I remembered from another thread you were not using *.dll.a's anymore).

This time pacman installed cmake AND curl without any problems (it seems we need curl installed before running git update for curl)

Same issue, this is my final try. Again, all I did was choose was to install curl with a GNUTLS backend. Please tell me if error is reproducible. 

  Running git clone for curl...
┌ curl git  ........................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
make[2]: Entering directory '/build/curl-git/build-64bit/src'
  CCLD     curl.exe
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib/.libs/libcurl.a(libcurl_la-gtls.o):gtls.c:(.text+0x143a): undefined reference to `__imp_gnutls_free'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../lib/.libs/libcurl.a(libcurl_la-gtls.o):gtls.c:(.text+0x14a8): undefined reference to `__imp_gnutls_free'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:997: curl.exe] Error 1
make[2]: Leaving directory '/build/curl-git/build-64bit/src'
make[1]: *** [Makefile:2156: all-recursive] Error 1
make[1]: Leaving directory '/build/curl-git/build-64bit/src'
make: *** [Makefile:1252: all-recursive] Error 1

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6051288/logs.zip)

**Comment by 1480c1** [comment]
Can you retry on https://github.com/m-ab-s/media-autobuild_suite/commit/6d012fa1b5e7caff65af4e5a259ee09454d8e2c0 ?

**Comment by chirrilover** [comment]
Retrying on 6d012fa solved this one.

Thank you
