### ISSUE TITLE
GPAC/MP4Box Build Error

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1921]
┌ gpac git  .............................................. [Updates found]
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe61c): undefined reference to `_imp__nghttp2_session_send'
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe65d): undefined reference to `_imp__nghttp2_session_mem_recv'
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe705): undefined reference to `_imp__nghttp2_strerror'
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe793): undefined reference to `_imp__nghttp2_strerror'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:56: gpac.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/build-32bit/applications/gpac'
make[1]: *** [Makefile:41: apps] Error 2
make[1]: Leaving directory '/build/gpac-git/build-32bit/applications'
make: *** [Makefile:14: all] Error 2
make failed. Check D:/mabs/build/gpac-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-KH1.zip
Copy and paste [logs.zip](https://0x0.st/-KH1.zip) in the GitHub issue.

**Comment by BlackScreen** [comment]
Looks like #1918

**Comment by 1480c1** [comment]
Going to close as a duplicate
