### ISSUE TITLE
libxml2 fails to build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1922]
┌ libxml2 git  ........................................ [Recently updated]
├ Running autogen...
├ Running configure...
Likely error (tail of the failed operation logfile):
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... ccache gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... configure: error: in `/build/libxml2-git/build-32bit':
configure: error: cannot compute suffix of executables: cannot compile and link
See `config.log' for more details
configure failed. Check D:/MABS-ffmpeg/build/libxml2-git/build-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-KP_.zip

**Comment by 1480c1** [comment]
Can you try checking if your antivirus is acting up?
```bash
configure:4222: ccache gcc -o conftest.exe -mthreads -mtune=generic -O2 -pipe -DLIBXML_STATIC_FOR_DLL -DNOLIBTOOL -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1 -pipe -static-libgcc -static-libstdc++ conftest.c  >&5
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot open output file conftest.exe: Permission denied
```

**Comment by Barough** [comment]
I've made an exception for the AV not to check the mabs folders, but i can check again when i get back home tonight.

**Comment by Barough** [comment]
The folder exception was set in my AV. Don't know atm what else that can block the permission for that file in question.

**Comment by Barough** [comment]
It's works now. Beats my what locked that file up

**Comment by 1480c1** [comment]
I'm just going to assume temporary issues
