### ISSUE TITLE
Error 000 while downloading http://www.libsdl.org/release/SDL2-2.0.12.tar.gz

### ISSUE THREAD

**Issue by Weezzel** [m-ab-s/media-autobuild_suite#1927]
I wanted to start with a fresh install, so I deleted the Directory and did a new git clone from source. After running the new script install it started to download all new items and this error showed up when trying to download SDL2

19:43:58 sdl2 2.0.12  ................................... [Not installed]
19:44:44 └ SDL2-2.0.12  ........................................ [Failed]
Error 000 while downloading http://www.libsdl.org/release/SDL2-2.0.12.tar.gz
<Ctrl+c> to cancel build or <Enter> to continue
if you're sure nothing depends on it.

After hitting Enter, the script will continue on through, but fails while compiling FFMPEG saying that SDL2 is missing and is required.
 I have tried to disable SDL2 in both  ffmpeg_options.txt and mvp_options.txt with  "--disable-sdl2" but I still get the same response

Also got this error as well.

19:57:10 ┌ gpac git  ................................. [Recently updated]
19:57:10 ├ Running configure...
19:57:24 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdfef): undefined reference to `__imp_nghttp2_session_send'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdff6): undefined reference to `__imp_nghttp2_session_mem_recv'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe15c): undefined reference to `__imp_nghttp2_strerror'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe1d1): undefined reference to `__imp_nghttp2_strerror'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:56: gpac.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/build-64bit/applications/gpac'
make[1]: *** [Makefile:41: apps] Error 2
make[1]: Leaving directory '/build/gpac-git/build-64bit/applications'
make: *** [Makefile:14: all] Error 2
make failed. Check C:/MABS/build/gpac-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
19:58:10   Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6053440/logs.zip)

**Comment by 1480c1** [comment]
For the first one
> 000 is a common code to use when no HTTP code was received due to a network error

I am not sure why it might do that since I can access it now, maybe when you were the site was down? Can you try again?

For the second one, that's https://github.com/m-ab-s/media-autobuild_suite/issues/1918

**Comment by Weezzel** [comment]
I have been trying for about a week now.
![Screenshot (3)](https://user-images.githubusercontent.com/67742562/109395377-0a021d80-78fa-11eb-87c8-7e44466c84fb.png)

**Comment by Weezzel** [comment]
as far as the second Issue,
I have made sure the code from this is in the file.
Can you try on [a4afbe2](https://github.com/m-ab-s/media-autobuild_suite/commit/a4afbe24101ed61b823f443e1f37dd7ed2d5192a)?

**Comment by Biswa96** [comment]
This may help https://downforeveryoneorjustme.com/

**Comment by Biswa96** [comment]
Source can be downloaded from here also https://github.com/libsdl-org/SDL/releases

**Comment by Weezzel** [comment]
Hmm, Interesting 
I checked with this  https://downforeveryoneorjustme.com/

Libsdl.org Status
Is libsdl.org down right now?
It's just you. libsdl.org is up.

What could cause this I have no network issues and no firewall setting to block.

**Comment by moisespr123** [comment]
Maybe your ISP. Can you try to access the site on your phone? Or with
another internet provider?

**Comment by Weezzel** [comment]
So I use windows 10 OS. If I was to download it directly from https://github.com/libsdl-org/SDL/releases
where do I extract it to \Build folder ? 
what name would I use to place it in the \Build\SDL2.0.12 folder?

**Comment by 1480c1** [comment]
I will switch the link to use that one instead since github's server should hopefully have no downtime or at least if you can use the suite, you probably can download from github

**Comment by Weezzel** [comment]
Yes I get the same response from Cell Phone, ATT in Ohio, USA

**Comment by Biswa96** [comment]
Not sure if SDL devs do some change before pushing it to libsdl.org

**Comment by Biswa96** [comment]
Why is SDL git repository not used here instead of tarball?

**Comment by wiiaboo** [comment]
We avoid using VCS for libraries that are not the ones being directly related to the suite.
It's enough bleeding edge brokeness for two mostly one person to maintain semi-regularly.
You're welcome to help and be responsible for maintaining it, though. Pull requests welcome.
