### ISSUE TITLE
ffmpeg fails to build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1930]
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
libnpp is only supported in 64-bit.
CUDA_PATH environment variable not set or directory does not exist.
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
cc1plus.exe: warning: command-line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wno-pointer-sign' is valid for C/ObjC but not for C++
cc1plus.exe: warning: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++
cc1plus.exe: warning: '-Werror=' argument '-Werror=missing-prototypes' is not valid for C++
cc1plus.exe: warning: command-line option '-std=c11' is valid for C/ObjC but not for C++
D:/MABS-ffmpeg/build/ffmpeg-git/libavfilter/glslang.cpp:27:10: fatal error: glslang/Include/revision.h: No such file or directory
   27 | #include <glslang/Include/revision.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/build/ffmpeg-git/ffbuild/common.mak:62: libavfilter/glslang.o] Error 1
make failed. Check D:/MABS-ffmpeg/build/ffmpeg-git/build-static-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-Kf0.zip
Copy and paste [logs.zip](https://0x0.st/-Kf0.zip) in the GitHub issue.

**Comment by GyanD** [comment]
That header reference was removed in July 2020. Seems your ffmpeg source dir is out of date. Remove it and try again.

**Comment by Biswa96** [comment]
`glslang/Include/revision.h` was removed from glslang 11.1.0.

**Comment by Barough** [comment]
> That header reference was removed in July 2020. Seems your ffmpeg source dir is out of date. Remove it and try again.

I've already done that a couple of times before i made this issue report

**Comment by 1480c1** [comment]
`+ git checkout --no-track -fB ab-suite origin/release/4.3`
seems this is probably the reason, you will either need to set glslang to track a version close to this or cherry-pick all of the changes to glslang

also, for packages with user set patches, we cannot reasonably give support since we can't tell you how to solve this within the scope of the suite

**Comment by Barough** [comment]
Totally missed that i had added the ffmpeg_extra.sh to the build folder. Gonna give it try now without it.
