### ISSUE TITLE
mingw32 gpac build error - undefined reference to BrotliDecoderDecompress

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#1931]
[logs.zip](https://0x0.st/-KxO.zip)

**Comment by ycwan** [comment]
Same issue when I try to update MAB suite.  Append below the output of MAB and the related logs files

20:32:04   Running git update for gpac...
20:32:18 ┌ gpac git  .................................... [Updates found]
20:32:18 ├ Running uninstall...
20:32:25 ├ Running configure...
20:32:54 ├ Running make...
Likely error (tail of the failed operation logfile):
make[1]: Entering directory '/build/gpac-git/build-64bit/applications'
set -e; for i in gpac mp4box  ; do make -C $i all; done
make[2]: Entering directory '/build/gpac-git/build-64bit/applications/gpac'
C:/MinGW64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW64/local64/lib/libfreetype.a(sfnt.o):sfnt.c:(.text+0xa523): undefined reference to `BrotliDecoderDecompress'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:56: gpac.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/build-64bit/applications/gpac'
make[1]: *** [Makefile:41: apps] Error 2
make[1]: Leaving directory '/build/gpac-git/build-64bit/applications'
make: *** [Makefile:14: all] Error 2
make failed. Check C:/MinGW64/build/gpac-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
20:34:40   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-Kl6.zip
Copy and paste [logs.zip](https://0x0.st/-Kl6.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/-Kl6.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/6061623/ab-suite.make.log)

**Comment by StefanBae** [comment]
I had the same issue.
The log file points to a problem within libfreetype.a 
After deleting the freetype2-git folder and the gpac-git folder and rerunning the script it worked for me. 
Maybe it is related to #1881 

Hope that helps.

**Comment by Selur** [comment]
@StefanBae :Thanks! worked for me too :)

**Comment by LigH-de** [comment]
May be fixed, today it built for me.

**Comment by fuchanghao** [comment]
> May be fixed, today it built for me.

It not works now.

**Comment by LigH-de** [comment]
A forced rebuild of *everything* by clearing /local32/libs might help? But no guarantees. I did it once and it works for me since. But it is a desperate move.

**Comment by githubReneFischer** [comment]
Hi, thanks to @StefanBae I managed to run all again but I have also to delete "fontconfig" in the build-folder, due to following problems (fetch and build).
In full I deleted fontconfig, freetype-2 and gpac from build-folder then it all worked again.
Thanks very much Rene

**Comment by 1480c1** [comment]
I have not yet encountered this issue, so I am going to assume it's fixed, if it's still an issue, I can reopen
