### ISSUE TITLE
[Question] How to build with locally modified source files?

### ISSUE THREAD

**Issue by DeanZwikel** [m-ab-s/media-autobuild_suite#1936]
We are developing changes to ffmpeg and trying to use media-autobuild-suite to build ffmpeg for testing. To do so, we modify some source files in /build/ffmpeg-git/libavcodec and /build/ffmpeg-git/libavformat. Unfortunately, when we run media-autobuild_suite.bat it downloads and replaces our modified files. How can we prevent this and use our files?

Thank you.

**Comment by Biswa96** [comment]
Option1: Create a patch file and add that with `git apply` command in the build script.

**Comment by DeanZwikel** [comment]
Do you mean similar to this example script in the documentation? Are there any other options? It would be easier for us to just modify the code rather than have to build a patch each time.

Example Script: /build/ffmpeg_extra.sh for ffmpeg-git

`#!/bin/bash

# Force to the suite to think the package has updates to recompile.
# Alternatively, you can use "touch recompile" for a similar effect.
touch custom_updated

_pre_configure(){
    #
    # Apply a patch from ffmpeg's patchwork site.
    do_patch "https://patchwork.ffmpeg.org/patch/12563/mbox/" am
    #
    # Apply a local patch inside the directory where is "ffmpeg_extra.sh"
    patch -p1 -i "$LOCALBUILDDIR/ffmpeg-0001-my_patch.patch"
    #
    # Add extra configure options to ffmpeg (ffmpeg specific)
    # If you want to add something to ffmpeg not within the suite already
    # you will need to install it yourself, either through pacman
    # or compiling from source.
    FFMPEG_OPTS+=(--enable-libsvthevc)
    #
}

_post_make(){
    # Don't run configure again.
    touch "$(get_first_subdir -f)/do_not_reconfigure"
    # Don't clean the build folder on each successive run.
    # This is for if you want to keep the current build folder as is and just recompile only.
    touch "$(get_first_subdir -f)/do_not_clean"
}`

**Comment by DeanZwikel** [comment]
@dbyoung720 Thank you. What is the best way to generate the uFFMPEG.patch file?

**Comment by wiiaboo** [comment]
`git -C /build/ffmpeg-git diff origin/master.. > /build/myffmpegchanges.diff`
then add `patch -p1 -i /build/myffmpegchanges.diff` to the `_pre_configure()` stage.

Don't modify the suite's files, that's what the *.extra.sh functionality is there for.

And of course, you break it, you fix it. Don't expect us to fix your broken ffmpeg build if you do anything wrong.

**Comment by DeanZwikel** [comment]
@wiiaboo Thank you
