### ISSUE TITLE
qpac - patch couldn't be applied (64bit)

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1939]
Just a little heads up......

┌ gpac git  ........................................... [Recently updated]
├ Running uninstall...
0001-downloader-always-define-NGHTTP2_STATICLIB-on-win.patch
        Patch could not be applied with `patch`. Continuing without patching.
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ gpac-git  .................................................... [Updated]

**Comment by 1480c1** [comment]
Fixed in https://github.com/gpac/gpac/commit/75b879fc4e63ba26e76efddf1f74e029de94c9e1
