### ISSUE TITLE
libtiff - patch couldn't be applied (64bit)

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1940]
Just a little heads up.........

┌ libtiff git  ........................................ [Recently updated]
├ Running uninstall...
233.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libtiff-git  ................................................. [Updated]

**Comment by 1480c1** [comment]
it seems to apply neatly for me
