### ISSUE TITLE
ffmpeg - patch couldn't be applied (64bit)

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1941]
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
0001-Add-Alternative-VapourSynth-demuxer.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ ffmpeg-git  .................................................. [Updated]

**Comment by 1480c1** [comment]
Patch applies neatly, but I think it may be related to https://github.com/m-ab-s/media-autobuild_suite/issues/1803 where since the patch creates a new file and git reset doesn't delete it, it thinks the patch fails

**Comment by Barough** [comment]
ok
