### ISSUE TITLE
Request: Build new gpac.exe and legacy MP4Box.exe

### ISSUE THREAD

**Issue by Murmur** [m-ab-s/media-autobuild_suite#1943]
Current build scripting builds gpac/MP4Box.exe binary which is soon to be a legacy version. They have implemented a new gpac.exe with the brand new filter architechture and ffmpeg encoding integration. This would be a super helpfull to have both mp4box.exe and gpac.exe binaries available.

Anyone done a customized scripting add-on or instructions to build gpac.exe release?

https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Windows
https://github.com/gpac/gpac

**Comment by 1480c1** [comment]
Can you point exactly to where they mention the new and old or somewhere where they describe the difference in building the two? As a note, you can click on the chain on the left of the headers to get a url to that section example https://github.com/gpac/gpac#mp4box

**Comment by 1480c1** [comment]
No response in about a month, so going to close

**Comment by Murmur** [comment]
(hmm..I did not get a notification from this topic until it was closed)
See this link about the `gpac exe binary`
https://github.com/gpac/gpac/wiki/gpac_general

**Comment by 1480c1** [comment]
Just to make sure, it isn't that gpac is remove mp4box, but rather they just introduced a new gpac binary?

**Comment by Murmur** [comment]
Correct, should have two binaries gpac.exe and mp4box.exe files. New binary has an extensive refactoring of filter logic and ffmpeg integration.

It can do so much more of everything.

**Comment by 1480c1** [comment]
Closed in https://github.com/m-ab-s/media-autobuild_suite/commit/d81b310bc3489859a55ca959e1e5af209688087d
