### ISSUE TITLE
kvazaar build error

### ISSUE THREAD

**Issue by edsonqr** [m-ab-s/media-autobuild_suite#1946]
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe -fno-asynchronous-unwind-tables
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
make -j4 
make  all-recursive
make[1]: Entering directory '/build/kvazaar-git/build-32bit'
Making all in src
make[2]: Entering directory '/build/kvazaar-git/build-32bit/src'
  CC       kvazaar-encmain.o
  CC       kvazaar-cli.o
  CC       kvazaar-yuv_io.o
  CC       libkvazaar_la-bitstream.lo
  CC       libkvazaar_la-cabac.lo
  CC       libkvazaar_la-checkpoint.lo
  CC       libkvazaar_la-cfg.lo
  CC       libkvazaar_la-constraint.lo
  CC       libkvazaar_la-context.lo
  CC       libkvazaar_la-cu.lo
  CC       libkvazaar_la-encoder.lo
  CC       libkvazaar_la-encoderstate.lo
  CC       libkvazaar_la-encoder_state-bitstream.lo
  CC       libkvazaar_la-encoder_state-ctors_dtors.lo
  CC       libkvazaar_la-encoder_state-geometry.lo
  CC       libkvazaar_la-encode_coding_tree.lo
  CC       libkvazaar_la-fast_coeff_cost.lo
  CC       libkvazaar_la-filter.lo
  CC       libkvazaar_la-image.lo
  CC       libkvazaar_la-imagelist.lo
  CC       libkvazaar_la-input_frame_buffer.lo
  CC       libkvazaar_la-inter.lo
  CC       libkvazaar_la-intra.lo
  CC       libkvazaar_la-kvazaar.lo
  CC       libkvazaar_la-ml_intra_cu_depth_pred.lo
  CC       libkvazaar_la-nal.lo
  CC       libkvazaar_la-rate_control.lo
  CC       libkvazaar_la-rdo.lo
  CC       libkvazaar_la-sao.lo
  CC       libkvazaar_la-scalinglist.lo
  CC       libkvazaar_la-search.lo
  CC       libkvazaar_la-search_inter.lo
  CC       libkvazaar_la-search_intra.lo
  CC       libkvazaar_la-tables.lo
  CC       libkvazaar_la-threadqueue.lo
  CC       libkvazaar_la-transform.lo
  CC       libkvazaar_la-videoframe.lo
  CC       libkvazaar_la-strategyselector.lo
  YASM     strategies/x86_asm/picture-x86-asm-sad.lo
  YASM     strategies/x86_asm/picture-x86-asm-satd.lo
  CC       strategies/generic/libkvazaar_la-dct-generic.lo
  CC       strategies/generic/libkvazaar_la-intra-generic.lo
  CC       strategies/generic/libkvazaar_la-ipol-generic.lo
  CC       strategies/generic/libkvazaar_la-nal-generic.lo
  CC       strategies/generic/libkvazaar_la-picture-generic.lo
  CC       strategies/generic/libkvazaar_la-quant-generic.lo
  CC       strategies/generic/libkvazaar_la-sao-generic.lo
  CC       strategies/generic/libkvazaar_la-encode_coding_tree-generic.lo
  CC       strategies/libkvazaar_la-strategies-dct.lo
  CC       strategies/libkvazaar_la-strategies-intra.lo
  CC       strategies/libkvazaar_la-strategies-ipol.lo
  CC       strategies/libkvazaar_la-strategies-nal.lo
  CC       strategies/libkvazaar_la-strategies-picture.lo
  CC       strategies/libkvazaar_la-strategies-quant.lo
  CC       strategies/libkvazaar_la-strategies-sao.lo
  CC       strategies/libkvazaar_la-strategies-encode.lo
  CC       strategies/x86_asm/libkvazaar_la-picture-x86-asm.lo
  CC       extras/libkvazaar_la-libmd5.lo
  CC       strategies/altivec/libaltivec_la-picture-altivec.lo
  CC       strategies/avx2/libavx2_la-dct-avx2.lo
  CC       strategies/avx2/libavx2_la-intra-avx2.lo
  CC       strategies/avx2/libavx2_la-ipol-avx2.lo
  CC       strategies/avx2/libavx2_la-picture-avx2.lo
  CC       strategies/avx2/libavx2_la-quant-avx2.lo
  CC       strategies/avx2/libavx2_la-sao-avx2.lo
  CC       strategies/avx2/libavx2_la-encode_coding_tree-avx2.lo
  CC       strategies/sse2/libsse2_la-picture-sse2.lo
  CC       strategies/sse41/libsse41_la-picture-sse41.lo
  CCLD     libasm.la
  CCLD     libaltivec.la
  CCLD     libavx2.la
  CCLD     libsse2.la
  CCLD     libsse41.la
  GEN      libkvazaar.la
  GEN      kvazaar.exe
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x16): undefined reference to `kvz_sad_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x30): undefined reference to `kvz_sad_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x56): undefined reference to `kvz_sad_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x64): undefined reference to `kvz_sad_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x30f): undefined reference to `kvz_sad_4x4_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x33b): undefined reference to `kvz_sad_8x8_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x367): undefined reference to `kvz_sad_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x3eb): undefined reference to `kvz_satd_4x4_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x417): undefined reference to `kvz_satd_8x8_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x443): undefined reference to `kvz_satd_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x46d): undefined reference to `kvz_satd_32x32_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x497): undefined reference to `kvz_satd_64x64_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x218): undefined reference to `kvz_sad_64x64_stride_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x26b): undefined reference to `kvz_sad_8x8_stride_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x28f): undefined reference to `kvz_sad_16x16_stride_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x2b3): undefined reference to `kvz_sad_32x32_stride_avx'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:1009: kvazaar.exe] Error 1
make[2]: Leaving directory '/build/kvazaar-git/build-32bit/src'
make[1]: *** [Makefile:527: all-recursive] Error 1
make[1]: Leaving directory '/build/kvazaar-git/build-32bit'
make: *** [Makefile:397: all] Error 2
make  all-recursive
make[1]: Entering directory '/build/kvazaar-git/build-32bit'
Making all in src
make[2]: Entering directory '/build/kvazaar-git/build-32bit/src'
  GEN      kvazaar.exe
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x16): undefined reference to `kvz_sad_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x30): undefined reference to `kvz_sad_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x56): undefined reference to `kvz_sad_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x64): undefined reference to `kvz_sad_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x30f): undefined reference to `kvz_sad_4x4_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x33b): undefined reference to `kvz_sad_8x8_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x367): undefined reference to `kvz_sad_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x3eb): undefined reference to `kvz_satd_4x4_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x417): undefined reference to `kvz_satd_8x8_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x443): undefined reference to `kvz_satd_16x16_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x46d): undefined reference to `kvz_satd_32x32_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x497): undefined reference to `kvz_satd_64x64_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x218): undefined reference to `kvz_sad_64x64_stride_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x26b): undefined reference to `kvz_sad_8x8_stride_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x28f): undefined reference to `kvz_sad_16x16_stride_avx'
C:/DADOS/media-autobuild/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazaar.a(libkvazaar_la-picture-x86-asm.o):picture-x86-asm.c:(.text+0x2b3): undefined reference to `kvz_sad_32x32_stride_avx'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:1009: kvazaar.exe] Error 1
make[2]: Leaving directory '/build/kvazaar-git/build-32bit/src'
make[1]: *** [Makefile:527: all-recursive] Error 1
make[1]: Leaving directory '/build/kvazaar-git/build-32bit'
make: *** [Makefile:397: all] Error 2
[log.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6185954/log.zip)

**Comment by LigH-de** [comment]
Everything passed today. So this may be fixed upstream.

**Comment by 1480c1** [comment]
They did recently commit a set of patches, so maybe inside there

**Comment by 1480c1** [comment]
Assuming closed
