### ISSUE TITLE
sdl2 2.0.14 configure error: Unsupported host after fresh installation

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#1947]
12:15:08 sdl2 2.0.14  ................................... [Not installed]
12:15:09 ├ release-2.0.14  ............................ [File up-to-date]
12:15:09 ├ Running extract...
12:15:16 ├ Running configure...
Likely error (tail of the failed operation logfile):
checking for Altivec with GCC altivec.h and -maltivec option... no
checking for Altivec with GCC -maltivec option... no
checking for Altivec with GCC altivec.h and -faltivec option... no
checking for Altivec with GCC -faltivec option... no
checking for GCC -Wall option... yes
checking for necessary GCC -Wno-multichar option... no
checking for GCC -fno-strict-aliasing option... yes
configure: error:
*** Unsupported host:  Please add to configure.ac
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6189151/logs.zip)

**Comment by LigH-de** [comment]
A better title may be e.g.:
> sdl2 2.0.14 configure error: Unsupported host

**Comment by Hunterswood** [comment]
Yep am seeing the same thing!

[logs.zip](https://0x0.st/-q9j.zip)
