### ISSUE TITLE
JPEG XL compilation failed

### ISSUE THREAD

**Issue by vivazkote** [m-ab-s/media-autobuild_suite#1950]
[1/201] Generating cjxl.1
FAILED: cjxl.1 
cmd.exe /C "cd /D C:\mingw64\build\jpeg-xl-git\build-32bit && E:\mingw64\msys64\mingw32\bin\python3.8.exe C:/mingw64/msys64/usr/bin/a2x --format manpage --destination-dir="C:/mingw64/build/jpeg-xl-git/build-32bit" C:/mingw64/build/jpeg-xl-git/doc/man/cjxl.txt"
a2x: ERROR: unable to find asciidoc: asciidoc

[2/201] Generating djxl.1
FAILED: djxl.1 
cmd.exe /C "cd /D C:\mingw64\build\jpeg-xl-git\build-32bit && C:\mingw64\msys64\mingw32\bin\python3.8.exe C:/mingw64/msys64/usr/bin/a2x --format manpage --destination-dir="C:/mingw64/build/jpeg-xl-git/build-32bit" C:/mingw64/build/jpeg-xl-git/doc/man/djxl.txt"
a2x: ERROR: unable to find asciidoc: asciidoc

[3/201] Building C object third_party/CMakeFiles/lcms2.dir/lcms/src/cmscam02.c.o
[4/201] Building C object third_party/CMakeFiles/lcms2.dir/lcms/src/cmsalpha.c.o
ninja: build stopped: subcommand failed.
[1/199] Generating djxl.1
FAILED: djxl.1 
cmd.exe /C "cd /D C:\mingw64\build\jpeg-xl-git\build-32bit && E:\mingw64\msys64\mingw32\bin\python3.8.exe C:/mingw64/msys64/usr/bin/a2x --format manpage --destination-dir="C:/mingw64/build/jpeg-xl-git/build-32bit" C:/mingw64/build/jpeg-xl-git/doc/man/djxl.txt"
a2x: ERROR: unable to find asciidoc: asciidoc

ninja: build stopped: subcommand failed.

**Comment by ycwan** [comment]
I have  the same issue.  Below is the MABS output and logs
21:12:00 ┌ jpeg-xl git  ................................. [Updates found]
21:12:07 Warning: JPEG-XL compiled with GCC will not use SIMD optimizations!
21:12:07 ├ Running cmake...
21:12:27 ├ Running build...
Likely error (tail of the failed operation logfile):
a2x: ERROR: unable to find asciidoc: asciidoc

[3/201] Building C object third_party/CMakeFiles/lcms2.dir/lcms/src/cmsalpha.c.o
ninja: build stopped: subcommand failed.
[1/200] Generating djxl.1
FAILED: djxl.1
cmd.exe /C "cd /D C:\MinGW64\build\jpeg-xl-git\build-64bit && C:\MinGW64\msys64\mingw64\bin\python3.8.exe C:/MinGW64/msys64/mingw64/bin/a2x --format manpage --destination-dir="C:/MinGW64/build/jpeg-xl-git/build-64bit" C:/MinGW64/build/jpeg-xl-git/doc/man/djxl.txt"
a2x: ERROR: unable to find asciidoc: asciidoc

ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW64/build/jpeg-xl-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
21:12:28   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-qvS.zip
Copy and paste [logs.zip](https://0x0.st/-qvS.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/-qvS.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/6207372/ab-suite.build.log)

**Comment by nikolasr** [comment]
I had the same problem.
Cause: asciidoc missing 
Workaround:
- open your "mintty" shortcut in your media-autobuild_suite directory
- type
`pacman -S mingw-w64-x86_64-asciidoc`
for 64-bit compilation
or
`pacman -S mingw-w64-i686-asciidoc`
for 32-bit compilation
(or, if in doubt, do both: it won't hurt ;-) )

-rerun "media-autobuild_suite.bat"
- if it complains about unnecessary packages and ask if these should be removed:
 **_say no ( "n")_**

**Comment by Biswa96** [comment]
Or, there should be an option in upstream to disable man page so that asciidoc is not required. Less dependency less headache.

**Comment by nikolasr** [comment]
@Biswa96 
Yeah, that's why it's only a "quick and dirty workaround" for those who are wanting to compile right now. ;-)
Of course it should be fixed _the right way_ *thumbs up*

**Comment by sboukortt** [comment]
> Or, there should be an option in upstream to disable man page so that asciidoc is not required. Less dependency less headache.

It’s already [supposed](https://gitlab.com/wg1/jpeg-xl/-/blob/c2d18d95df67fe167e495d22c9876d33438d4055/CMakeLists.txt#L291) to be optional, however having `msys2/asciidoc` (part of `base-devel`) installed without the corresponding `mingw` package appears to trigger the detection without actually working.

Relevant issue: https://github.com/msys2/MINGW-packages/issues/6708

An explicit `JPEGXL_ENABLE_MANPAGES` flag would indeed work around this until this is resolved.

**Comment by kmilos** [comment]
Just ran into the same issue when trying to build under the new `ucrt64` subsystem, the package is not yet available there so it falls through to `msys/asciidoc` as well...
