### ISSUE TITLE
libplacebo build error, from clean install

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#1951]
08:45:37 ┌ libplacebo git  ........................... [Recently updated]
08:45:38 ├ Running meson...
08:45:44 ├ Running build...
Likely error (tail of the failed operation logfile):
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: F:/m-a-s/local32/lib/libvulkan.a(loader.c.obj):loader.c:(.text+0x10eca): undefined reference to `_imp__CM_Get_Device_ID_List_SizeW@12'
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: F:/m-a-s/local32/lib/libvulkan.a(loader.c.obj):loader.c:(.text+0x10f61): undefined reference to `_imp__CM_Get_Device_ID_ListW@16'
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: F:/m-a-s/local32/lib/libvulkan.a(loader.c.obj):loader.c:(.text+0x11035): undefined reference to `_imp__CM_Locate_DevNodeW@12'
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: F:/m-a-s/local32/lib/libvulkan.a(loader.c.obj):loader.c:(.text+0x11065): undefined reference to `_imp__CM_Get_DevNode_Status@16'
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: F:/m-a-s/local32/lib/libvulkan.a(loader.c.obj):loader.c:(.text+0x1111c): undefined reference to `_imp__CM_Get_Child@12'
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: F:/m-a-s/local32/lib/libvulkan.a(loader.c.obj):loader.c:(.text+0x111b3): undefined reference to `_imp__CM_Get_Sibling@12'
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: F:/m-a-s/local32/lib/libvulkan.a(loader.c.obj):loader.c:(.text+0x111df): undefined reference to `_imp__CM_Get_Device_IDW@16'
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: F:/m-a-s/local32/lib/libvulkan.a(loader.c.obj):loader.c:(.text+0x1123f): undefined reference to `_imp__CM_Get_DevNode_Registry_PropertyW@24'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check F:/m-a-s/build/libplacebo-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
08:46:02   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-qlE.zip
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6210483/logs.zip)

**Comment by simplesalt** [comment]
me too.  

[logs.zip](https://0x0.st/-bPi.zip)

**Comment by Ajaja** [comment]
@simplesalt 
By default It's needed at least for mpv. But you can turn it off in mpv_options.txt  adding ```--disable-libplacebo```

**Comment by simplesalt** [comment]
Thanks.  Got it compiled in exactly that way.  decent workaround, and I can confirm that the resulting binaries work great for the encoding tasks I needed them for.
