### ISSUE TITLE
ffmpeg - missing online patch

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1952]
Just a heads up........

┌ ffmpeg git  ............................................ [Updates found]
├ Changing options to comply to nonfree...
libnpp is only supported in 64-bit.
CUDA_PATH environment variable not set or directory does not exist.
0001-Add-Alternative-VapourSynth-demuxer.patch
        File not found online. Using local copy.

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/mabs-patches/blob/master/ffmpeg/0001-Add-Alternative-VapourSynth-demuxer.patch well, it's certainly still there

**Comment by Barough** [comment]
I just report what i noticed in the log while ffmpeg was compiling
