### ISSUE TITLE
[QUESTION] FFmpeg & External dependencies

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1953]
Haven't been able to build a 'Full' FFmpeg in a while until today and noticed this in the compile log when i had a closer look at it 

├ FFmpeg and related apps will depend on OpenCL.dll
 
├ Compiling FFmpeg with Vapoursynth R52
├ FFmpeg will need vapoursynth.dll and vsscript.dll to run using vapoursynth demuxers!

That tells me that FFmpeg will require external files to fully work and i found the vaporsynth related files in the 7Zip Vaporsynth archives in the build folder so that's ok then. But there is no trace of a OpenCL.dll file in mabs folders. So where can i get this required file(s) from, if i mite ask?

**Comment by 1480c1** [comment]
Theoretically you get the opencl dll from your system32 folder that should be installed by your graphics driver

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/blob/57b5746188b87faa5409ccbb6da7fae1918baf63/build/media-suite_compile.sh#L508-L515

are the lines of interest

**Comment by Barough** [comment]
Thanks :)

But i think it would be great though if the OpenCL.dll files could be made available in the /bin-video/ folders

**Comment by 1480c1** [comment]
Issue with that is that would make it imply as if you can distribute the OpenCL.dll file, which theoretically, you shouldn't as it would be graphics driver specific

**Comment by Barough** [comment]
ok
