### ISSUE TITLE
[mingw64] harfbuzz: meson failed

### ISSUE THREAD

**Issue by wpapp** [m-ab-s/media-autobuild_suite#1957]
`22:47:01 ┌ harfbuzz git  ............................. [Recently updated]
22:47:03 ├ Running meson...
Likely error (tail of the failed operation logfile):
C++ linker for the host machine: g++.bat ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports link arguments -Bsymbolic-functions: YES
Compiler for C++ supports arguments -fno-exceptions: YES
Compiler for C++ supports arguments -fno-rtti: YES
Compiler for C++ supports arguments -fno-threadsafe-statics: YES
Compiler for C++ supports arguments -fvisibility-inlines-hidden: YES
Library m found: YES
Found pkg-config: --keep-system-libs (1.7.3)
meson failed. Check G:/FFmpeg/build/harfbuzz-git/build-64bit/ab-suite.meson.log
This is required for other packages, so this script will exit.
22:47:07   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-cQD.zip
Copy and paste [logs.zip](https://0x0.st/-cQD.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.`

**Comment by voltagex** [comment]
I just hit this as well [logs.zip](https://0x0.st/-At9.zip)


```
OSError: [WinError 1005] The volume does not contain a recognized file system.

Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/lib/x86_64-w64-mingw32/10.2.0'
```

D is not a valid drive on my system right now - what's it trying to do?

**Comment by 1480c1** [comment]
Can you retry? Meson got recently updated

**Comment by wpapp** [comment]
`09:41:35 ┌ harfbuzz git  ............................. [Recently updated]
09:41:41 ├ Running meson...
Likely error (tail of the failed operation logfile):
C++ linker for the host machine: g++.bat ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports link arguments -Bsymbolic-functions: YES
Compiler for C++ supports arguments -fno-exceptions: YES
Compiler for C++ supports arguments -fno-rtti: YES
Compiler for C++ supports arguments -fno-threadsafe-statics: YES
Compiler for C++ supports arguments -fvisibility-inlines-hidden: YES
Library m found: YES
Found pkg-config: --keep-system-libs (1.7.4)
meson failed. Check G:/FFmpeg/build/harfbuzz-git/build-64bit/ab-suite.meson.log
This is required for other packages, so this script will exit.
09:42:46   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-Brs.zip
Copy and paste [logs.zip](https://0x0.st/-Brs.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
`

**Comment by 1480c1** [comment]
Just making sure, do you have a D drive?

**Comment by wpapp** [comment]
these is linux

**Comment by 1480c1** [comment]
Are you trying to run mabs under linux?

**Comment by wpapp** [comment]
no,win10 x64.

**Comment by 1480c1** [comment]
> these is linux

Then what does this message mean?

**Comment by wpapp** [comment]
D drive is linux system.  “there is”.

**Comment by 1480c1** [comment]
Ah, that's making more sense, okay, I think the issue is that it's trying to look inside your D drive, but because it is not NTFS, it's failing to do so, try mapping that drive to something else like E or L

**Comment by wpapp** [comment]
how to do? I do not know Programming.

**Comment by 1480c1** [comment]
Try getting this page in your native language

https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-drive-letter

**Comment by wpapp** [comment]
harfbuzz build ok,thank you.

**Comment by wpapp** [comment]
Hi @1480c1 
I want to backup the ffmpeg and share it to my friends, if right to backup local64\bin,bin-audio,bin-global,bin-video?

**Comment by 1480c1** [comment]
Should be yes
