### ISSUE TITLE
libmpv (mpv-1.dll) build not working

### ISSUE THREAD

**Issue by stax76** [m-ab-s/media-autobuild_suite#1958]
The last two builds of shinshiro [are crashing](https://github.com/shinchiro/mpv-winbuild-cmake/issues/112), so I thought maybe I can build libmpv using m-ab-s, but I'm not getting a mpv-1.dll file, it's only outputting a mpv.exe file.

My options:

--disable-cplayer
--disable-manpage-build

--enable-dvdnav
--enable-javascript
--enable-lcms2
--enable-libarchive
--enable-libbluray
--enable-libmpv-shared
--enable-lua
--enable-openal
--enable-pdf-build
--enable-rubberband
--enable-sdl2
--enable-spirv-cross
--enable-static-build
--enable-uchardet
--enable-vapoursynth
--enable-vulkan

**Comment by 1480c1** [comment]
Make sure you have the shared option enabled, inside build/media-autobuild_suite.ini on the line with ffmpegB2 needs to be set to either 3 or 5

**Comment by stax76** [comment]
Thanks for the support, unfortunately it didn't help. At this point for me, I think it's better to read a couple of tutorials first.
