### ISSUE TITLE
tesseract failed to build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1959]
┌ tesseract git  ...................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
  CXX      src/classify/libtesseract_la-intfx.lo
  CXX      src/classify/libtesseract_la-intmatcher.lo
  CXX      src/classify/libtesseract_la-intproto.lo
  CXX      src/classify/libtesseract_la-kdtree.lo
  CXX      src/classify/libtesseract_la-mf.lo
make[2]: *** No rule to make target 'src/classify/mfdefs.cpp', needed by 'src/classify/libtesseract_la-mfdefs.lo'.  Stop.
make[2]: Leaving directory '/build/tesseract-git/build-32bit'
make[1]: *** [Makefile:8661: all-recursive] Error 1
make[1]: Leaving directory '/build/tesseract-git/build-32bit'
make: *** [Makefile:3165: all] Error 2
make failed. Check D:/MABS-ffmpeg/build/tesseract-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-clV.zip

**Comment by 1480c1** [comment]
https://github.com/tesseract-ocr/tesseract/commit/6ddceac538856fda547b0b01c2039b90a3c05e22 try again

**Comment by Barough** [comment]
Working now :)
