### ISSUE TITLE
ffmpeg : patch could not be applied (64bit)

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1960]
Notice this when the suite was running. It's was like this yesterday also when i ran the suite.

┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
0001-Add-Alternative-VapourSynth-demuxer.patch
        Patch could not be applied with `git am`. Continuing without patching.

**Comment by 1480c1** [comment]
On line 1936, try adding `vcs_clean` if you don't have any other important file inside the ffmpeg-git directory and see if it stays there

**Comment by Barough** [comment]
Line 1936 say
        do_changeFFmpegConfig "$license"

Where do i add it. Don't know a damn thing about this kinda stuff

**Comment by 1480c1** [comment]
You can change it to
```bash
do_changeFFmpegConfig "$license"
vcs_clean
```

**Comment by Barough** [comment]
I'll add that on the row bellow then and give it a try.

**Comment by Barough** [comment]
Didn't make any difference. :(

**Comment by Barough** [comment]
Works fine now
