### ISSUE TITLE
x264: avisynth and opencl support

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1962]
x264 0.161.3053 c347e7a
x264 [warning]: OpenCL: not compiled with OpenCL support, disabling
or
avs [error]: failed to load avisynth
x264 [error]: could not open input file

Please, enable x264 avisynth and OpenCL support

**Comment by wiiaboo** [comment]
avisynth isn't disabled in the compilation, your installation of it is probably broken, and we're not video-help or doom9. Get usage help somewhere else.

On OpenCL, no. Too much work for little to no gain. Try to figure it out using [Custom Patches](https://github.com/m-ab-s/media-autobuild_suite#custom-patches) instead.
