### ISSUE TITLE
ffmpeg : patch could not be applied #2 (64bit)

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1963]
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.

**Comment by 1480c1** [comment]
https://github.com/OpenVisualCloud/SVT-VP9/issues/145

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/2f3f306f92f2e3887ea49f644c01e94dc01af57c

leaving open until upstream has a fix for it

**Comment by Barough** [comment]
Thnx :)

**Comment by Barough** [comment]
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
040-ffmpeg-add-svt-vp9.patch?h=ffmpeg-full-git
        Patch could not be applied with `git am`. Continuing without patching.
0001-Add-Alternative-VapourSynth-demuxer.patch
        Patch could not be applied with `git am`. Continuing without patching.

**Comment by Barough** [comment]
Gave it another try today........

┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
        Patch could not be applied with `git am`. Continuing without patching.
0001-Add-Alternative-VapourSynth-demuxer.patch
        Patch could not be applied with `git am`. Continuing without patching.
0002-vapoursynth_alt-use-atomic_int-for-async_pending.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...

**Comment by Barough** [comment]
Patch is gone........

+ ffmpeg git  ............................................ [Files missing]
+ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
+ 0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch  ..... [Failed]
Error 404 while downloading https://raw.githubusercontent.com/OpenVisualCloud/SVT-HEVC/master/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

**Comment by 1480c1** [comment]
updated the patches

**Comment by Barough** [comment]
Working just fine now. Thnx :)
