### ISSUE TITLE
[mingw64] libwebp build failure

### ISSUE THREAD

**Issue by slyfox1186** [m-ab-s/media-autobuild_suite#1967]
The libwebp-git repo has failed for the last 2 months every time I have attempted to build it. I thought it may get fixed over time but it still is giving me a build error. I attempted to manually install it running autoconfig and make but afterwards when I run the master update batch script it fails as soon as it gets to it.

This is what the window shows after it reports the error

``` bash
12:41:57 ┌ libwebp git  ................................. [Files missing]
12:41:58 ├ Running autoreconf...
12:42:20 ├ Running configure...
12:43:03 ├ Running make...
Likely error (tail of the failed operation logfile):
make[1]: Entering directory '/build/libwebp-git/build-64bit/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/build/libwebp-git/build-64bit/man'
Making all in extras
make[1]: Entering directory '/build/libwebp-git/build-64bit/extras'
  CCLD     webp_quality.exe
gcc.exe: error: G:/MAB-G/msys64/mingw64/lib/libpng16.dll.a: No such file or directory
make[1]: *** [Makefile:441: webp_quality.exe] Error 1
make[1]: Leaving directory '/build/libwebp-git/build-64bit/extras'
make: *** [Makefile:422: all-recursive] Error 1
make failed. Check G:/MAB-G/build/libwebp-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
12:43:42   Creating diagnostics file...
```

Below is the zip file as requested.
https://0x0.st/-a_B.zip

Does anyone have any ideas?

**Comment by 1480c1** [comment]
Have you tried completely cleaning `/build/libwebp-git`? The configure script should not be finding that nor should make be finding it as nothing indicates that it is resolving `-lpng16` to that, and we even pass `-lpng16` to LIBS

**Comment by slyfox1186** [comment]
> Have you tried completely cleaning `/build/libwebp-git`? The configure script should not be finding that nor should make be finding it as nothing indicates that it is resolving `-lpng16` to that, and we even pass `-lpng16` to LIBS

Yes I have. I have even completely deleted the entire suite and started over from scratch. If I change the build back to Zerano lite everything will update. As soon as I change the setting back to full update it fails at this repo. ￼￼

**Comment by slyfox1186** [comment]
For the time being until we can find a proper fix I successfully compiled this using visual studio code 2019.

In vs open a developer command prompt and cd into the `build\libwebp` folder. Now run the command: `nmake /f Makefile.vc CFG=release-static RTLIBCFG=static OBJDIR=output`

The next time you try to build this it should show the repo as updated and not throw a fatal error.

**Comment by 1480c1** [comment]
Since we are no longer using autotools, I'm going to assume the issue no longer exists
