### ISSUE TITLE
Compiling ffmpeg with librist library

### ISSUE THREAD

**Issue by laurfb** [m-ab-s/media-autobuild_suite#1972]
Hi. Anyone managed to build ffmpeg with rist library?

I build rist libraries with this code added in media-suite_compile.sh:

    _check=(librist.{a,pc} librist/librist.h)
    if do_vcs "https://code.videolan.org/rist/librist.git"; then
        do_uninstall include/librist "${_check[@]}"
		extracommands=("--default-library=static")
        do_mesoninstall video "${extracommands[@]}"
        do_checkIfExist
    fi

binaries are working well (ristsender/ristreceiver) but I've got some erros in ffmpeg build section:
....
19:52:32 ├ Running make...
Likely error (tail of the failed operation logfile):
E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-thread.o):(.text+0x1960): multiple definition of `pthread_exit'; E:/AB_Suite/local64/lib/librist.a(contrib_pthread-shim.c.obj):pthread-shim.c:(.text+0x80): first defined here
E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-thread.o):(.text+0x1e30): multiple definition of `pthread_cancel'; E:/AB_Suite/local64/lib/librist.a(contrib_pthread-shim.c.obj):pthread-shim.c:(.text+0xa0): first defined here
E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-thread.o):(.text+0x2420): multiple definition of `pthread_create'; E:/AB_Suite/local64/lib/librist.a(contrib_pthread-shim.c.obj):pthread-shim.c:(.text+0x0): first defined here
E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-thread.o):(.text+0x2700): multiple definition of `pthread_join'; E:/AB_Suite/local64/lib/librist.a(contrib_pthread-shim.c.obj):pthread-shim.c:(.text+0x50): first defined here
E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-thread.o):(.text+0x2a70): multiple definition of `pthread_detach'; E:/AB_Suite/local64/lib/librist.a(contrib_pthread-shim.c.obj):pthread-shim.c:(.text+0xc0): first defined here
E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-sem.o):(.text+0x130): multiple definition of `sem_init'; E:/AB_Suite/local64/lib/librist.a(contrib_pthread-shim.c.obj):pthread-shim.c:(.text+0x420): first defined here
E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-sem.o):(.text+0x3a0): multiple definition of `sem_wait'; E:/AB_Suite/local64/lib/librist.a(contrib_pthread-shim.c.obj):pthread-shim.c:(.text+0x460): first defined here
E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-sem.o):(.text+0x620): multiple definition of `sem_post'; E:/AB_Suite/local64/lib/librist.a(contrib_pthread-shim.c.obj):pthread-shim.c:(.text+0x4c0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:123: ffmpeg_g.exe] Error 1

Diagnostic logs: https://0x0.st/-a65.zip

regards,
laur

**Comment by 1480c1** [comment]
You might need `do_mesoninstall video -Dhave_mingw_pthreads=true`

**Comment by Sleepingbug** [comment]
Is there a complete compilation script?
