### ISSUE TITLE
libtiff - Patch could not be applied (x64)

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1974]
Just a little headsup..........

┌ libtiff git  ........................................ [Recently updated]
├ Running uninstall...
233.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libtiff-git  ................................................. [Updated]

**Comment by 1480c1** [comment]
hmm, applies cleanly for me

**Comment by Barough** [comment]
Have had a lot of 'Patch could not be applied with git am.' lately. Different patches here and there. A friend have basically had the same issues.
The '233.patch' issue is gone now.
