### ISSUE TITLE
stat: cannot stat 'hardlinktest': No such file or directory and other errors

### ISSUE THREAD

**Issue by necros2k7** [m-ab-s/media-autobuild_suite#1975]
win10x64
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6445691/logs.zip)

**Comment by 1480c1** [comment]
> info: using up to 500.0 MiB of RAM to unpack components
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-mingw'
info: installing component 'rust-std'
info: installing component 'rustc'
memory allocation of 16777216 bytes failed

How much ram do you have?

The
> stat: cannot stat 'hardlinktest': No such file or directory

is fine as that's just checking if you have symlink permission

**Comment by necros2k7** [comment]
hm 32gb total

**Comment by 1480c1** [comment]
Are you running the suite in some special way?

**Comment by 1480c1** [comment]
No response in 28 days, closing
