### ISSUE TITLE
Request: Add support for librsvg

### ISSUE THREAD

**Issue by spider-x** [m-ab-s/media-autobuild_suite#1977]
It would great to add support for lirbsvg.

**Comment by 1480c1** [comment]
Dup of https://github.com/m-ab-s/media-autobuild_suite/issues/1385,  might try looking at it again soon

**Comment by GyanD** [comment]
If I recall correctly, there were some build system or dependency changes in the last few years which made static linking a pain, but the library itself hasn't changed much, so earlier versions may be easier to include.
