### ISSUE TITLE
Request: plz add MLT Multimedia Framework

### ISSUE THREAD

**Issue by CoreSec-xyz** [m-ab-s/media-autobuild_suite#1980]
I think it was useful to add MLT to the Suite.
Some Video Editors use this Framework (Shotcut, Kdenlive).

https://www.mltframework.org/
https://github.com/mltframework/mlt

Thank you :-)

**Comment by wiiaboo** [comment]
Why?
What would building this in the suite add of value to the existing build packaged with Shotcut?

**Comment by 1480c1** [comment]
No response for a while, going to close
