### ISSUE TITLE
ffmpeg failed to build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#1981]
┌ ffmpeg git  ............................................ [Updates found]
├ Changing options to comply to nonfree...
libnpp is only supported in 64-bit.
CUDA_PATH environment variable not set or directory does not exist.
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(chacha-x86.o) and D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(ecp_nistz256-x86.o) and D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(poly1305-x86.o) and D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(sha1-586.o) and D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(sha256-586.o) and D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(sha512-586.o) and D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-gf2m.o) and D:/MABS-ffmpeg/msys64/mingw32/lib/libcrypto.a(x86-mont.o): warning: multiple common of `OPENSSL_ia32cap_P'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/local32/lib/libaom.a(pass2_strategy.c.o):pass2_strategy.c:(.text+0x12be): undefined reference to `warn'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:123: ffmpeg_g.exe] Error 1
make failed. Check D:/MABS-ffmpeg/build/ffmpeg-git/build-static-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-eqU.zip
Copy and paste [logs.zip](https://0x0.st/-eqU.zip) in the GitHub issue.

**Comment by wordlesswind** [comment]
### [mingw64] [ffmpeg] undefined reference to `warn'
------


``` bash
14:27:08 ┌ ffmpeg git  ............................... [Recently updated]
14:27:08 ├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK to run!
14:27:20 ├ Compiling static FFmpeg...
14:27:21 ├ Running configure...
14:31:54 ├ Running make...
Likely error (tail of the failed operation logfile):
make: *** [/build/ffmpeg-git/Makefile:123: ffprobe_g.exe] Error 1
make: *** Waiting for unfinished jobs....
collect2.exe: error: ld returned 1 exit status
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:123: ffplay_g.exe] Error 1
make: *** [/build/ffmpeg-git/Makefile:123: ffmpeg_g.exe] Error 1
LD      ffmpeg_g.exe
C:/src/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/src/media-autobuild_suite/local64/lib/libaom.a(pass2_strategy.c.o):pass2_strategy.c:(.text+0x1378): undefined reference to `warn'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:123: ffmpeg_g.exe] Error 1
make failed. Check C:/src/media-autobuild_suite/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
14:35:44   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-eTR.zip
Copy and paste [logs.zip](https://0x0.st/-eTR.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/-eTR.zip)

Windows 10 OS Version 21H1 (Build 19043.985)

**Comment by BlackScreen** [comment]
I have the same problem as mentioned in https://github.com/m-ab-s/media-autobuild_suite/issues/1981#issuecomment-845696777

**Comment by 1480c1** [comment]
Similar issue to https://github.com/m-ab-s/media-autobuild_suite/issues/1982

upstream issue https://bugs.chromium.org/p/aomedia/issues/detail?id=3064

**Comment by LucasMoskun** [comment]
I'm running into this too. Anyone have a quick workaround?

**Comment by Biswa96** [comment]
Not sure about the actual cause of this issue. But there is a definition in upstream which can be copy-pasted https://aomedia.googlesource.com/aom/+/refs/heads/master/common/tools_common.c
