### ISSUE TITLE
Errors running make when updating tesseract git - [Makefile:4021: libtesseract_ccutil.la] Error 1 & [Makefile:8585: all-recursive] Error 1

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1984]
``` bash
17:10:49   Running git update for tesseract...
17:10:54 ┌ tesseract git  ............................... [Updates found]
17:10:58 ├ Running autogen...
17:11:42 ├ Running uninstall...
17:11:42 ├ Running configure...
17:13:15 ├ Running make...
Likely error (tail of the failed operation logfile):
make: *** [Makefile:8585: all-recursive] Error 1
Making all in .
make[1]: Entering directory '/build/tesseract-git/build-64bit'
  CXXLD    libtesseract_ccutil.la
/usr/bin/grep: /local64/lib/libwebpmux.la: No such file or directory
/usr/bin/sed: can't read /local64/lib/libwebpmux.la: No such file or directory
libtool:   error: '/local64/lib/libwebpmux.la' is not a valid libtool archive
make[1]: *** [Makefile:4021: libtesseract_ccutil.la] Error 1
make[1]: Leaving directory '/build/tesseract-git/build-64bit'
make: *** [Makefile:8585: all-recursive] Error 1
make failed. Check C:/MinGW-w64/build/tesseract-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
17:17:04   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-ey8.zip
Copy and paste [logs.zip](https://0x0.st/-ey8.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/-ey8.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/6527825/ab-suite.make.log)

**Comment by moisespr123** [comment]
Same issue

[logs.zip](https://0x0.st/-ey7.zip)

**Comment by moisespr123** [comment]
I just got around this issue by copying another *.la file and renaming it to libwebpmux.la. Tesseract compiled successfully.

**Comment by ycwan** [comment]
@moisespr123 
Your workaround do not work for me

**Comment by ycwan** [comment]
Is there any expert ln MAB who can offer a fix for this problem.  I tried Moises Cardona workaround but to no avail.  Thanks

**Comment by 1480c1** [comment]
Perhaps delete build/libwebp-git and local64/lib/libwebpmux.la to make sure it rebuilds? libwebp no longer uses autotools, so it no longer produces .la files, thus tesseract should not detect or worry about it

**Comment by ycwan** [comment]
@1480c1
Thank you for your reply.

I only deleted the folder build/libwebp-git because the file libwebpmux.la can't be found in folder local64/lib.  Run MAB again, libwebp was rebuilt successfully but still the same error when updating tesseract git.  Append below the MAB output.

15:38:56   Running git clone for libwebp...
15:39:05 ┌ libwebp git  .............................. [Recently updated]
15:39:06 ├ Installing giflib... done
15:39:11 ├ Running uninstall...
15:39:12 ├ Running cmake...
15:39:27 ├ Running build...
15:39:33 ├ Running install...
15:39:34 ├ Stripping...
15:39:34 └ libwebp-git  ....................................... [Updated]

15:39:55   Running git update for tesseract...
15:40:08 ┌ tesseract git  ............................ [Recently updated]
15:40:13 ├ Running autogen...
15:40:49 ├ Running configure...
15:42:15 ├ Running make...
Likely error (tail of the failed operation logfile):
make: *** [Makefile:8585: all-recursive] Error 1
Making all in .
make[1]: Entering directory '/build/tesseract-git/build-64bit'
  CXXLD    libtesseract_ccutil.la
/usr/bin/grep: /local64/lib/libwebpmux.la: No such file or directory
/usr/bin/sed: can't read /local64/lib/libwebpmux.la: No such file or directory
libtool:   error: '/local64/lib/libwebpmux.la' is not a valid libtool archive
make[1]: *** [Makefile:4021: libtesseract_ccutil.la] Error 1
make[1]: Leaving directory '/build/tesseract-git/build-64bit'
make: *** [Makefile:8585: all-recursive] Error 1
make failed. Check C:/MinGW-w64/build/tesseract-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
15:43:18   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-_Vu.zip
Copy and paste [logs.zip](https://0x0.st/-_Vu.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by 1480c1** [comment]
Just to make sure, do you remember if the error appeared even after deleting /build/tesseract-git?

**Comment by ycwan** [comment]
Yes I have tried deleting /build/tesseract-git and there still error

**Comment by ycwan** [comment]
Run MAB and this issue did not happen again but openal-soft git encounter issue just like issue #2005
