### ISSUE TITLE
less header files

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#1991]
If I copy the header file and DLL file into the VC development project,
There should be three less header files: MinGW. h, inttypes. h, stdint. h.
It's better to add.

**Comment by 1480c1** [comment]
The output of mabs is not meant to be used in msvc as that is not an intended goal. Rather, it would be better to rely on the headers from MSVC instead of mingw-w64 as MSVC links to a different C runtime than what mingw-w64 does by default, they are not meant to be binary interchangeable.
