### ISSUE TITLE
[mingw64] [libwebp] Build error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#1998]
10:53:43 ┌ libwebp git  .............................. [Recently updated]
Failed to apply patch ''
Patch without filename, ignoring. Specify an explicit filename.
10:53:58 ├ Running cmake...
10:54:08 ├ Running build...
Likely error (tail of the failed operation logfile):
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1d90): undefined reference to `__imp_glVertexPointer'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1da0): undefined reference to `__imp_glNormalPointer'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1dc3): undefined reference to `__imp_glTexCoordPointer'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1ddf): undefined reference to `__imp_glDrawElements'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e10): undefined reference to `__imp_glDisableClientState'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1f13): undefined reference to `__imp_glDrawElements'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1f2c): undefined reference to `__imp_glDrawArrays'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libglut.a(fg_ext_mswin.c.obj):fg_ext_mswin.c:(.text+0x123): undefined reference to `__imp_wglGetProcAddress'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by kliffgomel** [comment]
[logs.zip](https://0x0.st/-L39.zip)

**Comment by kliffgomel** [comment]
for clang build:
12:24:03 ┌ libtiff git  ................................. [Updates found]
12:24:09 ├ Running uninstall...
12:24:10 ├ Running cmake...
12:24:26 ├ Running build...
12:24:39 ├ Running install...
12:24:40 ├ Stripping...
12:24:40 └ libtiff-git  ....................................... [Updated]
12:24:41   Running git clone for libwebp...
12:24:49 ┌ libwebp git  .............................. [Recently updated]
0001-CMake-add-WEBP_BUILD_LIBWEBPMUX.patch
        Patch could not be applied with `git am`. Continuing without patching.
12:25:04 ├ Running uninstall...
12:25:04 ├ Running cmake...
12:25:21 ├ Running build...
Likely error (tail of the failed operation logfile):
D:/ffmpeg-autobuild-clang/msys64/mingw64/bin/ld: D:/ffmpeg-autobuild-clang/local64/lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x5d4): undefined reference to `ZSTD_endStream'
D:/ffmpeg-autobuild-clang/msys64/mingw64/bin/ld: D:/ffmpeg-autobuild-clang/local64/lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x5df): undefined reference to `ZSTD_isError'
D:/ffmpeg-autobuild-clang/msys64/mingw64/bin/ld: D:/ffmpeg-autobuild-clang/local64/lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x62c): undefined reference to `ZSTD_getErrorName'
D:/ffmpeg-autobuild-clang/msys64/mingw64/bin/ld: D:/ffmpeg-autobuild-clang/local64/lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x6be): undefined reference to `ZSTD_compressStream'
D:/ffmpeg-autobuild-clang/msys64/mingw64/bin/ld: D:/ffmpeg-autobuild-clang/local64/lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x6c9): undefined reference to `ZSTD_isError'
D:/ffmpeg-autobuild-clang/msys64/mingw64/bin/ld: D:/ffmpeg-autobuild-clang/local64/lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x721): undefined reference to `ZSTD_getErrorName'
D:/ffmpeg-autobuild-clang/msys64/mingw64/bin/ld: D:/ffmpeg-autobuild-clang/local64/lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x794): undefined reference to `ZSTD_freeDStream'
D:/ffmpeg-autobuild-clang/msys64/mingw64/bin/ld: D:/ffmpeg-autobuild-clang/local64/lib/libtiff.a(tif_zstd.c.obj):tif_zstd.c:(.text+0x7b0): undefined reference to `ZSTD_freeCStream'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6669581/logs.zip)

**Comment by BlackScreen** [comment]
Same here...

```
11:32:58 ┌ libwebp git  ................................. [Updates found]
11:33:00 ├ Installing giflib... done
0001-CMake-add-WEBP_BUILD_LIBWEBPMUX.patch
        Patch could not be applied with `git am`. Continuing without patching.
11:33:21 ├ Running uninstall...
11:33:21 ├ Running cmake...
11:33:44 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS_All/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e1a): undefined reference to `__imp_glVertexPointer'
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS_All/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e2a): undefined reference to `__imp_glNormalPointer'
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS_All/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e4d): undefined reference to `__imp_glTexCoordPointer'
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS_All/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e69): undefined reference to `__imp_glDrawElements'
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS_All/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e9e): undefined reference to `__imp_glDisableClientState'
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS_All/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1f93): undefined reference to `__imp_glDrawElements'
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS_All/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1fac): undefined reference to `__imp_glDrawArrays'
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS_All/local64/lib/libglut.a(fg_ext_mswin.c.obj):fg_ext_mswin.c:(.text+0x123): undefined reference to `__imp_wglGetProcAddress'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/Development/MABS_All/build/libwebp-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
11:33:56   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-9bY.zip
Copy and paste [logs.zip](https://0x0.st/-9bY.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by 1480c1** [comment]
Right now trying to work with cmake upstream to try to fix their Find*.cmake files, if they are fine, I will try to backport them to the mingw-packages repo

**Comment by snowbie** [comment]
Was just about to make a post regarding this, but the error spat out from your clang build is identical to mine. Hopefully it's resolved soon :)

**Comment by 1480c1** [comment]
Working on it at https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6251, may take some time

**Comment by viliml** [comment]
Any temporary workaround we can use?

**Comment by kliffgomel** [comment]
It looks like the compilation is now working. But there were patch warnings.

15:28:00 ┌ libwebp git  .............................. [Recently updated]
0002-CMake-set-CMP0072-to-NEW.patch
        Patch could not be applied with `git am`. Continuing without patching.
0006-CMake-use-target_include_directories-instead-of-incl.patch
        Patch could not be applied with `git am`. Continuing without patching.
0007-CMake-use-import-libraries-if-possible-for-vwebp.patch
        Patch could not be applied with `git am`. Continuing without patching.
0009-CMake-include-src-along-with-binary_dir-src.patch
        Patch could not be applied with `git am`. Continuing without patching.
15:28:14 ├ Running cmake...
15:28:28 ├ Running build...
15:28:37 ├ Running install...
15:28:38 ├ Stripping...
15:28:39 └ libwebp-git  ....................................... [Updated]

**Comment by snowbie** [comment]
Still failed on the clang build.

```
┌ libwebp git  ........................................ [Recently updated]
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
C:/media-autobuild_suite/msys64/mingw64/bin/ld: C:/media-autobuild_suite/msys64/mingw64/lib/libtiff.a(tif_jbig.o):tif_jbig.c:(.text+0xb2): undefined reference to `jbg_newlen'
C:/media-autobuild_suite/msys64/mingw64/bin/ld: C:/media-autobuild_suite/msys64/mingw64/lib/libtiff.a(tif_jbig.o):tif_jbig.c:(.text+0xcb): undefined reference to `jbg_dec_in'
C:/media-autobuild_suite/msys64/mingw64/bin/ld: C:/media-autobuild_suite/msys64/mingw64/lib/libtiff.a(tif_jbig.o):tif_jbig.c:(.text+0xde): undefined reference to `jbg_dec_getsize'
C:/media-autobuild_suite/msys64/mingw64/bin/ld: C:/media-autobuild_suite/msys64/mingw64/lib/libtiff.a(tif_jbig.o):tif_jbig.c:(.text+0xfb): undefined reference to `jbg_dec_getimage'
C:/media-autobuild_suite/msys64/mingw64/bin/ld: C:/media-autobuild_suite/msys64/mingw64/lib/libtiff.a(tif_jbig.o):tif_jbig.c:(.text+0x111): undefined reference to `jbg_dec_free'
C:/media-autobuild_suite/msys64/mingw64/bin/ld: C:/media-autobuild_suite/msys64/mingw64/lib/libtiff.a(tif_jbig.o):tif_jbig.c:(.text+0x173): undefined reference to `jbg_strerror'
C:/media-autobuild_suite/msys64/mingw64/bin/ld: C:/media-autobuild_suite/msys64/mingw64/lib/libtiff.a(tif_jbig.o):tif_jbig.c:(.text+0x1a0): undefined reference to `jbg_dec_free'
C:/media-autobuild_suite/msys64/mingw64/bin/ld: C:/media-autobuild_suite/msys64/mingw64/lib/libtiff.a(tif_jbig.o):tif_jbig.c:(.text+0x1f6): undefined reference to `jbg_dec_free'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
https://0x0.st/-pb5.zip

**Comment by 1480c1** [comment]
Try again, updated the patch

**Comment by snowbie** [comment]
Built now with no problem, thanks
