### ISSUE TITLE
Building from a custom build 

### ISSUE THREAD

**Issue by Yankees4life** [m-ab-s/media-autobuild_suite#2001]
Hello

Great program you have. But I'm wondering if I can build from a custom build. I want to get ac4 support on my ffmpeg build from this link
https://github.com/richardpl/FFmpeg/tree/ac4

What to do to let this app use this?

Cheers

**Comment by 1480c1** [comment]
To add additional customization, you can use the extra scripts mentioned at https://github.com/m-ab-s/media-autobuild_suite#custom-patches to either checkout that repo and branch instead of the normal ffmpeg branch, but of course, the script cannot reasonably provide support if it fails.

**Comment by 1480c1** [comment]
An example would be to open mintty and run `nano /build/ffmpeg_extra.sh` and add the content
```bash
_pre_configure(){
    git fetch https://github.com/richardpl/FFmpeg.git ac4
    git reset --hard FETCH_HEAD
}
```
