### ISSUE TITLE
rav1e fail to build (64bit)

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2004]
┌ rav1e git  .......................................... [Recently updated]
├ Running rust.update...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
/opt/cargo/bin/cargo.exe update
error: the 'cargo.exe' binary, normally provided by the 'cargo' component, is not applicable to the 'stable-x86_64-pc-windows-gnu' toolchain
rust.update failed. Check D:/mabs/build/rav1e-git/ab-suite.rust.update.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-pjx.zip
Copy and paste [logs.zip](https://0x0.st/-pjx.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
I don't think I've seen this kind of error before, can you try deleting `/opt/cargo` and rerunning?

**Comment by Barough** [comment]
I'll give that a try and get back

**Comment by Barough** [comment]
That solved it. :)
