### ISSUE TITLE
openal-soft git failed to build (32bit)

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2005]
┌ openal-soft git  .................................... [Recently updated]
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
In file included from ../core/cpu_caps.cpp:18:
D:/MABS-ffmpeg/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.3.0/include/cpuid.h:300:1: error: redefinition of 'int __get_cpuid_count(unsigned int, unsigned int, unsigned int*, unsigned int*, unsigned int*, unsigned int*)'
  300 | __get_cpuid_count (unsigned int __leaf, unsigned int __subleaf,
      | ^~~~~~~~~~~~~~~~~
In file included from D:/MABS-ffmpeg/msys64/mingw32/i686-w64-mingw32/include/intrin.h:70,
                 from ../core/cpu_caps.cpp:15:
D:/MABS-ffmpeg/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.3.0/include/cpuid.h:300:1: note: 'int __get_cpuid_count(unsigned int, unsigned int, unsigned int*, unsigned int*, unsigned int*, unsigned int*)' previously defined here
  300 | __get_cpuid_count (unsigned int __leaf, unsigned int __subleaf,
      | ^~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check D:/MABS-ffmpeg/build/openal-soft-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-pEM.zip
Copy and paste [logs.zip](https://0x0.st/-pEM.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
The issue seems to be that `cpuid.h` doesn't have any header guards. Seems to be a GCC issue that I'm not sure where would be the best place to go to fix atm

**Comment by Biswa96** [comment]
IMO, patching this in mingw-packages would be the fastest way 🤔

**Comment by ycwan** [comment]
Same issue here

22:23:28   Running git clone for openal-soft...
22:23:38 ┌ openal-soft git  .......................... [Recently updated]
22:23:40 ├ Running cmake...
22:23:51 ├ Running build...
Likely error (tail of the failed operation logfile):
In file included from ../core/cpu_caps.cpp:18:
C:/MinGW-w64/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/include/cpuid.h:300:1: error: redefinition of 'int __get_cpuid_count(unsigned int, unsigned int, unsigned int*, unsigned int*, unsigned int*, unsigned int*)'
  300 | __get_cpuid_count (unsigned int __leaf, unsigned int __subleaf,
      | ^~~~~~~~~~~~~~~~~
In file included from C:/MinGW-w64/msys64/mingw64/x86_64-w64-mingw32/include/intrin.h:70,
                 from ../core/cpu_caps.cpp:15:
C:/MinGW-w64/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/include/cpuid.h:300:1: note: 'int __get_cpuid_count(unsigned int, unsigned int, unsigned int*, unsigned int*, unsigned int*, unsigned int*)' previously defined here
  300 | __get_cpuid_count (unsigned int __leaf, unsigned int __subleaf,
      | ^~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW-w64/build/openal-soft-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
22:24:00   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-pFr.zip
Copy and paste [logs.zip](https://0x0.st/-pFr.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/6741817/ab-suite.build.log)

**Comment by BlackScreen** [comment]
Yeah, same here with 64 bit.

**Comment by Biswa96** [comment]
There is a proposed fix for gcc in msys2/mingw-packages. The temporary package is in staging area https://repo.msys2.org/staging/. Try the `mingw-w64-i686-gcc` package from that repository with `pacman -U` command.

p.s. As usual, staging packages are unstable and may not be in actual release.

**Comment by Biswa96** [comment]
There is a new gcc package. Update packages and try with it.

**Comment by Barough** [comment]
Seems to be working fine now after the new gcc package
