### ISSUE TITLE
When I run the script this prompt appears, I don't know what to do

### ISSUE THREAD

**Issue by zhanghongyong123456** [m-ab-s/media-autobuild_suite#2010]
``` bash
Paste output of the suite here
```

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)
![60](https://user-images.githubusercontent.com/48466610/125735920-fd4b282e-2e45-467a-b90a-074aae17437b.png)

It's not like you have a YouTube video where you have options

**Comment by 1480c1** [comment]
Try running media-autobuild_suite.bat by double clicking or find a way to run it without having the visual studio tools in PATH

**Comment by zhanghongyong123456** [comment]
> Try running media-autobuild_suite.bat by double clicking or find a way to run it without having the visual studio tools in PATH

ok i try it，thank you replay

**Comment by 1480c1** [comment]
Assuming closed
