### ISSUE TITLE
[mingw64] [ffmpeg-git] libass error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2011]
20:24:18 ┌ ffmpeg git  ............................... [Recently updated]
20:24:18 ├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK to run!
20:24:25 ├ Compiling static FFmpeg...
20:24:27 ├ Running configure...
20:29:04 ├ Running make...
Likely error (tail of the failed operation logfile):
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:123: ffmpeg_g.exe] Error 1
make: *** Waiting for unfinished jobs....
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:123: ffprobe_g.exe] Error 1
LD      ffmpeg_g.exe
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libass.a(ass_directwrite.o):ass_directwrite.c:(.text+0x6eb): undefined reference to `__imp_GetTextFaceW'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/libass.a(ass_directwrite.o):ass_directwrite.c:(.text+0xde0): undefined reference to `__imp_EnumFontFamiliesW'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:123: ffmpeg_g.exe] Error 1
make failed. 

[logs.zip](https://0x0.st/-Okg.zip)

**Comment by rmkimathi** [comment]
Experiencing same error. Build process terminates before completing ffmpeg compile.

**Comment by Biswa96** [comment]
Try to add `-lgdi32 -ldwrite` in `Libs.private` entry in libass.pc file.

**Comment by rmkimathi** [comment]
> Try to add `-lgdi32 -ldwrite` in `Libs.private` entry in libass.pc file.

Thanks for this hack. It works applied to local64/lib/pkgconfig/libass.pc ..... libass-git newer dependencies will overwrite

**Comment by 1480c1** [comment]
I will probably have to submit a PR or something to libass about those, their pkg-config file seems to lack quite a bit.

**Comment by BlackScreen** [comment]
Same problem here...

```
15:35:47   Running git clone for ffmpeg...
15:37:37 ┌ ffmpeg git  ............................... [Recently updated]
15:37:37 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
15:37:51 ├ Compiling static FFmpeg...
15:37:53 ├ Running configure...
15:45:35 ├ Running make...
Likely error (tail of the failed operation logfile):
make: *** [/build/ffmpeg-git/Makefile:123: ffmpeg_g.exe] Error 1
make: *** Waiting for unfinished jobs....
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:123: ffplay_g.exe] Error 1
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:123: ffprobe_g.exe] Error 1
LD      ffmpeg_g.exe
C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS_All/local64/lib/librist.a(contrib_time-shim.c.obj):time-shim.c:(.text+0x60): multiple definition of `clock_gettime'; C:/Development/MABS_All/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-clock.o):clock.c:(.text+0x100): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:123: ffmpeg_g.exe] Error 1
make failed. Check C:/Development/MABS_All/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
15:48:32   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-W92.zip
Copy and paste [logs.zip](https://0x0.st/-W92.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by 1480c1** [comment]
your issue seems more like https://github.com/m-ab-s/media-autobuild_suite/issues/2013

**Comment by 1480c1** [comment]
Looking at this chain https://github.com/libass/libass/blob/12be84bf5dc57b498bac8ece18137f0d4a29024d/configure.ac#L163-L169 it seems the two libs @Biswa96 mentioned are being added to `LIBS`, but aren't actually appearing in libass.pc

**Comment by kliffgomel** [comment]
Still doesn't work out of the box ..
