### ISSUE TITLE
[repo][mingw64] [ffmpeg] LibRist fails x86 compilation

### ISSUE THREAD

**Issue by Ozyrys24** [m-ab-s/media-autobuild_suite#2015]
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mtune=generic -O2 -pipe
CXXFLAGS: -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
meson .. --default-library=static --buildtype=release --prefix=/local32 --backend=ninja --bindir=bin-global -Dhave_mingw_pthreads=true -Dtest=false -Dallow_obj_filter=true
The Meson build system
Version: 0.58.1
Source dir: C:/fb2/build/librist-git
Build dir: C:/fb2/build/librist-git/build-32bit
Build type: native build
Project name: libRIST
Project version: 0.2.5
C compiler for the host machine: clang.bat (clang 12.0.1 "clang version 12.0.1")
C linker for the host machine: clang.bat ld.bfd 2.36.1
Host machine cpu family: x86
Host machine cpu: i686
Library ws2_32 found: YES
Has header "pthread.h" : YES 
Run-time dependency threads found: YES
Compiler for C supports arguments -wd4996: NO 
Compiler for C supports arguments -wd4324: NO 
Compiler for C supports arguments -fvisibility=hidden: YES 
Check usable header "stdatomic.h" : YES 
Found pkg-config: --keep-system-cflags (1.7.4)
Found CMake: C:\fb2\msys64\mingw32\bin/cmake.EXE (3.21.0)
Run-time dependency cjson found: NO (tried pkgconfig and cmake)
Has header "cjson/cJSON.h" : NO 
Message: Using builtin cJSON library
Message: Building mbedtls
Run-time dependency mbedcrypto found: NO (tried pkgconfig and cmake)
Has header "mbedtls/aes.h" : YES 
Library mbedcrypto found: YES
Program C:/fb2/msys64/mingw32/bin/meson found: YES (C:/fb2/msys64/mingw32/bin/meson.exe)
Configuring version.h using configuration
Program objcopy found: YES (C:\fb2\msys64\mingw32\bin/objcopy.EXE)
Message: Using objcopy to localize symbols in static library
Configuring config.h using configuration
Message: Building tools
Library ws2_32 found: YES
Build targets in project: 7

Found ninja-1.10.2 at C:\fb2\msys64\mingw32\bin/ninja.EXE

ERROR: clang does not know how to do prelinking.

A full log can be found at C:/fb2/build/librist-git/build-32bit/meson-logs/meson-log.txt

``` bash
01:27:03   Running git clone for librist...
01:27:11 ┌ librist git  .............................. [Recently updated]
01:27:13 ├ Running meson...
Likely error (tail of the failed operation logfile):
Configuring config.h using configuration
Message: Building tools
Library ws2_32 found: YES
Build targets in project: 7

Found ninja-1.10.2 at C:\fb2\msys64\mingw32\bin/ninja.EXE

ERROR: clang does not know how to do prelinking.

A full log can be found at C:/fb2/build/librist-git/build-32bit/meson-logs/meson-log.txt
meson failed. Check C:/fb2/build/librist-git/build-32bit/ab-suite.meson.log
This is required for other packages, so this script will exit.
01:27:17   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-Vg2.zip
Copy and paste [logs.zip](https://0x0.st/-Vg2.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

[logs.zip](https://0x0.st/-Vg2.zip)

**Comment by 1480c1** [comment]
reverted the commit for now
