### ISSUE TITLE
Commit '20b0363' broke ffmpeg build

### ISSUE THREAD

**Issue by laurfb** [m-ab-s/media-autobuild_suite#2019]
Hi.
Commit '**20b0363**' (**Revert "Revert "librist: use allow_obj_filter""**) seems to broke again ffmpeg.
Reverting revert :) to '**956cec3**' commit fix this behaviour.
Please find the log files: https://0x0.st/-4z5.zip

Regards,
Laur

**Comment by 1480c1** [comment]
```c
LD	ffprobe_g.exe
E:/AB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/AB_Suite/local64/lib/libsrt.a(api.cpp.o):api.cpp:(.text+0xddbb): undefined reference to `.refptr.in6addr_any'
```
this seems to be a different issue not related to librist

**Comment by laurfb** [comment]
Hi.
Yes, '-Dallow_obj_filter' option seems to broke libsrt reference in ffmpeg build (maybe duplicate reference from libsrt/librist). You know better.
However, replacing 'extracommands=("-Dallow_obj_filter=true")' with 'extracommands=("-Ddisable_json=true")' in line 1719 (librist build code) in media-suite_compile.sh file (reverting commit 20b0363) seems to resolve this issue with both libs enabled (libsrt & librist).
I didn't try yet to disable libsrt build while keeping librist (and commit 20b0363) to see what's happening.
regards,
laur

**Comment by laurfb** [comment]
Hi.
Yep, ffmpeg build Ok when librist are enabled and libsrt are disabled with 'extracommands=("-Dallow_obj_filter=true")'.
regards,
laur

**Comment by 1480c1** [comment]
reverted the revert, so it's using the `-Ddisable_json` option
