### ISSUE TITLE
[mingw64] [vulkan-loader] Error: Patch could not be applied with `git am`

### ISSUE THREAD

**Issue by Ajaja** [m-ab-s/media-autobuild_suite#2020]
``` bash
┌ vulkan-loader git  ..................................... [Files missing]
├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running dependencies...
├ Installing Vulkan-Headers...
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ Building Vulkan-Loader...
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -IM:/media-autobuild_suite/build/vulkan-loader-git/loader -IM:/media-autobuild_suite/build/vulkan-loader-git/loader/generated -IM:/media-autobuild_suite/build/vulkan-loader-git/build-64bit/loader  /c /Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj M:/media-autobuild_suite/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: GetOverlappedResult: The handle is invalid.

[1/6] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -IM:/media-autobuild_suite/build/vulkan-loader-git/loader -IM:/media-autobuild_suite/build/vulkan-loader-git/loader/generated -IM:/media-autobuild_suite/build/vulkan-loader-git/build-64bit/loader  /c /Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj M:/media-autobuild_suite/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check M:/media-autobuild_suite/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-Jd0.zip
Copy and paste [logs.zip](https://0x0.st/-Jd0.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6986202/logs.zip)

```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6986205/logs.zip)

**Comment by Barough** [comment]
Same issue here also. 32-bit

┌ vulkan-loader git  .................................. [Recently updated]
├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running dependencies...
├ Installing Vulkan-Headers...
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ Building Vulkan-Loader...
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
  331 | static bool loader_platform_is_path_absolute(const char *path) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/MABS-ffmpeg/build/vulkan-loader-git/loader/vk_loader_platform.h:324:13: warning: 'loader_platform_file_exists' defined but not used [-Wunused-function]
  324 | static bool loader_platform_file_exists(const char *path) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[2/10] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -ID:/MABS-ffmpeg/build/vulkan-loader-git/loader -ID:/MABS-ffmpeg/build/vulkan-loader-git/loader/generated -ID:/MABS-ffmpeg/build/vulkan-loader-git/build-32bit/loader  /c /Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj D:/MABS-ffmpeg/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check D:/MABS-ffmpeg/build/vulkan-loader-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-JFH.zip
Copy and paste [logs.zip](https://0x0.st/-JFH.zip) in the GitHub issue.

**Comment by Biswa96** [comment]
Please format the output for the ease of readability.

**Comment by 1480c1** [comment]
I rebased the patches, try again

**Comment by Ajaja** [comment]
@1480c1 
Thank you, `vulkan-loader` builds fine now.
