### ISSUE TITLE
Patch could not be applied with `git am` (64bit)

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2023]
The patch issue with the vulkan-loader have been around for 2-3 days now and the VapourSynth-demuxer patch issue have been around for like over a week. Have made over 10 attempts now with building ffmpeg.

A friend of mine have the same issues also with these patches in question.

┌ vulkan-loader git  .................................. [Recently updated] 
├ Running uninstall...
0002-loader-vulkan.pc.in-use-the-normal-prefix-and-exec_p.patch
        Patch could not be applied with `git am`. Continuing without patching.

┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
0001-Add-Alternative-VapourSynth-demuxer.patch
        Patch could not be applied with `git am`. Continuing without patching.

**Comment by 1480c1** [comment]
Can you check again on the vulkan-loader stuff? I recently rebased those patches

For the vapoursynth patch, I rebased it as well, but I didn't see any conflicts

**Comment by Barough** [comment]
This time so did vulkan-loader & ffmpeg compile fine without any patch issues.

Haven't been able to check with my friend since he's away atm and doesn't come home until thursday or friday.
