### ISSUE TITLE
ffmpeg,exe cannot proceed because libLerc.dll was not found

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2024]
A totally new issue i've never stumbled over. It have surfaced sometime after August 31st.

Any suggestions??

![ffmpeg](https://user-images.githubusercontent.com/13651586/129653584-e9024422-502f-4383-abfb-ff92a7ce60b0.jpg)

**Comment by Ajaja** [comment]
It's a `libtiff` dependency.  And I can't find the static version of `libLerc` in `msys2`.  Do we need `--disable-lerc` there?

**Comment by 1480c1** [comment]
Please try deleting `build/libtiff-git` and rebuilding, I disabled lerc for it

**Comment by Barough** [comment]
Working fine now.
