### ISSUE TITLE
Windows build fails - media-autobuild_suite.bat uses system path to find pandoc, not absolute or relative paths...

### ISSUE THREAD

**Issue by FredThompsonII** [m-ab-s/media-autobuild_suite#2025]
windows, not linux, so no bash, here is bat output

18:33:32 ├ Running make...
Likely error (tail of the failed operation logfile):
  CC       json.o
  CC       base64.o
/c/Portable/- Linked/misc/pandoc -s -w man -f markdown -o jo.1 ../jo.pandoc
make: /c/Portable/-: No such file or directory
make: *** [Makefile:1235: jo.1] Error 127
make: *** Waiting for unfinished jobs....
  CCLD     jo.exe
/c/Portable/- Linked/misc/pandoc -s -w man -f markdown -o jo.1 ../jo.pandoc
make: /c/Portable/-: No such file or directory
make: *** [Makefile:1235: jo.1] Error 127
make failed. Check C:/test/build/jo-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
18:33:33   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-yeG.zip

Paste output of the suite here
```

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)

Issue seems to be batch accesses pandoc through my system path, not its own copy. How to ensure media-autobuild_suite.bat uses hard-coded or relative-only paths and not system path?

**Comment by Biswa96** [comment]
Where does this path come from `/c/Portable/- Linked/misc/pandoc`? The path contains space. Did you have any program installed which provides pandoc?

**Comment by 1480c1** [comment]
Can you try again?

**Comment by 1480c1** [comment]
no response in 26 days, closing
