### ISSUE TITLE
Neon Git Failed  while running Make

### ISSUE THREAD

**Issue by Weezzel** [m-ab-s/media-autobuild_suite#2026]
Neon Git Failed  while running Make on Windows setup, After latest Git Pull Today.

20:43:45 ┌ neon git  ................................. [Recently updated]
20:43:46 ├ Running autogen...
20:43:58 ├ Running configure...
20:45:10 ├ Running make...
Likely error (tail of the failed operation logfile):
../../src/ne_socket.c:2074:44: note: each undeclared identifier is reported only once for each function it appears in
../../src/ne_socket.c:2075:31: error: 'SHUT_WR' undeclared (first use in this function)
 2075 |      (flags == NE_SOCK_SEND ? SHUT_WR : SHUT_RDWR));
      |                               ^~~~~~~
../../src/ne_socket.c:2075:41: error: 'SHUT_RDWR' undeclared (first use in this function)
 2075 |      (flags == NE_SOCK_SEND ? SHUT_WR : SHUT_RDWR));
      |                                         ^~~~~~~~~
make[1]: *** [Makefile:69: ne_socket.lo] Error 1
make[1]: Leaving directory '/build/neon-git/build-64bit/src'
make: *** [Makefile:88: subdirs] Error 2

 [logs.zip](https://0x0.st/-yJK.zip)

**Comment by slyfox1186** [comment]
Same issue for me.

```
05:25:56 └ ffmpeg-git  ........................................ [Updated]
05:26:00   Running git clone for neon...
05:26:04 ┌ neon git  ................................. [Recently updated]
05:26:04 ├ Running autogen...
05:26:16 ├ Running configure...
05:27:17 ├ Running make...
Likely error (tail of the failed operation logfile):
../../src/ne_socket.c:2074:44: note: each undeclared identifier is reported only once for each function it appears in
../../src/ne_socket.c:2075:31: error: 'SHUT_WR' undeclared (first use in this function)
 2075 |      (flags == NE_SOCK_SEND ? SHUT_WR : SHUT_RDWR));
      |                               ^~~~~~~
../../src/ne_socket.c:2075:41: error: 'SHUT_RDWR' undeclared (first use in this function)
 2075 |      (flags == NE_SOCK_SEND ? SHUT_WR : SHUT_RDWR));
      |                                         ^~~~~~~~~
make[1]: *** [Makefile:69: ne_socket.lo] Error 1
make[1]: Leaving directory '/build/neon-git/build-64bit/src'
make: *** [Makefile:88: subdirs] Error 2
make failed. Check E:/MAB-E/build/neon-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
05:27:21   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-ytW.zip
Copy and paste [logs.zip](https://0x0.st/-ytW.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

https://0x0.st/-ytW.zip

**Comment by Weezzel** [comment]
> Same issue for me.
> 
> **You can skip neon-git by removing cyanrip from the update list in 'media-autobuild_suite.ini'**
> 
> ```
> 05:25:56 └ ffmpeg-git  ........................................ [Updated]
> 05:26:00   Running git clone for neon...
> 05:26:04 ┌ neon git  ................................. [Recently updated]
> 05:26:04 ├ Running autogen...
> 05:26:16 ├ Running configure...
> 05:27:17 ├ Running make...
> Likely error (tail of the failed operation logfile):
> ../../src/ne_socket.c:2074:44: note: each undeclared identifier is reported only once for each function it appears in
> ../../src/ne_socket.c:2075:31: error: 'SHUT_WR' undeclared (first use in this function)
>  2075 |      (flags == NE_SOCK_SEND ? SHUT_WR : SHUT_RDWR));
>       |                               ^~~~~~~
> ../../src/ne_socket.c:2075:41: error: 'SHUT_RDWR' undeclared (first use in this function)
>  2075 |      (flags == NE_SOCK_SEND ? SHUT_WR : SHUT_RDWR));
>       |                                         ^~~~~~~~~
> make[1]: *** [Makefile:69: ne_socket.lo] Error 1
> make[1]: Leaving directory '/build/neon-git/build-64bit/src'
> make: *** [Makefile:88: subdirs] Error 2
> make failed. Check E:/MAB-E/build/neon-git/build-64bit/ab-suite.make.log
> This is required for other packages, so this script will exit.
> 05:27:21   Creating diagnostics file...
> 
> All relevant logs have been anonymously uploaded to https://0x0.st/-ytW.zip
> Copy and paste [logs.zip](https://0x0.st/-ytW.zip) in the GitHub issue.
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
> Try running the build again at a later time.
> ```
> 
> https://0x0.st/-ytW.zip

cyanrip2=2 in my media-autobuild_suite.ini file. still didn't resolve the issue.
[media-autobuild_suite.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7018433/media-autobuild_suite.zip)

**Comment by 1480c1** [comment]
https://github.com/notroj/neon/pull/61

**Comment by 1480c1** [comment]
fixed by using patch of pr mentioned above
