### ISSUE TITLE
ld returned 1 exit status

### ISSUE THREAD

**Issue by ENunn** [m-ab-s/media-autobuild_suite#2030]
Been having an issue with building ffmpeg.

> Likely error (tail of the failed operation logfile):
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/librist.a(contrib_contrib_cJSON_cjson_cJSON.c.obj):cJSON.c:(.text+0x3550): multiple definition of `cJSON_CreateArray'; C:/mabs/local64/lib/libvulkan.a(cJSON.c.obj):cJSON.c:(.text+0x3140): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/librist.a(contrib_contrib_cJSON_cjson_cJSON.c.obj):cJSON.c:(.text+0x35b0): multiple definition of `cJSON_CreateObject'; C:/mabs/local64/lib/libvulkan.a(cJSON.c.obj):cJSON.c:(.text+0x31a0): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/librist.a(contrib_contrib_cJSON_cjson_cJSON.c.obj):cJSON.c:(.text+0x3610): multiple definition of `cJSON_CreateIntArray'; C:/mabs/local64/lib/libvulkan.a(cJSON.c.obj):cJSON.c:(.text+0x3200): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/librist.a(contrib_contrib_cJSON_cjson_cJSON.c.obj):cJSON.c:(.text+0x3770): multiple definition of `cJSON_CreateFloatArray'; C:/mabs/local64/lib/libvulkan.a(cJSON.c.obj):cJSON.c:(.text+0x3320): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/librist.a(contrib_contrib_cJSON_cjson_cJSON.c.obj):cJSON.c:(.text+0x3940): multiple definition of `cJSON_CreateDoubleArray'; C:/mabs/local64/lib/libvulkan.a(cJSON.c.obj):cJSON.c:(.text+0x3450): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/librist.a(contrib_contrib_cJSON_cjson_cJSON.c.obj):cJSON.c:(.text+0x3b00): multiple definition of `cJSON_CreateStringArray'; C:/mabs/local64/lib/libvulkan.a(cJSON.c.obj):cJSON.c:(.text+0x3570): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/librist.a(contrib_contrib_cJSON_cjson_cJSON.c.obj):cJSON.c:(.text+0x3ca0): multiple definition of `cJSON_Duplicate'; C:/mabs/local64/lib/libvulkan.a(cJSON.c.obj):cJSON.c:(.text+0x36d0): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/librist.a(contrib_contrib_cJSON_cjson_cJSON.c.obj):cJSON.c:(.text+0x3e30): multiple definition of `cJSON_Minify'; C:/mabs/local64/lib/libvulkan.a(cJSON.c.obj):cJSON.c:(.text+0x38a0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:125: ffmpeg_g.exe] Error 1
make failed. Check C:/mabs/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
00:17:40   Creating diagnostics file...

[logs.zip](https://0x0.st/-yCi.zip) - Here's the log. Don't know what's up.

**Comment by 1480c1** [comment]
Please try deleting `build/librist-git` and rebuilding

**Comment by ENunn** [comment]
Didn't work.

[logs.zip](https://0x0.st/-t-C.zip)

**Comment by 1480c1** [comment]
Please make sure you have pulled the latest suite, should have been fixed in https://github.com/m-ab-s/media-autobuild_suite/commit/10bada151722f0d65183a2a5b13fced4e521fe34

**Comment by ENunn** [comment]
I used the latest version as of yesterday. I downloaded it again today and it still errored out.

**Comment by 1480c1** [comment]
Please delete `build/librist-git` and rerun

**Comment by 1480c1** [comment]
no response in 22 days, closing
