### ISSUE TITLE
[Question] Alternative script wizard for linux?

### ISSUE THREAD

**Issue by jvsdr** [m-ab-s/media-autobuild_suite#2032]
Hello! Thank you for build this script! I use for windows, but there is an alternative for linux? I mean, a bash script similar?

**Comment by 1480c1** [comment]
A commonly recommended one for linux would be https://github.com/rdp/ffmpeg-windows-build-helpers

**Comment by Biswa96** [comment]
This type of solution is easy to maintain and use instead of a giant script https://aur.archlinux.org/packages/mingw-w64-ffmpeg
