### ISSUE TITLE
[mingw64] [ffmpeg] libaom.a(ivfdec.c.o):ivfdec.c:(.text+0x1d6): undefined reference to `warn'

### ISSUE THREAD

**Issue by Ajaja** [m-ab-s/media-autobuild_suite#2034]
``` bash
LD      libavcodec/avcodec-59.dll
Z:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Z:/media-autobuild_suite/local64/lib/libaom.a(ivfdec.c.o):ivfdec.c:(.text+0x1d6): undefined reference to `warn'
Z:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Z:/media-autobuild_suite/local64/lib/libaom.a(ivfdec.c.o):ivfdec.c:(.text+0x22a): undefined reference to `warn'
Z:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Z:/media-autobuild_suite/local64/lib/libaom.a(ivfdec.c.o):ivfdec.c:(.text+0x26e): undefined reference to `warn'
Z:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Z:/media-autobuild_suite/local64/lib/libaom.a(ivfdec.c.o):ivfdec.c:(.text+0x28c): undefined reference to `warn'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/ffbuild/library.mak:103: libavcodec/avcodec-59.dll] Error 1
make failed. Check Z:/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-tUs.zip
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7071605/logs.zip)

**Comment by ycwan** [comment]
Same error here

14:12:30 ┌ ffmpeg git  ............................... [Recently updated]
14:12:30 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
14:12:36 ├ Compiling static FFmpeg...
14:12:37 ├ Running configure...
14:17:29 ├ Running make...
Likely error (tail of the failed operation logfile):
make: *** Waiting for unfinished jobs....
make: *** [/build/ffmpeg-git/Makefile:125: ffprobe_g.exe] Error 1
make: *** [/build/ffmpeg-git/Makefile:125: ffmpeg_g.exe] Error 1
LD      ffmpeg_g.exe
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libaom.a(ivfdec.c.o):ivfdec.c:(.text+0x1d6): undefined reference to `warn'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libaom.a(ivfdec.c.o):ivfdec.c:(.text+0x22a): undefined reference to `warn'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libaom.a(ivfdec.c.o):ivfdec.c:(.text+0x26e): undefined reference to `warn'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libaom.a(ivfdec.c.o):ivfdec.c:(.text+0x28c): undefined reference to `warn'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:125: ffmpeg_g.exe] Error 1
make failed. Check C:/MinGW-w64/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
14:23:23   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-tG6.zip
Copy and paste [logs.zip](https://0x0.st/-tG6.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/-tG6.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/7072056/ab-suite.make.log)

**Comment by GyanD** [comment]
I suspect it's due to this [commit](https://aomedia.googlesource.com/aom/+/15b3c6dd0dc94c86ecd868a0123663df17512db7) in aom.

**Comment by 1480c1** [comment]
I mentioned the wrong commit in https://github.com/m-ab-s/media-autobuild_suite/commit/1206d504b8b9d72d9f5b7b4822d4121d2a720686
