### ISSUE TITLE
rav1e Installing error

### ISSUE THREAD

**Issue by steven8274** [m-ab-s/media-autobuild_suite#2035]
The 'media-suite_compile.sh' always stopped at installing rav1e, it reported as:

11:44:38 ┌ rav1e git  ................................ [Recently updated]
11:44:38 ├ Running install-rav1e-c...
Likely error (tail of the failed operation logfile):
warning: spurious network error (1 tries remaining): failed to send request: 无法与服务器建立连接
; class=Os (2)
Error: CliError { error: Some(failed to get `aom-sys` as a dependency of package `rav1e v0.4.0 (E:\huhai\media-autobuild_suite\build\rav1e-git)`

Caused by:
    0: failed to load source for dependency `aom-sys`
    1: Unable to update registry `https://github.com/rust-lang/crates.io-index`
    2: failed to fetch `https://github.com/rust-lang/crates.io-index`
    3: failed to send request: 无法与服务器建立连接
       ; class=Os (2)), exit_code: 101 }
install-rav1e-c failed. Check E:/huhai/media-autobuild_suite/build/rav1e-git/ab-suite.install-rav1e-c.log
This is required for other packages, so this script will exit.
11:44:50   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-th0.zip
Copy and paste [logs.zip](https://0x0.st/-th0.zip) in the GitHub issue.
Make sure the suite is up-to-date before repo

Is this caused by network problem?I changed several http proxies, but the problem still exists.Here is my logs.zip:

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7074147/logs.zip)

**Comment by steven8274** [comment]
Both 'https://github.com/rust-lang/crates.io-index' and 'https://github.com/rust-lang/crates.io-index' I can access via my http proxy I'm sure.

**Comment by Ajaja** [comment]
Maybe it requires
```
[http]
proxy = "host:port"    
```
in `config.toml`?

**Comment by steven8274** [comment]
> Maybe it requires
> 
> ```
> [http]
> proxy = "host:port"    
> ```
> 
> in `config.toml`?

I've set http proxy by add 'export http_proxy=http://x.x.x.x:xxxx;export https_proxy=http://x.x.x.x:xxxx' at the head of 'media-suite_compile.sh'.

**Comment by 1480c1** [comment]
going to assume this a machine/network specific issue that the suite can't really solve, closing
