### ISSUE TITLE
vulkan-loader build error

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2037]
┌ vulkan-loader git  .................................. [Recently updated]
├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running dependencies...
├ Installing Vulkan-Headers...
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ Building Vulkan-Loader...
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -ID:/MABS-ffmpeg/build/vulkan-loader-git/loader -ID:/MABS-ffmpeg/build/vulkan-loader-git/loader/generated -ID:/MABS-ffmpeg/build/vulkan-loader-git/build-32bit/loader  /c /Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj D:/MABS-ffmpeg/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: Referensen (handle) ▒r felaktig.

[1/9] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -ID:/MABS-ffmpeg/build/vulkan-loader-git/loader -ID:/MABS-ffmpeg/build/vulkan-loader-git/loader/generated -ID:/MABS-ffmpeg/build/vulkan-loader-git/build-32bit/loader  /c /Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj D:/MABS-ffmpeg/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check D:/MABS-ffmpeg/build/vulkan-loader-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-vCF.zip

**Comment by 1480c1** [comment]
Closed in https://github.com/m-ab-s/media-autobuild_suite/commit/95bc2574271217e557842119b326f88301077e3b

**Comment by Selur** [comment]
> 09:51:28 ┌ vulkan-loader git  ........................ [Recently updated]
09:51:28 ├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
09:51:29 ├ Running dependencies...
09:51:34 ├ Installing Vulkan-Headers...
09:51:34 ├ Running uninstall...
09:51:34 ├ Running cmake...
09:51:34 ├ Running build...
09:51:34 ├ Running install...
09:51:35 ├ Building Vulkan-Loader...
09:51:35 ├ Running cmake...
09:51:38 ├ Running build...
Likely error (tail of the failed operation logfile):
  356 | static bool loader_platform_is_path_absolute(const char *path) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I:/media-autobuild_suite/build/vulkan-loader-git/loader/vk_loader_platform.h:349:13: warning: 'loader_platform_file_exists' defined but not used [-Wunused-function]
  349 | static bool loader_platform_file_exists(const char *path) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[4/6] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -II:/media-autobuild_suite/build/vulkan-loader-git/loader -II:/media-autobuild_suite/build/vulkan-loader-git/loader/generated -II:/media-autobuild_suite/build/vulkan-loader-git/build-32bit/loader  /c /Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj I:/media-autobuild_suite/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check I:/media-autobuild_suite/build/vulkan-loader-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
09:51:39   Creating diagnostics file...
>
All relevant logs have been anonymously uploaded to https://0x0.st/-Y2k.zip
Copy and paste [logs.zip](https://0x0.st/-Y2k.zip) in the GitHub issue.

seems to be the same issue (deleteing the `build\vulkan-loader-git`- folder didn't help

**Comment by jindal1979** [comment]
I am facing the exact same issue [logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7230997/logs.zip)
