### ISSUE TITLE
Request: How to reserve my modification to ffmpeg code?

### ISSUE THREAD

**Issue by steven8274** [m-ab-s/media-autobuild_suite#2039]
Since I found that there seems to be a bug in ffmpeg's code, I modified the code and run 'media-autobuild_suite.bat' again for a rebuiding of ffmpeg.But I found the code modification is reverted before ffmpeg compiling.So how can I reserve my modification?

**Comment by 1480c1** [comment]
You could use `ffmpeg_extra.sh` to reapply your changes every time you recompile, it could be as simple as
```bash
_pre_configure(){
    do_patch "/c/myffmpeg.patch"
}
```
after generating the patch file using `git diff > /c/myffmpeg.patch`
