### ISSUE TITLE
Vulkan-Loader | ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by BedrockDotPng** [m-ab-s/media-autobuild_suite#2041]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7141527/logs.zip)

**Comment by BedrockDotPng** [comment]
After updating this component the whole setup is messed up...

**Comment by BedrockDotPng** [comment]
Solution for this problem is to REMOVE the "--enable-vulkan" key from build\ffmpeg_options.txt or to wait until the faulty component ("Vulkan-Loader" in this case) gets fixed.

**Comment by Ajaja** [comment]
`
0001-loader-cross-compile-static-linking-hacks.patch(B
	Patch could not be applied with `git am`. Continuing without patching.
0003-pc-remove-CMAKE_CXX_IMPLICIT_LINK_LIBRARIES.patch(B
	Patch could not be applied with `git am`. Continuing without patching.
`
Patches need rebase. Again.

**Comment by 1480c1** [comment]
Rebased the patches, was more annoying this time since they split the linux/macOS files and windows

**Comment by 1480c1** [comment]
Closing since they are working for me
