### ISSUE TITLE
vulkan-loader - Patch could not be applied with `git am`

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2045]
x64

┌ vulkan-loader git  .................................. [Recently updated]
├ Running uninstall...
0002-loader-vulkan.pc.in-use-the-normal-prefix-and-exec_p.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running dependencies...

Looks like we could use a rebase of the patch in question.

This patch issue have been around for a few days now

**Comment by 1480c1** [comment]
Rebased the patch, but literally only the commit hashes changed though

**Comment by Barough** [comment]
This is patch issue is gone now,
