### ISSUE TITLE
ffmpeg - Patch could not be applied with `git am`

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2046]
x64

┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
0001-Add-Alternative-VapourSynth-demuxer.patch
        Patch could not be applied with `git am`. Continuing without patching.

Looks like we could use a rebase of the patch in question. Been like this for about 5-6 days

**Comment by 1480c1** [comment]
Rebased the patch, but there didn't seem to be any conflict

**Comment by Barough** [comment]
This patch issue is still around. 

Any suggestions?

**Comment by Ajaja** [comment]
Try to remove `ffmpeg-git` folder.

**Comment by 1480c1** [comment]
Feels like duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1941 which is related to https://github.com/m-ab-s/media-autobuild_suite/issues/1803

**Comment by 1480c1** [comment]
Can't tell since you didn't attach a zips.log

**Comment by Barough** [comment]
> Try to remove `ffmpeg-git` folder.

Done that multiple times and that haven't helped.


> Can't tell since you didn't attach a zips.log

There is no zips.log available since there is no crash etc.
