### ISSUE TITLE
harfbuzz failed to build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2047]
┌ harfbuzz git  ....................................... [Recently updated]
├ Running meson...
├ Running build...
Likely error (tail of the failed operation logfile):
ninja: build stopped: subcommand failed.
[1/2] Compiling C++ object src/libharfbuzz.a.p/hb-ft.cc.obj
FAILED: src/libharfbuzz.a.p/hb-ft.cc.obj
"g++.bat" "-Isrc/libharfbuzz.a.p" "-Isrc" "-I../src" "-I." "-I.." "-I/local32/include/freetype2" "-fdiagnostics-color=always" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-Wnon-virtual-dtor" "-std=c++11" "-fno-exceptions" "-fno-rtti" "-O3" "-fno-exceptions" "-fno-rtti" "-fno-threadsafe-statics" "-fvisibility-inlines-hidden" "-DHAVE_CONFIG_H" "-mthreads" "-mtune=generic" "-O2" "-pipe" "-D_FORTIFY_SOURCE=0" "-D__USE_MINGW_ANSI_STDIO=1" "-Wno-non-virtual-dtor" -MD -MQ src/libharfbuzz.a.p/hb-ft.cc.obj -MF "src/libharfbuzz.a.p/hb-ft.cc.obj.d" -o src/libharfbuzz.a.p/hb-ft.cc.obj "-c" ../src/hb-ft.cc
In file included from ../src/hb-ft.cc:34:
../src/hb-ft.h:34:10: fatal error: ft2build.h: No such file or directory
   34 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
build failed. Check D:/MABS-ffmpeg/build/harfbuzz-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-xI-.zip

**Comment by ccx004B** [comment]
It may not be of much help to the developers but I get the same issue with a 64 bit build. The logs were uploaded to  [logs.zip](https://0x0.st/-x0G.zip) .

**Comment by moob158** [comment]
Same problem here :(

**Comment by Shadow-Kill** [comment]
I also have a problem myself
https://0x0.st/-xDy.zip

**Comment by sinnoken** [comment]
Same problem
https://0x0.st/-xnX.zip

**Comment by vivazkote** [comment]
Same problem

**Comment by moob158** [comment]
work here after the last "commit" :)

**Comment by vivazkote** [comment]
yep, downloaded latest, seems harfbuz problem gone; but cleaned up _local32/64_ folders and _src_ folders

**Comment by ccx004B** [comment]
Still not working. I removed the entire directory except for the media-autobuild_suite-master.zip file and ran that again from scratch so I guess that is cleaning up everything. Got exactly the same result as Barough got. The logs are: [logs.zip](https://0x0.st/-xCj.zip). This was done after 1480c1 closed the ticket.

**Comment by 1480c1** [comment]
Did you make sure to get the latest media-autobuild_suite-master.zip?

**Comment by Barough** [comment]
Still not working here.

Copy and paste [logs.zip](https://0x0.st/-3-K.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
@Barough can you make sure to delete freetype-git and rerun? I switched it to using meson instead of autotools as it now builds fine and the resulting pkg-config file is correct

**Comment by Barough** [comment]
I'll do that in a little while. Must run out for a few now,

**Comment by Barough** [comment]
That seems to have solved it. Harfbuzz compiles fine now.

**Comment by ccx004B** [comment]
Hi,

 

Thanks for the reply. No I have to confess I used the one I downloaded a few days before. Everything else was new though. I’ll do it now though.

 

Best wishes…..

Colin

**Comment by ccx004B** [comment]
Yep that was the problem. All built and working. Thanks for your help with this.

 

Best wishes….

Colin
