### ISSUE TITLE
[mingw64] [vulkun-loader] "0001-loader-cross-compile-static-linking-hacks.patch" "CreateProcess failed: The system cannot find the file specified." "ninja: build stopped: subcommand failed."

### ISSUE THREAD

**Issue by Lishrk** [m-ab-s/media-autobuild_suite#2054]
┌ vulkan-loader git  ........................ [Recently updated]
├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running dependencies...
├ Installing Vulkan-Headers...
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ Building Vulkan-Loader...
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
  356 | static bool loader_platform_is_path_absolute(const char *path) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/repos/media-autobuild_suite/build/vulkan-loader-git/loader/vk_loader_platform.h:349:13: warning: 'loader_platform_file_exists' defined but not used [-Wunused-function]
  349 | static bool loader_platform_file_exists(const char *path) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[4/5] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -IC:/repos/media-autobuild_suite/build/vulkan-loader-git/loader -IC:/repos/media-autobuild_suite/build/vulkan-loader-git/loader/generated -IC:/repos/media-autobuild_suite/build/vulkan-loader-git/build-64bit/loader  /c /Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj C:/repos/media-autobuild_suite/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check C:/repos/media-autobuild_suite/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
   Creating diagnostics file...

I set mpv=2 in media-autobuild_suite.ini

[logs.zip](https://0x0.st/-YLR.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/7231431/ab-suite.build.log)

**Comment by 1480c1** [comment]
rebased the patches, try again

**Comment by Lishrk** [comment]
Sorry. I'm a beginner.
I searched for "rebased" but didn't know how to command it.
If you like, please tell me the detailed method. （google translate）

**Comment by 1480c1** [comment]
I rebased, so you just need to rerun media-autobuild_suite.bat

**Comment by Lishrk** [comment]
Thanks! It's working!
arigato!
