### ISSUE TITLE
mplayer/mencoder incompatibility with dav1d's new threading parameters

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2072]
The AV1 decoder dav1d now uses DAV1D_MAX_TILE_THREADS and DAV1D_MAX_FRAME_THREADS instead of a common DAV1D_MAX_THREADS, so compiling mplayer fails.

```
libavcodec/libdav1d.c: At top level:
libavcodec/libdav1d.c:462:94: error: 'DAV1D_MAX_TILE_THREADS' undeclared here (not in a function); did you mean 'DAV1D_MAX_THREADS'?
  462 |     { "tilethreads", "Tile threads", OFFSET(tile_threads), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, DAV1D_MAX_TILE_THREADS, VD },
      |                                                                                              ^~~~~~~~~~~~~~~~~~~~~~
      |                                                                                              DAV1D_MAX_THREADS
libavcodec/libdav1d.c:463:97: error: 'DAV1D_MAX_FRAME_THREADS' undeclared here (not in a function); did you mean 'DAV1D_MAX_THREADS'?
  463 |     { "framethreads", "Frame threads", OFFSET(frame_threads), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, DAV1D_MAX_FRAME_THREADS, VD },
      |                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                 DAV1D_MAX_THREADS
make[1]: *** [ffbuild/common.mak:67: libavcodec/libdav1d.o] Error 1
```

[mplayerhq ticket 2381](https://trac.mplayerhq.hu/ticket/2381)

**beastd** replied:
>  AFAICT the problem is that your libavcodec version is too low for your libdav1d version.
>
> For your libdav1d version, at least libavcodec from FFmpeg 4.4.1 is required.
>
> Regarding threaded decoding with libdav1d, the current development version of FFmpeg and the upcoming 4.4.2 will be better because it contains a fix and improvements regarding libdav1d threading.
>
> Hope that helps and if possible report back if compiling with newer FFmpeg fixes the build.

**Comment by 1480c1** [comment]
From our code, it pulls ffmpeg either by a local `build/ffmpeg-git` clone, a git clone from `https://git.ffmpeg.org/ffmpeg.git`, or if it was cloned previously, it updates that clone, so it would essentially always use ffmpeg's master branch

**Comment by 1480c1** [comment]
```c
    { "tilethreads", "Tile threads", OFFSET(tile_threads), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, DAV1D_MAX_TILE_THREADS, VD | AV_OPT_FLAG_DEPRECATED },
    { "framethreads", "Frame threads", OFFSET(frame_threads), AV_OPT_TYPE_INT, { .i64 = 0 }, 0, DAV1D_MAX_FRAME_THREADS, VD | AV_OPT_FLAG_DEPRECATED },
```
it seems the master branch has something newer, can you try deleting the `ffmpeg` folder under mplayer-svn and see if it passes? If it does, I guess it was probably failing to update the ffmpeg folder

**Comment by LigH-de** [comment]
Dammit 👿 - whenever there is an issue to test, another dependency before it breaks. This time: SDL_hidapi.h not found
