### ISSUE TITLE
jpeg-xl-git build error 

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#2080]
jpeg-xl-git build error

libbrotlienc.a(encode.c.obj):encode.c:(.text+0x7c8): undefined reference to `_kBrotliContextLookupTable'
libbrotlienc.a(encode.c.obj):encode.c:(.text+0xd31): undefined reference to `_kBrotliContextLookupTable'
libbrotlienc.a(encode.c.obj):encode.c:(.text+0xd44): undefined reference to `_kBrotliContextLookupTable'
libbrotlienc.a(encode.c.obj):encode.c:(.text+0x228e): undefined reference to `_kBrotliContextLookupTable'
libbrotlienc.a(encode.c.obj):encode.c:(.text+0x582b): undefined reference to `_kBrotliContextLookupTable'
libbrotlienc.a(encoder_dict.c.obj):encoder_dict.c:(.text+0x42): undefined reference to `BrotliGetDictionary'
libbrotlienc.a(encoder_dict.c.obj):encoder_dict.c:(.text+0x49): undefined reference to `BrotliGetTransforms'
libbrotlienc.a(memory.c.obj):memory.c:(.text+0x31): undefined reference to `BrotliDefaultFreeFunc'
libbrotlienc.a(memory.c.obj):memory.c:(.text+0x36): undefined reference to `BrotliDefaultAllocFunc'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x419): undefined reference to `_kBrotliPrefixCodeRanges'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x431): undefined reference to `_kBrotliPrefixCodeRanges'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x544): undefined reference to `_kBrotliPrefixCodeRanges'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x1fb9): undefined reference to `_kBrotliPrefixCodeRanges'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x2281): undefined reference to `_kBrotliPrefixCodeRanges'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x229d): more undefined references to `_kBrotliPrefixCodeRanges' follow
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x3147): undefined reference to `_kBrotliContextLookupTable'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x3b59): undefined reference to `_kBrotliPrefixCodeRanges'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x3b6e): undefined reference to `_kBrotliPrefixCodeRanges'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x3f84): undefined reference to `_kBrotliPrefixCodeRanges'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x4111): undefined reference to `_kBrotliPrefixCodeRanges'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x4134): undefined reference to `_kBrotliPrefixCodeRanges'
libbrotlienc.a(brotli_bit_stream.c.obj):brotli_bit_stream.c:(.text+0x42fb): more undefined references to `_kBrotliPrefixCodeRanges' follow
libbrotlienc.a(histogram.c.obj):histogram.c:(.text+0x192): undefined reference to `_kBrotliContextLookupTable'
libbrotlienc.a(histogram.c.obj):histogram.c:(.text+0x199): undefined reference to `_kBrotliContextLookupTable'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7638579/logs.zip)

**Comment by dolpsdw** [comment]
It happens on both clang and gcc.

**Comment by dolpsdw** [comment]
Edit media-autobuild_suite\build line 1111 with as temporal fix
if [[ $jpegxl = y ]] && do_vcs "https://gitlab.com/wg1/jpeg-xl.git#commit=a205468bc5d3a353fb15dae2398a101dff52f2d3"; then
