### ISSUE TITLE
mingw64 - liblsmash repo failure

### ISSUE THREAD

**Issue by slyfox1186** [m-ab-s/media-autobuild_suite#2083]
```
22:11:32   Running git update for x264...
22:11:32 ┌ x264 git  ................................. [Recently updated]
22:11:33 liblsmash git  ................................. [Already built]
22:11:33 ├ Running configure...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
../configure --host=x86_64-w64-mingw32 --prefix=/local64 --bindir=/local64/bin-video --disable-lavf --disable-ffms --enable-static --bit-depth=all
../configure: line 1041: "C:\Program: No such file or directory
../configure: line 1044: "C:\Program: No such file or directory
endian test failed
configure failed. Check J:/MAB/build/x264-git/build-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
22:11:36   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-FmR.zip
Copy and paste [logs.zip](https://0x0.st/-FmR.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```
https://0x0.st/-FmR.zip

**Comment by Biswa96** [comment]
The full path of current working directory may contain spaces.

**Comment by slyfox1186** [comment]
Biswa96: This is the full path to the library `J:\MAB\build\liblsmash-git`

No Spaces.... I see it mentiones "C:\Program " not being found. How do I modify the code to fix this? Any ideas?

**Comment by 1480c1** [comment]
Based on this https://code.videolan.org/videolan/x264/-/blob/master/configure#L1041, It seems the variable that's being expanded is `STRINGS`, which I only see being set https://code.videolan.org/videolan/x264/-/blob/master/configure#L559, but as we don't pass any `--cross-prefix`, that should only evaluate to `strings`, unless you have some other environment variable called `STRINGS`

**Comment by slyfox1186** [comment]
I did have a env variable names STRINGS. I have removed it. I will update in a moment.

**Comment by slyfox1186** [comment]
Yep you were right on the money. It was the env variable in windows `STRINGS`. The repo has now updated as desired. Thank you very much for the help.
