### ISSUE TITLE
 fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by jriker1** [m-ab-s/media-autobuild_suite#2084]
Will assume everything or my attempt is built into the zip file.

https://0x0.st/-Fj9.zip

Didn't get to far I don't think:

19:19:27 ├ Running rust.build...
Likely error (tail of the failed operation logfile):
  --- stderr
  fatal: not a git repository (or any of the parent directories): .git

  error occurred: Command "ccache" "gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-mthreads" "-mtune=generic" "-O2" "-pipe" "-I" "pcre2/src" "-I" "C:\\temp\\ffmpeg_build\\build\\ripgrep-git\\target\\x86_64-pc-windows-gnu\\release\\build\\pcre2-sys-ce6e025363e19b94\\out\\include" "-DPCRE2_CODE_UNIT_WIDTH=8" "-DHAVE_STDLIB_H=1" "-DHAVE_MEMMOVE=1" "-DHEAP_LIMIT=20000000" "-DLINK_SIZE=2" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_DEPTH=10000000" "-DMAX_NAME_COUNT=10000" "-DMAX_NAME_SIZE=32" "-DNEWLINE_DEFAULT=2" "-DPARENS_NEST_LIMIT=250" "-DPCRE2_STATIC=1" "-DSTDC_HEADERS=1" "-DSUPPORT_PCRE2_8=1" "-DSUPPORT_UNICODE=1" "-DHAVE_WINDOWS_H=1" "-DSUPPORT_JIT=1" "-o" "C:\\temp\\ffmpeg_build\\build\\ripgrep-git\\target\\x86_64-pc-windows-gnu\\release\\build\\pcre2-sys-ce6e025363e19b94\\out\\src\\pcre2_chartables.o" "-c" "C:\\temp\\ffmpeg_build\\build\\ripgrep-git\\target\\x86_64-pc-windows-gnu\\release\\build\\pcre2-sys-ce6e025363e19b94\\out\\src\\pcre2_chartables.c" with args "gcc" did not execute successfully (status code exit code: 1).

warning: build failed, waiting for other jobs to finish...
warning: `ignore` (lib) generated 2 warnings
error: build failed
rust.build failed. Check C:/temp/ffmpeg_build/build/ripgrep-git/ab-suite.rust.build.log
This is required for other packages, so this script will exit.
19:21:09   Creating diagnostics file...

**Comment by jriker1** [comment]
Note I tried deleting C:\temp\ffmpeg_build\msys64\opt\cargo folder and running again that I saw for a similar issue posted before but didn't help.

**Comment by 1480c1** [comment]
Seems like it's related to https://github.com/msys2/MINGW-packages/issues/10295 based on looking at the logs

**Comment by 1480c1** [comment]
upstream seems to be fixed, can you try recompiling?

**Comment by 1480c1** [comment]
no response since last year, closing
