### ISSUE TITLE
Request: [Description]

### ISSUE THREAD

**Issue by slyfox1186** [m-ab-s/media-autobuild_suite#2085]
I pre-compiled a full build (max packages) of MAB with CUDA's libnpp enabled so you must have CUDA-SDK installed. I have uploaded a highly compressed 7-Zip file to my personal Google Drive.

This includes all repos not just any exe files of interest. See below for the DL link.

Is this something you guys would appreciate me doing from time to time?

File Size = 4.7 GB
You must have 7-Zip installed to extract the files.
[MAB_12.11.2021.7z](https://drive.google.com/file/d/14XFMukz4OII9-7cF_Ozyf2JoFTJt9dk0/view?usp=sharing)

**Comment by LigH-de** [comment]
I doubt this will be generally appreciated. Depending on the choice of licenses, you may e.g. be able to build ffmpeg including fdk-aac, which is not allowed to be distributed in binary form. This project legally provides the script to enable people to build on their own what may or may not be legally available as results.

**Comment by slyfox1186** [comment]
OK thanks for letting me know!
