### ISSUE TITLE
mpv has changed its shaderc checks

### ISSUE THREAD

**Issue by rld243** [m-ab-s/media-autobuild_suite#2088]
See https://github.com/mpv-player/mpv/pull/9617

The suite doesn't raise any errors during compiling but mpv configure can't detect shaderc anymore silently disabling d3d11 vo as well.

[ab-suite.configure.log](https://github.com/m-ab-s/media-autobuild_suite/files/7747002/ab-suite.configure.log)

**Comment by 1480c1** [comment]
Darn, that makes it harder a bit, we can't easily just ninja install shaderc since it installs a bunch of other stuff from its submodules, which also complicates some stuff since we already have a lot of the submodules already installed

**Comment by 1480c1** [comment]
Can you try this commit https://github.com/1480c1/media-autobuild_suite/commit/86ddfe431231fdb5fa6e480e87c4cfda94b8f2ce ? My build is currently running as well

**Comment by rld243** [comment]
@1480c1 
Just tried it and it looks like it works. mpv now detects shaderc and compiles just fine.
