### ISSUE TITLE
Script stuck at "Running git clone for fontconfig..."

### ISSUE THREAD

**Issue by FunctionDJ** [m-ab-s/media-autobuild_suite#2091]
My goal is to compile ffmpeg with libfdk_aac.
If i close the script when it hangs and when i start it again, it gets hung at the same step.
I assume that because the script hangs and doesn't throw an error, no logs.zip file is being generated, so i zipped all files without directories inside the /build directory which includes the ffmpeg config and what the console has printed so far.

[build.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7780005/zip.zip)

**Comment by GyanD** [comment]
it gets stuck on updating the fontconfig repo.

Change line 254 of `media-suite_compile.sh` in build folder

from

`do_vcs "https://gitlab.freedesktop.org/fontconfig/fontconfig.git#tag=LATEST"; then`

to

`do_vcs "https://github.com/freedesktop/fontconfig.git#tag=LATEST"; then`

**Comment by FunctionDJ** [comment]
@GyanD It continues now! Thanks a lot. How come the Github repo works but the Gitlab one doesn't?

**Comment by Biswa96** [comment]
But the official wiki suggests the GitLab one https://www.freedesktop.org/wiki/Software/fontconfig/

**Comment by LigH-de** [comment]
Please re-open. There is no solution in the MABS sources yet. I discovered similar issues.

After compiling `freetype`, the progress halts. Checking the processes, I see the following more or less inactive calls in ProcessExplorer:

  * `git.exe remote set-head -a origin`
  * `git.exe remote-https origin https://gitlab.freedesktop.org/fontconfig/fontconfig.git`
  * `git-remote-https.exe origin https://gitlab.freedesktop.org/fontconfig/fontconfig.git` (minimal CPU activity)
  
Searching the web for `git remote https hangs` I find a few hints that this may happen in other cases, not related to fontconfig though, more related to `push` calls (which is not the case here). Some sources also report hangs on `git clone` calls from gitlab.

Killing the process of `git-remote-https.exe` continues the progress, the other two calls get closed too. This may be a bad workaround, I have no clue about side effects.

**Comment by 1480c1** [comment]
Haven't had any issues recently with fontconfig, so going to close for now
