### ISSUE TITLE
libxml2 git seems to be down (windows 10, 64bit build)

### ISSUE THREAD

**Issue by N0N0** [m-ab-s/media-autobuild_suite#2092]
git clone of libxml2 fails under Windows 10 even though the repository is online.

I already verified that the repository under https://gitlab.gnome.org/GNOME/libxml2.git does exist and is reachable. I also tried to replace it with the alternative read only mirror under https://github.com/GNOME/libxml2 but that didn't change the behavior of the media autobuild suite.

``` bash
23:37:21 Warning: We will not accept any issues lacking any form of logs or logs.zip!
23:37:21
        Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
23:37:46
        Starting 64bit compilation of global tools
23:37:46 ├ Running rustup_update...
23:37:47 ├ Running set_default_toolchain...
23:37:47   Running git clone for libxml2...
libxml2 git seems to be down
Try again later or <Enter> to continue
if you're sure nothing depends on it.
23:37:52 ├ Running autogen...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
./autogen.sh
/build/media-suite_helper.sh: line 1435: ./autogen.sh: No such file or directory
autogen failed. Check G:/media-autobuild_suite-master/build/ab-suite.autogen.log
This is required for other packages, so this script will exit.
23:37:52   Creating diagnostics file...
/build/media-suite_helper.sh: line 1404: /usr/bin/curl: No such file or directory

Attach G:\media-autobuild_suite-master\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[```](url)
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7794809/logs.zip)

**Comment by 1480c1** [comment]
It seems you might have some other issues as it even mentions `/build/media-suite_helper.sh: line 1404: /usr/bin/curl: No such file or directory`, you could try removing the msys64 directory and see if it will repull msys2 successfully

**Comment by N0N0** [comment]
Thanks, I didn't saw that line in the first place.
Will try your suggestion, additionally I checked curl and it really was not on the search location but it is already installed on my system and is available via PATH.

**Comment by N0N0** [comment]
A first attempt to delete msys2 and restarting the script ended with an error at the rust installation.
msys2/usr/bin/curl.exe was present.
Another rerun of the script then ended with another erorr on a "git clone" and this time the msys2/usr/bin/curl.exe was gone again - it seems that it got deleted by the rerun of the media-autobuild_suite.bat.

However, I deleted msys2 directory again and this time i disabled my Avast Antivirus Life Scanner and for now the installation of the global 64bit tools is running longer than it ever did before - keeping my fingers crossed that just that was the root cause of these strange problems...

**Comment by N0N0** [comment]
I can now confirm that Avast Life Scanner is making problems with git clones in the first place and on every rerun of media-autobuild_suite.bat after a failure happened, curl.exe gets deleted - leading to start this Issue/Ticket.

Thanks and wishing everyobdy a good start into the new year :)

**Comment by 1480c1** [comment]
Yeah, annoyingly antivirus often gets into the way of compilation, previously Microsoft Defender even deleted gcc after marking it as an "obfuscator"

Going to assume this can be closed
