### ISSUE TITLE
Error when running git update for mpv

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2095]
01:50:00   Running git update for mpv...
01:50:48 ┌ mpv git  ..................................... [Updates found]
01:50:50 ├ Running bootstrap...
01:51:00 ├ Running configure...
01:51:42 ├ Running build...
Likely error (tail of the failed operation logfile):
      |     ^~~~~~~~~~~~~~
In file included from C:/MinGW-w64/local64/include/libavcodec/avcodec.h:45,
                 from ../video/image_writer.c:22:
C:/MinGW-w64/local64/include/libavcodec/packet.h:506:6: note: declared here
  506 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
build failed. Check C:/MinGW-w64/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
01:52:58   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/os_5.zip
Copy and paste [logs.zip](https://0x0.st/os_5.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/os_5.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/7796837/ab-suite.build.log)

**Comment by 1480c1** [comment]
Seems to be an upstream mingw-w64 issue, conflict was introduced in https://github.com/mirror/mingw-w64/commit/09def642bf5e8a78195791257ff53fd920c549d1 to ks.h, the definition already existed in ksmedia.h

it was already reported upstream at https://sourceforge.net/p/mingw-w64/discussion/723797/thread/c7085ad79b/

**Comment by Biswa96** [comment]
A fix has been proposed in upstream mingw-w64, see here https://sourceforge.net/p/mingw-w64/mailman/message/37410279/. Just rebuild mingw-w64-headers and mingw-w64-crt (optional) with those two fixes. Then rebuild mpv.

**Comment by Biswa96** [comment]
The fixed is applied in upstream mingw-w64 in this commit https://sourceforge.net/p/mingw-w64/mingw-w64/ci/5be8fcd83d7e8e6859cb3f78ea1850aa5bfc067f/.

**Comment by ycwan** [comment]
I deleted build/mpv-git folder and run MABS. Now the error is different as shown in below output from MABS

20:44:30   Running git clone for mpv...
20:44:52 ┌ mpv git  .................................. [Recently updated]
20:44:53 ├ Running bootstrap...
20:44:59 ├ Running configure...
20:45:19 ├ Running build...
Likely error (tail of the failed operation logfile):
      |     ^
In file included from C:/MinGW-w64/local64/include/libplacebo/renderer.h:25,
                 from ../video/out/vo_gpu_next.c:20:
C:/MinGW-w64/local64/include/libplacebo/shaders/colorspace.h:283:10: note: declared here
  283 |     bool gamut_clipping PL_DEPRECATED;  // replaced by PL_GAMUT_DESATURATE
      |          ^~~~~~~~~~~~~~

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
build failed. Check C:/MinGW-w64/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
20:45:42   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ozQD.zip
Copy and paste [logs.zip](https://0x0.st/ozQD.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/7814988/ab-suite.build.log)

**Comment by 1480c1** [comment]
```c
In file included from ../audio/out/ao_wasapi_utils.c:24:
C:/MinGW-w64/msys64/mingw64/x86_64-w64-mingw32/include/ksmedia.h:181:58: error: redefinition of 'KSCATEGORY_MICROPHONE_ARRAY_PROCESSOR'
  181 | DEFINE_GUIDSTRUCT("830a44f2-a32d-476b-be97-42845673b35a",KSCATEGORY_MICROPHONE_ARRAY_PROCESSOR);
      |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/MinGW-w64/msys64/mingw64/x86_64-w64-mingw32/include/ks.h:666:1: note: previous definition of 'KSCATEGORY_MICROPHONE_ARRAY_PROCESSOR' with type 'GUID'
  666 | DEFINE_GUIDSTRUCT("830A44F2-A32D-476B-BE97-42845673B35A",KSCATEGORY_MICROPHONE_ARRAY_PROCESSOR);
      | ^~~~~~~~~~~~~~~~~
C:/MinGW-w64/msys64/mingw64/x86_64-w64-mingw32/include/ksmedia.h:406:58: error: redefinition of 'KSCATEGORY_AUDIO'
  406 | DEFINE_GUIDSTRUCT("6994AD04-93EF-11D0-A3CC-00A0C9223196",KSCATEGORY_AUDIO);
      |                                                          ^~~~~~~~~~~~~~~~
C:/MinGW-w64/msys64/mingw64/x86_64-w64-mingw32/include/ks.h:581:1: note: previous definition of 'KSCATEGORY_AUDIO' with type 'GUID'
  581 | DEFINE_GUIDSTRUCT("6994AD04-93EF-11D0-A3CC-00A0C9223196",KSCATEGORY_AUDIO);
      | ^~~~~~~~~~~~~~~~~
C:/MinGW-w64/msys64/mingw64/x86_64-w64-mingw32/include/ksmedia.h:411:58: error: redefinition of 'KSCATEGORY_VIDEO'
  411 | DEFINE_GUIDSTRUCT("6994AD05-93EF-11D0-A3CC-00A0C9223196",KSCATEGORY_VIDEO);
      |                                                          ^~~~~~~~~~~~~~~~
C:/MinGW-w64/msys64/mingw64/x86_64-w64-mingw32/include/ks.h:746:1: note: previous definition of 'KSCATEGORY_VIDEO' with type 'GUID'
  746 | DEFINE_GUIDSTRUCT("6994AD05-93EF-11D0-A3CC-00A0C9223196",KSCATEGORY_VIDEO);
      | ^~~~~~~~~~~~~~~~~
C:/MinGW-w64/msys64/mingw64/x86_64-w64-mingw32/include/ksmedia.h:416:58: error: redefinition of 'KSCATEGORY_TEXT'
  416 | DEFINE_GUIDSTRUCT("6994AD06-93EF-11D0-A3CC-00A0C9223196",KSCATEGORY_TEXT);
      |                                                          ^~~~~~~~~~~~~~~
```
it's still there, it hasn't been updated on msys2's side just yet

**Comment by 1480c1** [comment]
seems to be fixed for me, closing
