### ISSUE TITLE
[mingw64] [libjxl] failed to link with gflags

### ISSUE THREAD

**Issue by Doofussy2** [m-ab-s/media-autobuild_suite#2100]
Failed build with cmake package.

```
Likely error (tail of the failed operation logfile):
  but not all the files it references.

Call Stack (most recent call first):
  G:/mpv_building_tools/msys64/mingw64/lib/cmake/gflags/gflags-config.cmake:17 (include)
  third_party/CMakeLists.txt:168 (find_package)
```
I am building 64bit on Windows 10. I initially was getting this error, and tried to resolve it. I tried replacing the `gflags` with the latest. On that failing, I rebuilt the entire suite. The error persists.

[logs.zip](https://0x0.st/oieV.zip)

**Comment by 1480c1** [comment]
Seems it occurred when msys2 added the shared library to the package, resulting in the cmake file referring to the dll import library, that we locally move so gcc doesn't find it, building locally to see what would be the best way to move forward.

**Comment by LigH-de** [comment]
Excerpt from libjxl:
```
CMake Error at G:/MABS/msys64/mingw32/lib/cmake/gflags/gflags-nonamespace-targets.cmake:107 (message):
  The imported target "gflags_shared" references the file

     "G:/MABS/msys64/mingw32/lib/libgflags.dll.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "G:/MABS/msys64/mingw32/lib/cmake/gflags/gflags-nonamespace-targets.cmake"

  but not all the files it references.
```

The file `G:/MABS/msys64/mingw32/lib/libgflags.dll.a` does not exit.
A file  `G:/MABS/msys64/mingw32/lib/libgflags.dll.a.dyn` does exit instead.

**Comment by bombenbodo** [comment]
I‘m getting the same error as above, but libgflags.dll.a actually exists in /msys64/mingw32/lib/

**Comment by LigH-de** [comment]
Did you ever build it more than 3 weeks ago? Maybe it's an older remnant. I set up a completely new suite before I got this error in my case.

**Comment by bombenbodo** [comment]
Yes, my last build/update was back in september. 

Also strange is:
```
libjxl git  ......................................... [Recently updated]
├ Uninstalling asciidoc-py3-git... failed
```

**Comment by LigH-de** [comment]
This attempt fails when it has been removed successfully before. May be ignored.

**Comment by bombenbodo** [comment]
I temporarily set jpegxl=2 in /build/media-autobuild_suite.ini to skip `libjxl` compilation.

**Comment by 1480c1** [comment]
I am trying to fix this specific issue, but I keep on running into other linking issues with libjxl, so it will take even longer till I can decide what I should do about it.

**Comment by Doofussy2** [comment]
I haven't tried building without that library. If I eliminate that library, will it build successfully?

**Comment by 1480c1** [comment]
what are you aiming to build?
If it's ffmpeg, then you can remove libjxl from building, as libjxl currently is linked to nothing else

**Comment by Doofussy2** [comment]
> what are you aiming to build? If it's ffmpeg, then you can remove libjxl from building, as libjxl currently is linked to nothing else

Yes, ffmpeg, also mpv

**Comment by 1480c1** [comment]
then, you can just disable it, it only provides cjxl.exe and djxl.exe for now

**Comment by Doofussy2** [comment]
> then, you can just disable it, it only provides cjxl.exe and djxl.exe for now

Great, thanks. I'll try it later, and see what happens.

**Comment by LigH-de** [comment]
> I am trying to fix this specific issue, but I keep on running into other linking issues with libjxl, so it will take even longer till I can decide what I should do about it.

Thank you for your efforts, much appreciated. I called Jamaika in the doom9 forums, hoping for a little additional experience building JPEG-XL.

**Comment by Jamaika1** [comment]
https://github.com/libjxl/libjxl/commit/9f544641ec83f6abd9da598bdd08178ee8a003e0
https://forum.doom9.org/showthread.php?p=1961529#post1961529
