### ISSUE TITLE
Planning to drop redshift by 1/28

### ISSUE THREAD

**Issue by 1480c1** [m-ab-s/media-autobuild_suite#2103]
Currently, doesn't seem like redshift works on Windows 10 and above, so it's currently pretty useless, plus Windows 10 comes with a built-in redshift-like color shift option, no clue about 8.1, planning to drop by 1/28 unless someone really wants to keep it for some reason.

https://github.com/jonls/redshift/issues/741

**Comment by wiiaboo** [comment]
Sure. I've replaced it by Windows built-in replacement since a while ago. Some Windows update broke it and they probably don't care much about Windows support, so it's fine to remove it.

**Comment by 1480c1** [comment]
Removed in https://github.com/m-ab-s/media-autobuild_suite/commit/96a32a62eb968b6ddfcf3d9cf6b1a7a7d19f5eb7
