### ISSUE TITLE
Request: [don't do check pacman packages everytime]

### ISSUE THREAD

**Issue by hamwong** [m-ab-s/media-autobuild_suite#2111]
Can script save a success output when 1st run (update pacman and checking pacman) then it will bypass check within 24/12/6/2/1 hrs? it takes very long time each time and if I got error during compile and need to restart or I need to build difference package, this would save lot of time.

**Comment by 1480c1** [comment]
It should be that pacman would query mirror.msys2.org, and it should redirect you to the closest, geographically, mirror

can you try editing msys64/etc/pacman.d/mirrorlist.mingw and move the mirror that is closest to you to the top of the file?

**Comment by GyanD** [comment]
It's not just a matter of download speed. An upgrade can introduce a change in the toolchain which leads to a failed build. Some time back, texinfo introduced a change which broke docs compilation, and I had to downgrade texinfo till we patched ffmpeg.

**Comment by hamwong** [comment]
I am not compliant about download speed, I just propose that once an update have been done on mintty, it would allow user to define bypass check within custom period (max 24 hrs), so if I run script again in a very short moment later, as it have been updated in maybe 1 hour ago, it will bypass update check on mintty and directly jump to ffmpeg part

**Comment by Biswa96** [comment]
> An upgrade can introduce a change in the toolchain which leads to a failed build.

An upgrade can introduce a change in the toolchain which can also lead to a fixed build. Feel free to report the issue in [MINGW-packages](https://github.com/msys2/MINGW-packages) repository as soon as possible 😊
