### ISSUE TITLE
Frei0r error while compiling

### ISSUE THREAD

**Issue by somogpt1** [m-ab-s/media-autobuild_suite#2113]
Suite is constantly failing to compile due to some Frei0r error.
Does anyone is getting that error?
Any clue?
Thanks in advanced.

log:
[95m02:19:49(B[m   Running git clone for dlfcn-win32...
[95m02:19:52(B[m [1m┌ dlfcn-win32 git (B[m .......................... [[93mRecently updated(B[m]
[95m02:19:53(B[m [1m├(B[m Running cmake...
[95m02:19:54(B[m [1m├(B[m Running build...
[95m02:19:55(B[m [1m├(B[m Running install...
[95m02:19:55(B[m [1m├(B[m Stripping...
[95m02:19:55(B[m [1m└ dlfcn-win32-git (B[m ................................... [[94mUpdated(B[m]
[95m02:19:56(B[m   Running git clone for frei0r...
[95m02:20:00(B[m [1m┌ frei0r git (B[m ............................... [[93mRecently updated(B[m]
[95m02:20:01(B[m [1m├(B[m Installing gavl... (B[mdone
[95m02:20:07(B[m [1m├(B[m Running cmake...
[95m02:20:10(B[m [1m├(B[m Running build...
[95m02:20:25(B[m [1m├(B[m Running install...
[95m02:20:25(B[m [1m└ frei0r-git (B[m ........................................ [[94mUpdated(B[m]
[95m02:20:26(B[m   Running git clone for include...
include git seems to be down
Try again later or <Enter> to continue
[?2004h[?2004l
[?2004h[?2004l
if you're sure nothing depends on it.
[95m10:18:51(B[m [1m├(B[m Running install...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
make -j8 install PREFIX=/local64
make: *** No rule to make target 'install'.  Stop.
make: *** No rule to make target 'install'.  Stop.
[31minstall failed. Check C:/autobuild/build/ab-suite.install.log(B[m
[31mThis is required for other packages, so this script will exit.(B[m
[95m10:18:51(B[m   Creating diagnostics file...

[32mAll relevant logs have been anonymously uploaded to https://0x0.st/oHQ3.zip
[32mCopy and paste [31m[logs.zip](https://0x0.st/oHQ3.zip)[32m in the GitHub issue.(B[m
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
[?2004h[?2004l
[?2004h[?2004l
Try running the build again at a later time.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7965746/logs.zip)

**Comment by 1480c1** [comment]
seems either the server stopped responding for some reason, or your internet is down, could you try again and see if it fails to connect again?

**Comment by soliveira82** [comment]
I've been trying several times since yesterday, even with different
computers without any luck.
All attempts to build stop on Frei0r Cairo as stated by the logs...
Does anyone tried this lately? Or is able to replicate the behaviour?
Thanks.


A domingo, 30/01/2022, 17:36, Christopher Degawa ***@***.***>
escreveu:

**Comment by 1480c1** [comment]
It seems the issue resides in the changes done in media-suite_compile.sh,
```bash
do_vcs "https://github.com/somogpt1/decklink-headers/tree/main/include"; then
```
that is not a valid git url, you should use
```bash
do_vcs "https://github.com/somogpt1/decklink-headers.git"; then
```

git does not allow you to selectively clone a subdirectory of a repo

**Comment by 1480c1** [comment]
no response in 8 days, closing

**Comment by somogpt1** [comment]
Hey Christopher,

I'm sorry for the late reply on this.
Thank you very much for your help.
The problem was exaclty what you've said. My fault in fact.
Stay safe.
Thanks.




A segunda, 7/02/2022, 19:13, Christopher Degawa ***@***.***>
escreveu:
