### ISSUE TITLE
mpv not building libplacebo with d3d11 support

### ISSUE THREAD

**Issue by Doofussy2** [m-ab-s/media-autobuild_suite#2115]
This is more of a question.

mpv just added d3d11 support for libplacebo (gpu-next). Here's the commit https://github.com/mpv-player/mpv/commit/053f10003ca0e2df354d959cecd7e83809b678b4

But when building, it isn't added.

```
[   0.006][v][cplayer] mpv 0.34.0-174-g67a2b2852c Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[   0.007][v][cplayer]  built on Wed Feb  2 18:31:11 PST 2022
[   0.007][v][cplayer] FFmpeg library versions:
[   0.007][v][cplayer]    libavutil       57.19.100
[   0.007][v][cplayer]    libavcodec      59.20.100
[   0.007][v][cplayer]    libavformat     59.17.101
[   0.007][v][cplayer]    libswscale      6.5.100
[   0.007][v][cplayer]    libavfilter     8.26.101
[   0.007][v][cplayer]    libswresample   4.4.100
[   0.007][v][cplayer] FFmpeg version: N-105449-gaf40447115-g2e82c61055+3

[   0.298][v][vo/gpu-next/d3d11] Using DXGI 1.2+
[   0.298][v][vo/gpu-next/d3d11] Queried output: \\.\DISPLAY1, 3840x2160 @ 12 bits, colorspace: RGB_FULL_G2084_NONE_P2020 (12)
[   0.298][v][vo/gpu-next/d3d11] Selected swapchain format R10G10B10A2_UNORM (24), attempting to utilize it.
[   0.299][v][vo/gpu-next/d3d11] Selected swapchain color space RGB_FULL_G2084_NONE_P2020 (12), attempting to utilize it.
[   0.299][v][vo/gpu-next/d3d11] Swapchain capabilities for color space RGB_FULL_G2084_NONE_P2020 (12): normal: yes, overlay: yes
[   0.299][v][vo/gpu-next/d3d11] Swapchain successfully configured to color space RGB_FULL_G2084_NONE_P2020 (12)!
[   0.299][v][vo/gpu-next/d3d11] Using flip-model presentation
[   0.299][v][vo/gpu-next] Initialized libplacebo v4.192.0-15-g9a10224 (API v192)
[   0.299][e][vo/gpu-next] libplacebo was built without D3D11 support.
```

And playback fails.

I have a build that someone else made (with a different suite), and it works correctly.

The question is why isn't it building, completely?

[compile.log](https://github.com/m-ab-s/media-autobuild_suite/files/7991767/compile.log)

**Comment by Biswa96** [comment]
Wondering if this can enable d3d11 in libplacebo?

```diff
diff --git a/build/media-suite_compile.sh b/build/media-suite_compile.sh
index 22d6d85..3f0a172 100644
--- a/build/media-suite_compile.sh
+++ b/build/media-suite_compile.sh
@@ -1862,7 +1862,7 @@ if { { [[ $mpv != n ]]  && ! mpv_disabled libplacebo; } ||
     do_patch "https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/libplacebo/0001-meson-use-shaderc_combined.patch" am
     do_pacman_install python-mako
     do_uninstall "${_check[@]}"
-    do_mesoninstall -Dvulkan-registry="$LOCALDESTDIR/share/vulkan/registry/vk.xml" -Ddemos=false
+    do_mesoninstall -Dvulkan-registry="$LOCALDESTDIR/share/vulkan/registry/vk.xml" -Ddemos=false -Dd3d11=enabled
     do_checkIfExist
 fi
 ```

**Comment by Doofussy2** [comment]
Apologies. I'm a noob. Where do I apply the patch?

**Comment by Biswa96** [comment]
In this repository.

**Comment by Doofussy2** [comment]
I don't have enough time to figure this out right now, and it's late. I'll just have to use the other build that I have.

**Comment by Ajaja** [comment]
@Biswa96 Thanks, it works.
`[vo/gpu-next] Initialized libplacebo v4.192.0-18-g3801431 (API v192)
[vo/gpu-next] Using DXGI 1.2+
[vo/gpu-next] Using Direct3D 11 feature level 12_1
[vo/gpu-next] Direct3D 11 device properties:
[vo/gpu-next]     Device Name: Intel(R) UHD Graphics
[vo/gpu-next]     Device ID: 8086:9b41 (rev 02)
[vo/gpu-next]     Subsystem ID: 1028:096a
[vo/gpu-next]     LUID: 00000000000131fe
[vo/gpu-next]     Driver version: 27.20.100.9664
[vo/gpu-next] shaderc SPIR-V version 1.6 rev 1
[vo/gpu-next] Initialized SPIR-V compiler 'shaderc'
[vo/gpu-next] Using Direct3D 11.4 runtime
[vo/gpu-next] D3DCompiler version: 10.0.19041.868
[vo/gpu-next] GPU information:
[vo/gpu-next]     GLSL version: 450 (vulkan)
[vo/gpu-next]       max_shmem_size:            32768
[vo/gpu-next]       max_group_threads:         1024
[vo/gpu-next]       max_group_size[0]:         1024
[vo/gpu-next]       max_group_size[1]:         1024
[vo/gpu-next]       max_group_size[2]:         64
[vo/gpu-next]       subgroup_size:             0
[vo/gpu-next]       min_gather_offset:         -32
[vo/gpu-next]       max_gather_offset:         31
[vo/gpu-next]     Limits:
[vo/gpu-next]       thread_safe:               0
[vo/gpu-next]       callbacks:                 0
[vo/gpu-next]       max_buf_size:              134217728
[vo/gpu-next]       max_ubo_size:              65536
[vo/gpu-next]       max_ssbo_size:             134217728
[vo/gpu-next]       max_vbo_size:              134217728
[vo/gpu-next]       max_mapped_size:           0
[vo/gpu-next]       max_buffer_texels:         134217728
[vo/gpu-next]       align_host_ptr:            0
[vo/gpu-next]       max_tex_1d_dim:            16384
[vo/gpu-next]       max_tex_2d_dim:            16384
[vo/gpu-next]       max_tex_3d_dim:            2048
[vo/gpu-next]       blittable_1d_3d:           1
[vo/gpu-next]       buf_transfer:              0
[vo/gpu-next]       align_tex_xfer_pitch:      1
[vo/gpu-next]       align_tex_xfer_offset:     32
[vo/gpu-next]       max_variable_comps:        0
[vo/gpu-next]       max_constants:             0
[vo/gpu-next]       max_pushc_size:            0
[vo/gpu-next]       align_vertex_stride:       1
[vo/gpu-next]       max_dispatch[0]:           65535
[vo/gpu-next]       max_dispatch[1]:           65535
[vo/gpu-next]       max_dispatch[2]:           65535
[vo/gpu-next]       fragment_queues:           1
[vo/gpu-next]       compute_queues:            1
[vo/gpu-next] Using flip-model presentation
[vo/gpu-next/win32] DPI detected from the new API: 96
[vo/gpu-next/win32] display-fps: 59.940060
[vo/gpu-next/win32] color-profile: C:\WINDOWS\system32\spool\drivers\color\sRGB Color Space Profile.icm
[vo/gpu-next] Assuming 59.940060 FPS for display sync.`

**Comment by Doofussy2** [comment]
I don't have the knowledge base to do that, unfortunately.

**Comment by Doofussy2** [comment]
So I guess this is now a bug. As is, building mpv is incomplete.

**Comment by Doofussy2** [comment]
I couldn't get the patch to work. I probably did some wrong. Clearly, something needs a tweak for the suite to build libplacebo completely.

**Comment by 1480c1** [comment]
Assuming my local compilation works, I will push some commits for this, @Ajaja what did you run to confirm d3d11 worked for you?

**Comment by Ajaja** [comment]
@1480c1 
mpv.conf:
```
vo=gpu-next
gpu-context=d3d11 
gpu-api=d3d11
```
the command line:  `mpv.com -v https://www.youtube.com/watch?v=WtASp2FH0X8 > out.txt`
out.txt is here: https://0x0.st/oXaH.txt

**Comment by 1480c1** [comment]
pushed the commits, please try again

**Comment by Doofussy2** [comment]
I'm afraid that's a fail.

```
Likely error (tail of the failed operation logfile):
Run-time dependency vulkan found: YES 1.3.205
Found CMake: G:\mpv_building_tools\msys64\mingw64\bin/cmake.EXE (3.22.2)
Run-time dependency epoxy found: NO (tried pkgconfig and cmake)
Run-time dependency shaderc_combined found: YES 2022.2.0
Dependency spirv-cross found: NO found 0.13.0 but need: '>=0.29.0'
Run-time dependency spirv-cross found: NO (tried cmake)

../src/meson.build:32:0: ERROR: Invalid version of dependency, need 'spirv-cross' ['>=0.29.0'] found '0.13.0'.
```
[logs.zip](https://0x0.st/oXuf.zip)

**Comment by 1480c1** [comment]
you might need to delete build/spirv-cross-git or whatever it's called, I have made changes there as well

**Comment by ImportTaste** [comment]
> pushed the commits, please try again

I was compiling everything completely successfully (last compilation being on the 7th) until the recent commits. Now libplacebo won't build. glslang-git fails at the `Running meson` stage with this error: `../src/meson.build:32:0: ERROR: Invalid version of dependency, need 'spirv-cross' ['>=0.29.0'] found '0.13.0'.`

[logs.zip](https://0x0.st/oXQD.zip)

**Comment by Doofussy2** [comment]
> you might need to delete build/spirv-cross-git or whatever it's called, I have made changes there as well

That worked! Thank you for your diligence. Much appreciated. I will close this.
