### ISSUE TITLE
MinGW64 GCC compiler isn't installed

### ISSUE THREAD

**Issue by okazunori2013** [m-ab-s/media-autobuild_suite#2116]
critical updates

warning: Public keyring not found; have you run 'pacman-key --init'?
error: mingw32: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: mingw64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: ucrt64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: clang64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: msys: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'ucrt64' is not valid (invalid or corrupted database (PGP signature))
error: database 'clang64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))

second update

creating local64-bit install folders

- write fstab mount file

install msys2 base system

install 64 bit compiler

MinGW64 GCC compiler isn't installed; maybe the download didn't work
Do you want to try it again?

try again [y/n]:

**Comment by okazunori2013** [comment]
maybe me PC was broken.

**Comment by dp289m** [comment]
Same error with Win 11 runnign github version.
