### ISSUE TITLE
libplacebo git

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2118]
┌ libplacebo git  ..................................... [Recently updated]
0001-meson-use-shaderc_combined.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running uninstall...
├ Running meson...
├ Running build...
├ Running install...
├ Stripping...
└ libplacebo-git  .............................................. [Updated]

**Comment by 1480c1** [comment]
I'll probably just work on getting that one upstreamed since I think shaderc recommends using the way I did it

**Comment by Barough** [comment]
Any news/info regarding this issue?
