### ISSUE TITLE
media-autobuild_suite.bat hangs

### ISSUE THREAD

**Issue by ReenigneArcher** [m-ab-s/media-autobuild_suite#2119]
The script hangs if running on a headless server, such as in a github workflow runner.

There is a prompt to enter "y or n" (see here: https://github.com/SunshineStream/Sunshine-Windows-Prebuilt/runs/5164017886?check_suite_focus=true#step:6:4039)

Partial output:
```txt
update autobuild suite
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
 Creating suite update file...

 Run this file by dragging it to mintty before the next time you run
 the suite and before reporting an issue.

 It needs to be run separately and with the suite not running!
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Updating pacman database...
-------------------------------------------------------------------------------

25l:: Synchronizing package databases...
 mingw32
 mingw64
 ucrt64
 clang64
 msys
 ucrt64 is up to date clang64 is up to date msys is up to date mingw32 is up to date mingw64 is up to date25h
-------------------------------------------------------------------------------
Checking pacman packages...
-------------------------------------------------------------------------------


-------------------------------------------------------------------------------
You have more packages than needed!
Do you want to remove them?
-------------------------------------------------------------------------------

Remove:
msys2-runtime
remove packs [y/n]? Please answer yes or no
```

**Comment by 1480c1** [comment]
Pushed a commit, can you check to see if it works?

I am thinking of making the script more headless/inputless friendly, but not sure yet

**Comment by ReenigneArcher** [comment]
> Pushed a commit, can you check to see if it works?
> 
> I am thinking of making the script more headless/inputless friendly, but not sure yet

Thanks for the quick response!

Unfortunately, I have the same problem... https://github.com/SunshineStream/Sunshine-Windows-Prebuilt/runs/5167854444?check_suite_focus=true#step:6:4370

Considering you are now explicitly installing `msys2-runtime`, should it be removed from the following two places?

https://github.com/m-ab-s/media-autobuild_suite/blob/4bcf272496217a1a2955c40cbc3f95ef97ecc02e/media-autobuild_suite.bat#L1462
https://github.com/m-ab-s/media-autobuild_suite/blob/4bcf272496217a1a2955c40cbc3f95ef97ecc02e/media-autobuild_suite.bat#L1618
