### ISSUE TITLE
Build aborts on leptonica git make [mingw64]

### ISSUE THREAD

**Issue by selfDemanDeD** [m-ab-s/media-autobuild_suite#2124]
Hello! Tried to delete the leptonica-git folder, but am still getting the same error. Unfortunately, I have no experience with compiling such stuff, so it has me baffled that make would fail on trying to go to lib directory. Shouldn't it be created if it is needed? Would appreciate help.

``` bash
        Warning: We will not accept any issues lacking any form of logs or logs.zip!

        Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt

        Starting 64bit compilation of global tools
├ Running rustup_update...
├ Running set_default_toolchain...
  Running git update for dssim...
dssim git  .................................................. [Up-to-date]
  Running git update for libxml2...
libxml2 git  ................................................ [Up-to-date]
  Running git update for freetype...
freetype git  ............................................... [Up-to-date]
  Running git update for fontconfig...
fontconfig git  ............................................. [Up-to-date]
  Running git update for harfbuzz...
harfbuzz git  ............................................... [Up-to-date]
  Running git update for fribidi...
fribidi git  ................................................ [Up-to-date]
  Running git update for libass...
libass git  ................................................. [Up-to-date]
gnutls 3.6.16  .............................................. [Up-to-date]
libidn2 2.3.0  .............................................. [Up-to-date]
libpsl 0.21.0  .............................................. [Up-to-date]
  Running git update for curl...
curl git  ................................................... [Up-to-date]
  Running git update for freeglut...
freeglut git  ............................................... [Up-to-date]
  Running git update for libtiff...
libtiff git  ................................................ [Up-to-date]
  Running git update for libwebp...
libwebp git  ................................................ [Up-to-date]
├ FFmpeg and related apps will depend on OpenCL.dll
  Running git update for OpenCL-Headers...
OpenCL-Headers git  ......................................... [Up-to-date]
  Running git update for leptonica...
┌ leptonica git  ...................................... [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
Making all in src
make[2]: Entering directory '/build/leptonica-git/build-64bit/src'
  CCLD     liblept.la
../libtool: line 7521: cd: lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'lib'
make[2]: *** [Makefile:635: liblept.la] Error 1
make[2]: Leaving directory '/build/leptonica-git/build-64bit/src'
make[1]: *** [Makefile:535: all-recursive] Error 1
make[1]: Leaving directory '/build/leptonica-git/build-64bit'
make: *** [Makefile:419: all] Error 2
make failed. Check C:/mabs/build/leptonica-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
```

[logs.zip](https://0x0.st/o81y.zip)

**Comment by dolpsdw** [comment]
Also happening to me
https://0x0.st/o8YX.zip

**Comment by Biswa96** [comment]
leptonical can be built separately in msys2/mingw-w64 environment without any error. I have used these commands.

```sh
git clone --depth=1 https://github.com/DanBloomberg/leptonica.git
cd leptonica/
./autogen.sh
./configure --prefix=$MINGW_PREFIX
make
```

**Comment by BedrockDotPng** [comment]
Maybe temporarily excluding it somehow?

**Comment by BedrockDotPng** [comment]
Probably have to open the issue in leptonica repo.

**Comment by SebastianGode** [comment]
Can we exclude that somehow?
I don't find it in ffmpeg_options or somewhere else sadly.

**Comment by dolpsdw** [comment]
if you comment tesseract in ffnpeg_options file it will be skyped

**Comment by BedrockDotPng** [comment]
Lemme try that. It may work!

**Comment by BedrockDotPng** [comment]
> leptonical can be built separately in msys2/mingw-w64 environment without any error. I have used these commands.
> 
> ```shell
> git clone --depth=1 https://github.com/DanBloomberg/leptonica.git
> cd leptonica/
> ./autogen.sh
> ./configure --prefix=$MINGW_PREFIX
> make
> ```

Doesn't work for me, so I reinstalled the compiler as it might pretty sure be the problem...

**Comment by 1480c1** [comment]
pushed a commit for libtiff, try deleting `build/libtiff-git` and rerun the suite

**Comment by 1480c1** [comment]
Did you repull the suite? If so, do you have the logs?

**Comment by selfDemanDeD** [comment]
> Did you repull the suite? If so, do you have the logs?

Here: [logs.zip](https://0x0.st/oK1S.zip)

**Comment by 1480c1** [comment]
You did delete build/libtiff-git right? Can you paste `local32/lib/pkgconfig/libtiff-4.pc`?

**Comment by selfDemanDeD** [comment]
> You did delete build/libtiff-git right? Can you paste `local32/lib/pkgconfig/libtiff-4.pc`?

Yes, of course.

Here it is:
`prefix=C:/mabs/local64
exec_prefix=C:/mabs/local64
libdir=lib
includedir=include

Name: libtiff
Description:  Tag Image File Format (TIFF) library.
Version: 4.3.0
Libs: -Llib -ltiff
Libs.private:  -ldeflate
Cflags: -Iinclude
Requires.private:  zlib libjpeg libzstd
`

**Comment by 1480c1** [comment]
Can you delete that file and rerun the suite? the libdir line should not only include `lib` and the Libs like should be more like `Libs: -L${libdir} -ltiff`

**Comment by selfDemanDeD** [comment]
> Can you delete that file and rerun the suite? the libdir line should not only include `lib` and the Libs like should be more like `Libs: -L${libdir} -ltiff`

This helped, thank you! The build is successful!
