### ISSUE TITLE
Build aborts on leptonica git make [mingw32] after fresh install

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#2128]
16:26:43 libtiff git  ................................... [Already built]
16:26:43 libwebp git  ................................... [Already built]
16:26:43 ├ FFmpeg and related apps will depend on OpenCL.dll
16:26:45 OpenCL-Headers git  ............................ [Already built]
16:26:48   Running git update for leptonica...
16:26:48 ┌ leptonica git  ............................ [Recently updated]
16:26:48 ├ Running autogen...
16:27:05 ├ Running configure...
16:28:13 ├ Running make...
Likely error (tail of the failed operation logfile):
Making all in src
make[2]: Entering directory '/build/leptonica-git/build-32bit/src'
  CCLD     liblept.la
../libtool: line 7521: cd: lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'lib'
make[2]: *** [Makefile:635: liblept.la] Error 1
make[2]: Leaving directory '/build/leptonica-git/build-32bit/src'
make[1]: *** [Makefile:535: all-recursive] Error 1
make[1]: Leaving directory '/build/leptonica-git/build-32bit'
make: *** [Makefile:419: all] Error 2

Deleting leptonica git didn't help!
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8089949/logs.zip)

**Comment by selfDemanDeD** [comment]
Same for me with 64 bit (#2124)

**Comment by 1480c1** [comment]
pushed a commit for libtiff, try deleting `build/libtiff-git` and rerun the suite

**Comment by ASopH** [comment]
deleted ..\local32\lib\pkgconfig\libtiff-4 and ..build\libtiff-git ...
seems to build fine now
