### ISSUE TITLE
Error running git update for tesseract

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2130]
02:46:33   Running git update for tesseract...
02:46:52 ┌ tesseract git  ............................... [Updates found]
02:46:57 ├ Running autogen...
02:47:44 ├ Running uninstall...
02:47:44 ├ Running configure...
02:49:16 ├ Running make...
Likely error (tail of the failed operation logfile):
make[1]: Leaving directory '/build/tesseract-git/build-64bit'
make: *** [Makefile:8138: all-recursive] Error 1
Making all in .
make[1]: Entering directory '/build/tesseract-git/build-64bit'
  CXXLD    libtesseract_ccutil.la
./libtool: line 7535: cd: lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'lib'
make[1]: *** [Makefile:3799: libtesseract_ccutil.la] Error 1
make[1]: Leaving directory '/build/tesseract-git/build-64bit'
make: *** [Makefile:8138: all-recursive] Error 1
make failed. Check C:/MinGW-w64/build/tesseract-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
02:52:43   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/o8YR.zip
Copy and paste [logs.zip](https://0x0.st/o8YR.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/o8YR.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/8099692/ab-suite.make.log)

**Comment by 1480c1** [comment]
pushed a commit for libtiff, try deleting `build/libtiff-git` and rerun the suite

**Comment by 1480c1** [comment]
no response in 22 days, closing
