### ISSUE TITLE
leptonica bug

### ISSUE THREAD

**Issue by lyglay1991** [m-ab-s/media-autobuild_suite#2131]
15:21:26 ┌ leptonica git  ............................ [Recently updated]
15:21:26 ├ Running autogen...
15:21:41 ├ Running configure...
15:22:37 ├ Running make...
Likely error (tail of the failed operation logfile):
Making all in src
make[2]: Entering directory '/build/leptonica-git/build-64bit/src'
  CCLD     liblept.la
../libtool: line 7521: cd: lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'lib'
make[2]: *** [Makefile:635: liblept.la] Error 1
make[2]: Leaving directory '/build/leptonica-git/build-64bit/src'
make[1]: *** [Makefile:535: all-recursive] Error 1
make[1]: Leaving directory '/build/leptonica-git/build-64bit'
make: *** [Makefile:419: all] Error 2
make failed. Check F:/media-autobuild_suite-master/build/leptonica-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
15:23:11   Creating diagnostics file...

Attach F:\media-autobuild_suite-master\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by Biswa96** [comment]
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2124

**Comment by lyglay1991** [comment]
> Duplicate of #2124

libtool:   error: cannot determine absolute directory name of 'lib'
make[2]: *** [Makefile:635: liblept.la] Error 1
make[2]: Leaving directory '/build/leptonica/src'
make[1]: *** [Makefile:535: all-recursive] Error 1
make[1]: Leaving directory '/build/leptonica'
make: *** [Makefile:419: all] Error 2
lyglay1991@DESKTOP-NOBGIU5 /build/leptonica

**Comment by 1480c1** [comment]
pushed a commit for libtiff, try deleting `build/libtiff-git` and rerun the suite

**Comment by lyglay1991** [comment]
Delete build/libtiff-git to run and compile normally，thx
