### ISSUE TITLE
 libjxl error

### ISSUE THREAD

**Issue by lyglay1991** [m-ab-s/media-autobuild_suite#2136]
12:01:28 ┌ libjxl git  ............................... [Recently updated]
12:01:33 ├ Uninstalling asciidoc-py3-git... failed
12:02:59 ├ Running cmake...
12:03:20 ├ Running build...
Likely error (tail of the failed operation logfile):
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/ios_base.h:41,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/ios:42,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/istream:38,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/sstream:38,
                 from F:/media-autobuild_suite-master/build/libjxl-git/examples/encode_oneshot.cc:12:
F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
build failed. Check F:/media-autobuild_suite-master/build/libjxl-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
12:03:22   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oK2g.zip
Copy and paste [logs.zip](https://0x0.st/oK2g.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/oK2g.zip)

**Comment by lyglay1991** [comment]
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
ninja -j5 
[1/273] Building CXX object CMakeFiles/encode_oneshot.dir/examples/encode_oneshot.cc.o
FAILED: CMakeFiles/encode_oneshot.dir/examples/encode_oneshot.cc.o 
F:\media-autobuild_suite-master\msys64\mingw64\bin\ccache.exe  g++ -DCMS_NO_REGISTER_KEYWORD=1 -DHWY_STATIC_DEFINE -DJXL_EXPORT="" -DJXL_THREADS_STATIC_DEFINE -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -IF:/media-autobuild_suite-master/build/libjxl-git -IF:/media-autobuild_suite-master/build/libjxl-git/lib/include -IF:/media-autobuild_suite-master/build/libjxl-git/build-64bit/lib/include -IF:/media-autobuild_suite-master/build/libjxl-git/third_party/highway -IF:/media-autobuild_suite-master/build/libjxl-git/third_party/lcms/include -isystem F:/media-autobuild_suite-master/msys64/mingw64/include -isystem F:/media-autobuild_suite-master/build/libjxl-git/third_party/-IF:/media-autobuild_suite-master/msys64/mingw64/include -mthreads -mtune=generic -O2 -pipe -fno-rtti -funwind-tables -O3 -DNDEBUG -O2 -fmacro-prefix-map=F:/media-autobuild_suite-master/build/libjxl-git=. -Wno-builtin-macro-redefined -Wall -std=c++11 -MD -MT CMakeFiles/encode_oneshot.dir/examples/encode_oneshot.cc.o -MF CMakeFiles\encode_oneshot.dir\examples\encode_oneshot.cc.o.d -o CMakeFiles/encode_oneshot.dir/examples/encode_oneshot.cc.o -c F:/media-autobuild_suite-master/build/libjxl-git/examples/encode_oneshot.cc
In file included from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/ext/string_conversions.h:41,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/basic_string.h:6607,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/string:55,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/locale_classes.h:40,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/ios_base.h:41,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/ios:42,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/istream:38,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/sstream:38,
                 from F:/media-autobuild_suite-master/build/libjxl-git/examples/encode_oneshot.cc:12:
F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
[2/273] Building C object CMakeFiles/jxlinfo.dir/examples/jxlinfo.c.o
[3/273] Building CXX object CMakeFiles/decode_progressive.dir/examples/decode_progressive.cc.o
[4/273] Building CXX object CMakeFiles/decode_oneshot.dir/examples/decode_oneshot.cc.o
[5/273] Building C object third_party/CMakeFiles/lcms2.dir/lcms/src/cmsalpha.c.o
ninja: build stopped: subcommand failed.
[1/269] Building CXX object CMakeFiles/encode_oneshot.dir/examples/encode_oneshot.cc.o
FAILED: CMakeFiles/encode_oneshot.dir/examples/encode_oneshot.cc.o 
F:\media-autobuild_suite-master\msys64\mingw64\bin\ccache.exe  g++ -DCMS_NO_REGISTER_KEYWORD=1 -DHWY_STATIC_DEFINE -DJXL_EXPORT="" -DJXL_THREADS_STATIC_DEFINE -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -IF:/media-autobuild_suite-master/build/libjxl-git -IF:/media-autobuild_suite-master/build/libjxl-git/lib/include -IF:/media-autobuild_suite-master/build/libjxl-git/build-64bit/lib/include -IF:/media-autobuild_suite-master/build/libjxl-git/third_party/highway -IF:/media-autobuild_suite-master/build/libjxl-git/third_party/lcms/include -isystem F:/media-autobuild_suite-master/msys64/mingw64/include -isystem F:/media-autobuild_suite-master/build/libjxl-git/third_party/-IF:/media-autobuild_suite-master/msys64/mingw64/include -mthreads -mtune=generic -O2 -pipe -fno-rtti -funwind-tables -O3 -DNDEBUG -O2 -fmacro-prefix-map=F:/media-autobuild_suite-master/build/libjxl-git=. -Wno-builtin-macro-redefined -Wall -std=c++11 -MD -MT CMakeFiles/encode_oneshot.dir/examples/encode_oneshot.cc.o -MF CMakeFiles\encode_oneshot.dir\examples\encode_oneshot.cc.o.d -o CMakeFiles/encode_oneshot.dir/examples/encode_oneshot.cc.o -c F:/media-autobuild_suite-master/build/libjxl-git/examples/encode_oneshot.cc
In file included from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/ext/string_conversions.h:41,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/basic_string.h:6607,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/string:55,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/locale_classes.h:40,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/ios_base.h:41,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/ios:42,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/istream:38,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/sstream:38,
                 from F:/media-autobuild_suite-master/build/libjxl-git/examples/encode_oneshot.cc:12:
F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by lyglay1991** [comment]
solved

**Comment by Intrinsic27** [comment]
> solved

How exactly? this has started happening for the last few weeks again.

**Comment by Biswa96** [comment]
The compile errors with `#include_next <stdlib.h>` message are not fatal. The issue is in the gcc compiler which has not solved yet.

The issue can be workaround just by re-running the build command or deleting the build directory of that project.

**Comment by Intrinsic27** [comment]
> The compile errors with `#include_next <stdlib.h>` message are not fatal. The issue is in the gcc compiler which has not solved yet.
> 
> The issue can be workaround just by re-running the build command or deleting the build directory of that project.

Unfortunately i'd already tried those (and again just now in case it'd been fixed) and the same issue remains :/

**Comment by diegocr** [comment]
```db
...  -o lib/CMakeFiles/jxl_cms.dir/jxl/cms/jxl_cms.cc.o -c D:/mabs/build/libjxl-git/lib/jxl/cms/jxl_cms.cc
In file included from D:/mabs/msys64/mingw64/include/c++/13.2.0/bits/stl_algo.h:71,
                 from D:/mabs/msys64/mingw64/include/c++/13.2.0/algorithm:61,
                 from D:/mabs/build/libjxl-git/lib/jxl/cms/jxl_cms.cc:14:
D:/mabs/msys64/mingw64/include/c++/13.2.0/cstdlib:79:15: fatal error: stdlib.h: No such file or directory
   79 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

Same here @Intrinsic27 


```c
#if !_GLIBCXX_HOSTED
// The C standard does not require a freestanding implementation to
// provide <stdlib.h>.  However, the C++ standard does still require
// <cstdlib> -- but only the functionality mentioned in
// [lib.support.start.term].
...
```

I'm not an expert on this, but i have the feeling this nay be solvable within mabs, given the way the toolchain is installed and/or with a patch or such @Biswa96  (?)

ref: https://bbs.archlinux.org/viewtopic.php?id=284000

```bash
$ pacman -Ql mingw-w64-x86_64-gcc | grep stdlib.h
mingw-w64-x86_64-gcc /mingw64/include/c++/13.2.0/stdlib.h
mingw-w64-x86_64-gcc /mingw64/include/c++/13.2.0/tr1/stdlib.h
```

**Comment by diegocr** [comment]
er... @Intrinsic27 dunno if your case will be the same, but i solved this on my side by deleting `D:\mabs\local64\etc\profile2.local` so that it's re-created on the next build...

@Biswa96 Sorry for bothering 😢

**Comment by Biswa96** [comment]
Those `#include_next <stdlib.h>` related issue was fixed long ago. Try to reinstall the gcc related packages if required.
