### ISSUE TITLE
 lensfun error

### ISSUE THREAD

**Issue by lyglay1991** [m-ab-s/media-autobuild_suite#2137]
ffmpeg_options setting --enable-liblensfun，lensfun error
21:53:46 ┌ lensfun git  .............................. [Recently updated]
21:53:52 ├ Running cmake...
21:53:56 ├ Running build...
Likely error (tail of the failed operation logfile):
In file included from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/ext/string_conversions.h:41,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/basic_string.h:6607,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/string:55,
                 from F:/media-autobuild_suite-master/build/lensfun-git/build-64bit/lensfun.h:39,
                 from F:/media-autobuild_suite-master/build/lensfun-git/libs/lensfun/auxfun.cpp:7:
F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
[logs.zip](https://0x0.st/oKtJ.zip)
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe -DGLIB_STATIC_COMPILATION
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe -DGLIB_STATIC_COMPILATION
LDFLAGS: -pipe -static-libgcc -static-libstdc++
ninja -j2 
[1/16] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mount.cpp.o
FAILED: libs/lensfun/CMakeFiles/lensfun.dir/mount.cpp.o 
F:\media-autobuild_suite-master\msys64\mingw64\bin\ccache.exe  g++ -DCONF_LENSFUN_STATIC -IF:/media-autobuild_suite-master/build/lensfun-git/build-64bit -IF:/media-autobuild_suite-master/build/lensfun-git/include/lensfun -isystem F:/media-autobuild_suite-master/msys64/mingw64/include/glib-2.0 -isystem F:/media-autobuild_suite-master/msys64/mingw64/lib/glib-2.0/include -isystem F:/media-autobuild_suite-master/msys64/mingw64/include -mthreads -mtune=generic -O2 -pipe -DGLIB_STATIC_COMPILATION -Wall -Wformat-security -O3 -DNDEBUG -std=c++11 -MD -MT libs/lensfun/CMakeFiles/lensfun.dir/mount.cpp.o -MF libs\lensfun\CMakeFiles\lensfun.dir\mount.cpp.o.d -o libs/lensfun/CMakeFiles/lensfun.dir/mount.cpp.o -c F:/media-autobuild_suite-master/build/lensfun-git/libs/lensfun/mount.cpp
In file included from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/ext/string_conversions.h:41,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/basic_string.h:6607,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/string:55,
                 from F:/media-autobuild_suite-master/build/lensfun-git/build-64bit/lensfun.h:39,
                 from F:/media-autobuild_suite-master/build/lensfun-git/libs/lensfun/mount.cpp:7:
F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
[2/16] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/camera.cpp.o
FAILED: libs/lensfun/CMakeFiles/lensfun.dir/camera.cpp.o 
F:\media-autobuild_suite-master\msys64\mingw64\bin\ccache.exe  g++ -DCONF_LENSFUN_STATIC -IF:/media-autobuild_suite-master/build/lensfun-git/build-64bit -IF:/media-autobuild_suite-master/build/lensfun-git/include/lensfun -isystem F:/media-autobuild_suite-master/msys64/mingw64/include/glib-2.0 -isystem F:/media-autobuild_suite-master/msys64/mingw64/lib/glib-2.0/include -isystem F:/media-autobuild_suite-master/msys64/mingw64/include -mthreads -mtune=generic -O2 -pipe -DGLIB_STATIC_COMPILATION -Wall -Wformat-security -O3 -DNDEBUG -std=c++11 -MD -MT libs/lensfun/CMakeFiles/lensfun.dir/camera.cpp.o -MF libs\lensfun\CMakeFiles\lensfun.dir\camera.cpp.o.d -o libs/lensfun/CMakeFiles/lensfun.dir/camera.cpp.o -c F:/media-autobuild_suite-master/build/lensfun-git/libs/lensfun/camera.cpp
In file included from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/ext/string_conversions.h:41,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/basic_string.h:6607,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/string:55,
                 from F:/media-autobuild_suite-master/build/lensfun-git/build-64bit/lensfun.h:39,
                 from F:/media-autobuild_suite-master/build/lensfun-git/libs/lensfun/camera.cpp:7:
F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
[1/16] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/auxfun.cpp.o
FAILED: libs/lensfun/CMakeFiles/lensfun.dir/auxfun.cpp.o 
F:\media-autobuild_suite-master\msys64\mingw64\bin\ccache.exe  g++ -DCONF_LENSFUN_STATIC -IF:/media-autobuild_suite-master/build/lensfun-git/build-64bit -IF:/media-autobuild_suite-master/build/lensfun-git/include/lensfun -isystem F:/media-autobuild_suite-master/msys64/mingw64/include/glib-2.0 -isystem F:/media-autobuild_suite-master/msys64/mingw64/lib/glib-2.0/include -isystem F:/media-autobuild_suite-master/msys64/mingw64/include -mthreads -mtune=generic -O2 -pipe -DGLIB_STATIC_COMPILATION -Wall -Wformat-security -O3 -DNDEBUG -std=c++11 -MD -MT libs/lensfun/CMakeFiles/lensfun.dir/auxfun.cpp.o -MF libs\lensfun\CMakeFiles\lensfun.dir\auxfun.cpp.o.d -o libs/lensfun/CMakeFiles/lensfun.dir/auxfun.cpp.o -c F:/media-autobuild_suite-master/build/lensfun-git/libs/lensfun/auxfun.cpp
In file included from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/ext/string_conversions.h:41,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/basic_string.h:6607,
                 from F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/string:55,
                 from F:/media-autobuild_suite-master/build/lensfun-git/build-64bit/lensfun.h:39,
                 from F:/media-autobuild_suite-master/build/lensfun-git/libs/lensfun/auxfun.cpp:7:
F:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by lyglay1991** [comment]
today make error
 [logs.zip](https://0x0.st/oKYa.zip)
15:43:01 ┌ lensfun git  .............................. [Recently updated]
15:43:10 ├ Installing glib2... done
15:43:31 ├ Running cmake...
15:43:36 ├ Running build...
Likely error (tail of the failed operation logfile):
In file included from D:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/ext/string_conversions.h:41,
                 from D:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/bits/basic_string.h:6607,
                 from D:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/string:55,
                 from D:/media-autobuild_suite-master/build/lensfun-git/build-64bit/lensfun.h:39,
                 from D:/media-autobuild_suite-master/build/lensfun-git/libs/lensfun/camera.cpp:7:
D:/media-autobuild_suite-master/msys64/mingw64/include/c++/11.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by 1480c1** [comment]
pushed https://github.com/m-ab-s/media-autobuild_suite/commit/dc53b9059d70385de3635c0342120bd55839138f to fix it, try again

**Comment by 1480c1** [comment]
no response, going to assume it's fixed
