### ISSUE TITLE
ffmpeg make error

### ISSUE THREAD

**Issue by lyglay1991** [m-ab-s/media-autobuild_suite#2139]
ffmpeg_options setting --enable-vapoursynth，ffmpeg make error
20:31:45 libplacebo git  ................................... [Up-to-date]
20:33:31 ├ Compiling FFmpeg with Vapoursynth R57
20:33:31 ├ FFmpeg will need vapoursynth.dll and vsscript.dll to run using vapoursynth demuxers!
20:33:45   Running git update for ffmpeg...
20:34:16 ┌ ffmpeg git  .................................. [Updates found]
20:34:16 ├ Changing options to comply to nonfree...
20:34:42 ├ Compiling static FFmpeg...
20:34:44 ├ Running configure...
20:44:41 ├ Running make...
Likely error (tail of the failed operation logfile):
D:/media-autobuild_suite-master/local64/include/vapoursynth/VSHelper.h:92:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   92 |     int64_t a, b;
      |     ^~~~~~~
D:/media-autobuild_suite-master/build/ffmpeg-git/libavformat/vapoursynth_alt.c: In function 'read_header':
D:/media-autobuild_suite-master/build/ffmpeg-git/libavformat/vapoursynth_alt.c:236:16: error: implicit declaration of function 'av_cpu_count'; did you mean 'av_popcount'? [-Werror=implicit-function-declaration]
  236 |     vs->ncpu = av_cpu_count();
      |                ^~~~~~~~~~~~
      |                av_popcount
cc1.exe: some warnings being treated as errors
make: *** [/build/ffmpeg-git/ffbuild/common.mak:78: libavformat/vapoursynth_alt.o] Error 1
make failed. Check D:/media-autobuild_suite-master/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
 [logs.zip](https://0x0.st/oKEH.zip)

**Comment by Patman86** [comment]
See issue #2134...

**Comment by 1480c1** [comment]
push patch changes and commits, please try again

**Comment by lyglay1991** [comment]
Solved, but there is one more problem:ffmpeg_options setting --enable-liblensfun，lensfun make error,[#2317](https://github.com/m-ab-s/media-autobuild_suite/issues/2137#issue-1150476145)need to be resolved

**Comment by 1480c1** [comment]
Since this specific issue is fixed, closing, still working on lensfun
