### ISSUE TITLE
[x64] Patches could not be applied

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2140]
┌ libtiff git  ........................................ [Recently updated]
├ Running uninstall...
233.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libtiff-git  ................................................. [Updated]
┌ libwebp git  ........................................ [Recently updated]
0002-deps.cmake-unroll-img-loop-and-use-import-libraries-.patch
        Patch could not be applied with `git am`. Continuing without patching.
0008-CMake-add-WEBP_BUILD_WEBPMUX-to-list-of-checks-for-e.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libwebp-git  ................................................. [Updated]

**Comment by 1480c1** [comment]
removed 233 since it seems uneeded since compilation is fine and rebased the libwebp patches, although I am wondering if they are no longer needed since I think I fixed some issues inside cmake's modules

**Comment by Barough** [comment]
Thnx :)
