### ISSUE TITLE
libwebp failed to build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2145]
┌ libwebp git  ........................................... [Updates found]
├ Running uninstall...
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libtiff.a(tif_lzma.o):(.text+0x45b): undefined reference to `lzma_stream_encoder'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libtiff.a(tif_lzma.o):(.text+0x516): undefined reference to `lzma_lzma_preset'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libtiff.a(tif_lzma.o):(.text+0x54b): undefined reference to `lzma_stream_encoder'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libtiff.a(tif_lzma.o):(.text+0x602): undefined reference to `lzma_code'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libtiff.a(tif_lzma.o):(.text+0x634): undefined reference to `lzma_memusage'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libtiff.a(tif_lzma.o):(.text+0x64c): undefined reference to `lzma_stream_decoder'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libtiff.a(tif_lzma.o):(.text+0x82f): undefined reference to `lzma_stream_decoder'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libtiff.a(tif_lzma.o):(.text+0xa00): undefined reference to `lzma_lzma_preset'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check D:/MABS-ffmpeg/build/libwebp-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oZB9.zip

**Comment by Barough** [comment]
Ok

**Comment by Barough** [comment]
Built just fine now

**Comment by 1480c1** [comment]
Fixed upstream
