### ISSUE TITLE
[x64] libwebp - patches could not be appiled

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2150]
┌ libwebp git  ........................................ [Recently updated]
0002-deps.cmake-unroll-img-loop-and-use-import-libraries-.patch
        Patch could not be applied with `git am`. Continuing without patching.
0005-CMake-add-WEBP_BUILD_WEBPMUX-to-list-of-checks-for-e.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libwebp-git  ................................................. [Updated]

tested 3 times and everytime it's the same patches

**Comment by donradzsk** [comment]
```
freeglut git  ............................................... [Up-to-date]
  Running git update for libtiff...
┌ libtiff git  ........................................... [Updates found]
├ Running uninstall...
2992ba372025f3bc273263391f6650148be7ae6c.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libtiff-git  ................................................. [Updated]
  Running git update for libwebp...
┌ libwebp git  ........................................ [Recently updated]
└ 0006-CMake-use-import-library-for-SDL-if-available.patch  ..... [Failed]
Error 404 while downloading https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/libwebp/0006-CMake-use-import-library-for-SDL-if-available.patch
<Ctrl+c> to cancel build or <Enter> to continue
if you're sure nothing depends on it.
0006-CMake-use-import-library-for-SDL-if-available.patch
        Patch not found anywhere. Continuing without patching.
└ 0008-CMake-add-WEBP_BUILD_WEBPMUX-to-list-of-checks-for-e.patch  ...................................................................... [Failed]
Error 404 while downloading https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/libwebp/0008-CMake-add-WEBP_BUILD_WEBPMUX-to-list-of-checks-for-e.patch
<Ctrl+c> to cancel build or <Enter> to continue
if you're sure nothing depends on it.
```
Could it be a server error?

**Comment by Barough** [comment]
> Could it be a server error?

'Error 404' = Site can't be accessed/reached.

Try again to build/compile it

**Comment by Biswa96** [comment]
The patches for libwebp were changed here https://github.com/m-ab-s/media-autobuild_suite/commit/4406dbe964574679067d138a51b09386503649c5. `git pull` this repository to get the changes.
