### ISSUE TITLE
Request: 64bit MPlayer&Mencoder with Avisynth support

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#2151]
Currently only 32bit MPlayer&Mencoder support Avisynth, would be nice if the 64bit versions would also be build with Avisynth support.
(Assuming this is not a MPlayer&Mencoder restriction I'm not aware of.)

**Comment by 1480c1** [comment]
Doesn't seem like we are explicitly doing anything with avisysnth or mplayer with 64-bit or 32-bit, so at least it's not a simple removing an if

**Comment by Selur** [comment]
Argh, just remembered an old post https://forum.doom9.org/showthread.php?p=1925928#post1925928 -> seems like it's a MPlayer&Mencoder restriction I wasn't aware off so probably no way around it unless MPlayer developement starts up again.
