### ISSUE TITLE
openal-soft build fails since openal-soft commit 88d5c47e3705fcc8978815442e80aa4205f29ad0

### ISSUE THREAD

**Issue by nikolasr** [m-ab-s/media-autobuild_suite#2154]
Building (64-bit) with openal-soft fails (see attached logs).
I think openal-soft commit 88d5c47e3705fcc8978815442e80aa4205f29ad0 causes this. When reverting to openal-soft commit b168482ea3f5bfb0df4dd043934a87f3132f96c9 everything builds fine.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8356282/logs.zip)

**Comment by donradzsk** [comment]
This working a few days ago but now getting this error.

**Comment by 1480c1** [comment]
Should have been fixed upstream

**Comment by nikolasr** [comment]
Confirmed. This issue is fixed by openal-soft commit b9ff9fa6d90676e2bb961fae25d83b9e4bbbea93.
