### ISSUE TITLE
[vulkan-loader] Error 'windows_read_manifest_from_d3d_adapters' while building

### ISSUE THREAD

**Issue by Bertaz** [m-ab-s/media-autobuild_suite#2156]
Building for 64-bit
Before it gave a different error, but I forgot to save logs. Something like `include winsock2.h before windows.h [-Werror=cpp]`

``` bash
16:40:37   Running git update for vulkan-loader...
16:40:37 ┌ vulkan-loader git  ........................ [Recently updated]
16:40:37 ├ Running uninstall...
16:40:39 ├ Running dependencies...
16:40:57 ├ Installing Vulkan-Headers...
16:40:57 ├ Running uninstall...
16:40:57 ├ Running cmake...
16:40:58 ├ Running build...
16:40:58 ├ Running install...
16:40:59 ├ Building Vulkan-Loader...
16:41:00 ├ Running cmake...
16:41:05 ├ Running build...
Likely error (tail of the failed operation logfile):
      |                                                         ^
D:/ffmpegAutobuildSuite/build/vulkan-loader-git/loader/loader_windows.c: In function 'windows_read_manifest_from_d3d_adapters':
D:/ffmpegAutobuildSuite/build/vulkan-loader-git/loader/loader_windows.c:580:9: error: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'NTSTATUS (*)(const LoaderEnumAdapters2 *)' {aka 'long int (*)(const LoaderEnumAdapters2 *)'} [-Werror=cast-function-type]
  580 |         (PFN_LoaderEnumAdapters2)GetProcAddress(GetModuleHandle("gdi32.dll"), "D3DKMTEnumAdapters2");
      |         ^
D:/ffmpegAutobuildSuite/build/vulkan-loader-git/loader/loader_windows.c:582:9: error: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'NTSTATUS (*)(const LoaderQueryAdapterInfo *)' {aka 'long int (*)(const LoaderQueryAdapterInfo *)'} [-Werror=cast-function-type]
  582 |         (PFN_LoaderQueryAdapterInfo)GetProcAddress(GetModuleHandle("gdi32.dll"), "D3DKMTQueryAdapterInfo");
      |         ^
cc1.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.
build failed. Check D:/ffmpegAutobuildSuite/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
16:41:12   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oq4A.zip
```

[logs.zip](https://0x0.st/oq4A.zip)

**Comment by Biswa96** [comment]
Werror compiler option was added in this commit https://github.com/KhronosGroup/Vulkan-Loader/commit/336508b06bab741cf6b832c5b98026c852ba461f. There should be an option to disable it. Let me ask it in upstream.

**Comment by Biswa96** [comment]
This commit now adds an option to disable werror compiler option https://github.com/KhronosGroup/Vulkan-Loader/commit/a59027c96db28b32a2c0a9cc8b858340620577e9. Just add `-DENABLE_WERROR=OFF` option with cmake configure command.

**Comment by Bertaz** [comment]
I noticed 91d9174a30d6c95d17d71bec7910dfdd934c6b8f added the option to the suite. I can confirm it fixes the issue.
> Just add `-DENABLE_WERROR=OFF` option with cmake configure command.

Btw I wasn't sure what you meant with cmake configure command. Was I supposed to do `cmake -D ENABLE_WERROR=OFF`?
I tried in \build\vulkan-loader-git but the build kept failing with the same error

**Comment by Biswa96** [comment]
> Btw I wasn't sure what you meant with cmake configure command.

The https://github.com/m-ab-s/media-autobuild_suite/commit/91d9174a30d6c95d17d71bec7910dfdd934c6b8f commit already did what I meant in my previous commit. Thank you for reporting this issue ❤️
