### ISSUE TITLE
ERROR: libplacebo >= 4.192.0 not found using pkg-config

### ISSUE THREAD

**Issue by lastrosade** [m-ab-s/media-autobuild_suite#2158]
ffmpeg won't build with libplacebo anymore.

I have waited for a while to see if it would ever get fixed by something upstream but no luck.

This is soon after a clean install.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8401932/logs.zip)

**Comment by BlueSwordM** [comment]
Yeah, it'd be amazing if it could fixed.

On my end, I've mostly had this issue with static builds.

**Comment by 1480c1** [comment]
```bash
.\local64\bin-video\ffmpeg.exe -filters | grep -i placebo
...
 ..C libplacebo        V->V       Apply various GPU filters from libplacebo
```
seems to exist for me, going to test with your ini files then

**Comment by 1480c1** [comment]
pushed https://github.com/m-ab-s/media-autobuild_suite/commit/6e00e757518eeb6a59ebc937fb6233f21ab1cb47, please try again

**Comment by lastrosade** [comment]
Works fine
