### ISSUE TITLE
Error when installing libxml2-git

### ISSUE THREAD

**Issue by YUKI2eN3e** [m-ab-s/media-autobuild_suite#2159]
I've tried deleting '/build/libxml2-git' and rerunning as suggested, and even completely wiping and reinstalling
media-autobuild_suite but the same error keeps coming up.
[libxml2-git_error.log](https://github.com/m-ab-s/media-autobuild_suite/files/8406601/libxml2-git_error.log)

**Comment by snowbie** [comment]
same for me

**Comment by Biswa96** [comment]
Does libxml-2.0.pc file exist anywhere in local64 directory?

**Comment by 1480c1** [comment]
I've pushed a [commit](https://github.com/m-ab-s/media-autobuild_suite/commit/56e31d52d8e8fe3a49755c8b0d242d16f9a78923), can you try again?

**Comment by YUKI2eN3e** [comment]
It seems to have made it past libxml2-git now, but the script is still running so that's all I know so far.

**Comment by YUKI2eN3e** [comment]
The script has finished running and it seems to be fine.
