### ISSUE TITLE
Patches could not be applied with `git am`

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2160]
x86/x64
┌ libwebp git  ........................................ [Recently updated]
0005-CMake-add-WEBP_BUILD_WEBPMUX-to-list-of-checks-for-e.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libwebp-git  ................................................. [Updated]

x64
┌ SPIRV-Cross git  .................................... [Recently updated]
├ Running uninstall...
0001-add-a-basic-Meson-build-system-for-use-as-a-subproje.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running meson...
├ Running build...
├ Running install...
├ Stripping...
└ SPIRV-Cross-git  ............................................. [Updated]

x64
┌ libplacebo git  ..................................... [Recently updated]
0001-meson-use-shaderc_combined.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running uninstall...
├ Running meson...
├ Running build...
├ Running install...
├ Stripping...
└ libplacebo-git  .............................................. [Updated]

x64
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Patch could not be applied with git am. Continuing without patching.
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
├ ffmpeg-git  .................................................. [Updated]

**Comment by Barough** [comment]
Original post updated

**Comment by 1480c1** [comment]
> 0001-add-a-basic-Meson-build-system-for-use-as-a-subproje.patch

This one, I think I know why, still working on a solution

> master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch


this one and libsvtvp9 are broken upstream, will try to think of a way to fix this one

**Comment by Nekofoxmiu** [comment]
My libwebp patch also failed, but they are another patch files.

 ┌ libwebp git  ........................................ [Recently updated]
├ Installing giflib... done
0002-deps.cmake-unroll-img-loop-and-use-import-libraries-.patch
        Patch could not be applied with `git am`. Continuing without patching.
0007-deps-use-pkg-config-instead-of-find_package.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libwebp-git  ................................................. [Updated]

**Comment by Barough** [comment]
Any news regarding this?

**Comment by 1480c1** [comment]
Don't have much time today and tomorrow as I still have final exams, can take a look Wednesday though

**Comment by Barough** [comment]
> Don't have much time today and tomorrow as I still have final exams, can take a look Wednesday though

Take your time m8, your exams is high priority. I was just wondering.

**Comment by Barough** [comment]
> > master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
> 
> this one and libsvtvp9 are broken upstream, will try to think of a way to fix this one

Hope u manage to think of a way to fixed those 2 so that we get libsvthevc and libsvtvp9 back in ffmpeg
