### ISSUE TITLE
Virus warnings....vmaf path issue...etc

### ISSUE THREAD

**Issue by ls-milkyway** [m-ab-s/media-autobuild_suite#2163]
Firstly, Let me give some positive feedback..congrats .exceptionally good automated script with some great inclusions & tremendous effort to maintain it....now I would like to mention some problems/shortcomings:

**1) CA-Bundle in curl always fails with log:**
├ Running ca-bundle...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
make -j2 ca-bundle
make: *** No rule to make target 'lib/mk-ca-bundle.pl', needed by 'ca-bundle'.  Stop.
make: *** No rule to make target 'lib/mk-ca-bundle.pl', needed by 'ca-bundle'.  Stop.
ca-bundle failed. Check C:/mabs/build/curl-git/build-64bit/ab-suite.ca-bundle.log
This isn't required for anything so we can move on.

**2) Kaspersky Internet Security flags a trojan (may be false ...as it is detected by heuristic scan).**
Event: Object deleted
User: Xxxxx\xxx
User type: Active user
Component: Virus Scan
Result: Deleted
Result description: Deleted
Type: Trojan
Name: VHO:Trojan.Win32.Inject.gen
Precision: Heuristic Analysis
Threat level: High
Object type: File
Object name: file_to_header.exe
Object path: X:\<folder name>\FFmpeg\build\AMF-git\Thirdparty\file_to_header
MD5: 0ECE4149D6B7BE4389E72E91359D925E

**3) Some domains have certificate issues they fail "Encrypted Connection Scanning: by KIS:**
sh.rustup.rs
0x0.st (I guess used to upload logs ..**.strangely without permission**).
& static.rust-lang.org

most probably these domains are using certificates (personal & not verified) ...& I have to include them in trusted address in KIS...for the script to download ...specially rust.

**4** Even if I do not select to include some packages like curl, svt-av1 ..etc. strangely the script still downloads & compile them.
media-autobuild_suite.ini (attached as txt)
[media-autobuild_suite.txt](https://github.com/m-ab-s/media-autobuild_suite/files/8442994/media-autobuild_suite.txt)

**5** Script should mention which packages might break static builds & are meant for shared builds only for those who are not well acquainted with FFmpeg build types......& logically, option to automate the future builds (with updated components) should be available only after a successful build.

**6** Absolute paths (for eg. in VMAF) is hard coded....a warning should be given....I have a successful build earlier....but moved binaries and deleted the folder.....cannot use VMAF models ...as I don't remember the folder names with structure?? Anyway to find the inbuilt path used by compiled ffmpeg.exe?

**Comment by Barough** [comment]
It's not uncommon for AV's to flag codecs as viruses etc. It have happen to me multiple times. Report it to Kaspersky as false positives. You can also set so that your AV so that it doesn't scan the mabs folder structure. That's what i've done to deal with the issue in question.

**Comment by 1480c1** [comment]
> 1) CA-Bundle in curl always fails with log:

seems that was broken upstream https://github.com/curl/curl/commit/8e22fc68e7dda43e9f0b6857b1057d0e9131a4b2, going to look into it now

> 2) Kaspersky Internet Security flags a trojan (may be false ...as it is detected by heuristic scan).

I've learned not to really trust anti-viruses on executables compiled by gcc and tools under mingw-w64, Windows Defender has managed to mark gcc and it's tools as "obfuscators" and caused a lot of issues in the past including extremely slow builds due to real-time scanning of each and every single temporary object files etc. It's up to you to decide if you want to trust amd. Sadly, they do not provide the source code for their binaries, so you can't view them in their original form.


> 3) Some domains have certificate issues they fail "Encrypted Connection Scanning: by KIS:

doesn't really seem like something the suite can do anything about, 

> sh.rustup.rs
> static.rust-lang.org

are rust's official sites as far as I know, and at least for sh.rustup.rs, it's certificate is
```bash
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            01:55:28:c9:27:0f:c7:02:e1:84:8c:b3:d8:87:74:a5
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
        Validity
            Not Before: Mar  4 00:00:00 2022 GMT
            Not After : Apr  2 23:59:59 2023 GMT
        Subject: CN = sh.rustup.rs
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:b2:e2:06:54:9d:7c:b0:61:2c:7a:fa:07:d3:53:
                    11:ec:46:eb:ad:91:fe:d1:69:9a:e1:a4:86:ec:3f:
                    ea:7f:37:94:00:21:c9:3a:e8:6f:10:65:fd:8d:4e:
                    2c:ad:b1:1a:de:07:28:3c:8c:24:0b:43:e3:d3:32:
                    a8:7e:de:a5:e7:c6:d8:72:83:0b:f3:e7:eb:61:0a:
                    71:84:15:bb:a8:75:3f:f9:bf:4a:33:0f:ec:14:4b:
                    b9:10:a0:0c:0e:19:4c:d8:d2:e6:4f:62:a2:d1:8a:
                    90:27:bf:19:94:eb:57:f5:63:26:56:c6:cb:d5:b8:
                    14:f2:2a:16:ee:ed:9e:d4:ec:a5:ff:31:fd:3c:1f:
                    00:74:1c:72:73:f9:88:62:88:a2:76:b4:3a:ba:e5:
                    a8:22:84:48:fe:75:52:bf:81:0c:2b:e4:a1:04:1b:
                    77:b2:f5:2b:ab:48:39:64:44:60:4d:c5:2b:a8:fa:
                    eb:b2:69:6d:ac:dd:b5:e9:87:a4:a9:c4:c9:b2:f1:
                    9e:02:c1:f3:d0:d9:0c:8e:7d:4f:d2:0e:e3:1c:6d:
                    f6:c5:8a:b7:63:2b:f4:39:da:5a:26:4a:f9:23:9a:
                    66:92:0a:b6:f9:bb:f0:e4:e9:c7:ba:9c:55:29:99:
                    da:ed:b9:b7:e3:d5:2e:09:19:79:59:dd:40:e5:84:
                    f7:1f
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                keyid:59:A4:66:06:52:A0:7B:95:92:3C:A3:94:07:27:96:74:5B:F9:3D:D0

            X509v3 Subject Key Identifier: 
                8D:8F:CC:F4:3E:A3:14:80:EE:B9:3F:C3:A2:9C:3D:BB:36:66:81:A4
            X509v3 Subject Alternative Name: 
                DNS:sh.rustup.rs
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:http://crl.sca1b.amazontrust.com/sca1b-1.crl

            X509v3 Certificate Policies: 
                Policy: 2.23.140.1.2.1

            Authority Information Access: 
                OCSP - URI:http://ocsp.sca1b.amazontrust.com
                CA Issuers - URI:http://crt.sca1b.amazontrust.com/sca1b.crt

```

and I guess kis doesn't have a chain of trust towards amazon I guess

> 0x0.st (I guess used to upload logs ...strangely without permission).

is hosted by @mia-0 (I think) using https://github.com/mia-0/0x0, and uses letsencrypt.

I personally trust it and have seen it in use by others as well, but for KIS, I guess it's different, for the "without permission" part, that is true, but at the same time, it's kinda hard to expect the average user to be able to upload their logs.zip file to github considering how many of them aren't even willing to quickly look through the latest issues to see if their issue already exists. If you know a better way to handle this, I am open to suggestions or pull requests

> 4 Even if I do not select to include some packages like curl, svt-av1 ..etc. strangely the script still downloads & compile them.
media-autobuild_suite.ini (attached as txt)

Probably from your ffmpeg_config.txt or ffmpegB2


> 6 Absolute paths (for eg. in VMAF) is hard coded....a warning should be given....I have a successful build earlier....but moved binaries and deleted the folder.....cannot use VMAF models ...as I don't remember the folder names with structure?? Anyway to find the inbuilt path used by compiled ffmpeg.exe?

I believe the models should be built in since we have xxd through vim, so you shouldn't need the individual model files, to find out the names, you could go to https://github.com/Netflix/vmaf/blob/e32389dfa8947f6b7843e6032ed6805c0de1c4bc/libvmaf/src/model.c#L43 and find the one you want, I don't know if they provide a way to retrieve them from the command line though

**Comment by 1480c1** [comment]
re: curl ca-bundle

https://github.com/curl/curl/pull/8728

**Comment by mia-0** [comment]
FWIW, I don’t mind logs getting uploaded to 0x0.st, and I will not look at them, but I strongly encourage you to ask for user consent. Maybe also make sure any paths in there are relative, i.e. do not contain user names.

**Comment by 1480c1** [comment]
I can probably add another question to the batch file asking if they want their logs.zip files to be automatically uploaded to 0x0.st or not and can probably also do something like a sed pass to replace instances of full paths with path's relative to `/` or something and replace `$USER` and `$USERDOMAIN` with `<user>` and `<domain>` or something

**Comment by mia-0** [comment]
Would not recommend replacinng $USER/$USERDOMAIN; might end up mangling the logs pretty badly depending on what those variables are set to.

**Comment by ls-milkyway** [comment]
> I've learned not to really trust anti-viruses on executables compiled by gcc and tools under mingw-w64, Windows Defender has managed to mark gcc and it's tools as "obfuscators" and caused a lot of issues in the past including extremely slow builds due to real-time scanning of each and every single temporary object files etc. It's up to you to decide if you want to trust amd. Sadly, they do not provide the source code for their binaries, so you can't view them in their original form.

The only file in question is: **"file_to_header.exe"** formed in folder "AMF-git"....not only flagged as suspicious by many big names like symantec, kaspersky, mcafee, bitdefender, trendmicro....etc. but it also tries to contact 2 ips (one of them is suspicious)....again without user consent....some thing should be done .....I have heard somewhere .....putting a logo with some digital signatures will stop it getting flagged, Virus-Total results are attached....
![virus-total](https://user-images.githubusercontent.com/55090624/164992792-e1515f04-4a4a-47c3-923a-4e429a2ce35e.png)
![ip-contact](https://user-images.githubusercontent.com/55090624/164992794-303f43f4-7be8-494a-b867-bd056775d6cb.png)

**Comment by 1480c1** [comment]
Seems an issue was opened upstream https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/311
