### ISSUE TITLE
mingw64 libavif build warning

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2169]
09:56:19 ┌ libavif git  .............................. [Recently updated]
0001-CMake-Use-the-import-libraries-and-the-proper-variab.patch
        Patch could not be applied with `git am`. Continuing without patching.
09:56:26 ├ Running cmake...
09:56:30 ├ Running build...
09:56:37 ├ Running install...
09:56:38 ├ Stripping...

**Comment by 1480c1** [comment]
remove the patch in 9039bcd734
