### ISSUE TITLE
mingw64 libwebp build warning

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2170]
07:45:19 ┌ libwebp git  ................................. [Updates found]
0002-deps.cmake-unroll-img-loop-and-use-import-libraries-.patch
        Patch could not be applied with `git am`. Continuing without patching.
0007-deps-use-pkg-config-instead-of-find_package.patch
        Patch could not be applied with `git am`. Continuing without patching.
07:45:29 ├ Running uninstall...
07:45:29 ├ Running cmake...
07:45:43 ├ Running build...
07:46:03 ├ Running install...
07:46:04 ├ Stripping...
07:46:04 └ libwebp-git  ....................................... [Updated]

**Comment by Bertaz** [comment]
## [mingw64] [libwebp] Patch could not be applied 0002 & 0007
``` bash
18:04:57   Running git clone for libwebp...
18:05:04 ┌ libwebp git  .............................. [Recently updated]
0002-deps.cmake-unroll-img-loop-and-use-import-libraries-.patch
        Patch could not be applied with `git am`. Continuing without patching.
0007-deps-use-pkg-config-instead-of-find_package.patch
        Patch could not be applied with `git am`. Continuing without patching.
18:05:12 ├ Running uninstall...
18:05:12 ├ Running cmake...
18:05:31 ├ Running build...
18:05:36 ├ Running install...
18:05:36 ├ Stripping...
18:05:37 └ libwebp-git  ....................................... [Updated]
```

[logs.zip](https://0x0.st/ock3.zip)

**Comment by 1480c1** [comment]
removed the patches since it seems to compile just fine without them https://github.com/m-ab-s/media-autobuild_suite/commit/acefce7062362595a4afe13911bdfc5ad665206c
