### ISSUE TITLE
Is libilbc (and others) being added to _to_remove intended?

### ISSUE THREAD

**Issue by waldonnis** [m-ab-s/media-autobuild_suite#2172]
Not sure if this is a bug or intended, but I noticed that add_to_remove is called for some repos that are being cloned from github.  I noticed it when libilbc was being cloned every time I reran the suite and was then deleted as part of the deleteSource function call at the end of the run.

Here's a list of the repos I found that are possibly being deleted unnecessarily:
- rubberband
- libilbc
- speexenc
- vorbis-tools
- xavs
- lensfun

Any chance someone can review these and ensure that they still need to be added to _to_remove for post-run removal?  I'm thinking that was a relic from when some of those were compiled from downloaded release zips/tarballs, but I could be mistaken.

**Comment by 1480c1** [comment]
I think those were indeed legacy lines that weren't removed, fa914b9f16

Thanks
