### ISSUE TITLE
/build/libxml2-git issue

### ISSUE THREAD

**Issue by jriker1** [m-ab-s/media-autobuild_suite#2173]
When I try and run the batch file to update the script I get which I didn't last time I ran it:

Try deleting '/build/libxml2-git' and start the script again.

If you are sure there are no dependencies, <Enter> to continue building.
[?2004h[?2004l
[?2004h[?2004l
Close this window if you wish to stop building.

Note I did delete all folders except the build folder but no joy.  Tried an admin and non admin dos window, no joy.

[compile.log](https://github.com/m-ab-s/media-autobuild_suite/files/8500675/compile.log)

**Comment by 1480c1** [comment]
do you have the latest suite?

**Comment by jriker1** [comment]
I zip downloaded the latest and overwrote what I had, then deleted the other folders but build and same deal.

**Comment by jriker1** [comment]
Yep, for some reason only the items in the root folder updated before.  Got past that now complaining about tesseract not found using pkg-config.

https://0x0.st/oc3s.zip
