### ISSUE TITLE
Request: Change MPlayer repository to GIT

### ISSUE THREAD

**Issue by hnsteyding** [m-ab-s/media-autobuild_suite#2176]
Actual MPlayer source code is also available under:

https://git.ffmpeg.org/mplayer.git

If switched from SVN to GIT repository MinGW/MSYS SVN component in media-autobuild_suite is not necessary anymore ?

Regards
Mark

**Comment by 1480c1** [comment]
Yeah, as in if someone opens an issue on mplayer's issue tracker and say "I have this issue on git commit adf5139497ba92916e95d5e8047393a58740a51a", would mplayer understand without needing to be pointed to that repository?

**Comment by hnsteyding** [comment]
OK, this is an important point.
To be honest - i don't know :-(

I've done bug reporting from time to time to http://lists.mplayerhq.hu/mailman/listinfo/mplayer-users and told the following Information:

- Clone from the latest repo
- Log file if compile errors occur:
./configure --<COMPILE OPTIONS> > Compile.log
Example (my name in subscriber list is "max muster")
http://lists.mplayerhq.hu/pipermail/mplayer-users/2022-February/089148.html

**Comment by 1480c1** [comment]
Let me think about it for maybe a day to consider the pros and cons of this

**Comment by therealt3nzin** [comment]
@1480c1 The git repo is AFAIK unofficial but it does include the svn commit id in the git log with the svn commit message so finding the svn commit to reference to submit an issue on the mplayer bugtracker shouldn't be much of an issue. For reference here is the git log for the commit you referenced above:
```
commit adf5139497ba92916e95d5e8047393a58740a51a (HEAD -> master, origin/master, origin/HEAD)
Author: reimar <reimar@b3059339-0415-0410-9bf9-f77b7e298cf2>
Date:   Sun Apr 17 18:15:10 2022 +0000

    configure: Fix compilation against latest FFmpeg.


    git-svn-id: svn://git.mplayerhq.hu/mplayer/trunk@38365 b3059339-0415-0410-9bf9-f77b7e298cf2
```
And here is the svn log for that same commit:
```
r38365 | reimar | 2022-04-17 14:15:10 -0400 (Sun, 17 Apr 2022) | 2 lines
Changed paths:
   M /trunk/configure

configure: Fix compilation against latest FFmpeg.
```

**Comment by 1480c1** [comment]
One issue I can see with it the version printout for the mplayer binary, their version generation goes like

```bash
if test -z $version ; then
# Extract revision number from file used by daily tarball snapshots
# or from the places different Subversion versions have it.
svn_revision=$(cat snapshot_version 2> /dev/null)
test $svn_revision || svn_revision=$(LC_ALL=C svn info 2> /dev/null | grep Revision | cut -d' ' -f2)
test $svn_revision || svn_revision=$(grep revision .svn/entries 2>/dev/null | cut -d '"' -f2)
test $svn_revision || svn_revision=$(sed -n -e '/^dir$/{n;p;q;}' .svn/entries 2>/dev/null)
test $svn_revision && svn_revision=SVN-r$svn_revision
test $svn_revision || svn_revision=UNKNOWN
version=$svn_revision
fi
```

and compiling with that git repo results in

```bash

MPlayer UNKNOWN-11.2.0 (C) 2000-2022 MPlayer Team

```

and I can't git svn clone it or anything, so it can't retain both a git commit and a svn hash
