### ISSUE TITLE
Vmaf enabled build refuses built-in model path?

### ISSUE THREAD

**Issue by ls-milkyway** [m-ab-s/media-autobuild_suite#2180]
Something is messing up vmaf model path in media auto build whereas same command runs smoothly in both [BtbN's](https://github.com/BtbN/FFmpeg-Builds/releases) & [Gyan's](https://github.com/GyanD/codexffmpeg) builds:

**Command:**  `ffmpeg -f lavfi -i color=c=black:s=640x480:d=1  -filter_complex "[0:v][0:v]libvmaf='model_path=C\:/Temp/FF/Audio Video/FFMetrics.1.0.0/vmaf-models/vmaf_v0.6.1.json:log_path=VMAF_out.json:n_threads=2:log_fmt=json'" -f null -`

**Output BtbN:**
![btbn](https://user-images.githubusercontent.com/55090624/165652692-a5ce0ba1-ae98-45f3-8241-e682fb46965b.png)

**Output Gyan's:**
![gyans](https://user-images.githubusercontent.com/55090624/165652829-25459ee7-85ba-4ce6-acb0-d642d7b53d18.png)

**Output Media Autobuild:**
![media-auto-build](https://user-images.githubusercontent.com/55090624/165652909-4aa518c7-2332-4883-98a2-b6dfe60140ae.png)

**Any body any ideas???**

**Comment by 1480c1** [comment]
I can run it if I escaped the colon with three backslashes, so 
```bash
ffmpeg.exe  -f lavfi -i color=c=black:s=640x480:d=1 -filter_complex "[0:v][0:v]libvmaf=model_path=D\\\:/media-autobuild_suite/build/vmaf-git/libvmaf/build-64bit/src/vmaf_v0.6.1.json" -f null -
```
or
```bash
ffmpeg.exe  -f lavfi -i color=c=black:s=640x480:d=1 -filter_complex "[0:v][0:v]libvmaf=model='path=D\\\:/media-autobuild_suite/build/vmaf-git/libvmaf/build-64bit/src/vmaf_v0.6.1.json'" -f null -
```
as recommended by the warning or
```bash
ffmpeg.exe  -f lavfi -i color=c=black:s=640x480:d=1 -filter_complex "[0:v][0:v]libvmaf=model=version=vmaf_v0.6.1" -f null -
```
to use the built-in models

**Comment by ls-milkyway** [comment]
> ffmpeg.exe  -f lavfi -i color=c=black:s=640x480:d=1 -filter_complex "[0:v][0:v]libvmaf=model_path=D\\\:/media-autobuild_suite/build/vmaf-git/libvmaf/build-64bit/src/vmaf_v0.6.1.json" -f null -

This path command works for me.....thanks....but built-in does not work (fyi: is working on both BtbN & Gyan?? As I want to use built-in command for my project...kindly suggest.
**Gyan:**
![gyan](https://user-images.githubusercontent.com/55090624/166571771-f696a45a-9fec-41e1-8920-ff2cc4604ea0.PNG)
**BtbN:**
![btbn](https://user-images.githubusercontent.com/55090624/166571866-21fc019a-ee33-43a4-95a1-bbb827fe9343.png)
**Media-Build**
![media-build](https://user-images.githubusercontent.com/55090624/166571959-26dc4088-2cdf-4587-9725-756e33b06e1b.png)

Since both gyan & media-build use gcc with MSYS2 ...hence I am attaching `ffmpeg -buildconf` as text for your reference ...Thanks
[build-gyan.txt](https://github.com/m-ab-s/media-autobuild_suite/files/8614489/build-gyan.txt)
[media-build.txt](https://github.com/m-ab-s/media-autobuild_suite/files/8614498/media-build.txt)

**Comment by 1480c1** [comment]
I'm absolutely confused as to why yours doesn't work, I ran the commands with the ffmpeg produced by the suite

![image](https://user-images.githubusercontent.com/8345542/166584689-8213719b-aab5-4e96-b16e-6933bec3f178.png)

I just pushed a commit to explicitly install vim, which should provide xxd.exe, try pulling and deleting build/vmaf-git and rerun and meanwhile it's running, try getting the log files from build/vmaf-git

**Comment by ls-milkyway** [comment]
> I just pushed a commit to explicitly install vim, which should provide xxd.exe, try pulling and deleting build/vmaf-git and rerun and meanwhile it's running, try getting the log files from build/vmaf-git

Hmm....sure....I will build & let you know ....you mean vim (with xxd,exe) is also needed on Windows ....I also see that you are running it from original path i.e. \local64\bin-video\...(cmd or mintty) ....whereas I am running by moving the builds to another partition with folder: G:\My..on cmd....

**Comment by 1480c1** [comment]
xxd.exe is needed for vmaf to generate internal models

**Comment by ls-milkyway** [comment]
> meanwhile it's running, try getting the log files from build/vmaf-git

What do you mean? Plz elaborate ....there is a logs folder at: \build\vmaf-git\.git\logs....do you want me to attach it?

**Latest Output:**
![media-build](https://user-images.githubusercontent.com/55090624/166639052-937ed50a-1020-4334-8e0d-a2ce3561069d.PNG)

**Comment by 1480c1** [comment]
> What do you mean? Plz elaborate ....there is a logs folder at: \build\vmaf-git\.git\logs....do you want me to attach it?

Yes, I want to confirm that the built-in models were actually compiled in

**Comment by ls-milkyway** [comment]
> > What do you mean? Plz elaborate ....there is a logs folder at: \build\vmaf-git.git\logs....do you want me to attach it?
> 
> Yes, I want to confirm that the built-in models were actually compiled in
 
**Attached:** The  logs folder at: `\build\vmaf-git\.git\logs`
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8624995/logs.zip)

**Comment by 1480c1** [comment]
oh, you meant the .git folder's logs, I mean `/build/vmaf-git/build-64bits/ab*.log` files. There should have been one with `meson` in it's name

**Comment by ls-milkyway** [comment]
> oh, you meant the .git folder's logs, I mean `/build/vmaf-git/build-64bits/ab*.log` files. There should have been one with `meson` in it's name

??? But **there is no folder named: `build-64bits`** inside location `/build/vmaf-git/` ..I have the following folders & files inside vmaf-git:
![vmaf-git](https://user-images.githubusercontent.com/55090624/166862938-ccaaac42-a0a4-40bd-9e02-347c59d0d4c3.PNG)

**Comment by 1480c1** [comment]
Seems I was wrong, it's `build/vmaf-git/libvmaf/build-64bit`. Forgot that vmaf uses an extra subdirectory for their project

**Comment by ls-milkyway** [comment]
> Seems I was wrong, it's `build/vmaf-git/libvmaf/build-64bit`. Forgot that vmaf uses an extra subdirectory for their project

nope, there is no such folder inside `/build/vmaf-git/libvmaf/` refer below:
![libvmaf](https://user-images.githubusercontent.com/55090624/166864063-9b569e00-16f2-4634-b634-2037380af8b3.png)

**Comment by 1480c1** [comment]
Hmm, seems like your build deleted the folders after it finished, mine still has them.

![image](https://user-images.githubusercontent.com/8345542/166864260-1bccc72c-e120-42a7-ab8b-3fd66bb61444.png)

![image](https://user-images.githubusercontent.com/8345542/166864270-e5f6e2d1-6847-45ad-8ab1-0d14958caa06.png)


Can you try deleting the vmaf-git folder and rebuilding, and while it's running the suite, but after it builds vmaf, can you try to get those log files?

**Comment by ls-milkyway** [comment]
>Hmm, seems like your build deleted the folders after it finished, mine still has them.

Yeah, I saw some cleaning up after the successful build.

>Can you try deleting the vmaf-git folder and rebuilding, and while it's running the suite, but after it builds vmaf, can you try to get those log files?

Sure....I will post them.

**Comment by 1480c1** [comment]
Actually, try repulling and rerunning, found an issue

Either way, the key line I'm looking for is
```none
Program xxd found: YES (C:\media-autobuild-suite\msys64\usr\bin/xxd.EXE)
```

**Comment by ls-milkyway** [comment]
> Actually, try repulling and rerunning, found an issue and pushed [c734b9c](https://github.com/m-ab-s/media-autobuild_suite/commit/c734b9c9b1dc4bf58e8c883a43167ce18d0491f9)
> 
> Either way, the key line I'm looking for is
> 
> ```
> Program xxd found: YES (C:\media-autobuild-suite\msys64\usr\bin/xxd.EXE)
> ```

added `-m switch`....started build.....got the logs & the log file: ab-suite.meson.log does contain "Program xxd found: YES (E:\Programs\FFmpeg\msys64\usr\bin/xxd.EXE)" @ line 27
[ab-suite.meson.log](https://github.com/m-ab-s/media-autobuild_suite/files/8628933/ab-suite.meson.log)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/8628953/ab-suite.build.log)
[ab-suite.install.log](https://github.com/m-ab-s/media-autobuild_suite/files/8628954/ab-suite.install.log)
Full build pending....

**Comment by ls-milkyway** [comment]
Running configure......
ERROR: sdl2 requested but not found.
[config.log](https://github.com/m-ab-s/media-autobuild_suite/files/8629417/config.log)

**Comment by ls-milkyway** [comment]
Could [not find vim](https://github.com/BtbN/FFmpeg-Builds/tree/master/scripts.d) or [xxd,exe in BtbN source.](https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/45-vmaf.sh)?? I mean in-built are working without xxd.exe in BtbN ??

**Comment by 1480c1** [comment]
For BtbN's, it's probably because his base docker image contains xxd https://github.com/BtbN/FFmpeg-Builds/blob/master/images/base/Dockerfile#L7

**Comment by 1480c1** [comment]
Do you have your logs.zip or `media-autobuild_suite.ini` and `ffmpeg_options.txt` and `mpv_options.txt`? (last two are optional if you didn't select 4 for selection libraries)

Having those 3 files would make it easier for me to try to reproduce your issue

**Comment by 1480c1** [comment]
Seems your issue is due to https://github.com/libsdl-org/SDL/commit/cd7c2f1de7d9e418bb554047d714dd7cacc020ff, sdl2 went from 2.0.23 to 2.23.0, causing ffmpeg to fail detection

**Comment by ls-milkyway** [comment]
>Having those 3 files would make it easier for me to try to reproduce your issue

ffmpeg_options.txt was made to temporarily --disable-sdl2...now removed it & mpv_options.txt is not present.

>Seems your issue is due to https://github.com/libsdl-org/SDL/commit/cd7c2f1de7d9e418bb554047d714dd7cacc020ff, sdl2 went from 2.0.23 to 2.23.0, causing ffmpeg to fail detection.

I will try with previous commit or after rectification & then let u know with logs.zip or media-autobuild_suite.ini...thanks.

**Comment by ls-milkyway** [comment]
> Seems your issue is due to https://github.com/libsdl-org/SDL/commit/cd7c2f1de7d9e418bb554047d714dd7cacc020ff, sdl2 went from 2.0.23 to 2.23.0, causing ffmpeg to fail detection

**Yeah that's the reason .... in-built commands are now working! ....thanks** ...just to remind you .....master branch requires commit for libwebp patches as:

`do_patch "https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/libwebp/0001-WEBP_DEP_LIBRARIES-use-Threads-Threads.patch" am`
   ` do_patch "https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/libwebp/0003-CMake-link-imageioutil-to-exampleutil-after-defined.patch" am`
    `do_patch "https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/libwebp/0004-CMake-use-import-library-for-SDL-if-available.patch" am`
	`do_patch "https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/libwebp/0005-CMake-add-WEBP_BUILD_WEBPMUX-to-list-of-checks-for-e.patch" am`
    `do_patch "https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/libwebp/0006-CMake-add-WEBP_BUILD_WEBPINFO-to-list-of-checks-for-.patch" am`
