### ISSUE TITLE
curl fails, possible loss of compatibility to mbedtls v3

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2181]
see [curl issue 8766](https://github.com/curl/curl/issues/8766)

a relevant part of **ab-suite.make.log**
```
  CC       vtls/libcurl_la-mbedtls.lo
../../lib/vtls/mbedtls.c: In function 'mbed_connect_step2':
../../lib/vtls/mbedtls.c:818:43: error: 'ALPN_H2_LEN' undeclared (first use in this function); did you mean 'ALPN_H2_LENGTH'?
  818 |       if(!strncmp(next_protocol, ALPN_H2, ALPN_H2_LEN) &&
      |                                           ^~~~~~~~~~~
      |                                           ALPN_H2_LENGTH
```

[logs.zip](https://0x0.st/oThH.zip)

**Comment by LigH-de** [comment]
I purged lib, opt, bin-global, bin-audi, bin-video in local## before building.

Did the same yesterday on another PC, here everything passed yesterday.

**Comment by 1480c1** [comment]
Closing as you confirmed it's fixed upstream. Nice speed from him
