### ISSUE TITLE
[x86] vmaf

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2189]
┌ vmaf git  .............................................. [Updates found]
├ Running uninstall...
├ Installing vim... warning: database file for 'clang32' does not exist (use '-Sy' to download)
done
├ Running meson...
├ Running build...
├ Running install...
├ Stripping...
└ vmaf-git  .................................................... [Updated]

**Comment by Biswa96** [comment]
Run `pacman -Syu` first.

**Comment by Barough** [comment]
thnx
