### ISSUE TITLE
FFmpeg / sdl2 requested but not found

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2192]
┌ ffmpeg git  ....................................... [Newer dependencies]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local32/lib -L/mingw32/lib
../configure --prefix=/local32 --bindir=/local32/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --disable-autodetect --enable-amf --enable-bzlib --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-librist --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-liblensfun --enable-libglslang --enable-vulkan --enable-libuavs3d --enable-libplacebo --enable-openssl --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-ID:/MABS-ffmpeg/local32/include --extra-cflags=-ID:/MABS-ffmpeg/local32/include/AL --extra-version=ge3580f6077+135
ERROR: sdl2 requested but not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check D:/MABS-ffmpeg/build/ffmpeg-git/build-static-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oas2.zip
Copy and paste [logs.zip](https://0x0.st/oas2.zip) in the GitHub issue.

--------

Have tested with removing the FFmpeg & sdl2 build folders and then re-run but it didn't help

**Comment by 1480c1** [comment]
Since you are using FFmpeg 5.0, you may need to cherry-pick FFmpeg/FFmpeg@e5163b1d34381a3319214a902ef1df923dd2eeba

**Comment by Barough** [comment]
Don't have a clue on how to do that.

The fun part is that i didn't ran into this issue like 3-4 days ago when FFmpeg compiled just fine.

**Comment by 1480c1** [comment]
I think you should be able to add a `git cherry-pick e5163b1d34381a3319214a902ef1df923dd2eeba` in your pre_vcs since it seems you have a pre_vcs function

**Comment by Barough** [comment]
Sorry, but i don't know how to do that.
Im basically a noob when it comes to this stuff.

**Comment by Biswa96** [comment]
Doesn't normal git pull work? 🤔

**Comment by Barough** [comment]
@Biswa96
Im building FFmpeg from the stable branch. Guess that the specific commit ain't added to the stable branch as of now.

**Comment by Biswa96** [comment]
There are some workaround. Sometimes, when I shallow clone a repository and `git cherry-pick` is not possible, I grab the commit as a patch file and apply it with `git apply` or `patch -p1 -i` or `git am`.

**Comment by Barough** [comment]
As i said above "Im basically a noob when it comes to this stuff."

Have tried to setup my own compile environment some time ago but i couldn't get it to work and then i found out about MABS and gave up on my setting up my own compile environment and have never looked back after that.

**Comment by 1480c1** [comment]
You should have a ffmpeg_extra.sh file or something, I don't know where it is on your system, you can either delete it to pull the master branch, or edit it, and it should have a line that looks like
```bash
_pre_vcs() {
```
that's the function that should be causing you to pull 5.0, you can add somewhere after that function, so the closing `}`, another function
```bash
_post_vcs() {
    git -C "$REPO_DIR" cherry-pick e5163b1d34381a3319214a902ef1df923dd2eeba
}
```
If you do not know how to do this, I don't recommend using a ffmpeg_extra.sh file until so since you can mess with your build  and since they are technically unsuported

**Comment by Barough** [comment]
Here is the content of my ffmpeg_extra.sh file

#!/usr/bin/bash

_pre_vcs() {
    ref=release/5.0
}



So with your addition it should look like this

#!/usr/bin/bash

_pre_vcs() {
    ref=release/5.0
}

_post_vcs() {
    git -C "$REPO_DIR" cherry-pick e5163b1d34381a3319214a902ef1df923dd2eeba
}

**Comment by Barough** [comment]
I'll give it a try and get back later. Thanks

**Comment by Barough** [comment]
Didn't work :(

 Found ffmpeg_extra.sh. Sourcing script...
├ Running pre vcs from ffmpeg_extra.sh...
┌ ffmpeg git  ......................................... [Recently updated]
├ Running post vcs from ffmpeg_extra.sh...
Likely error (tail of the failed operation logfile):
        ab-suite.git.fetch.log
        ab-suite.git.reset.log
        ab-suite.post_vcs.log
        ab-suite.pre_vcs.log
        build-static-32bit/
        build_successful32bit
        recently_checked
        recently_updated

nothing added to commit but untracked files present (use "git add" to track)
post_vcs failed. Check D:/MABS-ffmpeg/build/ffmpeg-git/ab-suite.post_vcs.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oaa3.zip
Copy and paste [logs.zip](https://0x0.st/oaa3.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
All I got for this I guess would be to try
```bash
_post_vcs() {
    git -C "$REPO_DIR" show e5163b1d34381a3319214a902ef1df923dd2eeba | git -C "$REPO_DIR"  apply -3
}
```
and see if that works, else I don't really have any other ideas

**Comment by Barough** [comment]
I got this error this time

┌ ffmpeg git  ............................................ [Updates found]
├ Running post vcs from ffmpeg_extra.sh...
├ Changing options to comply to nonfree...
0001-configure-deduplicate-linking-flags.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local32/lib -L/mingw32/lib
../configure --prefix=/local32 --bindir=/local32/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --disable-autodetect --enable-amf --enable-bzlib --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-librist --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-liblensfun --enable-libglslang --enable-vulkan --enable-libuavs3d --enable-libplacebo --enable-libjxl --enable-openssl --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-ID:/MABS-ffmpeg/local32/include --extra-cflags=-ID:/MABS-ffmpeg/local32/include/AL --extra-version=gf55c91497d+134
Unknown option "--enable-libjxl".
See ../configure --help for available options.
configure failed. Check D:/MABS-ffmpeg/build/ffmpeg-git/build-static-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oBgW.zip
Copy and paste [logs.zip](https://0x0.st/oBgW.zip) in the GitHub issue.

---------------------

Don't know if it's related to the updated '_post_vcs' or not.

**Comment by 1480c1** [comment]
For the patch, that's not sure yet, for the error, that's probably because libjxl support isn't in n5.0, you might need to remove that from your ffmpeg_options.txt or something

**Comment by Barough** [comment]
Totally missed it said unknown option. Was way too tired when i tested compiling earlier.
