### ISSUE TITLE
SDL (mingw32): SDL_windows_gaming_input.c fails compiling

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2199]
Possible reason: pointer types are not compatible, missing explicit typecasts?

Details: https://github.com/libsdl-org/SDL/issues/5728

**Comment by LigH-de** [comment]
Required changes were reported here: https://github.com/libsdl-org/SDL/issues/5589

**Comment by Biswa96** [comment]
It was already fixed/added in upstream.
