### ISSUE TITLE
libjxl git - Uninstalling asciidoc-py3-git... failed

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2201]
Guess that this have to do with this commit
https://github.com/m-ab-s/media-autobuild_suite/commit/169515db579bddc2dfc715c53c880b60fceb8353

┌ libjxl git  ............................................ [Updates found]
├ Running uninstall...
├ Uninstalling asciidoc-py3-git... failed
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ libjxl-git  .................................................. [Updated]

**Comment by LigH-de** [comment]
Pretty old issue, from a time when there was a clash between similarly named package and metapackage (asciidoc for Python 2 vs Pyhon 3), which made it getting installed again during the next start and update of the suite. Should be irrelevant today, I hope, so maybe the forceful uninstallation of this package can be removed...

**Comment by 1480c1** [comment]
removed in https://github.com/m-ab-s/media-autobuild_suite/commit/dd50dc1015304ea4653e71ea0cd47cb9b8eb92c3
