### ISSUE TITLE
highway git fails to compile

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2202]
┌ highway git  ........................................... [Updates found]
├ Running uninstall...
├ Running cmake...
Likely error (tail of the failed operation logfile):

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:259 (add_library):
  No SOURCES given to target: hwy

CMake Generate step failed.  Build files cannot be regenerated correctly.
cmake failed. Check D:/MABS-ffmpeg/build/highway-git/build-32bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oMzx.zip

**Comment by 1480c1** [comment]
Seems build was broken in https://github.com/google/highway/commit/5e5cf8d7f2905932af3a1136eadad3113da4cf4b

**Comment by ycwan** [comment]
Same issue here:

18:43:14 └ libavif-git  ....................................... [Updated]
18:43:19   Running git update for highway...
18:43:21 ┌ highway git  ................................. [Updates found]
18:43:21 ├ Running uninstall...
18:43:22 ├ Running cmake...
Likely error (tail of the failed operation logfile):

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:259 (add_library):
  No SOURCES given to target: hwy


CMake Generate step failed.  Build files cannot be regenerated correctly.
cmake failed. Check [ab-suite.cmake.log](https://github.com/m-ab-s/media-autobuild_suite/files/8837515/ab-suite.cmake.log)/ab-suite.cmake.log
This is required for other packages, so this script will exit.
18:43:34   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oMow.zip
Copy and paste [logs.zip](https://0x0.st/oMow.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[ab-suite.cmake.log](https://github.com/m-ab-s/media-autobuild_suite/files/8837524/ab-suite.cmake.log)

**Comment by LigH-de** [comment]
The reason is apparently:
```
-- Found Python: G:/MABS/msys64/mingw32/bin/python3.9.exe (found version "3.9.13") found components: Interpreter 
-- Configuring done
CMake Error at CMakeLists.txt:259 (add_library):
  Cannot find source file:

    hwy/per_targets.cc
```

**Comment by Barough** [comment]
Just wait and see what happens upstream then.......

**Comment by 1480c1** [comment]
Fixed upstream https://github.com/google/highway/commit/b3bba57d6acec54e404c6a531af3bfdc693b5b0b
