### ISSUE TITLE
List of patches which could not be applied + ANSI stripping

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2204]
2022-06-05

**curl**
  * 0003-libpsl-static-libs.patch
  
**ffmpeg**
  * master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
  
*BTW: How can I strip the **compile.log** off of ANSI color codes when the suite finished successfully? Usually it only creates stripped log files when something failed.*

**Comment by 1480c1** [comment]
You could probably run strip_ansi "$LOCALBUILDDIR"/*.log in mintty

**Comment by LigH-de** [comment]
Which requires a previous `source "$LOCALBUILDDIR"/media-suite_helper.sh` in an interactive console. But yes, it works, thanks.

**Comment by LigH-de** [comment]
So far I only found the patterns `(B` and `]0;` to be missed. Here a short log from a run which was supposed to compile only uvg266.

[compile.log](https://github.com/m-ab-s/media-autobuild_suite/files/8847899/compile.log)
[compile.stripped.log](https://github.com/m-ab-s/media-autobuild_suite/files/8847890/compile.stripped.log)

I tried to escape `(` and `]` with backslashes in the replace string, as I found discussed in the web, but that did not create the desired results.

**Comment by LigH-de** [comment]
I created a file **build/post_suite.sh** to test some RegEx substitutions, and this appears to work for me:

```bash
#!/bin/bash
sed -r "s/\x1b[[(][0-9;?]*[a-zA-Z]|\x1b\][0-9];//g" compile.log > compile.stripped.log
```
I learned that `[` and `(` need no escape when they are inside a `[`list`]`. Thanks to the [GNU sed live editor](https://sed.js.org/)! 😄 

Your choice whether you want to integrate it.

**Comment by 1480c1** [comment]
changes added as 06070a399bf1846e3a01c7bc5f931fcea112ba1a
