### ISSUE TITLE
mingw64 main

### ISSUE THREAD

**Issue by kevev** [m-ab-s/media-autobuild_suite#2206]
``` libwebp git  ................................................ [Up-to-date]
├ FFmpeg and related apps will depend on OpenCL.dll
  Running git update for OpenCL-Headers...
OpenCL-Headers git  ......................................... [Up-to-date]
  Running git clone for leptonica...
┌ leptonica git  ...................................... [Recently updated]
├ Running uninstall...
├ Running autogen...
├ Running configure...
├ Running make...
├ Running install...
├ /local32/lib/liblept.a  .................................... [Not found]
└ leptonica-git  ................................................ [Failed]

Try deleting '/build/leptonica-git' and start the script again.
If you are sure there are no dependencies, <Enter> to continue building.
Close this window if you wish to stop building.
```

I have removed leptonica-git dir and run build script agian. Same error.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8847988/logs.zip)

**Comment by patrickenfuego** [comment]
I ran into this issue earlier today. Let it build past tesseract (even though I thought it was a dep for tesseract?) and then rerun it from the start. For whatever reason, that fixed the issue for me.

**Comment by kevev** [comment]
I ran it again and now have this error:

├ Running rust.install...
Likely error (tail of the failed operation logfile):
  running: "ccache" "gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-m32" "-mthreads" "-mtune=generic" "-O2" "-pipe" "-I" "src/zlib" "-DZ_SOLO" "-o" "C:\\media-autobuild_suite\\build\\cargo-c-git\\target\\release\\build\\libz-sys-4d66c68cf692c559\\out\\lib\\src/zlib/compress.o" "-c" "src/zlib/compress.c"
  exit code: 1

  --- stderr


  error occurred: Command "ccache" "gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-m32" "-mthreads" "-mtune=generic" "-O2" "-pipe" "-I" "src/zlib" "-DZ_SOLO" "-o" "C:\\media-autobuild_suite\\build\\cargo-c-git\\target\\release\\build\\libz-sys-4d66c68cf692c559\\out\\lib\\src/zlib/adler32.o" "-c" "src/zlib/adler32.c" with args "gcc" did not execute successfully (status code exit code: 1).


error: failed to compile `cargo-c v0.9.10+cargo-0.62 (C:\media-autobuild_suite\build\cargo-c-git)`, intermediate artifacts can be found at `C:\media-autobuild_suite\build\cargo-c-git\target`
rust.install failed. Check C:/media-autobuild_suite/build/cargo-c-git/ab-suite.rust.install.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach C:\media-autobuild_suite\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by kevev** [comment]
All good now with latest master.

**Comment by 1480c1** [comment]
Seems the library name was changed in https://github.com/DanBloomberg/leptonica/commit/29a33a364848f67d0fc102fda6d4ed858d7470b3

**Comment by 1480c1** [comment]
pushed https://github.com/m-ab-s/media-autobuild_suite/commit/6eced1f775052e9dc3bd0b2620ada5a5143d33cb
