### ISSUE TITLE
Newtek NDI help build please

### ISSUE THREAD

**Issue by kevev** [m-ab-s/media-autobuild_suite#2209]
Hello, I know that NDI is not included for licensing reasons. Just hoping someone can help me anyways.  I am attempting to build ffmpeg to include --enable-libndi

I am receiving this error on make.

C:\media-autobuild_suite\msys64\mingw64\bin\ar.exe: libavdevice/libndi_newtek_dec.o: No such file or directory
make: *** [/build/ffmpeg-git/ffbuild/library.mak:38: libavdevice/libavdevice.a] Error 1
make: *** Waiting for unfinished jobs....
AR	libavdevice/libavdevice.a
C:\media-autobuild_suite\msys64\mingw64\bin\ar.exe: libavdevice/libndi_newtek_dec.o: No such file or directory
make: *** [/build/ffmpeg-git/ffbuild/library.mak:38: libavdevice/libavdevice.a] Error 1

**Comment by 1480c1** [comment]
Not really able to help with this one since in the first place, FFmpeg lacks the source code for newtek NDI, and you didn't specify how you tried to add support for `--enable-libndi` to your build

**Comment by kevev** [comment]
I added this patch to ffmpeg source: https://framagit.org/tytan652/ffmpeg-ndi-patch/-/raw/master/master_Revert-lavd-Remove-libndi_newtek.patch

I added to media-suite_compile.sh as I was having issue with  /build/ffmpeg_extra.sh not working and /build/ffmpeg_options.txt was not being created.

FFMPEG_BASE_OPTS=("--pkg-config=pkgconf" --pkg-config-flags="--keep-system-libs --keep-system-cflags --static" "--cc=$CC" "--cxx=$CXX" "--ld=$CXX" --enable-nonfree --enable-librist --enable-libndi_newtek)

Also I copied the contents of C:\NDI-5-SDK/lib/ to C:\media-autobuild_suite\msys64\mingw64\lib/ .
And I copied the contents of C:\NDI-5-SDK\Include/ to C:\media-autobuild_suite\msys64\mingw64\include/
