### ISSUE TITLE
Vapoursynth R59 

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2211]
Hope that the patches for FFmpeg works with this release

https://github.com/vapoursynth/vapoursynth/releases

r59:
fixed several convolution crashes
fixed averageframes weights with float input
fixed rare cython memory leak on error

r58:
updated the supported python versions to 3.10 and 3.8
updated visual studio 2022 runtime version
updated projects to visual studio 2022
updated zimg to 3.0.4
out of range requests getFrame() are now properly rejected instead of possibly crashing later
removed the prefer_props argument from resizers, trying to use it will result in a warning message
fixed certain expressions failing to compile in expr filter
fixed averageframes not respecting scenechange property (sekrit-twc)
added bob filter (sekrit-twc)
added support for separable convolutions and optimized convolution in general (sekrit-twc)
fixed audionode get_frame() in python
enabled cache for nodes with no registered dependencies, this means nodes returned by getoutput won't need to manually have the cache enabled if they have no filter

**Comment by hydra3333** [comment]
Well, on my non-MABS ffmpeg build I updated the python3 libs to 3.10.4 and vapoursynth to R59 and ffmpeg x64 seems to build and work, so it should here too I guess.

I do like MABS, I come here relatively often to check updates and whatnot.
