### ISSUE TITLE
libaacs-git

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2212]
fatal: not a git repository (or any of the parent directories): .git
fatal: not in a git directory
Likely error (tail of the failed operation logfile):
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_fetch
++ git rev-parse --git-dir
fatal: not a git repository (or any of the parent directories): .git
+ [[ -f /shallow ]]
+ unshallow=
+ git fetch --all -Ppft
fatal: not a git repository (or any of the parent directories): .git
+ git remote set-head -a origin
fatal: not a git repository (or any of the parent directories): .git
git.fetch failed. Check D:/MABS-ffmpeg/build/libaacs-git/ab-suite.git.fetch.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oM7l.zip

**Comment by 1480c1** [comment]
Can you try deleting build/libaacs-git if it's there and rerun?

**Comment by Barough** [comment]
Tested that already and it didn't work. :(

**Comment by Barough** [comment]
I'll give that a try in a few minutes

**Comment by Barough** [comment]
Still the same thing :(

fatal: not a git repository (or any of the parent directories): .git
fatal: not in a git directory
Likely error (tail of the failed operation logfile):
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_fetch
++ git rev-parse --git-dir
fatal: not a git repository (or any of the parent directories): .git
+ [[ -f /shallow ]]
+ unshallow=
+ git fetch --all -Ppft
fatal: not a git repository (or any of the parent directories): .git
+ git remote set-head -a origin
fatal: not a git repository (or any of the parent directories): .git
git.fetch failed. Check D:/MABS-ffmpeg/build/libbdplus-git/ab-suite.git.fetch.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ouXO.zip

**Comment by Barough** [comment]
Doesn't make any difference here what i do........ i've added exception to the suite in my AV. Deleted files/folders related to libaacs in the suite folders on my hdd...... libaacs just dont wanna compile.

Got a friend to have a go also with mabs and he tested to build ffmpeg with default full 'settings' and he also tested with my 'media-autobuild_suite.ini' and 'ffmpeg_options.txt' files and it's the same....... libaacs don't wanna compile.

**Comment by 1480c1** [comment]
Hmm, can you try opening mintty.lnk and running
```bash
. /build/media-suite_helper.sh
do_vcs "https://code.videolan.org/videolan/libaacs.git"
```
and see if that fails.

If it does, can you then go into `build/media-suite_helper.sh` and look for `do_vcs()` around line 229, and change the surrounding to look like

```bash
do_vcs() {
    set -x
    local vcsURL=${1#*::} vcsFolder=$2 vcsCheck=("${_check[@]}")
    local vcsBranch=${vcsURL#*#} ref=origin/HEAD
    local deps=("${_deps[@]}") && unset _deps
```

and rerun the first two commands, but change the second one to have `&>log` at the end and upload the `log` file to github, if you need to find where it is on your machine, you can run `cygpath.exe -m $(realpath log)`

That might give me more of a hint as to where it's going wrong when compared to my setup where it clones and builds it fine

**Comment by Barough** [comment]
That worked fine

$ . /build/media-suite_helper.sh
do_vcs "https://code.videolan.org/videolan/libaacs.git"
++ git rev-parse --git-dir
+ [[ -f .git/shallow ]]
+ unshallow=
+ git fetch --all -Ppft
Fetching origin
+ git remote set-head -a origin
origin/HEAD set to master
┌ libaacs git  ........................................ [Recently updated]
NetRanger@DESKTOP-54U99HF /build/libaacs-git
$

**Comment by Barough** [comment]
Looked at the mabs window now and libaacs compiled but then the 'fatal' thingy above happens

Latest set of logs
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8934561/logs.zip)

Looks like the auto log upload to https://0x0.st doesn't work any longer.

**Comment by 1480c1** [comment]
> Looks like the auto log upload to https://0x0.st/ doesn't work any longer.

https://github.com/m-ab-s/media-autobuild_suite/commit/a1270109df0f5c471f796662e289cbad00322f5c

accidentally got broken when vvenc/dec stuff got merged

> Looked at the mabs window now and libaacs compiled but then the 'fatal' thingy above happens

seems based on the logs, it's failing at libbdplus-git now instead of libaacs

Try the same stuff, but do `do_vcs "https://code.videolan.org/videolan/libbdplus.git"` instead

**Comment by Barough** [comment]
NetRanger@DESKTOP-54U99HF /trunk
$ . /build/media-suite_helper.sh
do_vcs "https://code.videolan.org/videolan/libbdplus.git"
fatal: not a git repository (or any of the parent directories): .git
fatal: not in a git directory
++ git rev-parse --git-dir
fatal: not a git repository (or any of the parent directories): .git
+ [[ -f /shallow ]]
+ unshallow=
+ git fetch --all -Ppft
fatal: not a git repository (or any of the parent directories): .git
+ git remote set-head -a origin
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
  Running git update for libbdplus in libbdplus-git
++ vcs_get_latest_tag origin/HEAD
++ case $1 in
++ false
++ echo origin/HEAD
+ git checkout --no-track -fB ab-suite origin/HEAD
fatal: not a git repository (or any of the parent directories): .git
+ git log --oneline --no-merges --no-color -n 1
+ tee /dev/null
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
libbdplus git  .............................................. [Up-to-date]

**Comment by Barough** [comment]
Im off to bed now. It's 3am here

**Comment by 1480c1** [comment]
Good night, pushed https://github.com/m-ab-s/media-autobuild_suite/commit/a730be243696aaa8166519f909c322af433b3fdd and maybe it might fix it
