### ISSUE TITLE
exhale errors

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2215]
┌ exhale git  ............................................ [Updates found]
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
D:/mabs/build/exhale-git/src/lib/exhaleEnc.cpp:2191:22: warning: 'unsigned int exhaleInitEncoder(ExhaleEncAPI*, unsigned char*, uint32_t*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
D:/mabs/build/exhale-git/src/lib/exhaleEnc.cpp:2200:22: error: function 'unsigned int exhaleEncodeLookahead(ExhaleEncAPI*)' definition is marked dllimport
 2200 | EXHALE_DECL unsigned exhaleEncodeLookahead (ExhaleEncAPI* exhaleEnc)
      |                      ^~~~~~~~~~~~~~~~~~~~~
D:/mabs/build/exhale-git/src/lib/exhaleEnc.cpp:2200:22: warning: 'unsigned int exhaleEncodeLookahead(ExhaleEncAPI*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
D:/mabs/build/exhale-git/src/lib/exhaleEnc.cpp:2208:22: error: function 'unsigned int exhaleEncodeFrame(ExhaleEncAPI*)' definition is marked dllimport
 2208 | EXHALE_DECL unsigned exhaleEncodeFrame (ExhaleEncAPI* exhaleEnc)
      |                      ^~~~~~~~~~~~~~~~~
D:/mabs/build/exhale-git/src/lib/exhaleEnc.cpp:2208:22: warning: 'unsigned int exhaleEncodeFrame(ExhaleEncAPI*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
ninja: build stopped: subcommand failed.
build failed. Check D:/mabs/build/exhale-git/build-32bit/ab-suite.build.log
This isn't required for anything so we can move on.
├ Running install...
Likely error (tail of the failed operation logfile):
D:/mabs/build/exhale-git/src/lib/exhaleEnc.cpp:2191:22: warning: 'unsigned int exhaleInitEncoder(ExhaleEncAPI*, unsigned char*, uint32_t*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
D:/mabs/build/exhale-git/src/lib/exhaleEnc.cpp:2200:22: error: function 'unsigned int exhaleEncodeLookahead(ExhaleEncAPI*)' definition is marked dllimport
 2200 | EXHALE_DECL unsigned exhaleEncodeLookahead (ExhaleEncAPI* exhaleEnc)
      |                      ^~~~~~~~~~~~~~~~~~~~~
D:/mabs/build/exhale-git/src/lib/exhaleEnc.cpp:2200:22: warning: 'unsigned int exhaleEncodeLookahead(ExhaleEncAPI*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
D:/mabs/build/exhale-git/src/lib/exhaleEnc.cpp:2208:22: error: function 'unsigned int exhaleEncodeFrame(ExhaleEncAPI*)' definition is marked dllimport
 2208 | EXHALE_DECL unsigned exhaleEncodeFrame (ExhaleEncAPI* exhaleEnc)
      |                      ^~~~~~~~~~~~~~~~~
D:/mabs/build/exhale-git/src/lib/exhaleEnc.cpp:2208:22: warning: 'unsigned int exhaleEncodeFrame(ExhaleEncAPI*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
ninja: build stopped: subcommand failed.
install failed. Check D:/mabs/build/exhale-git/build-32bit/ab-suite.install.log
This isn't required for anything so we can move on.
├ Stripping...
└ exhale-git  .................................................. [Updated]

**Comment by 1480c1** [comment]
Perhaps could have been caused by https://gitlab.com/ecodis/exhale/-/merge_requests/8

**Comment by Barough** [comment]
Made an issue report over at exhale

**Comment by jprjr** [comment]
Hi all, just leaving a comment here (and in the Exhale gitlab) to let you know I'm taking a look

**Comment by jprjr** [comment]
For reference, opened an MR that should correct the issue: https://gitlab.com/ecodis/exhale/-/merge_requests/9

**Comment by jprjr** [comment]
MR is merged, exhale should build properly now

**Comment by Barough** [comment]
Thnx for the fix. exhale compile without any errors now.
