### ISSUE TITLE
Request: Is it possible to allow users to set different CFlags for different programs?

### ISSUE THREAD

**Issue by lzy0702** [m-ab-s/media-autobuild_suite#2216]
e.g. opus cannot be compiled with -Ofast (will need "--enable-float-approx"), and I want to compile other programs with -Ofast for best performance. This cannot be done by changing the CFlags in the bat file only.

**Comment by 1480c1** [comment]
This could possibly be done using the `_extra` script and exporting your own CFLAGS for a certain project or alternatively removing certain flags from CFLAGS for certain projects as well.

It will require you to know how to use and script in bash and also know what tools to use to do so. I cannot really hand hold you on that point. Do keep in mind if you do decide to use custom CFLAGS, it will be harder to provide support for any potential issues that might arise from compile or runtime
