### ISSUE TITLE
[Help Wanted] Want to build GPAC/Mp4box v2.0

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2220]
Wanna try and build GPAC/Mp4box v2.0 with mabs.

I know it has to be done with help of 'gpac_extra.sh', but i dont know what to exactly put into it.

Do i need to use '_pre_vcs' or '_post_vcs' or????

The GPAC 2.0 commit in question is this
https://github.com/gpac/gpac/commit/418db4149af78773815b5f6a7030a120037ba140

**Comment by 1480c1** [comment]
probably the thing to do would be
```bash
_pre_vcs() {
    ref=418db4149af78773815b5f6a7030a120037ba140
}
```
