### ISSUE TITLE
[mingw64] [vulkan-loader] build errors

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2222]
21:06:10 ┌ vulkan-loader git  ........................ [Recently updated]
21:06:10 ├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
21:06:13 ├ Running dependencies...
21:06:45 ├ Installing Vulkan-Headers...
21:06:45 ├ Running uninstall...
21:06:45 ├ Running cmake...
21:06:46 ├ Running build...
21:06:46 ├ Running install...
21:06:48 ├ Building Vulkan-Loader...
21:06:48 ├ Running cmake...
21:06:57 ├ Running build...
Likely error (tail of the failed operation logfile):
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml  -ID:/ffmpeg-autobuild/build/vulkan-loader-git/build-64bit/loader -ID:/ffmpeg-autobuild/local64/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknowninja: fatal: GetOverlappedResult: ▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒.

n_ext_chain_masm.asm.obj D:/ffmpeg-autobuild/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
[1/20] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml  -ID:/ffmpeg-autobuild/build/vulkan-loader-git/build-64bit/loader -ID:/ffmpeg-autobuild/local64/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj D:/ffmpeg-autobuild/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.

[logs.zip](https://0x0.st/oSN2.zip)

**Comment by 1480c1** [comment]
rebased the patches
