### ISSUE TITLE
[QUESTION/REQUEST] libFLAC.dll & m-ab-s

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2224]
Don't know if this have been asked about earlier or no

Is it possible for the suite to output libFLAC.dll files or?

**Comment by 1480c1** [comment]
it's possible, but you would need to modify the compile.sh file yourself, it would probably entail modifying the `_check=` line to not look for `libFLAC.a` and such and adding `--enable-shared` to the do_separate_confmakeinstall line

**Comment by Barough** [comment]
That's way way over my knowledge. Thanks for the info.

Sad that there isn't an easy solution. Would have been great to both get the flac binary and the dll.file.
