### ISSUE TITLE
Key Import errors when building in Windows Sandbox (win10 x64)

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#2227]
Hello.

I thought I'd use MABS in Windows Sandbox so that my PC remained "clean".
I enabled the Windows Sandbox feature and created a Sandbox config with read-write folder shared with the host and then ran Sandbox.
I extracted the MABS zip from git into the shared folder and then double-clicked on media-autobuild_suite.bat
It asked me a lot of questions (great !) then started to download stuff and then yielded a bunch of "Could not import development key" errors and then stopped.  I tried typing "Y" and Enter but to no avail.
Since I had answered Y to upload logs, I hope you have them.

Any advice on how to get it to work in Windows Sandbox would be greatly appreciated.
(I hoped/assumed registry keys aren't used, since they won't persist across Sandbox restarts unlike files in the shared folder which are saved).
![MABS-err-01](https://user-images.githubusercontent.com/10749357/175814677-10cc5a95-0267-4f8f-a92d-266eaf4683ac.jpg)
![MABS-err-02](https://user-images.githubusercontent.com/10749357/175814698-ad588d1a-9d2c-4121-a474-9de54d5d12a8.jpg)

**Comment by hydra3333** [comment]
Hmm, unsure if this helps:

I enabled hyper-v etc in Win10 x64, downloaded the "Windows Development Environment" free hyper-v VM and ran MABS in that and it got past the key stuff passed OK.

**Comment by 1480c1** [comment]
If it's a "shared" folder, depending on how it's shared, it can have issues running msys2, msys2 does not run well when you try to run it from a smb share for example

**Comment by hydra3333** [comment]
OK I'll pop it onto the sandbox C: drive (copy the shared drive as a part of the sandbox initialization process) and try again.
Thank you.

**Comment by hydra3333** [comment]
> OK I'll pop it onto the sandbox C: drive (copy the shared drive as a part of the sandbox initialization process) and try again. 

Yes, that seemed to work. Go figure.

Thank you.

**Comment by hydra3333** [comment]
for posterity, here's the .wsb for the sandbox config
```
<Configuration>
  <VGpu>Enable</VGpu>
  <Networking>Default</Networking>
  <PrinterRedirection>Enable</PrinterRedirection>
  <ClipboardRedirection>Default</ClipboardRedirection>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>C:\software</HostFolder>
      <SandboxFolder>C:\Users\WDAGUtilityAccount\Desktop\software</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
    <MappedFolder>
      <HostFolder>C:\software\WindowsSandbox</HostFolder>
      <SandboxFolder>C:\Users\WDAGUtilityAccount\Desktop\WindowsSandbox</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
    <MappedFolder>
      <HostFolder>D:\VM</HostFolder>
      <SandboxFolder>C:\Users\WDAGUtilityAccount\Desktop\D_VM</SandboxFolder>
      <ReadOnly>false</ReadOnly>
    </MappedFolder>
    <MappedFolder>
      <HostFolder>D:\VM\MABS</HostFolder>
      <SandboxFolder>C:\VM_MABS</SandboxFolder>
      <ReadOnly>false</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <LogonCommand>
    <Command>C:\users\WDAGUtilityAccount\Desktop\software\WindowsSandbox\Setup.bat</Command>
  </LogonCommand>
</Configuration>
```

and here's the setup.bat, a roughie but it works

@echo on

mkdir c:\MABS
c:
cd C:\MABS
xcopy C:\VM_MABS\*.* C:\MABS\ /e /v /f /h /r /y

set create_shortcut_SCRIPT="%TEMP%\create_vscode_desktop_link_%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%.vbs"
del %create_shortcut_SCRIPT%
echo Set oWS = WScript.CreateObject("WScript.Shell") >> %create_shortcut_SCRIPT%
echo sLinkFile = "%USERPROFILE%\Desktop\VScode.lnk" >> %create_shortcut_SCRIPT%
echo Set oLink = oWS.CreateShortcut(sLinkFile) >> %create_shortcut_SCRIPT%
echo oLink.TargetPath = "C:\Users\WDAGUtilityAccount\Desktop\software\vscode\Microsoft VS Code\Code.exe" >> %create_shortcut_SCRIPT%
echo oLink.Arguments = "" >> %create_shortcut_SCRIPT%
echo oLink.Description = "VScode" >> %create_shortcut_SCRIPT%
echo 'oLink.HotKey = "" >> %create_shortcut_SCRIPT%
echo 'oLink.IconLocation = "" >> %create_shortcut_SCRIPT%
echo 'oLink.WindowStyle = "" >> %create_shortcut_SCRIPT%
echo 'oLink.WorkingDirectory = "" >> %create_shortcut_SCRIPT%
echo oLink.Save >> %create_shortcut_SCRIPT%
cscript /nologo %create_shortcut_SCRIPT%
del %create_shortcut_SCRIPT%

REM goto :eof

set create_shortcut_SCRIPT="%TEMP%\create_MABS_desktop_link_%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%.vbs"
del %create_shortcut_SCRIPT%
echo Set oWS = WScript.CreateObject("WScript.Shell") >> %create_shortcut_SCRIPT%
echo sLinkFile = "%USERPROFILE%\Desktop\VM_MABS.lnk" >> %create_shortcut_SCRIPT%
echo Set oLink = oWS.CreateShortcut(sLinkFile) >> %create_shortcut_SCRIPT%
echo oLink.TargetPath = "C:\VM_MABS\" >> %create_shortcut_SCRIPT%
echo oLink.Arguments = "" >> %create_shortcut_SCRIPT%
echo oLink.Description = "VM_MABS" >> %create_shortcut_SCRIPT%
echo 'oLink.HotKey = "" >> %create_shortcut_SCRIPT%
echo 'oLink.IconLocation = "" >> %create_shortcut_SCRIPT%
echo 'oLink.WindowStyle = "" >> %create_shortcut_SCRIPT%
echo 'oLink.WorkingDirectory = "" >> %create_shortcut_SCRIPT%
echo oLink.Save >> %create_shortcut_SCRIPT%
cscript /nologo %create_shortcut_SCRIPT%
del %create_shortcut_SCRIPT%

REM goto :eof

set create_shortcut_SCRIPT="%TEMP%\create_MABS_desktop_link_%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%.vbs"
del %create_shortcut_SCRIPT%
echo Set oWS = WScript.CreateObject("WScript.Shell") >> %create_shortcut_SCRIPT%
echo sLinkFile = "%USERPROFILE%\Desktop\MABS.lnk" >> %create_shortcut_SCRIPT%
echo Set oLink = oWS.CreateShortcut(sLinkFile) >> %create_shortcut_SCRIPT%
echo oLink.TargetPath = "C:\MABS\" >> %create_shortcut_SCRIPT%
echo oLink.Arguments = "" >> %create_shortcut_SCRIPT%
echo oLink.Description = "MABS" >> %create_shortcut_SCRIPT%
echo 'oLink.HotKey = "" >> %create_shortcut_SCRIPT%
echo 'oLink.IconLocation = "" >> %create_shortcut_SCRIPT%
echo 'oLink.WindowStyle = "" >> %create_shortcut_SCRIPT%
echo 'oLink.WorkingDirectory = "" >> %create_shortcut_SCRIPT%
echo oLink.Save >> %create_shortcut_SCRIPT%
cscript /nologo %create_shortcut_SCRIPT%
del %create_shortcut_SCRIPT%

REM goto :eof

explorer.exe "C:\MABS\"

goto :eof
