### ISSUE TITLE
[x64] ffmpeg 'git am' patch issues

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2228]
This is weird....... the previous time so did the compile went through without any 'git am' patch issues. This was just b4 the latest 'rav1e' issue.

┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
        Patch could not be applied with `git am`. Continuing without patching.
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ ffmpeg-git  .................................................. [Updated]

Have something changed again or????

**Comment by Barough** [comment]
Any news/info?

**Comment by 1480c1** [comment]
I think these are solved as they are building fine for me 
```none
 V..... libsvtav1            SVT-AV1(Scalable Video Technology for AV1) encoder (codec av1)
 V..... libsvt_hevc          SVT-HEVC(Scalable Video Technology for HEVC) encoder (codec hevc)
 V..... libsvt_vp9           SVT-VP9(Scalable Video Technology for VP9) encoder (codec vp9)
```
