### ISSUE TITLE
media-autobuild_suite error in rav1e

### ISSUE THREAD

**Issue by ArmendarizOscar** [m-ab-s/media-autobuild_suite#2229]
When compiling media-autobuild_suite, it throws me an error when compiling the .exe of the videos, here I leave the error report [logs.zip] (https://0x0.st/oSwQ.zip) 
 it tells me error: I don't know was able to compile `rav1e` (https://user-images.githubusercontent.com/103696464/176077788-4e2f362c-cbb5-43e7-b643-97a4eba3ec76.jpg) please help me with this soon I would really appreciate it.

**Comment by 1480c1** [comment]
can you try pulling the latest suite and rerunning? the latest commit or something should have resolved it, you may need to delete build/rav1e-git and run

**Comment by forthyen** [comment]
rav1e issue is closed now, but not vvenc

**Comment by ArmendarizOscar** [comment]
Hello thanks for the help if what you wrote worked for me.
