### ISSUE TITLE
media-autobuild_suite  error in C:/build_suite/build/vvenc-git/build-64bit/ab-suite.build.log

### ISSUE THREAD

**Issue by ArmendarizOscar** [m-ab-s/media-autobuild_suite#2231]
Hello i got an error with Check C:/build_suite/build/vvenc-git/build-64bit/ab-suite.build.log
I would like to know what I should do. Here I leave the image of the error   
![error 2]  (https://user-images.githubusercontent.com/103696464/176164727-f6e4022a-d648-4348-b06a-9f2dfb4e253f.jpg)
here is the error log (https://0x0.st/oSxR.zip) .
I would like to know what I should do, I would appreciate your help.

**Comment by 1480c1** [comment]
Can you try again? I think this would have been solved by https://github.com/m-ab-s/media-autobuild_suite/commit/a5e0bbaa5107e7566e99aab2bd0f9caeb0a72234
