### ISSUE TITLE
gpac compile issue

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2232]
┌ gpac git  ........................................... [Recently updated]
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
make[2]: Entering directory '/build/gpac-git/build-32bit/applications/gpac'
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc\libgpac_static.a(quickjs-libc.o):quickjs-libc.c:(.text+0xd42): undefined reference to `pipe'
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc\libgpac_static.a(quickjs-libc.o):quickjs-libc.c:(.text+0x56d0): undefined reference to `pipe'
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc\libgpac_static.a(quickjs-libc.o):quickjs-libc.c:(.text+0x5741): undefined reference to `pipe'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:61: gpac.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/build-32bit/applications/gpac'
make[1]: *** [Makefile:14: apps] Error 2
make[1]: Leaving directory '/build/gpac-git/build-32bit/applications'
make: *** [Makefile:14: all] Error 2
make failed. Check D:/mabs/build/gpac-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oS6Z.zip
Copy and paste [logs.zip](https://0x0.st/oS6Z.zip) in the GitHub issue.

**Comment by 1480c1** [comment]
probably fixed upstream

**Comment by Barough** [comment]
You beat me to it. It's fixed now. Just finished a compile rum with m-ab-s.
