### ISSUE TITLE
implement inclusion of ffmpeg vulkan filters ?

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#2235]
Hello.

If I wished to use ffmpeg's vulkan filters, I gather that one would need to build these dependencies (for static ffmpeg x64):
vulkan_loader
spirv-headers
spirv-cross
spirv-tools
shaderc  (shaderc and glslang are mutually exclusive in ffmpeg configure but you can build both dependencies)
glslang (shaderc and glslang are mutually exclusive in ffmpeg configure but you can build both dependencies)

And add these to the ffmpeg configure
--enable-vulkan 
--enable-libglslang (or, mutually exclusively, --enable-libshaderc which causes ffmpeg to fail at runtime)
--enable-filter=scale_vulkan 
--enable-filter=avgblur_vulkan 
--enable-filter=chromaber_vulkan 
--enable-filter=overlay_vulkan 
--enable-filter=blend_vulkan 
--enable-filter=flip_vulkan 
--enable-filter=gblur_vulkan 
--enable-filter=hflip_vulkan 
--enable-filter=transpose_vulkan 
--enable-filter=vflip_vulkan 
--disable-libplacebo (for me, enabling this causes ffmpeg configure to abort after I enable libglslang)

It seems a fair bet that when selecting vulkan to build into ffmpeg, the user would also hope/assume/expect that the ffmpeg vulkan filters get built/embedded too.

**Do you think it would be possible to implement inclusion of ffmpeg vulkan filters in MABS ?**

... in a separate build system, I have tried to build ffmpeg with shaderc enabled instead of glslang.
So far, shaderc is somehow flagged in the ffmpeg build process as shared (perhaps in shaderc.pc)
and so ffmpeg looks for a dll at runtime and aborts even though ffmpeg is built as notionally static.
If trying to use the static shaderc .a libraries instead, the ffmpeg build process aborts as unable to find shaderc.
Using glslang instead of shaderc does appear to cause static ffmpeg to not crash immediately at runtime (I hope).

Sorry, I don't know how to do a PR.

**Comment by 1480c1** [comment]
@hydra3333 afaik, the vulkan filters are enabled in FFmpeg https://github.com/m-ab-s/media-autobuild_suite/blob/33c06d4a2b3beae5adcdca55b1bf68f1ec024cd5/media-autobuild_suite.bat#L131

last time I checked (around a week or two ago), the filters did work on my machine

**Comment by hydra3333** [comment]
Oh, OK fair enough.

I had to do the --enable stuff to get these
`ffmpeg -filters`

```
 ... avgblur_vulkan    V->V       Apply avgblur mask to input video
 ..C blend_vulkan      VV->V      Blend two video frames in Vulkan
 ... chromaber_vulkan  V->V       Offset chroma of input video (chromatic aberration)
 ... flip_vulkan       V->V       Flip both horizontally and vertically
 ... gblur_vulkan      V->V       Gaussian Blur in Vulkan
 ... hflip_vulkan      V->V       Horizontally flip the input video in Vulkan
 ... overlay_vulkan    VV->V      Overlay a source on top of another
 ... scale_vulkan      V->V       Scale Vulkan frames
 ... transpose_vulkan  V->V       Transpose Vulkan Filter
 ... vflip_vulkan      V->V       Vertically flip the input video in Vulkan
```
