### ISSUE TITLE
[mingw64] [vulkan-loader] Building vulkan-loader fails because appmodel.h is not found

### ISSUE THREAD

**Issue by crhepner** [m-ab-s/media-autobuild_suite#2236]
Building vulkan-loader failed because a file called appmodel.h could not be found.  I can't find any file with that name in /build/vulkan-loader-git/, /local64/include/, or any of their subfolders.

``` bash
┌ vulkan-loader git  .................................. [Recently updated]
├ Running uninstall...
├ Running dependencies...
├ Installing Vulkan-Headers...
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ Building Vulkan-Loader...
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
      |           ^~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
[1/4] Building C object loader/CMakeFiles/vulkan.dir/loader_windows.c.obj
FAILED: loader/CMakeFiles/vulkan.dir/loader_windows.c.obj
C:\ab-suite-20210823\msys64\mingw64\bin\ccache.exe  gcc -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -D_GNU_SOURCE -IC:/ab-suite-20210823/build/vulkan-loader-git/loader -IC:/ab-suite-20210823/build/vulkan-loader-git/loader/generated -IC:/ab-suite-20210823/build/vulkan-loader-git/build-64bit/loader -isystem C:/ab-suite-20210823/local64/include -mthreads -mtune=generic -O2 -pipe -DSTRSAFE_NO_DEPRECATE -O3 -DNDEBUG -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wno-stringop-truncation -Wno-stringop-overflow -Wimplicit-fallthrough=0 -Wpointer-arith -std=c99 -MD -MT loader/CMakeFiles/vulkan.dir/loader_windows.c.obj -MF loader\CMakeFiles\vulkan.dir\loader_windows.c.obj.d -o loader/CMakeFiles/vulkan.dir/loader_windows.c.obj -c C:/ab-suite-20210823/build/vulkan-loader-git/loader/loader_windows.c
C:/ab-suite-20210823/build/vulkan-loader-git/loader/loader_windows.c:54:10: fatal error: appmodel.h: No such file or directory
   54 | #include <appmodel.h>
      |          ^~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
build failed. Check C:/ab-suite-20210823/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oQJD.zip
Copy and paste [logs.zip](https://0x0.st/oQJD.zip) in the GitHub issue.
```

[logs.zip](https://0x0.st/oQJD.zip)

**Comment by Barough** [comment]
Same here
https://0x0.st/oQy5.zip

**Comment by Biswa96** [comment]
I have sent a patch to mingw-w64 mailing list to add appmodel.h header file. Please follow this thread https://sourceforge.net/p/mingw-w64/mailman/message/37677890/

For a quick fix, you can copy the header files from that patch file.

**Comment by Biswa96** [comment]
The patch has been added in this commit https://sourceforge.net/p/mingw-w64/mingw-w64/ci/2918ac20006f0a1ddab2dcf52f7eaf7dc286a094/

**Comment by crhepner** [comment]
Thanks!  Should I put the header files in /msys64/mingw64/include/, or do they go somewhere else?

**Comment by 1480c1** [comment]
probably in `/msys64/mingw64/include` for now

**Comment by Barough** [comment]
@Biswa96 Thnx for the fix. :)

**Comment by crhepner** [comment]
I can confirm that putting both header files in /msys64/mingw64/include fixes the problem.

**Comment by ultrasound1372** [comment]
@Barough For now you can get the raw files [here](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/2918ac20006f0a1ddab2dcf52f7eaf7dc286a094/tree/mingw-w64-headers/include/appmodel.h?format=raw) and [here](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/2918ac20006f0a1ddab2dcf52f7eaf7dc286a094/tree/mingw-w64-headers/include/minappmodel.h?format=raw)

**Comment by Barough** [comment]
@ultrasound1372 Thnx :)

**Comment by herrbasan** [comment]
> @Barough For now you can get the raw files [here](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/2918ac20006f0a1ddab2dcf52f7eaf7dc286a094/tree/mingw-w64-headers/include/appmodel.h?format=raw) and [here](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/2918ac20006f0a1ddab2dcf52f7eaf7dc286a094/tree/mingw-w64-headers/include/minappmodel.h?format=raw)

I dropped those in, yet I can't get past the vulkan compile

`Likely error (tail of the failed operation logfile):
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml  -IC:/ffbuild/build/vulkan-loader-git/build-64bit/loader -IC:/ffbuild/local64/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj C:/ffbuild/build/vulkan-loader-git/loader/unknown_ext_ninja: fatal: GetOverlappedResult: The handle is invalid.

chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
[1/20] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml  -IC:/ffbuild/build/vulkan-loader-git/build-64bit/loader -IC:/ffbuild/local64/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj C:/ffbuild/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check C:/ffbuild/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
`
https://0x0.st/oQkF.zip

**Comment by ycwan** [comment]
After I added the 2 files MABS still has error when it runs build while updating vulkan-loader
![image](https://user-images.githubusercontent.com/33979551/178061529-7759f843-af06-47d0-b6ff-ba3f4edee16b.png)

![image](https://user-images.githubusercontent.com/33979551/178061436-93d87076-e284-4de7-b9e0-e7c710e10fb6.png)

03:27:22 AviSynthPlus git ................................. [Up-to-date]
03:27:28 Running git update for vulkan-loader...
03:27:31 ┌ vulkan-loader git ........................ [Recently updated]
03:27:32 ├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
Patch could not be applied with git am. Continuing without patching.
03:27:34 ├ Running dependencies...
03:27:52 ├ Installing Vulkan-Headers...
03:27:52 ├ Running uninstall...
03:27:52 ├ Running cmake...
03:27:53 ├ Running build...
03:27:53 ├ Running install...
03:27:56 ├ Building Vulkan-Loader...
03:27:57 ├ Running cmake...
03:28:00 ├ Running build...
Likely error (tail of the failed operation logfile):
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -IC:/MinGW-w64/build/vulkan-loader-git/build-64bit/loader -IC:/MinGW-w64/local64/include -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj C:/MinGW-w64/build/vulkan-loader-git/loadeninja: fatal: GetOverlappedResult: The handle is invalid.

r/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
[1/20] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -IC:/MinGW-w64/build/vulkan-loader-git/build-64bit/loader -IC:/MinGW-w64/local64/include -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj C:/MinGW-w64/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW-w64/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
03:28:00 Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oQdM.zip
Copy and paste [logs.zip](https://0x0.st/oQdM.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/oQdM.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/9074695/ab-suite.build.log)

**Comment by Ajaja** [comment]
+1 
appmodel.h and minappmodel.h in /msys64/mingw64/include files do  not work:
```21:48:41 ┌ vulkan-loader git  ........................... [Updates found]
21:48:41 ├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
21:48:43 ├ Running dependencies...
21:48:54 ├ Installing Vulkan-Headers...
21:48:55 ├ Running uninstall...
21:48:55 ├ Running cmake...
21:48:55 ├ Running build...
21:48:55 ├ Running install...
21:48:56 ├ Building Vulkan-Loader...
21:48:57 ├ Running cmake...
21:48:58 ├ Running build...
Likely error (tail of the failed operation logfile):
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml  -IE:/media-autobuild_suite/build/vulkan-loader-git/build-64bit/loader -IE:/media-autobuild_suite/local64/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/uninja: fatal: GetOverlappedResult: The handle is invalid.

nknown_ext_chain_masm.asm.obj E:/media-autobuild_suite/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
[1/20] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml  -IE:/media-autobuild_suite/build/vulkan-loader-git/build-64bit/loader -IE:/media-autobuild_suite/local64/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj E:/media-autobuild_suite/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check E:/media-autobuild_suite/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
21:48:59   Creating diagnostics file...
```

**Comment by Biswa96** [comment]
That's different error than current issue topic. We need a masm compatible assembler e.g. jwasm. Investigating 🕵️

**Comment by Biswa96** [comment]
Assembly code is disabled with patches. There were new patches added tomorrow.

**Comment by herrbasan** [comment]
Well, something has changed. Still no dice tho :)
`Likely error (tail of the failed operation logfile):
C:/ffbuild/build/vulkan-loader-git/loader/loader.c:3254:17: error: 'home' undeclared (first use in this function)
 3254 |     if (NULL != home) {
      |                 ^~~~
C:/ffbuild/build/vulkan-loader-git/loader/loader.c:3257:17: error: 'default_data_home' undeclared (first use in this function)
 3257 |     if (NULL != default_data_home) {
      |                 ^~~~~~~~~~~~~~~~~
C:/ffbuild/build/vulkan-loader-git/loader/loader.c:3260:17: error: 'default_config_home' undeclared (first use in this function)
 3260 |     if (NULL != default_config_home) {
      |                 ^~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
`

**Comment by Biswa96** [comment]
I can compile vulkan-loader from git repository and the patches from msys2's [mingw-w64-vulkan-loader][1]. That build errors may be this project specific.

[1]: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-vulkan-loader

**Comment by herrbasan** [comment]
Excuse my ignorance, but how to apply these patches ?

**Comment by Ajaja** [comment]
It's builds fine now with appmodel.h and minappmodel.h in /msys64/mingw64/include. No errors.

**Comment by Ajaja** [comment]
But mpv with  `gpu-api=vulkan` and `gpu-context=winvk` now crashes.  So, It's not a solution after all.

**Comment by Barough** [comment]
Builds fine now
