### ISSUE TITLE
Windows 10 x64 "You are running in a MSVC environment"

### ISSUE THREAD

**Issue by Victor-Freeze** [m-ab-s/media-autobuild_suite#2237]
Hi,
With the latest media-autobuild_suite I'm facing the following issue:
Whenever I try to launch media-autobuild_suite.bat either with a double click in the Windows Explorer or from the Comand Prompt, I'm getting the "You are running in a MSVC environment (cl.exe or lib.exe detected^) This is not supported." error.
I had to comment out lines 81 to 99

> rem (
> rem    where lib.exe || ^
> rem    where cl.exe || ^
> rem	VSINSTALLDIR cd .
> rem    if DEFINED VSINSTALLDIR cd .
> rem ) >nul 2>&1 && (
>     rem MSVCINSTALLED
> rem    echo ----------------------------------------------------------------------
> rem    echo. You are running in a MSVC environment (cl.exe or lib.exe detected^)
> rem    echo. This is not supported.
> rem    echo. Please run the script through a normal cmd.exe some other way.
> rem    echo.
>  rem   echo. Detected Paths:
> rem    where lib.exe 2>nul
> rem    where cl.exe 2>nul
> rem    echo %VSINSTALLDIR%
> rem    pause
> rem    exit
> rem )

in media-autobuild_suite.bat to make the script work.

**Operating System: Windows 10 Pro 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)
CMD (Command Prompt): Version 10.0.19044.1806**

**Comment by 1480c1** [comment]
Not sure what the ask here is, running in an environment where cl.exe and link.exe are accessible is considered unsupported and broken as msvc provides conflicting binaries with some binaries provided by msys2 and also some build systems may prefer msvc's compilers even when provided gcc on Windows.

**Comment by Victor-Freeze** [comment]
> Not sure what the ask here is, running in an environment where cl.exe and link.exe are accessible is considered unsupported and broken as msvc provides conflicting binaries with some binaries provided by msys2 and also some build systems may prefer msvc's compilers even when provided gcc on Windows.

Thank you for your response. From the script message, it was not clear what is the reason for the problem. And now you explained it - the presence of the Visual Studio may cause issues with the build tools.

**Comment by Biswa96** [comment]
Only presence of Visual Studio should not conflict with msys2/mingw-w64 environment. Make sure there is no presence of MSVC in PATH environment variable of m-ab-s.
