### ISSUE TITLE
highway fails to compile

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2238]
┌ highway git  ........................................ [Recently updated]
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
  539 | constexpr bool IsSigned<float16_t>() {
      |                         ^~~~~~~~~
      |                         bfloat16_t
D:/MABS-ffmpeg/build/highway-git/hwy/base.h:539:16: error: template-id 'IsSigned<<expression error> >' for 'constexpr bool hwy::IsSigned()' does not match any template declaration
  539 | constexpr bool IsSigned<float16_t>() {
      |                ^~~~~~~~~~~~~~~~~~~
D:/MABS-ffmpeg/build/highway-git/hwy/base.h:535:24: note: candidate is: 'template<class T> constexpr bool hwy::IsSigned()'
  535 | HWY_API constexpr bool IsSigned() {
      |                        ^~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check D:/MABS-ffmpeg/build/highway-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oQnT.zip

**Comment by 1480c1** [comment]
https://github.com/google/highway/issues/846

**Comment by Barough** [comment]
Fixed Upstream
