### ISSUE TITLE
not building with cmake

### ISSUE THREAD

**Issue by j-mas** [m-ab-s/media-autobuild_suite#2241]
Hi! 

Can someone help me please. I keep getting this error message with cmake! What is the problem and how can I solve it?
No idea what it is!
System: Intel Core i 9 Windows 11 64 bit
j-mas
<img width="477" alt="2022-07-12" src="https://user-images.githubusercontent.com/43079436/178572757-866ecc5b-8125-41cc-9d78-b2a284d52ed8.png">

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/9096055/logs.zip)

**Comment by 1480c1** [comment]
```c
  It fails with the following output:

    Change Dir: C:/m-a-master2/build/aom-git/build-64bit/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/m-a-master2/msys64/mingw64/bin/ninja.exe cmTC_d6d36 && [1/2] Building C object CMakeFiles/cmTC_d6d36.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_d6d36.exe
    FAILED: cmTC_d6d36.exe 
    cmd.exe /C "cd . && C:\m-a-master2\msys64\mingw64\bin\ccache.exe  gcc -mthreads -mtune=generic -O2 -pipe  -O3 -DNDEBUG -pipe -static-libgcc -static-libstdc++ CMakeFiles/cmTC_d6d36.dir/testCCompiler.c.o -o cmTC_d6d36.exe -Wl,--out-implib,libcmTC_d6d36.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
    C:/m-a-master2/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file cmTC_d6d36.exe: Invalid argument
    collect2.exe: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.
```

can you check to see if your anti-virus software caught something?

**Comment by j-mas** [comment]
I only use windows defender. I disabled it, but the same result!

**Comment by j-mas** [comment]
I always get this error log by using cmake:

[CMakeError.log](https://github.com/m-ab-s/media-autobuild_suite/files/9145064/CMakeError.log)

Is it possible that the problem is yasm?

**Comment by 1480c1** [comment]
Can you try a shorter path?

**Comment by j-mas** [comment]
I tried this also, but no success. 
I think the problem is my windows 11 system. 
Could it be that installing python and vapoursynth for av1an is the problem, because before installing this the problem does not occur?

**Comment by 1480c1** [comment]
I am not sure how to reproduce nor help with this issue as despite having a Windows 11 system as well, I have not been able to reproduce this issue
