### ISSUE TITLE
Missing functions from library files

### ISSUE THREAD

**Issue by sodaboy581** [m-ab-s/media-autobuild_suite#2245]
Why is it when compiling FFmpeg with media-autobuild, avutil.lib is missing:

av_fifo_write
av_fifo_freep2
av_channel_layout_compare
av_channel_layout_uninit
av_fifo_alloc2
av_channel_layout_copy
av_channel_layout_default
av_fifo_read

Also, swresample.lib is missing:

swr_alloc_set_opts2

Is there something else I need to enable to get these to be inside of the libraries?

The libraries that are generated are located in build\AMF-git\Thirdparty\ffmpeg\ffmpeg-4.3.2\win32\release\lib as well as build\AMF-git\Thirdparty\ffmpeg\ffmpeg-4.3.2\x64\release\lib

**Comment by Biswa96** [comment]
In mingw toolchain, the import libraries are named with .dll.a extension instead of .lib.

**Comment by sodaboy581** [comment]
> In mingw toolchain, the import libraries are named with .dll.a extension instead of .lib.

Sorry, I don't understand.  I use the libraries generated underneath AMF-git for use with MSVC projects.  They're fine and dandy to use except they're missing a few functions.

Just wondering why and how to get those in there. 

Also there are no relevant dll.a files for avutil or swresample.

The libraries, as is, are fine for use for most functions of FFmpeg when used with a DLL at runtime... except a few procedures that have been omitted from the .LIBs

**Comment by 1480c1** [comment]
Those files are not provided by mabs and I was not even aware of their existence until this issue, if you are trying to use them, I would recommend asking amf about them. This project does not deal with compiling nor linking with msvc with some exceptions

**Comment by sodaboy581** [comment]
Thanks!  I figured it out anyhow.  Looks like the MSVC/Win32 version makes slightly different APIs.  ex: swr_alloc_set_opts vs swr_alloc_set_opts2  and also av_fifo_generic_read instead of just _read 

Also channel layouts are just a 64-bit # as opposed to a structure now.

I got everything working tho!

**Comment by Biswa96** [comment]
Try not to mix MSVC compiled libraries with gcc/clang mingw ones.

**Comment by sodaboy581** [comment]
I'm not stupid and I did no such thing.

The Libraries generated by the tool work natively on MSVC and are located underneath the build\AMF-git\Thirdparty\win32(or x64)\release sub folder.  You need to do nothing to use them except include the .h and link the .libs generated.

The Mingw ones are clearly underneath the local32 folder 

I was just noting the actual API stuff is different for the ones under AMF-git (MSVC compatible) as opposed to the ones underneath the local32 folder.

I've never attempted to use the local32 files.

Anyhow, thanks for your replies.  I was able to add an SDL video player into my program to augment the DirectShow player I was using which didn't work that well for Linux users under WINE.  

Being able to compile this on Windows and give them options will help them tremendously.

Have a nice day!
