### ISSUE TITLE
Rust download failed

### ISSUE THREAD

**Issue by mecurry0232** [m-ab-s/media-autobuild_suite#2246]
I cannot smoothly build Rust for months.
Each time I started my building, it showed error messenge. 
The error log in the rustup was in the following:

CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
curl --proto =https --tlsv1.2 https://sh.rustup.rs -sSo rustup.sh
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/9175113/logs.zip)

**Comment by 1480c1** [comment]
> I cannot smoothly build Rust for months.

Then you should have probably opened an issue months ago

> curl: (60) SSL certificate problem: unable to get local issuer certificate

seems like there's an issue with the ssl provider, but I've never had the issue before, so I do not know how to reproduce.

Could you try another machine on the same network or the same machine on a different network? I wonder if it's related to your network condition or firewall

**Comment by 1480c1** [comment]
ping @mecurry0232?

I don't think there's anything I can do on my side since it's working just fine for me, so unless you have a clear way to reasonably reproduce this issue, I will have to close as a not planned
