### ISSUE TITLE
Question - Build without updating from git

### ISSUE THREAD

**Issue by ChrisLambert1** [m-ab-s/media-autobuild_suite#2255]
Hi,
I wonder if it is possible to start the complete build process and skip the check for new repositories and build environment? 
Somehow I can't find out how to modify the media-suite_compile.sh file?

Thank you very much

**Comment by 1480c1** [comment]
It may be possible to try to modify the media-suite_helper.sh's `do_vcs()` function to skip git fetch, but past that, I cannot help
