### ISSUE TITLE
Error: Libbluray fails to build

### ISSUE THREAD

**Issue by JustAHippo** [m-ab-s/media-autobuild_suite#2257]
Libbluray fails on make. Used with mingw-w64 on a 64 bit only install. Is there a way to remove libbluray from the list or get past this issue? Sorry if this is me being stupid.
[logs.zip](https://0x0.st/oeOG.zip)

**Comment by JustAHippo** [comment]
Further inspection, it closes on:
compile:
    [javac] D:\FFMPEGTools\build\libbluray-git\src\libbluray\bdj\build.xml:26: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] D:\FFMPEGTools\build\libbluray-git\src\libbluray\bdj\build.xml:32: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 53 source files to D:\FFMPEGTools\build\libbluray-git\build-64bit\src\libbluray\bdj\build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.4
    [javac] warning: [options] source value 1.4 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.4 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] D:\FFMPEGTools\build\libbluray-git\src\libbluray\bdj\java\org\videolan\Libbluray.java:153: error: incompatible types: **_Class cannot be converted to Class[]_**
    [javac]                 java.lang.reflect.Method method = System.class.getDeclaredMethod("implSetSecurityManager", SecurityManager.class);
    [javac]                                                                                                                           ^
    [javac] D:\FFMPEGTools\build\libbluray-git\src\libbluray\bdj\java\org\videolan\Libbluray.java:155: error: incompatible types: SecurityManager cannot be converted to Object[]
    [javac]                 method.invoke(null, sm);
    [javac]                                     ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
    [javac] 2 errors
    [javac] 4 warnings

BUILD FAILED

This should be an error maybe with versions of java(?) because that doesn't make any sense really.

**Comment by JustAHippo** [comment]
Removed libbluray from ffmpeg_options.txt, will provide an update later

**Comment by Biswa96** [comment]
If you do not need java plugin it can be disabled with `--disable-bdjava-jar` option with libbluray configure command.

**Comment by JustAHippo** [comment]
where would i put that?

**Comment by Biswa96** [comment]
It seems that media-suite_compile.sh already adds `--disable-bdjava-jar` if `JAVA_HOME` environment variable is not set. So, another workaround would be to remove or disable `JAVA_HOME` environment variable in your system before compiling.

**Comment by JustAHippo** [comment]
so i have removed all the lines that dictate it and just set the extracommands+=(--disable-bdjava-jar) manually and set JAVA_HOME to ""

**Comment by Biswa96** [comment]
It is not required to modify any file of this repository. Just make sure `JAVA_HOME` variable is not set. That environment variable can be removed from Control Panel permanently or execute `set JAVA_HOME=` command before running media-autobuild_suite.bat.

**Comment by JustAHippo** [comment]
big issue. it finished compiling but libfdk_aac is nowhere to be found. it updated its git but appears nowhere else in the logs?!

**Comment by JustAHippo** [comment]
it happens to be in local64/lib and local64/include but isn't packaged? could someone please help with this?

**Comment by 1480c1** [comment]
What are you looking for exactly? How are you confirming "libfdk_aac is nowhere to be found"? Does it appear if you run
```bash
/local64/bin-video/ffmpeg.exe -encoders | grep fdk
```
?

**Comment by JustAHippo** [comment]
windows path is a bitch, isn't it. despite not being in my env variables, some shit maneuvered its way to the front despite this new install being at the front of my path settings. IT WORKED THO! thanks so much and sorry for all the trouble!
