### ISSUE TITLE
libbluray terminate with javac-error

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#2258]
13:55:51   Running git clone for libbluray...
13:55:56   Running git update for libbluray...
13:55:56 ┌ libbluray git  ............................ [Recently updated]
13:55:56 ├ Running git.submodule...
13:55:58 ├ Running autoreconf...
13:56:23 ├ Running javahome...
13:56:23 ├ Running ant-diagnostics...
13:56:25 ├ Running configure...
13:57:12 ├ Running make...
Likely error (tail of the failed operation logfile):
    [javac] 2 errors
    [javac] 4 warnings

BUILD FAILED
F:\m-a-s\build\libbluray-git\src\libbluray\bdj\build.xml:32: Compile failed; see the compiler error output for details.

Total time: 0 seconds
make[1]: *** [Makefile:2874: all-local] Error 1
make[1]: Leaving directory '/build/libbluray-git/build-32bit'
make: *** [Makefile:1039: all] Error 2
make failed. Check F:/m-a-s/build/libbluray-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.

I've no idea what happens  - nothing changed since last run
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/9259569/logs.zip)

**Comment by 1480c1** [comment]
https://code.videolan.org/videolan/libbluray/-/commit/3187c3080096e107f0a27eed1843232b58342577

possibly caused by that

**Comment by 1480c1** [comment]
Opened an issue at https://code.videolan.org/videolan/libbluray/-/issues/39

**Comment by ASopH** [comment]
Hi, thank you :-)

**Comment by ASopH** [comment]
Sorry, wrong button ...

**Comment by ASopH** [comment]
Hi, build passes
13:08:42 ┌ libbluray git  ............................... [Updates found]
13:08:42 ├ Running autoreconf...
13:09:09 ├ Running javahome...
13:09:09 ├ Running ant-diagnostics...
13:09:12 ├ Running configure...
13:10:01 ├ Running make...
13:10:18 ├ Running install...
13:10:22 ├ Stripping...
13:10:22 └ libbluray-git  ..................................... [Updated]


Thank you :-)
