### ISSUE TITLE
exit code 1 despite successful compilation

### ISSUE THREAD

**Issue by ReenigneArcher** [m-ab-s/media-autobuild_suite#2259]
I am running this in a GitHub runner. It appears that compilation is successful, but exits with error code 1.

Here is the output of the latest run: https://github.com/LizardByte/ffmpeg-prebuilt/runs/7661588462?check_suite_focus=true#step:7:3951

There are a few patches applied to get it to run headless (without prompts), but I don't believe these are causing the exit code 1. (These worked fine previously.)
```bash
sed -i 's/do_prompt /echo /g' build/media-suite_helper.sh build/media-suite_compile.sh
sed -i 's/read.*yn/yn=y/g' build/media-suite_update.sh
```

**Comment by 1480c1** [comment]
```bat
)
if %noMintty%==y (
    call :runBash compile.log /build/media-suite_compile.sh %compileArgs%
) else (
    if exist %build%\compile.log del %build%\compile.log
    start "compile" /I /LOW %CD%\msys64\usr\bin\mintty.exe -i /msys2.ico -t "media-autobuild_suite" ^
    --log 2>&1 %build%\compile.log /bin/env MSYSTEM=%MSYSTEM% MSYS2_PATH_TYPE=inherit ^
    /usr/bin/bash ^
    --login /build/media-suite_compile.sh %compileArgs%
)
color
exit /B %ERRORLEVEL%
```
I'm curious if `color` is "erroring" out, can you try removing that command and see again?

**Comment by 1480c1** [comment]
ping @ReenigneArcher

**Comment by ReenigneArcher** [comment]
> ping @ReenigneArcher

Sorry, I have not had a chance to dig into this further yet. It's not the easiest to modify and test in a github runner.
