### ISSUE TITLE
ffmpeg build error

### ISSUE THREAD

**Issue by mangohugo** [m-ab-s/media-autobuild_suite#2262]
09:15:42 ┌ ffmpeg git  ............................... [Recently updated]
09:15:42 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
09:15:51 ├ Compiling static FFmpeg...
09:15:53 ├ Running configure...
09:23:38 ├ Running make...
Likely error (tail of the failed operation logfile):
make: *** [/build/ffmpeg-git/Makefile:131: ffprobe_g.exe] Error 1
make: *** Waiting for unfinished jobs....
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:131: ffplay_g.exe] Error 1
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:131: ffmpeg_g.exe] Error 1
LD      ffmpeg_g.exe
C:/ffmpeg3/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg3/local64/lib/libSvtVp9Enc.a(EbEncHandle.c.obj):EbEncHandle.c:(.bss+0x110): multiple definition of `vpx_subtract_block'; C:/ffmpeg3/local64/lib/libvpx.a(vpx_dsp_rtcd.c.o):vpx_dsp_rtcd.c:(.bss+0x40): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:131: ffmpeg_g.exe] Error 1
make failed. Check C:/ffmpeg3/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
09:36:29   Creating diagnostics file...

[logs.zip](https://0x0.st/o2Xj.zip)

**Comment by 1480c1** [comment]
should be fixed upstream, can you try again?

**Comment by mangohugo** [comment]
Works, thx.
