### ISSUE TITLE
Request: Add option to disable pthreads

### ISSUE THREAD

**Issue by ispysoftware** [m-ab-s/media-autobuild_suite#2264]
Would it be possible to add an option to the config to disable pthreads in the builds?
Alternatively if someone could point me to which file i'd need to modify to do that I'd really appreciate it.
(for some reason pthreads are causing other components in my app to hang)

**Comment by Biswa96** [comment]
Can you provide which components are affected with pthreads and any error output etc. ? pthreds implementation is used in core parts of mingw compiler and libraries.

**Comment by ispysoftware** [comment]
I'm not sure, it's really hard to debug it as the application just completely hangs at random spots when pthreads are enabled and have to be force-closed. It's some internal conflict with win 32 threads in microsoft's (compiled) direct-x library and webrtc libraries. FFmpeg builds without pthread work fine (took a while to find that out!)

**Comment by 1480c1** [comment]
Do you mean pthreads for FFmpeg or like for the whole toolchain? Because for ffmpeg, there should be a `--disable-pthreads` and `--enable-win32threads` option or something, although it might be gated or forced enabled based on other libraries you might have that might hard require pthread or something

**Comment by ispysoftware** [comment]
just for ffmpeg - where would i add those flags to try them out?

**Comment by 1480c1** [comment]
Depends on what you have selected, but if there's a file called `build/ffmpeg_options.txt`, you can check that file and see if it's anywhere there, else add at the bottom
```bash
--disable-pthreads
--enable-w32threads
```
and I think that should be sufficient, do check `ffmpeg`'s output to see if it's there though

**Comment by 1480c1** [comment]
I'm going to assume this has been answered

**Comment by ispysoftware** [comment]
No i gave up on it. Thanks anyway.
