### ISSUE TITLE
rav1e fails to build even though I

### ISSUE THREAD

**Issue by taresh73** [m-ab-s/media-autobuild_suite#2270]
https://github.com/m-ab-s/media-autobuild_suite/issues/new

Likely error (tail of the failed operation logfile):
          C:/mabs/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\console-0.15.1\src/utils.rs:(.text+0x76): undefined reference to `__imp__ZN7console5utils13STDOUT_COLORS17hcce10a805ac03887E'
          C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\console-0.15.1\src/utils.rs:(.text+0x7f): undefined reference to `__imp__ZN7console5utils13STDERR_COLORS17h431a34178b191106E'
          C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\console-0.15.1\src/utils.rs:(.text+0x94): undefined reference to `__imp__ZN7console5utils13STDERR_COLORS17h431a34178b191106E'
          collect2.exe: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `rav1e` due to previous error
rust.build failed. Check C:/mabs/build/rav1e-git/ab-suite.rust.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/o_53.zip
Copy and paste [logs.zip](https://0x0.st/o_53.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by 1480c1** [comment]
Consolidating rav1e issues into https://github.com/m-ab-s/media-autobuild_suite/issues/2266
