### ISSUE TITLE
3 "Patch could not be applied with git am. Continuing without patching" warnings when running update for libwebp

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2273]
20:27:17 └ libtiff-git  ....................................... [Updated]
20:27:24   Running git update for libwebp...
20:27:36 ┌ libwebp git  ................................. [Updates found]
0001-vwebp-Use-GLUT-and-opengl-import-targets.patch
        Patch could not be applied with `git am`. Continuing without patching.
0002-vwebp-link-winmm-if-windows.patch
        Patch could not be applied with `git am`. Continuing without patching.
0003-deps-link-libtiff-first.patch
        Patch could not be applied with `git am`. Continuing without patching.
20:27:41 ├ Running uninstall...
20:27:42 ├ Running cmake...
20:27:59 ├ Running build...
20:28:27 ├ Running install...
20:28:28 ├ Stripping...
20:28:29 └ libwebp-git  ....................................... [Updated]

**Comment by Barough** [comment]
Already reported
https://github.com/m-ab-s/media-autobuild_suite/issues/2271

**Comment by 1480c1** [comment]
Should be closed with https://github.com/m-ab-s/media-autobuild_suite/commit/34d45e16225da2ebf626ba432aec7a89a2f68582
