### ISSUE TITLE
curl fails to build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2276]
┌ curl git  .............................................. [Updates found]
├ Running uninstall...
├ Running autogen...
├ Running configure...
Likely error (tail of the failed operation logfile):
checking whether to enable IPv6... yes
checking if struct sockaddr_in6 has sin6_scope_id member... yes
checking if argv can be written to... yes
checking if GSS-API support is requested... no
checking whether to enable Windows native SSL/TLS... yes
checking whether to enable Secure Transport... no
checking whether to enable Amiga native SSL/TLS (AmiSSL v5)... no
configure: error: --without-ssl has been set together with an explicit option to use an ssl library
(e.g. --with-openssl, --with-gnutls, --with-wolfssl, --with-mbedtls, --with-nss, --with-schannel, --with-secure-transport, --with-amissl, --with-bearssl, --with-rustls).
Since these are conflicting parameters, verify which is the desired one and drop the other.
configure failed. Check D:/MABS-ffmpeg/build/curl-git/build-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ofXG.zip

**Comment by 1480c1** [comment]
I guess something changed with https://github.com/curl/curl/commit/7d69924ce773f13c175e56ad1b20b0d5dac224b9, and I'm not sure if `--without-ssl` was ever intentional or not

**Comment by 1480c1** [comment]
Ah, possibly https://github.com/curl/curl/blob/7d69924ce773f13c175e56ad1b20b0d5dac224b9/configure.ac#L215 maybe originally implied `--with-openssl` and the `--without-ssl` to mean `--without-openssl`, rather than just `ssl`, which seems I might be right https://github.com/curl/curl/commit/7bdec2a08bf025d2f66c168111d47df6b21890d9#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R1740

**Comment by 1480c1** [comment]
I'll just remove the arguments relating to just `--with/out-ssl`

**Comment by 1480c1** [comment]
pushed https://github.com/m-ab-s/media-autobuild_suite/commit/7c541d426c01ff80f716990b8fb092f0cfcb8d81, please try again

**Comment by hydra3333** [comment]
Hi. OK.
Of possible  interest https://github.com/curl/curl/issues/9438#issuecomment-1237892231
So in a different build script with Mingw64, I have to use: --without-ssl --with-gnutls or it fails to build.

Probably unrelated to your issue, but there you go.

**Comment by donnaken15** [comment]
I got this same issue and I just updated

[logs.zip](https://0x0.st/ovNF.zip)

**Comment by 1480c1** [comment]
> I got this same issue and I just updated
> 
> [logs.zip](https://0x0.st/ovNF.zip)

it does not seem like your is updated, as the latest is supposed to look like:
```bash
    case $curl in
    libressl|openssl)
        extra_opts+=(--with-{nghttp2,openssl} --without-{gnutls,mbedtls})
        ;;
    mbedtls) extra_opts+=(--with-{mbedtls,nghttp2} --without-openssl) ;;
    gnutls) extra_opts+=(--with-gnutls --without-{nghttp2,mbedtls,openssl}) ;;
    *) extra_opts+=(--with-{schannel,winidn,nghttp2} --without-{gnutls,mbedtls,openssl});;
    esac
```
while yours looks like
```bash
    case $curl in
    libressl|openssl)
        extra_opts+=(--with-{ssl,nghttp2} --without-{gnutls,mbedtls})
        ;;
    mbedtls) extra_opts+=(--with-{mbedtls,nghttp2} --without-ssl) ;;
    gnutls) extra_opts+=(--with-gnutls --without-{ssl,nghttp2,mbedtls}) ;;
    *) extra_opts+=(--with-{schannel,winidn,nghttp2} --without-{ssl,gnutls,mbedtls});;
    esac

```

**Comment by donnaken15** [comment]
i thought it wouldve since i saw pacman pull updates for stuff before recompiling everything
