### ISSUE TITLE
mingw64 libplacebo build error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2277]
11:11:18 ├ Running build...
Likely error (tail of the failed operation logfile):
  140 |     TOffsetRange(TRange binding, TRange offset)
      |                  ~~~~~~~^~~~~~~
C:/ffmpeg-autobuild/local64/include/glslang/MachineIndependent/localintermediate.h:146:12: note: shadowed declaration is here
  146 |     TRange binding;
      |            ^~~~~~~
../src/glsl/glslang.cc: At global scope:
../src/glsl/glslang.cc:224:1: error: cannot convert '<brace-enclosed initializer list>' to 'int' in initialization
  224 | };
      | ^
ninja: build stopped: subcommand failed.

 [logs.zip](https://0x0.st/ofKS.zip)

**Comment by Biswa96** [comment]
It seems that glslang changed one structure here https://github.com/KhronosGroup/glslang/commit/228c67228a181ac299df2a1c09a322dcc9bb0cdc#diff-ec0122601d80f687509af698e63af301c0689d0b813bd5e075c3e4f3b8c44de5.

I also get the error

```c
../src/glsl/glslang.cc:224:1: error: cannot convert '<brace-enclosed initializer list>' to 'int' in initialization
  224 | };
      | ^
```

As a workaround, try to apply this patch in libplacebo source directory.

```diff
diff --git a/src/glsl/glslang.cc b/src/glsl/glslang.cc
index 21f7ccb..d7489c7 100644
--- a/src/glsl/glslang.cc
+++ b/src/glsl/glslang.cc
@@ -208,6 +208,15 @@ const TBuiltInResource DefaultTBuiltInResource = {
     /* .maxTaskWorkGroupSizeY_NV = */ 1,
     /* .maxTaskWorkGroupSizeZ_NV = */ 1,
     /* .maxMeshViewCountNV = */ 4,
+    /* .maxMeshOutputVerticesEXT = */ 256,
+    /* .maxMeshOutputPrimitivesEXT = */ 256,
+    /* .maxMeshWorkGroupSizeX_EXT = */ 128,
+    /* .maxMeshWorkGroupSizeY_EXT = */ 128,
+    /* .maxMeshWorkGroupSizeZ_EXT = */ 128,
+    /* .maxTaskWorkGroupSizeX_EXT = */ 128,
+    /* .maxTaskWorkGroupSizeY_EXT = */ 128,
+    /* .maxTaskWorkGroupSizeZ_EXT = */ 128,
+    /* .maxMeshViewCountEXT = */ 4,
     /* .maxDualSourceDrawBuffersEXT = */ 1,
 
     /* .limits = */ {
```

**Comment by MEKKERMB** [comment]
> It seems that glslang changed one structure here [KhronosGroup/glslang@228c672#diff-ec0122601d80f687509af698e63af301c0689d0b813bd5e075c3e4f3b8c44de5](https://github.com/KhronosGroup/glslang/commit/228c67228a181ac299df2a1c09a322dcc9bb0cdc#diff-ec0122601d80f687509af698e63af301c0689d0b813bd5e075c3e4f3b8c44de5).
> 
> I also get the error
> 
> ```c
> ../src/glsl/glslang.cc:224:1: error: cannot convert '<brace-enclosed initializer list>' to 'int' in initialization
>   224 | };
>       | ^
> ```
> 
> As a workaround, try to apply this patch in libplacebo source directory.
> 
> ```diff
> diff --git a/src/glsl/glslang.cc b/src/glsl/glslang.cc
> index 21f7ccb..d7489c7 100644
> --- a/src/glsl/glslang.cc
> +++ b/src/glsl/glslang.cc
> @@ -208,6 +208,15 @@ const TBuiltInResource DefaultTBuiltInResource = {
>      /* .maxTaskWorkGroupSizeY_NV = */ 1,
>      /* .maxTaskWorkGroupSizeZ_NV = */ 1,
>      /* .maxMeshViewCountNV = */ 4,
> +    /* .maxMeshOutputVerticesEXT = */ 256,
> +    /* .maxMeshOutputPrimitivesEXT = */ 256,
> +    /* .maxMeshWorkGroupSizeX_EXT = */ 128,
> +    /* .maxMeshWorkGroupSizeY_EXT = */ 128,
> +    /* .maxMeshWorkGroupSizeZ_EXT = */ 128,
> +    /* .maxTaskWorkGroupSizeX_EXT = */ 128,
> +    /* .maxTaskWorkGroupSizeY_EXT = */ 128,
> +    /* .maxTaskWorkGroupSizeZ_EXT = */ 128,
> +    /* .maxMeshViewCountEXT = */ 4,
>      /* .maxDualSourceDrawBuffersEXT = */ 1,
>  
>      /* .limits = */ {
> ```

How do you apply the patch if you don't mind me asking?
Tried by manually pasting the new lines in the file glslang.cc without success.

**Comment by Biswa96** [comment]
> How do you apply the patch if you don't mind me asking?

* Copy the text from the comment in a file, let say test.patch.
* Find the libplacebo source directory and `cd` into it.
* Run `patch -p1 -i path/to/test.patch` command to apply it.

BTW, I have posted the patch as a workaround.

**Comment by ENunn** [comment]
I get an error - error: corrupt patch at line 20

> > How do you apply the patch if you don't mind me asking?
> 
>     * Copy the text from the comment in a file, let say test.patch.
> 
>     * Find the libplacebo source directory and `cd` into it.
> 
>     * Run `git apply path/to/test.patch` command to apply it.
> 
> 
> BTW, I have posted the patch as a workaround.

**Comment by 1480c1** [comment]
Reported upstream https://code.videolan.org/videolan/libplacebo/-/issues/225

**Comment by hydra3333** [comment]
Probably unrelated and does not affect you, however of possible interest if building glslang and shaderc from git head:

In a different mingw64 build system:
The latest git glslang became "incompatible" with the latest git shaderc which used glslang as a 3rd-party dependency.
Since I built glslang separately, I linked the 3rd-party folders to the separately-built dependencies and then patched the shaderc configure file(s) to ensure that the "last compatible" commit of glslang was specified in both the separate glslang build and in the shaderc configure file(s).

**Comment by Biswa96** [comment]
glslang, spirv and shaderc only become compatible sometimes. They maintain a specific commit set for that. For example, glslang has this https://github.com/KhronosGroup/glslang/blob/master/known_good.json. So, manually patching those repository at _incompatible time_ would not work always. One has to keep watch all those repos.

**Comment by Barough** [comment]
> Reported upstream https://code.videolan.org/videolan/libplacebo/-/issues/225

Looks like there is a solution available for you to add.

**Comment by redredbeard** [comment]
> 
After applying the patch manually, whenever you invoke media-autobuild_suite.bat again, it reverts the patch and still fails.  Is there a way to manually build this with the patch without invoking the main batch file?

**Comment by redredbeard** [comment]
Looks like they fixed it upstream and this is no longer failing.

**Comment by kliffgomel** [comment]
Fixed!
