### ISSUE TITLE
mingw64 curl configure error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2278]
08:16:54 ┌ curl git  ................................. [Recently updated]
08:16:57 ├ Running autogen...
08:18:08 ├ Running configure...
Likely error (tail of the failed operation logfile):
  --with-bearssl
  --with-gnutls
  --with-mbedtls
  --with-nss
  --with-openssl (also works for BoringSSL and libressl)
  --with-rustls
  --with-schannel
  --with-secure-transport
  --with-wolfssl

[logs.zip](https://0x0.st/ofmL.zip)

**Comment by hydra3333** [comment]
perhaps https://github.com/curl/curl/issues/9438#issuecomment-1237892231
perhaps use --without-ssl --with-gnutls

**Comment by kliffgomel** [comment]
It does not work for me with ffmpeg backend, but if you select another backend in the settings, then there are no problems.
