### ISSUE TITLE
libavif / avifenc version: "libyuv : unavailable"

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2282]
Is this a flaw at all – and if so, maybe a hint to a missing linking of this library, or a wrong reporting of version numbers?

`avifenc -h`
```
...

Version: 0.10.1 (dav1d [dec]:1.0.0-61-g5247319, aom [enc/dec]:3.4.0-397-gaeee77c48, rav1e [enc]:0.5.0 (p20220906-3-g25f6c0f))
libyuv : unavailable
```

**Comment by kliffgomel** [comment]
Still, the libyuv library is not linked when building. But image encoding works.
[ab-suite.cmake.log](https://github.com/m-ab-s/media-autobuild_suite/files/9547103/ab-suite.cmake.log)

**Comment by gitoss** [comment]
This is completed just liek https://github.com/m-ab-s/media-autobuild_suite/issues/2608 and can be closed.

**Comment by LigH-de** [comment]
True, forgot about this...
