### ISSUE TITLE
Request/Regression: Kvazaar with more than 8bit

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#2283]
With old Kvazaar builds from mbas I was able to use 8, 10, 12 and 16 bit, now only 8bit works.
Would be nice if 10/12/16bit would also be build,

**Comment by 1480c1** [comment]
Can you try https://github.com/m-ab-s/media-autobuild_suite/commit/4f36034e2bdd9335540db2e4fd10e4b1413d6c06?

**Comment by Selur** [comment]
Will do and report back once the script ran through.

**Comment by Selur** [comment]
Works! (at least 8bit and 12 bit so, 16bit doesn't crash but produces broken output, but that seems like an issue with the kvazaar encoder itself)

**Comment by Selur** [comment]
Checked with the kvazaar devs, it only supports 8&10 bit encoding, contrary to their command line help.
