### ISSUE TITLE
[mingw64] [clang] [gnutls 3.7.7] | Make failed, errors 1 & 2

### ISSUE THREAD

**Issue by snowbie** [m-ab-s/media-autobuild_suite#2288]
``` bash
gnutls 3.7.7  ............................................ [Not installed]
├ gnutls-3.7.7  ........................................ [File up-to-date]
├ Running extract...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
3 errors generated.
make[4]: *** [Makefile:2619: select.lo] Error 1
make[4]: Leaving directory '/build/gnutls-3.7.7/build-64bit/src/gl'
make[3]: *** [Makefile:2643: all-recursive] Error 1
make[3]: Leaving directory '/build/gnutls-3.7.7/build-64bit/src/gl'
make[2]: *** [Makefile:2415: all] Error 2
make[2]: Leaving directory '/build/gnutls-3.7.7/build-64bit/src/gl'
make[1]: *** [Makefile:2258: all-recursive] Error 1
make[1]: Leaving directory '/build/gnutls-3.7.7/build-64bit'
make: *** [Makefile:2183: all] Error 2
make failed. Check C:/mabs/build/gnutls-3.7.7/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

```

[logs.zip](https://0x0.st/oWrw.zip)

**Comment by 1480c1** [comment]
Seems to be an issue in gnulib

**Comment by kliffgomel** [comment]
Everything works for me now

**Comment by snowbie** [comment]
> Everything works for me now

I still haven't been able to get it to build because of this

**Comment by 1480c1** [comment]
Probably fixed by https://github.com/m-ab-s/media-autobuild_suite/commit/0cd1909331b8aabf856f938ad76df3fef098e833

**Comment by Biswa96** [comment]
What was the compiler being used while compiling gnutls?

**Comment by 1480c1** [comment]
probably mingw-w64-x86_64-clang 15.0.1

**Comment by 1480c1** [comment]
Seems to be a recent change with 15 as I saw a commit upstream in gnutls by @mstorsjo https://github.com/gnutls/gnutls/commit/88d79b964d88730e316919d6ccd17ca0fe9b3244 but since this was within a checkout of gnutls, I couldn't spend enough time trying to create a small patch for it and just disabled the warning

**Comment by Biswa96** [comment]
Yeah, noticed it. I suggested a patch to fix the similar issues in gnupg but the warnings are kept as a reminder 🤦‍♂️ https://lists.gnupg.org/pipermail/gnupg-devel/2022-October/035133.html
