### ISSUE TITLE
[mingw64] [ffmpeg] The mothed found CUDA_PATH environment variable not compatible with CUDA Toolkit v11.8.

### ISSUE THREAD

**Issue by fuchanghao** [m-ab-s/media-autobuild_suite#2303]
Seems m-ab-s's code which found CUDA_PATH should be updated.

For now, CUDA toolkit uses a version fixed path ON environment variable.

``` bash
Administrator@TEDDYSUN /trunk
$ cygpath -sm "$CUDA_PATH"
cygpath: can't convert empty path
Administrator@TEDDYSUN /trunk
$ cygpath -sm "$CUDA_PATH_V11_8"
C:/PROGRA~1/NVIDIA~2/CUDA/v11.8
```

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)

**Comment by okazunori2013** [comment]
I had this problem as well, but reinstalling CUDA solved it.
