### ISSUE TITLE
fatal: cannot change to 'vpx-git': No such file or directory

### ISSUE THREAD

**Issue by kenichi512** [m-ab-s/media-autobuild_suite#2308]
Regarding this problem (#2307), I created a new MABS directory for
compile from 0 but had this error.

``` bash
14:48:56   Running git clone for vpx...
Likely error (tail of the failed operation logfile):
Cloning into 'vpx-git'...
error: RPC failed; curl 56 OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
error: 7279 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
+ git -C vpx-git reset --hard origin/HEAD
fatal: cannot change to 'vpx-git': No such file or directory
+ check_valid_vcs vpx-git
+ [[ -d vpx-git/.git ]]
```

[logs.zip](https://0x0.st/oxax.zip)

Update:
``` bash
15:10:05   Running git clone for rav1e...
Likely error (tail of the failed operation logfile):
Cloning into 'rav1e-git'...
error: RPC failed; curl 56 OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
error: 7631 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
+ git -C rav1e-git reset --hard origin/HEAD
fatal: cannot change to 'rav1e-git': No such file or directory
+ check_valid_vcs rav1e-git
+ [[ -d rav1e-git/.git ]]
```

[logs.zip](https://0x0.st/oxan.zip)

**Comment by Barough** [comment]
Looks like you got disconnected. Delete the vpx folder and give it another try.

**Comment by 1480c1** [comment]
This seems like a connection issue/git/ssl issue, could you open mintty.lnk from mabs and run `command -v git` and confirm it's using `/usr/bin/git` and then also try running `rm -rf rav1e; git clone https://github.com/xiph/rav1e.git` a few times and see if it causes an error?

Try checking to make sure you don't require a proxy or some special network configuration

**Comment by 1480c1** [comment]
Based on your recent issues, I'm inclined to think you may really have a network issue. I have no way to diagnose them nor help you with them, unless you can prove that it's caused by something the suite has done, I would recommend try tracking the issue down to the specific component.
