### ISSUE TITLE
x265: Last additions destroy building / multilib linking

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2309]
Already reported in the [x265-devel mailing list](https://mailman.videolan.org/pipermail/x265-devel/2022-October/013518.html)...

[logs.zip](https://0x0.st/oxm2.zip)

**Comment by 1480c1** [comment]
https://bitbucket.org/multicoreware/x265_git/pull-requests/9 should fix this, but testing locally before I add the patch

**Comment by 1480c1** [comment]
https://bitbucket.org/multicoreware/x265_git/pull-requests/9 should fix this, but testing locally before I add the patch

Closed with https://github.com/m-ab-s/media-autobuild_suite/commit/ad156e6f545b6d2ed4a4efbee1adc5e0cf4eabf4

**Comment by LigH-de** [comment]
Patch has been commited.
