### ISSUE TITLE
x265 fails to compile

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2310]
┌ x265_git git  .......................................... [Updates found]
├ Running uninstall...
├ Building 12-bit lib for multilib...
├ Running cmake...
├ Running build...
├ Building 10-bit lib for multilib...
├ Running cmake...
├ Running build...
├ Building multilib lib/bin...
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x140): multiple definition of `OrigPicBuffer::~OrigPicBuffer()'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x140): first defined here
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x140): multiple definition of `OrigPicBuffer::~OrigPicBuffer()'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x140): first defined here
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x2f0): multiple definition of `OrigPicBuffer::recycleOrigPicList()'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x2f0): first defined here
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x3a0): multiple definition of `TemporalFilter::TemporalFilter()'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x3a0): first defined here
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x3a0): multiple definition of `TemporalFilter::TemporalFilter()'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x3a0): first defined here
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x410): multiple definition of `TemporalFilter::init(x265_param const*)'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x410): first defined here
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x4a0): multiple definition of `TemporalFilter::createRefPicInfo(TemporalFilterRefPicInfo*, x265_param*)'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x4a0): first defined here
D:/mabs/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x3f00): multiple definition of `TemporalFilter::destroyRefPicInfo(TemporalFilterRefPicInfo*)'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x3e10): first defined here
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check D:/mabs/build/x265_git-git/build-32bit/8bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oxeu.zip
Copy and paste [logs.zip](https://0x0.st/oxeu.zip) in the GitHub issue.

**Comment by OliverMD15** [comment]
I can't compile it either. [logs.zip](https://0x0.st/ox2G.zip)
```
14:45:06 ┌ x265_git git  ............................. [Recently updated]
14:45:07 ├ Building 12-bit lib for multilib...
14:45:07 ├ Running cmake...
14:45:11 ├ Running build...
14:46:43 ├ Building 10-bit lib for multilib...
14:46:43 ├ Running cmake...
14:46:47 ├ Running build...
14:48:19 ├ Building multilib lib/bin...
14:48:19 ├ Running cmake...
14:48:24 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/Download/Media-Autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x160): multiple definition of `OrigPicBuffer::~OrigPicBuffer()'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x160): first defined here
C:/Download/Media-Autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x160): multiple definition of `OrigPicBuffer::~OrigPicBuffer()'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x160): first defined here
C:/Download/Media-Autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x2e0): multiple definition of `OrigPicBuffer::recycleOrigPicList()'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x2e0): first defined here
C:/Download/Media-Autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x380): multiple definition of `TemporalFilter::TemporalFilter()'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x380): first defined here
C:/Download/Media-Autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x380): multiple definition of `TemporalFilter::TemporalFilter()'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x380): first defined here
C:/Download/Media-Autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x3e0): multiple definition of `TemporalFilter::init(x265_param const*)'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x3e0): first defined here
C:/Download/Media-Autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x460): multiple definition of `TemporalFilter::createRefPicInfo(TemporalFilterRefPicInfo*, x265_param*)'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x460): first defined here
C:/Download/Media-Autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .\libx265_main12.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x7370): multiple definition of `TemporalFilter::destroyRefPicInfo(TemporalFilterRefPicInfo*)'; libx265.a(temporalfilter.cpp.obj):temporalfilter:(.text+0x6260): first defined here
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/Download/Media-Autobuild/build/x265_git-git/build-64bit/8bit/ab-suite.build.log
This is required for other packages, so this script will exit.
14:49:41   Creating diagnostics file...
```

**Comment by Maypeur** [comment]
Same here, i removed --enable-x265 in ffmpeg options and it builds well.
local32\lib\libx265.a and local32\lib\pkgconfig\x265.pc are here too.

**Comment by Biswa96** [comment]
Can anyone provide steps to reproduce the issue with simple build commands and without media-autobuild-suite project?

**Comment by 1480c1** [comment]
Closed with https://github.com/m-ab-s/media-autobuild_suite/commit/ad156e6f545b6d2ed4a4efbee1adc5e0cf4eabf4
