### ISSUE TITLE
x265 - fix-multibit-builds.patch / Patch could not be applied with `git am`.

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2315]
┌ x265_git git  .......................................... [Updates found]
fix-multibit-builds.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running uninstall...

Think commit ad156e6 can be reverted since the patch have been added to commited to the x265 source

**Comment by 1480c1** [comment]
Closed with https://github.com/m-ab-s/media-autobuild_suite/commit/cb3d5a470476c54b7a00f6619074186de5ba76fa
