### ISSUE TITLE
Compiling ffmpeg with libvpl.

### ISSUE THREAD

**Issue by MEKKERMB** [m-ab-s/media-autobuild_suite#2317]
Is it possible to compile ffmpeg with libvpl?

According to this [article](https://www.intel.com/content/www/us/en/developer/articles/technical/onevpl-in-ffmpeg-for-great-streaming-on-intel-gpus.html) from Intel it should be as simple as replacing "--enable-libmfx" with "--enable-libvpl".
But it fails with an error.

I tried pasting the source code from [this repository](https://github.com/oneapi-src/oneVPL) into the build folder, hoping it would solve the problem, but without success.

``` bash
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libvpl --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-libsvtav1 --enable-chromaprint --enable-decklink --enable-frei0r --enable-libaribb24 --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libsvthevc --enable-libsvtvp9 --enable-libkvazaar --enable-libmodplug --enable-librist --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-libglslang --enable-vulkan --enable-libdavs2 --enable-libxavs2 --enable-libuavs3d --enable-libplacebo --enable-libjxl --enable-opencl --enable-opengl --enable-libopenh264 --enable-openssl --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-IC:/media-autobuild_suite-master/local64/include --extra-cflags=-IC:/media-autobuild_suite-master/local64/include/AL --extra-version=g01b9abd771+3
ERROR: libvpl >= 2.6 not found
```

[logs.zip](https://0x0.st/oYqL.zip)

**Comment by Biswa96** [comment]
libvpl is not present as a mingw package right now. I can try to add that package in msys2 pacman repository. Would you like to provide any test cases on how to detect if ffmpeg is compiled with libvpl?

**Comment by MEKKERMB** [comment]
>Would you like to provide any test cases on how to detect if ffmpeg is compiled with libvpl?

Would love to.
What should I do to provide you those test cases?

**Comment by Biswa96** [comment]
Is there any ffmpeg command which will tell that ffmpeg binaries loaded onevpl modules successfully?

**Comment by MEKKERMB** [comment]
I think I interpreted your comment wrong.
You would like me to write some code which can detect if ffmpeg binaries loaded onevpl modules successfully? If so, that will not be possible. I am unfortunately not very experienced in shell or batchfile :/

**Comment by GyanD** [comment]
You can grep `ffmpeg -v 0 -buildconf` for `--enable-libvpl`.

**Comment by MEKKERMB** [comment]
> You can grep `ffmpeg -v 0 -buildconf` for `--enable-libvpl`.

Not to sound annoying but what should I do with the command above?
I feel really out of place besides two knowledgeable people who know what they are talking about.

**Comment by GyanD** [comment]
That command was meant for @Biswa96.

**Comment by Biswa96** [comment]
I have added the onevpl package in this pull request https://github.com/msys2/MINGW-packages/pull/13800. Please try the package from CI artifacts. It's probably mingw64 and can be installed with `pacman -U <full-file-path>` command.

**Comment by MEKKERMB** [comment]
Can't seem to figure it out.
I've tried pasting the folder named "mingw-w64-onevpl" inside "media-autobuild_suite-master\msys64\var\lib\pacman\local"

![Capture](https://user-images.githubusercontent.com/27371810/198888085-12c74835-d4ba-4904-ba8d-2fc674f9a6c0.JPG)

Then I opened the "mintty" shortcut and typed `pacman -U /trunk/msys64/var/lib/pacman/local/mingw-w64-onevpl/` which gives this error:

![Capture](https://user-images.githubusercontent.com/27371810/198888539-ed0161e5-0ca0-4194-bd7c-b0b568d3c86d.JPG)

Anybody willing to help?

**Comment by MEKKERMB** [comment]
> onevpl and onevpl-cpu (x86_64 only) packages are available in msys2 mingw packages. The packages can be installed with the command: `pacman -S $MINGW_PACKAGE_PREFIX-onevpl $MINGW_PACKAGE_PREFIX-onevpl-cpu`. Adding `--enable-libvpl` option with ffmpeg configure command would link ffmpeg with libvpl.dll.
> 
> Christopher reported that av1 encoding/decoding is not working. According the the onevpl project, it works with Tiger Lake CPUs and above. But I am currently using older CPU in my system. Please test the onevpl packages.

The packages installed successfully.
Everything seems to be working as intended. I tried transcoding a file with av1_qsv and vp9_qsv on an A380 which finished without severe errors.
I've attached a log as a reference.
[ffmpeg-20221109-214329.log](https://github.com/m-ab-s/media-autobuild_suite/files/9974972/ffmpeg-20221109-214329.log)

**Comment by MEKKERMB** [comment]
Case closed long time ago.
