### ISSUE TITLE
mingw64 ffmpeg-git configure error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2320]
22:26:54 ┌ ffmpeg git  ............................... [Recently updated]
22:26:54 ├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK to run!
22:26:57 ├ Compiling static FFmpeg...
22:26:58 ├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -march=znver2 -O3 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --enable-nonfree --disable-debug --enable-libnpp --enable-cuvid --enable-nvenc --enable-nvdec --enable-d3d11va --enable-dxva2 --enable-avisynth --enable-libvmaf --enable-libass --enable-libbluray --enable-libcaca --enable-libdav1d --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-frei0r --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librav1e --enable-librtmp --enable-libtesseract --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libaom --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-libglslang --enable-vulkan --enable-libplacebo --enable-zlib --enable-bzlib --enable-lzma --enable-opencl --enable-opengl --enable-gnutls --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --disable-w32threads --enable-gpl --extra-cflags=-IC:/PROGRA~1/NVIDIA~2/CUDA/v11.8/include --extra-ldflags=-LC:/PROGRA~1/NVIDIA~2/CUDA/v11.8/lib/x64 --extra-version=g09eaa76a72+1
ERROR: libplacebo >= 4.192.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check D:/ffmpeg-autobuild/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.

 [logs.zip](https://0x0.st/oESm.zip)

**Comment by Ajaja** [comment]
```Libs.private:  -lcfgmgr32``` in vulkan.pc resolves this error, but  still, mpv  doesn`t work with ```gpu-api=vulkan``` and current version of vulkan-loader. Only solution I've found is to roll back to the previous version.
vulkan-loader_extra.sh:
```
_pre_vcs() {
    ref=d4cb3b54bb822c819b378af478145b60320e6679
}
```

**Comment by 1480c1** [comment]
Rebased vulkan-loader patch, please delete the vulkan-loader folder and rerun, that should also fix the libplacebo error with ffmpeg
