### ISSUE TITLE
fxc2 git error

### ISSUE THREAD

**Issue by kenichi512** [m-ab-s/media-autobuild_suite#2321]
I wanted to build only VLC so I just put number 2 for almost all tools in media-autobuild_suite.ini but there is almost always a different error when running MABS. Today fxc2 has given many bug reports.

``` bash
19:02:22 fxc2 git  ......................................... [Up-to-date]
19:02:23   Running git clone for qtbase...
Likely error (tail of the failed operation logfile):
Cloning into 'qtbase-git'...
error: RPC failed; curl 56 OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
error: 7163 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
+ git -C qtbase-git reset --hard origin/5.15
fatal: cannot change to 'qtbase-git': No such file or directory
+ check_valid_vcs qtbase-git
+ [[ -d qtbase-git/.git ]]
```
[logs.zip](https://0x0.st/oEjS.zip)

There were other bugs with others git but all in common it have `1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac` error.  Coincidentally I got that same error code (`[tls @ 0ac374c0] error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac`) when I used FFmpeg (built with MABS) while downloading a live stream and I searched for info but I did not find anything about what it refers to or how to solve it

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/issues/2308#issuecomment-1317565787
