### ISSUE TITLE
FFmpeg - ERROR: libplacebo >= 4.192.0 not found using pkg-config

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2324]
┌ ffmpeg git  ............................................ [Updates found]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local32/lib -L/mingw32/lib
../configure --prefix=/local32 --bindir=/local32/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-amf --enable-bzlib --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-chromaprint --enable-decklink --enable-frei0r --enable-libaribb24 --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-librist --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-liblensfun --enable-libglslang --enable-vulkan --enable-libuavs3d --enable-libplacebo --enable-libjxl --enable-openssl --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-ID:/MABS-ffmpeg/local32/include --extra-cflags=-ID:/MABS-ffmpeg/local32/include/AL --extra-version=ga7ccfdc0d7+98

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check D:/MABS-ffmpeg/build/ffmpeg-git/build-static-32bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/o6-3.zip
Copy and paste [logs.zip](https://0x0.st/o6-3.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by waldonnis** [comment]
Same cause as #2325.  The commits upstream in the last week or so made it so the patches no longer apply cleanly (alas, no analog to patch's -F option for git-am still), and there are likely more fixes needed since there were (questionable) changes related to pkgconfig file generation in there too.  For grins, I rebased the patches locally, but it needed more effort to fix and I don't have the energy at the moment.  As a workaround you can clamp vulkan-loader to 374dbe9, which is tagged as v1.3.232, until the mabs-specific patches are rebased/fixed (v1.3.233 didn't work and I didn't bother testing the commits in between).

I think this was brought up before, but since vulkan-loader seemingly requires so much hand-holding effort, would it make more sense to just stick to specific release tags rather than HEAD until the patchset is updated/verified against newer tags?  If someone wants bleeding edge/HEAD or a newer reference (and run the associated risks re linking), they can always override the ref with an extra.sh script.  Really, vulkan-loader commits cause bugs and compilation problems to crop up so often that I'm about to drop it from my local build despite the benefits of having vulkan around as an alternate GPU API.  The issues tend not to be hard to fix at all, but they always crop up at the worst time.

**Comment by 32-bit-link** [comment]
Getting the same issue on my end
[logs.zip](https://0x0.st/o6Jx.zip)

**Comment by 1480c1** [comment]
Rebased patch, please delete the vulkan-loader folder and rerun, that should also fix the libplacebo error with ffmpeg

**Comment by Barough** [comment]
FFmpeg compiles fine now :)

**Comment by Murmur** [comment]
Same problem with the latest build, `ERROR: libplacebo >= 4.192.0 not found using pkg-config`. Deleted `build/libplacebo-git, build/vulkan-loader-git` folders but no help.

```
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Compiling shared FFmpeg...
├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --disable-static --enable-shared --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libopus --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libfreetype --enable-libmfx --enable-libwebp --enable-libxml2 --enable-libzimg --enable-avisynth --enable-librav1e --enable-libsrt --enable-libvmaf --enable-libsvtav1 --enable-decklink --enable-libfribidi --enable-libsvthevc --enable-libkvazaar --enable-librtmp --enable-librubberband --enable-libplacebo --enable-libglslang --enable-vulkan --enable-libxavs2 --enable-libuavs3d --enable-demuxer=dash --disable-demuxer=bethsoftvid --disable-demuxer=tedcaptions --disable-muxer=a64 --disable-muxer=alp --enable-openssl --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-gpl --enable-nonfree --prefix=/local64 --bindir=/local64/bin-video --shlibdir=/local64/bin-video
ERROR: libplacebo >= 4.192.0 not found using pkg-config
```

[logs.zip](https://fastupload.io/QYij5iqTWLf8Kk3/file)
