### ISSUE TITLE
vulkan-loader - Patch could not be applied with `git am`.

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2325]
┌ vulkan-loader git  ..................................... [Updates found]
├ Running uninstall...
0002-pc-remove-CMAKE_CXX_IMPLICIT_LINK_LIBRARIES.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running dependencies...
├ Installing Vulkan-Headers...
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ Building Vulkan-Loader...
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ vulkan-loader-git  ........................................... [Updated]

**Comment by 84378996** [comment]
I had the same problem，
by the way, how to configure if i don't want to update ffmpeg-git when rerun the media-autobuild_suite.bat?

**Comment by 1480c1** [comment]
Rebased patch, please delete the vulkan-loader folder and rerun, that should also fix the libplacebo error with ffmpeg

**Comment by 1480c1** [comment]
> by the way, how to configure if i don't want to update ffmpeg-git when rerun the media-autobuild_suite.bat?

Don't think we have an easy way of doing that, you may need to try messing around with a `_pre_vcs` hook inside a ffmpeg_extra.sh file
