### ISSUE TITLE
mingw64 set_default_toolchain error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2327]
Starting 64bit compilation of global tools
20:29:44 ├ Running rustup_update...
20:29:44 ├ Running set_default_toolchain...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -march=znver2 -O3 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_fetch
++ git rev-parse --git-dir
+ [[ -f .git/shallow ]]
+ unshallow=
+ git fetch --all -Ppft
fatal: unable to access 'https://gitlab.gnome.org/GNOME/libxml2.git/': The requested URL returned error: 503
+ git remote set-head -a origin
fatal: unable to access 'https://gitlab.gnome.org/GNOME/libxml2.git/': The requested URL returned error: 503
git.fetch failed. Check D:/ffmpeg-autobuild/build/libxml2-git/ab-suite.git.fetch.log
This is required for other packages, so this script will exit.

[logs.zip](https://0x0.st/oIYh.zip)

**Comment by Biswa96** [comment]
The website is down [503 Service Unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503)

```
$ /usr/bin/curl -I "https://gitlab.gnome.org/"
HTTP/2 503
pragma: no-cache
cache-control: private, max-age=0, no-cache, no-store
content-type: text/html
```
