### ISSUE TITLE
[mingw64] [libtiff]

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2328]
10:51:55 freeglut git  ..................................... [Up-to-date]
10:52:00   Running git update for libtiff...
10:52:01 ┌ libtiff git  ................................. [Updates found]
10:52:10 ├ Running uninstall...
10:52:10 ├ Running cmake...
10:52:37 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2299): undefined reference to `__imp_glVertexPointer'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x22a9): undefined reference to `__imp_glNormalPointer'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x22cc): undefined reference to `__imp_glTexCoordPointer'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x22e8): undefined reference to `__imp_glDrawElements'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2319): undefined reference to `__imp_glDisableClientState'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x23a2): undefined reference to `__imp_glDrawElements'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x23be): undefined reference to `__imp_glDrawArrays'
C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/local64/lib/libglut.a(fg_ext_mswin.c.obj):fg_ext_mswin.c:(.text+0xf3): undefined reference to `__imp_wglGetProcAddress'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/ffmpeg-autobuild/build/libtiff-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
10:53:04   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oIdd.zip
Copy and paste [logs.zip](https://0x0.st/oIdd.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by Czembro** [comment]
Same for me

09:18:50   Running git clone for libtiff...
09:18:59   Running git update for libtiff...
09:18:59 ┌ libtiff git  .............................. [Recently updated]
09:19:00 ├ Installing libjpeg-turbo... done
09:19:06 ├ Installing xz... done
09:19:10 ├ Installing zlib... done
09:19:13 ├ Installing zstd... done
09:19:17 ├ Installing libdeflate... done
09:19:21 ├ Running cmake...
09:19:43 ├ Running build...
Likely error (tail of the failed operation logfile):
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x20f9): undefined reference to `__imp_glVertexPointer'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2109): undefined reference to `__imp_glNormalPointer'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x212c): undefined reference to `__imp_glTexCoordPointer'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2149): undefined reference to `__imp_glDrawElements'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x217e): undefined reference to `__imp_glDisableClientState'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2202): undefined reference to `__imp_glDrawElements'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x221e): undefined reference to `__imp_glDrawArrays'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_ext_mswin.c.obj):fg_ext_mswin.c:(.text+0xf3): undefined reference to `__imp_wglGetProcAddress'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check D:/Video/ffmpeg/build/libtiff-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
09:20:22   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oIdC.zip
Copy and paste [logs.zip](https://0x0.st/oIdC.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by 1480c1** [comment]
Seems https://gitlab.kitware.com/cmake/cmake/-/issues/21924 came back again after the latest cmake update

**Comment by Intrinsic27** [comment]
Same issue for me.
[logs.zip](https://0x0.st/ol8W.zip)

**Comment by 1480c1** [comment]
Probably fixed with https://github.com/m-ab-s/media-autobuild_suite/commit/fc42f804edb830ee80eb99a53c67de583dac1bbe

**Comment by Czembro** [comment]
> Probably fixed with [fc42f80](https://github.com/m-ab-s/media-autobuild_suite/commit/fc42f804edb830ee80eb99a53c67de583dac1bbe)

Doesn't look like it

19:15:03   Running git clone for libtiff...
19:15:12   Running git update for libtiff...
19:15:13 ┌ libtiff git  .............................. [Recently updated]
19:15:14 ├ Installing libjpeg-turbo... done
19:15:20 ├ Installing xz... done
19:15:23 ├ Installing zlib... done
19:15:27 ├ Installing zstd... done
19:15:31 ├ Installing libdeflate... done
19:15:35 ├ Running cmake...
19:15:58 ├ Running build...
Likely error (tail of the failed operation logfile):
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x20f9): undefined reference to `__imp_glVertexPointer'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2109): undefined reference to `__imp_glNormalPointer'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x212c): undefined reference to `__imp_glTexCoordPointer'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2149): undefined reference to `__imp_glDrawElements'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x217e): undefined reference to `__imp_glDisableClientState'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2202): undefined reference to `__imp_glDrawElements'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x221e): undefined reference to `__imp_glDrawArrays'
D:/Video/ffmpeg/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Video/ffmpeg/local64/lib/libglut.a(fg_ext_mswin.c.obj):fg_ext_mswin.c:(.text+0xf3): undefined reference to `__imp_wglGetProcAddress'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check D:/Video/ffmpeg/build/libtiff-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
19:16:39   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/olhw.zip
Copy and paste [logs.zip](https://0x0.st/olhw.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

**Comment by 1480c1** [comment]
Please make sure you have pulled the latest suite, I do not see the changes made in https://github.com/m-ab-s/media-autobuild_suite/commit/fc42f804edb830ee80eb99a53c67de583dac1bbe in your compile.sh file
