### ISSUE TITLE
libSDL / ffmpeg configure issue

### ISSUE THREAD

**Issue by laurfb** [m-ab-s/media-autobuild_suite#2330]
Some trouble today with latest libsdl commits (SDL master branches is changing to SDL3.0)
Till SDL3.0/ffmpeg upstream configure changes you may need to clamp libsdl to #0bfeed0 commit (to the latest v2.26.0, before transition to v3.0).

So, change the line 1183 from media-suite_compile.sh to

    do_vcs "https://github.com/libsdl-org/SDL.git#commit=0bfeed0"; then

regards,
laurfb

**Comment by laurfb** [comment]
Agree, you're right! :)
Use instead:

do_vcs "https://github.com/libsdl-org/SDL.git#SDL2"; then

regards,
laurfb

**Comment by 1480c1** [comment]
Is there an open issue for what is currently incompatible/needs to be changed on FFmpeg's side from either sdl's or FFmpeg's tracker?

**Comment by laurfb** [comment]
Not yet, since SDL 3.0 is (stil) under development phase... 

It’s safe to stay to SDL2 for a while 😊

Regards,

Laurfb

**Comment by Biswa96** [comment]
This issue may be fixed with this commit https://github.com/m-ab-s/media-autobuild_suite/commit/049e9241c352bba2136aec3cf2efdc75f55ab07e. Please pull the latest changes and try to compile it as usual.
