### ISSUE TITLE
hevc-nvenc and GTX1050

### ISSUE THREAD

**Issue by F1EJP** [m-ab-s/media-autobuild_suite#2332]
Hello,
After severals new compiling ffmpeg with autobuild since 2022 november 09 works perfectly in encoding with an NVIDIA GTX1660 card but not on several GTX1050 cards with up-to-date drivers.
Works perfectly with compiling from 2022 april and with last version of Gyan.dev ffmpeg-release-essentials 5.1.2

Exemple on windows
C:\PROGRA~1\ffmpeg\bin\ffmpeg.exe -rtbufsize 400M -f dshow -thread_queue_size 16384' -i video="' & $VID1 & '"' -f dshow -thread_queue_size 16384 -i audio="' & $AUD1 & '" -c:v hevc_nvenc -s 960x540 -r 25  -profile:v main -pix_fmt yuv420p -preset slow -rc cbr -aspect 16:9 -g 50 -b:v ' & $VIDRATE1 & ' -minrate ' & $VIDRATE1 & ' -maxrate ' & $VIDRATE1 & ' -bufsize ' & $BUFSIZE & ' -c:a ' & $AUDCOD1 & ' -ac 2' -b:a ' & $AUDIO & 'k -ar ' & $AUDF & ' -mpegts_flags system_b -flush_packets 0 -f mpegts -muxrate ' & $BASEVIDRATE & ' "udp://' & $IP & '&bitrate=' & $BASEVIDRATE & '&overrun_nonfatal=1&fifo_size=262140&buffer_size=262140

![ffmpegAuto](https://user-images.githubusercontent.com/104235948/203875222-7c2c1cdc-bc39-4c0c-9ca2-1757c0e70a8f.png)

**Comment by hydra3333** [comment]
Deary me, I also have a 1050Ti and so am very interested in the conversation in this thread !
I must rush off and give it a try.

**Comment by hydra3333** [comment]
your quoting looks a tad unusual.
`C:\PROGRA~1\ffmpeg\bin\ffmpeg.exe -rtbufsize 400M -f dshow -thread_queue_size 16384' -i video="' & $VID1 & '"' -f dshow -thread_queue_size 16384 -i audio="' `

May I suggest you post the ACTUAL commandline used in your screen grab ?

**Comment by F1EJP** [comment]
Hello,
I didn't report it to ffmpeg trac because the official versions work on this card.GTX1050
But in the compilation something must be missing?
Example without quote:
C:\PROGRA~1\ffmpeg\bin\ffmpeg.exe -rtbufsize 400M -f dshow -thread_queue_size 16384' -i video=OBS-Camera -f dshow -thread_queue_size 16384 -i audio=OBS-Audio -c:v hevc_nvenc -s 960x540 -r 30 -profile:v main -pix_fmt yuv420p -preset slow -rc cbr -aspect 16:9 -g 50 -b:v 304000 -minrate 304000 -maxrate 304000 -bufsize 1880000 -c:a libfdk_aac -ac 2' -b:a 128k -ar 44100 -mpegts_flags system_b -flush_packets 0 -f mpegts -muxrate 440310 "udp://192.168.0.40:8282&bitrate=440310& '&overrun_nonfatal=1&fifo_size=262140&buffer_size=262140

**Comment by hydra3333** [comment]
If ffmpeg has been built with opencl, try this:
`ffmpeg.exe -hide_banner -v debug -init_hw_device opencl`

and you should see your device something like: 

`[AVHWDeviceContext @ 0000022089657300] 0.0: NVIDIA CUDA / NVIDIA GeForce RTX 2060 SUPER`

**Comment by F1EJP** [comment]
Thanks for your advices.
here are the test results attached
Firts not ok
second with GTX1660
third with GTX1050
fourth with GTX1050 and option -v debug

Thanks for your help

[first-GTX1660.txt](https://github.com/m-ab-s/media-autobuild_suite/files/10108863/first-GTX1660.txt)
[second-GTX1660.txt](https://github.com/m-ab-s/media-autobuild_suite/files/10108866/second-GTX1660.txt)
[third-GTX1050Test 2.txt](https://github.com/m-ab-s/media-autobuild_suite/files/10108867/third-GTX1050Test.2.txt)
[fourth-GTX1050Test 3.txt](https://github.com/m-ab-s/media-autobuild_suite/files/10108870/fourth-GTX1050Test.3.txt)

**Comment by hydra3333** [comment]
```
[hevc_nvenc @ 000001f196edb080] 1 CUDA capable devices found
[hevc_nvenc @ 000001f196edb080] [ GPU #0 - < NVIDIA GeForce GTX 1050 Ti > has Compute SM 6.1 ]
[hevc_nvenc @ 000001f196edb080] No capable devices found
[hevc_nvenc @ 000001f196edb080] Nvenc unloaded
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```
OK so it found the 1050 Ti OK.

```
[hevc_nvenc @ 00000249a42f21c0] Loaded Nvenc version 12.0
[hevc_nvenc @ 00000249a42f21c0] Nvenc initialized successfully
[hevc_nvenc @ 00000249a42f21c0] 1 CUDA capable devices found
[hevc_nvenc @ 00000249a42f21c0] [ GPU #0 - < NVIDIA GeForce GTX 1660 > has Compute SM 7.5 ]
[hevc_nvenc @ 00000249a42f21c0] Nvenc unloaded
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```
And it found the 1660 OK and then aborted too by the looks.

Perhaps this is the clue:
`maybe incorrect parameters`
parameters not compatible with those devices ? and perhaps new checks in ffmpeg to abort if detected ?

**Comment by hydra3333** [comment]
This probably won't help, however here's an example of something which works on a 1050Ti:

`"C:\SOFTWARE\Vapoursynth-x64\ffmpeg.exe" -hide_banner -v verbose -nostats -f vapoursynth -i "D:\VRDTVSP-SCRATCH\input_file2.vpy" -probesize 200M -analyzeduration 200M  -i "D:\VRDTVSP-SCRATCH\input_file2.mpg" -map 0:v:0 -map 1:a:0 -vf "setdar=16/9" -vsync 0 -sws_flags lanczos+accurate_rnd+full_chroma_int+full_chroma_inp -strict experimental -c:v h264_nvenc -pix_fmt nv12 -preset p7 -multipass fullres -forced-idr 1 -g 25 -coder:v cabac -spatial-aq 1 -temporal-aq 1 -dpb_size 0 -bf:v 3 -b_ref_mode:v 0 -rc:v vbr -cq:v 0 -b:v 2000000 -minrate:v 100000 -maxrate:v 4000000 -bufsize 4000000 -profile:v high -level 5.2 -movflags +faststart+write_colr -af "adelay=delays=7ms:all=1"  -c:a libfdk_aac -cutoff 20000 -ab 256k -ar 48000  -y "T:\HDTV\output_file2.mp4"
`

**Comment by hydra3333** [comment]
Ok I re-read
`I didn't report it to ffmpeg trac because the official versions work on this card.GTX1050`

I don't know which official versions you mention, so sorry but the rest is over to you.

**Comment by F1EJP** [comment]
Thanks for the analysis.
For the official version i meant on ffmpeg.org the version of Gian.dev 5.1.2 the same parameters works with GTX1050 !
normally it's the same hvec-nvenc encoder that's why I don't understand?

Example with obs V28 and plugin VB-AudioCABLE: (streaming in constant bitrate)
ffmpeg.exe -v debug -rtbufsize 400M -f dshow -thread_queue_size 16384 -i video="OBS Virtual Camera" -f dshow -thread_queue_size 16384 -i audio="CABLE Output (VB-Audio Virtual Cable)" -c:v hevc_nvenc -s 960x540 -r 25 -profile:v main -pix_fmt yuv420p -preset slow -rc cbr -aspect 16:9 -g 50 -b:v 304000 -minrate 304000 -maxrate 304000 -bufsize 1880000 -c:a aac -ac 2 -b:a 48k -ar 44100 -mpegts_flags system_b -flush_packets 0 -f mpegts -muxrate 440310 udp://192.168.0.40:8282&bitrate=440310&overrun_nonfatal=1&fifo_size=262140&buffer_size=26214

**Comment by F1EJP** [comment]
Has anyone seen the same problem ?

**Comment by hydra3333** [comment]
I don't know what Gian implements.
Just a thought, perhaps if you don't get any takers then you may choose to check your parameters for modernness ... eg -preset slow vs -preset p7
eg see https://developer.download.nvidia.com/video/gputechconf/gtc/2020/presentations/s21337-nvidia-video-technologies-video-codec-and-optical-flow-sdk.pdf page 18 onwards.

**Comment by hydra3333** [comment]
good luck.  
when I did it I also checked with ffmpeg help output for codec hevc_nvenc to cross-check every parameter. 
I also found, which was not well documented anywhere, that my 2060 Super accepted "more" parameters than my 1050 Ti (refer above) and so I had to put conditionals in my script to add them to the common base set of parameters when running on the kit with the 2060; you'd need to figure out which ones that you want to you use actually work a 1050 Ti.

(after that, I'd still recommend considering you post over at the ffmpeg-user list asking for advice)

**Comment by F1EJP** [comment]
I tested a simplified command line not using obsolete parameters:

ffmpeg.exe -rtbufsize 400M -f dshow -thread_queue_size 16384 -i video="OBS-Camera" -f dshow -thread_queue_size 16384 -i audio="OBS-Audio" -c:v hevc_nvenc -b:v 304000 -c:a libfdk_aac -ac 2 -b:a 48k -ar 44100 -f mpegts -muxrate 440310 udp://192.168.0.40:8282&bitrate=440310

And same error with GTX1050ti and not with GTX1660

ffmpeg version N-109106-gd91eda4e58-g07357e56a6+1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.2.0 (Rev6, Built by MSYS2 project)
  configuration:  --pkg-config=pkgconf --cc='ccache gcc' --cxx='ccache g++' --ld='ccache g++' --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-libsvtav1 --enable-openssl --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --enable-nonfree
  libavutil      57. 42.100 / 57. 42.100
  libavcodec     59. 52.102 / 59. 52.102
  libavformat    59. 34.101 / 59. 34.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 50.100 /  8. 50.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
[swscaler @ 000002a4d6484000] Warning: data is not aligned! This can lead to a speed loss
Input #0, dshow, from 'video=OBS-Camera':
  Duration: N/A, start: 16465.763000, bitrate: N/A
  Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 1920x1080, 30 fps, 30 tbr, 10000k tbn
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, dshow, from 'audio=OBS-Audio':
  Duration: N/A, start: 16467.093000, bitrate: 1411 kb/s
  Stream #1:0: Audio: pcm_s16le, 44100 Hz, 2 channels, s16, 1411 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (hevc_nvenc))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[hevc_nvenc @ 000002a4d64f06c0] B frames as references are not supported
[hevc_nvenc @ 000002a4d64f06c0] No capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

I'm disappointed I'm going to test another new compilation...

**Comment by F1EJP** [comment]
new compilation from November 30 at 23:58 has the same result

**Comment by hydra3333** [comment]
OK. Sorry, I'm out of ideas.

Could you do me one last favour though ? 
Try this commandline and see what it says about the 1050, and please post the full uncut commandline with resulting console log ?
It's a combination of your commandline and a h.264 one that works for me (ffmpeg from a separate but related build system).
You'll need to delete the output file afterward though.
`ffmpeg.exe -v debug -nostats -rtbufsize 400M -f dshow -thread_queue_size 16384 -i video="OBS-Camera" -an -c:v henv_nvenc -pix_fmt nv12 -preset p7 -multipass fullres -forced-idr 1 -g 25 -coder:v cabac -rc:v vbr -cq:v 0 -b:v 304000 -minrate:v 200000 -maxrate:v 608000 -bufsize 608000 -profile:v main -movflags +faststart+write_colr -y "test_hevc.mp4" 
`
and for good measure maybe see what happens with h.264
`ffmpeg.exe -v debug -nostats -rtbufsize 400M -f dshow -thread_queue_size 16384 -i video="OBS-Camera" -an -c:v h264_nvenc -pix_fmt nv12 -preset p7 -multipass fullres -forced-idr 1 -g 25 -coder:v cabac -rc:v vbr -cq:v 0 -b:v 304000 -minrate:v 200000 -maxrate:v 608000 -bufsize 608000 -profile:v high -level 5.2 -movflags +faststart+write_colr -y "test_h264.mp4" `

**Comment by F1EJP** [comment]
Thank you HYDRA3333 for continuing to help me find a solution!
I don't have a GTX1050 myself and I ask friends to do the tests for me.
I developed a DATV transmission software for radio amateurs and they do the tests and experiments with me.
Here is the result of the 2 tests unfortunately still negative with the HEVC_NVENC
[H264 test.txt](https://github.com/m-ab-s/media-autobuild_suite/files/10137065/H264.test.txt)
[H265 test.txt](https://github.com/m-ab-s/media-autobuild_suite/files/10137068/H265.test.txt)

**Comment by hydra3333** [comment]
Cool :)  You seem to be well versed in ffmpeg use, more than me.

Ah. The h.264 test worked.  That tells is that the device is indeed found and works.

Perhaps nvenc stuff has been upgraded behind the scenes (by nvidia and/or ffmpeg) and some hevc defaults are pre-set expecting "better" cards and the 1050 isn't up to those default(s).
One issue I've had in the past is that ffmpeg error/warning messages do not necessarily yield user language about what's happening - in this case my guess is that "No capable devices found" actually means that there is a device "1 CUDA capable devices found" but it can't handle the parameters (eg default parameters) ... the hint being "B frames as references are not supported".
`ffmpeg.exe -v verbose -hide_banner -h encoder=hevc_nvenc`
indicates 
```
  -b_ref_mode        <int>        E..V....... Use B frames as references (from -1 to 2) (default -1)
     disabled        0            E..V....... B frames will not be used for reference
     each            1            E..V....... Each B frame will be used for reference
     middle          2            E..V....... Only (number of B frames)/2 will be used for reference
```
and I'm positive that the 1050 does not handle b-frames as reference, so you could try to add
`-b_ref_mode disabled`

Although, why the official build works and not MABS is a mystery to me.

If you are a risk taker, I could give you a link to my build which is "similar" to MABS but definitely different (more like rdp's) and you could try that just to see.

**Comment by F1EJP** [comment]
Well done !
I believe you have found the problem.
Indeed the codec must now request by default the use of BFRAME as reference.
You're probably more used to using all the parameters in ffmpeg than I am!
Attached are the 2 test results!
Thank you very much I will pay attention in the next versions to the new parameters!
[Test avec -b_ref_mode disabled .txt](https://github.com/m-ab-s/media-autobuild_suite/files/10141018/Test.avec.-b_ref_mode.disabled.txt)
[Test sans -b_ref_mode disabled.txt](https://github.com/m-ab-s/media-autobuild_suite/files/10141020/Test.sans.-b_ref_mode.disabled.txt)

**Comment by hydra3333** [comment]
Always a pleasure to work with someone from France :)

**Comment by F1EJP** [comment]
It's a pleasure to work with you too!
I would also like to be able to test a codec in av1 or H266 to create a broadcast TV stream but for the moment the Mpeg-ts muxer of ffmpeg does not seem to accept these codecs yet. 
Best wishes

**Comment by hydra3333** [comment]
OK.

https://en.wikipedia.org/wiki/AV1#Supported_container_formats
It seems mpeg-ts is an "Unfinished standard" in regard to av1 so you may be waiting for a while.

**Comment by F1EJP** [comment]
Thanks again for help and for the new ticket
It is confirmation of this new problem with new hevc_nvenc
I close this treath

**Comment by hydra3333** [comment]
Final comment from me:

Over at ffmpeg trac https://trac.ffmpeg.org/ticket/10093 there's no action.

I'd not necessarily expect any now, given the time elapsed. 

One will just have to be careful when using an older perfectly good working card and know that if ffmpeg crashes it's likely due to the parameters (and look carefully at the log, the issue was evident in there all along).

**Comment by hydra3333** [comment]
Interestingly, spotted this today:
https://git.videolan.org/gitweb.cgi/ffmpeg.git/?a=commit;h=eb0455d64690eed0068e5cb202f72ecdf899837c
