### ISSUE TITLE
SDL-git Failed - /local64/lib/libSDL2.a Not found

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2335]
20:04:30   Running git update for kvazaar...
20:04:34 kvazaar git  ...................................... [Up-to-date]
20:04:35   Running git clone for SDL...
20:05:05   Running git update for SDL...
20:05:05 ┌ SDL git  .................................. [Recently updated]
20:05:05 ├ Running autogen...
20:05:08 ├ Running configure...
20:07:06 ├ Running make...
20:09:07 ├ Running install...
20:09:10 ├ /local64/lib/libSDL2.a  .......................... [Not found]
20:09:10 └ SDL-git  ............................................ [Failed]

Try deleting '/build/SDL-git' and start the script again.
If you are sure there are no dependencies, <Enter> to continue building.

Close this window if you wish to stop building.

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)

**Comment by ceo-domido** [comment]
I confirm that issue

**Comment by Selur** [comment]
For me it ends at a different position:
```
09:40:55 kvazaar git  ...................................... [Up-to-date]
09:40:59   Running git update for SDL...
09:41:00 ┌ SDL git  ..................................... [Updates found]
09:41:00 ├ Running uninstall...
09:41:00 ├ Running autogen...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
./autogen.sh
/build/media-suite_helper.sh: line 1437: ./autogen.sh: No such file or directory
```
[logs.zip](https://0x0.st/oUIY.zip) 

After deleting the 'build/kvazaar-git'-folder and running the script again, it stops at the same position.

**Comment by Biswa96** [comment]
In the `build/media-suite_compile.sh` file, try to change the line
from
`do_vcs "https://github.com/libsdl-org/SDL.git"`
to
`do_vcs "https://github.com/libsdl-org/SDL.git#SDL2"`

**Comment by Selur** [comment]
Tha seems to work, thanks!

**Comment by LigH-de** [comment]
Created a patch and pull request. 👍 @Biswa96

**Comment by Biswa96** [comment]
This issue may be fixed with this commit https://github.com/m-ab-s/media-autobuild_suite/commit/049e9241c352bba2136aec3cf2efdc75f55ab07e. Please pull the latest changes and try to compile it as usual.
