### ISSUE TITLE
Proposal for Splitting out Reference Links

### ISSUE THREAD

**Issue by softworkz** [m-ab-s/media-autobuild_suite#2340]
Hi,

I want to submit a PR that would make the management of dependency libraries easier and more transparent, but before doing so, I wanted to check back whether this would be agreeable in one or another way.

A problem with the current scripting is that the references to library sources are buried inside and spread all over the script with its 3k lines. It's tedious to follow changes and/or make changes or compare the states from two different points in time.  
Customization of library versions has often be requested in the past, but I understand that this wouldn't end well and would be a nightmare to maintain and support - so I don't want to go as far as that, but just make it a bit easier for those who want to do it (like me) at their own risk.

The change I'm proposing is really simple:

#### Replace all hard-coded source URLs with variables

Like this:

![image](https://user-images.githubusercontent.com/4985349/206343159-a22adf6c-5e25-4afe-a3c4-6bd27f3340d8.png)

#### And put the variable initialization...

![image](https://user-images.githubusercontent.com/4985349/206343414-a7b7c6e8-a998-41c1-af74-0e65133f7d6a.png)

...into a separate file - e.g. `dependency-links.sh`

Then, `media-suite_compile.sh` just needs to run it on start to get all variables set.  
The benefit would be to have all dependency links in one place and easy to review, compare, adjust, etc.

Would this be an acceptable PR? (or something similar in that direction)

Thanks,  
sw

**Comment by 1480c1** [comment]
personally okay with this

**Comment by softworkz** [comment]
Cool, I'll prepare a PR.

A next step could be to think about whether patches should go there as well, maybe?

**Comment by 1480c1** [comment]
Unsure about the patches, unless it's something like a comma separated list of urls+git am/no gitam thing, as patches may often be temporary or semi-permanent depending on the content

**Comment by softworkz** [comment]
> Unsure about the patches, unless it's something like a comma separated list of urls+git am/no gitam thing, as patches may often be temporary or semi-permanent depending on the content

I'm unsure myself. Probably time will tell whether there's a need to. What's on the good side is that the builds don't stop in case a patch is not applicable, so it's not a big problem when there's a version specified to which a patch doesn't apply.

I've submitted the PR now: #2341
