### ISSUE TITLE
Request: [Description] Build for CPU Architecture

### ISSUE THREAD

**Issue by pulp25** [m-ab-s/media-autobuild_suite#2342]
Hi,

Is it possible to build for a special CPU architecture or native CPU architecture using -march=native ou -mtune=native ?
Not a compiler expert so don't know where to put these.

Thanks.

**Comment by 1480c1** [comment]
custom profile options should go inside `$LOCALDESTDIR/etc/custom_profile` (e.g. /local64/etc/custom_profile for 64-bit), this file is sourced after all the options are set by the suite, so you can add `CFLAGS+="-march=native` in there

**Comment by FriedGenera** [comment]
> custom profile options should go inside `$LOCALDESTDIR/etc/custom_profile` (e.g. /local64/etc/custom_profile for 64-bit), this file is sourced after all the options are set by the suite, so you can add `CFLAGS+="-march=native` in there

I don't see a file/folder named `custom_profile` do I have to make it myself?

**Comment by 1480c1** [comment]
You have to make it yourself, it will be sourced like a bash script

**Comment by FriedGenera** [comment]
> You have to make it yourself, it will be sourced like a bash script

Ah so I make a file named `custom_profile.sh` in `/local64/etc/` then add something like-
```
CFLAGS+="-march=native -O3 -pipe -fomit-frame-pointer"
CXXFLAGS+="$CFLAGS"
LDFLAGS+="-Wl,-O1,--sort-common,--as-needed"
```
It'll apply for FFMPEG and all it's dependencies(and also other programs we decide to build)?
