### ISSUE TITLE
error

### ISSUE THREAD

**Issue by HZJ1** [m-ab-s/media-autobuild_suite#2343]
: Starting core system upgrade...
19:35:55 ├ Running build...
Likely error (tail of the failed operation logfile):
[1/44] Generating src_base_ftver.rc with a custom command
FAILED: src_base_ftver.rc_ftver.o
"C:\Tools\msys64\mingw64\bin/windres.EXE" "../src/base/ftver.rc" "src_base_ftver.rc_ftver.o" "--preprocessor-arg=-MD" "--preprocessor-arg=-MQsrc_base_ftver.rc_ftver.o" "--preprocessor-arg=-MFsrc_base_ftver.rc_ftver.o.d"
../src/base/ftver.rc:20: fatal error: when writing output to : Invalid argument
   20 |
      |
compilation terminated.
C:\Tools\msys64\mingw64\bin/windres.EXE: ../src/base/ftver.rc:1: syntax error
C:\Tools\msys64\mingw64\bin/windres.EXE: preprocessing failed.
ninja: build stopped: subcommand failed.
build failed. Check C:/Tools/build/freetype-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
19:35:56   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/onvh.zip
Copy and paste [logs.zip](https://0x0.st/onvh.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

**Comment by 1480c1** [comment]
Haven't been able to reproduce this, if its still an issue, we can reopen
