### ISSUE TITLE
FFmpeg fails to make [hwcontext_vulkan]

### ISSUE THREAD

**Issue by OliverMD15** [m-ab-s/media-autobuild_suite#2345]
Turning off `--enable-vulkan` in ffmpeg_options.txt is a temporary fix
```
05:17:20 ┌ ffmpeg git  ............................... [Recently updated]
05:17:20 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
05:17:24 ├ Compiling static FFmpeg...
05:17:25 ├ Running configure...
05:21:10 ├ Running make...
Likely error (tail of the failed operation logfile):
CC      libavutil/hwcontext_vulkan.o
C:/Download/Media-Autobuild/build/ffmpeg-git/libavutil/hwcontext_vulkan.c:367:7: error: 'VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME' undeclared here (not in a function); did you mean 'VK_EXT_VIDEO_ENCODE_H264_EXTENSION_NAME'?
  367 |     { VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME,                FF_VK_EXT_NO_FLAG                },
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       VK_EXT_VIDEO_ENCODE_H264_EXTENSION_NAME
C:/Download/Media-Autobuild/build/ffmpeg-git/libavutil/hwcontext_vulkan.c:368:7: error: 'VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME' undeclared here (not in a function); did you mean 'VK_EXT_VIDEO_ENCODE_H265_EXTENSION_NAME'?
  368 |     { VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME,                FF_VK_EXT_NO_FLAG                },
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       VK_EXT_VIDEO_ENCODE_H265_EXTENSION_NAM
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10265276/logs.zip)
E
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavutil/hwcontext_vulkan.o] Error 1
make failed. Check C:/Download/Media-Autobuild/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
05:23:52   Creating diagnostics file...```

**Comment by fuchanghao** [comment]
> Probably you need to `git pull` the vulkan repository again to sync with vulkan headers or loaders.

I removed the vulkan repository let m-ab-s re-download and build it same error happened.

**Comment by OliverMD15** [comment]
> Probably you need to `git pull` the vulkan repository again to sync with vulkan headers or loaders.

It was a fresh (kinda) m-a-s install, I freshly pulled everything, yet the error keeps happening.

**Comment by Biswa96** [comment]
The VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME was removed from vulkan headers in this commit https://github.com/KhronosGroup/Vulkan-Headers/commit/00671c64ba5c488ade22ad572a0ef81d5e64c803#diff-b1e4e7ea6a31d516e9a13c9e08028fb3959058081965270ac94d587d9ec1758dL903

I am not sure if this should be reported to ffmpeg. But one can try.

**Comment by Biswa96** [comment]
One temporary workaround might be to `git checkout` a commit in vulkan-headers before that one.

**Comment by Mr-Z-2697** [comment]
`https://github.com/KhronosGroup/Vulkan-Loader.git#sdk-1.3.236`
change vulkan loader source repo link in media-suite_deps.sh to this may be a temporary solution

**Comment by hydra3333** [comment]
> The VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME was removed from vulkan headers (include/vulkan/vulkan_beta.h) in this commit [KhronosGroup/Vulkan-Headers@00671c6#diff-b1e4e7ea6a31d516e9a13c9e08028fb3959058081965270ac94d587d9ec1758dL903](https://github.com/KhronosGroup/Vulkan-Headers/commit/00671c64ba5c488ade22ad572a0ef81d5e64c803#diff-b1e4e7ea6a31d516e9a13c9e08028fb3959058081965270ac94d587d9ec1758dL903)
> 
> I am not sure if this should be reported to ffmpeg. But one can try.

OK, did that. Feel free to comment over there: https://trac.ffmpeg.org/ticket/10115

**Comment by 1480c1** [comment]
Fixed upstream https://github.com/FFmpeg/FFmpeg/commit/eb0455d646

**Comment by OriKovacsiKatz** [comment]
edited the nano <workspace folder>/HandBrake/build/contrib/ffmpeg/ffmpeg-5.1.2/libavutil/hwcontext_vulkan.c the two unknown items (VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME, VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME) removed manually. rebuild using make is successful. 
I didn't try yet to use the HandBrake application but it is running GUI is running well and mkv format file is loaded successfully.
