### ISSUE TITLE
How to build a specific version of FFmpeg

### ISSUE THREAD

**Issue by ggarra13** [m-ab-s/media-autobuild_suite#2347]
I tried building a specific version of ffmpeg, but failed to do so.  I changed the media-autobuild_suite.ini file to have:

ffmpegPath=https://git.ffmpeg.org/ffmpeg.git#tag=n5.1

or similar, but the equal sign of the path gets parsed as another option.  I tried quoting the whole path, backslashing the = sign, etc. all to no avail.

Is there a way to build a specific version of ffmpeg now?  How?

**Comment by 1480c1** [comment]
Are you able to patch your install with
```diff
commit fc7e81b999b8d24718d706a23a854b5bfa6422a9 (HEAD -> asdeps, origin/asdeps)
Author: Christopher Degawa <ccom@randomderp.com>
Date:   Mon Dec 26 16:21:53 2022 -0600

    bat: fix parsing ini file with equal signs in values

diff --git a/media-autobuild_suite.bat b/media-autobuild_suite.bat
index 7d3bbcb89b..f984b476fe 100755
--- a/media-autobuild_suite.bat
+++ b/media-autobuild_suite.bat
@@ -160,7 +160,7 @@ for %%a in (%iniOptions%) do set %%aINI=0
 
 if exist %ini% (
     rem Set INI options to what's found in the inifile
-    for %%a in (%iniOptions%) do for /F "tokens=2 delims==" %%b in ('findstr %%a %ini%') do set %%aINI=%%b
+    for %%a in (%iniOptions%) do for /F "usebackq" %%b in (`powershell -Command "(Select-String -Path "%ini%" -SimpleMatch -Pattern "%%a").Line.Split('=', 2)[1]"`) do set %%aINI=%%b
 ) else set deleteIni=1
 
 setlocal EnableDelayedExpansion
 ```
?

**Comment by ggarra13** [comment]
I patched it but it still did not work.   

$ patch -p 0 --strip 1 < patch.txt
patching file media-autobuild_suite.bat
Hunk #1 succeeded at 159 (offset -1 lines).

If I run it without quotes, I get:
No se esperaba =n5.1==0 en este momento.

If I quote the value, I get:
No se esperaba =n5.1==https://git.ffmpeg.org/ffmpeg.git#tag=n5.1 en este momento

**Comment by 1480c1** [comment]
Huh

**Comment by 1480c1** [comment]
Okay, back to the drawing board

**Comment by 1480c1** [comment]
Pushed https://github.com/m-ab-s/media-autobuild_suite/commit/0ba8b04a74006cf48d7e622dc5a2ac8854eb52ea, it should be working, and I tested it locally as well
