### ISSUE TITLE
CURL Make Failed

### ISSUE THREAD

**Issue by bytos** [m-ab-s/media-autobuild_suite#2356]
Can't we just download a curl executable and place it where ever it is needed and bypass this?

The suite was downloaded today (Win10 x64).

![s](https://user-images.githubusercontent.com/16452541/210647782-5849a34d-d860-473e-be95-192e214f7cc8.jpg)

[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/10354474/ab-suite.make.log)

  CC       tool_vms.o
  CC       tool_writeout.o
  CC       tool_writeout_json.o
  CC       tool_xattr.o
windres -I../../include -DCURL_EMBED_MANIFEST  -i ../../src/curl.rc -o curl.o
cc1.exe: **fatal error**: ../../src/curl.rc: No such file or directory
compilation terminated.
(...)\msys64\mingw64\bin\windres.exe: preprocessing **failed**.
make[2]: *** [Makefile:20200: curl.o] **Error 1**
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/build/curl-git/build-64bit/src'
make[1]: *** [Makefile:1476: all-recursive] **Error 1**
make[1]: Leaving directory '/build/curl-git/build-64bit/src'
make: *** [Makefile:1247: all-recursive] **Error 1**
Making all in lib
make[1]: Entering directory '/build/curl-git/build-64bit/lib'
make  all-am
make[2]: Entering directory '/build/curl-git/build-64bit/lib'
make[2]: Leaving directory '/build/curl-git/build-64bit/lib'
make[1]: Leaving directory '/build/curl-git/build-64bit/lib'
Making all in src
make[1]: Entering directory '/build/curl-git/build-64bit/src'
Making all in ../docs
make[2]: Entering directory '/build/curl-git/build-64bit/docs'
Making all in .
make[3]: Entering directory '/build/curl-git/build-64bit/docs'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/build/curl-git/build-64bit/docs'
Making all in cmdline-opts
make[3]: Entering directory '/build/curl-git/build-64bit/docs/cmdline-opts'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/build/curl-git/build-64bit/docs/cmdline-opts'
make[2]: Leaving directory '/build/curl-git/build-64bit/docs'
make[2]: Entering directory '/build/curl-git/build-64bit/src'
  CC       tool_hugehelp.o
  CC       ../lib/strtoofft.o
  CC       ../lib/timediff.o
  CC       ../lib/nonblock.o
  CC       ../lib/warnless.o
  CC       ../lib/curl_multibyte.o
  CC       ../lib/version_win32.o
  CC       ../lib/dynbuf.o
windres -I../../include -DCURL_EMBED_MANIFEST  -i ../../src/curl.rc -o curl.o
cc1.exe: fatal error: ../../src/curl.rc: **No such file or directory**
compilation terminated.
(...)\msys64\mingw64\bin\windres.exe: preprocessing **failed**.
make[2]: *** [Makefile:20200: curl.o] **Error 1**
make[2]: Leaving directory '/build/curl-git/build-64bit/src'
make[1]: *** [Makefile:1476: all-recursive] **Error 1**
make[1]: Leaving directory '/build/curl-git/build-64bit/src'
make: *** [Makefile:1247: all-recursive] **Error 1**

**Comment by 1480c1** [comment]
> Can't we just download a curl executable and place it where ever it is needed and bypass this?

main purpose of compiling curl is for the library and being able to link it to a specific ssl library rather than relying on msys2's, supposing the user worries about licensing etc. so the executable isn't really needed at all, that can be controlled by the standalone option.

I haven't run into this problem, so I don't know if it's still valid, but I'm going to assume its not anymore

**Comment by bytos** [comment]
Still not able to compile CURL ..

> compile.log:

make[2]: *** [Makefile:1989: curl.o] Error 1
make[2]: Leaving directory '/build/curl-git/build-64bit/src'
make[1]: *** [Makefile:1481: all-recursive] Error 1
make[1]: Leaving directory '/build/curl-git/build-64bit/src'
make: *** [Makefile:1254: all-recursive] Error 1
[31mmake failed. Check /build/curl-git/build-64bit/ab-suite.make.log(B[m
[31mThis is required for other packages, so this script will exit.(B[m
  Creating diagnostics file...

[32mAttach \build\logs.zip to the GitHub issue.(B[m
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
[?2004h[?2004l

Try running the build again at a later time.

> ab-suite.make.log:

  CCLD     libcurl.la
make[2]: Leaving directory '/build/curl-git/build-64bit/lib'
make[1]: Leaving directory '/build/curl-git/build-64bit/lib'
Making all in src
make[1]: Entering directory '/build/curl-git/build-64bit/src'
Making all in ../docs
make[2]: Entering directory '/build/curl-git/build-64bit/docs'
Making all in .
make[3]: Entering directory '/build/curl-git/build-64bit/docs'
if test "..x" != "../..x" -a -e "../../docs/curl.1"; then \
	/usr/bin/install -c -m 644 "../../docs/curl.1" /build/curl-git/build-64bit/docs/curl.1; fi
cd cmdline-opts && make
make[4]: Entering directory '/build/curl-git/build-64bit/docs/cmdline-opts'
  GENERATE ../../docs/curl.1
make[4]: Leaving directory '/build/curl-git/build-64bit/docs/cmdline-opts'
make[3]: Leaving directory '/build/curl-git/build-64bit/docs'
Making all in cmdline-opts
make[3]: Entering directory '/build/curl-git/build-64bit/docs/cmdline-opts'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/build/curl-git/build-64bit/docs/cmdline-opts'
make[2]: Leaving directory '/build/curl-git/build-64bit/docs'
make[2]: Entering directory '/build/curl-git/build-64bit/src'
