### ISSUE TITLE
[mingw32] ffmpeg

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#2360]
```
20:29:02 ┌ ffmpeg git  ............................... [Recently updated]
20:29:02 ├ Changing options to comply to gplv3...
20:29:03 ├ Compiling static FFmpeg...
20:29:04 ├ Running configure...
20:31:57 ├ Running make...
Likely error (tail of the failed operation logfile):
    inlined from 'get_cabac' at I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/cabac_functions.h:145:12,
    inlined from 'decode_cabac_mb_intra4x4_pred_mode' at I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/h264_cabac.c:1377:9,
    inlined from 'ff_h264_decode_mb_cabac' at I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/h264_cabac.c:2081:32:
I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
  199 |     __asm__ volatile(
      |     ^~~~~~~
I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/h264_cabac.o] Error 1
make failed. Check I:/media-autobuild_suite/build/ffmpeg-git/build-static-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
20:33:13   Creating diagnostics file...

Attach I:\media-autobuild_suite\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
```

**Comment by maxiuca** [comment]
This error was discussed in another thread: 
https://github.com/m-ab-s/media-autobuild_suite/issues/1660#issuecomment-1374136382

I ran my last build on Dec 17 and 32b FFmpeg compiled fine, but now I'm getting the same error, so I assume that one of the latest commits is the reason. 

I suspect that one of the libx264 commits from Jan 4 caused this issue.

**Comment by Biswa96** [comment]
Side question. Why are you compiling 32 bit ffmpeg? Asking this because some upstream projects are removing 32 bit support.

**Comment by Selur** [comment]
(like LigH-de pointed out) the 'Dropping support of 32-bit build' is the wrong place for a bug report, which is why I posted a new thread.

I compile it to use with Avisynth 32bit. Sadly, there are a bunch of filters which are available for Avisynth 32bit and not 64bit.

**Comment by maxiuca** [comment]
@Selur
My only intention was to point to you that thread and LigH-de explanation

@Biswa96 
Same reason Selur has mentioned: old 32b Avisynth's unique filters that aren't available for 64b

**Comment by 1480c1** [comment]
I submitted a patch a while ago for this https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230102230128.972907-1-ccom@randomderp.com/, seems to be an issue between the compiler's `-mtune=generic` and `-mtune=i686`

**Comment by Selur** [comment]
could that path be applied to the build script to that thinks work again?

**Comment by 1480c1** [comment]
Right now testing it locally before I push the commit

**Comment by Selur** [comment]
thanks :)

**Comment by 1480c1** [comment]
pushed https://github.com/m-ab-s/media-autobuild_suite/commit/7ce4160867383b912da7ed5be7a41d2cf6a4ff43

**Comment by Selur** [comment]
Could you also check that the patch gets applied when compilng ffmpeg for mplayer?
```
19:07:16 ┌ ffmpeg git  ............................... [Recently updated]
19:07:16 ├ Changing options to comply to gplv3...
19:07:19 ├ Compiling static FFmpeg...
19:07:19 ├ Running configure...
19:10:23 ├ Running make...
19:14:49 ├ Running install...
19:14:51 ├ Stripping...
19:14:51 └ ffmpeg-git  ........................................ [Updated]
19:14:53   Running svn update for mplayer...
19:14:54 ┌ mplayer svn  ................................. [Updates found]
19:14:54 ├ Running distclean...
19:15:01 ├ Running configure...
19:16:29 ├ Running install...
Likely error (tail of the failed operation logfile):
    inlined from 'ff_h264_decode_mb_cabac' at libavcodec/h264_cabac.c:2081:32:
libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
  199 |     __asm__ volatile(
      |     ^~~~~~~
libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
make[1]: *** [ffbuild/common.mak:81: libavcodec/h264_cabac.o] Error 1
make[1]: Leaving directory '/build/mplayer-svn/ffmpeg'
make: *** [Makefile:744: ffmpeg/libavcodec/libavcodec.a] Error 2
install failed. Check I:/media-autobuild_suite/build/mplayer-svn/ab-suite.install.log
This isn't required for anything so we can move on.
19:20:47 ├ /local32/bin-video/mplayer.exe  .................. [Not found]
19:20:47 └ mplayer-svn  ........................................ [Failed]
Package failed to build, but is not required; proceeding with compilation.
```

**Comment by 1480c1** [comment]
Ah, forgot to add it for mplayer, pushed new commit

**Comment by Selur** [comment]
thanks 👍

**Comment by maxiuca** [comment]
@1480c1 Thank you for pushing the new commit and sorry for replying in a closed thread, but I just tried to compile the 32b tools (after compiling 64b tools without any issues), but I'm still getting the error that the OP posted (see below). 

I guess I'm doing something wrong, but I can't figure out what. I will be grateful if anyone has an idea.


`14:59:55   Running git update for ffmpeg...
14:59:56 ┌ ffmpeg git  .................................. [Updates found]
14:59:56 ├ Changing options to comply to nonfree...
15:00:03 ├ Compiling static FFmpeg...
15:00:04 ├ Running configure...
15:04:44 ├ Running make...
Likely error (tail of the failed operation logfile):
    inlined from 'get_cabac' at C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/cabac_functions.h:145:12,
    inlined from 'decode_cabac_mb_intra4x4_pred_mode' at C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/h264_cabac.c:1377:9,
    inlined from 'ff_h264_decode_mb_cabac' at C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/h264_cabac.c:2081:32:
C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
  199 |     __asm__ volatile(
      |     ^~~~~~~
C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
C:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/h264_cabac.o] Error 1
make failed. Check C:/media-autobuild_suite/build/ffmpeg-git/build-static-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
15:06:35   Creating diagnostics file...
`

**Comment by 1480c1** [comment]
Can't help you much without any logs, but check to make sure that you have pulled the latest commits

**Comment by maxiuca** [comment]
Yeah, I'm stupid, for some reason I thought you pushed a commit to the x264 branch, not the m-ab_s branch... Bad brain fart... I'm very sorry
