### ISSUE TITLE
[REQ] SoX (sox.exe)

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2365]
@1480c1 
Would it be possible for you to add a separate build option for SoX (sox.exe)?

As it's now so does it get built due to dependencies to other binaries used in the suite. I would be very thankful if it could be added as a separate build option using the the official repo (https://sourceforge.net/p/sox/code/ci/master/tree/) since that's most up to date. Info on the official repo being most up to date and should be stable comes from @mansr (1 of the SoX devs)

Quote from @mansr
> The official repo (https://sourceforge.net/p/sox/code/ci/master/tree/) is the most up to date. Although there is no recent tagged release, the master branch should be stable.

**Comment by 1480c1** [comment]
Just to confirm, do you mean sox.exe? We currently pull 14.4.2
```bash
if [[ $sox = y ]] && do_pkgConfig "sox = 14.4.2" &&
    do_wget_sf -h ba804bb1ce5c71dd484a102a5b27d0dd "sox/sox/14.4.2/sox-14.4.2.tar.bz2"
```
and it's gated behind the `Build sox binaries [Sound processing tool]?` question. Your second request is for it to be build using the git repo instead?

**Comment by Barough** [comment]
Yup i, talking about sox.exe and requesting it to be built from the official repo instead of using the 'sox-14.4.2.tar.bz2'

**Comment by Barough** [comment]
> @1480c1 Would it be possible for you to add a separate build option for SoX (sox.exe)?
> 
> As it's now so does it get built due to dependencies to other binaries used in the suite. I would be very thankful if it could be added as a separate build option using the the official repo (https://sourceforge.net/p/sox/code/ci/master/tree/) since that's most up to date. Info on the official repo being most up to date and should be stable comes from @mansr (1 of the SoX devs)

Quote from @mansr
> The official repo (https://sourceforge.net/p/sox/code/ci/master/tree/) is the most up to date. Although there is no recent tagged release, the master branch should be stable.

**Comment by 1480c1** [comment]
pushed 89f8a47e4a

**Comment by Barough** [comment]
Would be great to see a build option in the 'media-autobuild_suite.ini' file then i just being built due to external dependencies
