### ISSUE TITLE
AVS3 codec in ffmpeg and dependency lib (windows)

### ISSUE THREAD

**Issue by Murmur** [m-ab-s/media-autobuild_suite#2366]
**AVS3 video codec in ffmpeg and dependency uavs3d library**
https://www.ffmpeg.org/general.html#uavs3d
https://github.com/uavs3/uavs3d
Editing `build/ffmpeg_options.txt: --enable-libuavs3d` .

is anyone tried AVS3 codec compilation on windows, maybe one day a simple on/off option in `build/media-autobuild_suite.ini` options list?

Script may have uavs3d import already in place but how do I enable in an existing m-ab-s folder, I have regulary run `update_suite.sh` script.

```
------------------------- build/media-suite_compile.sh ----
index d68ff29..a8d3440 100644
@@ -1326,6 +1326,7 @@ _check=(libuavs3d.a uavs3d.{h,pc})
 [[ $standalone = y ]] && _check+=(bin-video/uavs3dec.exe)
 if [[ $ffmpeg != no ]] && enabled libuavs3d &&
     do_vcs "https://github.com/uavs3/uavs3d.git"; then
+    do_patch "https://github.com/uavs3/uavs3d/pull/29.patch"
     do_cmakeinstall
     [[ $standalone = y ]] && do_install uavs3dec.exe bin-video/
     do_checkIfExist
```

**Comment by 1480c1** [comment]
uavs3d compiled and links fine for me

```bash
 D.V.L. avs                  AVS (Audio Video Standard) video
 ..V.L. avs2                 AVS2-P2/IEEE1857.4
 D.V.L. avs3                 AVS3-P2/IEEE1857.10 (decoders: libuavs3d )
 DEV.L. cavs                 Chinese AVS (Audio Video Standard) (AVS1-P2, JiZhun profile) (encoders: libxavs )
 ```

to enable it on an existing mabs, you need to edit build/media-autobuild_suite.ini and change `ffmpegChoice` to either 1 or 4, and if you select 1, you add the line to ffmpeg_options.txt

**Comment by Murmur** [comment]
Thanks, I deleted `ffmpeg_options.txt` and all works now, old file were missing proper `--enable-xxxx` flags.
