### ISSUE TITLE
Can we find a way to use specific revisions of SPIRV and GLSLANG?

### ISSUE THREAD

**Issue by softworkz** [m-ab-s/media-autobuild_suite#2367]
shaderc is very picky with regards to its dependencies and yet we are always just cloning the latest HEAD of 

```
SOURCE_REPO_GLSLANG=https://github.com/KhronosGroup/glslang.git
SOURCE_REPO_SPIRV_CROSS=https://github.com/KhronosGroup/SPIRV-Cross.git
SOURCE_REPO_SPIRV_HEADERS=https://github.com/KhronosGroup/SPIRV-Headers.git
SOURCE_REPO_SPIRV_TOOLS=https://github.com/KhronosGroup/SPIRV-Tools.git
```

...which sometimes doesn't end well - like today:

```
CMake Error at third_party/spirv-tools/CMakeLists.txt:33 (message):
  SPIRV-Tools requires C++17 or later, but is configured for C++11)
```

They have added that requirement just a week ago or so. 

Unlike with most other URLs, it's not possible to specify a revision in the URL  
(like  `https://github.com/KhronosGroup/SPIRV-Cross.git#revision=xxxxxx`). 

That would fail like here:

```
git clone --depth 1 https://github.com/KhronosGroup/SPIRV-Cross.git#revision=c77b09b57c27837dc2d41aa371ed3d236ce9ce47 third_party/spirv-cross
Cloning into 'third_party/spirv-cross'...
fatal: unable to update url base from redirection:
  asked for: https://github.com/KhronosGroup/SPIRV-Cross.git#revision=c77b09b57c27837dc2d41aa371ed3d236ce9ce47/info/refs?service=git-upload-pack
   redirect: https://github.com/KhronosGroup/SPIRV-Cross
             https://github.com/KhronosGroup/SPIRV-Cross.git

spirv-cross-clone failed. Check D:/a/1/s/build/shaderc-git/ab-suite.spirv-cross-clone.log
```

IIUC, this is because the code isn't using do_vcs for cloning but this instead:

`media-suite_compile.sh:`
```
        add_third_party() {
            local repo=$1
            local name=$2
            [[ ! $name ]] && name=${repo##*/} && name=${name%.*}
            local dest=third_party/$name

            if [[ -d $dest/.git ]]; then
                log "$name-reset" git -C "$dest" reset --hard "@{u}"
                log "$name-pull" git -C "$dest" pull
            else
                log "$name-clone" git clone --depth 1 "$repo" "$dest"
            fi
        }

        add_third_party "$SOURCE_REPO_GLSLANG"
        add_third_party "$SOURCE_REPO_SPIRV_TOOLS" spirv-tools
        add_third_party "$SOURCE_REPO_SPIRV_HEADERS" spirv-headers
        add_third_party "$SOURCE_REPO_SPIRV_CROSS" spirv-cross

```

I don't quire understand the above, especially not the "@{u}" part (but I have  no passion in shell scripts..).
And why doesn't it use do_vcs?

What would be the best way for allowing to have revisions in the git urls for these 4 repos?

Thanks,
softworkz

**Comment by softworkz** [comment]
Or maybe it's  better to just use the exact revisions that shaderc is indicating in the DEPS file?

https://github.com/google/shaderc/blob/main/DEPS

**Comment by 1480c1** [comment]
> I don't quire understand the above, especially not the "@{u}" part 

"@{u}" for git is short hand for upstream

> And why doesn't it use do_vcs?

That would cause the resulting folders to be under /build/<name>-git rather than under `third_party/<name>`

> What would be the best way for allowing to have revisions in the git urls for these 4 repos?

One could be to modify the `add_third_party` function to use similar logic to `do_vcs` to extract a commit/branch to reset to

> Or maybe it's  better to just use the exact revisions that shaderc is indicating in the DEPS file?

I don't remember if we ever tried that, it might be, as long as it doesn't interfere with anything outside shaderc

**Comment by softworkz** [comment]
Thanks. I have created a `do_vcs_local()` for this. Will test it a bit more before submitting.
