### ISSUE TITLE
Dependency URLs with `#tag=tagname` do not check out the specified tag

### ISSUE THREAD

**Issue by softworkz** [m-ab-s/media-autobuild_suite#2368]
Dependency URLs with `#tag=tagname` do not check out the specified tag

### Example

Specifying

```bash
SOURCE_REPO_FFNVCODEC=https://git.videolan.org/git/ffmpeg/nv-codec-headers.git#tag=n11.0.10.1
```

will check out HEAD instead of the tag, while

```bash
SOURCE_REPO_FFNVCODEC=https://git.videolan.org/git/ffmpeg/nv-codec-headers.git#revision=27b5db61c9eb4b98d3f565cecf8713b4ecabd990
```

actually checks out the specified revision.

**Comment by 1480c1** [comment]
I think I found the reason, `git reset --hard origin/v0.9.1` doesn't work, `git reset --hard v0.9.1` does

**Comment by softworkz** [comment]
Ah, great. TBH, I couldn't quite follow what the code is doing exactly. I haven't seen any point where it would make a distinction between whether the url has `#revision=`, `#branch=` or `#tag=`

Or doesn't it even make any?

**Comment by 1480c1** [comment]
It doesn't, that's probably the issue

**Comment by 1480c1** [comment]
I think I will take the route of first trying to resolve a name to a remote commit hash or a local hash if possible

**Comment by softworkz** [comment]
When it's too involved, then we can also stick to pin by revision and note the tag in a comment.

**Comment by 1480c1** [comment]
Well, I got something for now
```bash
vcs_ref_to_hash() (
    vcsURL=$1 ref=$2 vcsFolder=${3:-$(basename "$vcsURL" .git)}
    if _ref=$(git ls-remote --refs --exit-code -q -- "$vcsURL" "$ref"); then
        cut -f1 <<< "$_ref"
        return 0
    fi
    if git -C "$vcsFolder-git" rev-parse --verify -q --end-of-options "$ref" 2> /dev/null ||
        git -C "$vcsFolder" rev-parse --verify -q --end-of-options "$ref" 2> /dev/null ||
        git rev-parse --verify -q --end-of-options "$ref" 2> /dev/null; then
        return 0
    fi
    return 1
)
```

**Comment by 1480c1** [comment]
Can you try https://github.com/m-ab-s/media-autobuild_suite/commit/5b351a2813c368ad712962efb490efd13d090c4a ?

**Comment by softworkz** [comment]
I still have an earlier vesion of the deps file with all specified as tags. Together that will make a nice combination for a CI build test run. 

Right now I have 6 different local MABS installations and 3 on Azure, which means I need to consolidate as long as I have full  overview. But that won't take long.

**Comment by softworkz** [comment]
A very first build run https://dev.azure.com/githubsync/mas/_build/results?buildId=27524&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a

**Comment by 1480c1** [comment]
I wonder which git command the `fatal: Not a valid object name` message is from

**Comment by softworkz** [comment]
I thought I'd know what it is, but now that it also appears without any customizations, my theory is moot :wink:

**Comment by softworkz** [comment]
> Can you try [5b351a2](https://github.com/m-ab-s/media-autobuild_suite/commit/5b351a2813c368ad712962efb490efd13d090c4a) ?

I've fired up a build now with your changes and an earlier version of the deps file which is using tags:

[https://dev.azure.com/githubsync/mas/_build/results?buildId=27526&view=results](https://dev.azure.com/githubsync/mas/_build/results?buildId=27526&view=results)

It will fail by guarantee, but hopefully it fails only after we got sufficient proof that tags are working now.

**Comment by softworkz** [comment]
The build has failed on libTiff - and that means that your patch is working!  
(because it fails with v4.4.0 but not with current HEAD, so the error means that it has actually pulled 4.4.0)

So tags are fixed, thanks a lot for the quick response!
