### ISSUE TITLE
[mingw32|mingw64] [repo] compilation error with librtmp

### ISSUE THREAD

**Issue by vrunk11** [m-ab-s/media-autobuild_suite#2372]
i'm trying to build ffmpeg (x64) for windows with VVC encoder / decoder folowing the instruction here : https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration

then at compilation i tried diferent setting with a reduced number of library (i tried with clang and GCC) and it said there is an error everytime with librtmp and it can't proceed

the error is abount undefined reference "__imp___gmpz_something"

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10579480/logs.zip)

**Comment by Biswa96** [comment]
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2352

**Comment by 1480c1** [comment]
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2352
