### ISSUE TITLE
Error running make when update ffmpeg  - src/libavcodec/libsvt_vp9.c:692:46: error: 'AV_CODEC_CAP_AUTO_THREADS' undeclared here (not in a function); did you mean 'FF_CODEC_CAP_AUTO_THREADS'?

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2376]
17:25:21   Running git update for ffmpeg...
17:26:23 ┌ ffmpeg git  .................................. [Updates found]
17:26:23 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
17:26:35 ├ Compiling static FFmpeg...
17:26:36 ├ Running uninstall...
17:26:36 ├ Running configure...
17:31:58 ├ Running make...
Likely error (tail of the failed operation logfile):
      |     ^~~~~~~
src/libavcodec/libsvt_vp9.c:530:18: warning: unused variable 'ref' [-Wunused-variable]
  530 |     AVBufferRef *ref;
      |                  ^~~
src/libavcodec/libsvt_vp9.c: At top level:
src/libavcodec/libsvt_vp9.c:692:46: error: 'AV_CODEC_CAP_AUTO_THREADS' undeclared here (not in a function); did you mean 'FF_CODEC_CAP_AUTO_THREADS'?
  692 |     .p.capabilities   = AV_CODEC_CAP_DELAY | AV_CODEC_CAP_AUTO_THREADS,
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                              FF_CODEC_CAP_AUTO_THREADS
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/libsvt_vp9.o] Error 1
make failed. Check C:/MinGW-w64/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
17:44:17   Creating diagnostics file...

Attach C:\MinGW-w64\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10713085/logs.zip)
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/10713088/ab-suite.make.log)

**Comment by Fishman0919** [comment]
Same here...

**Comment by LigH-de** [comment]
Possibly a change in the ffmpeg API towards v6.0?

Could report this [upstream](https://github.com/OpenVisualCloud/SVT-VP9) if that seems sensible.
