### ISSUE TITLE
/build/media-suite_helper.sh: line 1509: ../configure: No such file or directory

### ISSUE THREAD

**Issue by clostou** [m-ab-s/media-autobuild_suite#2377]
An error occurred when compiling. I've retried serveral times but nothing changes. I'm not familiar with these tools so hoping anyone could tell me what is wrong, thanks!

In addition I think it's not problem of network. Because in previous steps that kind of errors have happened. Then I set proxy in ab_suite\local64\etc\custom_profile and it does works.

The infos terminal displayed are as follows:

Starting 64bit compilation of video tools
  Running git update for librtmp...
librtmp git  ................................................ [Up-to-date]
  Running git clone for vpx...
  Running git update for vpx...
┌ vpx git  ............................................ [Recently updated]
├ Running configure...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
../configure --prefix=/local64 --target=x86_64-win64-gcc --disable-shared --disable-unit-tests --disable-docs --disable-install-bins --disable-examples --disable-webm-io --disable-libyuv --disable-postproc --enable-vp9-postproc --enable-vp9-highbitdepth
/build/media-suite_helper.sh: line 1509: ../configure: No such file or directory
configure failed. Check E:/ab_suite/build/build-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

And log archive here: [logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10716391/logs.zip)

**Comment by 1480c1** [comment]
I'm not entirely sure what happened there, normally, your logs would have the vpx-git folder, and then under that it would have the build-64bit folder. Just to confirm, you did try deleting any traces of `vpx-git` under the build folder? Could you also check if there is a `build-64bit` folder directly under the build folder? If so, can you also try deleting that as well? It clone and builds fine locally.

**Comment by clostou** [comment]
Great thoughts! Today I try executing the suits again after removing 'vpx-git' and 'build-64bit' these two folders in 'build' folder of root directory, then it compiles successfully.
Although the reasons behind are still unclear it's quite enough to have a pratical solution enabling my subsequent use and learning. Done me a great service, thank you! )
