### ISSUE TITLE
[mingw64] [vulkan-loader]

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2378]
16:27:01 ┌ vulkan-loader git  ........................ [Recently updated]
16:27:01 ├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
16:27:08 ├ Running dependencies...
16:29:54 ├ Installing Vulkan-Headers...
16:29:54 ├ Running uninstall...
16:29:54 ├ Running cmake...
16:29:57 ├ Running build...
16:29:57 ├ Running install...
16:29:59 ├ Building Vulkan-Loader...
16:29:59 ├ Running cmake...
16:30:04 ├ Running build...
Likely error (tail of the failed operation logfile):
ninja: fatal: GetOverlappedResult: ▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒.

FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml  -IC:/ffmpeg-autobuild/build/vulkan-loader-git/build-64bit/loader -IC:/ffmpeg-autobuild/local64/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj C:/ffmpeg-autobuild/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
[1/20] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml  -IC:/ffmpeg-autobuild/build/vulkan-loader-git/build-64bit/loader -IC:/ffmpeg-autobuild/local64/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj C:/ffmpeg-autobuild/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10733321/logs.zip)

**Comment by LigH-de** [comment]
Similar results here, **ab-suite.build.log** with {local system message translated to English}:
```
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe -DSTRSAFE_NO_DEPRECATE
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
ninja -j4 
[1/23] Building C object loader/CMakeFiles/asm_offset.dir/asm_offset.c.obj
In file included from G:/MABS/build/vulkan-loader-git/loader/vk_loader_platform.h:34,
                 from G:/MABS/build/vulkan-loader-git/loader/loader_common.h:37,
                 from G:/MABS/build/vulkan-loader-git/loader/asm_offset.c:26:
G:/MABS/msys64/mingw32/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
   15 | #warning Please include winsock2.h before windows.h
      |  ^~~~~~~
[2/23] Linking C executable loader\asm_offset.exe
[3/23] Generating gen_defines.asm
[4/23] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ninja: fatal: GetOverlappedResult: {Invalid handle}


FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj 
ml  -IG:/MABS/build/vulkan-loader-git/build-32bit/loader -IG:/MABS/local32/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj G:/MABS/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
[1/20] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj 
ml  -IG:/MABS/build/vulkan-loader-git/build-32bit/loader -IG:/MABS/local32/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj G:/MABS/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
```

**Comment by LigH-de** [comment]
The report has been rejected upstream, it is not intended to be supported over there. Must be solved here or not at all.

**Comment by L4cache** [comment]
Yeah, those guys really know how to f**k up things and to not fix them.

**Comment by Biswa96** [comment]
The build issue is not related to upstream. So, it is expected that the upstream issue will be closed. The vulkan patch file of this m-ab-s project has to be rebased, see this commit https://github.com/m-ab-s/mabs-patches/commit/9550f90e7468c980b3dc8863d0bbd99d67fa10a5.
