### ISSUE TITLE
[mingw32|mingw64] [repo]

### ISSUE THREAD

**Issue by newcapricasean** [m-ab-s/media-autobuild_suite#2380]
``` bash
21:18:06 Warning: We will not accept any issues lacking any form of logs or logs.zip!
21:18:06
        Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
21:19:20
        Starting 64bit compilation of global tools
21:19:20 ├ Running download_rustup...
21:19:21 ├ Running install_rust...
21:19:57 ├ Stripping...
21:19:57 └ rustinstall  ....................................... [Updated]
warning: could not canonicalize path: 'Z:\media-autobuild_suite-master\build'
warning: could not canonicalize path: 'Z:\media-autobuild_suite-master'
warning: could not canonicalize path: 'Z:\'
21:19:58 ├ Running rustup_update...
Likely error (tail of the failed operation logfile):
LDFLAGS: -pipe -static-libgcc -static-libstdc++
/opt/cargo/bin/rustup.exe update
info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'
info: checking for self-updates

  stable-x86_64-pc-windows-gnu unchanged - rustc 1.67.1 (d5a82bbd2 2023-02-07)

info: cleaning up downloads & tmp directories
thread 'main' panicked at 'Unable to clean up Z:/media-autobuild_suite-master/msys64/opt/cargo\downloads: Os { code: 1, kind: Uncategorized, message: "Incorrect function." }', src\utils\utils.rs:649:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
rustup_update failed. Check Z:/media-autobuild_suite-master/build/ab-suite.rustup_update.log
This is required for other packages, so this script will exit.
21:19:59   Creating diagnostics file...

Attach Z:\media-autobuild_suite-master\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
















```

***
Microsoft Windows [Version 10.0.22621.1265]
(c) Microsoft Corporation. All rights reserved.

C:\Users\newca>Z:

Z:\>cd media-autobuild_suite-master

Z:\media-autobuild_suite-master>media-autobuild_suite.bat
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Select the build target system:
 1 = both [32 bit and 64 bit]
 2 = 32 bit build system
 3 = 64 bit build system

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build System: 3
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build FFmpeg with which license?
 1 = Non-free [unredistributable, but can include anything]
 2 = GPLv3 [disables OpenSSL and FDK-AAC]
 3 = GPLv2.1
   [Same disables as GPLv3 with addition of gmp, opencore codecs]
 4 = LGPLv3
   [Disables x264, x265, XviD, GPL filters, etc.
    but reenables OpenSSL/FDK-AAC]
 5 = LGPLv2.1 [same disables as LGPLv3 + GPLv2.1]

 If building for yourself, it's OK to choose non-free.
 If building to redistribute online, choose GPL or LGPL.
 If building to include in a GPLv2.1 binary, choose LGPLv2.1 or GPLv2.1.
 If you want to use FFmpeg together with closed source software, choose LGPL
 and follow instructions in https://www.ffmpeg.org/legal.html

 OpenSSL and FDK-AAC have licenses incompatible with GPL but compatible
 with LGPL, so they won't be disabled automatically if you choose LGPL.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
FFmpeg license: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build standalone binaries for libraries included in FFmpeg?
 eg. Compile opusenc.exe if --enable-libopus
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build standalone binaries: 2
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build vpx [VP8/VP9 encoder]?
 1 = Yes
 2 = No

 Binaries being built depends on "standalone=y"

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build vpx: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build aom [Alliance for Open Media codec]?
 1 = Yes
 2 = No

 Binaries being built depends on "standalone=y"

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build aom: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build rav1e [Alternative, faster AV1 standalone encoder]?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build rav1e: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build dav1d [Alternative, faster AV1 decoder]?
 1 = Yes
 2 = No

 Binaries being built depends on "standalone=y" and are always static.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build dav1d: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build libavif [AV1 image format encoder and decoder]?
 1 = Yes
 2 = No

 Binaries being built depends on "standalone=y" and are always static.
 Will build aom, dav1d, and rav1e if not already previously enabled

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build libavif: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build jpeg-xl tools [JPEG XL image format encoder and decoder]?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build jpegxl: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build x264 [H.264 encoder]?
 1 = Lib/binary with 8 and 10-bit
 2 = No
 3 = Lib/binary with only 10-bit
 4 = Lib/binary with 8 and 10-bit, and libavformat and ffms2
 5 = Shared lib/binary with 8 and 10-bit
 6 = Same as 4 with video codecs only (can reduce size by ~3MB)
 7 = Lib/binary with only 8-bit

 Binaries being built depends on "standalone=y" and are always static.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build x264: 4
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build x265 [H.265 encoder]?
 1 = Lib/binary with Main, Main10 and Main12
 2 = No
 3 = Lib/binary with Main10 only
 4 = Lib/binary with Main only
 5 = Lib/binary with Main, shared libs with Main10 and Main12
 6 = Same as 1 with XP support and non-XP compatible x265-numa.exe
 7 = Lib/binary with Main12 only

 Binaries being built depends on "standalone=y"

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build x265: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build Kvazaar? [H.265 encoder]
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build kvazaar: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build SVT-HEVC? [H.265 encoder]
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build SVT-HEVC: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build xvc? [HEVC and AV1 competitor]
 1 = Yes
 2 = No

 Any issues with this will be considered low-priority due to lack of
 potential stability
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build xvc: 2
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build VVC Reference Software? [H.265 successor enc/decoder]
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build vvc: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build uvg266? [H.266 encoder by ultravideo, the Kvazaar team]
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build uvg266: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build vvenc? [Fraunhofer HHI Versatile Video Encoder]
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build vvenc: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build vvdec? [Fraunhofer HHI Versatile Video Decoder]
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build vvdec: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build SVT-AV1? [AV1 encoder]
 1 = Yes
 2 = No

 Look at the link for hardware requirements
 https://github.com/OpenVisualCloud/SVT-AV1/blob/master/README.md#Hardware

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build SVT-AV1: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build SVT-VP9? [VP9 encoder]
 1 = Yes
 2 = No

 Look at the link for hardware requirements
 https://github.com/OpenVisualCloud/SVT-VP9#Hardware

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build SVT-VP9: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build FLAC? [Free Lossless Audio Codec]
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build flac: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build FDK-AAC library and binary? [AAC-LC/HE/HEv2 codec]
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build fdkaac: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build FAAC library and binary? [old, low-quality and nonfree AAC-LC codec]
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build faac: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build exhale binary? [open-source ISO/IEC 23003-3 USAC, xHE-AAC encoder]
 1 = Yes
 2 = No

 Binaries being built do not depend on "standalone=y"

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build exhale: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build mediainfo binaries [Multimedia file information tool]?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build mediainfo: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build sox binaries [Sound processing tool]?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build sox: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build FFmpeg binaries and libraries:
 1 = Yes [static] [recommended]
 2 = No
 3 = Shared
 4 = Both static and shared [shared goes to an isolated directory]
 5 = Shared-only with some shared dependencies (libass, freetype and fribidi)
 6 = Same as 4, but static compilation ignores shared dependencies

 Note: Option 5 differs from 3 in that libass, freetype and fribidi are
 compiled shared so they take less space. Currently broken if libass or libass
 dependees are enabled.
 Option 6 produces static and shared ffmpeg and ffmpeg libs where the static
 one includes only strictly static dependencies (opencl, opengl, cuda-nvcc,
 libnpp, libopenh264 are hard disabled.)

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build FFmpeg: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Using default ffmpeg source path: https://git.ffmpeg.org/ffmpeg.git

 If you want to use a custom source repository, add a line like this
 to media-autobuild_suite.ini:

     ffmpegPath=https://github.com/username/FFmpeg.git#branch=branchname

 or for a local repository like:

     ffmpegPath=../myrepos/ffmpeg

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Always build FFmpeg when libraries have been updated?
 1 = Yes
 2 = No
 3 = Only build FFmpeg/mpv and missing dependencies

 FFmpeg is updated a lot so you only need to select this if you
 absolutely need updated external libraries in FFmpeg.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build ffmpeg if lib is new: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Choose ffmpeg and mpv optional libraries?
 1 = Yes
 2 = No (Light build)
 3 = No (Mimic Zeranoe)
 4 = No (All available external libs)

 Avoid the last two unless you really want useless libraries you'll never use.
 Just because you can include a shitty codec no one uses doesn't mean you should.

 If you select yes, we will create files with the default options
 we use with FFmpeg and mpv. You can remove any that you don't need or prefix
 them with #

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Choose ffmpeg and mpv optional libs: 1
-------------------------------------------------------------------------------
 File with default FFmpeg options has been created in
 Z:\media-autobuild_suite-master\build\ffmpeg_options.txt

 Edit it now or leave it unedited to compile according to defaults.
-------------------------------------------------------------------------------
Press any key to continue . . .
-------------------------------------------------------------------------------
 File with default mpv options has been created in
 Z:\media-autobuild_suite-master\build\mpv_options.txt

 Edit it now or leave it unedited to compile according to defaults.
-------------------------------------------------------------------------------
Press any key to continue . . .
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build static mp4box [mp4 muxer/toolbox] binary?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build mp4box: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build static rtmpdump binaries [rtmp tools]?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build rtmpdump: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

######### UNSUPPORTED, IF IT BREAKS, IT BREAKS ################################

 Build static mplayer/mencoder binary?
 1 = Yes
 2 = No

 Don't bother opening issues about this if it breaks, I don't fucking care
 about ancient unmaintained shit code. One more issue open about this that
 isn't the suite's fault and mplayer goes fucking out.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build mplayer: 2
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build mpv?
 1 = Yes
 2 = No

 Note: when built with shared-only FFmpeg, mpv is also shared.
 Note: the third option was removed since vapoursynth is now a delay-import
 dependency that is only required if you try to use the corresponding filter.
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build mpv: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build vlc?
 Takes a long time because of qt5 and wouldn't recommend it if you
 don't have ccache enabled.
 1 = Yes
 2 = No

 Note: the resulting vlc is extra buggy, do not expect it to work smoothly

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build vlc: 2
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build static bmx tools?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build bmx: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build static curl?
 1 = Yes (same backend as FFmpeg's)
 2 = No
 3 = SChannel backend
 4 = GnuTLS backend
 5 = OpenSSL backend
 6 = LibreSSL backend
 7 = mbedTLS backend

 A curl-ca-bundle.crt will be created to be used as trusted certificate store
 for all backends except SChannel.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build curl: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

######### UNSUPPORTED, IF IT BREAKS, IT BREAKS ################################

 Build FFMedia Broadcast binary?
 1 = Yes
 2 = No

 Note: this is a fork of FFmpeg 0.10. As such, it's very likely to fail
 to build, work, might burn your computer, kill your children, like mplayer.
 Only enable it if you absolutely need it. If it breaks, complain first to
 the author in #ffmbc in Freenode IRC.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build ffmbc: 2
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build cyanrip (CLI CD ripper)?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build cyanrip: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build ripgrep (faster grep in Rust)?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build ripgrep: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build jq (CLI JSON processor)?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build jq: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build jo (CLI JSON from shell)?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build jo: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build dssim (multiscale SSIM in Rust)?
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build dssim: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Build avs2 (Audio Video Coding Standard Gen2 encoder/decoder)?
 1 = Yes
 2 = No

 Binaries being built depends on "standalone=y" and are always static.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build avs2: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Use clang instead of gcc (C compiler)?
 Experimental and possibly broken due to gcc assumptions
 1 = Yes
 2 = No [Recommended]

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Build using clang: 2
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Number of CPU Cores/Threads for compiling:
 [it is non-recommended to use all cores/threads!]

 Recommended: 64

 If you have Windows Defender Real-time protection on, most of your processing
 power will go to it. It is recommended to whitelist this directory from
 scanning due to the amount of new files and copying/moving done by the suite.
 If you do not know how to do this, google it. If you don't care, ignore this.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Core/Thread Count: 64
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Delete versioned source folders after compile is done?
 1 = Yes [recommended]
 2 = No

 This will save a bit of space for libraries not compiled from git.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Delete source: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Strip compiled files binaries?
 1 = Yes [recommended]
 2 = No

 Makes binaries smaller at only a small time cost after compiling.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Strip files: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Pack compiled files?
 1 = Yes
 2 = No [recommended]

 Attention: Some security applications may detect packed binaries as malware.
 Increases delay on runtime during which files need to be unpacked.
 Makes binaries smaller at a big time cost after compiling and on runtime.

 If distributing the files, consider packing them with 7-zip instead.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Pack files: 2
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Write logs of compilation commands?
 1 = Yes [recommended]
 2 = No

Note: Setting this to yes will also hide output from these commands.
On successful compilation, these logs are deleted since they aren't needed.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Write logs: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Create script to update suite files automatically?
 1 = Yes
 2 = No

If you have made changes to the scripts, they will be reset but saved to a
.diff text file inside Z:\media-autobuild_suite-master\build

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Create update script: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Show timestamps of commands during compilation?
 1 = Yes
 2 = No

This will show the start times of commands during compilation.
Don't turn this on unless you really want to see the timestamps.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Show Timestamps: 1
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Use ccache when compiling?
 Experimental.
 Speeds up rebuilds and recompilations, but requires the files to be
 compiled at least once before any effect is seen
 1 = Yes
 2 = No

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Use ccache: 2
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

 Are you running this script through ssh or similar?
 (Can't open another window outside of this terminal)
 1 = Yes
 2 = No

This will disable the use of mintty and print the output to this console.
There is no guarantee that this will work properly.
You must make sure that you have ssh keep-alive enabled or something similar
to screen that will allow you to run this script in the background.

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
SSH: 2
-------------------------------------------------------------------------------

- Download and install msys2 basic system

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

- unpacking msys2 basic system

-------------------------------------------------------------------------------

7-Zip SFX 21.03 ZS v1.5.0 R2 (x64) : Copyright (c) 1999-2021 Igor Pavlov, 2016-2021 Tino Reichardt : 2021-10-05

Extracting archive: Z:\media-autobuild_suite-master\build\msys2-base.sfx.exe
--
Path = Z:\media-autobuild_suite-master\build\msys2-base.sfx.exe
Type = 7z

Everything is Ok
-------------------------------------------------------------------------------
- make a first run
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
first update
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
critical updates
-------------------------------------------------------------------------------
warning: bash-5.2.009-1 is up to date -- skipping
warning: pacman-6.0.1-31 is up to date -- skipping
warning: msys2-runtime-3.4.5-1 is up to date -- skipping
 there is nothing to do
-------------------------------------------------------------------------------
second update
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
creating local64-bit install folders
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

- write fstab mount file

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
install msys2 base system
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
install 64 bit compiler
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
update autobuild suite
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
 Creating suite update file...

 Run this file by dragging it to mintty before the next time you run
 the suite and before reporting an issue.

 It needs to be run separately and with the suite not running!
-------------------------------------------------------------------------------

Z:\media-autobuild_suite-master>
***

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10762642/logs.zip)

**Comment by 1480c1** [comment]
according to https://github.com/m-ab-s/media-autobuild_suite/issues/2382 it seems it ran fine for you after rerunning
