### ISSUE TITLE
FFmpeg x64 fails to build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2385]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10806086/logs.zip)

**Comment by Biswa96** [comment]
It seems that something is wrong in your system. The compiler is searching for headers in both D:/MABS-ffmpeg/msys64/mingw64/ and D:/MABS-ffmpeg/local64/ directories.

**Comment by Barough** [comment]
Just took a quick look at the compile log here.....

D:/MABS-ffmpeg/build/ffmpeg-git/libavcodec/libsvt_vp9.c:530:18: warning: unused variable 'ref' [-Wunused-variable]
  530 |     AVBufferRef *ref;
      |                  ^~~
D:/MABS-ffmpeg/build/ffmpeg-git/libavcodec/libsvt_vp9.c: At top level:
D:/MABS-ffmpeg/build/ffmpeg-git/libavcodec/libsvt_vp9.c:693:25: error: 'FF_CODEC_CAP_NOT_INIT_THREADSAFE' undeclared here (not in a function); did you mean 'FF_CODEC_CAP_INIT_THREADSAFE'?
  693 |     .caps_internal    = FF_CODEC_CAP_NOT_INIT_THREADSAFE |
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         FF_CODEC_CAP_INIT_THREADSAFE
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/libsvt_vp9.o] Error 1

**Comment by Barough** [comment]
Still not possible to build FFmpeg here. Goes for both 32 & 64 bit
https://github.com/m-ab-s/media-autobuild_suite/issues/2431
