### ISSUE TITLE
lensfun: errors related to locale_t type

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2390]
Reported to https://github.com/lensfun/lensfun/issues/1998

```
...
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp: In member function 'lfError lfDatabase::Load(const char*, const char*, size_t)':
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:826:27: error: 'locale_t' was not declared in this scope; did you mean '_locale_t'?
  826 |     auto loc = uselocale((locale_t) 0); // get current local
      |                           ^~~~~~~~
      |                           _locale_t
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:826:16: error: 'uselocale' was not declared in this scope; did you mean 'setlocale'?
  826 |     auto loc = uselocale((locale_t) 0); // get current local
      |                ^~~~~~~~~
      |                setlocale
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:827:27: error: 'LC_NUMERIC_MASK' was not declared in this scope; did you mean 'LC_NUMERIC'?
  827 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                           ^~~~~~~~~~~~~~~
      |                           LC_NUMERIC
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:827:59: error: expected ')' before numeric constant
  827 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                          ~                                ^~
      |                                                           )
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:827:17: error: 'newlocale' was not declared in this scope; did you mean 'setlocale'?
  827 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                 ^~~~~~~~~
      |                 setlocale
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:858:5: error: 'freelocale' was not declared in this scope; did you mean '_free_locale'?
  858 |     freelocale(nloc);
      |     ^~~~~~~~~~
      |     _free_locale
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp: In member function 'lfError lfDatabase::Save(char*&, size_t&) const':
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:901:27: error: 'locale_t' was not declared in this scope; did you mean '_locale_t'?
  901 |     auto loc = uselocale((locale_t) 0); // get current local
      |                           ^~~~~~~~
      |                           _locale_t
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:901:16: error: 'uselocale' was not declared in this scope; did you mean 'setlocale'?
  901 |     auto loc = uselocale((locale_t) 0); // get current local
      |                ^~~~~~~~~
      |                setlocale
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:902:27: error: 'LC_NUMERIC_MASK' was not declared in this scope; did you mean 'LC_NUMERIC'?
  902 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                           ^~~~~~~~~~~~~~~
      |                           LC_NUMERIC
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:902:59: error: expected ')' before numeric constant
  902 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                          ~                                ^~
      |                                                           )
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:902:17: error: 'newlocale' was not declared in this scope; did you mean 'setlocale'?
  902 |     auto nloc = newlocale(LC_NUMERIC_MASK, "C", (locale_t) 0);
      |                 ^~~~~~~~~
      |                 setlocale
G:/MABS/build/lensfun-git/libs/lensfun/database.cpp:1144:5: error: 'freelocale' was not declared in this scope; did you mean '_free_locale'?
 1144 |     freelocale(nloc);
      |     ^~~~~~~~~~
      |     _free_locale
...
```

[logs.zip](https://github.com/lensfun/lensfun/files/10871363/logs.zip)

**Comment by LigH-de** [comment]
Is anyone able to try ^ this pull request?

**Comment by newcapricasean** [comment]
I am having this same problem... I've been trying to resolve it for hours... literally... Help would greatly be appreciated... I'm now running on Fedora 37... Oh, I see a response above... I'm going to look into that, now...

**Comment by newcapricasean** [comment]
How would one amend the m-ab-s/media-autobuild_suite script to pass this parameter over to the lensfun build?

build_lensfun() {
build_glib
do_git_checkout https://github.com/lensfun/lensfun.git lensfun_git
cd lensfun_git
export CMAKE_STATIC_LINKER_FLAGS='-lws2_32 -pthread'
do_cmake "-DBUILD_STATIC=on -DCMAKE_INSTALL_DATAROOTDIR=$mingw_w64_x86_64_prefix"
do_make
do_make_install
sed -i.bak 's/-llensfun/-llensfun -lstdc++/' "$PKG_CONFIG_PATH/lensfun.pc"
unset CMAKE_STATIC_LINKER_FLAGS
cd ..
}

Could I just add "-CMAKE_SYSTEM_NAME=Windows" to CMAKE_STATIC_LINKER_FLAGS='-lws2_32 -pthread' ???

**Comment by LigH-de** [comment]
There is a script **build/media-suite_deps.sh** with all the URLs to the repositories.

I'm just testing if it works with `SOURCE_REPO_LENSFUN=https://github.com/Biswa96/lensfun.git` ... please wait ...

**Comment by LigH-de** [comment]
Ah, will try that then...

**Comment by newcapricasean** [comment]
Where in the media-suite_compile.sh file do you add/change that?

**Comment by newcapricasean** [comment]
I'm relatively new to this github, compiling, and linux... If your changes to lensfun script become "commit" ... how long before the actual source code is updated with this change?

**Comment by LigH-de** [comment]
As soon as you can read from Biswa96 that he published it, you can revert your local changes to the suite scripts.

**Comment by newcapricasean** [comment]
And, do you have to actually delete the entire media-suite_compile folder, redownload it, and run it from scratch to test it? Alternatively, can you just erase the sandbox folder, or is it enough to just erase the lensfun folder in the sandbox. Thus far, with these proposed changes, I've just been deleting the lensfun folder, and re-running the script.

**Comment by newcapricasean** [comment]
Thank you all for helping... I have seriously been trying to resolve this for most of the night, on my own... lol... Was getting close to just giving up...

**Comment by newcapricasean** [comment]
Does his proposed fix correct the problem, for you? Did you just change the media-suite_compile.sh with his proposal above? If so, where in the script do you add that, and do you replace something else with it?

**Comment by LigH-de** [comment]
Yes, I added the patch as described [here](https://github.com/m-ab-s/media-autobuild_suite/issues/2390#issuecomment-1451965836).
Yes, after this change the compilation passed.

No, you better do not change anything anymore, because @Biswa96 will probably commit it soon, and then you do not need to add this patch anymore.

**Comment by newcapricasean** [comment]
Modifying the database.cpp and lens.cpp files, with the suggested changes, resolved the issue for me... Thank you!!!

**Comment by LigH-de** [comment]
@1480c1 - would you add the [patch](https://github.com/m-ab-s/media-autobuild_suite/issues/2390#issuecomment-1451965836) until the [pull request](https://github.com/lensfun/lensfun/pull/1999/commits/ef7879fc911146e7c11b896d956a5c3e84f15b69) gets committed in the lensfun project?

**Comment by 1480c1** [comment]
> @1480c1 - would you add the [patch](https://github.com/m-ab-s/media-autobuild_suite/issues/2390#issuecomment-1451965836) until the [pull request](https://github.com/lensfun/lensfun/pull/1999/commits/ef7879fc911146e7c11b896d956a5c3e84f15b69) gets committed in the lensfun project?

https://github.com/m-ab-s/media-autobuild_suite/commit/7ccbc15535d46b088bfdce6282807c0edfb11b42

**Comment by Biswa96** [comment]
This has been fixed in upstream https://github.com/lensfun/lensfun/commit/6cb00f4445f0a7edaae306bbf4f340de37b58fb8
