### ISSUE TITLE
x264 (INI Setting : 4) - Fails to build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2397]
┌ x264 git  ........................................... [Recently updated]
  Running git clone for ffmpeg...
  Running git update for ffmpeg...
┌ ffmpeg git  ......................................... [Recently updated]
Failed to apply patch 'https://patchwork.ffmpeg.org/series/8130/mbox/'
Patch without filename, ignoring. Specify an explicit filename.
├ Running configure...
├ Running install...
Likely error (tail of the failed operation logfile):
    inlined from 'get_cabac' at D:/mabs/build/ffmpeg-git/libavcodec/cabac_functions.h:145:12,
    inlined from 'decode_cabac_mb_intra4x4_pred_mode' at D:/mabs/build/ffmpeg-git/libavcodec/h264_cabac.c:1377:9,
    inlined from 'ff_h264_decode_mb_cabac' at D:/mabs/build/ffmpeg-git/libavcodec/h264_cabac.c:2081:32:
D:/mabs/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
  199 |     __asm__ volatile(
      |     ^~~~~~~
D:/mabs/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
D:/mabs/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
D:/mabs/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/h264_cabac.o] Error 1
install failed. Check D:/mabs/build/ffmpeg-git/build-light-32bit/ab

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10924772/logs.zip)

**Comment by Selur** [comment]
Same here, when building:
```
21:20:54 AviSynthPlus git  ................................. [Up-to-date]
21:20:59   Running git update for ffmpeg...
21:21:00 ┌ ffmpeg git  .................................. [Updates found]
21:21:00 ├ Changing options to comply to gplv3...
Failed to apply patch 'https://patchwork.ffmpeg.org/series/8130/mbox/'
Patch without filename, ignoring. Specify an explicit filename.
21:21:23 ├ Compiling static FFmpeg...
21:21:23 ├ Running configure...
21:24:46 ├ Running make...
Likely error (tail of the failed operation logfile):
    inlined from 'get_cabac' at I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/cabac_functions.h:145:12,
    inlined from 'decode_cabac_mb_intra4x4_pred_mode' at I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/h264_cabac.c:1377:9,
    inlined from 'ff_h264_decode_mb_cabac' at I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/h264_cabac.c:2081:32:
I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
  199 |     __asm__ volatile(
      |     ^~~~~~~
I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
I:/media-autobuild_suite/build/ffmpeg-git/libavcodec/x86/cabac.h:199:5: error: 'asm' operand has impossible constraints
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/h264_cabac.o] Error 1
make failed. Check I:/media-autobuild_suite/build/ffmpeg-git/build-static-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10925001/logs.zip)

**Comment by Barough** [comment]
It builds again atm. Will wait a little while before i close the issue.
