### ISSUE TITLE
librist - ../meson.build:6:0: ERROR: Unknown options: "disable_json"

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2402]
┌ librist git  ........................................... [Updates found]
0001-Workaround-fixes-for-cJSON-symbol-collision.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running uninstall...
├ Running meson...
Likely error (tail of the failed operation logfile):
The Meson build system
Version: 1.0.1
Source dir: D:/MABS-ffmpeg/build/librist-git
Build dir: D:/MABS-ffmpeg/build/librist-git/build-32bit
Build type: native build

../meson.build:6:0: ERROR: Unknown options: "disable_json"

A full log can be found at D:/MABS-ffmpeg/build/librist-git/build-32bit/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
meson failed. Check D:/MABS-ffmpeg/build/librist-git/build-32bit/ab-suite.meson.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11010227/logs.zip)

**Comment by Fishman0919** [comment]
Same

**Comment by PanRe** [comment]
Same

**Comment by L4cache** [comment]
I think the reason is patch apply failure, this option disable_json seems like is added by the patch here.
librist build can pass after delete related option from compile command, but I haven't test if it will work in ffmpeg yet.

**Comment by Biswa96** [comment]
The solution is to rebase this patch file https://github.com/m-ab-s/mabs-patches/blob/master/librist/0001-Workaround-fixes-for-cJSON-symbol-collision.patch

**Comment by L4cache** [comment]
But how to use rist in ffmpeg in first place? I can't find useful info so I tired to just output to rist://127.0.0.1 but not working

**Comment by PanRe** [comment]
@1480c1 Would you be so kind to rebase the patch file?

**Comment by kliffgomel** [comment]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11025887/logs.zip)

**Comment by r4b8iiiiiit** [comment]
Also getting the same issue

**Comment by vndevil** [comment]
You can try this:

1. In folder "yourlocal\media-autobuild_suite\build\librist-git" rename file "0001-Workaround-fixes-for-cJSON-symbol-collision.patch" to "0001-Workaround-fixes-for-cJSON-symbol-collision.patch.bak"

2. run media-autobuild_suite.bat again

**Comment by r4b8iiiiiit** [comment]
> You can try this:
> 
> 1. In folder "yourlocal\media-autobuild_suite\build\librist-git" rename file "0001-Workaround-fixes-for-cJSON-symbol-collision.patch" to "0001-Workaround-fixes-for-cJSON-symbol-collision.patch.bak"
> 2. run media-autobuild_suite.bat again

Same error still after doing that

**Comment by dmki** [comment]
> 1. In folder "yourlocal\media-autobuild_suite\build\librist-git" rename file "0001-Workaround-fixes-for-cJSON-symbol-collision.patch" to "0001-Workaround-fixes-for-cJSON-symbol-collision.patch.bak"
> 2. run media-autobuild_suite.bat again

The media build script overwrites that file, no matter what. So no, it doesn't work.

**Comment by Nekofoxmiu** [comment]
compare the lines to make the fixed patch. Not sure it will cause promblem or not, but it can pass the meson build.
https://github.com/Nekofoxmiu/patch_ff/releases/download/release/0001-Workaround-fixes-for-cJSON-symbol-collision.patch

**Comment by L4cache** [comment]
I'm wondering what the patch was doing and why, because I disabled it and got no problem (suite compiles, at least)

**Comment by Cooly0** [comment]
Changed it to Nekofoxmiu's and it Worked!

**Comment by Biswa96** [comment]
The patch was rebased in this commit https://github.com/m-ab-s/mabs-patches/commit/e1c8996fa79697298bb1a79f9ca77aeffdfa1c02. Retrying to build may fix the issue.

**Comment by kliffgomel** [comment]
it's fixed!
