### ISSUE TITLE
mingw64 rav1e build fail

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2407]
15:09:47 ┌ rav1e git  ................................ [Recently updated]
15:09:47 ├ Running rust.update...
15:09:49 ├ Running rust.build...
Likely error (tail of the failed operation logfile):
warning: spurious network error (1 tries remaining): [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.)
warning: spurious network error (1 tries remaining): [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.)
warning: spurious network error (1 tries remaining): [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.)
warning: spurious network error (1 tries remaining): [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.)
warning: spurious network error (1 tries remaining): [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.)
warning: spurious network error (1 tries remaining): [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.)
error: failed to download from `https://crates.io/api/v1/crates/anstream/0.2.6/download`

Caused by:
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.)
rust.build failed. Check D:/ffmpeg-autobuild/build/rav1e-git/ab-suite.rust.build.log
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11129452/logs.zip)

**Comment by Biswa96** [comment]
This could be your network issue and not caused by this project. Please see this thread https://github.com/rust-lang/cargo/issues/6513. It has some workaround. You can also find some workaround by searching "warning: spurious network error".
