### ISSUE TITLE
mingw64 clang gpac-git

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2410]
16:47:13 ┌ gpac git  ................................. [Recently updated]
16:47:13 ├ Running configure...
16:47:47 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/ffmpeg-autobuild-clang/build/gpac-git/src/utils/os_thread.c:225:10: warning: cast to 'void *' from smaller integer type 'DWORD' (aka 'unsigned long') [-Wint-to-void-pointer-cast]
                return (void *)ret;
                       ^~~~~~~~~~~
C:/ffmpeg-autobuild-clang/build/gpac-git/src/utils/os_thread.c:225:10: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'DWORD' (aka 'unsigned long') [-Wint-conversion]
                return (void *)ret;
                       ^~~~~~~~~~~
1 warning and 1 error generated.
make[1]: *** [../config.mak:174: utils/os_thread.o] Error 1
make[1]: Leaving directory '/build/gpac-git/build-64bit/src'
make: *** [Makefile:13: all] Error 2
make failed. Check C:/ffmpeg-autobuild-clang/build/gpac-git/build-64bit/ab-suite.make.log
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11179374/logs.zip)

**Comment by Biswa96** [comment]
This pull request will fix the issue https://github.com/gpac/gpac/pull/2437.

**Comment by kliffgomel** [comment]
Fixed!
