### ISSUE TITLE
Multiple errors running make when update curl

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2411]
``` bash
20:06:38   Running git update for curl...
20:07:06 ┌ curl git  .................................... [Updates found]
20:07:08 ├ Running uninstall...
20:07:08 ├ Running autoreconf...
20:07:50 ├ Running configure...
20:11:36 ├ Running make...
Likely error (tail of the failed operation logfile):
   41 | const char *Curl_http2_strerror(uint32_t err);
      |                                 ^~~~~~~~
../../lib/http2.h:1:1: note: 'uint32_t' is defined in header '<stdint.h>'; did you forget to '#include <stdint.h>'?
  +++ |+#include <stdint.h>
    1 | #ifndef HEADER_CURL_HTTP2_H
make[2]: *** [Makefile:2234: libcurl_la-cf-https-connect.lo] Error 1
make[2]: Leaving directory '/build/curl-git/build-64bit/lib'
make[1]: *** [Makefile:1507: all] Error 2
make[1]: Leaving directory '/build/curl-git/build-64bit/lib'
make: *** [Makefile:1266: all-recursive] Error 1
make failed. Check C:/MinGW-w64/build/curl-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
20:11:49   Creating diagnostics file...

Attach C:\MinGW-w64\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11183233/logs.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/11183235/ab-suite.make.log)

**Comment by Biswa96** [comment]
It seems that the Curl_http2_strerror function declaration was not removed in older commit. I have asked upstream about that.

**Comment by Selur** [comment]
Same happens when building 32bit, [logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11183411/logs.zip).
@Biswa96 : Thanks for asking upstream about it.

**Comment by Biswa96** [comment]
For quick workaround, you can try to remove the line 41 in lib/http2.h file in curl source directory, not sure what the full path is.

**Comment by bytos** [comment]
C:\MAS\build\curl-git\lib\http2.h

**Comment by Biswa96** [comment]
This pull request will fix the issue https://github.com/curl/curl/pull/10912

**Comment by ggarra13** [comment]
I fixed the file in question (http2.h) and was able to compile manually in the cure-git/build-32bits directory.  Then I run:

$ make install

However, when I run the media-autobuild_suite.bat file again, it downloaded the curl-git again, leading to a failed compilation again.

What file should I run "touch" on to make m-ab-s not update curl-git again?

**Comment by Biswa96** [comment]
The pull request was merged in this upstream commit https://github.com/curl/curl/commit/5023d7c9449e79b8eb953b0da4853ba711ec1825. Now just try to rebuild this project. The fix should be automatically pulled in.
