### ISSUE TITLE
Updating MAS Without Losing Compiler Files

### ISSUE THREAD

**Issue by bytos** [m-ab-s/media-autobuild_suite#2412]
Which folders/files should be saved to avoid having to start from scratch when updating MAS?

It takes a long time to download and setup compiler files (etc.) just to get the latest MAS.

Is there a convenient way to have the latest MAS?

I'm not talking about the **build** folder.

**Comment by L4cache** [comment]
why not just replace(overwrite) script files directly into your existing suite

**Comment by bytos** [comment]
Thanks for confirming. Looking at the files didn't see anything obvious that could cause a conflict.
