### ISSUE TITLE
mingw64 ffmpeg: SVT-VP9 patch fails

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2418]
Already integrated or rebase required?
```
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
```

**Comment by dedbbs1** [comment]
I am also having this problem as of 2023-05-06 and would appreciate a fix. Wish I knew how to do so myself. Thanks.

**Comment by LigH-de** [comment]
Still the same.

Already integrated or rebase required?

**Comment by hassan379** [comment]
me too

**Comment by LigH-de** [comment]
@1480c1 - running your test branch from librist, ffmpeg does not complain about the svtvp9 patch but fails anyway.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11986049/logs.zip)

**Comment by hassan379** [comment]
@LigH-de 
Hi 
do you have any version of ffmpeg with svtvp9 and its shared libs (.libs and .dlls files) ?

**Comment by LigH-de** [comment]
No, I prefer static builds and don't backup libraries (*.a).

**Comment by hassan379** [comment]
@LigH-de 
thank u for ur help
@1480c1 
Sorry for repeating my question but it is very important for me.  Do u have any old version of ffmpeg with svtvp9 and its shared libs (.lib and .dll files, include folder) ?

**Comment by hassan379** [comment]
in order to build libsvt_vp9 and to avoid the error at the end of  the compiling you have to remove --enable-libvpx from ffmpeg_options.txt

**Comment by LigH-de** [comment]
So I am forced to choose between either libvpx or libsvtvp9.

**Comment by hassan379** [comment]
for now yes
