### ISSUE TITLE
luajit: Patches fail

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2419]
Implemented or rebase required?
```
0001-Add-win32-UTF-8-filesystem-functions.patch
        Patch could not be applied with `git am`. Continuing without patching.
0002-win32-UTF-8-Remove-va-arg-and-.-and-unused-functions.patch
        Patch could not be applied with `git am`. Continuing without patching.
```

**Comment by Biswa96** [comment]
Would you like to rebuild the program? The patches have been rebased in this https://github.com/m-ab-s/mabs-patches/commit/b7def7d4d185220baa3130c9c91b3485e11fc4b3 commit.

**Comment by LigH-de** [comment]
Removed **build/luajit-git** to force rebuild and re-download of patches: works. 👍
