### ISSUE TITLE
mingw64 ffms2 make error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2424]
09:20:17 ┌ ffms2 git  ................................... [Updates found]
0001-ffmsindex-fix-linking-issues.patch
        Patch could not be applied with `git am`. Continuing without patching.
09:20:19 ├ Running autoreconf...
09:21:16 ├ Running configure...
09:22:25 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/ffmpeg-autobuild-clang/msys64/mingw64/lib\libstdc++.a(eh_aux_runtime.o): duplicate section `.rdata$_ZTSSt9bad_alloc[_ZTSSt9bad_alloc]' has different size
C:/ffmpeg-autobuild-clang/msys64/mingw64/lib\libstdc++.a(eh_aux_runtime.o): duplicate section `.rdata$_ZTISt9bad_alloc[_ZTISt9bad_alloc]' has different size
C:/ffmpeg-autobuild-clang/msys64/mingw64/lib\libstdc++.a(stdexcept.o): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:/ffmpeg-autobuild-clang/msys64/mingw64/lib\libstdc++.a(stdexcept.o): duplicate section `.rdata$_ZTISt11logic_error[_ZTISt11logic_error]' has different size
C:/ffmpeg-autobuild-clang/msys64/mingw64/lib\libstdc++.a(cxx11-ios_failure.o): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:/ffmpeg-autobuild-clang/msys64/mingw64/lib\libstdc++.a(ios_failure.o): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:/ffmpeg-autobuild-clang/msys64/mingw64/bin/ld: C:/ffmpeg-autobuild-clang/msys64/mingw64/lib/libmingw32.a(lib64_libmingw32_a-crtexewin.o): in function `main':
C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexewin.c:70: undefined reference to `WinMain'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:665: src/index/ffmsindex.exe] Error 1
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11340766/logs.zip)

**Comment by Biswa96** [comment]
> Patch could not be applied with `git am`. Continuing without patching.

Please try to rebuild the project. It should pull the latest patch file. The ffms2 patch file was rebased in this commit https://github.com/m-ab-s/mabs-patches/commit/9b38a14f1d2b65677db796653ef1ed65d78820fe

**Comment by kliffgomel** [comment]
fixed
