### ISSUE TITLE
cjpeg_hdr.exe  ............... [Not found]

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#2427]
Hello.  
Attempting a full-ish x64 build in a WIn11 sandbox.
This error pops up:
``` 23:58:47   Running git clone for libjxl...
23:58:58   Running git update for libjxl...
23:58:59 ┌ libjxl git  ............................... [Recently updated]
23:59:02 ├ Installing lcms2... done
23:59:11 ├ Installing asciidoc... done
00:00:16 ├ Running cmake...
00:00:24 ├ Running build...
00:02:43 ├ Running install...
00:02:44 ├ /local64/bin-global/cjpeg_hdr.exe  ............... [Not found]
00:02:44 └ libjxl-git  ......................................... [Failed]
```
`cjpeg_hdr` appears as text in `media-suite_compile.sh` line 563.

Cheers

**Comment by Biswa96** [comment]
> `cjpeg_hdr` appears as text in `media-suite_compile.sh` line 563.

Would you like to check if replacing `cjpeg_hdr` with `cjpegli` fixes the issue?

**Comment by hydra3333** [comment]
Sure, will do that tonight and post the result here.

**Comment by Cerlancism** [comment]
> > `cjpeg_hdr` appears as text in `media-suite_compile.sh` line 563.
> 
> Would you like to check if replacing `cjpeg_hdr` with `cjpegli` fixes the issue?

Seems to work after replace.

Cause:
https://github.com/libjxl/libjxl/pull/2420

**Comment by hydra3333** [comment]
yes, confrmed.
