### ISSUE TITLE
mpv: undefined reference to `pl_log_create_273' in libavfilter.a(vf_libplacebo.o)

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2430]
```
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: G:/MABS/local32/lib\libavfilter.a(vf_libplacebo.o):vf_libplacebo.:(.text+0x2754): undefined reference to `pl_log_create_273'
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11360034/logs.zip)

**Comment by LigH-de** [comment]
**local##\lib\libplacebo.a** contains a reference to `pl_log_create_274` instead.

**Comment by Biswa96** [comment]
Probably there is some version mismatch between ffmpeg and libplacebo libraries. Try to build those from fresh start.

**Comment by LigH-de** [comment]
I already tried to remove **build/libplacebo-git** and **build/mpv-git** to force a rebuild, will try again by removing **build/ffmpeg-git** as well.

**Comment by LigH-de** [comment]
Removing **build/ffmpeg-git** helped, the suite passed.

I wonder if it would fix as well when ffmpeg rebuilds anyway due to updates.
