### ISSUE TITLE
rav1e: const_fn_assert v0.1.2+deprecated 

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2432]
**ab-suite.install-rav1e-c.log**
```
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
/opt/cargo/bin/cargo.exe capi install --release --jobs 4 --prefix=/local32 --destdir=/build/rav1e-git/install-32bit
 Downloading crates ...
  Downloaded const_fn_assert v0.1.2+deprecated
Error: CliError { error: Some(failed to verify the checksum of `const_fn_assert v0.1.2+deprecated`), exit_code: 101 }
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11415215/logs.zip)

**Comment by LigH-de** [comment]
Adding a `--locked` CLI parameter to the cargo call should lock sources to the release development state, I was told in IRC. But I am not sure how much that may stay back from the HEAD.

**Comment by LigH-de** [comment]
It did not work right away, so I removed **cargo-c-git** and **rav1e-git** from **build** to force a fresh compilation. That passed.

**Comment by lu-zero** [comment]
Once https://github.com/xiph/rav1e/pull/3198 lands you should not have problems. Thank you for reporting the issue on IRC :)

**Comment by lu-zero** [comment]
Now I also put a release 0.6.5 out so you should be fine even if you track the releases.

**Comment by LigH-de** [comment]
Fixed upstream, compiles with the original set of parameters.
