### ISSUE TITLE
Autobuild fails after an hour (logs)

### ISSUE THREAD

**Issue by mikpinky** [m-ab-s/media-autobuild_suite#2439]
Hi, I'm a total noob here and I appreciate if you can help me.
I was trying to build non-free ffmpeg enabling most of the codecs (I was interested in FDK AAC audio), except for those that were Not Reccomended.

I got this error after an hour of the script working, anyway I'll attach logs.zip [here](https://file.io/Kb5Cy3IOBAvG)
```
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lnghttp2  -lidn2 -liconv  -lpsl -lidn2 -liconv  -lbcrypt -ladvapi32 -lcrypt32 -lssl -lcrypto -lssl -lws2_32 -lgdi32 -lcrypt32 -lcrypto -lws2_32 -lgdi32 -lcrypt32  -lgdi32 -lwldap32 -lzstd  -lbrotlidec -lbrotlidec -lbrotlicommon  -lz -lws2_32
configure failed. Check C:/ffmpeg/autobuild/build/curl-git/build-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach C:\ffmpeg\autobuild\build\logs.zip to the GitHub issue.

```
Thanks.

**Comment by voltagex** [comment]
You can attach a zip file directly to this GitHub issue instead of unreliable filehosters.

**Comment by okazunori2013** [comment]
Same as #2411

**Comment by mikpinky** [comment]
@voltagex @okazunori2013 
Sorry to both of you! Here's the log file.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11522924/logs.zip)

Anyway I managed to find a non-free build of FFMPEG that included the FDK AAC I was interested in, but I'm still interested on the reason why my compiling went wrong, so I will retry to build my personal (and reliable) full FFMPEG.
