### ISSUE TITLE
[mingw64][ffmpeg] ERROR: x265 not found using pkg-config

### ISSUE THREAD

**Issue by Boulder08** [m-ab-s/media-autobuild_suite#2449]
Once again running into this problem. I've tried deleting the whole x265 and ffmpeg git folders without any luck. I've had this error for months now I think.

``` bash
Likely error (tail of the failed operation logfile):
CXXFLAGS: -march=znver3 -mtune=znver3 -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-schannel --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --extra-libs=-liconv --enable-gpl --enable-version3 --enable-nonfree --extra-version=gc5508f60c2+1
ERROR: x265 not found using pkg-config
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11601780/logs.zip)

**Comment by Biswa96** [comment]
It seems that the x265.h is missing stdbool.h include. I shall reproduce the issue and let you know.

**Comment by Boulder08** [comment]
Funny if it's that as x265 itself builds just fine.

**Comment by Biswa96** [comment]
> items brought on by a patch installed during x265's build

Could you provide the link to that patch file? media-autobuild_suite only adds a cmake patch with x265.

**Comment by Boulder08** [comment]
It's a custom patch, attached here if you are interested.
[x265patch.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11604255/x265patch.zip)

**Comment by Biswa96** [comment]
Oh, I thought the issue in the media-autobuild_suite project. Thanks.
