### ISSUE TITLE
Request: Provide easy way to replace ffmpeg repository

### ISSUE THREAD

**Issue by Meetem** [m-ab-s/media-autobuild_suite#2454]
Hello.
I'm using custom ffmpeg with my own changes. While it's possible to disable ffmpeg update and change the files inside the folder, it would be much better to allow pulling changes from the custom repository. Just provide a link to git repo. 
Right now as I can see there's common url on m-ab-s gitlab, so it's not one line change unfortunately.

/cc @1480c1

**Comment by Meetem** [comment]
Checked commits, it's already there. Good stuff! Thank you.

**Comment by Meetem** [comment]
Oh, while it's possible to supply custom repo, there's an issue if repo name is not ffmpeg.git. For instance I'm building my fork https://github.com/Meetem/FFmpeg-better-hap and it gets cloned into FFmpeg-better-hap-git folder, instead of ffmpeg-git, which makes it unable to compile correctly.

**Comment by 1480c1** [comment]
I guess technically, one way I can address this is by making it so `do_vcs()` can take the folder name in the first argument, so something like `"https://github.com/Meetem/FFmpeg-better-hap.git#branch=better-hap ffmpeg"`. This way, it would split the input and use the part after the space as the folder name if present and a second argument is not supplied. I doubt any sane person is using a space literal in their git url as opposed to a %20 if they are using one.

**Comment by 1480c1** [comment]
98b4845ca7
