### ISSUE TITLE
[mingw64] [glslang] Python gets bad path to gen_extension_headers.py

### ISSUE THREAD

**Issue by DoctorHayes** [m-ab-s/media-autobuild_suite#2462]
I am just building the 64-bit version in Windows 11. I also commented out `--enable-libglslang` in `ffmpeg_options.txt`, but it is still attempting to compile the library.

Here is the relevant error:

``` bash
cmd.exe /C "cd /D C:\media-autobuild\build\glslang-git\build-64bit\StandAlone && C:\media-autobuild\msys64\usr\bin\python3.11.exe C:/media-autobuild/build/glslang-git/StandAlone/../gen_extension_headers.py -i C:/media-autobuild/build/glslang-git/StandAlone/../glslang/ExtensionHeaders -o C:/media-autobuild/build/glslang-git/build-64bit/include/glslang/glsl_intrinsic_header.h"
/trunk/msys64/usr/bin/python3.11.exe: can't open file '/trunk/build/glslang-git/build-64bit/StandAlone/C:/media-autobuild/build/glslang-git/StandAlone/../gen_extension_headers.py': [Errno 2] No such file or directory
ninja: build stopped: subcommand failed.
build failed. Check C:/media-autobuild/build/glslang-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11792918/logs.zip)

I can edit the Python command manually to get it to work, (removing `/trunk/build/glslang-git/build-64bit/StandAlone/`). But my changes get blown out when I rerun the script. Let me know if there is a quick workaround or fix.

**Comment by Fishman0919** [comment]
Same

**Comment by jon-waltman** [comment]
I have the same issue. Looking at the compile script:
https://github.com/m-ab-s/media-autobuild_suite/blob/de449072e2916afc37d0c4c0f405d43970b30ef2/build/media-suite_compile.sh#L1980-L1981
...it looks like you need to do ALL of the below to skip the glslang build as a workaround:

* `mpv=2` (disabled) in `media-autobuild_suite.ini` **OR** `--disable-libplacebo` in `mpv_options.txt`
* Comment out `--enable-libglslang` in `ffmpeg_options.txt`
* Comment out `--enable-libplacebo` in `ffmpeg_options.txt`

Note I haven't tested this yet as I'm still trying to figure out what is lost by dropping the dependency.

**Comment by DoctorHayes** [comment]
Thanks, [jon-waltman](https://github.com/jon-waltman), those configuration changes allowed it to build successfully without libglslang.

**Comment by Biswa96** [comment]
Could you try uninstalling the msys2 python with `pacman -R python` command?

**Comment by Fishman0919** [comment]
same with "pacman -R python"

**Comment by Georgecolla** [comment]
is someone have any solution i have this issue and i think that is from this path /trunk/build/glslang-git/build-64bit/StandAlone/C:/media-autobuild_suite-master/build/glslang-git/StandAlone/../gen_extension_headers.py it wanna be ./trunk/build/glslang-git/StandAlone/../gen_extension_headers.py or ./trunk/build/glslang-git/gen_extension_headers.py plz if anyone have any solution type it i tried to edit glslang-git but when i run build again its updated from github and return again and didnt work??

**Comment by hydra3333** [comment]
> **Edit:** It looks like glslang and placebo are just extra filter options in ffmpeg.

isn't placebo necessary to use vulkan filters ?

**Comment by Biswa96** [comment]
This should be fixes after this https://github.com/m-ab-s/media-autobuild_suite/commit/8ae921e6ca517c29633e42994ad5bfd78db2bb8f commit. Please run `git pull` in the cloned repository.

**Comment by Georgecolla** [comment]
> This should be fixes after this [8ae921e](https://github.com/m-ab-s/media-autobuild_suite/commit/8ae921e6ca517c29633e42994ad5bfd78db2bb8f) commit. Please run `git pull` in the cloned repository.

plz i didnt understand what should i do,, i opened very very compilicated file and every file got another file till i fet lost what should i do with this problem this path is wrong /trunk/build/glslang-git/build-64bit/StandAlone/C:/media-autobuild_suite-master/build/glslang-git/StandAlone/../gen_extension_headers.py and the correct path of is /trunk/build/glslang-git/StandAlone/../gen_extension_headers.py and i cant change this path in glslang-git cause when i made it it update when i run it again what should i do and what can i do?? plz can u help me??

**Comment by Biswa96** [comment]
Just go to the media-autobuild_suite directory and run `git pull` command. Then try to rebuild things as usual.

**Comment by Georgecolla** [comment]
> Just go to the media-autobuild_suite directory and run `git pull` command. Then try to rebuild things as usual.

it gives me in cmd (im using win 10) fatal: not a git repository (or any of the parent directories): .git

**Comment by Georgecolla** [comment]
> Just go to the media-autobuild_suite directory and run `git pull` command. Then try to rebuild things as usual.

it gives me in cmd (im using win 10) Already up to date.

**Comment by Georgecolla** [comment]
> Just go to the media-autobuild_suite directory and run `git pull` command. Then try to rebuild things as usual.

it gives me in cmd (im using win 10) Already up to date.

**Comment by Georgecolla** [comment]
> Just go to the media-autobuild_suite directory and run `git pull` command. Then try to rebuild things as usual.

after i updated it it gives me vmaf git  ................................................... [Up-to-date]
Likely error (tail of the failed operation logfile):
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_fetch
++ git rev-parse --git-dir
+ [[ -f .git/shallow ]]
+ unshallow=
+ git fetch --all -Ppft
From https://aomedia.googlesource.com/aom
   d2e0b70c6..57dd20ae5  main       -> origin/main
+ git remote set-head -a origin
fatal: unable to access 'https://aomedia.googlesource.com/aom/': Failed to connect to aomedia.googlesource.com port 443 after 21053 ms: Couldn't connect to server
git.fetch failed. Check C:/media-autobuild_suite-master/build/aom-git/ab-suite.git.fetch.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
plz help me

**Comment by Georgecolla** [comment]
> Just go to the media-autobuild_suite directory and run `git pull` command. Then try to rebuild things as usual.

after i updated it it gives me vmaf git  ................................................... [Up-to-date]
Likely error (tail of the failed operation logfile):
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_fetch
++ git rev-parse --git-dir
+ [[ -f .git/shallow ]]
+ unshallow=
+ git fetch --all -Ppft
From https://aomedia.googlesource.com/aom
   d2e0b70c6..57dd20ae5  main       -> origin/main
+ git remote set-head -a origin
fatal: unable to access 'https://aomedia.googlesource.com/aom/': Failed to connect to aomedia.googlesource.com port 443 after 21053 ms: Couldn't connect to server
git.fetch failed. Check C:/media-autobuild_suite-master/build/aom-git/ab-suite.git.fetch.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
plz help me

**Comment by Biswa96** [comment]
> Failed to connect to aomedia.googlesource.com port 443 after 21053 ms: Couldn't connect to server

That's network issue in your system and not related to this project.

**Comment by hydra3333** [comment]
try locating and deleting the deleting the folder glslang git folder then re-running ... after fixing your network issue.
