### ISSUE TITLE
highway fails to build

### ISSUE THREAD

**Issue by Fishman0919** [m-ab-s/media-autobuild_suite#2463]
18:58:30 ┌ highway git  .............................. [Recently updated]
18:58:31 ├ Running cmake...
18:58:41 ├ Running build...
Likely error (tail of the failed operation logfile):
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                        F64_ERROR);                                        \
      |                        ~~~~~~~~~~
C:/MAS/build/highway-git/hwy/contrib/math/math_test.cc:229:1: note: in expansion of macro 'DEFINE_MATH_TEST'
  229 | DEFINE_MATH_TEST(SinCosCos,
      | ^~~~~~~~~~~~~~~~
C:/MAS/build/highway-git/hwy/contrib/math/math_test.cc:153:14: note: candidate is: 'template<class D, class V> V hwy::N_AVX3_ZEN4::SinCosCos(D, V)'
  153 | HWY_INLINE V SinCosCos(const D d, V x)
      |              ^~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check C:/MAS/build/highway-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
19:06:46   Creating diagnostics file...

Attach C:\MAS\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11808642/logs.zip)

**Comment by Cooly0** [comment]
Same issue here. I've been retrying all-day, Once I got it, but stuck on a different package with different error of not being able to connect.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11808800/logs.zip)

**Comment by ycwan** [comment]
Same issue,

19:04:16   Running git update for highway...
19:04:30 ┌ highway git  ................................. [Updates found]
19:04:30 ├ Running uninstall...
19:04:31 ├ Running cmake...
19:04:55 ├ Running build...
Likely error (tail of the failed operation logfile):
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  116 |                        F64_ERROR);                                        \
      |                        ~~~~~~~~~~
C:/MinGW-w64/build/highway-git/hwy/contrib/math/math_test.cc:229:1: note: in expansion of macro 'DEFINE_MATH_TEST'
  229 | DEFINE_MATH_TEST(SinCosCos,
      | ^~~~~~~~~~~~~~~~
C:/MinGW-w64/build/highway-git/hwy/contrib/math/math_test.cc:153:14: note: candidate is: 'template<class D, class V> V hwy::N_AVX3_ZEN4::SinCosCos(D, V)'
  153 | HWY_INLINE V SinCosCos(const D d, V x)
      |              ^~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW-w64/build/highway-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
19:21:41   Creating diagnostics file...

Attach C:\MinGW-w64\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11816985/logs.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/11816995/ab-suite.build.log)

**Comment by Cooly0** [comment]
I got it past Highway-git with disabling 'bmx' (bmx=2). 

But, I haven't finished compiling yet, and I believe it will be hours.

**Comment by Cooly0** [comment]
Failed at zvbi:
```
12:01:40 zvbi-0.2 0.2.35  ............................... [Not installed]
12:01:42 ┌ zvbi-0.2.35  .................................... [Downloaded]
12:01:42 ├ Running extract...
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11821385/logs.zip)

12:01:43 ├ Running configure...
12:02:56 ├ Running install...
Likely error (tail of the failed operation logfile):
                                 ^
../../src/export.c:1813:12: error: call to undeclared function 'open'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                int fd = open (name, flags, mode);
                         ^
3 errors generated.
make[2]: *** [Makefile:591: export.lo] Error 1
make[2]: Leaving directory '/build/zvbi-0.2.35/build-64bit/src'
make[1]: *** [Makefile:645: install-recursive] Error 1
make[1]: Leaving directory '/build/zvbi-0.2.35/build-64bit/src'
make: *** [Makefile:822: install] Error 2

```

**Comment by Cooly0** [comment]
Thanks!  But the further past that I get this:

```
17:03:37 zvbi-0.2 0.2.35  ............................... [Not installed]
17:03:37 ├ zvbi-0.2.35  ............................... [File up-to-date]
17:03:37 ├ Running extract...
17:03:39 ├ Running configure...
17:04:50 ├ Running install...
Likely error (tail of the failed operation logfile):
                                 ^
../../src/export.c:1813:12: error: call to undeclared function 'open'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                int fd = open (name, flags, mode);
                         ^
3 errors generated.
make[2]: *** [Makefile:591: export.lo] Error 1
make[2]: Leaving directory '/build/zvbi-0.2.35/build-64bit/src'
make[1]: *** [Makefile:645: install-recursive] Error 1
make[1]: Leaving directory '/build/zvbi-0.2.35/build-64bit/src'
make: *** [Makefile:822: install] Error 2

```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11826580/logs.zip)

**Comment by Fishman0919** [comment]
Highway seems to be working fine on it's own now

**Comment by Biswa96** [comment]
> Highway seems to be working fine on it's own now

The build issue with highway project was workaround by disabling tests compilation. The media-suite_compile.sh file of this project should now contain `-DHWY_ENABLE_TESTS=OFF` option.
