### ISSUE TITLE
Error running ffmpeg build when update cyanrip - undefined reference to `ff_golomb_vlc_len'

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2467]
```bash
20:48:46   Running git update for cyanrip...
20:48:47 ┌ cyanrip git  ................................. [Updates found]
20:49:00   Running git update for ffmpeg...
20:50:31 ┌ ffmpeg git  .................................. [Updates found]
20:50:31 ├ Running uninstall...
20:50:32 ├ Running configure...
20:53:43 ├ Running install...
20:55:59 ├ Running meson...
20:56:10 ├ Running build...
Likely error (tail of the failed operation logfile):
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/3] Generating src/version.c with a custom command
[2/2] Linking target src/cyanrip.exe
FAILED: src/cyanrip.exe
"gcc.bat"  -o src/cyanrip.exe src/cyanrip.exe.p/meson-generated_.._version.c.obj src/cyanrip.exe.p/cyanrip_encode.c.obj src/cyanrip.exe.p/cyanrip_log.c.obj src/cyanrip.exe.p/cyanrip_main.c.obj src/cyanrip.exe.p/utils.c.obj src/cyanrip.exe.p/fifo_frame.c.obj src/cyanrip.exe.p/discid.c.obj src/cyanrip.exe.p/musicbrainz.c.obj src/cyanrip.exe.p/coverart.c.obj src/cyanrip.exe.p/accurip.c.obj src/cyanrip.exe.p/cue_writer.c.obj "-LC:/MinGW-w64/local64/opt/cyanffmpeg/lib" "-LC:/MinGW-w64/local64/lib" "-IC:/MinGW-w64/local64/opt/cyanffmpeg/include" "-IC:/MinGW-w64/local64/include" "-Wl,--allow-shlib-undefined" "-Wl,-O1" "-pipe" "-static-libgcc" "-static-libstdc++" "-mthreads" "-mtune=generic" "-O2" "-DLIBXML_STATIC" "-D_FORTIFY_SOURCE=0" "-D__USE_MINGW_ANSI_STDIO=1" "-Wl,--start-group" "C:/MinGW-w64/local64/opt/cyanffmpeg/lib/libavcodec.a" "C:/MinGW-w64/msys64/mingw64/lib/libmp3lame.a" "C:/MinGW-w64/local64/lib/libopus.a" "C:/MinGW-w64/msys64/mingw64/lib/libvorbisenc.a" "C:/MinGW-w64/msys64/mingw64/lib/libvorbis.a" "C:/MinGW-w64/msys64/mingw64/lib/libogg.a" "C:/MinGW-w64/msys64/mingw64/lib/libole32.a" "C:/MinGW-w64/msys64/mingw64/lib/libz.a" "C:/MinGW-w64/local64/opt/cyanffmpeg/lib/libavutil.a" "-lm" "C:/MinGW-w64/msys64/mingw64/lib/libuser32.a" "C:/MinGW-w64/msys64/mingw64/lib/libbcrypt.a" "C:/MinGW-w64/msys64/mingw64/lib/libatomic.a" "C:/MinGW-w64/local64/opt/cyanffmpeg/lib/libavformat.a" "C:/MinGW-w64/local64/opt/cyanffmpeg/lib/libswresample.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libuser32.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libbcrypt.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libatomic.a" "C:/MinGW-w64/local64/opt/cyanffmpeg/lib/libavfilter.a" "C:/MinGW-w64/msys64/mingw64/lib/libcdio.a" "C:/MinGW-w64/msys64/mingw64/lib/libwinmm.a" "C:/MinGW-w64/msys64/mingw64/lib/libiconv.a" "C:/MinGW-w64/msys64/mingw64/lib/libcdio_paranoia.a" "C:/MinGW-w64/msys64/mingw64/lib/libcdio_cdda.a" "C:/MinGW-w64/local64/lib/libmusicbrainz5.a" "C:/MinGW-w64/local64/lib/libmusicbrainz5cc.a" "C:/MinGW-w64/msys64/mingw64/lib/libstdc++.a" "C:/MinGW-w64/local64/lib/libneon.a" "C:/MinGW-w64/msys64/mingw64/lib/libws2_32.a" "C:/MinGW-w64/local64/lib/libxml2.a" "C:/MinGW-w64/msys64/mingw64/lib/liblzma.a" "C:/MinGW-w64/local64/lib/libcurl.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libnghttp2.a" "C:/MinGW-w64/local64/lib/libpsl.a" "C:/MinGW-w64/local64/lib/libidn2.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libiconv.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libadvapi32.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libssl.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libcrypto.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libcrypt32.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libgdi32.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libwldap32.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libzstd.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libbrotlidec.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libbrotlicommon.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libz.a" "C:/MinGW-w64/msys64/mingw64/lib/../lib/libws2_32.a" "-pthread" "-Wl,--subsystem,console" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/opt/cyanffmpeg/lib/libavformat.a(evc.o):evc.c:(.rdata$.refptr.ff_ue_golomb_vlc_code[.refptr.ff_ue_golomb_vlc_code]+0x0): undefined reference to `ff_ue_golomb_vlc_code'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/opt/cyanffmpeg/lib/libavformat.a(evc.o):evc.c:(.rdata$.refptr.ff_golomb_vlc_len[.refptr.ff_golomb_vlc_len]+0x0): undefined reference to `ff_golomb_vlc_len'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW-w64/build/cyanrip-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
20:56:19   Creating diagnostics file...

Attach C:\MinGW-w64\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11848663/logs.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/11848668/ab-suite.build.log)

**Comment by Fishman0919** [comment]
Same.

12:35:04 ┌ cyanrip git  ................................. [Updates found]
12:35:07   Running git update for ffmpeg...
12:35:09 ┌ ffmpeg git  ............................... [Recently updated]
12:35:09 ├ Running uninstall...
12:35:09 ├ Running configure...
12:36:45 ├ Running install...
12:37:22 ├ Running meson...
12:37:25 ├ Running build...
Likely error (tail of the failed operation logfile):
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/3] Generating src/version.c with a custom command
[2/2] Linking target src/cyanrip.exe
FAILED: src/cyanrip.exe
"gcc.bat"  -o src/cyanrip.exe src/cyanrip.exe.p/meson-generated_.._version.c.obj src/cyanrip.exe.p/cyanrip_encode.c.obj src/cyanrip.exe.p/cyanrip_log.c.obj src/cyanrip.exe.p/cyanrip_main.c.obj src/cyanrip.exe.p/utils.c.obj src/cyanrip.exe.p/fifo_frame.c.obj src/cyanrip.exe.p/discid.c.obj src/cyanrip.exe.p/musicbrainz.c.obj src/cyanrip.exe.p/coverart.c.obj src/cyanrip.exe.p/accurip.c.obj src/cyanrip.exe.p/cue_writer.c.obj "-LC:/MAS/local64/opt/cyanffmpeg/lib" "-LC:/MAS/local64/lib" "-IC:/MAS/local64/opt/cyanffmpeg/include" "-IC:/MAS/local64/include" "-Wl,--allow-shlib-undefined" "-Wl,-O1" "-pipe" "-static-libgcc" "-static-libstdc++" "-mthreads" "-mtune=generic" "-O2" "-DLIBXML_STATIC" "-D_FORTIFY_SOURCE=0" "-D__USE_MINGW_ANSI_STDIO=1" "-Wl,--start-group" "C:/MAS/local64/opt/cyanffmpeg/lib/libavcodec.a" "C:/MAS/msys64/mingw64/lib/libmp3lame.a" "C:/MAS/local64/lib/libopus.a" "C:/MAS/msys64/mingw64/lib/libvorbisenc.a" "C:/MAS/msys64/mingw64/lib/libvorbis.a" "C:/MAS/msys64/mingw64/lib/libogg.a" "C:/MAS/msys64/mingw64/lib/libole32.a" "C:/MAS/msys64/mingw64/lib/libz.a" "C:/MAS/local64/opt/cyanffmpeg/lib/libavutil.a" "-lm" "C:/MAS/msys64/mingw64/lib/libuser32.a" "C:/MAS/msys64/mingw64/lib/libbcrypt.a" "C:/MAS/msys64/mingw64/lib/libatomic.a" "C:/MAS/local64/opt/cyanffmpeg/lib/libavformat.a" "C:/MAS/local64/opt/cyanffmpeg/lib/libswresample.a" "C:/MAS/msys64/mingw64/lib/../lib/libuser32.a" "C:/MAS/msys64/mingw64/lib/../lib/libbcrypt.a" "C:/MAS/msys64/mingw64/lib/../lib/libatomic.a" "C:/MAS/local64/opt/cyanffmpeg/lib/libavfilter.a" "C:/MAS/msys64/mingw64/lib/libcdio.a" "C:/MAS/msys64/mingw64/lib/libwinmm.a" "C:/MAS/msys64/mingw64/lib/libiconv.a" "C:/MAS/msys64/mingw64/lib/libcdio_paranoia.a" "C:/MAS/msys64/mingw64/lib/libcdio_cdda.a" "C:/MAS/local64/lib/libmusicbrainz5.a" "C:/MAS/local64/lib/libmusicbrainz5cc.a" "C:/MAS/msys64/mingw64/lib/libstdc++.a" "C:/MAS/local64/lib/libneon.a" "C:/MAS/msys64/mingw64/lib/libws2_32.a" "C:/MAS/local64/lib/libxml2.a" "C:/MAS/msys64/mingw64/lib/liblzma.a" "C:/MAS/local64/lib/libcurl.a" "C:/MAS/msys64/mingw64/lib/../lib/libnghttp2.a" "C:/MAS/local64/lib/libpsl.a" "C:/MAS/local64/lib/libidn2.a" "C:/MAS/msys64/mingw64/lib/../lib/libiconv.a" "C:/MAS/msys64/mingw64/lib/../lib/libadvapi32.a" "C:/MAS/msys64/mingw64/lib/../lib/libssl.a" "C:/MAS/msys64/mingw64/lib/../lib/libcrypto.a" "C:/MAS/msys64/mingw64/lib/../lib/libcrypt32.a" "C:/MAS/msys64/mingw64/lib/../lib/libgdi32.a" "C:/MAS/msys64/mingw64/lib/../lib/libwldap32.a" "C:/MAS/msys64/mingw64/lib/../lib/libzstd.a" "C:/MAS/msys64/mingw64/lib/../lib/libbrotlidec.a" "C:/MAS/msys64/mingw64/lib/../lib/libbrotlicommon.a" "C:/MAS/msys64/mingw64/lib/../lib/libz.a" "C:/MAS/msys64/mingw64/lib/../lib/libws2_32.a" "-pthread" "-Wl,--subsystem,console" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
C:/MAS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MAS/local64/opt/cyanffmpeg/lib/libavformat.a(evc.o):evc.c:(.rdata$.refptr.ff_ue_golomb_vlc_code[.refptr.ff_ue_golomb_vlc_code]+0x0): undefined reference to `ff_ue_golomb_vlc_code'
C:/MAS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MAS/local64/opt/cyanffmpeg/lib/libavformat.a(evc.o):evc.c:(.rdata$.refptr.ff_golomb_vlc_len[.refptr.ff_golomb_vlc_len]+0x0): undefined reference to `ff_golomb_vlc_len'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/MAS/build/cyanrip-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
12:37:28   Creating diagnostics file...

Attach C:\MAS\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11857752/logs.zip)

**Comment by LigH-de** [comment]
Golomb-Rice code might be related to JPEGXL. And cyanrip should omit any video related libraries.

**Comment by LigH-de** [comment]
Works again.

**Comment by ycwan** [comment]
Error did not recur.
