### ISSUE TITLE
Error running make when update ffmpeg - multiple definition of `vpx_idct16x16_256_add' & multiple definition of `vpx_comp_avg_pred'

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2477]
``` bash
23:14:53 ┌ ffmpeg git  .................................. [Updates found]
23:14:53 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
23:15:05 ├ Compiling static FFmpeg...
23:15:06 ├ Running uninstall...
23:15:06 ├ Running configure...
23:20:28 ├ Running make...
Likely error (tail of the failed operation logfile):
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:133: ffmpeg_g.exe] Error 1
make: *** Waiting for unfinished jobs....
make: *** [/build/ffmpeg-git/Makefile:133: ffplay_g.exe] Error 1
make: *** [/build/ffmpeg-git/Makefile:133: ffprobe_g.exe] Error 1
LD      ffmpeg_g.exe
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libSvtVp9Enc.a(EbEncHandle.c.obj):EbEncHandle.c:(.bss+0x240): multiple definition of `vpx_idct16x16_256_add'; C:/MinGW-w64/local64/lib/libvpx.a(vpx_dsp_rtcd.c.o):vpx_dsp_rtcd.c:(.bss+0x240): first defined here
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libSvtVp9Enc.a(EbEncHandle.c.obj):EbEncHandle.c:(.bss+0x430): multiple definition of `vpx_comp_avg_pred'; C:/MinGW-w64/local64/lib/libvpx.a(vpx_dsp_rtcd.c.o):vpx_dsp_rtcd.c:(.bss+0x598): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:133: ffmpeg_g.exe] Error 1
make failed. Check C:/MinGW-w64/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
23:43:29   Creating diagnostics file...

Attach C:\MinGW-w64\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11991045/logs.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/11991048/ab-suite.make.log)

**Comment by ChadDuck** [comment]
Not sure if it's on purpose, but I had the same error and commenting out "--enable-libsvtvp9" in build/ffmpeg_options.txt fixed the redefinition error and compilation finished with no issues.

SVT-VP9 won't be included in the binary though.

**Comment by Fishman0919** [comment]
Same.

15:36:15 ┌ ffmpeg git  .................................. [Updates found]
15:36:15 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
15:36:21 ├ Compiling static FFmpeg...
15:36:22 ├ Running configure...
15:39:23 ├ Running make...
Likely error (tail of the failed operation logfile):
make: *** Waiting for unfinished jobs....
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:133: ffmpeg_g.exe] Error 1
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:133: ffplay_g.exe] Error 1
LD      ffmpeg_g.exe
C:/MAS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MAS/local64/lib/libSvtVp9Enc.a(EbEncHandle.c.obj):EbEncHandle.c:(.bss+0x240): multiple definition of `vpx_idct16x16_256_add'; C:/MAS/local64/lib/libvpx.a(vpx_dsp_rtcd.c.o):vpx_dsp_rtcd.c:(.bss+0x240): first defined here
C:/MAS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MAS/local64/lib/libSvtVp9Enc.a(EbEncHandle.c.obj):EbEncHandle.c:(.bss+0x430): multiple definition of `vpx_comp_avg_pred'; C:/MAS/local64/lib/libvpx.a(vpx_dsp_rtcd.c.o):vpx_dsp_rtcd.c:(.bss+0x598): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:133: ffmpeg_g.exe] Error 1
make failed. Check C:/MAS/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/12006156/logs.zip)

**Comment by Fishman0919** [comment]
Yes, commenting out SVT-VP9 fixed it for me

**Comment by L4cache** [comment]
Weird but it works. (disabling svt-vp9)

**Comment by ycwan** [comment]
Update without errors even without disabling svt-vp9.
