### ISSUE TITLE
fontconfig fails to build

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2496]
┌ fontconfig git  ........................................ [Updates found]
├ Running uninstall...
├ Installing gperf... done
├ Running meson...
├ Running build...
Likely error (tail of the failed operation logfile):
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libfreetype.a(src_gzip_ftgzip.c.obj):(.text+0x945): undefined reference to `inflate'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libfreetype.a(src_gzip_ftgzip.c.obj):(.text+0x954): undefined reference to `inflateEnd'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libfreetype.a(src_gzip_ftgzip.c.obj):(.text+0x9ba): undefined reference to `inflateEnd'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libfreetype.a(src_bzip2_ftbzip2.c.obj):(.text+0x80): undefined reference to `BZ2_bzDecompressEnd'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libfreetype.a(src_bzip2_ftbzip2.c.obj):(.text+0x136): undefined reference to `BZ2_bzDecompress'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libfreetype.a(src_bzip2_ftbzip2.c.obj):(.text+0x309): undefined reference to `BZ2_bzDecompressEnd'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libfreetype.a(src_bzip2_ftbzip2.c.obj):(.text+0x365): undefined reference to `BZ2_bzDecompressInit'
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/msys64/mingw32/lib/libfreetype.a(src_bzip2_ftbzip2.c.obj):(.text+0x5f8): undefined reference to `BZ2_bzDecompressInit'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/12325023/logs.zip)

**Comment by basilisk0315** [comment]
Hi Barough,

I have the same issue.

**Comment by ultrasound1372** [comment]
Same here. Here's my  [logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/12391653/logs.zip).
The relevant portion from this end is probably this blurb.
```
C:/tools/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tools/mabs/msys64/mingw64/lib/libfreetype.a(src_gzip_ftgzip.c.obj):(.text+0x94e): undefined reference to `inflate'
C:/tools/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tools/mabs/msys64/mingw64/lib/libfreetype.a(src_gzip_ftgzip.c.obj):(.text+0x95d): undefined reference to `inflateEnd'
C:/tools/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tools/mabs/msys64/mingw64/lib/libfreetype.a(src_gzip_ftgzip.c.obj):(.text+0x9ba): undefined reference to `inflateEnd'
C:/tools/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tools/mabs/msys64/mingw64/lib/libfreetype.a(src_bzip2_ftbzip2.c.obj):(.text+0x6c): undefined reference to `BZ2_bzDecompressEnd'
C:/tools/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tools/mabs/msys64/mingw64/lib/libfreetype.a(src_bzip2_ftbzip2.c.obj):(.text+0x11d): undefined reference to `BZ2_bzDecompress'
C:/tools/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tools/mabs/msys64/mingw64/lib/libfreetype.a(src_bzip2_ftbzip2.c.obj):(.text+0x32a): undefined reference to `BZ2_bzDecompressEnd'
C:/tools/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tools/mabs/msys64/mingw64/lib/libfreetype.a(src_bzip2_ftbzip2.c.obj):(.text+0x380): undefined reference to `BZ2_bzDecompressInit'
C:/tools/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tools/mabs/msys64/mingw64/lib/libfreetype.a(src_bzip2_ftbzip2.c.obj):(.text+0x612): undefined reference to `BZ2_bzDecompressInit'

collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/tools/mabs/build/fontconfig-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
`
``

**Comment by Mhanz3500** [comment]
Same issue, new build 
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/12402875/ab-suite.build.log)

**Comment by ultrasound1372** [comment]
Yeah it turns out it gets hundreds of linker errors on my end, that tail was only a tiny fraction of them.

**Comment by Ajaja** [comment]
Had the same problem with x64 build. Removing msys2 freetype package (```pacman -R mingw-w64-x86_64-freetype ...``` with all packages that depend on it) fixed the issue.

**Comment by ultrasound1372** [comment]
Huh. Why is that being installed even if we build it from source? Suppose the script should be updated to not install freetype that way, then, or anything that depends on it.

**Comment by ultrasound1372** [comment]
That doesn't break anything else about the environment? I saw that removing glib2 and pcre among others. It also removed libcaca and harfbuzz but we already build those. And will the automatic update bring them back?

**Comment by doehrm** [comment]
I can confirm that doing 

`pacman -R mingw-w64-x86_64-freetype mingw-w64-x86_64-fontconfig mingw-w64-x86_64-harfbuzz mingw-w64-x86_64-libcaca  mingw-w64-x86_64-pango  mingw-w64-x86_64-cairo`

will bring back libcaca and harfbuzz after removal (with some error messages) but fontconfig can be built afterwards.

**Comment by Selur** [comment]
How should that look for 32bit?

**Comment by Selur** [comment]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/12738423/logs.zip)

**Comment by hydra3333** [comment]
> I can confirm that doing
> 
> `pacman -R mingw-w64-x86_64-freetype mingw-w64-x86_64-fontconfig mingw-w64-x86_64-harfbuzz mingw-w64-x86_64-libcaca mingw-w64-x86_64-pango mingw-w64-x86_64-cairo`
> 
> will bring back libcaca and harfbuzz after automatic update (with some error messages) but fontconfig can be built afterwards.

Does that mean this command should be in MABS now ?
Thanks in advance.

**Comment by Murmur** [comment]
See this comment I was finally able to compile ffmpeg with vulkan+libglslang+drawtext flags and `fontconfig` module as well compiled fine.
https://github.com/m-ab-s/media-autobuild_suite/issues/2494#issuecomment-1782566361
