### ISSUE TITLE
Build error libplacebo:: Run-time dependency dovi found: NO 

### ISSUE THREAD

**Issue by marcusdoc** [m-ab-s/media-autobuild_suite#2498]
It looks like libplacebo is looking for dovi_tool
https://github.com/quietvoid/dovi_tool

How can this be corrected?
(my apologies is this is a simple solution; I tried building with the script x2 and both times I had this result)
x64 build; most recent version of script

``` bash
23:55:44   Running git clone for libplacebo...
23:56:06   Running git update for libplacebo...
23:56:06 ┌ libplacebo git  ........................... [Recently updated]
23:56:08 ├ Installing python-mako... done
23:56:13 ├ Installing python-setuptools... done
23:56:46 ├ Running meson...
Likely error (tail of the failed operation logfile):
Run-time dependency vulkan found: YES 1.3.261
Header "vulkan/vulkan_core.h" has symbol "VK_VERSION_1_3" : YES
Run-time dependency lcms2 found: YES 2.15
Run-time dependency dovi found: NO (tried pkgconfig and cmake)
Configuring config.h using configuration
Configuring config_internal.h using configuration

../src/meson.build:217:6: ERROR: Cannot link_whole a custom or Rust target 'ucrt_math.lib' into a static library 'placebo'. Instead, pass individual object files with the "objects:" keyword argument if possible. Meson had to promote link to link_whole because 'placebo' is installed but not 'ucrt_math.lib', and thus has to include objects from 'ucrt_math.lib' to be usable.

A full log can be found at E:/ffmpeg_compile/build/libplacebo-git/build-64bit/meson-logs/meson-log.txt
meson failed. Check E:/ffmpeg_compile/build/libplacebo-git/build-64bit/ab-suite.meson.log
This is required for other packages, so this script will exit.
23:56:55   Creating diagnostics file...
```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/12364159/logs.zip)

**Comment by waldonnis** [comment]
I don't think the check for (lib)dovi is fatal and that the error is unrelated, but that's just from looking at the build scripts as I don't include libplacebo in my builds.  This error could be caused by the same issue that's affecting highway and other stuff that uses meson for building (see #2497).  You can try downgrading meson using the instructions in that bug report and see if that helps.

I do a separate scripted build of dovi_tool/libdovi and hdr10plus_tool periodically and use dovi_tool itself fairly frequently, so this report caught my eye.  If you want to include the dovi-related code in libplacebo, it's not difficult to build dovi_tool and libdovi...and quietvoid's build instructions are a good starting point.  Just be sure to check the dolby_vision dir too, which is where the library's code and instructions are.

Last I checked, there were no instructions for installing the binary or library, though.  I usually just cp the binary where I like it installed, but use cargo cinstall for the library (I just add a --prefix for my preferred install dir prefix).  I've never linked anything with the library yet and don't use much Rust stuff otherwise, so I'm not sure if --crt-static is needed as well.

**Comment by LigH-de** [comment]
You should include libplacebo in the title of this issue.

**Comment by marcusdoc** [comment]
ok ... did both suggestions in (see https://github.com/m-ab-s/media-autobuild_suite/issues/2497); passed the dovi issue, but libplacebo still problematic

I did delete the libplacebo folder to force a re-download but still the problem exists

`18:33:46 ┌ libplacebo git  ........................... [Recently updated]
18:35:27 ├ Running meson...
18:35:36 ├ Running build...
18:35:43 ├ Running install...
18:35:44 ├ Stripping...
18:35:44 └ libplacebo-git  .................................... [Updated]
18:35:58   Running git update for ffmpeg...
18:35:59 ┌ ffmpeg git  ............................... [Recently updated]
18:35:59 ├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK to run!
18:36:03 ├ Compiling static FFmpeg...
18:36:04 ├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -fstack-protector-strong -mtune=generic -O2 -pipe -mthreads
LDFLAGS: -pipe -static-libgcc -fstack-protector-strong -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-libsvtav1 --enable-chromaprint --enable-decklink --enable-frei0r --enable-libaribb24 --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libsvthevc --enable-libsvtvp9 --enable-libkvazaar --enable-libmodplug --enable-librist --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-libglslang --enable-vulkan --enable-libdavs2 --enable-libxavs2 --enable-libuavs3d --enable-libplacebo --enable-libjxl --enable-opencl --enable-opengl --enable-libnpp --enable-libopenh264 --enable-openssl --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-IC:/PROGRA~1/NVIDIA~2/CUDA/v12.2/include --extra-ldflags=-LC:/PROGRA~1/NVIDIA~2/CUDA/v12.2/lib/x64 --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-IE:/ffmpeg_compile/local64/include --extra-cflags=-IE:/ffmpeg_compile/local64/include/AL --extra-version=g81a48d96e2+3
ERROR: libplacebo >= 4.192.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check E:/ffmpeg_compile/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
18:37:33   Creating diagnostics file...

Attach E:\ffmpeg_compile\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/12374349/logs.zip)

Try running the build again at a later time.
`

**Comment by marcusdoc** [comment]
The meson-log.txt states the following:
```
Called: `pkgconf --keep-system-libs --keep-system-cflags --modversion dovi` -> 1
stderr:
Package dovi was not found in the pkg-config search path.
Perhaps you should add the directory containing `dovi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'dovi', required by 'virtual:world', not found
-----------
CMake binary for 1 is cached.
Preliminary CMake check failed. Aborting.
Run-time dependency dovi found: NO (tried pkgconfig and cmake)
```

**Comment by marcusdoc** [comment]
just hold on ... I'm going to start a completely fresh compile with the modifications from
(see https://github.com/m-ab-s/media-autobuild_suite/issues/2497)

**Comment by marcusdoc** [comment]
(see https://github.com/m-ab-s/media-autobuild_suite/issues/2497) resolves this error
closing report

**Comment by LigH-de** [comment]
I suspect a solution within the automated operation of the suite could be found, avoiding every user manually patching the system... but the linked discoveries will surely be helpful.
