### ISSUE TITLE
Can't reach the git repo

### ISSUE THREAD

**Issue by Now2407** [m-ab-s/media-autobuild_suite#2503]
Can't reach the git repo. the repo link is not working when visited.

attached are logs.
the output is pasted.
thanks.

Likely error (tail of the failed operation logfile):
CXXFLAGS: -fstack-protector-strong -mtune=generic -O2 -pipe -mthreads
LDFLAGS: -pipe -static-libgcc -fstack-protector-strong -static-libstdc++
vcs_fetch
++ git rev-parse --git-dir
+ [[ -f .git/shallow ]]
+ unshallow=
+ git fetch --all -Ppft
fatal: unable to access 'https://gitlab.gnome.org/GNOME/libxml2.git/': The requested URL returned error: 503
+ git remote set-head -a origin
fatal: unable to access 'https://gitlab.gnome.org/GNOME/libxml2.git/': The requested URL returned error: 503
git.fetch failed. Check C:/ffmpeg/build/libxml2-git/ab-suite.git.fetch.log
This is required for other packages, so this script will exit.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/12427148/logs.zip)

**Comment by Biswa96** [comment]
https://gitlab.gnome.org/ shows "Application is not available"
