### ISSUE TITLE
Just wondering if MABS updates are paused or something

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#2514]
Hi, not pressing for action, MABS updates haven't been made for a while so I am wondering if the author is busy ... holidays counts as busy ;) ... 

I suppose I could try to help by making some infrequent attempts at updates where I could figure some things out (likely not to the author's satisfaction, given my very low level of skill and knowledge) but guess pull requests won't be committed if the author is busy. 
I notice others propose pull requests, so not sure what the arrangements are.

Cheers

**Comment by 1480c1** [comment]
Hi @hydra3333,

I've just mainly been on coding hiatus and haven't touched any code in the past 2 months or so. Nothing particular, just was busy with real life stuff and didn't feel motivated to do anything related to code. Hopefully, as my cs classes start back up again, I'll feel more inclined to code.

If you submit a pull request that's simple enough to review and visually verify, I can merge it, no problem.

**Comment by hydra3333** [comment]
ok, thanks.

**Comment by maddes8cht** [comment]
As far as i can see, this whole thing seems 100% unusable in the moment, as it first fails the mediainfo compile #2506 ,
and if one uses that temporary workaround posted ther one runs into the vulkan-loader ail #2507
There seems to be other unresolved issues that may or may not be 100% showstopers, but at least these 2 are making the whole project 100% pointless until resolved.

**Comment by UlrikHD** [comment]
@maddes8cht You can set up WSL and run [ffmpeg-windows-build-helpers](https://github.com/rdp/ffmpeg-windows-build-helpers) until the issues are resolved.

**Comment by hydra3333** [comment]
> making the whole project 100% pointless

Well, one supposes you could use it as a base (fork) and fix the issues, thus not pointless ...

**Comment by hydra3333** [comment]
> @maddes8cht You can set up WSL and run [ffmpeg-windows-build-helpers](https://github.com/rdp/ffmpeg-windows-build-helpers) until the issues are resolved.

Cool.  

One could, I suppose use MABS users look at how rdp over there does it and create equivalent in pull requests for MABS ?

Also, I must take a look over at https://github.com/BtbN/FFmpeg-Builds (unofficial nightly successful builds without nonfree components such as fdk-aac) to see if there's stuff in there which is equivalent and could be borrowed in the same way.
