### ISSUE TITLE
 libjxl error

### ISSUE THREAD

**Issue by lyglay1991** [m-ab-s/media-autobuild_suite#2521]
┌ libjxl git  ............................... [Recently updated]
09:27:44 ├ Running cmake...
09:27:52 ├ Running build...
Likely error (tail of the failed operation logfile):
O:/ffmpeg/build/libjxl-git/lib/jxl/jxl_cms.cc:1003:9: error: 'struct jxl::ColorEncoding' has no member named 'rendering_intent'; did you mean 'GetRenderingIntent'?
 1003 |   c_enc.rendering_intent = static_cast<RenderingIntent>(rendering_intent32);
      |         ^~~~~~~~~~~~~~~~
      |         GetRenderingIntent
O:/ffmpeg/build/libjxl-git/lib/jxl/jxl_cms.cc: In function 'void* jxl::{anonymous}::JxlCmsInit(void*, size_t, size_t, const JxlColorProfile*, const JxlColorProfile*, float)':
O:/ffmpeg/build/libjxl-git/lib/jxl/jxl_cms.cc:1234:55: error: 'struct jxl::ColorEncoding' has no member named 'rendering_intent'; did you mean 'GetRenderingIntent'?
 1234 |   const uint32_t intent = static_cast<uint32_t>(c_dst.rendering_intent);
      |                                                       ^~~~~~~~~~~~~~~~
      |                                                       GetRenderingIntent
ninja: build stopped: subcommand failed.
build failed. Check O:/ffmpeg/build/libjxl-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
09:29:12   Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/12755153/logs.zip)

**Comment by mrtajniak** [comment]
Omg same here

**Comment by hydra3333** [comment]
I wonder, if someone has skills to contribute to MABS with pull requests to fix things such as this, please also see https://github.com/m-ab-s/media-autobuild_suite/issues/2514#issuecomment-1741595999 for suggestion on how to possibly contribute to updating MABS ?

**Comment by Biswa96** [comment]
This seems to be fixed in upstream libjxl but the brotli linking fails due to pkgconf bug. Could anyone verify that?

**Comment by mrtajniak** [comment]
There is a lot of patches to apply to this repo, I feel like everything in this repo because of age is broken 😞

**Comment by nikolasr** [comment]
I still had this problem (@Biswa96 even when downgrading pkgconf to 'safe' 1.8 version). Like always I became very _quick'n'dirty_  and changed in _media-suite_deps.sh_ : 
`SOURCE_REPO_LIBJXL=https://github.com/libjxl/libjxl.git` 
to 
`SOURCE_REPO_LIBJXL=https://github.com/libjxl/libjxl.git#tag=v0.8.2`
_Really ugly_, but works for now. :-)

**Comment by hydra3333** [comment]
Looks like there have been some upstream patches.
I built with the newest version by doing this:

In `media-suite_deps.sh` ensure these lines are there:
```
SOURCE_REPO_LCSM2=https://github.com/mm2/Little-CMS.git
SOURCE_REPO_LIBJXL=https://github.com/libjxl/libjxl.git
```

In `media-autobuild_suite.ini` ensure
```
jpegxl=2
```


In `media-suite_compile.sh` modify the area around building libxjl with a few changes so it looks like this (yes it is just an interime hack):
```
do_pacman_install asciidoc

if [[ $jpegxl = y ]] || { [[ $ffmpeg != no ]] && enabled libjxl; }; then

    # HACK - BUILD INSTALL OUR OWN UP TO DATE LCMS2 FOR LIBJXL TO FIND
    if do_vcs "$SOURCE_REPO_LCSM2"; then
        do_mesoninstall -Djpeg=enabled -Dtiff=enabled -Dsamples=false -Dthreaded=true -Dfastfloat=true
    fi

    _check=(bin/gflags_completions.sh gflags.pc gflags/gflags.h libgflags{,_nothreads}.a)
    if do_vcs "$SOURCE_REPO_GFLAGS"; then
        do_patch "https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/gflags/0001-cmake-chop-off-.lib-extension-from-shlwapi.patch" am
        do_uninstall "${_check[@]}" lib/cmake/gflags include/gflags
        do_cmakeinstall -D{BUILD,INSTALL}_STATIC_LIBS=ON -DBUILD_gflags_LIB=ON -DINSTALL_HEADERS=ON \
            -DREGISTER_{BUILD_DIR,INSTALL_PREFIX}=OFF
        do_checkIfExist
    fi

    _deps=(libgflags.a)
    _check=(libjxl{{,_dec,_threads}.a,.pc} jxl/decode.h)
    [[ $jpegxl = y ]] && _check+=(bin-global/{{c,d}jxl,cjpegli,jxlinfo}.exe)
    if do_vcs "$SOURCE_REPO_LIBJXL"; then
        do_patch "https://raw.githubusercontent.com/m-ab-s/mabs-patches/master/libjxl/0001-brotli-add-ldflags.patch" am
        do_uninstall "${_check[@]}" include/jxl
        #do_pacman_install lcms2 asciidoc
        extracommands=()
        log -q "git.submodule" git submodule update --init --recursive
        [[ $jpegxl = y ]] || extracommands=("-DJPEGXL_ENABLE_TOOLS=OFF")
        do_cmakeinstall global -D{JPEGXL_TEST_TOOLS,BUILD_TESTING,JPEGXL_ENABLE_{TOOLS,BENCHMARK,DOXYGEN,MANPAGES,OPENEXR,SKCMS,EXAMPLES}}=OFF \
            -DJPEGXL_{FORCE_SYSTEM_BROTLI,FORCE_SYSTEM_LCMS2,STATIC}=ON "${extracommands[@]}"
        do_checkIfExist
        unset extracommands
    fi
fi
```
