### ISSUE TITLE
tesseract git build failed

### ISSUE THREAD

**Issue by mangohugo** [m-ab-s/media-autobuild_suite#2531]
11:51:51 ┌ tesseract git  ............................ [Recently updated]
11:52:40 ├ Running autogen...
11:56:31 ├ Running configure...
12:04:03 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/ffmpeg2/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg2/msys64/mingw64/bin/../lib/libtiff.a(tif_webp.o):(.text+0xb35): undefined reference to `WebPIDecGetRGB'
C:/ffmpeg2/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg2/msys64/mingw64/bin/../lib/libtiff.a(tif_webp.o):(.text+0xbc3): undefined reference to `WebPIDelete'
C:/ffmpeg2/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg2/msys64/mingw64/bin/../lib/libtiff.a(tif_webp.o):(.text+0xbcf): undefined reference to `WebPFreeDecBuffer'
C:/ffmpeg2/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg2/msys64/mingw64/bin/../lib/libtiff.a(tif_webp.o):(.text+0xcca): undefined reference to `WebPInitDecBufferInternal'
C:/ffmpeg2/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg2/msys64/mingw64/bin/../lib/libtiff.a(tif_webp.o):(.text+0xd21): undefined reference to `WebPINewDecoder'
C:/ffmpeg2/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg2/msys64/mingw64/bin/../lib/libtiff.a(tif_webp.o):(.text+0xe02): undefined reference to `WebPInitDecBufferInternal'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:4482: tesseract.exe] Error 1
make[1]: Leaving directory '/build/tesseract-git/build-64bit'
make: *** [Makefile:8200: all-recursive] Error 1
make failed. Check C:/ffmpeg2/build/tesseract-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
12:18:42   Creating diagnostics file...

**Comment by 1480c1** [comment]
No zip file and have not been able to reproduce
