### ISSUE TITLE
undefined reference to `cmsCloseProfile' collect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by atplsx** [m-ab-s/media-autobuild_suite#2545]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/13053523/logs.zip)

**Comment by nille02** [comment]
As a work around, disable jpegxl. Edit media-autobuild_suite.ini and change `jpegxl=1` to `jpegxl=2`

**Comment by hydra3333** [comment]
It's a known issue with current building of libjxl.

Perhaps consider these:
https://github.com/m-ab-s/media-autobuild_suite/issues/2551#issuecomment-1783955605
https://github.com/m-ab-s/media-autobuild_suite/issues/2494#issuecomment-1782566361
