### ISSUE TITLE
collect2.exe: error: ld returned 1 exit status ninja: build stopped: subcommand failed. "libjxl"

### ISSUE THREAD

**Issue by bluttmer** [m-ab-s/media-autobuild_suite#2553]
I am trying to get this to work but it keeps failing with this error. What can I do?

[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/13199701/ab-suite.build.log)

**Comment by hydra3333** [comment]
It's a known issue with current building of libjxl.

Perhaps consider these:
https://github.com/m-ab-s/media-autobuild_suite/issues/2551#issuecomment-1783955605
https://github.com/m-ab-s/media-autobuild_suite/issues/2494#issuecomment-1782566361

**Comment by hydra3333** [comment]
Also https://github.com/m-ab-s/media-autobuild_suite/issues/2521#issuecomment-1807370461

**Comment by LigH-de** [comment]
It failed once for me after I didn't run the suite for longer, but worked when I ran the suite again right away.
