### ISSUE TITLE
Cargo build error ''Credential not satisfied'' / "rustc e0277"

### ISSUE THREAD

**Issue by Justuzz** [m-ab-s/media-autobuild_suite#2554]
I ran the media-autobuild_suite to compile some tools in 64bit on Windows 10 but an error occurs when building Cargo. I choosed not to build Cargo but it seems to be needed for compiling other tools. I tried to do some research on **_error[E0277]: the trait bound `WindowsCredential: cargo_credential::Credential` is not satisfied_** but no luck yet. Please see cli screenshot and log.zip attached. Cheers!

![Screen Shot 11-19-23 at 05 40 PM](https://github.com/m-ab-s/media-autobuild_suite/assets/140958701/80087550-136c-412c-babf-47c7d49c0d09)

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/13403899/logs.zip)

**Comment by marseb** [comment]
I have exactly the same e0277 error like you. I first tried it to build it yesterday. Today the error remain. It may be useful for other users, if you insert the error code "rustc --explain e0277" in the title...

Normal unmodded Win 11 12700h Laptop.

**Comment by 1480c1** [comment]
Upstream issue: https://github.com/lu-zero/cargo-c/issues/355#issuecomment-1818744965

**Comment by marseb** [comment]
This is solved by new upstream :)

But runs 2h later to another problem (maybe another thread/ or I am just wating another week) 😂

**Comment by Justuzz** [comment]
> But runs 2h later to another problem 
Same here. Basically I just want to compile ffmpeg and tried a variety of options but it always fails.

**Comment by marseb** [comment]
The same problem like me, with [mpv git](url=https://github.com/m-ab-s/media-autobuild_suite/issues/2555)?

**Comment by Justuzz** [comment]
> The same problem like me, with mpv git https://github.com/m-ab-s/media-autobuild_suite/issues/2555 ?

Not sure, I started the script again just now and will post a screenshot... *elevator music*

**Comment by marseb** [comment]
Thanks for feedback!
