### ISSUE TITLE
Configure ffmpeg: ERROR: libplacebo >= 4.192.0 not found using pkg-config

### ISSUE THREAD

**Issue by rainman74** [m-ab-s/media-autobuild_suite#2557]
All dependencies and libs are compiled correctly, but in the last step, the configuration of FFmpeg, this message appears:

```
media-autobuild_suite  (64bit): Running configure in ffmpeg-git
ERROR: libplacebo >= 4.192.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
This is required for other packages, so this script will exit.
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/13451490/logs.zip)

**Comment by hydra3333** [comment]
I fiddled with a few MABS options in files in the `build` subfolder to get it to build: ffmpeg_options.txt mpv_options.txt media-autobuild_suite.ini

It is possible those options may give you some or most of what you desire, take a look in them to see (eg I don't build mpv, for example).

To use those the three options files, 

- remove any previous MABS folder structure
- download a fresh copy of MABS and extract it into a new folder
- unzip the 3 files into the `build` subfolder in the new MABS folder structure
- run MABS as normal

Good luck.

[build.zip](https://github.com/m-ab-s/media-autobuild_suite/files/13456358/build.zip)

**Comment by rainman74** [comment]
> I fiddled with a few MABS options in files in the `build` subfolder to get it to build: ffmpeg_options.txt mpv_options.txt media-autobuild_suite.ini
> ```

Thanks for the tips, but that doesn't solve the problem, it just avoids it.

`--disable-libplacebo`

**Comment by hydra3333** [comment]
Yes, sorry, I should have made that caveat explicit.
It allows one to still build an ffmpeg using MABS with most other features ;)

**Comment by WernMich** [comment]
Having the same issue with fresh mabs from two day ago. Still no solution or workaround found by myself.

**Comment by 1480c1** [comment]
Should be fixed with https://github.com/m-ab-s/media-autobuild_suite/commit/e9fc1af2098bd3740b5391c658dc01e501b81d68

**Comment by rainman74** [comment]
Yes, it is fixed! Thank you.
