### ISSUE TITLE
rav1e fails: NASM build failed

### ISSUE THREAD

**Issue by Whitehawkx** [m-ab-s/media-autobuild_suite#2560]
┌ rav1e git  .......................................... [Recently updated]
├ Running rust.update...
├ Running rust.build...
Likely error (tail of the failed operation logfile):
  E:\media-autobuild_suite-master\build\rav1e-git\src/x86/sse.asm:444: ... from macro `WEIGHTED_SSE' defined here
  E:\media-autobuild_suite-master\build\rav1e-git\src/x86/sse.asm:474: warning: trailing garbage after macro name ignored [-w+pp-trailing]
  E:\media-autobuild_suite-master\build\rav1e-git\src/x86/sse.asm:444: ... from macro `WEIGHTED_SSE' defined here
  panic: E:\media-autobuild_suite-master\build\rav1e-git\src/x86/looprestoration16_sse.asm:3529: assertion data.insoffs == data.inslen failed at asm/assemble.c:908
  thread 'main' panicked at build.rs:153:7:
  NASM build failed. Make sure you have nasm installed or disable the "asm" feature.
  You can get NASM from https://nasm.us or your system's package manager.

  error: nonzero exit status: exit code: 0xc0000005
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
rust.build failed. Check E:/media-autobuild_suite-master/build/rav1e-git/ab-suite.rust.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach E:\media-autobuild_suite-master\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

_____________________________________________________________________________

Per the error message above I installed NASM and added to path. The build still fails with this error after doing so. I've never had to install NASM previously so found this strange. Did something change recently that now requires this? Any idea how to resolve?

_____________________________________________________________________________

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/13540738/logs.zip)

**Comment by dawkaka** [comment]
I'm currently facing the same issue, how did you get it to work.

**Comment by Whitehawkx** [comment]
I never did. Opened a new issue up about it here: https://github.com/m-ab-s/media-autobuild_suite/issues/2573

All I can figure is it's something about my PC build which is
13900k
RTX 4090
2x32GB RAM

**Comment by hydra3333** [comment]
> I never did. Opened a new issue up about it here: #2573
> 
> All I can figure is it's something about my PC build which is 13900k RTX 4090 2x32GB RAM

Ooh, nice, you must have been rich !
May one enquire about your s/w environment ?
