### ISSUE TITLE
shaderc git fail

### ISSUE THREAD

**Issue by Fishman0919** [m-ab-s/media-autobuild_suite#2561]
From a fresh install...

16:22:14   Running git clone for shaderc...
16:22:17   Running git update for shaderc...
16:22:17 ┌ shaderc git  .............................. [Recently updated]
16:22:18 ├ Running dependencies...
16:22:37 ├ Running cmake...
16:22:43 ├ Running build...
Likely error (tail of the failed operation logfile):
[18/21] Linking CXX static library libshaderc\libshaderc_combined.a
[19/21] Linking CXX static library glslc\libglslc.a
[20/21] Building CXX object glslc/CMakeFiles/glslc_exe.dir/src/main.cc.o
FAILED: glslc/CMakeFiles/glslc_exe.dir/src/main.cc.o
C:\MAS\msys64\mingw64\bin\ccache.exe  g++  -IC:/MAS/build/shaderc-git/build-64bit/glslc/.. -IC:/MAS/build/shaderc-git/third_party/spirv-tools/include -IC:/MAS/build/shaderc-git/third_party/glslang -IC:/MAS/build/shaderc-git/libshaderc_util/include -IC:/MAS/build/shaderc-git/libshaderc/include -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -Wimplicit-fallthrough -O3 -DNDEBUG -std=gnu++17 -Wextra-semi -Wall -fvisibility=hidden -MD -MT glslc/CMakeFiles/glslc_exe.dir/src/main.cc.o -MF glslc\CMakeFiles\glslc_exe.dir\src\main.cc.o.d -o glslc/CMakeFiles/glslc_exe.dir/src/main.cc.o -c C:/MAS/build/shaderc-git/glslc/src/main.cc
C:/MAS/build/shaderc-git/glslc/src/main.cc:208:10: fatal error: build-version.inc: No such file or directory
  208 | #include "build-version.inc"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
build failed. Check C:/MAS/build/shaderc-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
16:24:23   Creating diagnostics file...

Attach C:\MAS\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

 
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/13573460/logs.zip)

**Comment by 1480c1** [comment]
Cannot reproduce using the same config, if you see the issue again, you can comment and I can reopen
