### ISSUE TITLE
glslang fails

### ISSUE THREAD

**Issue by Fishman0919** [m-ab-s/media-autobuild_suite#2567]
11:59:39   Running git clone for glslang...
11:59:57   Running git update for glslang...
11:59:58 ┌ glslang git  .............................. [Recently updated]
11:59:58 ├ Installing python... done
12:00:00 ├ Running dependencies...
12:00:13 ├ Running cmake...
12:00:15 ├ Running build...
Likely error (tail of the failed operation logfile):
  263 | };
      | ^
C:/MAS/msys64/mingw64/include/c++/13.2.0/tuple:2005:45: note: candidate: 'template<class _Tp, long long unsigned int _Nm> array(std::array<_Tp, _Nm>)-> std::array<_Tp, _Nm>'
 2005 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
C:/MAS/msys64/mingw64/include/c++/13.2.0/tuple:2005:45: note:   template argument deduction/substitution failed:
C:/MAS/build/glslang-git/glslang/MachineIndependent/Initialize.cpp:263:1: note:   'glslang::{anonymous}::BuiltInFunction' is not derived from 'std::array<_Tp, _Nm>'
  263 | };
      | ^
ninja: build stopped: subcommand failed.
build failed. Check C:/MAS/build/glslang-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
12:01:37   Creating diagnostics file...

Attach C:\MAS\build\logs.zip to the GitHub issue.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/13759742/logs.zip)

**Comment by doehrm** [comment]
The upstream changes from this commit seem to have caused this:

https://github.com/KhronosGroup/glslang/commit/0ae8960087182fbda997a04aca130ec2d7720b66

Is there an easy way of un-patching just this commit?

**Comment by doehrm** [comment]
seems to be fixed by https://github.com/m-ab-s/media-autobuild_suite/commit/56bc538a941134f68a436dd79e8301db5d18c516

**Comment by 1480c1** [comment]
https://github.com/KhronosGroup/glslang/commit/809fd43ed62d0b3b7827fcd6913db03588f58b08
