### ISSUE TITLE
Rust install failed.

### ISSUE THREAD

**Issue by classicdoomenjoyer** [m-ab-s/media-autobuild_suite#2575]
I am using the latest version of Media Autobuild Suite.

21:46:51
        Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
21:47:14
        Starting 64bit compilation of global tools
21:47:14 ├ Running download_rustup...
21:47:25 ├ Running install_rust...
Likely error (tail of the failed operation logfile):
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++
./rustup.sh -v -y --no-modify-path --default-host=x86_64-pc-windows-gnu --default-toolchain=stable
info: downloading installer
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe /tmp/tmp.KhTHA4t3Dd/rustup-init.exe x86_64-pc-windows-gnu
install_rust failed. Check D:/Media_autobuild/build/rustinstall/ab-suite.install_rust.log
This is required for other packages, so this script will exit.
21:47:31   Creating diagnostics file...

Attach D:\Media_autobuild\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/13930251/logs.zip)

I tried to run the build twice, but it failed.

I uninstalled everything like msys, mingw32/64, and did a fresh re-install, but the problem still persits.

**Comment by hydra3333** [comment]
Hmm.

I just successfully compiled ffmpeg using standard MABS (excluding libplacebo, libjxl, and a couple of others) without thee issue you describe.  Built in a windows 11  sandbox. Host had latest win11 and nearly up to date nvidia drivers (no cuda toolkit etc).

The nature of the issue looks like a connectivity related issue.  
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it.

```

Network issues ? Firewall issues ?  Infected ? etc.

**Comment by classicdoomenjoyer** [comment]
I have a pretty fast internet connection here.

Never mind, I downloaded curl.exe and curl-ca-bundle.crt and pasted it in C drive.

I will close the issue right now.

**Comment by hydra3333** [comment]
Cool.  Still feels like something is wrong with your rig, security wise, for you to experience that.

**Comment by classicdoomenjoyer** [comment]
> Cool. Still feels like something is wrong with your rig, security wise, for you to experience that. It had nothing whatsoever to do with your internet connection speed. Cheers.

No, I have a purchased version of Avast Antivirus in my PC so nothing to worry about ig.
