### ISSUE TITLE
mingw64 curl libpsl patch could not be applied

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2577]
21:23:37 libpsl 0.21.0  .................................... [Up-to-date]
21:23:43   Running git update for curl...
21:23:56 ┌ curl git  .................................... [Updates found]
0003-libpsl-static-libs.patch
        Patch could not be applied with `patch`. Continuing without patching.
21:23:58 ├ Running uninstall...
21:23:58 ├ Running autoreconf...
21:24:28 ├ Running configure...
21:26:51 ├ Running make...
21:28:29 ├ Running install...
21:28:35 ├ Running ca-bundle...
21:28:43 ├ Stripping...
21:28:43 └ curl-git  .......................................... [Updated]

**Comment by hydra3333** [comment]
Me too.

**Comment by 1480c1** [comment]
Fixed with https://github.com/m-ab-s/media-autobuild_suite/commit/5b99bd792de238ae4676b25e6fae56f35de194cf
