### ISSUE TITLE
Request: pls consider updating vapoursynth to R65

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#2583]
Hello.

Currently, vapoursynth here is at R61.
I notice that the current vapoursynth release is R65 (with python 3.11) and it has a range of bugfixes.

Would there be any chance of updating it to R65 ?

Thanks

**Comment by 1480c1** [comment]
Updated in https://github.com/m-ab-s/media-autobuild_suite/commit/7fb7532c96ef79ff12585d08098cc386270c9d09, open an issue if it's broken

**Comment by hydra3333** [comment]
OK, I'll try it.  

I recall recently trying to use portable R65 with python 3.12.1 and had issues, so had to revert to python 3.11.7 which is specified in portable vapoursynth R65's `vs-detect-python.bat`.

Anyway, I'll give it a whirl as-is and let you know.

**Comment by hydra3333** [comment]
Ah. 
As soon as I pop portable (embedded) python 3.12.1 into the portable vapoursynth folder, over the top of python 3.11.7 (which is the way of doing it) then things break, eg vsrepo crashes.

So, for R65 python needs to be reverted to python 3.11.7 ...

**Comment by 1480c1** [comment]
So r65 should be fine with 3.11.7? 1346bd914c

**Comment by hydra3333** [comment]
Should be.
That's what's in the R65 release in file `vs-detect-python.bat` (it's changed in the git head to 3.12.1 however that's not yet a release).
I run R65 with  3.11.7 and vsrepo does not crash (whereas it does crash with 3.12.1).

Thanks !

**Comment by hydra3333** [comment]
It works !

Thank you muchly.

**Comment by LigH-de** [comment]
R66 is available, requires Python 3.12.

**Comment by hydra3333** [comment]
Interestingly,

1. the release has this as a NEW asset `Install-Portable-VapourSynth-R66.ps1`
2. `Install-Portable-VapourSynth-R66.ps1` specifies python 3.12.2
3. After downloading and extracting vapoursynth,  `Install-Portable-VapourSynth-R66.ps1` **specifically** removes `.\VSScriptPython38.dll` which came in the python .zip before installing python

Here's the section of code:
```
Write-Host "Extracting Python..."
Expand-Archive -LiteralPath ".\Downloads\python-$PythonVersionMajor.$PythonVersionMid.$PythonVersionMinor-embed-amd64.zip" -DestinationPath ".\" -Force
Add-Content -Path ".\python$PythonVersionMajor$PythonVersionMid._pth" -Encoding UTF8 -Value "..\Scripts" | Out-Null
Add-Content -Path ".\python$PythonVersionMajor$PythonVersionMid._pth" -Encoding UTF8 -Value "Scripts" | Out-Null
Add-Content -Path ".\python$PythonVersionMajor$PythonVersionMid._pth" -Encoding UTF8 -Value "Lib\site-packages" | Out-Null
Write-Host "Installing Pip..."
& ".\python.exe" ".\Downloads\get-pip.py" "--no-warn-script-location"
Remove-Item -Path ".\Scripts\*.exe"
Write-Host "Extracting VapourSynth..."
Expand-Archive -LiteralPath ".\Downloads\VapourSynth64-Portable-R$VSVersion.zip" -DestinationPath ".\" -Force
Remove-Item -Path ".\VSScriptPython38.dll"
Write-Host "Installing VapourSynth..."
& ".\python.exe" "-m" "pip" "install" ".\wheel\VapourSynth-$VSVersion-cp$PythonVersionMajor$PythonVersionMid-cp$PythonVersionMajor$PythonVersionMid-win_amd64.whl"

```

**Comment by hydra3333** [comment]
I think I'll test MABS build with R66 and 3.12.2 (without the wheel stuff)  and if it works post a request to use R66

**Comment by LigH-de** [comment]
**Myrsloik** reported:
> The portable install script and portable zip have now been sneakily updated to fix several annoying issues related to plugin and script paths. Windows 7 support also added, however you'll need to install powershell 5.0 or later to actually run it since the bundled version on win7 is ancient.

**Comment by hydra3333** [comment]
OK, the revised release of R66 works. 

There's a possible caveat on the portable install via the file `Install-Portable-VapourSynth-RXX.ps1` though; it installs into a slightly different place than the documentation suggests depending on how you read it - any scripts you may have could need to be changed unless you tell R66t to install in the place you want.
Reference: https://github.com/vapoursynth/vapoursynth/issues/1037

Would it be possible to update MABS to use R66 ?

Thanks
