### ISSUE TITLE
[mingw32] [bmx] liburiparser not found

### ISSUE THREAD

**Issue by technically-speaking** [m-ab-s/media-autobuild_suite#2585]
[ab-suite.configure.log](https://github.com/m-ab-s/media-autobuild_suite/files/14005639/ab-suite.configure.log)

**Comment by 1480c1** [comment]
Can you find the logs.zip file and upload that here?

**Comment by technically-speaking** [comment]
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14016303/logs.zip)

**Comment by 1480c1** [comment]
Seems the issue stems from uriparser being removed from mingw32's repository <https://github.com/msys2/MINGW-packages/commit/61e4e1d0b90b88e8b86e67f2e98e9b3bdde135dc>. Similar issue with mbedtls, going to need to figure out a workaround or something else.

**Comment by LigH-de** [comment]
Could liburiparser be built from sources instead of relying on a shipped package?

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/2487e0c5714e04363aa160d973800be0ecf70139
