### ISSUE TITLE
DLL missing in ffmpeg (both static & shared)

### ISSUE THREAD

**Issue by F1FAQ** [m-ab-s/media-autobuild_suite#2586]
Bonjour,
After compiling ffmpeg (both static and shared) I found that they were not running in my test directory. I found that the libopenh264.dll was missing. Adding it manually in the ffmpeg or ffmpeg-shared test directory I made, made them both running well...

**Comment by 1480c1** [comment]
I am not sure if I understand what you mean by “my test directory”?

All the .dlls for a shared ffmpeg should be present in the local64\bin-video folder for you to use or copy

**Comment by F1FAQ** [comment]
Sorry, it appears that I made a mistake while testing and sorry for your time
