### ISSUE TITLE
RE: Request: pls consider updating vapoursynth to R65 #2583

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#2587]
Sorry, I could not find a way to re-open the original issue.  Cheers.

https://github.com/m-ab-s/media-autobuild_suite/issues/2583#issuecomment-1907081533
> Ah.
> As soon as I pop portable (embedded) python 3.12.1 into the portable vapoursynth folder, over the top of python 3.11.7 (which is the way of doing it) then things break, eg vsrepo crashes.
> 
> So, for R65 python needs to be reverted to python 3.11.7 ...

**Comment by 1480c1** [comment]
Reopened
