### ISSUE TITLE
Function calls not updated after signature change in libavcodec\libjxldec.c

### ISSUE THREAD

**Issue by a-j-albert** [m-ab-s/media-autobuild_suite#2588]
In libjxl-git\CHANGELOG.md there's a line:

- decoder API: the signature of `JxlDecoderGetColorAsEncodedProfile`,
  `JxlDecoderGetICCProfileSize`, and `JxlDecoderGetColorAsICCProfile`

Those functions are called in libjxldec.c under conditional compilation.  For each use, one case was changed to fit the new signature, but not the alternate one.  E.g., line 216:

#if JPEGXL_NUMERIC_VERSION < JPEGXL_COMPUTE_NUMERIC_VERSION(0, 9, 0)
    jret = JxlDecoderGetICCProfileSize(ctx->decoder, &ctx->jxl_pixfmt, JXL_COLOR_PROFILE_TARGET_DATA, &icc_len);
#else
    jret = JxlDecoderGetICCProfileSize(ctx->decoder, JXL_COLOR_PROFILE_TARGET_DATA, &icc_len);
#endif

The first case above has the now unused argument &ctx->jxl_pixfmt, which causes the build to fail.  (Also see lines 267, 276 and 227

I'm not sure why my build hits that case.

**Comment by a-j-albert** [comment]
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/14034178/ab-suite.make.log)

**Comment by a-j-albert** [comment]
I didn't mean to close it.

**Comment by 1480c1** [comment]
Should be closed with https://github.com/libjxl/libjxl/pull/3184
