### ISSUE TITLE
dssim fails

### ISSUE THREAD

**Issue by Fishman0919** [m-ab-s/media-autobuild_suite#2589]
19:24:00   Running git update for dssim...
19:24:01 ┌ dssim git  ................................ [Recently updated]
19:24:01 ├ Running rust.update...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++
/opt/cargo/bin/cargo.exe update
error: failed to load manifest for dependency `ordered-channel`

Caused by:
  failed to read `C:\MABS\build\ordered-channel\Cargo.toml`

Caused by:
  The system cannot find the path specified. (os error 3)
rust.update failed. Check C:/MABS/build/dssim-git/ab-suite.rust.update.log
This is required for other packages, so this script will exit.
19:24:01   Creating diagnostics file...

Attach C:\MABS\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14059063/logs.zip)

**Comment by 1480c1** [comment]
Fixed with https://github.com/kornelski/dssim/commit/f3e2191efed786081f780ddea08a1e6027f31680
