### ISSUE TITLE
[mingw64] [ogg] Building ogg fails at ./autogen.sh 

### ISSUE THREAD

**Issue by yurysch** [m-ab-s/media-autobuild_suite#2594]
Building for 64-bit arch, ogg build fails at the configuration step. I verified that ltmain.sh is copied to the ogg root directory (ogg-git).
``` bash
./autogen.sh 
Updating build configuration files for libogg, please wait....
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
autoreconf-2.72: error: libtoolize failed with exit status: 1
```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14101446/logs.zip)

Running the following command (from autogen.sh) manually in ogg-git succeeds:
``` bash
autoreconf -if
```

**Comment by 1480c1** [comment]
haven't been able to reproduce, if you still have the issue, you can comment and I can reopen and check again
