### ISSUE TITLE
ffmpeg fail (vulkan)

### ISSUE THREAD

**Issue by Fishman0919** [m-ab-s/media-autobuild_suite#2595]
05:13:24   Running git update for ffmpeg...
05:13:25 ┌ ffmpeg git  ............................... [Recently updated]
05:13:25 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
05:13:31 ├ Compiling static FFmpeg...
05:13:32 ├ Running configure...
05:16:27 ├ Running make...
Likely error (tail of the failed operation logfile):
      |     av1_params
C:/MABS/build/ffmpeg-git/libavcodec/vulkan_av1.c:115:53: note: 'av1_params' declared here
  115 |     VkVideoDecodeAV1SessionParametersCreateInfoMESA av1_params;
      |                                                     ^
C:/MABS/build/ffmpeg-git/libavcodec/vulkan_av1.c:171:24: error: use of undeclared identifier 'VkVideoDecodeAV1SessionParametersAddInfoMESA'
  171 |     av1_params_info = (VkVideoDecodeAV1SessionParametersAddInfoMESA) {
      |                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/vulkan_av1.o] Error 1
make failed. Check C:/MABS/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
05:19:45   Creating diagnostics file...

Attach C:\MABS\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14138772/logs.zip)

**Comment by cantrell216** [comment]
similar here.  disabling vulkan is temp fix if that is an option.

 ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
      |                                                                                      ^
src/libavcodec/vulkan_av1.c: In function 'vk_av1_end_frame':
src/libavcodec/vulkan_av1.c:516:23: error: request for member 'nb_tiles' in something not a structure or union
  516 |     if (!ap->tile_list.nb_tiles)
      |                       ^
src/libavcodec/vulkan_av1.c:534:42: error: request for member 'nb_tiles' in something not a structure or union
  534 |            vp->slices_size, ap->tile_list.nb_tiles);
      |                                          ^
cc1.exe: some warnings being treated as errors
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/vulkan_av1.o] Error 1
make failed. Check C:/ffmpeg/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.

**Comment by 1480c1** [comment]
Should be resolved for now with https://github.com/m-ab-s/media-autobuild_suite/commit/a74adbc79084c32c1d43e6fa18faf95a681cafbd
