### ISSUE TITLE
git clone for dav1d failed, running mason failed under compile

### ISSUE THREAD

**Issue by Ekhrikhor** [m-ab-s/media-autobuild_suite#2596]
There it is the error:

`10:38:33   Running git clone for dav1d...
dav1d git seems to be down
Try again later or <Enter> to continue

if you're sure nothing depends on it.
10:38:38 ├ Running meson...
Likely error (tail of the failed operation logfile):
CPPFLAGS:
CFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -mthreads
CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++
meson setup .. --default-library=static --buildtype=release --prefix=/local64 --backend=ninja --bindir=bin-video -Denable_tests=false -Denable_examples=false

ERROR: Neither source directory '..' nor build directory None contain a build file meson.build.
meson failed. Check C:/media-autobuild_suite/build/build-64bit/ab-suite.meson.log
This is required for other packages, so this script will exit.
10:38:38   Creating diagnostics file...`

I attached the log file
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14150927/logs.zip)

So I can't finish compile under win11 64 bit system
What can I do?
Thanks for help

**Comment by L4cache** [comment]
This is part your network issue. Or gitlab's. I ran the suite around that time too, not saw this, so probably you net issue.
I remember normally this **continue** option should skip to the next component, and finish the rest of the jobs, but here it incorrectly ran the dav1d building process under /build causes error.

**Comment by 1480c1** [comment]
Not reproduced, so probably a temporary issue

**Comment by L4cache** [comment]
> Not reproduced, so probably a temporary issue

Most likely, but would it be good to investigate why "continue" failed?

**Comment by 1480c1** [comment]
I have a guess as to why and a potential fix https://github.com/m-ab-s/media-autobuild_suite/commit/166778ef04be961b50f02ff4e621a30d1222f83f
