### ISSUE TITLE
Suite downloads older version of libopenh264

### ISSUE THREAD

**Issue by blap-o** [m-ab-s/media-autobuild_suite#2602]
Attempted to build ffmpeg today with the latest version of the media-autobuild_suite on Windows.

The build process is successful but version 2.3.1 of openh264 is downloaded instead of the latest (2.4.0). 

I manually downloaded 2.4.0 and replaced it with the version downloaded by the suite AFTER compile and ffmpeg seems to work fine with it.

Is this a problem? Does the build process actually do something with the openh264 dll? Or is the dll only important when something needs to be encoded/decoded?

If the later is true, can I then just upgrade the codec manually after the media suite compile process is complete?

**Comment by 1480c1** [comment]
Probably more like that I did not know they updated it. Shouldn't have any known issue afaik

**Comment by 1480c1** [comment]
> Is this a problem? Does the build process actually do something with the openh264 dll? Or is the dll only important when something needs to be encoded/decoded?

As far as I remember, the main things we do with it is just to have it next to ffmpeg.exe in bin-video. We rely on msys2's package for the headers and pkg-config file and import library, so we don't compile it ourselves, potentially going against their license. The dll should actually only be needed when running the binary, as it is not `dlopen`'d or `LoadLibrary`'d.


> If the later is true, can I then just upgrade the codec manually after the media suite compile process is complete?

Nothing that I know of should be stopping that.

**Comment by blap-o** [comment]
Thank you very much for the explanation @1480c1 ! I'll do just that in case next time there is a new version.
