### ISSUE TITLE
[mingw32|mingw64] [repo] FFMPEG looking for libopenh264-7.dll instead of libopenh264.dll

### ISSUE THREAD

**Issue by Travillion** [m-ab-s/media-autobuild_suite#2606]
``` bash
Paste output of the suite here
```
I just compiled ffmpeg (64-bit version) on a fresh PC build (Win 11 Home, 64-bit). Everything seemed to go okay. After adding the appropriate PATH variables, I couldn't run ffmpeg from the command prompt (just a basic 'ffmpeg -i [.mkv file]' to make sure it was working). I got an error saying that ffmpeg could not find libopenh264-7.dll. I found libopenh264.dll in the bin-video folder. I renamed this to libopenh264-7.dll and ffmpeg seems to run fine. I'm wondering why it was looking for *-7.dll instead of what was built. As I said before, this is a fresh PC build. I'm not aware of any other instances of ffmpeg on this machine, except for whatever may have been installed with Plex Media Server. The compile log is attached. There were no errors with the build, except two patches were not applied (FFmpeg-devel-2-2-lavc-vulkan_av1-port-to-the-new-stable-API.diff and 0001-glslang-Remove-HLSL-and-OGLCompiler-libraries.patch).
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)
[compile.log](https://github.com/m-ab-s/media-autobuild_suite/files/14335823/compile.log)

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/bcdfaf05d45423be2d37cd742d53a3a0b3045962
