### ISSUE TITLE
[mingw64] [opus] getting the same error after what should be the fix

### ISSUE THREAD

**Issue by L4cache** [m-ab-s/media-autobuild_suite#2609]
Reference: https://github.com/m-ab-s/media-autobuild_suite/issues/2597

I wasn't getting the error before but after commit https://github.com/m-ab-s/media-autobuild_suite/commit/0c689127fd309ae0d401707e19f9cef6a5f653a1 I got this error.

``` bash
11:32:37 ┌ opus git  .................................... [Updates found]
11:32:42 ├ Installing wget... done
11:32:58 ├ Running uninstall...
11:32:58 ├ Running autogen...
Wget https://media.xiph.org/opus/models/opus_data-735117b.tar.gzLikely error (tail of the failed operation logfile):
CFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O3 -pipe -D__USE_MINGW_ANSI_STDIO=1 --start-no-unused-arguments -mthreads --end-no-unused-arguments -Qunused-arguments
CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O3 -pipe -D__USE_MINGW_ANSI_STDIO=1
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O3 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc --start-no-unused-arguments -static-libstdc++ --end-no-unused-arguments
./autogen.sh 
Downloading latest model
--2024-02-23 11:33:01--  https://media.xiph.org/opus/models/opus_data-735117b.tar.gz
Resolving media.xiph.org (media.xiph.org)... 54.39.18.101
Connecting to media.xiph.org (media.xiph.org)|54.39.18.101|:443... connected.
ERROR: The certificate of 'media.xiph.org' is not trusted.
ERROR: The certificate of 'media.xiph.org' doesn't have a known issuer.
autogen failed. Check C:/m-ab-s/build/opus-git/ab-suite.autogen.log
This is required for other packages, so this script will exit.
11:33:02   Creating diagnostics file...

```

I think patch the opus autogen with `--no-check-certificate` added to wget command would be a solution, or like Biswa96 in referenced issue's comments said remove the whole section that downloads the file.

**Comment by hydra3333** [comment]
me too.

hmm, especially nowadays isn't `--no-check-certificate` a bit on the unsafe side ?

**Comment by L4cache** [comment]
> me too.
> 
> hmm, especially nowadays isn't `--no-check-certificate` a bit on the unsafe side ?

It just some NN model data... should be okay, I guess?

**Comment by hydra3333** [comment]
Hmm, no.
Checking certs has nothing to do with current content ... not checking certs is about flagging if someone has introduced something nefarious and especially nowadays is not recommended.

**Comment by L4cache** [comment]
I'm talking about using no-check-certificate for just this one command that went wrong.

Seems harmless to *unknowing me* since it only downloads, and the content is some... non-essential stuff I guess?
And it maybe even not used by the build process that m-ab-s uses because we can just ignore it. (comment the line calls `dnn/download_model.sh` in `opus-git/autogen.sh`)

Well, then, if it's not used, ignoring it is the better way.

**Comment by L4cache** [comment]
It looks like after the ca-certificate package was updated I have no problems here (both msys and mingw wget), how about those who were having problems with the msys wget?

**Comment by L4cache** [comment]
@1480c1 Shall we close this issue?
