### ISSUE TITLE
Patch could not be applied with `git am`

### ISSUE THREAD

**Issue by F1FAQ** [m-ab-s/media-autobuild_suite#2611]
I need ffmpeg with vvenc and vvdec embedded to make tests via a Satellite DVB-S2 link.
I found a patch to do so on the Fraunhoferhhi web site via media-autobuild_suite: "https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#windows"
I stricly followed the procedure, but the ffmpeg compilation failed. Hereafter last lines of the compilation log, just after vvenc and vvdec have been successfully compiled.
Any help welcome / Thank you
  
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
FFmpeg-devel-v1-2-5-avformat-add-muxer-support-for-H266-VVC.patch
        Patch could not be applied with `git am`. Continuing without patching.
FFmpeg-devel-v1-3-5-avformat-add-ts-stream-types-for-H266-VVC.patch
        Patch could not be applied with `git am`. Continuing without patching.
FFmpeg-devel-v1-5-5-avcodec-add-external-decoder-libvvdec-for-H266-VVC.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Compiling shared FFmpeg...
├ Running configure...
Likely error (tail of the failed operation logfile):
CPPFLAGS:
CFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 --start-no-unused-arguments -mthreads --end-no-unused-arguments -Qunused-arguments
CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc --start-no-unused-arguments -static-libstdc++ --end-no-unused-arguments -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --disable-static --enable-shared --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache clang --cxx=ccache clang++ --ld=ccache clang++ --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-gmp --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-libvvdec --enable-libvvenc --enable-gpl --enable-version3 --enable-libsvtav1 --enable-schannel --extra-libs=-liconv --enable-nonfree --prefix=/local64/bin-video/ffmpegSHARED
Unknown option "--enable-libvvdec".
See ../configure --help for available options.
configure failed. Check C:/Dev/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14448982/logs.zip)

**Comment by 1480c1** [comment]
you will need to request vvdec to rebase their patches, this is not something we can really help with

**Comment by F1FAQ** [comment]
Many thanks for quick reply I will revert to them

**Comment by L4cache** [comment]
There's native vvc decoder now, you can let m-ab-s use the 6.1 release branch if you want to apply that patch (like fraunhofer suggested)
