### ISSUE TITLE
newly revised release of Vapoursynth R66

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#2618]
OK, the newly revised release of Vapoursynth R66 works, after some initial tests. 
The assets in the github R66 release have been updated in-place to ensure portable installation is more "local".

There's a possible caveat on the portable install via the file Install-Portable-VapourSynth-RXX.ps1 though; it installs into a slightly different place than the documentation suggests depending on how you read it - any scripts you may have could need to be changed unless you tell R66 to install in the place you want.
Reference: https://github.com/vapoursynth/vapoursynth/issues/1037

Would it be possible to update MABS to use vapoursynth R66 ?

Thanks

**Comment by 1480c1** [comment]
once my laptop gets back from repairs, I will try to take a look at it

**Comment by L4cache** [comment]
I bet you can just unzip the wheel file and place the .dll and .pyd file in the old place and call it a day

**Comment by hydra3333** [comment]
> I bet you can just unzip the wheel file and place the .dll and .pyd file in the old place and call it a day

um, different subfolder names for a start ...

**Comment by L4cache** [comment]
> um, different subfolder names for a start (if you are installing for real) ...

Only plugins folders of portable changed, but the suite didn't install plugins.
They're different to older version, but I mean there should be no difference between install the wheel with pip and just unzip wheel (and move .dll .pyd files to proper location) based on my understanding. Although, if you are doing some serious stuff you might need pip to install some packages anyway...

**Comment by L4cache** [comment]
The alternative vapoursynth demuxer patch needs rebase by the way, the struct names in allformats.c (from libavformat/internal.h) changed.

**Comment by hydra3333** [comment]
Wondering if it's possible to know whether the alternative demuxer is still applicable ?
I guess since it's building for me now without the patch, I could save and test this version and then if and when the patch is rebased rebuild and test that. Unless someone else has already done it.
Cheers

**Comment by hydra3333** [comment]
Vapoursynth Portable now works great.

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/2cab2de652535fd0191eaa4405862c96cb15275c
