### ISSUE TITLE
FFmpeg 4.x/5.x branch ?

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#2626]
Since I'm running into more and more bugs with FFmpeg 6.x I was wondering whether there was an easy way to use the 5.x FFmpeg branch instead of the 6.x branch?

**Comment by woot000** [comment]
In `build\media_autobuild_suite.ini`, you can append the URL in `ffmpegPath` with a [branch](https://git.ffmpeg.org/gitweb/ffmpeg.git/heads) `#branch=release/4.4` or a [tag](https://git.ffmpeg.org/gitweb/ffmpeg.git/tags) `#tag=n5.1.4`

**Comment by Selur** [comment]
Thanks!
