### ISSUE TITLE
curl: can't read makefile.in

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#2628]
Hi,

perhaps an typo in 32 and 64bit
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14852241/logs.zip)

14:31:59 ┌ curl git  .................................... [Updates found]
14:32:01 ├ Running uninstall...
sed: can't read Makefile.in: No such file or directory
14:32:01 ├ Running autoreconf...
14:32:42 ├ Running configure...
14:36:45 ├ Running make...
14:38:31 ├ Running install...
14:38:49 ├ Running ca-bundle...
14:38:54 ├ Stripping...
14:38:54 └ curl-git  .......................................... [Updated]

there's another issue with ffmpeg (64bit) in these logs

ASopH

**Comment by ASopH** [comment]
Oh, I forgot:

"Makefile.in" is present in directory

**Comment by 1480c1** [comment]
the sed error shouldn't really matter as all it should do is disable building curl.exe the ffmpeg one should be fixed with https://github.com/OpenVisualCloud/SVT-VP9/commit/3b9a3fa43da4cc5fe60c7d22afe2be15341392ea
