### ISSUE TITLE
mingw-w64-[i686|x86_64]-llvm-openmp gets removed and re-installed

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2631]
Uninstall-reinstall loop:
[update.stripped.log](https://github.com/m-ab-s/media-autobuild_suite/files/14890405/update.stripped.log)

**Comment by Biswa96** [comment]
openmp package was renamed to llvm-openmp in this commit https://github.com/msys2/MINGW-packages/commit/df5dc2264055b202ba3572f9caf73218a00b4afb

I am not sure how you ended up in that kind of error. The update went fine in my system.

**Comment by LigH-de** [comment]
I remember there was some manual pacman command to force the installation of a package...

**Comment by 1480c1** [comment]
Probably fixed with https://github.com/m-ab-s/media-autobuild_suite/commit/a93604b85a7ee1cd844efef24e87ad85df5babc9

**Comment by LigH-de** [comment]
It now repeats this:
```
You're missing some packages!
Proceeding with installation...
warning: mingw-w64-i686-llvm-openmp-18.1.3-1 is up to date -- skipping
warning: mingw-w64-x86_64-llvm-openmp-18.1.3-1 is up to date -- skipping
 there is nothing to do
warning: mingw-w64-i686-llvm-openmp-18.1.3-1 is up to date -- skipping
warning: mingw-w64-x86_64-llvm-openmp-18.1.3-1 is up to date -- skipping
 there is nothing to do
error: could not set install reason for package mingw-w64-i686-openmp (could not find or read package)
error: could not set install reason for package mingw-w64-x86_64-openmp (could not find or read package)
```

**Comment by 1480c1** [comment]
I would just recommend removing `/etc/pac-*-extra.pk` and rerunning, it shouldn't cause any issues

**Comment by LigH-de** [comment]
It wants to remove a frightening list of packages ... let's see what happens. If it messes up, I can at least always reinstall from scratch, so no panic.
