### ISSUE TITLE
Looking for MediaInfo.dll

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#2632]
Hi, I see MediaInfo.exe is built, and libMediaInfo is referred to in the compile .sh.

I cannot seem to locate `MediaInfo.DLL` (or libMediaInfo.DLL if that is what it is called) ... advice would be welcomed.

(I wish to make use of code derived from the examples, eg "build\libmediainfo-git\Source\Example\HowToUse_Dll3.py")

Cheers

**Comment by 1480c1** [comment]
I don't think we ever compile it shared, only static.

If you need a dll, you can run
```bash
. /build/media-suite_deps.sh
. /build/media-suite_helper.sh
do_vcs "$SOURCE_REPO_LIBMEDIAINFO" libmediainfo
CFLAGS+=" $($PKG_CONFIG --cflags libzen)" \
    LDFLAGS+=" $($PKG_CONFIG --cflags --libs libzen)"
    do_cmake Project/CMake -DBUILD_ZLIB=off -DBUILD_ZENLIB=off -DBUILD_SHARED_LIBS=ON 
do_ninja
```

I do not know where it will generate the .dll since I haven't run the commands, but you can try to find it using `find . -name "*.dll`

**Comment by 1480c1** [comment]
Closing as an off-topic issue, but you can still use it.
