### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by mwkenna** [m-ab-s/media-autobuild_suite#2634]
I have an issue:

configure: error: TLS not detected, you will not be able to use HTTPS, FTPS, NTLM and more.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14903683/logs.zip)

**Comment by mwkenna** [comment]
I believe this something to do with the use of mbedtls which I have disabled in favor of libtls. It seems to be building now

**Comment by 1480c1** [comment]
duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2627
