### ISSUE TITLE
How to keep the build-shared-64bit folder?

### ISSUE THREAD

**Issue by shizidushu** [m-ab-s/media-autobuild_suite#2637]
Is there an option to keep the  `build\ffmpeg-git\build-shared-64bit` or `build-static-64bit` folder?

I want to run `make install DESTDIR=**` to install it to a custom place so it can be conveniently used as a third party lib for a C++ app.

**Comment by 1480c1** [comment]
You can comment out the line `clean_suite` in `/build/media-suite_compile.sh` near the bottom. Theoretically, just setting `deleteSource` to 2 in your `/build/media-autobuild_suite.ini` file should be good enough
