### ISSUE TITLE
Error running build when update libavif 

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2640]
``` bash
  Running git update for libavif...
┌ libavif git  ........................................... [Updates found]
├ Running uninstall...
├ Installing libjpeg-turbo... done
├ Installing libyuv... done
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
ninja: build stopped: subcommand failed.
[1/2] Linking CXX executable avifenc.exe
FAILED: avifenc.exe
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\MABS\msys64\mingw64\bin\ccache.exe  g++ -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++ CMakeFiles/avifenc.dir/apps/avifenc.c.o CMakeFiles/avifenc.dir/apps/utf8.rc.obj -o avifenc.exe -Wl,--out-implib,libavifenc.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libavif_apps.a  libavif_internal.a  C:/MABS/msys64/mingw64/lib/libyuv.a  -lm  C:/MABS/local64/lib/libdav1d.a  C:/MABS/local64/lib/librav1e.a  C:/MABS/local64/lib/libaom.a  C:/MABS/local64/lib/libpng.a  C:/MABS/msys64/mingw64/lib/libz.a  C:/MABS/msys64/mingw64/lib/libjpeg.a  -lmingwthrd  -lmingwthrd  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/librav1e.a(rav1e.std-8984bea53711d8dc.std.822af3e2effa3d17-cgu.0.rcgu.o.rcgu.o): in function `std::sys::pal::windows::c::NtWriteFile':
/rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys\pal\windows/c.rs:309:(.text+0x1eadc): undefined reference to `NtWriteFile'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/librav1e.a(rav1e.std-8984bea53711d8dc.std.822af3e2effa3d17-cgu.0.rcgu.o.rcgu.o): in function `std::sys::pal::windows::handle::Handle::synchronous_write':
/rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys\pal\windows/handle.rs:314:(.text+0x1eb93): undefined reference to `RtlNtStatusToDosError'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/MABS/build/libavif-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach C:\MABS\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14970484/logs.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/14970486/ab-suite.build.log)

**Comment by kliffgomel** [comment]
same problem
21:58:36 ┌ libavif git  .............................. [Recently updated]
21:58:38 ├ Installing libjpeg-turbo... done
21:58:44 ├ Installing libyuv... done
21:59:47 ├ Running cmake...
22:00:33 ├ Running build...
Likely error (tail of the failed operation logfile):
ninja: build stopped: subcommand failed.
[1/2] Linking CXX executable avifenc.exe
FAILED: avifenc.exe
C:\Windows\system32\cmd.exe /C "cd . && D:\ffmpeg-autobuild\msys64\mingw64\bin\ccache.exe  g++ -fstack-protector-strong -march=znver2 -O3 -pipe -mthreads -O3 -DNDEBUG -pipe -static-libgcc -fstack-protector-strong -static-libstdc++ CMakeFiles/avifenc.dir/apps/avifenc.c.o CMakeFiles/avifenc.dir/apps/utf8.rc.obj -o avifenc.exe -Wl,--out-implib,libavifenc.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libavif_apps.a  libavif_internal.a  D:/ffmpeg-autobuild/msys64/mingw64/lib/libyuv.a  -lm  D:/ffmpeg-autobuild/local64/lib/libdav1d.a  D:/ffmpeg-autobuild/local64/lib/librav1e.a  D:/ffmpeg-autobuild/local64/lib/libaom.a  D:/ffmpeg-autobuild/msys64/mingw64/lib/libpng.a  D:/ffmpeg-autobuild/msys64/mingw64/lib/libz.a  D:/ffmpeg-autobuild/msys64/mingw64/lib/libjpeg.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/librav1e.a(rav1e.std-8984bea53711d8dc.std.822af3e2effa3d17-cgu.0.rcgu.o.rcgu.o): in function `std::sys::pal::windows::c::NtWriteFile':
/rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys\pal\windows/c.rs:309:(.text+0x1eadc): undefined reference to `NtWriteFile'
D:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/ffmpeg-autobuild/local64/lib/librav1e.a(rav1e.std-8984bea53711d8dc.std.822af3e2effa3d17-cgu.0.rcgu.o.rcgu.o): in function `std::sys::pal::windows::handle::Handle::synchronous_write':
/rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys\pal\windows/handle.rs:314:(.text+0x1eb93): undefined reference to `RtlNtStatusToDosError'

**Comment by 1480c1** [comment]
Should be closed with https://github.com/m-ab-s/media-autobuild_suite/commit/c30aef835cebb355584bba4e34a40c790dadcfb8
