### ISSUE TITLE
install_rust failed. Check C:/Builder/Autobuild/build/rustinstall/ab-suite.install_rust.log

### ISSUE THREAD

**Issue by FastError** [m-ab-s/media-autobuild_suite#2657]
Windows 11 pro: curl --version = curl 8.4.0 (Windows) libcurl/8.4.0 Schannel WinIDN
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe /tmp/tmp.QGdQgMqZj2/rustup-init.exe x86_64-pc-windows-gnu
install_rust failed. Check C:/Builder/Autobuild/build/rustinstall/ab-suite.install_rust.log
This is required for other packages, so this script will exit.
----------------
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15159527/logs.zip)
---------
        Starting 64bit compilation of global tools
02:53:04 ├ Running download_rustup...
02:53:04 ├ Running install_rust...
Likely error (tail of the failed operation logfile):
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++
./rustup.sh -v -y --no-modify-path --default-host=x86_64-pc-windows-gnu --default-toolchain=stable
info: downloading installer
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe /tmp/tmp.OwweLSD8pe/rustup-init.exe x86_64-pc-windows-gnu

**Comment by 1480c1** [comment]
try updating and run again https://github.com/m-ab-s/media-autobuild_suite/commit/d1188fa6fa0851a76b64a16c6e9d1a7d9b5eb38c
