### ISSUE TITLE
[clang64] every clang environment packages are recognized as "more than needed"

### ISSUE THREAD

**Issue by L4cache** [m-ab-s/media-autobuild_suite#2666]
This seems to only happen on the first run.
If choose y, it will remove these packages, if choose n it will set these packages to 'installed as dependency', either way, it will then detect missing packages and install mingw64 environment packages. (and these installed mingw64 environment packages will be recognized as "more than needed" in next run)
![2024-05-05_180506](https://github.com/m-ab-s/media-autobuild_suite/assets/42721712/1a743000-0006-4616-aa0e-190e6cf0e313)
[update.log](https://github.com/m-ab-s/media-autobuild_suite/files/15212448/update.log)
[update.stripped-n.log](https://github.com/m-ab-s/media-autobuild_suite/files/15212546/update.stripped-n.log)
[update.stripped-y.log](https://github.com/m-ab-s/media-autobuild_suite/files/15212547/update.stripped-y.log)

**Comment by 1480c1** [comment]
I would recommend going ahead and deleting the msys64 folder and rerunning. I didn't make the transition from mingw64's clang to clang64's environment the cleanest unfortunately.

**Comment by L4cache** [comment]
This happens with fresh install

**Comment by L4cache** [comment]
Github won't let me upload zip files for some reason
[logs.zip.txt](https://github.com/m-ab-s/media-autobuild_suite/files/15234706/logs.zip.txt)
This is taken after choosing not to remove "more than needed" packages, and without any suite's build option enabled

**Comment by L4cache** [comment]
Maybe you can add a separate option to choose between msys2 environments?
I personally revert the related commits and continue to use mingw64 environment even if I use clang as compiler.

**Comment by assy1204** [comment]
cc=1 same error
cc=2 xavs2 error

**Comment by 1480c1** [comment]
I think it has been fixed with https://github.com/m-ab-s/media-autobuild_suite/commit/555a24d0f0f3b76b81e0f8ca06f0419349fce88b and https://github.com/m-ab-s/media-autobuild_suite/commit/4d75ac2ee033048fe9f8960216bd5dc9bbbda6d3, if not, recomment and I can reopen
