### ISSUE TITLE
curl: nonblock.c: In function 'curlx_nonblock': no non-blocking method was found/used/set (GCC 14?)

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2674]
https://github.com/curl/curl/issues/13579
```
  CC       libcurl_la-nonblock.lo
../../lib/nonblock.c: In function 'curlx_nonblock':
../../lib/nonblock.c:82:4: error: #error "no non-blocking method was found/used/set"
   82 | #  error "no non-blocking method was found/used/set"
      |    ^~~~~
make[2]: *** [Makefile:2831: libcurl_la-nonblock.lo] Error 1
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15273830/logs.zip)

**Comment by Fishman0919** [comment]
Same.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15276137/logs.zip)

**Comment by LigH-de** [comment]
Possible reason:

> gcc.exe (Rev2, Built by MSYS2 project) 14.1.0

**Comment by LigH-de** [comment]
https://github.com/curl/curl/commit/4bab28f0661d95bb6421d9ae3630cb1cca2fc487 applied as patch might help?

**Comment by LigH-de** [comment]
Merged upstream.
