### ISSUE TITLE
[HELP/QUESTION] FLAC v1.4.3 / GCC v14.1.0

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2675]
New GCC v14.1.0 is out and i thought i would re-compile FLAC v1.4.3 with it  

Have a 'flac_extra.sh' file with the following contents

#!/usr/bin/bash

_pre_vcs() {
    ref=28e4f0528c76b296c561e922ba67d43751990599
}

The ref hold the correct commit value for v1.4.3

Found flac_extra.sh. Sourcing script...
├ Running pre vcs from flac_extra.sh...
  Running git clone for flac...
fatal: Not a valid object name
  Running git update for flac...
┌ flac git  .............................................. [Updates found]
├ Running autogen...
├ Running uninstall...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ flac-git  .................................................... [Updated]

When i check the complied 'flac.exe' so does it say 'flac 1.4.3' 
but it don't get what the 'fatal: Not a valid object name' is.

Can maybe someone put some light on that?

**Comment by Biswa96** [comment]
'fatal: Not a valid object name' - the error is from git https://stackoverflow.com/questions/36739029/not-a-valid-object-name-master

**Comment by Barough** [comment]
Thanks for the reply Biswa96. I'll have a look there and see if i get any wiser. ;)

**Comment by Biswa96** [comment]
Try to delete the flac source directory (e.g. `rm -rf path/to/flac`) and recompile this project as usual.

**Comment by Barough** [comment]
Just removed the flac-git folder from m-ab-s and restarted the suite

**Comment by L4cache** [comment]
Why not just add the tag name to the link in _deps.sh?

**Comment by Barough** [comment]
> Why not just add the tag name to the link in _deps.sh?

How do it do that?
Im not got at this compiling stuff nor tweaking stuff in m-ab-s.

**Comment by L4cache** [comment]
Add `#tag=1.4.3` or `#tag=LATEST` to the end of the flac's git url

**Comment by Barough** [comment]
Thanks for the info :)

**Comment by Barough** [comment]
Got my FLAC v1.4.3 binaries compiled with GCC v14.1.0 now without no 'fatal' stuff in the log. :)

**Comment by Biswa96** [comment]
Can this issue be closed now?
