### ISSUE TITLE
xavs2 compile err

### ISSUE THREAD

**Issue by mojie126** [m-ab-s/media-autobuild_suite#2677]
![微信截图_20240512233904](https://github.com/m-ab-s/media-autobuild_suite/assets/7426101/b286854f-38ab-4a68-a4b2-d2410828cd24)
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15286856/logs.zip)

**Comment by LigH-de** [comment]
Please do not close your issues before the suggested fixes are commited into the master branch.

**Comment by LigH-de** [comment]
So because it's not officially fixed yet, could you please reopen?

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/101faeaf7c615ec47af1645d1a0f341a7ec0b205
