### ISSUE TITLE
[mingw64] [xavs2 git]

### ISSUE THREAD

**Issue by lopes143** [m-ab-s/media-autobuild_suite#2680]
``` bash
...
libbluray git  .............................................. [Up-to-date]
xavs 0.1  ................................................... [Up-to-date]
  Running git update for xavs2...
┌ xavs2 git  .......................................... [Recently updated]
├ Running uninstall...
├ Running configure...
├ Running install...
Likely error (tail of the failed operation logfile):
      |                                             ^~~~
      |                                             |
      |                                             char **
C:/media-autobuild/build/xavs2-git/source/encoder/parameters.c:531:62: note: expected 'const char * const*' but argument is of type 'char **'
  531 | static char *xavs2_get_configs(int argc, const char * const *argv)
      |                                          ~~~~~~~~~~~~~~~~~~~~^~~~
C:/media-autobuild/build/xavs2-git/source/encoder/parameters.c:626:11: warning: unused variable 'map_index' [-Wunused-variable]
  626 |     int   map_index;
      |           ^~~~~~~~~
make: *** [Makefile:266: encoder/parameters.o] Error 1
install failed. Check C:/media-autobuild/build/xavs2-git/build/linux/ab-suite.install.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach C:\media-autobuild\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15300366/logs.zip)

**Comment by lopes143** [comment]
I applied the patch, but when I run the build script again, it updates the build to the no-patch version. I can't avoid updating the xavs2 build although I marked avs2 as "No" in the initial options.

![parameters.c after patch and before script running](https://github.com/m-ab-s/media-autobuild_suite/assets/120063531/3b0fcae9-7459-4dfb-b233-97cad0fc0434)
![console log after applying patch and running again the script](https://github.com/m-ab-s/media-autobuild_suite/assets/120063531/a3cc5035-cb1d-41b8-a691-6f64a7fbc201)
![parameters.c after running the script - revering the patch](https://github.com/m-ab-s/media-autobuild_suite/assets/120063531/5b6c2ea0-344e-43ee-b2ce-f585b9e7ebfa)

**Comment by lopes143** [comment]
Thank you. It worked

**Comment by piegit** [comment]
> Because ma will check git when compiling Add below this line
> 
> ```c++
>     do_vcs "$SOURCE_REPO_XAVS2"; then
>     do_wget -c -r -q "https://raw.githubusercontent.com/mojie126/ma/main/patch/xavs2/0001_xavs2_encoder_parameters.patch" "0001_xavs2_encoder_parameters.patch"
>     git apply "0001_xavs2_encoder_parameters.patch"
> ```

Where do I put the text?

**Comment by lopes143** [comment]
> > Because ma will check git when compiling Add below this line
> > ```c++
> >     do_vcs "$SOURCE_REPO_XAVS2"; then
> >     do_wget -c -r -q "https://raw.githubusercontent.com/mojie126/ma/main/patch/xavs2/0001_xavs2_encoder_parameters.patch" "0001_xavs2_encoder_parameters.patch"
> >     git apply "0001_xavs2_encoder_parameters.patch"
> > ```
> 
> Where do I put the text?

I can't remember exactly because I had to redownload the suite, bit I think its on `media-suite_compile.sh` under the `build` folder. Find where's the first line and then add the other two down below
