### ISSUE TITLE
Request: libavif - avifenc may support SVT-AV1 encoder in 64-bit build

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2692]
When building libavif, avifenc already gets AOM and rav1e enabled as available AV1 encoders if the suite compiles them. SVT-AV1 may also be supported; but it is only built in the Win64 branch, so adding it to available encoders in avifenc would also only be suitable for its 64-bit version.

**Comment by gitoss** [comment]
It's nice to see all 3 av1 encoders included in libavif through m-a-s.

Is there a comparison of the resulting avif quality anywhere between aom, rav1e and svt anywhere?

Personally, rav1e seems quite competitive visually, but I didn'd do any synthetic benchmarks and didn't chec svt yet.

**Comment by LigH-de** [comment]
The issues tracker is not suitable for discussions. You may like to ask in the doom9 forum instead.
