### ISSUE TITLE
mplayer/mencoder: incompatible to GCC 14 (e.g. constant M_PI undeclared in xvid_vbr)

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2702]
https://trac.mplayerhq.hu/ticket/2423

Suggested patch (complex, WIP) in https://lists.mplayerhq.hu/pipermail/mplayer-dev-eng/2024-April/074173.html

**Comment by LigH-de** [comment]
It remains a major issue.

https://trac.mplayerhq.hu/ticket/2424

**Comment by LigH-de** [comment]
After adding [another patch which defines `M_PI` whereever some math is done](https://trac.mplayerhq.hu/ticket/2423#comment:11), @beastd suggested adding `-lstdc++` to **LDFLAGS**; do you believe thos may be useful? I just don't know how to edit **media-suite_compile.sh** to achieve that, I only see a definition for `--extra-ldflags` which may be something different.

**Comment by LigH-de** [comment]
@1480c1 - any suggestions what to try?

**Comment by 1480c1** [comment]
I wouldn't suggest to directly add `-lstdc++`. I would instead recommend setting the linker to `${CXX}`On Oct 15, 2024, at 04:43, LigH ***@***.***> wrote:﻿
@1480c1 - any suggestions what to try?

**Comment by 1480c1** [comment]
My immediate guess is to add `LD=$CXX` to the `do_configure` line, but since I don't think I compile mplayer, I can't immediately check

**Comment by LigH-de** [comment]
Testing it with a parameter similar to ffmbc: `--ld="$CXX"` ...

**Comment by LigH-de** [comment]
`do_configure LD="$CXX" ...` does not work either:
```
CPPFLAGS: 
CFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -mthreads
CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++
./configure --prefix=/local64 LD=ccache g++ --bindir=/local64/bin-video --extra-cflags=-fpermissive -DPTW32_STATIC_LIB -O3 -DMODPLUG_STATIC -Wno-int-conversion --extra-libs=-llzma -liconv -lws2_32 -lpthread -lwinpthread -lpng -lwinmm -LG:/MABS/local64/lib -lilbc         -LG:/MABS/local64/lib -lvsscript -lpython312 --extra-ldflags=-Wl,--allow-multiple-definition --enable-static --enable-runtime-cpudetection --disable-gif --disable-cddb --disable-faac --with-dvdread-config=/mingw64/bin/pkgconf --keep-system-cflags --static dvdread --with-freetype-config=/mingw64/bin/pkgconf --keep-system-cflags --static freetype2 --with-dvdnav-config=/mingw64/bin/pkgconf --keep-system-cflags --static dvdnav
Unknown parameter: LD=ccache g++
```

**Comment by LigH-de** [comment]
So apparently I misunderstood the instructions?

**Comment by 1480c1** [comment]
Give me a bit to check again, I might have a local checkout somewhere

**Comment by 1480c1** [comment]
```bash

ASFLAGS    = \$(CFLAGS)
AS_DEPFLAGS= $DEPFLAGS
HOSTCC     = \$(HOST_CC)
HOSTCFLAGS = $HOSTCFLAGS
HOSTLIBS   = $libm
AS_O       = -o \$@
CC_O       = $CC_O
CC_LINK_O  = $CC_LINK_O
CXX_O      = -o \$@
AS_C       = -c
CC_C       = -c
CXX_C      = -c
LD         = gcc
RANLIB     = $_ranlib
YASM       = $_yasm
X86ASM     = $_yasm
DEPYASM    = $_yasm
DEPX86ASM  = $_yasm
YASMFLAGS  = $YASMFLAGS
```
based on this, perhaps the linker is hardcoded?

Would you be able to locally patch configure to have `LD         = g++` instead of `LD         = gcc`?

**Comment by 1480c1** [comment]
![image](https://github.com/user-attachments/assets/cf81ebab-e702-42d1-bfed-9ea10a7b4408)
Looks to me that it didn't actually use g++ for linking. You may need to ask mplayer how to do so, since I don't know enough about their build system, nor do I really want to navigate it myself.

**Comment by LigH-de** [comment]
Maybe it helps to read the output of `./configure -help` - attached:

[configure_help.txt](https://github.com/user-attachments/files/17596906/configure_help.txt)

I'll try now to add `-lstdc++` to `--extra-ldflags` because @beastd recommended to

> try to add standard C++ lib to the LDFLAGS

but I don't know how to do that in **media-suite_compile.sh** so literally. So it looks now like:

```
    do_configure --bindir="$LOCALDESTDIR"/bin-video \
    --extra-cflags='-fpermissive -DPTW32_STATIC_LIB -O3 -DMODPLUG_STATIC -Wno-int-conversion' \
    --extra-libs="-llzma -liconv -lws2_32 -lpthread -lwinpthread -lpng -lwinmm $($PKG_CONFIG --libs libilbc) \
        $(enabled vapoursynth && $PKG_CONFIG --libs vapoursynth-script)" \
    --extra-ldflags='-Wl,--allow-multiple-definition -lstdc++' --enable-{static,runtime-cpudetection} \
    --disable-{gif,cddb} "${faac_opts[@]}" --with-dvdread-config="$PKG_CONFIG dvdread" \
    --with-freetype-config="$PKG_CONFIG freetype2" --with-dvdnav-config="$PKG_CONFIG dvdnav" &&
        do_makeinstall && do_checkIfExist
```

**Comment by LigH-de** [comment]
Another attempt: `--extra-ldflags='-Wl,--allow-multiple-definition -Wl,-lstdc++'`

**Comment by 1480c1** [comment]
Can you send your mabs.ini, ffmpeg_options.txt, and mpv_options.txt if you have them? I will try to reproduce the build locally

**Comment by LigH-de** [comment]
The mpv_options.txt should be rather irrelevant... but here are my custom files:

[build.zip](https://github.com/user-attachments/files/17603157/build.zip)

**Comment by 1480c1** [comment]
Looking at it, it seems `r38457` might be the cause.

```diff
$ svn diff -c r38457
Index: configure
===================================================================
--- configure   (revision 38456)
+++ configure   (revision 38457)
@@ -3003,7 +3003,7 @@
 if test "$cc_vendor" = "gnu" ; then
   cflag_check -fno-tree-vectorize && CFLAGS="$CFLAGS -fno-tree-vectorize"
   cflag_check -Wundef && WARNFLAGS="-Wundef $WARNFLAGS"
-  cflag_check -std=gnu99 && WARN_CFLAGS="-std=gnu99 $WARN_CFLAGS"
+  cflag_check -std=c11 && WARN_CFLAGS="-std=c11 $WARN_CFLAGS"
   cflag_check -Wdeclaration-after-statement && WARN_CFLAGS="-Wdeclaration-after-statement $WARN_CFLAGS"
   cflag_check -Wno-pointer-sign && WARN_CFLAGS="-Wno-pointer-sign $WARN_CFLAGS"
   cflag_check -Wdisabled-optimization && WARN_CFLAGS="-Wdisabled-optimization $WARN_CFLAGS"
```

They changed it from `gnu` to just `c`, which disables a lot of the extensions, and one of them happens to be declaring `M_PI` in math.h
```c
#if !defined(__STRICT_ANSI__) || defined(_POSIX_C_SOURCE) || defined(_POSIX_SOURCE) || defined(_XOPEN_SOURCE) || defined(_GNU_SOURCE) || defined(_BSD_SOURCE) || defined(_USE_MATH_DEFINES)
...
#define M_PI		3.14159265358979323846
...
#endif
```

**Comment by LigH-de** [comment]
> After adding [another patch which defines `M_PI` whereever some math is done](https://trac.mplayerhq.hu/ticket/2423#comment:11), ...

... there is still a lot of issues related to the C++ standard version. See my build.zip archive, it contains a media-suite_compile.sh including this patch.

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/e986b33ca115517dc4e48655bb0a9db933619605

**Comment by LigH-de** [comment]
It would be lovely if anyone with a lot of experience regarding the differences between C and C++ could help the mplayer project, because [it is supposed to rely on C and shall avoid C++ as linker](https://trac.mplayerhq.hu/ticket/2423#comment:29).
