### ISSUE TITLE
librist termiate only in 64bit

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#2703]
Hi,

it's only in 64bit:

14:59:09 ┌ librist git  ................................. [Files missing]
14:59:09 ├ Running meson...
14:59:59 ├ Running build...
Likely error (tail of the failed operation logfile):
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: F:/m-a-s/msys64/mingw64/lib/libmbedcrypto.a(entropy_poll.c.obj):(.text+0x43): undefined reference to `BCryptGenRandom'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/12] Generating include/vcs_version.h with a custom command
[2/5] Linking target tools/ristsender.exe
FAILED: tools/ristsender.exe
"gcc.bat"  -o tools/ristsender.exe tools/ristsender.exe.p/ristsender.c.obj tools/ristsender.exe.p/oob_shared.c.obj tools/ristsender.exe.p/srp_shared.c.obj tools/ristsender.exe.p/.._contrib_getopt-shim.c.obj tools/ristsender.exe.p/.._contrib_time-shim.c.obj tools/ristsender.exe.p/.._contrib_pthread-shim.c.obj "-Wl,--allow-shlib-undefined" "-Wl,-O1" "-fstack-protector-strong" "-mtune=generic" "-O2" "-pipe" "-static-libgcc" "-static-libstdc++" "-D_FORTIFY_SOURCE=2" "-fstack-protector-strong" "-mtune=generic" "-O2" "-D__USE_MINGW_ANSI_STDIO=1" "-mthreads" "-Wl,--start-group" "librist.a" "-pthread" "-lws2_32" "F:/m-a-s/msys64/mingw64/lib/libmbedcrypto.a" "-lws2_32" "-liphlpapi" "F:/m-a-s/msys64/mingw64/lib/libcjson.a" "-Wl,--subsystem,console" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: F:/m-a-s/msys64/mingw64/lib/libmbedcrypto.a(entropy_poll.c.obj):(.text+0x43): undefined reference to `BCryptGenRandom'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check F:/m-a-s/build/librist-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
15:00:06   Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15470091/logs.zip)

**Comment by Biswa96** [comment]
This was supposed to be fixed after this commit https://github.com/msys2/MINGW-packages/commit/6ebec37fa54ea6ce0f1a565e7f6b4060034acafb

**Comment by ASopH** [comment]
Ok then I have to be patient :-)

**Comment by Biswa96** [comment]
I just realized that librist is built from source. So, the patch has to be imported to mabs-patches repository. Yeah, _patience_ is all that we need :)

**Comment by ASopH** [comment]
seems to build ...

**Comment by ASopH** [comment]
seems to build ...

**Comment by LigH-de** [comment]
Happens again (or still?) according to #2758

**Comment by LigH-de** [comment]
Strange behaviour...

For a longer time I disabled librist in ffmpeg_options.txt; now I was curious and enabled it again. And ffmpeg built in 32 and 64 bit.

I noticed several "late updated" components being mentioned in the closing console output. So I ran the whole suite again. And this time librist failed in 64 bit with the usual "undefined reference to `BCryptGenRandom'".
