### ISSUE TITLE
Compile svt-av1 before libavif to pick up dependency

### ISSUE THREAD

**Issue by gitoss** [m-ab-s/media-autobuild_suite#2716]
Thankfully, svt-av1 is now enabled in libiv: https://github.com/m-ab-s/media-autobuild_suite/commit/fd4dbf99e420504e7dd745c2c377a1c42d8e1ba4

However, by default svt-av1 is compiled _after_ libavif, i.e. the dependency is only picked up when running media-autobuild_suite.bat for a second time. 

This isn't severe, but it took me a while to realize - so placing svt-av1 _before_ libavif (wherever this is done exactly) would be useful.

**Comment by 1480c1** [comment]
90a968a039
