### ISSUE TITLE
keeps failing at libmediainfo x64 build

### ISSUE THREAD

**Issue by jamiesaun85** [m-ab-s/media-autobuild_suite#2723]
``` bash
Paste output of the suite here
```

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)

**Comment by jamiesaun85** [comment]
┌ mediainfo git  ......................................... [Updates found]
├ Running autogen...
├ Running configure...
Likely error (tail of the failed operation logfile):
checking if ccache g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if ccache g++ static flag -static works... yes
checking if ccache g++ supports -c -o file.o... yes
checking if ccache g++ supports -c -o file.o... (cached) yes
checking whether the ccache g++ linker (C:/ab-suite/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
./configure: line 16929: libzen-config: command not found
./configure: line 17028: libmediainfo-config: command not found
configure: error: libmediainfo configuration is not found
configure failed. Check C:/ab-suite/build/mediainfo-git/Project/GNU/CLI/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach C:\ab-suite\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.


[logs.zip](https://github.com/user-attachments/files/15905372/logs.zip)
[logs.zip](https://github.com/user-attachments/files/15905398/logs.zip)

**Comment by dbyoung720** [comment]
same with me .
It seems to be related to zenlib

**Comment by nero-0** [comment]
It happens to me too.

**Comment by jamiesaun85** [comment]
so what do we do about it? Ive already deleted both folders and ran again, same thing happens. I guess not include them in the build maybe?

**Comment by ls-milkyway** [comment]
> so what do we do about it? Ive already deleted both folders and ran again, same thing happens. I guess not include them in the build maybe?
> 
> Not sure about you guys but I'm on the recent update for 23H2. The one from last week.

nope nothing to do with 23H2...same output on my 22H2.

**Comment by dbyoung720** [comment]
![image](https://github.com/m-ab-s/media-autobuild_suite/assets/11304997/e44a796f-c2cd-4d3d-b575-b19102ed027f)

**Comment by jamiesaun85** [comment]
Thanks man. Unfortunately I have absolutely no idea how to interpret any of that. Even less how to implement it. I just wanted to make one of my softwares use hardware acceleration, and somehow ended up here, thinking this build or suite or whatever it is would make it happen. 

As far as coding, or communicating with a computer in any way, shit I may as well be Zoolander. I am really really goodlooking after all.

Thanks for the help though. Always appreciated

**Comment by L4cache** [comment]
It's the pkgconf can't detect existance of libmediainfo static library. Weird.

**Comment by L4cache** [comment]
But zstd also exists!
Maybe just lack of .pc file for it.
```
$ pkgconf --keep-system-cflags --static --print-errors --exists libmediainfo
Package zstd was not found in the pkg-config search path.
Perhaps you should add the directory containing `zstd.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zstd', required by 'libcurl', not found
```

**Comment by L4cache** [comment]
Makeshift solution: copy libzstd.pc to zstd.pc.
It's in /mingw64(or clang64)/lib/pkgconfig

**Comment by L4cache** [comment]
Maybe we should just disable curl-reader in libmediainfo like this https://github.com/m-ab-s/media-autobuild_suite/issues/2707#issuecomment-2145862504

**Comment by diegocr** [comment]
@L4cache worth a try at least, i can tell i just ran the suite, having seeing the libzen update, and i got no issues at all getting mediainfo.exe compiled.

**Comment by LigH-de** [comment]
> Pkgconf can't detect static libmediainfo because it can't find zstd required by libcurl required by libmediainfo.
> 
> But zstd also exists! (installed via pacman by the suite) ~Maybe just lack of .pc file for it.~ It just looking for `zstd.pc` instead of `libzstd.pc`

Your competence is seriously a win for this project! Thank you for contributing!

**Comment by L4cache** [comment]
> > Pkgconf can't detect static libmediainfo because it can't find zstd required by libcurl required by libmediainfo.
> > But zstd also exists! (installed via pacman by the suite) ~Maybe just lack of .pc file for it.~ It just looking for `zstd.pc` instead of `libzstd.pc`
> 
> Your competence is seriously a win for this project! Thank you for contributing!
> 
> So this is mainly to be solved in the suite, no need to mention it upstream?

Thank you.
Unfortunately I don't know the exact cause...
It could be pkgconf changed behavior or zstd changed it's .pc file name, and all sorts of possibilities.
But yeah, the workaround can be done just in the suite.

Reporting to upstream is, I don't know, maybe after narrowing the possibilities down?

**Comment by L4cache** [comment]
https://github.com/curl/curl/commit/f057de5a1a950a90d1920021db152a4b695f1a8a#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R1562

https://github.com/curl/curl/commit/f057de5a1a950a90d1920021db152a4b695f1a8a#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR606

Curl recently added Requires.private configuring, they use "libzstd" in cmake but "zstd" in autoconf.

Well, I guess, cmake vs. autoconf again? (not really)

**Comment by jamiesaun85** [comment]
Soooo, its fixed now? do i just run it again?

**Comment by hydra3333** [comment]
I deleted the folders for mediainfo, libmediainfo, curl, and re-ran it and ffmpeg built fine.

**Comment by L4cache** [comment]
> Well, that was quick. Solved _soon™_ after MSYS2 updates packages?

Curl in MSYS2 packages is not (and will not be) affected, it's release version and current release is before the addition of Requires.private, and in next release the fix is already there.
