### ISSUE TITLE
mediainfo

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2726]
┌ mediainfo git  ...................................... [Recently updated]
├ Running autogen...
├ Running configure...
Likely error (tail of the failed operation logfile):
checking if ccache g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if ccache g++ static flag -static works... yes
checking if ccache g++ supports -c -o file.o... yes
checking if ccache g++ supports -c -o file.o... (cached) yes
checking whether the ccache g++ linker (D:/MABS-ffmpeg/msys64/mingw32/i686-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
./configure: line 16929: libzen-config: command not found
./configure: line 17028: libmediainfo-config: command not found
configure: error: libmediainfo configuration is not found
configure failed. Check D:/MABS-ffmpeg/build/mediainfo-git/Project/GNU/CLI/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

[logs.zip](https://github.com/user-attachments/files/15937448/logs.zip)

**Comment by L4cache** [comment]
duplicate, #2723
