### ISSUE TITLE
lensfun, ffmpeg: Failing patches

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2727]
```
┌ lensfun git  ........................................ [Recently updated]
0001-CMake-exclude-mingw-w64-from-some-msvc-exclusive-thi.patch
	Patch could not be applied with `git am`. Continuing without patching.
1999.patch
	Patch could not be applied with `git am`. Continuing without patching.
```
```
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to gplv3...
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
	Patch could not be applied with `git am`. Continuing without patching.
```

**Comment by LigH-de** [comment]
Lensfun works.
SVT-VP9 fails still or again. Is #2418 still true that you can use only either libvpx or libsvtvp9? In that case, as VP9 is more or less unimportant already, I would close this issue.

**Comment by 1480c1** [comment]
To be honest on the svt-vp9 patch, I'm not sure if or when svt-vp9 will be put in archive mode like svt-hevc was, so I'm hesitant to really do any updates to it.

**Comment by 1480c1** [comment]
I believe both patches have been rebased for now

**Comment by 1480c1** [comment]
Seems I was wrong on SVT-VP9, I did not test it in conjuction with vvdec
