### ISSUE TITLE
SVT-AV1-git   [local64/lib/libSvtAv1Dec.a ..................... [Not found]]

### ISSUE THREAD

**Issue by deep4x6** [m-ab-s/media-autobuild_suite#2728]
16:49:26 frei0r git  ....................................... [Up-to-date]
16:49:30   Running git update for decklink-headers...
16:49:30 decklink-headers git  ............................. [Up-to-date]
16:49:32   Running git update for libmfx...
16:49:32 libmfx git  ....................................... [Up-to-date]
16:49:34   Running git update for AMF...
16:49:35 AMF git  .......................................... [Up-to-date]
16:49:38   Running git update for gpac...
16:49:38 gpac git  ......................................... [Up-to-date]
16:49:40   Running git update for SVT-HEVC...
16:49:40 SVT-HEVC git  ..................................... [Up-to-date]
16:49:44   Running git update for SVT-AV1...
16:49:44 ┌ SVT-AV1 git  ................................. [Files missing]
16:49:44 ├ Running uninstall...
16:49:44 ├ Running cmake...
16:49:57 ├ Running build...
16:50:13 ├ Running install...
16:50:13 ├ /local64/lib/libSvtAv1Dec.a  ..................... [Not found]
16:50:13 └ SVT-AV1-git  ........................................ [Failed]

Try deleting '/build/SVT-AV1-git' and start the script again.
If you are sure there are no dependencies, <Enter> to continue building.

Close this window if you wish to stop building.

![Screenshot 2024-06-28 165028](https://github.com/m-ab-s/media-autobuild_suite/assets/67199435/089fd490-eac3-49b4-9e01-1e916bdd3164)

[log.zip](https://github.com/user-attachments/files/16028661/log.zip)

**Comment by ls-milkyway** [comment]
> 16:49:26 frei0r git ....................................... [Up-to-date] 16:49:30 Running git update for decklink-headers... 16:49:30 decklink-headers git ............................. [Up-to-date] 16:49:32 Running git update for libmfx... 16:49:32 libmfx git ....................................... [Up-to-date] 16:49:34 Running git update for AMF... 16:49:35 AMF git .......................................... [Up-to-date] 16:49:38 Running git update for gpac... 16:49:38 gpac git ......................................... [Up-to-date] 16:49:40 Running git update for SVT-HEVC... 16:49:40 SVT-HEVC git ..................................... [Up-to-date] 16:49:44 Running git update for SVT-AV1... 16:49:44 ┌ SVT-AV1 git ................................. [Files missing] 16:49:44 ├ Running uninstall... 16:49:44 ├ Running cmake... 16:49:57 ├ Running build... 16:50:13 ├ Running install... 16:50:13 ├ /local64/lib/libSvtAv1Dec.a ..................... [Not found] 16:50:13 └ SVT-AV1-git ........................................ [Failed]
> 
> Try deleting '/build/SVT-AV1-git' and start the script again. If you are sure there are no dependencies, to continue building.
> 
> Close this window if you wish to stop building.
> 
> ![Screenshot 2024-06-28 165028](https://private-user-images.githubusercontent.com/67199435/344143379-089fd490-eac3-49b4-9e01-1e916bdd3164.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzgzNDMsIm5iZiI6MTcxOTU3ODA0MywicGF0aCI6Ii82NzE5OTQzNS8zNDQxNDMzNzktMDg5ZmQ0OTAtZWFjMy00OWI0LTllMDEtMWU5MTZiZGQzMTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDEyMzQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZDk4NjhkMGUwMmY1ZGU4YTQzZmIyZDUyYzgzZWNhNzBkYzFjNTY3NGZjMzBiNGQ1YWNiZDgxZjhjZDA3NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BEhfGHDT3_m-4q_2am_z31Sj_noIupd1HN7hbBdt1SY)
> 
> [log.zip](https://github.com/user-attachments/files/16028661/log.zip)

**Probably** deleted by your antivirus.

**Comment by deep4x6** [comment]
no  i disabled AntiVirus  means excluded for c drive for all sub folder
like  downloads, desktop....
so that's not reason 🥲

**Comment by L4cache** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/8932151c9d2dfed93f9e920d0ecb9edadfb239db
When was the last time you update yout suite?

**Comment by deep4x6** [comment]
yesterday

**Comment by L4cache** [comment]
clearly not.
the modification timestamp of compile.sh in your log.zip is 24 days ago. not yesterday.

**Comment by deep4x6** [comment]
so u mean that i have to install it again with new freshly downloaded
media auto buuld suite.bat

**Comment by deep4x6** [comment]
i mean whole new zip file package from github

**Comment by deep4x6** [comment]
and please explain (you authored the thread ) what it mean
how to update suite 🥲

**Comment by deep4x6** [comment]
Ok, I'll do that. thnks bro for suggestions and helping this to reply
and u r doing great job by providing contribution in such a great project
