### ISSUE TITLE
[clang64] [SoX] undefined pthread symbols referenced by FLAC

### ISSUE THREAD

**Issue by L4cache** [m-ab-s/media-autobuild_suite#2730]
Mingw64 environment don't have this problem.
If I add `-lpthread` to flac.pc Libs.private then the problem is seemingly solved.
```
  CCLD     sox.exe
ld.lld: error: undefined symbol: pthread_mutex_lock
>>> referenced by libFLAC.a(stream_encoder.c.o):(FLAC__stream_encoder_finish)
>>> referenced by libFLAC.a(stream_encoder.c.o):(FLAC__stream_encoder_finish)
>>> referenced by libFLAC.a(stream_encoder.c.o):(FLAC__stream_encoder_finish)
>>> referenced 14 more times

ld.lld: error: undefined symbol: pthread_cond_broadcast
>>> referenced by libFLAC.a(stream_encoder.c.o):(FLAC__stream_encoder_finish)
>>> referenced by libFLAC.a(stream_encoder.c.o):(FLAC__stream_encoder_finish)
```

[logs.zip.txt](https://github.com/user-attachments/files/16098108/logs.zip.txt)
(I don't know why github won't let me upload zip files...)

**Comment by L4cache** [comment]
This is probably introduced by the migration from autotools to cmake.

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/51a599590365386868f7304190d3e64e57e86064

**Comment by 1480c1** [comment]
Possibly the other projects have something else that links pthread for flac, that's my current guess

**Comment by L4cache** [comment]
> Possibly the other projects have something else that links pthread for flac, that's my current guess

That can explain why other tools built successfully in this case, but can't explain the bigger mistery:
Autotools-built flac don't have `-lpthread` in flac.pc too and in the same environment I tested and same SoX code would successfully built.
And the difference (successful or not) in mingw64 and clang64 is also... mind-blowing?

**Comment by 1480c1** [comment]
mingw-w64 gcc implicitly always links pthreads due to needing pthread for some base libraries or something like that

**Comment by L4cache** [comment]
Wow thanks, that's one more mystery solved.
(shame for my lack of knowledge)
