### ISSUE TITLE
mingw64 gpac 2836.patch could not be applied

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2734]
2836.patch could not be applied

10:16:06 ┌ gpac git  ................................. [Recently updated]
2836.patch
        Patch could not be applied with `git am`. Continuing without patching.
10:16:07 ├ Running configure...
10:16:24 ├ Running make...
10:17:19 ├ Running install...
10:17:19 ├ Stripping...
10:17:20 └ gpac-git  .......................................... [Updated]

**Comment by L4cache** [comment]
It was merged, so not gonna cause problem.

**Comment by 1480c1** [comment]
https://github.com/m-ab-s/media-autobuild_suite/commit/5d29600826e02817457688eb6548ff5ea2687e7d
