### ISSUE TITLE
libavif: UNKNOWN exact build version of rav1e in avifenc and avifdec

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2743]
In the latest few builds, about since SVT-AV1 encoder got included (current version is 1.0.4-132b02c), avifenc and avifdec report the following version strings:
```
Version: 1.0.4 (dav1d [dec]:1.4.1-66-g3623543, aom [enc/dec]:3.9.0-146-g4637f5d7, rav1e [enc]:0.7.0 (UNKNOWN), svt [enc]:v2.1.0)
libyuv : available (1887)
```

In an earlier version (e.g. 1.0.4-8db5d51) it was able to report the rav1e version more exactly:
```
Version: 1.0.4 (dav1d [dec]:1.4.0-67-g85a1035, aom [enc/dec]:3.8.1-302-g14010c6f0f, rav1e [enc]:0.7.0 (p20240227))
libyuv : available (1887)
```

May the reason be rather in the suite or upstream? I have a gut feeling it could be related to MSYS2 and suite specific version handling but could be wrong.

**Comment by L4cache** [comment]
```
Version: 1.1.0 (dav1d [dec]:1.4.2-15-g2355eeb, aom [enc/dec]:3.9.1-286-g55740da9, rav1e [enc]:0.7.0 (p20240612-2-ge34e772), svt [enc]:v2.1.2-52-gb13aec2)
libyuv : available (1887)
```
I got no problem...

**Comment by LigH-de** [comment]
Before I built 2-3 days ago, I removed all source and local directories to enforce a complete re-download and re-build of every project supported by the suite. Today I see that some components of avif are already remarkably ahead of mine, so I will try again and check if that flaw was caused in an older source version and fixed now...
