### ISSUE TITLE
[mingw] can clang package installation be moved to clang environment only?

### ISSUE THREAD

**Issue by L4cache** [m-ab-s/media-autobuild_suite#2745]
It's defined globally here
```bat
set mingwpackages=cmake dlfcn libpng nasm pcre tools-git yasm ninja pkgconf meson ccache jq ^
clang gettext-tools
```
Can we move it here?
```bat
if %CC%==clang (
    set "mingwpackages=%mingwpackages% gcc-compat lld"
) else (
    set "mingwpackages=%mingwpackages% binutils gcc"
)
```

Is any "m-ab-s thing" depends on it in mingw env?

**Comment by 1480c1** [comment]
From what I remember, we still need clang in mingw64 envs because of some rust packages like rav1e needing it for compiling their C related stuff. I could be wrong, and it's all been fixed, but I haven't tried it yet.

**Comment by L4cache** [comment]
I'm happy to test it.
It's good to have a clang lying around when doing some thing manually in mintty though, but I guess it's not too much a hassle to manually install it either.
If required by rust is the case, we are installing rust only when necessary now so maybe clang too?

**Comment by L4cache** [comment]
Yes, clang is required by rav1e, dssim and dovi_tool...
