### ISSUE TITLE
mingw64 ffmpeg-git harfbuzz not found using pkg-config

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2748]
10:28:30 ┌ ffmpeg git  ............................... [Recently updated]
10:28:30 ├ Changing options to comply to nonfree...
10:28:37 ├ Compiling static FFmpeg...
10:28:40 ├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -flto -march=alderlake -O3 -pipe -D__USE_MINGW_ANSI_STDIO=1
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -flto -march=alderlake -O3 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-bzlib --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libharfbuzz --enable-libmfx --enable-libopenjpeg --enable-libsoxr --enable-libwebp --enable-libxml2 --enable-libzimg --enable-gpl --enable-avisynth --enable-version3 --enable-librav1e --enable-libsrt --enable-libvmaf --enable-libfribidi --enable-libilbc --enable-libsvthevc --enable-librtmp --enable-openal --enable-libglslang --enable-vulkan --enable-libplacebo --enable-opencl --enable-opengl --enable-gnutls --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --enable-nonfree --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-ID:/ffmpeg_autobuild_suite/local64/include --extra-cflags=-ID:/ffmpeg_autobuild_suite/local64/include/AL --extra-version=ge7d3ff8dcd+2
ERROR: harfbuzz not found using pkg-config

[logs.zip](https://github.com/user-attachments/files/16409133/logs.zip)

**Comment by gaamaaresosa** [comment]
Me too had this issue when building older version n5.1

I disabled libharfbuzz in ffmpeg_options.txt, because I didn't wanted graphical font support
# Zeranoe
--enable-fontconfig
--enable-gnutls
--enable-libass
--enable-libbluray
--enable-libfreetype
#--enable-libharfbuzz
--enable-libmfx
