### ISSUE TITLE
Request: [Description] NDI supported ffmpeg build help

### ISSUE THREAD

**Issue by gaamaaresosa** [m-ab-s/media-autobuild_suite#2752]
Hi,
As on date the need of NDI (Newtek) in ffmpeg is inevitable on multimedia world.
There is no proper stems to include it on this build script.

Very little clue we get on internet also not working straight forward.
Eg one below:
https://forums.vmix.com/posts/m53790-FFmpeg-3-4-w--NDI

Since that was wrote 6 years ago the changes on your script may not working now.
I add the "--enable-libndi_newtek" option inside ffmpeg_options.txt 
Then start the media-autobuild_suite.bat file.
Immediately the **"--enable-libndi_newtek"** option is removed from that file.
I follow all the steps said on the above link. But still fails.

Could you please help me with the steps to add NDI option ?
Thanks in advance.

gaamaa

**Comment by 1480c1** [comment]
You would most likely need to remove any mention of `ndi_newtek` and `ndi-newtek` from https://github.com/m-ab-s/media-autobuild_suite/blob/master/build/media-suite_helper.sh#L919 to ensure the options are stripped out. Other than that, I cannot help you as it has been removed from FFmpeg's repo for a while now https://superuser.com/questions/1421395/libndi-newtek-missing-from-ffmpeg.


You would need to find out how to either adapt patches floating online for older FFmpeg version to the latest master branch or settle for compiling with an older FFmpeg. There have been previous attempts, https://github.com/m-ab-s/media-autobuild_suite/issues/2209 and https://github.com/m-ab-s/media-autobuild_suite/issues/1377, but we cannot help you with either option as they are not supported options.

**Comment by gaamaaresosa** [comment]
> You would most likely need to remove any mention of `ndi_newtek` and `ndi-newtek` from https://github.com/m-ab-s/media-autobuild_suite/blob/master/build/media-suite_helper.sh#L919 to ensure the options are stripped out. Other than that, I cannot help you as it has been removed from FFmpeg's repo for a while now https://superuser.com/questions/1421395/libndi-newtek-missing-from-ffmpeg.
> 
> You would need to find out how to either adapt patches floating online for older FFmpeg version to the latest master branch or settle for compiling with an older FFmpeg. There have been previous attempts, #2209 and #1377, but we cannot help you with either option as they are not supported options.

Thanks you so much explain the impossibility.
But I am still unaware why everyone run away from the *****
