### ISSUE TITLE
expected 'x265_picture *' but argument is of type 'x265_picture **'

### ISSUE THREAD

**Issue by hydra3333** [m-ab-s/media-autobuild_suite#2776]
Hello.  Not sure what to do about this one ...

```
11:01:07 ├ Compiling FFmpeg with Vapoursynth R70
11:01:07 ├ FFmpeg will need vapoursynth.dll and vsscript.dll to run using vapoursynth demuxers!
11:01:14   Running git update for ffmpeg...
11:01:20 ┌ ffmpeg git  ............................... [Recently updated]
11:01:20 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
11:01:32 ├ Compiling static FFmpeg...
11:01:34 ├ Running configure...
11:06:39 ├ Running make...
Likely error (tail of the failed operation logfile):
AR      libavfilter/libavfilter.a
CC      libavcodec/libx265.o
src/libavcodec/libx265.c: In function 'libx265_encode_frame':
src/libavcodec/libx265.c:813:59: error: passing argument 5 of 'ctx->api->encoder_encode' from incompatible pointer type [-Wincompatible-pointer-types]
  813 |                                    pic ? &x265pic : NULL, x265pic_lyrptr_out);
      |                                                           ^~~~~~~~~~~~~~~~~~
      |                                                           |
      |                                                           x265_picture **
src/libavcodec/libx265.c:813:59: note: expected 'x265_picture *' but argument is of type 'x265_picture **'
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/libx265.o] Error 1
make failed. Check C:/MABS/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
11:09:13   Creating diagnostics file...
```

[ab-suite.make.log](https://github.com/user-attachments/files/17264770/ab-suite.make.log)
[ab-suite.configure.log](https://github.com/user-attachments/files/17264771/ab-suite.configure.log)

**Comment by hydra3333** [comment]
seems to be the reverse of https://github.com/m-ab-s/media-autobuild_suite/issues/2750

**Comment by GyanD** [comment]
Have sent patch.

**Comment by ycwan** [comment]
Same issue happens to me :

┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
AR      libavfilter/libavfilter.a
CC      libavcodec/libx265.o
src/libavcodec/libx265.c: In function 'libx265_encode_frame':
src/libavcodec/libx265.c:813:59: error: passing argument 5 of 'ctx->api->encoder_encode' from incompatible pointer type [-Wincompatible-pointer-types]
  813 |                                    pic ? &x265pic : NULL, x265pic_lyrptr_out);
      |                                                           ^~~~~~~~~~~~~~~~~~
      |                                                           |
      |                                                           x265_picture **
src/libavcodec/libx265.c:813:59: note: expected 'x265_picture *' but argument is of type 'x265_picture **'
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/libx265.o] Error 1
make failed. Check C:/MABS/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach [logs.zip](https://github.com/user-attachments/files/17265983/logs.zip)\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

**Comment by cantrell216** [comment]
├ Installing zeromq... done
├ Installing ladspa-sdk... done
  Running git update for ffmpeg...
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
AR      libavfilter/libavfilter.a
CC      libavcodec/libx265.o
src/libavcodec/libx265.c: In function 'libx265_encode_frame':
src/libavcodec/libx265.c:813:59: error: passing argument 5 of 'ctx->api->encoder_encode' from incompatible pointer type [-Wincompatible-pointer-types]
  813 |                                    pic ? &x265pic : NULL, x265pic_lyrptr_out);
      |                                                           ^~~~~~~~~~~~~~~~~~
      |                                                           |
      |                                                           x265_picture **
src/libavcodec/libx265.c:813:59: note: expected 'x265_picture *' but argument is of type 'x265_picture **'
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/libx265.o] Error 1
make failed. Check C:/ffmpeg/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach C:\ffmpeg\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

same word for word al most
[ab-suite.configure.log](https://github.com/user-attachments/files/17266585/ab-suite.configure.log)
[ab-suite.make.log](https://github.com/user-attachments/files/17266586/ab-suite.make.log)
[logs.zip](https://github.com/user-attachments/files/17266587/logs.zip)

**Comment by GyanD** [comment]
Patch pushed.

https://github.com/FFmpeg/FFmpeg/commit/099f88b8641dfc299f3896d17d9addc5b9ae7799
