### ISSUE TITLE
mingw64 libjxl bulid failed

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2780]
09:07:39 ┌ libjxl git  ............................... [Recently updated]
09:09:03 ├ Running cmake...
09:09:11 ├ Running build...
Likely error (tail of the failed operation logfile):
[5/23] Linking CXX static library lib\libjxl_extras-internal.a
[6/23] Linking CXX static library lib\libjxl_extras_codec.a
[7/23] Building RC object tools/CMakeFiles/cjpegli.dir/utf8.rc.obj
FAILED: tools/CMakeFiles/cjpegli.dir/utf8.rc.obj
D:\ffmpeg-autobuild\msys64\mingw64\bin\windres.exe -O coff -DFJXL_ENABLE_AVX512=0 -DHWY_STATIC_DEFINE -DJPEGXL_ENABLE_JPEGLI=1 -DJXL_STATIC_DEFINE -DTOOLCHAIN_MISS_ASM_HWCAP_H -DTOOLCHAIN_MISS_SYS_AUXV_H -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -I D:/ffmpeg-autobuild/build/libjxl-git -I D:/ffmpeg-autobuild/build/libjxl-git/third_party/highway -I D:/ffmpeg-autobuild/build/libjxl-git/lib/include -I D:/ffmpeg-autobuild/msys64/mingw64/include -I D:/ffmpeg-autobuild/build/libjxl-git/third_party/-ID:/ffmpeg-autobuild/msys64/mingw64/include -I D:/ffmpeg-autobuild/build/libjxl-git/build-64bit/lib/include  D:/ffmpeg-autobuild/build/libjxl-git/tools/utf8.rc tools/CMakeFiles/cjpegli.dir/utf8.rc.obj
<command-line>: warning: "__DATE__" redefined [-Wbuiltin-macro-redefined]
<command-line>: warning: "__TIMESTAMP__" redefined [-Wbuiltin-macro-redefined]
<command-line>: warning: "__TIME__" redefined [-Wbuiltin-macro-redefined]
D:\ffmpeg-autobuild\msys64\mingw64\bin\windres.exe: can't open file `utf8.manifest': Invalid argument
ninja: build stopped: subcommand failed.
build failed. 

[logs.zip](https://github.com/user-attachments/files/17429678/logs.zip)

**Comment by nikolasr** [comment]
libjxl commit 7b70ef1 is to blame for this.
Quick'n'dirty workaround: 
Switch to stable git branch for libjxl
To do so edit your _media-suite_deps.sh_ in your _build_ dir.
Change 
`SOURCE_REPO_LIBJXL=https://github.com/libjxl/libjxl.git`
to 
`SOURCE_REPO_LIBJXL=https://github.com/libjxl/libjxl.git#branch=v0.11.x `

and try again :-)

**Comment by 1480c1** [comment]
One thing I am interested in is how ` -I D:/ffmpeg-autobuild/build/libjxl-git/third_party/-ID:/ffmpeg-autobuild/msys64/mingw64/include` got in there.

**Comment by 1480c1** [comment]
It seems to be from the patch we add for brotli linking, as removing the patch removes the malformed include directory, but will instead cause linking issues with brotli

**Comment by L4cache** [comment]
Somehow, clang64 environment can successfully build it, mingw64 can't

It not limited to jpegli part but jpegli should be disabled (why don't they just remove it completely?)

**Comment by L4cache** [comment]
Uh, after think it more thoroughly, the jpegli is put in "check list" but is not enabled explicitly, so:

- If we explicit disable it now, if upstream remove it in the future, that will probably result in an extra option not used warning in cmake, not a big deal.

- If we only remove it from "check list" but not explicitly disable it, it will be built by default until upstream remove it.

- If we leave it there, once upstream remove it, there will be Files Missing error in m-ab-s suite.

I think it should be removed from "check list", and probably disable it explicitly (because it will be outdated anyway).

**Comment by nikolasr** [comment]
Well, why not postpone the decision and just change libjxl code to stable git branch by default? Gives us time and does not break anything. With libjxl set to stable everything compiles well for me at MinGW64 - well, mostly, except lebtonica and tesseract, which I also switched to stable git branch to successfully compile ffmpeg on MinGW64. But I think that's a different issue (or not?)  ;-)

**Comment by LigH-de** [comment]
I would be a little bit sad if you disabled JPEGLI because it is just the "perceptual JPEG optimizer" I was looking for as substitute for XAT.com JPEG Optimizer. But of course I could download it from any other location, it was just convenient to have it built *en passant* as part of JPEGXL.

**Comment by L4cache** [comment]
> I would be a little bit sad if you disabled JPEGLI because it is just the "perceptual JPEG optimizer" I was looking for as substitute for XAT.com JPEG Optimizer. But of course I could download it from any other location, it was just convenient to have it built _en passant_ as part of JPEGXL.

It has migrated to it's own repo, so the "as part of JXL" one will be outdated (except security patches, maybe, like [this commit](https://github.com/libjxl/libjxl/commit/9cc451b91b74ba470fd72bd48c121e9f33d24c99))
https://github.com/google/jpegli

I'm not sure if they are going to eventually remove it from libjxl repo, leave it outdated forever, or "sync upstream" (who's upstream now?) someday, just speculating. Removing is the right choice in my opinion.

**Comment by kliffgomel** [comment]
As I can see, the problem has been fixed, the project builds without errors.
