### ISSUE TITLE
FFmpeg fails

### ISSUE THREAD

**Issue by Fishman0919** [m-ab-s/media-autobuild_suite#2781]
11:20:11   Running git update for ffmpeg...
11:20:12 ┌ ffmpeg git  ............................... [Recently updated]
11:20:12 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
11:20:19 ├ Compiling static FFmpeg...
11:20:20 ├ Running configure...
Likely error (tail of the failed operation logfile):
Package '-lwebpmux', required by 'tesseract', not found
Package '-lwebp', required by 'tesseract', not found
Package '-lsharpyuv', required by 'tesseract', not found
ERROR: tesseract not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check F:/MABS/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
11:22:31   Creating diagnostics file...

Attach F:\MABS\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

[logs.zip](https://github.com/user-attachments/files/17445795/logs.zip)

**Comment by nikolasr** [comment]
Yeah, there seems currently to be an issue with upstream leptonica and tesseract.
So, either be patient and wait for a fix or use a quick and dirty workaround by switching tesseract and leptonica to stable git branch.
To do so, edit your media-suite_deps.sh in your build dir:
Change 
`SOURCE_REPO_TESSERACT=https://github.com/tesseract-ocr/tesseract.git`
to 
`SOURCE_REPO_TESSERACT=https://github.com/tesseract-ocr/tesseract.git#branch=5.4.1`

and 
`SOURCE_REPO_LEPT=https://github.com/DanBloomberg/leptonica.git`
to
`SOURCE_REPO_LEPT=https://github.com/DanBloomberg/leptonica.git#tag=1.85.0`

Delete your tesseract-git and leptonica-git folder in your build dir and retry compilation ;-)
Keep in mind, that these are only temporary workarounds, which  you'll need to revert later, when things are fixed finally.

Also take a look at issue #2780 for current problems with libjxl.

**Comment by 1480c1** [comment]
Should have been closed with https://github.com/tesseract-ocr/tesseract/commit/2976eb1678a1c272e8d780f01f3258cb955000a2
