### ISSUE TITLE
mingw64 vulkan-loader build failed

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2797]
Both for clang and gcc compilers

10:13:39 ┌ vulkan-loader git  ........................... [Updates found]
10:13:42 ├ Running uninstall...
10:13:46 ├ Running dependencies...
10:14:02 ├ Installing Vulkan-Headers...
10:14:02 ├ Running uninstall...
10:14:02 ├ Running cmake...
10:14:05 ├ Running build...
10:14:05 ├ Running install...
10:14:06 ├ Building Vulkan-Loader...
10:14:07 ├ Running cmake...
Likely error (tail of the failed operation logfile):
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: D:/ffmpeg-autobuild-clang/msys64/usr/bin/git.exe (found version "2.47.0")
-- The ASM_MASM compiler identification is unknown
-- Found assembler: D:/ffmpeg-autobuild-clang/msys64/clang64/bin/jwasm.exe
-- Found PkgConfig: D:/ffmpeg-autobuild-clang/msys64/clang64/bin/pkgconf.exe (found version "2.3.0")
-- Configuring done (1.8s)
CMake Error: install(EXPORT "VulkanLoaderConfig" ...) includes target "vulkan" which requires target "loader_specific_options" that is not in any export set.
-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

09:44:35 ┌ vulkan-loader git  ........................ [Recently updated]
09:44:38 ├ Running uninstall...
09:44:41 ├ Running dependencies...
09:45:03 ├ Installing Vulkan-Headers...
09:45:03 ├ Running uninstall...
09:45:04 ├ Running cmake...
09:45:05 ├ Running build...
09:45:05 ├ Running install...
09:45:07 ├ Building Vulkan-Loader...
09:45:07 ├ Running cmake...
Likely error (tail of the failed operation logfile):
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: D:/ffmpeg-autobuild/msys64/usr/bin/git.exe (found version "2.47.0")
-- The ASM_MASM compiler identification is unknown
-- Found assembler: D:/ffmpeg-autobuild/msys64/mingw64/bin/jwasm.exe
-- Found PkgConfig: D:/ffmpeg-autobuild/msys64/mingw64/bin/pkgconf.exe (found version "2.3.0")
-- Configuring done (1.1s)
CMake Error: install(EXPORT "VulkanLoaderConfig" ...) includes target "vulkan" which requires target "loader_specific_options" that is not in any export set.
-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
cmake failed. Check D:/ffmpeg-autobuild/build/vulkan-loader-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
[logs.zip](https://github.com/user-attachments/files/17811253/logs.zip)
[logs.zip](https://github.com/user-attachments/files/17811256/logs.zip)

**Comment by LigH-de** [comment]
Same for 32-bit.

[logs.zip](https://github.com/user-attachments/files/17821614/logs.zip) contains all the files from the build-32bit directory to inspect.

**Comment by wesson09** [comment]
Hi, 
I encountered the same error yesterday, but today as of 5 minutes ago the error is gone and compile of Vulkan completed successfully.

**Comment by LigH-de** [comment]
Confirming.

**Comment by kliffgomel** [comment]
fixed
