### ISSUE TITLE
Av1an compile error

### ISSUE THREAD

**Issue by moob158** [m-ab-s/media-autobuild_suite#2803]
Av1an error

![Captura de ecrã 2024-11-26 185504](https://github.com/user-attachments/assets/e0af4054-8182-4562-bf4c-9e577a074997)

**Comment by moob158** [comment]
how to skip av1an compiler? I don't want av1an not need it.

**Comment by 1480c1** [comment]
edit `build\media-autobuild_suite.ini` and set `av1an=` to 2

**Comment by moob158** [comment]
i already have av1an set to 2 but it keeps trying to compile and giving the same error

**Comment by L4cache** [comment]
Should set it to 3 to turn off

**Comment by moob158** [comment]
@L4cache  thank you, work now ;)

**Comment by LigH-de** [comment]
Well, this disables building Av1an.

But it does not fix compiling it. So closing this issue is not useful for all those who would like to have it built.

[Av1an issue 898](https://github.com/master-of-zen/Av1an/issues/898)
