### ISSUE TITLE
libxml2-git Git fetch error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2804]
Likely error (tail of the failed operation logfile):
vcs_fetch
++ git rev-parse --git-dir
+ [[ -f .git/shallow ]]
+ unshallow=
+ git fetch --all -Ppft
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
fatal: expected flush after ref listing
+ git remote set-head -a origin
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
fatal: expected flush after ref listing

[logs.zip](https://github.com/user-attachments/files/17944746/logs.zip)

**Comment by woot000** [comment]
You can replace the URL after `SOURCE_REPO_LIBXML2` in `build/media-suite_deps.sh` with the Github mirror: `https://github.com/GNOME/libxml2.git`

Related: https://status.gitlab.com/
![{06D1D52E-1513-4BC3-8AE6-CAFE18017520}](https://github.com/user-attachments/assets/58be7b19-35ec-4aef-a6e7-5298c926bf75)
https://status.gnome.org/
![{A4DE7BA4-A499-4790-A1BF-A2C4AC3C3947}](https://github.com/user-attachments/assets/f08d63c5-8485-46bd-b819-60e1c224e8c4)
