### ISSUE TITLE
openal-soft / CMake Error

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2805]
┌ openal-soft git  ....................................... [Updates found]
├ Running uninstall...
├ Running cmake...
Likely error (tail of the failed operation logfile):
--
-- Configuring done (33.9s)
CMake Error: install(EXPORT "OpenAL" ...) includes target "OpenAL" which requires target "alsoft.fmt-header-only" that is not in any export set.
CMake Error in CMakeLists.txt:
  export called with target "OpenAL" which requires target
  "alsoft.fmt-header-only" that is not in any export set.

-- Generating done (0.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
cmake failed. Check D:/MABS-ffmpeg/build/openal-soft-git/build-32bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
[logs.zip](https://github.com/user-attachments/files/17969696/logs.zip)

**Comment by kliffgomel** [comment]
I had the same error
[logs.zip](https://github.com/user-attachments/files/17974580/logs.zip)

**Comment by LigH-de** [comment]
Reported upstream: [openal-soft issue 1076](https://github.com/kcat/openal-soft/issues/1076)

**Comment by kliffgomel** [comment]
fixed with commit https://github.com/kcat/openal-soft/commit/c238f733faa828c9efc9edb6f2dbc6888ef6ce49.

**Comment by LigH-de** [comment]
@Barough - confirmed
