### ISSUE TITLE
mingw64 Av1an build failed

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2806]
09:13:12 ┌ Av1an git  ................................ [Recently updated]
09:13:16 ├ Running rust.update...
09:13:24 ├ Running rust.build...
Likely error (tail of the failed operation logfile):
help: consider importing one of these unit variants
   |
1  + use crate::software::scaling::SwsFlags::SWS_ERROR_DIFFUSION;
   |
1  + use ffmpeg_sys_the_third::SwsFlags::SWS_ERROR_DIFFUSION;
   |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `ffmpeg-the-third` (lib) due to 18 previous errors
warning: build failed, waiting for other jobs to finish...

[logs.zip](https://github.com/user-attachments/files/17988376/logs.zip)

**Comment by igorbaryshev** [comment]
same thing here
