### ISSUE TITLE
Clang support

### ISSUE THREAD

**Issue by leavittx** [m-ab-s/media-autobuild_suite#802]
Just wondering, how much effort could it take to switch from mingw/gcc to Clang compiler?
Could it be done by just replacing compiler executable somewhere? (assuming that Clang attempts to copy the command-line options from gcc)
The reason I want it is to have debug symbols in PDB format to use with Visual Studio.

**Comment by wiiaboo** [comment]
Never tried, so no idea if mingw's clang is good at all.
