### ISSUE TITLE
ffmpeg: failed to configure with lensfun

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#911]
ERROR: lensfun not found using pkg-config

https://0x0.st/svJF.zip

**Comment by darrenmarklines** [comment]
Same problem for me, how can I stop the ffmpeg build from including it as I don't need it?

**Comment by schmidthubert** [comment]
Do you already have the recent [glib2 update](https://github.com/jb-alvarado/media-autobuild_suite/issues/908)? Check your msys64/var/log/pacman.log for the update to 2.58.0-2:

`[2018-09-06 14:28] [ALPM] upgraded mingw-w64-x86_64-glib2 (2.58.0-1 -> 2.58.0-2)`

**Comment by darrenmarklines** [comment]
No, the log file shows (2.56.2-1 -> 2.58.0-1)

**Comment by schmidthubert** [comment]
Then you need to wait or quickest way without going to the cmdline insert a
`do_pacman remove glib2` before `do_pacman_install glib2` in the liblensfun routine currently sitting around line 1420 of the script ...

**Comment by schmidthubert** [comment]
Oh, and better remove these files first manually in order to rebuild lensfun lib:
`_check=(liblensfun.a lensfun.pc lensfun/lensfun.h)`

**Comment by darrenmarklines** [comment]
No Luck, same problem. Here is the diagnostic zip. [https://0x0.st/svtu.zip]([https://0x0.st/svtu.zip]).

**Comment by wiiaboo** [comment]
That's not really the right fix. Meson needs to be fixed upstream and then recompiled, along with glib2 also being recompiled for the issue to be fixed.
Meanwhile, just use an older version of glib2 and force pacman to ignore the newer versions.

**Comment by schmidthubert** [comment]
There's this code in the liblens routine:
`grep_or_sed stdc libs/lensfun/lensfun.pc.cmake 's;Libs.private.*;& -lstdc++;`

But there's no Libs.private line in the cmake file ?

**Comment by wiiaboo** [comment]
It doesn't error that far. The errors in the logs are for missing gnulib/charset/etc.

**Comment by schmidthubert** [comment]
Indeed. I've just copied an old libglib2 from around April and ffmpeg compiled fine again. So quite a bunch of stuff is missing then from lastest glib2 (did a check with nm). Where's [@Alexpux](https://github.com/Alexpux) quality control and where's a really stable and usable msys2 tree? :-1:

Anyway, apart from moaning again: even if it compiles fine then using ffmpeg with lensfun (I've used the [official ffmpeg examples](https://ffmpeg.org/ffmpeg-filters.html#Examples-72)) doesn't work in Windows: it's still crashing with an error in ntdll.dll ... :face_with_head_bandage:

**Comment by hydra3333** [comment]
In a separate ffmpeg build system, the equivalent of this
`grep_or_sed stdc libs/lensfun/lensfun.pc.cmake 's;Libs.private.*;& -lstdc++;`
didn't work for me as this file
`libs/lensfun/lensfun.pc.cmake`
did not have a "Libs.private" line; source downloaded from 
`https://downloads.sourceforge.net/project/lensfun/0.3.95/lensfun-0.3.95.tar.gz`
The equivalent of this did work though:
sed -i.bak 's;-llensfun;-llensfun -lstdc++;'
just thought I'd mention it.

**Comment by schmidthubert** [comment]
Yes, it just didn append it because what was searched for wasn't there but that's fixed now. Do the lensfun examples work in rdp's build?

**Comment by hydra3333** [comment]
OK.  I see the line is now 
` grep_or_sed Libs.private libs/lensfun/lensfun.pc.cmake '/Libs:/ a\Libs.private: -lstdc++'`
turning Libs: into Libs.private:

Haven't checked rdp's build system - thanks, I will head on over there to have a peek.  I use a derivative of deadsix27's build script ... a set of comparison timing runs some months ago indicated some ffmpeg.exe audio processing was > 2x quicker than rdp's ffmpeg.exe for the exact same commandline switches - please don't ask me why as I do not know.  There are some comments on that somewhere over at Zeranoe's forum.

**Comment by schmidthubert** [comment]
The question actually is, is there any other crosscompilation ffmpeg build with lensfun which works? 
>turning Libs: into Libs.private:
No, it's appending, Libs stays, has to ...

**Comment by hydra3333** [comment]
OK.  I see your reference to lensfun examples at 
https://ffmpeg.org/ffmpeg-filters.html#Examples-72
so I'll have a look at them.
Thank you !

**Comment by BlackScreen** [comment]
Tried building the suite from scratch - no sucess. It stops at building ffmpeg.
[logs.zip] (https://0x0.st/svli.zip)

**Comment by wiiaboo** [comment]
It won't be fixed until there's glib 2.58.0-3 or 2.58.1-0. Just downgrade glib and add its package to /msys64/etc/pacman.conf in Ignore line until you know there's a newer version.
This can't be done automatically.

**Comment by schmidthubert** [comment]
But then it's still crashing and doesn't work in Windows  ...

**Comment by wiiaboo** [comment]
What do you want me to do? I'm definitely not compiling meson and glib just for a lib to work. Will you?

**Comment by schmidthubert** [comment]
There must be ways to debug this properly, even when the sourcecode from the alltime ripoff asshole clowns from Redmond isn't available? I mean how can it link and then still crash? It is crashes with vapoursynth and it is crashes with lensfun now, that's 2, what's next? I've already asked if it's working with rdp's build, I don't use that anymore, it takes way too much time for a run. Maybe you should remove both vapoursynth and lensfun for now completely because RIGHT NOW there's unfortunately only one thing for sure: they CURRENTLY don't work HERE. Tickets will otherwise only pile up ...

I don't like giving in, ever, in computing. But sometimes it's better to take a step back (first), there's no sledgehammer possible here. You've done all you could so far, thank you! :+1:

**Comment by wiiaboo** [comment]
Maybe they (lensfun, glib, whatever) never thought of it being used statically. Just move to Linux if you want things like this to just work. Most Linux people don't compile things static because it's a waste of space and a security risk.

**Comment by schmidthubert** [comment]
If any program, and ffmpeg devs they do a lot of checking for overruns , fuzzes etc, works under Linux and is 99.999% free of errors and runs error free under Linux, then I actually expect it to crosscompile and RUN under the target as well. If you compile ffmpeg with all options disabled so just the bare minimum and just for instance lensfun enabled and with debug symbols enabled and load that into a debugger then it should be possible to identify (even without ntdll.dll src) where it is crashing exactly. Sure, it could be just opcodes, but that should be close enough to identify the culprit ...

**Comment by wiiaboo** [comment]
Waiting on meson https://github.com/mesonbuild/meson/pull/3939 being merged, new release or new build of meson with backported fix being built by MSYS2 and then glib2 being recompiled in MSYS2 with the fixed meson.

Meanwhile, I'll just disable compilation with lensfun.

**Comment by schmidthubert** [comment]
Interesting read, thanks! :+1:

**Comment by 1480c1** [comment]
It seems that the follow up pr for https://github.com/mesonbuild/meson/pull/3939, https://github.com/mesonbuild/meson/pull/5936 has been merged, it may be possible to try lensfun again

**Comment by kliffgomel** [comment]
The lensfun 0.3.95 compilation was successful for me.
